### ISSUE TITLE
更新之后quickstart serve占用内存过高

### ISSUE THREAD

**Issue by wangweiweiwei** [istoreos/istoreos#1000]
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x]没有类似的issue

### (1) 具体问题

A：更新之后quickstart serve占用内存过高，这两天升级系统之后发现网速急剧变慢，后台页面也不时卡死，发现内存占用过高，排查出quickstart serve占用71%总共内存1024M,1024x0.71=727.04

### (2) 路由器型号和固件版本

A：x84_64。固件版本：iStoreOS 22.03.5 [2023090810](tel:2023090810)

### (3) 详细日志和/或截图

A：
![IMG_5072](https://github.com/istoreos/istoreos/assets/38938115/1f060e52-cd34-4f5b-a009-5c75a2b8f7b2)

**Comment by jjm2473** [comment]
不是quickstart占用的，而是erofs内核模块，升级最新固件就能解决

**Comment by jjm2473** [comment]
你要看内存的实际占用，要用htop命令，然后点下RES列，或者使用top -m命令

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2722/1
