### ISSUE TITLE
关于x86固件缺少rtl8168/rtl8111H 网卡驱动的问题

### ISSUE THREAD

**Issue by everfu** [istoreos/istoreos#1001]
Hi guys,我在软件包无法查找到有关rtl8168/rtl8111H的任何驱动，请问有什么办法可以解决吗？跪求

**Comment by tuntun2019** [comment]
在这里已经关闭的问题单里面搜索，下载手动安装

**Comment by jjm2473** [comment]
8169驱动应该支持这些网卡吧

**Comment by everfu** [comment]
<img width="846" alt="image" src="https://github.com/istoreos/istoreos/assets/74389842/8201d14e-05f9-4df5-ad29-311f8ca1af92">
好想最新的核心与这个不匹配，安装失败

**Comment by everfu** [comment]
最新的iStoreOS 没有内置rtl8168的驱动，我自己编译一直失败，🥹

**Comment by everfu** [comment]
不行，安装好5.10的驱动后，网卡被驱动了，但是接上设备显示无连接

**Comment by tuntun2019** [comment]
安装这里的驱动，https://github.com/istoreos/istoreos/issues/904 ，显示无连接 你检查下线路 下级设备

**Comment by jjm2473** [comment]
r8168是第三方驱动，不是内核自带的，会影响其他网卡，所以不集成了。可以参考楼上自己安装r8168驱动

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2721/1
