### ISSUE TITLE
首页一直提示软件源错误

### ISSUE THREAD

**Issue by lcuwx2016** [istoreos/istoreos#1002]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
首页一直提示软件源错误

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：修改定制源后回滚修改，首页一直提示软件源错误

### (2) 路由器型号和固件版本

A：X86 iStoreOS 22.03.5 2023090112

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/31233561/fde160ca-ae57-460e-b959-e463e512bd44)

![image](https://github.com/istoreos/istoreos/assets/31233561/78fcdee4-2e9f-42b8-94b2-417a22b4842b)

**Comment by lcuwx2016** [comment]
目前只有清华源有这个问题，切换到中国科大源后显示正常

**Comment by jjm2473** [comment]
是清华源返回了403，之后会改变检测方式

**Comment by yangpin97** [comment]
@lcuwx2016 你好，我也遇到了相同的问题，换了很多个国内dns，以及切换不同的软件源，都不行，切终端运行opkg update都是失败的，见下图
![image](https://github.com/istoreos/istoreos/assets/105636974/ac65fd61-65f2-422c-be57-29b5045bc5af)
![image](https://github.com/istoreos/istoreos/assets/105636974/25ed09e8-402d-4b89-a08a-61160c443385)

**Comment by wx2020** [comment]
你这是虚拟机安装的吧，安装的旁路由吗

**Comment by yangpin97** [comment]
是的



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2023年11月29日(周三) 晚上6:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 首页一直提示软件源错误 (Issue #1002)




 
你这是虚拟机安装的吧，安装的旁路由吗

**Comment by wx2020** [comment]
手动设置一下上游dns和网关

**Comment by yangpin97** [comment]
我目前就是这样设置的，网关是主路由，dns是国内的dns114.114.114.114和223.5.5.5



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2023年11月29日(周三) 晚上7:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 首页一直提示软件源错误 (Issue #1002)




 
手动设置一下上游dns和网关

**Comment by yangpin97** [comment]
我进设备底层，用nslookup和dig解析域名都可以正常加载出来。



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2023年11月29日(周三) 晚上7:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 首页一直提示软件源错误 (Issue #1002)




 
手动设置一下上游dns和网关

**Comment by wx2020** [comment]
重装试试吧。。我有也不好说是什么问题。。

**Comment by yangpin97** [comment]
好的，那我试试吧，谢谢



---原始邮件---
发件人: "Wang ***@***.***&gt;
发送时间: 2023年11月29日(周三) 晚上7:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 首页一直提示软件源错误 (Issue #1002)




 
重装试试吧。。我有也不好说是什么问题。。

**Comment by jjm2473** [comment]
@yangpin97 你的配置文件语法都错了吧，恢复出厂设置吧

**Comment by yangpin97** [comment]
@jjm2473 重装了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2720/1
