### ISSUE TITLE
系统升级后DNS报错无法上网

### ISSUE THREAD

**Issue by nickel2023** [istoreos/istoreos#1003]
你好，咨询一个问题。我先把iStore OS现有配置备份，然后选择不保留原来设置重新刷入最新版的iStore OS固件，再上传备份还原配置，我原来的所有配置例如阿里网盘广告屏蔽等配置还能继续保留吗？谢谢！

**Comment by jjm2473** [comment]
你这个问题跟标题有关系吗？

备份的配置包括你在luci界面上的所有配置，但是不包括docker的容器，如果你的docker是在外部硬盘，就不需要担心。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2719/1
