### ISSUE TITLE
r5c用最新版本固件问题

### ISSUE THREAD

**Issue by tianzhu1992** [istoreos/istoreos#1005]
1、wan口和lan后互换了
2、lan口灯不亮

**Comment by jjm2473** [comment]
开机以后看看识别到的型号对不对，是不是R5C

**Comment by jjm2473** [comment]
你是不是混用了不同作者的固件，例如emmc和sd卡分别有两个固件？不同固件的uboot可能不兼容，导致一些问题

**Comment by jjm2473** [comment]
如果你在后台看到的设备型号是R5S，估计就是混用了固件。

还有一种可能性很低的情况，如果你改了硬件，把R5C的ADC电阻调成跟R5S接近，那也会认成R5S，不过一般不会有人这么蛋疼。

**Comment by jjm2473** [comment]
我刚刚测试了R5C刷最新固件，没有问题

**Comment by tianzhu1992** [comment]
确实是我的问题，loader弄错

**Comment by tianzhu1992** [comment]
感谢大佬回复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2717/1
