### ISSUE TITLE
istoreos-23.05 版本同步openwrt官网更新5.15.130这补丁路劲不对

### ISSUE THREAD

**Issue by Dr-chen99** [istoreos/istoreos#1009]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
istoreos-23.05 版本

能不能给我改个5.15.130内核补丁谢谢

我今天尝试升级了130内核这个补丁过不去
这个补丁 https://github.com/istoreos/istoreos/blob/istoreos-23.05/package/network/config/netifd/patches/002-fix-ethtool.patch

5.15.130 system-linux.c  https://wwqk.lanzouq.com/itpMd198o7xi 

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
跟内核无关，这是netifd的补丁，上游好像已经修复了，你可以直接删掉这个补丁文件

**Comment by Dr-chen99** [comment]
> 跟内核无关，这是netifd的补丁，上游好像已经修复了，你可以直接删掉这个补丁文件

好的谢谢解决了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2713/1
