### ISSUE TITLE
X86如何更新版本哇？

### ISSUE THREAD

**Issue by xsj684135** [istoreos/istoreos#1016]
想保留配置更新版本 请问各位大佬们该如何升级？

**Comment by jjm2473** [comment]
直接升级啊，不是有保留配置的选项吗？

**Comment by jjm2473** [comment]
甚至都有在线升级

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2707/1
