### ISSUE TITLE
H69K iStoreOS 关于风扇风速控制的建议

### ISSUE THREAD

**Issue by am3k0** [istoreos/istoreos#1019]
目前H69K使用iStoreOS 风扇控制策略比较简单，仅能控制风扇启停温度
希望可以在启停温度的基础上添加对风扇速度的设置，让散热风扇可以在特定场景下保持较低噪音与较低温度。
多谢大佬

**Comment by jjm2473** [comment]
默认就是按温度自动调节转速的

**Comment by linyang-aivine-ai** [comment]
> 默认就是按温度自动调节转速的

希望可以自己设置启停温度。

**Comment by jjm2473** [comment]
风扇控制里面不行吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2705/1
