### ISSUE TITLE
istoreOS云打印功能

### ISSUE THREAD

**Issue by littleLice** [istoreos/istoreos#1020]
## 云打印功能

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 现在多数的istoreOS适配的设备都有USB，istoreOS能否适配个云打印，文件存储在istoreOS的硬盘，希望可以考虑这个功能。谢谢！

**Comment by jjm2473** [comment]
什么云打印，istore里面有个CUPS插件，看看是不是你要的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2704/1
