### ISSUE TITLE
升级后会修改之前自定义的挂载点名称，统一改为sata*-*

### ISSUE THREAD

**Issue by lcuwx2016** [istoreos/istoreos#1023]
## 1.关于你要提交的问题
升级后会修改之前自定义的挂载点名称，统一改为sata*-*，丢失自定义配置

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：从 22.03.5-2023092209 升级到 22.03.5-2023092815，丢失了原有的自定义挂载点名称，**导致docker无法启动**

### (2) 路由器型号和固件版本

A：X86 22.03.5-2023092815

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/31233561/45bde23d-90e9-4b64-90c3-be44c80be209)
![image](https://github.com/istoreos/istoreos/assets/31233561/429a5284-d3be-46ed-9bf0-ae03a9da602d)
docker 指向的自定义挂载点

**Comment by jjm2473** [comment]
你有配置挂载点吗？如果没配置，那就是自动生成的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2703/1
