### ISSUE TITLE
无法自动挂载NFS 目录，每次重启后需手动重新启用

### ISSUE THREAD

**Issue by lcuwx2016** [istoreos/istoreos#1024]
## 1.关于你要提交的问题
无法自动挂载NFS 目录，每次重启后需手动开关挂载目录重新启用
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：无法自动挂载NFS 目录，每次重启后需手动重新启用

### (2) 路由器型号和固件版本

A：X86 22.03.5 2023092815

### (3) 详细日志和/或截图

A：
NFS 设置里已设置
![image](https://github.com/istoreos/istoreos/assets/31233561/eb653608-c714-4380-92af-8cc0cc931a74)
重启后已挂载文件系统里找不到
![image](https://github.com/istoreos/istoreos/assets/31233561/48efce89-8b21-43db-8547-9f22111d77f1)

**Comment by szkeum** [comment]
系统 启动项 本地启动脚本添加一行格式如下，mount -t nfs 10.10.10.188:/film /mnt/sata1-1/film

**Comment by jjm2473** [comment]
增加延迟时间应该就行了，例如改成10秒

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2702/1
