### ISSUE TITLE
启用/禁用NFS 已挂载的目录时，页面会报错 missing

### ISSUE THREAD

**Issue by lcuwx2016** [istoreos/istoreos#1025]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
启用/禁用NFS 已挂载的目录时，页面会在底部报错 missing，同时页面右上角显示“未保存的配置”

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：启用/禁用NFS 已挂载的目录时，页面会在底部报错 missing，同时页面右上角显示“未保存的配置”

### (2) 路由器型号和固件版本

A：X86 22.03.5 2023092815

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/31233561/41d8e735-989d-4255-97b7-6ed9dd785420)

https://github.com/istoreos/istoreos/assets/31233561/d7f6603c-f85c-4e45-b8c1-c3e54b07a131

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2701/1
