### ISSUE TITLE
AX210网卡不支持吗？

### ISSUE THREAD

**Issue by NEA147** [istoreos/istoreos#1027]
我的设备是x86刷了原生的istoreos 安装了AX210,无线一直显示设备未激活，作为接受端也无法使用。

**Comment by jjm2473** [comment]
固件版本是什么？重启下，然后把内核日志发过来

**Comment by jjm2473** [comment]
哦，你要把热点都删掉才行，Intel的无线网卡只能作为客户端的 https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2699/1
