### ISSUE TITLE
我的zerotier显示运行了，但是无法联网，不知道怎么排除

### ISSUE THREAD

**Issue by taizhourenjia** [istoreos/istoreos#1029]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：安装了zerotier，后台也显示运行了，但是在zerotier显示这台设备离线，我不止到怎么排除故障让他上线。

### (2) 路由器型号和固件版本

A：iStoreOS 22.03.5 2023092815

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
看看ip和路由表是不是都有了

**Comment by jjm2473** [comment]
还有看看系统日志，搜一下zerotier看看有没有报错

**Comment by jjm2473** [comment]
可能只是因为最近墙变高了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2697/1
