### ISSUE TITLE
ZeroTier 无法更改保存NETWORK ID，提示一个或多个必选项值为空！

### ISSUE THREAD

**Issue by vxiaonanv** [istoreos/istoreos#1030]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

2. 详细叙述
#ZeroTier 无法更改保存NETWORK ID，提示一个或多个必选项值为空！
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A： iStoreOS 22.03.5 2023092815

### (3) 详细日志和/或截图

A：
![1696001531092](https://github.com/istoreos/istoreos/assets/146461895/2752de69-7ee8-42d8-9f64-58b2011cdab5)

**Comment by GolemZ2K** [comment]
你是来搞笑的？ 先去注册，得到一个网络ID，填进去，点加号！

**Comment by jjm2473** [comment]
填了以后要点下加号才算完成。

**Comment by vxiaonanv** [comment]
> 填了以后要点下加号才算完成。

我截图错了   填了 点+号 显示这个错误    网络ID注册了

**Comment by vxiaonanv** [comment]
> 我截图错了 填了 点+号 显示这个错误 网络ID注册了

我截图错了 填了 点+号 显示这个错误 网络ID注册了

**Comment by jjm2473** [comment]
不可能的，我昨天还测试了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2696/1
