### ISSUE TITLE
全2.5G环境下，速率不达标问题。已排除硬件问题。

### ISSUE THREAD

**Issue by nanbin6** [istoreos/istoreos#1032]
环境：ESXI 8.0
硬件：TANK D-1581 主板（板载RLT8125B）+ Pcie插槽 i226-V网口
光猫：F4607 2.5G光猫 
宽带：广东电信2000M X-GPON
测速平台：10000.gd.cn/#/speed
iStoreOS 拨号上网

测试结果如下：（全部是直通）
1.全用RTL8125B未使用驱动 下载1300Mbps左右 内网测速1.8G
2.全用RTL8125B并且勾选使用驱动 下载1300Mbps左右 内网测速 2.2G
3.WAN口使用 i226-V，LAN口使用RTL8125。下载1700Mbps左右 内网测速 2.2G
4.全使用i226-V，下载1700Mbps左右 内网测速 2.2G

爱快测速，全i226-V，下载可跑满2300Mbps。

**Comment by nanbin6** [comment]
更换其他OpenWrt固件，已经可以跑满2300Mbps

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2695/1
