### ISSUE TITLE
小米 Ax9000 无法刷机 iStoreOS

### ISSUE THREAD

**Issue by guohongtao0214** [istoreos/istoreos#1034]
小米 Ax9000 无法刷机 iStoreOS
官方文档缺少相应的 bin 包

![image](https://github.com/istoreos/istoreos/assets/38782106/804818e9-7de2-41b4-a18f-1f8f1ea742af)
希望解决一下，照着官方文档买得 Ax9000，现在没法刷机

**Comment by jjm2473** [comment]
是链接的跳转有bug，先用这个链接下载 https://fw.koolcenter.com/Lean/Xiaomi_AX9000/AX9000%E4%B8%8D%E6%AD%BBuboot%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80.txt

**Comment by jjm2473** [comment]
看起来uboot是第三方提供的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2693/1
