### ISSUE TITLE
BCM57810S不支持2.5G速率

### ISSUE THREAD

**Issue by zijieKwok** [istoreos/istoreos#1036]
在EXSi虚拟机上用bcm57810s网卡能识别到2.5G猫棒，单不能用到2.5G速率，只用到1G，如果使用爱快8就能用到2.5G！是否驱动不支持

**Comment by jjm2473** [comment]
这个网卡对应的驱动是什么？执行`lspci -nnk`看看输出

**Comment by zijieKwok** [comment]
Ethernet controller [0200]: Broadcom Inc. and subsidiaries NetXtreme II BCM57810 10 Gigabit Ethernet [14e4:168e] (rev 10)
        DeviceName: pciPassthru0
        Subsystem: Hitachi, Ltd Device [1054:3087]
        Kernel driver in use: bnx2x

**Comment by zijieKwok** [comment]
我试过三张不同品牌的BCM57810只能识别1G的速率，惠普的530FLR，戴尔BCM57810 N20KJ，技嘉GC-MLBZ1-BCM57810的网卡试了几次都是不支持识别猫棒的2.5G速率，我用你们iStoreOS版本已经3年了，现在换了硬件，却不能用到你们的固件，有些失望！现在只能安装其它版本的OpenWrt了！

**Comment by zijieKwok** [comment]
你们的iStoreOS软件包里是有bnx2x，但就是不能用！

**Comment by zijieKwok** [comment]
我用了
iStoreOS 23.05-SNAPSHOT 2023092209
iStoreOS 22.03.5-2023092815-x86-64-squashfs-combined
两个版本都试过了！不能使用

**Comment by zijieKwok** [comment]
[993-bnx2x_warpcore_8727_2_5g_sgmii_txfault.patch](https://github.com/istoreos/istoreos/files/12909047/993-bnx2x_warpcore_8727_2_5g_sgmii_txfault.patch)
是否缺少了这驱动编译代码

**Comment by zijieKwok** [comment]
我用iStoreOS 23.05源码编译了固件，加入[993-bnx2x_warpcore_8727_2_5g_sgmii_txfault.patch](https://github.com/istoreos/istoreos/files/12909047/993-bnx2x_warpcore_8727_2_5g_sgmii_txfault.patch)就支持2.5G速率了！
![猫棒状态](https://github.com/istoreos/istoreos/assets/109743406/381341e2-346b-456b-9ae9-eda7eeedebb8)
![iStoreOS版本](https://github.com/istoreos/istoreos/assets/109743406/5672158a-cb2a-4f44-b79e-b2016c049493)
![iStoreOS网口配置](https://github.com/istoreos/istoreos/assets/109743406/3328c695-1b4e-4941-8c5a-08764608affb)

**Comment by jjm2473** [comment]
谢谢，补丁加上了

**Comment by zijieKwok** [comment]
![20231024050030](https://github.com/istoreos/istoreos/assets/109743406/b20913f0-4a32-43dc-ba8d-e31e189e5bbd)
请教一下这里的版本日期序号怎么添加与修改

**Comment by jjm2473** [comment]
就是版本号，例如r123456或者日期，正常情况下是会自动通过git产生r开头的版本号，可能你的系统缺少git。还有个简单的方法，就是直接写一串字符到`version`文件，例如在源代码目录执行`echo 2023102410 > version`，之后编译出来的固件就会带2023102410这个版本号

**Comment by jjm2473** [comment]
最好还是使用22版分支吧，23版还是之前的测试版本

**Comment by zijieKwok** [comment]
我用23版编译了自己需要的应用在用了，挺好的！

**Comment by zijieKwok** [comment]
你好！再请教你一下，请问编译时怎么把lan端口改为默认eth0

**Comment by jjm2473** [comment]
修改 `/etc/board.d` 里面的 network 相关文件

**Comment by jjm2473** [comment]
具体到源代码位置 `/target/linux/x86/base-files/etc/board.d/99-default_network`

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2691/1
