### ISSUE TITLE
新版istoreos使用时会突然断网甚至会自己重启

### ISSUE THREAD

**Issue by NEA147** [istoreos/istoreos#1038]
我的设备是x86 cpu是1125G4 istoreos版本是22.03.5 2023092815目前最新版
在使用的时候会自己突然断网设备也访问不到，甚至有几次会自己重启。
****
这是一次突然重启的详细日志
****
![image](https://github.com/istoreos/istoreos/assets/72664231/2b108cf2-2e93-40a9-a51c-39cab4fd74cf)
![image](https://github.com/istoreos/istoreos/assets/72664231/7f0a5505-4a45-4b41-be27-9d43a58372c7)
![image](https://github.com/istoreos/istoreos/assets/72664231/72ba0fcd-344d-4925-b503-aab84473cb25)

![image](https://github.com/istoreos/istoreos/assets/72664231/938d9f7a-5eb4-4df6-a7d5-9cc82e238af0)
![image](https://github.com/istoreos/istoreos/assets/72664231/cd7fa526-e71e-493b-99ee-c93bac6ecf8c)
![image](https://github.com/istoreos/istoreos/assets/72664231/23a2d857-b182-4de6-85f4-861c795f9a62)
![image](https://github.com/istoreos/istoreos/assets/72664231/9578f26f-2f71-4b14-8671-3936229a4a0c)
![image](https://github.com/istoreos/istoreos/assets/72664231/f89eaa2c-f23d-4dc0-bf8f-bcc27d321b3e)
![image](https://github.com/istoreos/istoreos/assets/72664231/835ae82e-3167-42a5-a9bf-bd335527e4c0)
![image](https://github.com/istoreos/istoreos/assets/72664231/ad25361c-cc0b-479f-929c-f83f65e82e89)
![image](https://github.com/istoreos/istoreos/assets/72664231/e8f90e04-6834-45cf-a10e-169fb02c3cbd)
![image](https://github.com/istoreos/istoreos/assets/72664231/74f79de0-1053-43cc-9e19-d709b05f2723)
希望解决。

**Comment by jjm2473** [comment]
没有测试机，你可以试试23.05测试固件看有没有问题
 
EFI： https://fw0.koolcenter.com/iStoreOS/alpha/x86_64_efi/istoreos-23.05-SNAPSHOT-2023083016-x86-64-squashfs-combined-efi.img.gz
非EFI https://fw0.koolcenter.com/iStoreOS/alpha/x86_64/istoreos-23.05-SNAPSHOT-2023083016-x86-64-squashfs-combined.img.gz


还可以刷Openwrt官方的22.03固件试试，可能需要自己安装些驱动

**Comment by NEA147** [comment]
> 没有测试机，你可以试试23.05测试固件看有没有问题
> 
> EFI： https://fw0.koolcenter.com/iStoreOS/alpha/x86_64_efi/istoreos-23.05-SNAPSHOT-2023083016-x86-64-squashfs-combined-efi.img.gz 非EFI https://fw0.koolcenter.com/iStoreOS/alpha/x86_64/istoreos-23.05-SNAPSHOT-2023083016-x86-64-squashfs-combined.img.gz
> 
> 还可以刷Openwrt官方的22.03固件试试，可能需要自己安装些驱动

尝试了测试版istoreos23.05的固件之后解决问题了

**Comment by shen-lan** [comment]
我的也是， pve下的istore。昨天又重装了 istore,   看日志依然会偶尔wan接口 down,  up切换， 亚运会看直播  我真是心态爆炸了

**Comment by jjm2473** [comment]
@shen-lan pve直通网卡吗？网卡是什么型号？有没有看最新固件的更新说明？

**Comment by shen-lan** [comment]
@jjm2473 谢谢老哥解答。🤙🤙🤙是pve网卡直通，n5105的工控机，网卡是i225。现在物理机重装的istore, 一天多了没有重启。观察下有重启再反馈

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2689/1
