### ISSUE TITLE
r2s 固件更新失败

### ISSUE THREAD

**Issue by szh811218** [istoreos/istoreos#1039]
r2s 固件更新失败

路由器型号和固件版本

设备型号
FriendlyElec NanoPi R2S
固件版本
iStoreOS 22.03.5 2023082509

使用固件更新功能，更新
istoreos-22.03.5-2023092815-r2s-squashfs.img.gz
重启后还是原来的版本

**Comment by Mioscout** [comment]
0804使用在线更新有同样问题，手动上传固件包更新正常

**Comment by szh811218** [comment]
> 0804使用在线更新有同样问题，手动上传固件包更新正常

我回头试试手动更新

**Comment by awyaya** [comment]
> 0804使用在线更新有同样问题，手动上传固件包更新正常

为什么我手动上传固件包更新也是重启后还是原来的版本

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2688/1
