### ISSUE TITLE
istoreos docker容器访问不了宿主机的服务

### ISSUE THREAD

**Issue by Jeafly** [istoreos/istoreos#1041]
###### (1) 具体问题

A：istoreos docker容器访问不了宿主机的服务，比如nastools无法关联aria2，防火墙通信规则设置了转发ipv4与ipv6从任意区域到任意区域

###### (2) 路由器型号和固件版本

A：设备型号 : FriendlyElec NanoPi R4SE
      固件版本 : iStoreOS 22.03.5 2023092815
      内核版本 : 5.10.176

**Comment by jjm2473** [comment]
你用的什么ip访问宿主？一般用172.17.0.1

**Comment by Jeafly** [comment]
> 你用的什么ip访问宿主？一般用172.17.0.1

127.0.0.1,以往我在armbian上都用的这个，刚刚这个172.17.0.1也试了，不行，容器bridge与host模式都试了，关联不了主机的aria2

**Comment by jjm2473** [comment]
你怎么访问aria2的后台的？用同一个ip

**Comment by Jeafly** [comment]
> 你怎么访问aria2的后台的？用同一个ip

就是宿主机ip+端口，这个Alist插件可以关联宿主机Aria2插件的服务，路由狗也可以关联Docker的Jellyfin，但是docker里的东西貌似关联不上宿主机的东西，如果是容器与容器之间可以

**Comment by jjm2473** [comment]
你有改过防火墙的docker的规则吗？

**Comment by jjm2473** [comment]
防火墙的全局设置里面把“转发”设置为“允许”试试。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2686/1
