### ISSUE TITLE
无法运行nohup命令

### ISSUE THREAD

**Issue by wmxerni** [istoreos/istoreos#1047]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：无法运行nohup命令

### (2) 路由器型号和固件版本

A：R86S      版本22.03.5 2023092815

### (3) 详细日志和/或截图

A：

**Comment by majie1993** [comment]
```bash
opkg update
opkg install coreutils-nohup
```

**Comment by jjm2473** [comment]
楼上正解。openwrt一般都使用procd来启动后台进程，nohup一般用不上。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2680/1
