### ISSUE TITLE
怎么对接 可通讯后备UPS电源? 涉及到市电断了自动关机, 这个关机指令依然是Linux的关机指令?

### ISSUE THREAD

**Issue by gowy222** [istoreos/istoreos#1049]
本地跑docker挂载网盘等... 安全考虑还是上了后备UPS电源。目前设定的是 市电断了 就自动关闭整个设备。
ups使用的软件是installLADIS_Linux_text_x86_64
同时打算用dockerfile折腾一下把这个用docker来部署(给与完整root权限，映射sh bin来调用关机),又涉及到一个root权限问题。能关机？依然是默认/bin/sh?
或者 Istoreos 是基于什么Linux开发的？

-----
同时有点疑问: 

有一个厂房办公室每晚定点断电下班的...对! 强制下班的那种!

istoreos 是否可以做 系统只读区域和配置隔离？ 这样没有UPS，即使意外断电，只要固件+硬件不损坏，市电恢复，能进基本底层系统，再去读取对应配置，初始化系统 和 运行隔离的docker..

**Comment by jjm2473** [comment]
`poweroff`就可以关机了，openwrt都是使用root用户执行，没有权限问题。

现在就是有只读分区的啊，如果配置出现问题或者安装的程序有问题，回复出厂设置就行了，也就是把配置分区格式化掉。

**Comment by jjm2473** [comment]
> 映射sh bin来调用关机

你是不是不了解docker的隔离机制？映射sh能有什么用？就算你能成功执行sh，那也是在容器内。
如果你要调用宿主机的关机命令，需要使用ssh或者其他远程调用宿主的命令，而不是映射sh。或者参考这个文章 https://stackoverflow.com/questions/42660690/is-it-possible-to-shut-down-the-host-machine-by-executing-a-command-on-one-of-it

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2677/1
