### ISSUE TITLE
升级系统到22.03.5 2023092815后，同一网络下的docker容器之间无法ping通

### ISSUE THREAD

**Issue by fujie-xiyou** [istoreos/istoreos#1053]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：升级系统后 docker容器之间无法ping通 确认是在同一个docker网络下 ，尝试重启系统无法解决

### (2) 路由器型号和固件版本

A：x86_64  固件版本 iStoreOS 22.03.5 2023092815

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/23140941/a2ae910b-8da2-417e-a059-283bbbc82ac9)

![image](https://github.com/istoreos/istoreos/assets/23140941/7fb267b1-e1d1-4941-95c9-f64153de175e)

**Comment by fujie-xiyou** [comment]
系统日志里面也有很多docker相关的 
![image](https://github.com/istoreos/istoreos/assets/23140941/6159f305-1fd4-47db-b42e-7d6d5b3b8ee6)

**Comment by fujie-xiyou** [comment]
![image](https://github.com/istoreos/istoreos/assets/23140941/6f042244-6092-45e2-9853-65a24d3e9fbb)
对应的docker网络配置

**Comment by jjm2473** [comment]
防火墙的全局设置里面把“转发”设置为“允许”试试。或者将实际的接口名称加入到防火墙的docker区域。

你这个情况是因为自己添加的docker网络，默认docker网络桥都会经过防火墙，如果没配置桥内允许转发，防火墙的全局设置默认又是禁止转发的，那就没法互通了。

**Comment by fujie-xiyou** [comment]
感谢！全局设置里面允许转发之后确实可以了，但是比较奇怪为啥升级系统会导致这个问题呀  升级之前确认是好的

**Comment by jjm2473** [comment]
因为以前21版本的固件还是使用docker自带的防火墙，docker会打开自己创建的桥的内部的转发。但是docker自带防火墙功能是不安全的，不遵守openwrt系统防火墙的规则，会把所有容器的服务开放到公网，所以22版本以后禁用了docker的防火墙，转为使用openwrt的防火墙，但是只有docker0才加入系统防火墙，也就是默认的docker网络是可以桥转发的，其他自定义的docker网络需要自己添加到防火墙列表，或者全局允许转发。

不过今天发布的固件已经把桥过滤也关掉了，之后就算不允许全局转发也没问题，详情看更新日志。

**Comment by fujie-xiyou** [comment]
> 因为以前21版本的固件还是使用docker自带的防火墙，docker会打开自己创建的桥的内部的转发。但是docker自带防火墙功能是不安全的，不遵守openwrt系统防火墙的规则，会把所有容器的服务开放到公网，所以22版本以后禁用了docker的防火墙，转为使用openwrt的防火墙，但是只有docker0才加入系统防火墙，也就是默认的docker网络是可以桥转发的，其他自定义的docker网络需要自己添加到防火墙列表，或者全局允许转发。
> 
> 不过今天发布的固件已经把桥过滤也关掉了，之后就算不允许全局转发也没问题，详情看更新日志。

明白了！多谢解答！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2674/1
