### ISSUE TITLE
升级到2023092815，接入USB 绿联8156网卡（2.5G）问题

### ISSUE THREAD

**Issue by kenanadm2000** [istoreos/istoreos#1059]
最新版本的iStoreOS，刷的X86软路由，USB3.0口接入USB 绿联8156网卡（2.5G），在网口配置中可以看到新增的eth接口，但是网线接上后灯都不亮，电脑显示也是无连接状态

**Comment by kenanadm2000** [comment]
已解决

**Comment by fujie-xiyou** [comment]
> 已解决

请教下怎么解决的，我也遇到了类似的问题 usb网卡配置中能看到 但是电脑没网络

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2671/1
