### ISSUE TITLE
R4SE企业版，拔电源重启会跟openclash冲突，导致DNS错误上不了网

### ISSUE THREAD

**Issue by mykev** [istoreos/istoreos#1060]
具体问题

A：目前刷了0825固件和0928最新的固件，拔电源断电重启会跟openclash冲突，显示DNS错误，上不了网，但是在固件界面软重启就一切正常。

openclash 不启用的话也没事

路由器型号和固件版本

A：R4SE 4G  #企业版，固件没有用TF卡，直接刷在内置存储里。

![image](https://github.com/istoreos/istoreos/assets/88918861/27635f57-4cc7-47ad-9910-7ced738c7953)

**Comment by jjm2473** [comment]
麻烦反馈给openclash，很明显是软件bug。
