### ISSUE TITLE
23.05最新固件安装后反复重启

### ISSUE THREAD

**Issue by fly127** [istoreos/istoreos#1064]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：23.05最新9月22日的固件,刷机后进入反复重启状态,无法进入系统, 此前8月22日的固件不存在此问题.

### (2) 路由器型号和固件版本

A：X86--N5000 cpu    固件版本: [istoreos-23.05-SNAPSHOT-2023092209-x86-64-squashfs-combined.img.gz]

### (3) 详细日志和/或截图

A：无

**Comment by jjm2473** [comment]
不要使用23.05，这个只是测试固件，只是为了支持N100以上的核显才发的测试版本。请使用正式版固件。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2669/1
