### ISSUE TITLE
x86硬盘休眠挂了

### ISSUE THREAD

**Issue by sunqin0310** [istoreos/istoreos#1066]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图
![48e07bd7415d81a0fe5534363438d84](https://github.com/istoreos/istoreos/assets/139628049/73258486-14d6-4b46-92e3-64c26b44ff81)

x86硬盘休眠挂了，报错，进不去
win server2022 hyper-v环境
最近两版都是，

**Comment by jjm2473** [comment]
istore里面卸载重装这个插件试试

**Comment by jjm2473** [comment]
已确认插件没问题。可能是因为你是在老版本的固件安装的插件，现在不兼容了，从istore卸载重装就行了。

**Comment by sunqin0310** [comment]
![f796a632b9dbf2c0b2a7fa113b7b828](https://github.com/istoreos/istoreos/assets/139628049/c93caa75-d052-41e2-b8aa-e471bdf2295f)
问题依旧，我装的就是目前最新的x86固件，新开的虚拟机，测试的，无论是软件包下载重装，还是istor下载重装，均是这个提示，不存在老版本的问题，我也不清楚是为什么，我只是找固件的时候测试出来的，希望对你们有帮助
![87e106ad6980fdd18dcf8901310870f](https://github.com/istoreos/istoreos/assets/139628049/267b7a7e-8cd8-4d9e-b836-4fca104c2021)

**Comment by jjm2473** [comment]
你用的是什么浏览器？有没有试过chrome？

**Comment by sunqin0310** [comment]
你们这可真神奇，我主用edge浏览器，刚下载了个谷歌浏览器，进去重新安装还是不行，然后我用手机的uc浏览器进去重新下载试试，天，他居然好了，能进去了，回来又用edge和谷歌也能进去了，用edge重新安装也可以进去了，好神奇，用uc进去重新下载前，提示的是已损坏，然后卸载重新安装就可以了，

**Comment by jjm2473** [comment]
可能是某个硬盘有问题，看代码是硬盘信息某个字段为null才会导致这个错误。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2627/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2667/1
