### ISSUE TITLE
USB口2.5g网卡问题

### ISSUE THREAD

**Issue by kenanadm2000** [istoreos/istoreos#1067]
X86软路由刷的22.03.5 2023102014版本，有如下几个问题
1：软路由的2个USB3.0接口接了2个USB绿联2.5G网卡，一个接WAN一个接LAN，每次重启路由器，2个端口就会自动对换，需要登陆路由端口设置一下才能工作，每次重启都会发生
2：重启路由后，安装的阿里云盘WebDAVv2.2.2就会无法启动，需要更换一个新的监听端口号才能恢复正常
3：状态-概览中的内存，经常出现内存占用99%的情况（大部分都显示为已缓冲），但是首页里面显示占用却很低，不影响上网，但是不知会不会影响其他的，只能重启后才恢复正常，但过一段时间又是99%了

**Comment by jjm2473** [comment]
你的两个USB网卡每次重启都会交换一次？USB网卡一般是按驱动注册的顺序产生网口名称的，网口名称变化只能说明每次启动先发现的USB设备都不一样。如果你要固定网口名称，只能参考arm平台的init脚本，例如 https://github.com/istoreos/istoreos/blob/f17a656f81281b611110ef8580876132175d150b/target/linux/rockchip/rk35xx/base-files/lib/board/init.sh ，注意其中的 board_fixup_iface_name 函数。

阿里云盘WebDAV每次重启端口号都变成默认吗？

用free命令看看内存占用，‘已缓冲’本来就是计为可用内存的。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2666/1
