### ISSUE TITLE
R5s opkg 搜不到netadata（mac timemachaine的软件）有大佬有安装方法吗 或者编译好的插件 也希望官方未来可以加入到商店

### ISSUE THREAD

**Issue by DemonJimmy** [istoreos/istoreos#1069]
如题

**Comment by jjm2473** [comment]
什么netdata，netdata是系统状态监控软件。你说的是netatalk吧。

现在其实已经不需要使用netatalk了，samba就支持timemachaine功能。

**Comment by DemonJimmy** [comment]
是吗 但是怎么操作啊 我打开了samba 但是没有发现timemachine的文件 是需要磁盘格式化成AFP+吗

**Comment by jjm2473** [comment]
@DemonJimmy 不需要格式化，samba配置页面勾选“启用 macOS 兼容共享“，然后添加的共享文件夹勾选”Apple Time-machine 共享“。

samba都有网页界面的了，还要人教？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2664/1
