### ISSUE TITLE
N100硬解 每次都需要开机后执行 chmod 777 /dev/dri/* Emby 转码才看得到转码器

### ISSUE THREAD

**Issue by blankhang** [istoreos/istoreos#1070]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述

建议直接给这个目录下的设备 777 的权限
我现在是加在开机启动脚本里面

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
你的emby容器有添加特权吗？如果不知道怎么搞，就参考jellyfin的部署方式。

**Comment by whale-fall-wh** [comment]
同样的问题， 楼主解决了吗？ 给了777权限后， 正常，重启后， 777权限又掉了，需要重新给权限

**Comment by blankhang** [comment]
> 同样的问题， 楼主解决了吗？ 给了777权限后， 正常，重启后， 777权限又掉了，需要重新给权限

你把给权限的写个脚本放开机启动里面。。。只能这样了 他们不打算改的样子。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2663/1
