### ISSUE TITLE
ARS2历史更新日志中的more链接失效

### ISSUE THREAD

**Issue by LeungKowk** [istoreos/istoreos#1071]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：ARS2更新日志中的more链接失效，跳转到https://fw2.koolcenter.com:5000/iStoreOS/ars2，页面报404
B：正确应该为https://fw.koolcenter.com/iStoreOS/ars2/

### (2) 路由器型号和固件版本

A：ARS2 21.02.3 r16951

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/24469688/83ff23c7-35c9-4493-8cb6-27a6e278a075)

![image](https://github.com/istoreos/istoreos/assets/24469688/8c43eaed-3557-4b7f-bb5c-bfc98922c34c)

**Comment by jannson** [comment]
已修复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2662/1
