### ISSUE TITLE
插件Heimdall和可道云不兼容，请务必抓紧时间解决

### ISSUE THREAD

**Issue by jimdengdev** [istoreos/istoreos#1072]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
插件Heimdall和可道云有冲突，请务必抓紧时间解决

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：istore先安装可道云插件后再安装Heimdall有冲突，导致Heimdall和可道云均不可用，需要两者卸载干净才能解决，对用户影响极大，请务必抓紧时间解决

### (2) 路由器型号和固件版本

A：最先版本固件

### (3) 详细日志和/或截图

A：安装Heimdall后Heimdall打不开，可道云崩溃
<img width="1466" alt="image" src="https://github.com/istoreos/istoreos/assets/35894046/a434de67-b273-4e65-a1b9-7ab61490c789">

**Comment by jjm2473** [comment]
这跟固件有什么关系？不是这些软件自身的问题吗

**Comment by wx2020** [comment]
docker 安裝解決此問題

**Comment by jjm2473** [comment]
@wx2020 Heimdall和可道云现在应该都是docker版的，看报错估计是使用的数据库类型有问题，可能要部署mysql容器。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2661/1
