### ISSUE TITLE
N100 CPU  物理机直装 jellyfin硬解码报错

### ISSUE THREAD

**Issue by s949492225** [istoreos/istoreos#1075]
(1) 具体问题

N100 CPU jellyfin硬解码失败

该客户端与媒体不兼容，服务器未发送兼容的媒体格式。

关闭硬解码也报错，报错提示信息是一样的

(2) 路由器型号和固件版本

硬件:畅网P5 N100
固件版本：iStoreOS 22.03.5 2023102014 / LuCI istoreos-22.03 branch git-23.271.10849-b445bc4
内核版本：5.10.176

系统直接装在物理机上的，没有在虚拟机

(3) 详细日志和/或截图
![image](https://github.com/istoreos/istoreos/assets/7496283/ed36fc44-67e5-4fff-a74f-6b3501e79ace)

![image](https://github.com/istoreos/istoreos/assets/7496283/b3a04ffa-51e7-4623-af88-781cfe4ee9e6)

![image](https://github.com/istoreos/istoreos/assets/7496283/5d7c51c2-e2db-475f-961d-ad570b8a0b93)

错误日志
[jellfin.log](https://github.com/istoreos/istoreos/files/13114560/jellfin.log)

**Comment by s949492225** [comment]
看前面bug里有人回退jellyfin 10.8.10 能够解决，但是我回退到这版本后还是不行

**Comment by s949492225** [comment]
如果需要我配合测试，我会尽力帮忙，可以直接给我发邮件，这样我能及时看到
s949492225@gmail.com

**Comment by s949492225** [comment]
我发现是rclone导致文件访问不了，仅供大家参考

**Comment by jjm2473** [comment]
看jellyfin的转码日志，如果是文件无法访问，会直接告诉你的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2659/1
