### ISSUE TITLE
Docker容器 配置为非Port Map时能否允许保留Port字段，仅作为记录当前的实际使用到的接口

### ISSUE THREAD

**Issue by luyufan498** [istoreos/istoreos#1078]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

希望配置Docker时候能够够保留 -p 的配置，即使Dockr 实际上没有使用port映射

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：![image](https://github.com/istoreos/istoreos/assets/6166841/b4e113c3-5eab-492b-b82f-1ff7e9bdf556)
希望能在Docker容器中添加类似的描述字段，即使-p 不生效的， 这样可以通过链接直接跳转到实际使用到的对应端口，方便管理和记忆，目前是空的，也没不能配置

可以看到Unraid是保留了这个描述，方便管理：
![image](https://github.com/istoreos/istoreos/assets/6166841/f1553f3d-7517-41cf-b67d-e1446ddbd2ad)

### (2) 路由器型号和固件版本

A：X86 N100

### (3) 详细日志和/或截图

A：

**Comment by luyufan498** [comment]
此外，使用MACVLAN的时候，点击编辑，是看不到网络的情况的：
![image](https://github.com/istoreos/istoreos/assets/6166841/6b9eaa40-d951-42ff-8e0f-8748f5dcb7df)

**Comment by jjm2473** [comment]
这是docker的限制，不是这个界面的限制。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2657/1
