### ISSUE TITLE
救命啊，docker点了个远程终端，点保存就恢复不到原来的docker啦，有没有办法恢复？在线等。

### ISSUE THREAD

**Issue by szicely** [istoreos/istoreos#1079]
原以为远程终端是连自己的docker的，docker点了个远程终端，点保存就恢复不到原来的docker啦，有没有办法恢复？在线等。
![53c6d0ef-1c9f-4955-bf6c-ca41dff862ca](https://github.com/istoreos/istoreos/assets/140148567/03e59b8d-7281-4260-8196-b61b985be873)
![fd93fff1-d8cc-47db-a831-4bc0fa824c20](https://github.com/istoreos/istoreos/assets/140148567/8c90e848-0c3b-401e-8fc8-02288237a5c7)
现在除了docker状态没启动之外，istoreos网页打开还巨卡。我的机子是j4125.版本是：
设备型号
x86 Generic
固件版本
iStoreOS 21.02.3 2023060914
内核版本
5.4.188

**Comment by szicely** [comment]
docker做过一次目录迁移，移到了一个大的硬盘下的/sata1-4/docker,之前所有配置和容器应该都在这里。我刚看了下，都还在。

**Comment by szicely** [comment]
我试图把远程终端取消，填上docker目录，提示一个或多个必选项值为空保存不了。
![ec28bf7b-86d5-4616-8cdd-a7373d600b62](https://github.com/istoreos/istoreos/assets/140148567/c3d14242-20d8-4208-9c54-62dcd84f0222)

**Comment by szicely** [comment]
可以了，原来把目录填上原来的路径，在右上角会弹出未保存配置，按保存应用就可以了。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2656/1
