### ISSUE TITLE
passwall连接上，但无法上Google，油管

### ISSUE THREAD

**Issue by wssfxtx** [istoreos/istoreos#1082]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [✓ ] 没有类似的issue

### (1) 具体问题

A：passwall连接上节点，passwall页面点击google显示ping值，ip111显示国外IP为代理IP，goole IP不现实,无法上Google，油管

### (2) 路由器型号和固件版本

A：设备型号
FastRhino R66s
固件版本
iStoreOS 22.03.5 2023102711

### (3) 详细日志和/或截图

A：[![piZLJPK.jpg](https://z1.ax1x.com/2023/10/27/piZLJPK.jpg)](https://imgse.com/i/piZLJPK)
[![piZL856.jpg](https://z1.ax1x.com/2023/10/27/piZL856.jpg)](https://imgse.com/i/piZL856)

**Comment by jjm2473** [comment]
可能你用了ipv6，但是节点又不支持ipv6。关掉电脑的ipv6试试，或者关掉软路由的ipv6解析。

**Comment by wssfxtx** [comment]
关掉ipv6还是同样的问题，并且，同样的节点和设置，在r66s下passwall2上，和x86下的passwall都没有问题。

**Comment by jjm2473** [comment]
你把电脑的ipv6关掉试试，然后重连wifi，并且在passwall的基本设置的dns栏，把dns缓存清空
