### ISSUE TITLE
大佬帮忙适配seewo sv21-rk3568，已有设备源码

### ISSUE THREAD

**Issue by blacksamuraiiii** [istoreos/istoreos#1083]
lean大佬已经添加了seewo sv21-rk3568的设备源码，链接：https://github.com/coolsnowwolf/lede/commit/36278047cf24cb58640b3bdddefb9e58a0e6ee05

我用lean大佬的代码可以编译成功，但是添加is的商店和主题后会乱码无法访问，而且显卡也没法驱动（同RK3568的R66s/R68s可以），求大佬帮忙适配下固件，添加显卡支持，跪谢！

**Comment by jjm2473** [comment]
可以pr代码，只要不搞乱代码结构一般都会接受。不过，如果用户量不大我们也不会发布固件或者支持ota的。

**Comment by blacksamuraiiii** [comment]
> 可以pr代码，只要不搞乱代码结构一般都会接受。不过，如果用户量不大我们也不会发布固件或者支持ota的。

多谢大佬，是直接在pull requests里面提交么，其实给我一版代码就行了，其他的我可以自己编译

**Comment by jjm2473** [comment]
这个仓库就是代码啊

**Comment by blacksamuraiiii** [comment]
> 这个仓库就是代码啊

我自己fork了尝试改了之后编译不成功，才求助的==！

**Comment by jjm2473** [comment]
不是热门硬件或厂家合作，我们不提供移植相关的技术支持，有问题自行解决或者找厂商适配，找其他固件开发者pr也可以。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2655/1
