### ISSUE TITLE
有计划支持bpi r3 mini 嘛

### ISSUE THREAD

**Issue by qooke** [istoreos/istoreos#1084]
https://wiki.banana-pi.org/Getting_Started_with_BPI-R3_MINI

**Comment by jjm2473** [comment]
没适配过MediaTek平台，而且也没测试机

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2654/1
