### ISSUE TITLE
修改docker目录后 docker 报错 failed to register layer: operation not supported

### ISSUE THREAD

**Issue by blankhang** [istoreos/istoreos#1085]
### (1) 具体问题

A：
系统盘是1TB的 M2 装完后 我把剩下的空间给扩容了 然后就想把在其他盘的docker给迁移回来
改了目录后 重新拉镜像报错

### (2) 路由器型号和固件版本

A：
INTEL N100  iStoreOS 22.03.5 2023102711

### (3) 详细日志和/或截图
![image](https://github.com/istoreos/istoreos/assets/3981276/c41edaa4-9a56-44ea-b933-6f3719df2a30)
![image](https://github.com/istoreos/istoreos/assets/3981276/bec59069-6fad-4083-b5f0-8a40e679872c)
A：

**Comment by blankhang** [comment]
ps 迁移docker 能不能不要限制/ 根目录。。。

**Comment by jjm2473** [comment]
本来就不能放在根目录啊，就算你扩容了，也要放在/overlay/upper/opt/docker里面。你遇到的这个报错就是因为放在根目录。

**Comment by blankhang** [comment]
为什么非要限制我放根目录？ 做个提示不建议放根目录就可以了吗，实在不能理解 我自己1TB的盘还跑不起docker 我服务器的系统40G都跑的欢

**Comment by jjm2473** [comment]
还有，扩容最好是创建个新分区，这样以后就算不保留配置升级固件，只要再分区到同一个位置，那数据就还在。还有，硬盘的挂载点最好都设置到/mnt里面，避免硬盘没挂载的情况下数据被写到根目录，导致系统配置文件损坏。

**Comment by jjm2473** [comment]
还有docker的数据只能放在ext4等linux的文件系统里，不能放在ntfs或fat之类的文件系统

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2653/1
