### ISSUE TITLE
docker 配置 镜像加速 无效

### ISSUE THREAD

**Issue by 876529270** [istoreos/istoreos#1086]
root@iStoreOS:~# docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: de40ad0
 Kernel Version: 5.10.176
 Operating System: iStoreOS 22.03.5
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.699GiB
 Name: iStoreOS
 ID: 7JM3:N5XA:BMBY:KNWG:SMUW:E5RG:E5CK:UFY6:TWYV:NERU:SL6R:BGH6
 Docker Root Dir: /ext_overlay/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://mirror.baidubce.com/
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

通过 爱快  查看  链接 的地址  是 美国 ip

**Comment by 876529270** [comment]
莫名其妙 有 有效了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2652/1
