### ISSUE TITLE
SyntaxError Failed to execute 'open' on 'XMLHttpRequest': Invalid URL错误

### ISSUE THREAD

**Issue by longaga** [istoreos/istoreos#109]
![6) IERRI~ZSO}F$8_ CXXFP](https://user-images.githubusercontent.com/25930270/166900168-0497b586-88d7-471e-9345-0731aa91db3e.png)
SyntaxError Failed to execute 'open' on 'XMLHttpRequest': Invalid URL错误，触发原因不明，偶尔遇到，刷新后正常

**Comment by jannson** [comment]
感觉是因为某个接口数据量大，然后请求错误了。

**Comment by jannson** [comment]
因为 ubus 承受不了某些大流量的数据导致，做了限制缓解

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3665/1
