### ISSUE TITLE
UPNP 无法自动转发

### ISSUE THREAD

**Issue by bobotm** [istoreos/istoreos#1090]
反馈bug/问题模板，提建议请删除

UPNP 无法自动转发，网心云跑CDN 提示UPNP无法使用，
链接太多无法使用手动映射，希望修复。

**Comment by jjm2473** [comment]
如果网心云直接在网关上跑，那不需要UPNP，有问题问网心云客服

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2649/1
