### ISSUE TITLE
终端无法登陆

### ISSUE THREAD

**Issue by 714625449** [istoreos/istoreos#1092]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
r2s 刷2023102711固件，终端无法登陆 login incorrect, 或者login can't execute “/usr/bin/Zsh” no such file...
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：r2s istoreos 2023102711

### (3) 详细日志和/或截图

A：
Thu Nov  2 12:37:12 2023 daemon.notice ttyd[12726]: HTTP / - 192.168.2.149
Thu Nov  2 12:37:12 2023 daemon.notice ttyd[12726]: HTTP /token - 192.168.2.149
Thu Nov  2 12:37:12 2023 daemon.notice ttyd[12726]:  ++ [wsisrv|7|adopted] (2)
Thu Nov  2 12:37:12 2023 daemon.notice ttyd[12726]: WS   /ws - 192.168.2.149, clients: 1
Thu Nov  2 12:37:12 2023 daemon.notice ttyd[12726]: started process, pid: 15951
Thu Nov  2 12:37:17 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:17:1746] N: lws_libuv_closewsi: [wsisrv|6|adopted]
Thu Nov  2 12:37:17 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:17:1749] N: lws_libuv_closewsi: thr 0: [wsisrv|6|adopted] sa left 2: dyn left: 4 (rk 0)
Thu Nov  2 12:37:17 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:17:1752] N:  -- [wsisrv|6|adopted] (1) 5.056s
Thu Nov  2 12:37:25 2023 auth.info login[15951]: root login on 'pts/0'
Thu Nov  2 12:37:25 2023 daemon.notice ttyd[12726]: process exited with code 1, pid: 15951
Thu Nov  2 12:37:25 2023 daemon.err ttyd[12726]: read_cb: EIO (i/o error)
Thu Nov  2 12:37:25 2023 daemon.notice ttyd[12726]: WS closed from 192.168.2.149, clients: 0
Thu Nov  2 12:37:25 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:25:2618] N: lws_libuv_closewsi: [wsisrv|7|adopted]
Thu Nov  2 12:37:25 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:25:2621] N: lws_libuv_closewsi: thr 0: [wsisrv|7|adopted] sa left 2: dyn left: 3 (rk 0)
Thu Nov  2 12:37:25 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:25:2622] N:  -- [wsisrv|7|adopted] (0) 13.043s
Thu Nov  2 12:37:25 2023 daemon.notice ttyd[12726]:  ++ [wsisrv|8|adopted] (1)
Thu Nov  2 12:37:25 2023 daemon.notice ttyd[12726]: HTTP /token - 192.168.2.149
Thu Nov  2 12:37:25 2023 daemon.notice ttyd[12726]:  ++ [wsisrv|9|adopted] (2)
Thu Nov  2 12:37:25 2023 daemon.notice ttyd[12726]: WS   /ws - 192.168.2.149, clients: 1
Thu Nov  2 12:37:25 2023 daemon.notice ttyd[12726]: started process, pid: 15961
Thu Nov  2 12:37:30 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:30:3937] N: lws_libuv_closewsi: [wsisrv|8|adopted]
Thu Nov  2 12:37:30 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:30:3941] N: lws_libuv_closewsi: thr 0: [wsisrv|8|adopted] sa left 2: dyn left: 4 (rk 0)
Thu Nov  2 12:37:30 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:30:3944] N:  -- [wsisrv|8|adopted] (1) 5.007s
Thu Nov  2 12:37:43 2023 auth.info login[15961]: root login on 'pts/0'
Thu Nov  2 12:37:43 2023 daemon.notice ttyd[12726]: process exited with code 1, pid: 15961
Thu Nov  2 12:37:43 2023 daemon.err ttyd[12726]: read_cb: EIO (i/o error)
Thu Nov  2 12:37:43 2023 daemon.notice ttyd[12726]: WS closed from 192.168.2.149, clients: 0
Thu Nov  2 12:37:43 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:43:1847] N: lws_libuv_closewsi: [wsisrv|9|adopted]
Thu Nov  2 12:37:43 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:43:1849] N: lws_libuv_closewsi: thr 0: [wsisrv|9|adopted] sa left 2: dyn left: 3 (rk 0)
Thu Nov  2 12:37:43 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:43:1851] N:  -- [wsisrv|9|adopted] (0) 17.787s
Thu Nov  2 12:37:43 2023 daemon.notice ttyd[12726]:  ++ [wsisrv|a|adopted] (1)
Thu Nov  2 12:37:43 2023 daemon.notice ttyd[12726]: HTTP /token - 192.168.2.149
Thu Nov  2 12:37:43 2023 daemon.notice ttyd[12726]:  ++ [wsisrv|b|adopted] (2)
Thu Nov  2 12:37:43 2023 daemon.notice ttyd[12726]: WS   /ws - 192.168.2.149, clients: 1
Thu Nov  2 12:37:43 2023 daemon.notice ttyd[12726]: started process, pid: 15982
Thu Nov  2 12:37:48 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:48:3227] N: lws_libuv_closewsi: [wsisrv|a|adopted]
Thu Nov  2 12:37:48 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:48:3230] N: lws_libuv_closewsi: thr 0: [wsisrv|a|adopted] sa left 2: dyn left: 4 (rk 0)
Thu Nov  2 12:37:48 2023 daemon.err ttyd[12726]: [2023/11/02 12:37:48:3233] N:  -- [wsisrv|a|adopted] (1) 5.007s
Thu Nov  2 12:38:05 2023 daemon.notice ttyd[12726]: WS closed from 192.168.2.149, clients: 0
Thu Nov  2 12:38:05 2023 daemon.notice ttyd[12726]: killing process 15982 with signal: 1 (SIGHUP)
Thu Nov  2 12:38:05 2023 daemon.err ttyd[12726]: [2023/11/02 12:38:05:2994] N: lws_libuv_closewsi: [wsisrv|b|adopted]
Thu Nov  2 12:38:05 2023 daemon.err ttyd[12726]: [2023/11/02 12:38:05:2997] N: lws_libuv_closewsi: thr 0: [wsisrv|b|adopted] sa left 2: dyn left: 3 (rk 0)
Thu Nov  2 12:38:05 2023 daemon.err ttyd[12726]: [2023/11/02 12:38:05:3001] N:  -- [wsisrv|b|adopted] (0) 21.969s
Thu Nov  2 12:38:05 2023 daemon.notice ttyd[12726]: process

**Comment by jjm2473** [comment]
重刷或恢复出厂设置

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2647/1
