### ISSUE TITLE
R2S 网口协议无L2TP,安装xl2tpd,ppp-mod-pppol2tp后无法启动

### ISSUE THREAD

**Issue by eddyclay** [istoreos/istoreos#1094]
网口协议中没有L2tp协议
尝试安装软件包 xl2tpd,ppp-mod-pppol2tp
重启路由 然后就无法启动了
硬件是R2s
固件:istoreos-22.03.5-2023102711-r2s-squashfs.img.gz

**Comment by jjm2473** [comment]
我测试了全新系统安装xl2tpd，没任何问题。估计跟安装xl2tpd没什么关系。
你确定不TF卡的兼容性问题吗？R2S对某些TF卡兼容性不好，可能无法软重启，但也不至于无法启动（断电重启肯定可以）

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2645/1
