### ISSUE TITLE
无法连接PPTP VPN该如何解决

### ISSUE THREAD

**Issue by Richard1817** [istoreos/istoreos#1098]
### (1) 具体问题

A：我的windows电脑使用这个路由器，无法使用PPTP，连接公司的VPN

### (2) 路由器型号和固件版本

A：软路由 N100
iStoreOS 22.03.5 2023102711

### (3) 详细日志和/或截图

A：是不是需要打开路由器的PPTP服务，请问如何打开

**Comment by jjm2473** [comment]
打开防火墙设置，在区域lan的右边点“编辑”，在“连接跟踪设置”的“连接跟踪助手”里面选择PPTP看有没有用：
<img width="842" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/038fd23e-6382-4845-96ce-c6e15d09830a">

**Comment by jjm2473** [comment]
测试了没？

**Comment by Richard1817** [comment]
已经不用这个了 刷了op 正常了



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2023年11月10日(周五) 中午11:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 无法连接PPTP VPN该如何解决 (Issue #1098)




 
测试了没？

**Comment by Amoystyle** [comment]
> 打开防火墙设置，在区域lan的右边点“编辑”，在“连接跟踪设置”的“连接跟踪助手”里面选择PPTP看有没有用： <img alt="image" width="842" src="https://user-images.githubusercontent.com/3896703/281649639-038fd23e-6382-4845-96ce-c6e15d09830a.png">

我使用你说的这个确实能成功连上VPN

**Comment by jjm2473** [comment]
新固件会默认打开端口转发助手，但只对新刷机有效，老用户还是按这个方式解决

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2643/1
