### ISSUE TITLE
新版更新后无法登陆 LUCI

### ISSUE THREAD

**Issue by zl3301** [istoreos/istoreos#1099]
11 月 6 日更新固件后，安装adbyby plus就不能登陆后台
显示Bad gateway,
重启docker和uhttpd都无效

**Comment by jjm2473** [comment]
那就卸载插件

**Comment by zl3301** [comment]
卸载嘞也不行，只能firstboot恢复设置

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2642/1
