### ISSUE TITLE
已增加rtw88-oot驱动，支持此网卡

### ISSUE THREAD

**Issue by HLLOUIS** [istoreos/istoreos#1100]
已增加rtw88-oot驱动，支持此网卡

_Originally posted by @jjm2473 in https://github.com/istoreos/istoreos/issues/987#issuecomment-1782241465_
            支持吗？用不了啊！

**Comment by jjm2473** [comment]
什么机型？固件版本是什么？执行`lsusb -tv`看看

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2641/1
