### ISSUE TITLE
增加MT7662驱动

### ISSUE THREAD

**Issue by lff110** [istoreos/istoreos#1101]
可以增加mediatek MT7662(VID_0E8D&PID_7612)的驱动吗？

**Comment by jjm2473** [comment]
不是本来就支持吗 https://github.com/openwrt/mt76/blob/d70546462b7b51ebc2bcdd5c534fdf3465be62a4/mt76x2/usb.c

你的什么机型？

**Comment by jjm2473** [comment]
如果有问题，开机以后，把内核日志提取出来

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2640/1
