### ISSUE TITLE
upnp有问题

### ISSUE THREAD

**Issue by elvellonwg** [istoreos/istoreos#1104]
upnp打开之后 群晖无法识别upnp路由器 别的openwrt系统都没问题  就istoreos的upnp有问题 能付下个版本编译时候换一个upnp版本 不用魔改的这个

**Comment by jjm2473** [comment]
isotoreos也没啥魔改，只是增加了强制转发，还有默认关掉了ipv6

**Comment by jjm2473** [comment]
你试试打开upnp的ipv6支持，也就是执行这段命令：
```bash
uci -q batch <<-EOF >/dev/null
    set upnpd.config.ipv6_disable=1
    commit upnpd
EOF
/etc/init.d/miniupnpd restart
```

**Comment by jjm2473** [comment]
重复 https://github.com/istoreos/istoreos/issues/1018

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2637/1
