### ISSUE TITLE
设置了下主题结果500错误了!!

### ISSUE THREAD

**Issue by w4575421** [istoreos/istoreos#1109]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：设置了下主题结果500错误了!!

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志和/或截图

A：Status: 500 Internal Server Error /usr/lib/lua/luci/template.lua:97: Failed to execute template 'sysauth'. A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'. A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/opentopd/header'. A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/opentopd/head..."]:22: attempt to call field 'node_childs' (a nil value) stack traceback: [string "/usr/lib/lua/luci/view/themes/opentopd/head..."]:22: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function 'render' /usr/lib/lua/luci/dispatcher.lua:699: in function 'include' [string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function 'render' /usr/lib/lua/luci/dispatcher.lua:699: in function 'include' [string "/usr/lib/lua/luci/view/sysauth.htm"]:1: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function (tail call): ? (tail call): ? /usr/lib/lua/luci/dispatcher.lua:482: in function
[img]https://pic.ziyuan.wang/2023/11/14/guest_1a3944151db80.png[/img]

**Comment by jjm2473** [comment]
说明主题不适配22.03

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2632/1
