### ISSUE TITLE
tailscale 组网失败，提示tailscale和tailscaled的版本号不一致

### ISSUE THREAD

**Issue by xmasrain** [istoreos/istoreos#1110]
### (1) 具体问题

A：启动服务时提示：Warning: client version "1.32.3-1 (OpenWrt)" != tailscaled server version "1.52.1-t75d3c9385-g3e9627f3b"

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/58833842/40d4d5b2-7467-46a4-8516-cb5a80ba9f2f)

**Comment by jjm2473** [comment]
卸载重装试试

**Comment by jjm2473** [comment]
istore不是有个tailscale的插件了吗，直接使用插件看看有没有问题

**Comment by xmasrain** [comment]
就是用的插件，后来我按照这个文章《OpenWrt安装配置Tailscale C ZhiYunHaiBo 智云海博 (zyh8.com)<https://www.zyh8.com/archives/135/openwrt%E5%AE%89%E8%A3%85%E9%85%8D%E7%BD%AEtailscale/>》重装了，就好了

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Liangbin ***@***.***>
发送时间: 2023年11月21日星期二 上午10:56
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [istoreos/istoreos] tailscale 组网失败，提示tailscale和tailscaled的版本号不一致 (Issue #1110)


istore不是有个tailscale的插件了吗，直接使用插件看看有没有问题

―

**Comment by Jesn** [comment]
建议官网把Tailscale的版本升级下，Tailscale版本太低了，derp节点会经常报错

**Comment by jjm2473** [comment]
@Jesn tailscale是openwrt仓库提供的，要升级只能反馈给openwrt

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2631/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2631/4
