### ISSUE TITLE
询问一下 PantherX2 应该使用哪个镜像？

### ISSUE THREAD

**Issue by wnpllrzodiac** [istoreos/istoreos#1111]
配置：
处理器: 瑞芯微，RK3566，四核 Cortex-A55 高达 1.8GHz
内存：DDR 4GB
储存：eMMC 32GB+ TF卡64GB
![233834310-b52fa0ce-82b9-4617-aa6d-8b27e3f46620](https://github.com/istoreos/istoreos/assets/6406690/b04e6286-b96e-476b-a595-bd99dbf860b1)

**Comment by jjm2473** [comment]
没适配，也没测试机

**Comment by jjm2473** [comment]
已经有用户pr了代码，可以自己编译。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2630/1
