### ISSUE TITLE
检查更新，提示Curl 60 Error

### ISSUE THREAD

**Issue by cocci810123** [istoreos/istoreos#1112]
检查失败:
% Total
% Received % Xferd Average Speed
Time
Time
Time Current
Dload Upload Total
Spent
Left Speed
O
O
O
100
85 100
85
649
696
O
O
curl: (60) SSL certificateproblem: certificate
has expired
More details here: https://url.se/docs/sslcerts
.html
curl failed to verify the legitimacy of the server
and therefore could not
establish a secure connection to it. To learn
more about this situation and
how to fix it, please visit the web page
mentioned above.

请问这是哪里出的问题呢

**Comment by ANGELMARS** [comment]
我也出现相同问题

**Comment by AlanHJ** [comment]
一样的，两天前还是OK的，现在提示证书过期

**Comment by cocci810123** [comment]
已恢复正常

**Comment by m1a2sep** [comment]
我今天又出现这个问题了，哪位大佬也有发现这情况么？

**Comment by leonisir** [comment]
@cocci810123 我也遇到这个问题了，请问你是怎么恢复的呢

**Comment by jjm2473** [comment]
系统时间不对

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2478/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2629/1
