### ISSUE TITLE
在iStoreOS系统怎么开启DMZ ？

### ISSUE THREAD

**Issue by goeli-ibm** [istoreos/istoreos#1116]
在R5S上安装了最新版的iStoreOS，但是发现没有DMZ选项，导致游戏用的电脑网络类型是NET3，怎么设置才能使指定IP地址的游戏电脑获得NET1的网络类型？

**Comment by jjm2473** [comment]
防火墙增加个转发规则，把所有端口转发到一个内网ip，就是DMZ了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2626/1
