### ISSUE TITLE
是否可以选择关闭ars2固件的uas驱动

### ISSUE THREAD

**Issue by seacatwu** [istoreos/istoreos#1120]
yda设备，刷ARS2固件，由于sata用usb转，uas驱动在大量IO下，容易崩溃，然后掉盘。
有没有办法关闭uas驱动

**Comment by jjm2473** [comment]
需要修改内核或者uboot参数或者dtb文件，由于ars2的固件没有boot分区，dtb很难修改，只能试试修改uboot参数。具体操作比较麻烦。

**Comment by seacatwu** [comment]
> 需要修改内核或者uboot参数或者dtb文件，由于ars2的固件没有boot分区，dtb很难修改，只能试试修改uboot参数。具体操作比较麻烦。

我看了openwrt的论坛，那些方法都无效。有人说是openwrt的问题，具体也不是很清楚。理论上系统里卸载uas，应该是不调用uas，但是我卸载了，还是没用。

**Comment by bluedevils23** [comment]
> > 需要修改内核或者uboot参数或者dtb文件，由于ars2的固件没有boot分区，dtb很难修改，只能试试修改uboot参数。具体操作比较麻烦。
> 
> 我看了openwrt的论坛，那些方法都无效。有人说是openwrt的问题，具体也不是很清楚。理论上系统里卸载uas，应该是不调用uas，但是我卸载了，还是没用。

启动的时候还没有overlay文件系统，所以配置文件是只读的，貌似dev给了一个解决方案

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2622/1
