### ISSUE TITLE
用iStoreOS做NAS，没有IPv6 DNS解析

### ISSUE THREAD

**Issue by Artyaya** [istoreos/istoreos#1127]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
单网卡，添加Lan6后，能获得IPv6公网地址，但是没有IPv6 DNS解析

Q：是否用关键词搜索了issue? (使用 "x" 选择)
    [*] 没有类似的issue
             有，https://github.com/istoreos/istoreos/issues/871
             但是没有解决我这个问题。

## 2. 详细叙述
             1、在iStoreOS网络接口和首页都显示已获得IPv6地址。
             2、在路由器设置里看设备列表显示iStoreOS显示没有IPv6地址。
             3、过滤IPv6 AAAA记录的勾已取消。
             4、能够直接ping通IPv6的IP地址，但不能ping通IPv6的域名。

### (1) 具体问题

路由器设备列表截图：
![屏幕截图 2023-11-23 122928](https://github.com/istoreos/istoreos/assets/49084742/48f0fc3c-0326-4e0b-aa4b-0381e7d8a579)

iStoreOS的相关设置截图：
![屏幕截图 2023-11-23 123120](https://github.com/istoreos/istoreos/assets/49084742/b2cf711d-f82e-4ff2-9af7-1f87176afcff)
![屏幕截图 2023-11-23 122852](https://github.com/istoreos/istoreos/assets/49084742/e15a1f00-f7c2-42a2-bd0d-b0195397266b)
![屏幕截图 2023-11-23 122743](https://github.com/istoreos/istoreos/assets/49084742/adca199c-6b89-43a4-bef8-3c40bcff4300)
![屏幕截图 2023-11-23 122723](https://github.com/istoreos/istoreos/assets/49084742/e5f1799a-5c16-4039-8131-a93f93edd919)
![屏幕截图 2023-11-23 122709](https://github.com/istoreos/istoreos/assets/49084742/1c8877ae-984a-430b-8b7c-692ac5308885)

### (2) 路由器型号和固件版本

A：老毛子固件

**Comment by bcseputetto** [comment]
`163.com` 这个域名本来就没有 AAAA IPv6解析记录，你先不修改DNS，尝试解析一下别的域名，`www.163.com`才有AAAA IPv6记录。`6.ipw.cn` 是一个只有AAAA IPv6记录的域名。

```console
root@iStoreOS:~# nslookup 163.com 119.29.29.29
Server:		119.29.29.29
Address:	119.29.29.29:53

Non-authoritative answer:
Name:	163.com
Address: 123.58.180.8
Name:	163.com
Address: 123.58.180.7

Non-authoritative answer:

root@iStoreOS:~# nslookup www.163.com 119.29.29.29
Server:		119.29.29.29
Address:	119.29.29.29:53

Non-authoritative answer:
www.163.com	canonical name = www.163.com.163jiasu.com
www.163.com.163jiasu.com	canonical name = www.163.com.bsgslb.cn
www.163.com.bsgslb.cn	canonical name = z163picipv6.v.bsgslb.cn
Name:	z163picipv6.v.bsgslb.cn
Address: 240e:b1:9801:40e:800::49
Name:	z163picipv6.v.bsgslb.cn
Address: 240e:f7:4f00:1d01::1:f8
Name:	z163picipv6.v.bsgslb.cn
Address: 240e:f7:4f00:1d01::1:fb

Non-authoritative answer:
www.163.com	canonical name = www.163.com.163jiasu.com
www.163.com.163jiasu.com	canonical name = www.163.com.bsgslb.cn
www.163.com.bsgslb.cn	canonical name = z163picipv6.v.bsgslb.cn
Name:	z163picipv6.v.bsgslb.cn
Address: 124.239.251.62
```
```console
root@iStoreOS:~# ping6 163.com
ping6: bad address '163.com'
root@iStoreOS:~# ping6 www.163.com
PING www.163.com (240e:f7:4f00:1d01::1:fb): 56 data bytes
64 bytes from 240e:f7:4f00:1d01::1:fb: seq=0 ttl=50 time=16.129 ms
64 bytes from 240e:f7:4f00:1d01::1:fb: seq=1 ttl=50 time=15.342 ms
64 bytes from 240e:f7:4f00:1d01::1:fb: seq=2 ttl=50 time=15.345 ms
64 bytes from 240e:f7:4f00:1d01::1:fb: seq=3 ttl=50 time=15.156 ms
^C
--- www.163.com ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 15.156/15.493/16.129 ms
```

如果还是不行，请尝试将IPv4 DNS 更改为公共DNS `119.29.29.29` `223.5.5.5`
不是说一定要IPv6 DNS才能解析IPv6记录的域名，修改过后尝试测试域名解析
```console
root@iStoreOS:~# nslookup 6.ipw.cn 119.29.29.29
Server:		119.29.29.29
Address:	119.29.29.29:53

Non-authoritative answer:

Non-authoritative answer:
Name:	6.ipw.cn
Address: 2402:4e00:1013:e500:0:9671:f018:4947

root@iStoreOS:~# nslookup 6.ipw.cn 223.5.5.5
Server:		223.5.5.5
Address:	223.5.5.5:53

Non-authoritative answer:
Name:	6.ipw.cn
Address: 2402:4e00:1013:e500:0:9671:f018:4947

Non-authoritative answer:
```
以上是直接指定了DNS服务器，你可以修改DNS后，不指定DNS进行测试，以确保路由器DNS正常
```console
nslookup 6.ipw.cn
```
或者在你上面截图那样，在路由器网页后台测试。

**只能说，你完全挑了一个错误的域名进行IPv6的测试。**
