### ISSUE TITLE
友善R6S刷此固件USB3.0接口无反应

### ISSUE THREAD

**Issue by Mr-Fook** [istoreos/istoreos#1128]
友善R6S刷此固件(1027版本，其他版本没试过)
USB3.0接口无反应，具体表现为USB2.0的接口连接优盘，网卡都是正常的，USB3.0的接口连接什么设备指示灯会亮但是系统上都没有反应，系统日志里也没有连接记录。 (已排除硬件问题，因为这个机器比较冷门，需要帮忙测试可以随时回复)

**Comment by jjm2473** [comment]
我看看，是不是otg模式没切换

**Comment by jjm2473** [comment]
看起来是内核升级rkr4以后出现的，暂时没发现简单的修复方式。0928版本固件没问题，你可以先用这个版本。

**Comment by jjm2473** [comment]
OK，暂时可以强制改成host模式解决问题。等今天的固件发布吧

**Comment by Mr-Fook** [comment]
感谢解答

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2616/1
