### ISSUE TITLE
istoreos的网口自动加入lan如何实现的，我想将这个引入我的固件

### ISSUE THREAD

**Issue by jiu-chuan** [istoreos/istoreos#1130]
istoreos的网口自动加入lan如何实现的，我想将这个引入我的固件
设备：X86

**Comment by jjm2473** [comment]
istoreos也没这个功能啊，只是第一次开机会自动分配网口角色，之后如果增加了新网卡，也是要手动配置角色的

**Comment by jiu-chuan** [comment]
> istoreos也没这个功能啊，只是第一次开机会自动分配网口角色，之后如果增加了新网卡，也是要手动配置角色的

感谢你的回复，方便指导一下自动分配角色是如何制作吗，想将此方法引入我的openwrt固件

**Comment by jjm2473** [comment]
openwrt 的网络初始配置都在这里 https://github.com/istoreos/istoreos/tree/istoreos-22.03/target/linux/x86/base-files/etc/board.d

**Comment by jjm2473** [comment]
对于非特定机型，修改 99-default_network 即可

**Comment by jiu-chuan** [comment]
> 对于非特定机型，修改 99-default_network 即可

感谢

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2614/1
