### ISSUE TITLE
检查一下 DHCP/DNS，高级设置里，过滤AAAA IPv6记录 是否勾选，尝试取消勾选后，再观察观察

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1138]
检查一下 DHCP/DNS，高级设置里，过滤AAAA IPv6记录 是否勾选，尝试取消勾选后，再观察观察

_Originally posted by @bcseputetto in https://github.com/istoreos/istoreos/issues/1135#issuecomment-1826238432_
解决了确实是没开ipv6的原因

**Comment by jjm2473** [comment]
你是不是不会用issue？直接在你自己的帖子回复就行了啊，还开个新issue。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2609/1
