### ISSUE TITLE
DDNS dynv6 ipv4和ipv6的问题

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1139]
反馈bug/问题模板，提建议请删除

1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时包括已关闭的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)

 没有类似的issue
2. 详细叙述
(1) 具体问题
A：

(2) 路由器型号和固件版本
FriendlyElec NanoPi R6S

iStoreOS 22.03.4 2023071416

(3) 详细日志和/或截图
最先的问题是  ipv6动态域名运行正常，但是在 已注册的 IP 地址 那一栏显示是无数据，正常应该显示ipv6地址
经由 检查一下 DHCP/DNS，高级设置里，过滤AAAA IPv6记录 是否勾选，尝试取消勾选后，再观察观察这个回答解决了ipv6动态域名的问题，但是紧接着想要添加一个ipv4的域名，发现
addresses unchanged
 163403  info : Update successful - IP '110.178.211.26' send
 163403  info : Forced update successful - IP: '110.178.211.26' send
 163403       : Waiting 300 seconds (Check Interval)
 163903       : Detect registered/public IP
 163903       : #> /usr/bin/nslookup yiyeshu.dynv6.net  >/var/run/ddns/ipv4.dat 2>/var/run/ddns/ipv4.err
 163903  WARN : NO valid IP found
 163903  WARN : Get registered/public IP for 'yiyeshu.dynv6.net' failed - retry 1/0 in 60 seconds
无法向服务器获取ipv4地址了。。。，这两个冲突吗？不太搞得懂都是dynv6的ddns，甚至重新建立一个新得域名还是这样子，ipv6和ipv4不能共存吗
后来发现ipv4是一会成功一会又是163903  WARN : NO valid IP found 不知道这是服务器的问题还是程序的bug

165804  WARN : NO valid IP found
 165805  WARN : Get registered/public IP for 'yiyeshu.dynv6.net' failed - retry 1/0 in 60 seconds
 165905       : #> /usr/bin/nslookup yiyeshu.dynv6.net  >/var/run/ddns/ipv4.dat 2>/var/run/ddns/ipv4.err
 165905  WARN : NO valid IP found
 165905  WARN : Get registered/public IP for 'yiyeshu.dynv6.net' failed - retry 2/0 in 60 seconds
 170005       : #> /usr/bin/nslookup yiyeshu.dynv6.net  >/var/run/ddns/ipv4.dat 2>/var/run/ddns/ipv4.err
 170005  WARN : NO valid IP found
 170005  WARN : Get registered/public IP for 'yiyeshu.dynv6.net' failed - retry 3/0 in 60 seconds
 170105       : #> /usr/bin/nslookup yiyeshu.dynv6.net  >/var/run/ddns/ipv4.dat 2>/var/run/ddns/ipv4.err
 170105       : Registered IP '110.178.211.26' detected
 170105  info : Rerun IP check at 2023-11-26 17:01
 170105       : Detect local IP on 'interface'
 170105       : #> ip -o addr show dev pppoe-wan scope global >/var/run/ddns/ipv4.dat 2>/var/run/ddns/ipv4.err
 170105       : Local IP '110.178.211.26' detected on interface 'pppoe-wan'
 170105       : Waiting 300 seconds (Check Interval)

**Comment by jjm2473** [comment]
你开这么多issue干嘛？

**Comment by pili-book** [comment]
> 你开这么多issue干嘛？

不是很熟悉网站操作吧

**Comment by pili-book** [comment]
已经解决，给小白参考
![微信图片_20231128164142](https://github.com/istoreos/istoreos/assets/96804858/9989ef66-148f-48ac-947b-ac33742594b3)
如图所示要手动添加两条记录，默认好像只有一条，把另一个补足，一个A代表ipv4，AAAA代表ipv6

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2608/1
