### ISSUE TITLE
更新日志 - 22.03.5 - 20231124

### ISSUE THREAD

**Issue by letit2020** [istoreos/istoreos#1141]
### Discussed in https://github.com/istoreos/istoreos/discussions/1134

<div type='discussions-op-text'>

<sup>Originally posted by **jjm2473** November 24, 2023</sup>
# 系统
1. 更新 Mediatek 系列无线网卡驱动，并支持 MT7922。（如果第一次启动没出现无线菜单，就重启一次试试）
2. Intel AX201 增加新fw文件，某些版本需要
3. 内核支持 Quectel RM500U-CN 5G 模块（需要自行配置，可能需要使用特定拨号工具）

# 设备
* x86：
  1. EFI 未压缩镜像对齐到 4KB，方便直接解压固件给虚拟机使用（可能对性能有好处）
* rk35xx：
  1. 修复 R6S/R6C 的 USB 3.0 接口 #1128
  2. 修复 H28K 的 PPPoE 拨号性能 #1125
  3. H69K 优化风扇调度
  4. uboot 修改长按电源键 pmic 强制关机的触发时间，从6秒改成10秒，只对重新刷机有效
  5. ffmpeg 支持 mjpeg 硬解，支持USB摄像头数据硬件转码

</div>

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2606/1
