### ISSUE TITLE
请问大佬11月24 号的固件不能通过在线升级安装吗

### ISSUE THREAD

**Issue by benzo970210** [istoreos/istoreos#1143]
请问大佬11月24 号的固件不能通过在线升级安装吗

**Comment by jjm2473** [comment]
还没上传，老板忘记了，今天应该会上传的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2604/1
