### ISSUE TITLE
N100处理器，系统每周一上午都会自动关闭是怎么回事？

### ISSUE THREAD

**Issue by hui-f** [istoreos/istoreos#1145]

**Comment by jjm2473** [comment]
要么被攻击了，要么自己设置了定时任务，还有其他可能吗

**Comment by hui-f** [comment]
> 要么被攻击了，要么自己设置了定时任务，还有其他可能吗
怎么看是否设定了定时任务

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2602/1
