### ISSUE TITLE
可以麻烦帮忙编译一个 西瓜皮v3   rk3568 固件？自己编译的老是各种问题

### ISSUE THREAD

**Issue by qooke** [istoreos/istoreos#1148]
我看主线有支持 rk3568 的dts

可以麻烦帮忙编译一个 西瓜皮v3  rk3568 固件？带5g模块  mt79xx系列网卡驱动的

自己编译的mt7921k 无线网卡断流经常断。

看系统日志、内核日志，没报错，不知道怎么排查了

**Comment by jjm2473** [comment]
https://fw.koolcenter.com/iStoreOS/alpha/xgp/

**Comment by qooke** [comment]
谢谢大佬

**Comment by blackboygirl** [comment]
这个固件，开机不能拨号怎么解决的？

**Comment by 201866637** [comment]
> https://fw.koolcenter.com/iStoreOS/alpha/xgp/

这个好像没有编译上模块的pcie驱动

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2599/1
