### ISSUE TITLE
刷入一台x86电脑，想作为旁路，发现内网外网都无法访问

### ISSUE THREAD

**Issue by Yoshiya1997** [istoreos/istoreos#1151]
### (2) 路由器型号和固件版本

路由器：华为TC7102,联通定制版
固件版本：istoreos-22.03.5-2023102711-x86-64-squashfs-combined.img.gz

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2597/1
