### ISSUE TITLE
r5c 在线升级固件后版本号没有变

### ISSUE THREAD

**Issue by leechhboy** [istoreos/istoreos#1152]
设备是r5c 当前固件是20231124 在线升级固件后版本号没有变 是怎么回事？
![Uploading Image_1701577304798.jpg…]()
![Uploading Image_1701577324376.jpg…]()
![Uploading Image_1701577310810.jpg…]()

**Comment by leechhboy** [comment]
我重新刷机后  在线升级还是不能成功 版本号还是不变  固件升级还是有升级提示  请问怎么办？

**Comment by leechhboy** [comment]
r5c TF卡 只安装了alist和 clouddrive2  docker迁移到TF卡剩余空间 pppoe拨号

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2596/1
