### ISSUE TITLE
istoreos能卸载docker么，卸载了对系统有没有影响

### ISSUE THREAD

**Issue by rootazero** [istoreos/istoreos#1153]
如题：
大佬，istoreos能卸载docker么，卸载了对系统有没有影响

**Comment by wnpllrzodiac** [comment]
肯定能啊。docker又不是必要组件

**Comment by jjm2473** [comment]
启动项那边禁用就行了，没必要卸载，而且docker程序在ROM只读分区里面，卸载并不会释放空间，当然，卸载也没问题，只是以后要安装的话就麻烦了。

**Comment by cnwikee** [comment]
请问如何卸载Docker

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2595/1
