### ISSUE TITLE
请问MT7621A的设备支持吗，应该下载哪个包？

### ISSUE THREAD

**Issue by AKiwiBirdGMail** [istoreos/istoreos#1154]
请问MT7621A的设备支持吗，应该下载哪个安装包？我的是新路由3 Newwifi3 D2，已经安装的旧的OpenWRT，想更新到istoreos来

**Comment by jjm2473** [comment]
没有，也不打算支持低端的硬路由，内存和rom都不够玩

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2594/1
