### ISSUE TITLE
X86 N4100路由器使用Samba协议拷贝文件时出现速度掉落和高CPU占用

### ISSUE THREAD

**Issue by goodwish1** [istoreos/istoreos#1155]
固件版本：22.03.5 2023112413

在使用Samba协议拷贝文件进入X86 N4100路由器时，出现间歇性的速度掉落和高CPU占用。具体表现是将一部80GB的电影从路由器拷贝至电脑时，速度保持在110MB/s，但将文件拷贝进路由器时，速度不稳定，有时降至几兆每秒，同时掉速的时候观察到CPU占用较高。

**Comment by goodwish1** [comment]
以前的版本不会这样，更新后就这样。
现在我限制了smbd 进程的CPU使用率，基本可以解决掉速到接近零的问题，但是整个过程还是有10%的时间掉速。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2593/1
