### ISSUE TITLE
DOCKER不见了

### ISSUE THREAD

**Issue by hx801217** [istoreos/istoreos#1157]
X86固件，重启后DOCKER不见了，在ISTORE里面再点隐藏/显示也出不来，但是docker里面的服务还在运行，就是docker进口没了
![QQ截图20231205093448](https://github.com/istoreos/istoreos/assets/34504398/f77dc95f-c397-4a7e-9ae7-a3ad7e500729)

![QQ截图20231205103137](https://github.com/istoreos/istoreos/assets/34504398/91cfc539-eb55-493c-894e-ca9c847ee944)

**Comment by xkloveme** [comment]
+1

**Comment by AlphaGHX** [comment]
是否安装了 KVM 然后又卸载了？如果是这样，就和我踩了同样的坑。因为 KVM 卸载的时候反手把除 dockerd 以外的 docker 软件包全删了。

解决办法：如下图，只需要把 docker 相关的软件包装回来就好。
![image](https://github.com/istoreos/istoreos/assets/61853980/e027048e-173e-4972-b329-0879d9d20c6d)

**Comment by hx801217** [comment]
> 是否安装了 KVM 然后又卸载了？如果是这样，就和我踩了同样的坑。因为 KVM 卸载的时候反手把除 dockerd 以外的 docker 软件包全删了。
> 
> 解决办法：如下图，只需要把 docker 相关的软件包装回来就好。 ![image](https://private-user-images.githubusercontent.com/61853980/288086953-e027048e-173e-4972-b329-0879d9d20c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODk2MTQsIm5iZiI6MTcwMTc4OTMxNCwicGF0aCI6Ii82MTg1Mzk4MC8yODgwODY5NTMtZTAyNzA0OGUtMTczZS00OTcyLWIzMjktMDg3OWQ5ZDIwYzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE1MTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNjUxYjQ0ZDRlYzkzMTZkYjhlNzM5NTI5NmYzZWFiYzg1Y2VmN2U3MjA1NmEzOTc2MWMxZGI0MjJmY2NmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9QPbtkb7Wh7nqTMfiCUpU1SMiGQKx0slqg-uULwgjWM)

果然如此，感觉指教！

**Comment by iamfang2019** [comment]
我也是这样，非常感谢，试试

**Comment by jjm2473** [comment]
之前有个插件有bug（好像就是kvm的那个），插件卸载时会卸载掉docker。修复方式不一定要从软件包安装，可以从istore安装“系统便利工具”，然后执行里面的“修复系统软件”就可以恢复docker了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2591/1
