### ISSUE TITLE
Intel(R) Xeon(R) E-2174G CPU  显卡P60 如何安装jellyfin 支持硬件加速

### ISSUE THREAD

**Issue by zhibeen** [istoreos/istoreos#1158]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
Intel(R) Xeon(R) E-2174G CPU  显卡P60 如何安装jellyfin 支持硬件加速， istoreos 是否支持intel p630 核显

已经勾选了系统自带的驱动， 但是jellyfin 设置硬件加速还是无效
![图片](https://github.com/istoreos/istoreos/assets/25072839/15e03ba7-0bf5-404e-b718-37e83d551268)

**Comment by jjm2473** [comment]
如果不是近3年的产品，不要勾选，而且现在最新的固件可以自动判断要不要加载这个驱动，不需要用户选择

**Comment by zypj1123** [comment]
> 如果不是近3年的产品，不要勾选，而且现在最新的固件可以自动判断要不要加载这个驱动，不需要用户选择

我的是n5000需要勾选吗？感觉jellyfin没有硬解

**Comment by jjm2473** [comment]
自己看系统里面有没有 `/dev/dri/card*`，如果有，那基本是你的配置有问题。用istore里面的jellyfin插件部署，还有不要使用docker的国内镜像仓库，以免安装到jellyfin的老版本。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2590/1
