### ISSUE TITLE
易有云文件管理上传文件在非80或443端口的跨域问题

### ISSUE THREAD

**Issue by fankangsong** [istoreos/istoreos#1159]
## 1.关于你要提交的问题

主路由通过 DDNS 绑定了域名，并使用了 4433 端口，易有云文件管理器在上传文件时，没有适配 4433 这个端口，导致文件上传接口跨域报错，无法上传文件；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

易有云上传文件接口存在端口适配导致的跨域问题
接口名称：cgi-bin/luci/linkease/api/file/transmit/

### (2) 路由器型号和固件版本
x86 路由器，系统版本iStoreOS 22.03.5 2023102711 / LuCI istoreos-22.03 branch git-23.271.10849-b445bc4

### (3) 详细日志和/或截图

第一个接口cgi-bin/luci/linkease/api/file/transmit拼接了 4433端口，正常可用。
![1](https://github.com/istoreos/istoreos/assets/554934/536042fc-9945-4a7c-b18a-7e847e275f3b)

第二个接口 cgi-bin/luci/linkease/api/file/transmit/ 没有拼接 4433端口，跨域报错。
![2](https://github.com/istoreos/istoreos/assets/554934/70d0d14e-d4c8-454e-9581-09336a269c8a)

**Comment by jjm2473** [comment]
应该修复了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2589/1
