### ISSUE TITLE
无法正常使用网卡发射wifi信号

### ISSUE THREAD

**Issue by lff110** [istoreos/istoreos#1160]
反馈bug/问题模板，提建议请删除

Q：是否用关键词搜索了issue? (使用 "x" 选择)
没有类似的issue

2. 详细叙述
使用磊科NW337v2(RTL8188CU)芯片网卡时一直提示设备未激活，无法发射出WiFi信号但是删除所有WiFi信号时可以显示出数据并且也能连接到路由器发射的信号
(1) 具体问题
使用磊科NW337v2(RTL8188CU)芯片网卡时一直提示设备未激活，无法发射出WiFi信号但是删除所有WiFi信号时可以显示出数据并且也能连接到路由器发射的信号

### (3)截图

A：
![1](https://github.com/istoreos/istoreos/assets/104684922/440dd802-4c95-44e6-8b2e-490051f09620)
![2](https://github.com/istoreos/istoreos/assets/104684922/749484ee-2ab2-4420-809f-5b774adecc84)
![3](https://github.com/istoreos/istoreos/assets/104684922/040f1145-dcb3-4aa6-9c51-e2f678113d94)

**Comment by zhangdi-go** [comment]
我是RTL8811CU，也是一样的情况

**Comment by jjm2473** [comment]
有些网卡需要设置正确的国家，有些还不支持5G，有些网卡要设置频道（不能自动）

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2588/1
