### ISSUE TITLE
系统升级时，会覆盖原先设定好的挂载点路径为“设备类型-设备分区号” , 类似 “sata-1”

### ISSUE THREAD

**Issue by wx2020** [istoreos/istoreos#1165]
## 1.关于你要提交的问题
系统升级时，会覆盖原先设定好的挂载点路径为“设备类型-设备分区号” , 类似 “sata-1”；虚拟机下因磁盘类型不明确，显示为“-1"

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：每次系统升级时，会覆盖原先设定好的挂载点路径为“设备类型-设备分区号” , 类似 “sata-1”；虚拟机下因磁盘类型不明确，显示为“-1"

### (2) 路由器型号和固件版本

A：X86 iStoreOS 22.03.5 2023112413

### (3) 详细日志和/或截图

A：暂无，但此问题每次升级均可复现

**Comment by jjm2473** [comment]
用uuid挂载啊

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2584/1
