### ISSUE TITLE
如何在挂载网络共享那里挂载成功samba

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1166]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：我有一个小猫盘，能提供samba服务，想把他挂载到openwrt,但是各种填写那个内容在 挂载网络共享插件那里也无法实现挂载，也没有日志能看。。。。找不到原因 易有云文件查看是不行没挂载成功

### (2) 路由器型号和固件版本

A： FriendlyElec NanoPi R6S
StoreOS 22.03.4 2023071416 / LuCI istoreos-22.03 branch git-23.103.23275-0193674

**Comment by alphazhugit** [comment]
系统-启动项-本地启动脚本里脚本挂

**Comment by pili-book** [comment]
那个插件不管用么？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月9日(周六) 中午12:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 如何在挂载网络共享那里挂载成功samba (Issue #1166)




 
系统-启动项-本地启动脚本里脚本挂

**Comment by pili-book** [comment]
> 系统-启动项-本地启动脚本里脚本挂

惭愧，小白，不会在那里挂载脚本，直接把命令输入进去放那好似不管用

**Comment by pili-book** [comment]
官方插件不管用的话有没有第三方插件能直接使用的了有没有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月9日(周六) 中午12:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 如何在挂载网络共享那里挂载成功samba (Issue #1166)




 
系统-启动项-本地启动脚本里脚本挂

**Comment by jjm2473** [comment]
samba挂载失败的话，执行`/etc/init.d/cifs start`看看有没有报错。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2583/1
