### ISSUE TITLE
Kmod-sit 安裝時報錯 ccps 之後自動重起

### ISSUE THREAD

**Issue by DumplingMiku** [istoreos/istoreos#1176]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：Kmod-sit 安裝時報錯 ccps 之後自動重起

### (2) 路由器型号和固件版本

A： pve 7.4.3   iStoreOS 22.03.5 2023102711
![image](https://github.com/istoreos/istoreos/assets/44613282/7d3141b6-f4d3-4409-bedd-28f50c0ef28c)

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/44613282/8a0c4749-c9f3-43e6-989d-80221f1be198)

**Comment by jjm2473** [comment]
可能是因为openwrt的软件源更新了内核版本导致了不兼容，今天更新固件会通过集成kmod-sit来解决此问题，之后跟openwrt同步代码应该可以彻底修复。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2573/1
