### ISSUE TITLE
esxi安装后每次启动需要按一下任意按键，能跳过该步骤吗

### ISSUE THREAD

**Issue by CodeWarriors0** [istoreos/istoreos#1178]
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [X] 没有类似的issue

## 2. 详细叙述
因为一些原因设备会不定期断电一下，断电后重启设备OS会卡在按一下任意按键这个步骤,有办法能关掉该设置吗

### (2) 路由器型号和固件版本

A：倍控J4125

**Comment by jjm2473** [comment]
靠，你是说“按任意键激活当前终端”，跟你的使用有啥关系？

**Comment by CodeWarriors0** [comment]
> 靠，你是说"按任意键激活当前终端"，跟你的使用有啥关系？

因为我当前的环境会经常重启我的路由器，而路由器重启后esxi会自动启动，并启动安装了IstoreOS的镜像，但这个时候IStore OS会提示我按任意键😂从而导致了我没法让它实现通电后自启，它会在启动后卡在这一步骤

**Comment by jjm2473** [comment]
截图看看到底是什么，如果是`active console`那就不用管

**Comment by CodeWarriors0** [comment]
> 截图看看到底是什么，如果是`active console`那就不用管

 今晚仔细研究了一下，确实是`active console`不按也不影响使用，感谢回复！！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2571/1
