### ISSUE TITLE
正版emby无法激活

### ISSUE THREAD

**Issue by edcyoo** [istoreos/istoreos#1179]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
emby无法使用官方key激活
### (1) 具体问题

A：emby无法使用官方key激活

### (2) 路由器型号和固件版本

A：x86软路由

### (3) 详细日志和/或截图

A：给官方发过邮件了 说是防火墙阻挡 无法连接他们的服务器

**Comment by edcyoo** [comment]
![Uploading QQ截图20231214172556.png…]()

**Comment by edcyoo** [comment]
![QQ截图20231214172556](https://github.com/istoreos/istoreos/assets/118623786/947f502d-9c5a-4a8a-9f41-466d9b431e4a)

**Comment by jjm2473** [comment]
"防火墙"是指路由器的防火墙，还是GFW？

**Comment by edcyoo** [comment]
> "防火墙"是指路由器的防火墙，还是GFW？

是路由防火墙 已经没问题了 在防火墙 区域里配置了下相应区域就好了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2570/1
