### ISSUE TITLE
heimdall无法通过服务状态里的快捷按钮打开页面

### ISSUE THREAD

**Issue by HAN915** [istoreos/istoreos#1180]
heimdall安装以后，无法通过服务状态栏里的快捷按钮打开页面，emby、jellyfin都是可以直接打开的，heimdall这个点击以后没有任何反应
![screenshot20231214](https://github.com/istoreos/istoreos/assets/100837367/4bbd4fc0-30fa-418b-914b-58cfe5c15833)

**Comment by jjm2473** [comment]
这部分跟jellyfin代码一样的，是不是你的浏览器拦截了heimdall的页面，所以没法跳转？试试换个浏览器

**Comment by jjm2473** [comment]
OK，确认了，是因为有两个端口，没有分开判断

**Comment by jjm2473** [comment]
修复了，等一会儿istore就能看到更新

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2569/1
