### ISSUE TITLE
Docker容器无法访问被透明代理的IP

### ISSUE THREAD

**Issue by zzj6116** [istoreos/istoreos#1183]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：20230609之后的固件使用Docker版本nastool 2.91版的telegram通知功能，一直都能正常使用，后来全新刷机后，安装同样版本的nastool，telegram通知功能无法联网。检测网络连通性，显示api.telegram.org无法连通，Docker网络使用的都是默认的设置，一直以为是nastool的问题，前几天在绿联DX4600的Docker上使用nastool没有这个问题，可正常连通api.telegram.org，win版本的nastool同样可以正常连通api.telegram.org，所以判断是istoreos的问题，盼官方能解决这个问题。

### (2) 路由器型号和固件版本

A：硬件是J4125的x86机器，固件版本是iStoreOS 22.03.5 2023120811

### (3) 详细日志和/或截图

[A：
![1](https://github.com/istoreos/istoreos/assets/76789765/87ab22bc-5697-407b-b46e-79862f74b838)
![2](https://github.com/istoreos/istoreos/assets/76789765/0ca9de26-7c40-4f9f-9fa6-74629af68c67)
![3](https://github.com/istoreos/istoreos/assets/76789765/a52063a0-4241-41db-b5a3-77b96d0f85d6)
![5](https://github.com/istoreos/istoreos/assets/76789765/1fda0354-ee9c-45e6-952b-3cbf069da830)
![6](https://github.com/istoreos/istoreos/assets/76789765/64405b4e-0e4d-45f7-a912-de348e5b55e7)

**Comment by jjm2473** [comment]
你的翻墙插件运行在哪，跟nastool同一机器吗？翻墙插件配置本机代理模式是什么？还有执行`ip addr ; route`把结果发出来看看。

**Comment by zzj6116** [comment]
> ip addr ; route

感谢您的回复，翻墙插件用的是Are you ok 下载的新版的ShadowSocksR Plus+ ，运行在iStoreOS物理机上，和Nastool在同一机器，iStoreOS是主路由，此路由下，所有的设备翻墙都是正常的，只有iStoreOS内安装的Docker版的nastool翻墙不正常，同样的网段下，绿联dokcer安装的nastool翻墙正常，执行命令行显示如下：
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         hn.kd.ny.adsl   0.0.0.0         UG    0      0        0 pppoe-wan
10.0.0.0        *               255.255.255.0   U     0      0        0 br-lan
42.228.239.254  *               255.255.255.255 UH    0      0        0 pppoe-wan
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0
192.168.191.0   *               255.255.255.0   U     0      0        0 zteb4nen5y
![9](https://github.com/istoreos/istoreos/assets/76789765/42ad310d-73a1-414a-8d0e-691a2482d184)
![10](https://github.com/istoreos/istoreos/assets/76789765/4444aa85-6255-4435-a8ea-ea198ee843f0)
![8](https://github.com/istoreos/istoreos/assets/76789765/6a1e7aa3-2137-42be-b645-dc41ca34804e)

**Comment by jjm2473** [comment]
nastools是自己手动部署的吗，还是用istore的插件部署的？手动部署有没有设置dns？

**Comment by zzj6116** [comment]
> nastools是自己手动部署的吗，还是用istore的插件部署的？手动部署有没有设置dns？
nastools是用istore的插件部署的，但是镜像因为拉不到官方镜像了，使用的的第三方备份的官方2.91镜像，后来也试着升级到官方的最后一版nastools 3.2的镜像，但是问题依旧，还是显示显示api.telegram.org无法连通。相同的镜像，在绿联的docker设备上没有这个问题。
![2](https://github.com/istoreos/istoreos/assets/76789765/45a05636-dc82-4e11-81ed-28b1fb70c432)
![3](https://github.com/istoreos/istoreos/assets/76789765/a93cd34c-54c5-44cc-83cc-2c0b1583110c)

**Comment by jjm2473** [comment]
因为绿联是在内网啊，翻墙插件又不是在绿联上运行。
翻墙插件的本机和内网代理策略是不一样的。

你试试istoreos里面执行`curl https://api.telegram.org/`

**Comment by jjm2473** [comment]
哦，我还想到一个问题，你的翻墙插件配置的TCP代理模式是redirect还是tproxy，也许换一个就行了

**Comment by jjm2473** [comment]
我在其他机器上遇到过tproxy无法代理docker流量的情况，改成redirect就行了。不过我用的插件是passwall

**Comment by zzj6116** [comment]
您好，请问这个怎么改？



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2023年12月15日(周五) 晚上6:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] X86硬件 20230609之后的固件，Docker版的nastool无法联通telegram，需要代理的IP无法联网 (Issue #1183)




 
我在其他机器上遇到过tproxy无法代理docker流量的情况，改成redirect就行了

**Comment by jjm2473** [comment]
passwall的话，高级设置里。其他插件就不知道了

**Comment by zzj6116** [comment]
感谢，果然可以了，那看来是插件的原因。



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2023年12月15日(周五) 晚上6:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] X86硬件 20230609之后的固件，Docker版的nastool无法联通telegram，需要代理的IP无法联网 (Issue #1183)




 
我在其他机器上遇到过tproxy无法代理docker流量的情况，改成redirect就行了

**Comment by jjm2473** [comment]
不一定是插件问题，可能内核tproxy就是不支持docker虚拟网络。好像passwall默认的tcp代理模式是redirect。

**Comment by zzj6116** [comment]
passwall默认的tcp代理模式就是redirect
&nbsp;
ShadowSocksR Plus+没有设置redirect的选项，

目前更换插件为passwall2，问题解决了

---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2023年12月15日(周五) 晚上7:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] X86硬件 20230609之后的固件，Docker版的nastool无法联通telegram，需要代理的IP无法联网 (Issue #1183)




 
不一定是插件问题，可能内核tproxy就是不支持docker虚拟网络。好像passwall默认的tcp代理模式是redirect。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2566/1
