### ISSUE TITLE
关于无线网卡M2接口发射wifi信号

### ISSUE THREAD

**Issue by jiaz520** [istoreos/istoreos#1187]
已经刷了istoreos系统，但是没有无线，不能发射wifi信号，想寻求帮助，到底需要购买具体哪个型号的无线网卡，我的设备是迷你电脑，支持M2接口，官网推荐了 MT7921，但是我搜索，发现很多买无线网卡的MT7921只支持wind10和11,所以想问问，具体该买哪个，设备太多了，想减轻负担。还有想了解，能同时发射2.4G 和5G信号吗

**Comment by szzProject** [comment]
MT7922亲测可以的
![image](https://github.com/istoreos/istoreos/assets/20944039/111c6248-8335-474e-b0f8-89002bc3acb2)

**Comment by jjm2473** [comment]
如果要做AP，需要支持双频同时发射，那就MT7915/MT7916，如果不需要双频同时发射，那么MT7921/MT7922。

如果不需要做AP，那除了MTK以外，Intel的都行，甚至USB无线网卡都行。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2563/1
