### ISSUE TITLE
Homeassistant 找不到DLNA设备

### ISSUE THREAD

**Issue by maxhboss** [istoreos/istoreos#1189]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：从iStore里下载设置的Homeassistant无法找到网络里的DLNA设备， 但是我群晖里的就可以

### (2) 路由器型号和固件版本

A：
设备型号
Intel(R) Celeron(R) CPU 3965U @ 2.20GHz
x86 Generic
固件版本
iStoreOS 22.03.5 2023102711
内核版本
5.10.176

### (3) 详细日志和/或截图

A：无

**Comment by jjm2473** [comment]
Homeassistant你是使用istore里面的插件部署的吗，还是自己手动部署的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2561/1
