### ISSUE TITLE
状态里面的实时信息，连接数统计这里，udp连接数超过50000之后，大概过了10几个小时，这个页面就无法显示出具体连接数了

### ISSUE THREAD

**Issue by nobita215** [istoreos/istoreos#119]
状态里面的实时信息，连接数统计这里，udp连接数超过50000之后，大概过了10几个小时，这个页面就无法显示出具体连接数了，
等多久都不显示，系统负载也很低，其他也未见异常，就是连接数不显示统计了。
![image](https://user-images.githubusercontent.com/12522734/167244963-2396d766-4540-422e-be43-979adfe7b463.png)

**Comment by jannson** [comment]
这个是官方的 BUG，因为数据量太大，无法显示出来了。。。

**Comment by jjm2473** [comment]
我有个补丁限制只显示1000条

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3641/1
