### ISSUE TITLE
静态路由不生效

### ISSUE THREAD

**Issue by jinxiao** [istoreos/istoreos#1191]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：静态路由不生效。在界面，网络-路由，配置静态路由和IPV4规则，使用命令route查看未生效

### (2) 路由器型号和固件版本

A：x86_64 iStoreOS 22.03.5 2023112413 / LuCI istoreos-22.03 branch git-23.271.10849-b445bc4

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/2718196/0359a57c-abdb-457c-9094-91e7292b1570)
使用route查看，不生效

![image](https://github.com/istoreos/istoreos/assets/2718196/635fa3ea-32db-416c-ae3d-88a20c6b1a99)

**Comment by jjm2473** [comment]
为啥你要配置规则，而且还是main表，应该只要配置路由就行了吧

**Comment by jjm2473** [comment]
把规则都删掉，看看你的静态路由怎么配置的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2559/1
