### ISSUE TITLE
管理页面无法登录

### ISSUE THREAD

**Issue by Alstonsz** [istoreos/istoreos#1195]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
X86系统,在线升级最新系统,导致管理页面无法访问.
### (1) 具体问题
系统都能正常工作.管理页面192.168.100.1、外网(已经做端口转发,未升级之前可以正常访问),无法登录访问.
A：

### (2) 路由器型号和固件版本
X86;无法登录页面,看不到固件版本.是因为在线更新固件后无法访问管理后台.
A：

### (3) 详细日志和/或截图

A：

**Comment by kelvin80man** [comment]
我也遇到这个情况，管理页面无法登录访问。通过vi etc/config/network 修改了 IP地址也不行

**Comment by jjm2473** [comment]
重启试试

**Comment by lwj1994** [comment]
直接  ssh wan 口的 ip  也无法登录，局域网内根本找不到这个 ip  @jjm2473  之前的系统安装都是正常的，环境没有问题

**Comment by jjm2473** [comment]
@lwj1994 如果你是x86机型，在1月12日到1月16日之间升级的，且网卡是RTL8125，那你遇到的问题估计是这个 https://github.com/istoreos/istoreos/issues/1257 ，连显示器看看`ip addr`命令会不会卡死。

**Comment by jjm2473** [comment]
其他人如果只是访问不了后台，联网什么的还正常，是不是之前安装了nginx？如果是，参考 https://github.com/istoreos/istoreos/issues/863 修复

**Comment by lwj1994** [comment]
> ip addr

没有卡死，但是 ssh 192.168.6.157 连不了
![img_v3_028d_11a71983-b891-4a50-8066-87d00d7cd6cg](https://github.com/istoreos/istoreos/assets/10978048/8c1dac9b-417f-4038-aa8b-7223dff17d9b)

**Comment by jjm2473** [comment]
@lwj1994 防火墙默认禁止wan口访问后台

**Comment by lwj1994** [comment]
> @lwj1994 防火墙默认禁止wan口访问后台

这个问题依然存在。192.168.100.1 就是进不去. （已放弃

**Comment by jjm2473** [comment]
都说了wan口默认禁止访问，这不是“问题”，是设计好的。你在lan口连接就可以通过192.168.100.1访问后台。

根据你的截图，lan口都没接网线。如果你不知道哪个是lan口，那就都试一下，反正也就两个网口。

**Comment by jayansi** [comment]
系统原来能用，使用手动升级iStoreOS 22.03.7, 2024122712时，升级过程一直卡在升级过程，强行重启后后台进不去。

**Comment by bigsky315** [comment]
是不是网卡驱动的问题，可以试试先把网络设置成100M看看能不能获取到IP，我遇到过类似的问题，只能把网络设置成100M，1000M就DHCP获取不到ip/静态IP不生效

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2556/1
