### ISSUE TITLE
Docker开关不定时遇到自动关闭的情况，docker stats 报错Cannot connect to the Docker daemon at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by wei400804** [istoreos/istoreos#1197]
机器n5105,用ESXI装的IStoreOS
更新了几个版本了，都遇到过这个情况（一般几天或十多天遇到一次），每次都是发现HomeAssistant访问不到了，然后打开IStoreOS发现主页上的Docker开关显示为关闭

执行 docker stats
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
执行 /etc/init.d/dockerd status
running

使用top命令发现HomeAssistant进程在运行有CPU占用

**Comment by jjm2473** [comment]
监控下内存使用，或者看看内核日志，有没有“OOM”相关的日志

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2555/1
