### ISSUE TITLE
golang版本问题

### ISSUE THREAD

**Issue by loopback123** [istoreos/istoreos#1202]
有考虑升级golang到最新的1.21吗？ 现在1.19有的插件编译有问题呢

**Comment by jjm2473** [comment]
嗯，确实golang太老了，有些插件都编译不了了，不过这些基础软件一般都跟着openwrt升级的。

如果你只是想编译翻墙插件，可以先试试其他网友编译好的 https://github.com/bcseputetto/Are-u-ok/

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2552/1
