### ISSUE TITLE
官网AX9000的大分区固件版本有无升级版本？

### ISSUE THREAD

**Issue by HelloFy** [istoreos/istoreos#1203]
AX 9000 目前官网下载的大分区固件版本有点老旧，有无自编译办法，如何升级较新的版本？

**Comment by jjm2473** [comment]
这个设备是lean在维护的，代码也不在这个仓库，可能去他的群里反馈更合适

**Comment by HelloFy** [comment]
感觉这个设备的固件绝版了，搞了大分区之后，还刷不回去。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2551/1
