### ISSUE TITLE
配置交换分区后，交换分区提示“磁盘读写状态：只读”是正常的吗？？？

### ISSUE THREAD

**Issue by N1k1Zhang** [istoreos/istoreos#1204]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：配置交换分区后，交换分区提示“磁盘读写状态：只读”是正常的吗？？？

### (2) 路由器型号和固件版本

A：设备型号
Raspberry Pi 4 Model B Rev 1.4
固件版本
iStoreOS 22.03.5 2023121510

### (3) 详细日志和/或截图

A：
<img width="506" alt="swap" src="https://github.com/istoreos/istoreos/assets/76231660/9e9ecbe8-336f-4a0a-a88c-43713ea5e9c7">

**Comment by jjm2473** [comment]
没啥问题，应该要去掉这个提示。swap本来就不是为了挂载的

**Comment by N1k1Zhang** [comment]
收到，谢谢了

**Comment by jjm2473** [comment]
已修复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2550/1
