### ISSUE TITLE
编译的时候dax.so miss

### ISSUE THREAD

**Issue by houandy** [istoreos/istoreos#1205]
ntering directory '/workspace/istoreos-rtd129x-build/istoreos/package/kernel/linux'
mkdir -p /workspace/istoreos-rtd129x-build/istoreos/staging_dir/target-aarch64_cortex-a53_musl/root-realtek/stamp

SHELL= flock /workspace/istoreos-rtd129x-build/istoreos/tmp/.root-copy.flock -c 'cp -fpR /workspace/istoreos-rtd129x-build/istoreos/build_dir/target-aarch64_cortex-a53_musl/linux-realtek_rtd129x/packages/.pkgdir/kernel/. /workspace/istoreos-rtd129x-build/istoreos/staging_dir/target-aarch64_cortex-a53_musl/root-realtek/'
touch /workspace/istoreos-rtd129x-build/istoreos/staging_dir/target-aarch64_cortex-a53_musl/root-realtek/stamp/.kernel_installed
ERROR: module '/workspace/istoreos-rtd129x-build/istoreos/build_dir/target-aarch64_cortex-a53_musl/linux-realtek_rtd129x/linux-4.9.282/drivers/dax/dax.ko' is missing.
make[3]: *** [modules/block.mk:220: /workspace/istoreos-rtd129x-build/istoreos/bin/targets/realtek/rtd129x/packages/kmod-dax_4.9.282-1_aarch64_cortex-a53.ipk] Error 1
make[3]: Leaving directory '/workspace/istoreos-rtd129x-build/istoreos/package/kernel/linux'
time: package/kernel/linux/compile#1.48#0.14#1.60
    ERROR: package/kernel/linux failed to build.
make[2]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[2]: Leaving directory '/workspace/istoreos-rtd129x-build/istoreos'
make[1]: *** [package/Makefile:110: /workspace/istoreos-rtd129x-build/istoreos/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workspace/istoreos-rtd129x-build/istoreos'
make: *** [/workspace/istoreos-rtd129x-build/istoreos/include/toplevel.mk:234: world] Error 2

**Comment by jjm2473** [comment]
开源内核代码不支持rtd1296，需要使用闭源的内核代码。并且rtd1296不提供任何支持。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2549/1
