### ISSUE TITLE
首页和网络向导没了

### ISSUE THREAD

**Issue by wuai1024** [istoreos/istoreos#1207]
如题，我的首页和网络设置向导不见了。我在删除软件包的时候可能不小心勿删了。 现在这样显示了
![image](https://github.com/istoreos/istoreos/assets/13379708/732e00c9-4e71-4502-adec-fe26e53e455e)

我希望能重新安装回来，但是我不知道是哪个包，有知道的，希望能告知下。

**Comment by jjm2473** [comment]
修复下就行了 https://github.com/istoreos/istoreos/wiki/FAQ

**Comment by linnvirgo** [comment]
所以是删了什么呀，我刚好想删掉那两个

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2547/1
