### ISSUE TITLE
X86 外网测速减半

### ISSUE THREAD

**Issue by weiyideai520** [istoreos/istoreos#1208]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A： 外网测速减半

### (2) 路由器型号和固件版本

A：X86主机，iStoreOS 22.03.5 2023121510 / LuCI istoreos-22.03 branch git-23.342.39264-37c783a

### (3) 详细日志和/或截图

A：内外持续压力测速
<a href="https://imgse.com/i/piHb7qA"><img src="https://s11.ax1x.com/2023/12/25/piHb7qA.png" alt="piHb7qA.png" border="0" /></a>

B：外网测速（iStoreOS）
<a href="https://imgse.com/i/piHbqat"><img src="https://s11.ax1x.com/2023/12/25/piHbqat.png" alt="piHbqat.png" border="0" /></a>

C：电脑直连光猫测速
<a href="https://imgse.com/i/piHqFI0"><img src="https://s11.ax1x.com/2023/12/25/piHqFI0.png" alt="piHqFI0.png" border="0" /></a>

**Comment by weiyideai520** [comment]
网卡信息
```
root@UN45:~# ethtool -i eth0
driver: r8169
version: 5.10.176
firmware-version: rtl8168h-2_0.0.2 02/26/15
expansion-rom-version: 
bus-info: 0000:02:00.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```

CPU信息：Intel(R) Celeron(R) CPU N3150 @ 1.60GHz

**Comment by weiyideai520** [comment]
网卡信息
```
root@UN45:~# ethtool -i eth0
driver: r8169
version: 5.10.176
firmware-version: rtl8168h-2_0.0.2 02/26/15
expansion-rom-version:
bus-info: 0000:02:00.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```

**Comment by weiyideai520** [comment]
网络-防火墙-路由/NAT 分载

✔软件流量分载
✔硬件流量分载

后测速从5xxMbps 提升到 7xxMbps，还是没办法实现满速的 9xxMbps

**Comment by jjm2473** [comment]
https://github.com/istoreos/istoreos/issues/1150

**Comment by shengnannan** [comment]
同有此问题。
软路由：康耐信的n4100，英特尔2.5G网卡。
猫：vsol 2.5G
硬路由：中兴巡天PRO+ AX3000

硬路由拨号，可以跑满千兆宽带。
软路由拨号，只可以跑到730M上下。
内网测速正常。

用提供的方法也是无效的：“打开后台，网络-接口-全局网络选项，勾选“数据包引导”试试，可能要重启下。

（注意：非x86平台用户不需要配置，一般都有初始化脚本配置好了。）”

**Comment by xkdvSrPD** [comment]
相同的问题，500兆宽带
![Image](https://github.com/user-attachments/assets/65f706b1-267c-4d50-8111-76eca702221a)

![Image](https://github.com/user-attachments/assets/aacc0b99-4868-42e7-b910-b6799c4e7edc)

**Comment by jjm2473** [comment]
如果是x86平台，且使用realtek网卡，可以试试在系统-杂项设置-驱动中选择相应的驱动。然后重启。

全平台通用的加速方式：
1. 网络-防火墙，“FullCone-NAT” 选择“禁用”或者“高性能模式”
2. 网络-防火墙，“流量卸载类型” 选择 “软件流量卸载”
3. 网络-接口-全局网络选项，勾选“数据包引导”，可能要重启

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2546/1
