### ISSUE TITLE
[BUG]Docker根目录迁移RAID分区后，无法正常启动

### ISSUE THREAD

**Issue by hk519** [istoreos/istoreos#1211]
## 1.关于你要提交的问题

* [x] 没有类似的issue

### (1) 具体问题

A：Docker根目录选择RAID分区后，Docker启动异常（在挂载RAID分区前先启动了Docker）：
![1](https://github.com/istoreos/istoreos/assets/38304523/606f51e9-90cf-4d22-a54f-d4f04060d1cd)

### (2) 路由器型号和固件版本

A：
固件版本：iStoreOS 22.03.5 2023121510
镜像：istoreos-22.03.5-2023121510-x86-64-squashfs-combined
VMware Workstation 17.5
![3](https://github.com/istoreos/istoreos/assets/38304523/e69c769c-38ce-44cf-b60f-ef75c2914af4)
![4](https://github.com/istoreos/istoreos/assets/38304523/5efd93e1-eb98-4661-9947-5e3f982e8445)

**Comment by hk519** [comment]
查看日志，发现Docker启动早于分区挂载，重启iStoreOS后，必须重启Docker一次才能正常使用。

**Comment by jjm2473** [comment]
md0占用0B，要么迁移失败了，要么就是启动以后没有挂载

**Comment by jjm2473** [comment]
应该要把挂载点设置到/mnt里面的，例如/mnt/raid。
如果硬盘加载比较慢，导致docker启动时raid还没挂载。“系统”-“杂项设置”-“启动”可以配置等待硬盘分区，下个固件支持等待raid盘

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2544/1
