### ISSUE TITLE
请教，无线热点可以自定义网关信息吗？

### ISSUE THREAD

**Issue by weiyideai520** [istoreos/istoreos#1212]
我现在使用的旁路由模式

DHCP由主路由分发
 
我现在已经在软路由（iStoreOS） 上开启了无线热点

手机连接软路由的热点，IP是是主路由的DHCP分配的，由于主路由的DHCP的网关指向的是主路由。

我想的是，手机连接软路由的热点，网关可以指向软路由，不知如何实现

**Comment by hk519** [comment]
DHCP在主路由上的话，怎么设置DHCP和你的主路由有关，有的路由器不能自定义DHCP下发的网关。

**Comment by weiyideai520** [comment]
主要还是 软路由做主路由的跑不满宽带。

所以我想的是，在软路由上开 WiFi，所有连接软路由的设备在获取DHCP时，
拉取的网关信息就是 软路由的IP
（有一些设备，不支持手段修改IP）

这样，只有连接软路由的WiFi就是自动走代理了

**Comment by hk519** [comment]
最简单的办法就是软路由使用路由模式，不要桥接就好

**Comment by jjm2473** [comment]
关掉硬路由的dhcp服务，让软路由提供dhcp服务，怎么改都行

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2543/1
