### ISSUE TITLE
防火墙不加自定义规则【iptables -t nat -I POSTROUTING -j MASQUERADE】就不能上网

### ISSUE THREAD

**Issue by cocollin23** [istoreos/istoreos#1213]
配置：主路由，双网口，PPPOE拨号模式，下游桥接无线路由做ap，上游桥接光猫
问题：当主路由不开启科学软件时，路由本身和下游设备（无线和有线连接）均不能联网，lan口勾选ip动态伪装，取消勾选 “发送 ICMP 重定向”后，问题依旧；当主路由开启科学软件后，只能访问被墙网站，其他网站依然打不开，路由器本身有网路；防火墙添加规则iptables -t nat -I POSTROUTING -j MASQUERADE】后，网络正常。

**Comment by jjm2473** [comment]
查看置顶的issue

**Comment by cocollin23** [comment]
按照你的方式设置后是无效的，只能加这条规则

**Comment by cocollin23** [comment]
而且你置顶的是旁路由，我的是主路由

**Comment by jjm2473** [comment]
不开翻墙插件，重启机器能解决吗

**Comment by jjm2473** [comment]
还有，你用的翻墙插件是什么，openclash？从哪下载的？

**Comment by cocollin23** [comment]
工具用的passwall，群连接第二个下载的，不开翻墙重启防火墙没法解决，没试过重启机器，添加自定义规则重启防火墙就可以上网了，抓取过日志，问题是防火墙勾选ip动态伪装不生效，只能添加自定义，已重置软路由，问题已解决，不能复现了，应该是个例！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2542/1
