### ISSUE TITLE
docker如何安装chrome浏览器，

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1216]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
oldiy/chrome-novnc:latest
selenium/standalone-chrome:latest
docker如何安装浏览器，实在是不会用不了，镜像能下载啊安装了就是不行，有没有手把手教的教程，试过威联通能安装，也简单，就是istore的界面剂就看不懂，还是这个镜像是不通用的
### (1) 具体问题

A：FriendlyElec NanoPi R6S

### (2) 路由器型号和固件版本

A：FriendlyElec NanoPi R6S
iStoreOS 22.03.5 2023121510 / LuCI istoreos-22.03 branch git-23.342.39264-37c783a

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
https://hub.docker.com/r/linuxserver/chromium

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2540/1
