### ISSUE TITLE
docker 端口暴露

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1222]
docker的创建容器的时候端口暴露那里如何填写，能够用路由ip直接登陆容器，试过直接填写端口号好似不行
![image](https://github.com/istoreos/istoreos/assets/96804858/5c2fbfde-f853-4ed6-9564-0585a9853464)

**Comment by jjm2473** [comment]
这个端口暴露只是表示容器内的端口映射到宿主，局域网内肯定可以使用路由器ip访问了，但是外网访问需要宿主自己的防火墙允许。

**Comment by pili-book** [comment]
就是如何填写这地方了，，如何填写暴露到宿主机了，直接填一个端口号好像不行



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年1月2日(周二) 中午11:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] docker 端口暴露 (Issue #1222)




 
这个端口暴露只是表示容器内的端口映射到宿主，局域网内肯定可以使用路由器ip访问了，但是外网访问需要宿主自己的防火墙允许。

**Comment by jjm2473** [comment]
都说了你截图的只是容器内的端口映射到宿主。如果你要外网访问，还要去防火墙页面“通信规则”增加端口开放（默认有个“linkease”的规则，你可以参考）。如果是内网访问则不需要修改防火墙。

**Comment by jjm2473** [comment]
暴露到宿主机只需要端口就行了啊，但是你确定自己填的端口没被使用？例如22端口肯定被宿主的ssh服务占用了。

**Comment by pili-book** [comment]
好的，我再研究下



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年1月2日(周二) 中午1:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] docker 端口暴露 (Issue #1222)




 
暴露到宿主机只需要端口就行了啊，但是你确定自己填的端口没被使用？例如22端口肯定被宿主的ssh服务占用了。
