### ISSUE TITLE
新版22.03.5是否对web地址进行了设置？

### ISSUE THREAD

**Issue by Vip4pt** [istoreos/istoreos#1224]
在上一个版本的时候 我的主路由是192.168.0.1
然后istoreos过去的dhcp地址为192.168.0.100

因为经常需要用到主路由 istoreos作为单独的辅助其他iot设备进行统一管理

当我设备在主路由0.1上面的时候不能从0.100进入软路由的管理

**Comment by jjm2473** [comment]
看看防火墙的wan区域是不是禁止入站，现在默认是禁止的。 https://github.com/istoreos/istoreos/discussions/1164

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2535/1
