### ISSUE TITLE
家装了MT7921无线网卡，怎么查看自己软路由的主板，以及怎么选择 应该刷哪个镜像？

### ISSUE THREAD

**Issue by sunwenju1991** [istoreos/istoreos#1226]
家装了MT7921无线网卡，怎么查看自己软路由的主板，以及怎么选择 应该刷哪个镜像？

**Comment by jjm2473** [comment]
https://doc.linkease.com/zh/guide/istoreos/ 看看左侧的系统安装，如果除了x86是通用的，其他固件都按机型匹配，如果没有列出，说明不支持

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2533/1
