### ISSUE TITLE
系统挂载点出现了一大堆类似的overlay挂载分区，请教什么原因？能否删除

### ISSUE THREAD

**Issue by NJYZ-96** [istoreos/istoreos#1231]
反馈bug/问题模板，提建议请删除

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [X] 没有类似的issue
我搜索了，没看到类似的
### (1) 具体问题

A：偶然发现系统挂载点出现一大堆类似的overlay挂载分区，请教什么原因？能否删除

### (2) 路由器型号和固件版本

A：型号 JP TVbox RK3566

固件版本 | iStoreOS 22.03.5 2023092815 / LuCI istoreos-22.03 branch git-23.271.10849-b445bc4
内核版本：5.10.176

### (3) 详细日志和/或截图

A：
![截图_20240104113403](https://github.com/istoreos/istoreos/assets/125748593/13e1c465-8eee-44ae-9d02-d0eb905d8d36)

![截图_20240104112955](https://github.com/istoreos/istoreos/assets/125748593/17cea824-53da-41d6-a209-99e2e969ca54)

**Comment by jjm2473** [comment]
只是docker创建的，不需要关注，一般一个容器对应一个挂载点。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2527/1
