### ISSUE TITLE
请问iStoreOS怎么设置DMZ区域

### ISSUE THREAD

**Issue by xzzcx** [istoreos/istoreos#1232]
请问iStoreOS怎么设置DMZ区域

**Comment by jjm2473** [comment]
DMZ就是全部端口转发，使用端口转发功能就行了，支持端口范围。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2526/1
