### ISSUE TITLE
istoreos间歇下载和间歇性cpu占用高，每天会有大量的不明流量下载！

### ISSUE THREAD

**Issue by cocollin23** [istoreos/istoreos#1246]
（1）主要问题
主路由模式下，istoreos会不断的进行下载和上传！导致cpu占用间歇性占用高！
未重置前，每天上午十点和下午六点左右会进行大量下载，每天下载量达100G以上，重置后没用备份恢复，现在的问题是会进行间歇性下载！
（2) 路由器型号和固件版本
![image](https://github.com/istoreos/istoreos/assets/143804546/d38dfe5c-e434-4ef9-ab0f-02e50793e72c)
（3）详细日志和截图
系统日志
![image](https://github.com/istoreos/istoreos/assets/143804546/488577b0-445f-43cb-8290-fc52839add09)
网络占用
![image](https://github.com/istoreos/istoreos/assets/143804546/c617ae2f-ce60-4d63-ad14-57a5ae56f6e0)
cpu占用
![image](https://github.com/istoreos/istoreos/assets/143804546/09633a5b-2940-4718-9496-9e1a076db8f4)
5分钟内的下载
![image](https://github.com/istoreos/istoreos/assets/143804546/4b664cef-cd39-44d7-b8ae-3abd59f28a40)
系统进程
![image](https://github.com/istoreos/istoreos/assets/143804546/37336460-ac3c-4516-ace9-a89b81a157a9)
![image](https://github.com/istoreos/istoreos/assets/143804546/aa4703c3-1680-48e5-bbae-0e8a02d1a579)
![image](https://github.com/istoreos/istoreos/assets/143804546/1c508e49-74c3-4e84-9e88-1ca5475b309d)
![image](https://github.com/istoreos/istoreos/assets/143804546/bcbe1a32-a0ca-4f72-8fa9-16daffca2b14)
![image](https://github.com/istoreos/istoreos/assets/143804546/93af1e85-0878-449b-a2c5-64b79e56f35b)
![image](https://github.com/istoreos/istoreos/assets/143804546/8710649a-422a-486f-9130-618268e456e4)
![image](https://github.com/istoreos/istoreos/assets/143804546/da2fce18-1021-46ab-b816-309667bd2006)
![image](https://github.com/istoreos/istoreos/assets/143804546/c00e0139-5ad8-43b0-a53d-74931225e144)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2518/1
