### ISSUE TITLE
ipv6到底咋 开？

### ISSUE THREAD

**Issue by Joker-lm** [istoreos/istoreos#1248]
ipv6到底咋开嘛？也没个教程。。。。网上教程都不一样，没一个能用的

**Comment by dalaoshi777** [comment]
首先需要你家里宽带支持ipv6，如果是软路由拨号，ipv6是自动默认开启的，光猫拨号就用nat6

**Comment by ilovetaimei** [comment]
> 首先需要你家里宽带支持ipv6，如果是软路由拨号，ipv6是自动默认开启的，光猫拨号就用nat6
光猫拨号软路由新建个wan6的虚拟接口？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2516/1
