### ISSUE TITLE
建议在把网口设置为DHCP客户端时(新增MAC地址重设子项，用于修改DHCP客户端的MAC地址)

### ISSUE THREAD

**Issue by mayluoyi** [istoreos/istoreos#1249]
需求来源：当想要将运营商的IPTV，通过组播转单播在家庭局域网共享时让多台设备自由同时观看时，需通过运营商自带DHCP验证，需将虚拟的DHCP客户端，在通过运营商认证时，提供与机顶盒同样的MAC地址、ID信息等相关必要认证信息。如无法重置MAC。那么软路由某一网口虚拟DHCP的MAC地址将于IPTV机顶盒认证的地址不符，认证将会失败。
我看过别人家的固件，是有这个功能的。但是不知道为什么IsotreOS里面 少了这个子项，还希望添加上。现附图。
图一为别人的固件，设置网口类型为DHCP客户端时的选项。
<img width="684" alt="1" src="https://github.com/istoreos/istoreos/assets/65268751/f744ba3c-3824-4029-b7d0-9a485f432569">
这张是目前Isotre的网口设置为DHCP客户端的选项
<img width="807" alt="2" src="https://github.com/istoreos/istoreos/assets/65268751/649559a3-ef38-4c87-bf0d-93731169d09c">

**Comment by jjm2473** [comment]
mac地址在网络-接口-设备里面配置，如果你要复用其他的网口，又希望改变mac地址，那也可以在网络-接口-设备添加一个macvlan的虚拟设备

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2515/1
