### ISSUE TITLE
daemon.err odhcpd[11286]: Failed to send to ff02::1%dmz_dianxin@eth1 (Address not available)

### ISSUE THREAD

**Issue by bupahaibao** [istoreos/istoreos#1250]
![1704946103732](https://github.com/istoreos/istoreos/assets/67363931/05ce8430-7bca-4e99-ac9f-9d865d02fca1)
有人知道这是啥问题，怎么解决吗？

**Comment by dalaoshi777** [comment]
我也是一样，不过没有什么影响

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2514/1
