### ISSUE TITLE
MT7921无线网卡设置问题

### ISSUE THREAD

**Issue by 2253845067** [istoreos/istoreos#1251]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：正常设置MT7921无线网卡，安卓和电脑可以正常连接，苹果设备能搜到WiFi，却连不上，在其他固件上用同样的WiFi设置可以正常连接，  istoreos不管是自编译还是官方都没办法正常连接，想知道下苹果设备应该如何设置才可以正常连接上

### (2) 路由器型号和固件版本

A：
设备 H69K

固件版本 istoreos-22.03.5-2023122916-h6xk-squashfs-combined.img.gz

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/38485078/c33d432c-8c86-4829-9bd4-dad1d5875ab0)

[istoreos-22.03.5-2023122916-h6xk-squashfs-combined.img.gz](https://fw0.koolcenter.com/iStoreOS/h6xk/istoreos-22.03.5-2023122916-h6xk-squashfs-combined.img.gz)

**Comment by jjm2473** [comment]
高级设置试试选择国家为“China”，还有信道选择157试试

**Comment by 2253845067** [comment]
> 高级设置试试选择国家为“China”，还有信道选择157试试

默认就是China，连不上就改了us，157信道确实没尝试过，改为自动信道的话就时断时续的

**Comment by jjm2473** [comment]
你的苹果手机哪一年产的，支持wifi6吗？你先试试把wifi的AX改成AC

**Comment by 2253845067** [comment]
> 你的苹果手机哪一年产的，支持wifi6吗？你先试试把wifi的AX改成AC

手机是14pm，平板是ipad2021，有时间我试试看ax改ac，现在用的大雕的固件，一样的设置可以正常连接

**Comment by 2253845067** [comment]
切换到AC模式就可以正常连接了，速度也正常
![image](https://github.com/istoreos/istoreos/assets/38485078/5f55a205-d99a-4777-aa02-fd7a7df922a3)

**Comment by jjm2473** [comment]
那就是wifi6的兼容性问题，尤其老设备很容易遇到。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2513/1
