### ISSUE TITLE
沙箱功能不能利用存储卡后面空闲区域作为沙箱空间吗？

### ISSUE THREAD

**Issue by haobinnan** [istoreos/istoreos#1254]
问题如题。

**Comment by haobinnan** [comment]
<img width="576" alt="image" src="https://github.com/istoreos/istoreos/assets/31329170/35adfa6c-cc81-4d51-83d4-13fe9837d1dc">
<img width="782" alt="image" src="https://github.com/istoreos/istoreos/assets/31329170/94f33e07-612f-4fdf-be9f-ef5fd19c6983">

**Comment by jjm2473** [comment]
假设沙箱里面配置错误，导致后台都进不去了，如果是U盘或者外部硬盘，你还能靠关机拔掉硬盘来解决。要是内部存储，就没办法了，只能重刷或者恢复出厂设置。
虽然有些人拿沙箱作为扩容的方式，但根目录没有扩容的必要，把docker和下载目录放在你的扩展分区或者外部硬盘就行，插件你再怎么安装都不可能用完2GB。

**Comment by haobinnan** [comment]
> 假设沙箱里面配置错误，导致后台都进不去了，如果是U盘或者外部硬盘，你还能靠关机拔掉硬盘来解决。要是内部存储，就没办法了，只能重刷或者恢复出厂设置。 虽然有些人拿沙箱作为扩容的方式，但根目录没有扩容的必要，把docker和下载目录放在你的扩展分区或者外部硬盘就行，插件你再怎么安装都不可能用完2GB。

明白了，感谢回答。

**Comment by jdydhking** [comment]
沙箱所在的存储介质可以存储资料吗，会不会关闭沙箱后文件会被删除？

**Comment by jjm2473** [comment]
@jdydhking 多分一个区不就行了，其他数据为啥要跟沙箱同一个分区存储

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2511/1
