### ISSUE TITLE
T68M USB 无法识别

### ISSUE THREAD

**Issue by Gq138** [istoreos/istoreos#1255]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：T68M软路由无法识别usb3.0

### (2) 路由器型号和固件版本

A：t68m   

A：最新固件版 22.03.6-2024011211-t68m-squashfs.img.gz
### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
可能OTG不支持自动切换，之后会在开机脚本里切换到Host模式。

你现在可以执行这个命令看USB是不是能正常使用：
`echo host >/sys/kernel/debug/usb/fcc00000.dwc3/mode`

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2510/1
