### ISSUE TITLE
是否可以在istoreos内加入SFE和BBR两种加速技术

### ISSUE THREAD

**Issue by bailuxianfeiying** [istoreos/istoreos#1256]
![Screenshot_20240113_091518_com android browser](https://github.com/istoreos/istoreos/assets/136351769/a3100a6e-257c-4965-95fb-35a038c1ddcb)
对于像H28K这样的arm设备，这两个加速技术应该可以增强网络性能

**Comment by jjm2473** [comment]
SFE不就是offload吗，防火墙页面就可以开。BBR在路由器上一般没什么用，反而可能导致莫名其妙的问题，例如samba速度异常

**Comment by bailuxianfeiying** [comment]
好像sfe和offload有点区别，sfe可能性能更好？

**Comment by jjm2473** [comment]
那你有空可以对比下

**Comment by VwEl** [comment]
> 那你有空可以对比下

sfe性能会更高点，所以大伙呼声这么高，就加一个呗

**Comment by HernandoR** [comment]
related #352

**Comment by jjm2473** [comment]
SFE可能会引入兼容性问题。offload是linux内核和openwrt官方支持的，同样也是软件实现的流卸载。如果sfe性能比offload好，那就提供性能对比数据。或者反馈给openwrt社区，让openwrt支持sfe，既然这东西这么好他们应该不会拒绝。我认为内核4.19以前SFE可能还有用，但现在都已经有类似的offload，还要SFE干嘛。

BBR内核支持倒是简单，之后可以加上，不过不会默认启用。

**Comment by jjm2473** [comment]
如果是x86或者rk33xx系列，或者rpi4，在软件包里面搜索 kmod-tcp-bbr 安装就可以使用bbr了（安装后可能要重启下，自动切换到bbr，不需要设置），但是如果遇到samba速度或其他网络速度异常，不要反馈。

**Comment by jjm2473** [comment]
h28k就算不开offload都能跑满千兆PPPoE了，还有必要去折腾sfe或bbr吗

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2509/1
