### ISSUE TITLE
请istoreos给rtl8814au 添加驱动，万分感谢

### ISSUE THREAD

**Issue by bg2vcj** [istoreos/istoreos#1259]
请istoreos给rtl8814au 添加驱动，或者告知安装这个驱动的方法，万分感谢

**Comment by jjm2473** [comment]
不想搞usb wifi驱动，都是些鸡肋的设备，如果未来内核自带了驱动，可能会集成

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2506/1
