### ISSUE TITLE
請問 docker 遷移的分區容量大小限制，是否可以考慮適度縮小一些

### ISSUE THREAD

**Issue by TomFoxLee** [istoreos/istoreos#1261]
iStoreOS 團隊您好。我的機型是 "FriendlyElec NanoPi R2S"，目前使用的 iStoreOS 版本是 "iStoreOS 22.03.6 2024011211"

由於 R2S 本身性能並不算很強，所以之前我都只是拿它當最基本的主路由使用，沒想用過 docker，直到前不久換到 iStoreOS 的時候，發現已內建 docker 且建議遷移到系統分區以外的地方，才頭一次注意到這也能用 docker？

我在 R2S 上用的是 8GB 的 TF 卡，在裝完 iStoreOS 之後，還有 4GB 多的空間閒置，想用遷移嚮導把 docker 遷移到這個（已掛載到 /mnt/mmc0-4 ） 4GB 的分區，但是嚮導上出現小於 8GB 的限制提示無法遷移。

如果說 iStoreOS 本身留給系統分區大概 2GB 左右的大小，並且也允許 docker 在未遷移的情況下使用，那麼在前述 4GB > 2GB 空間的情形下，似乎把 docker 遷移到 4GB 閒置空間應該可行？

還請開發團隊考慮一下，是不是把限制下調一些，讓大家還是有機會可以充分利用一下剩餘空間。或者是不是有什麼手動的方式可以跳過限制達到遷移的目的？Linux 和 docker 都不熟悉，所以還得求大神們指點了。。。

非常感謝！

**Comment by jjm2473** [comment]
如果你之前没用过docker，不需要迁移数据，只是为了切换目录，那么你先配置好固定的挂载点（例如把新分区挂载到/mnt/data），然后手动修改 Docker 根目录就行。具体位置在后台的“Docker”-“配置”-“Docker 根目录”，如果你的挂载点是/mnt/data，那这里应该填 /mnt/data/docker/dockerd，注意一定要子目录。

**Comment by jjm2473** [comment]
R2S的内存很小，估计也玩不了啥 Docker

**Comment by TomFoxLee** [comment]
> R2S的内存很小，估计也玩不了啥 Docker

確實是這樣，所以我之前壓根就沒想過這玩意還能裝 docker 用，直到發現 iStoreOS 內建。。。

**Comment by jjm2473** [comment]
因为iStoreOS编译时多个目标板共用同一个rootfs和kernel的，例如R2S，R4S，R4SE都是使用rk33xx的rootfs和kernel，这几个板子的固件除了uboot和dtb文件不一样，其他部分完全一样。

**Comment by jjm2473** [comment]
如果自己编译单独一个板子的话，可以去掉不需要的功能。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2504/1
