### ISSUE TITLE
22.03.6-2024011211-x86-64升级报错，貌似网卡失效

### ISSUE THREAD

**Issue by leonedit** [istoreos/istoreos#1262]
详细叙述

### (1) 具体问题

A：22.03.6-2024011211-x86-64升级报错，卡在RTL8226B_RTL8221B 2.5Gbps PHY r8169-0-200:00，提示：No native access to PCI extended config space，falling back to CSI

### (2) 路由器型号和固件版本

A：路由型号：N5095 x86-64，固件版本：istoreos-22.03.6-2024011211-x86-64-squashfs-combined-efi.img.gz

**Comment by jjm2473** [comment]
跟这个bug一样 #1257

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2503/1
