### ISSUE TITLE
istoreos 如何安装portainer，安装后找不到本地环境

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1265]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：FriendlyElec NanoPi R6S

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
你把/var/run/docker.sock映射进portainer容器了吗

**Comment by pili-book** [comment]
没有，直接创建容器正常安装好，好似这东西必须代码安装，直接安装不行



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年1月16日(周二) 中午12:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] istoreos 如何安装portainer，安装后找不到本地环境 (Issue #1265)




 
你把/var/run/docker.sock映射进portainer容器了吗

**Comment by dalaoshi777** [comment]
> 没有，直接创建容器正常安装好，好似这东西必须代码安装，直接安装不行
> […](#)
> ---原始邮件--- 发件人: "Liangbin ***@***.***&gt; 发送时间: 2024年1月16日(周二) 中午12:49 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [istoreos/istoreos] istoreos 如何安装portainer，安装后找不到本地环境 (Issue #1265) 你把/var/run/docker.sock映射进portainer容器了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

就算直接用ui建这个容器也是需要把/var/run/docker.sock映射进portainer容器的

**Comment by jjm2473** [comment]
不管怎么安装的，portainer需要/var/run/docker.sock来跟dockerd服务通信。你肯定没好好看portianer的安装教程。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2501/1
