### ISSUE TITLE
H28K rtc驱动问题

### ISSUE THREAD

**Issue by cdz-me** [istoreos/istoreos#1267]
设备型号：Hlink H28K
固件版本：iStoreOS 22.03.6 2024011211
内核版本：5.10.201

故障描述
root@iStoreOS:/etc# hwclock
hwclock: can't open '/dev/misc/rtc': No such file or directory

问题定位
疑似rtc的驱动节点没打包上。

**Comment by jjm2473** [comment]
这有什么用？用date命令不行？

**Comment by cdz-me** [comment]
> 这有什么用？用date命令不行？

自己平时使用与设置都是系统时间date，但是有些软件使用、日志记录用的是硬件时间。查log的时候还得换算时间差。

**Comment by jjm2473** [comment]
啥意思？为什么要换算时间，date不是本地时间吗？什么软件会使用hwclock命令获取时间？

**Comment by jjm2473** [comment]
H28K有硬件RTC吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2500/1
