### ISSUE TITLE
无法进入系统>启动项，界面显示 Error XHR request timed out

### ISSUE THREAD

**Issue by bizshow** [istoreos/istoreos#1268]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：刚开机时，动作快的话，可以进入系统>启动项，两个tab的内容都能看到。但是启动过一会（大概一两分钟）后，就无法进入了，界面显示 “Error XHR request timed out”，并且之后也一直无法进入。

### (2) 路由器型号和固件版本

A：FriendlyElec NanoPi R2S
iStoreOS 22.03.6 2024011211

### (3) 详细日志和/或截图

A：![image](https://github.com/istoreos/istoreos/assets/42473885/716dfdd4-17ba-42ed-9cf3-7ef325a49056)
如果需要系统日志的话，稍后再附上

**Comment by jjm2473** [comment]
看看浏览器请求，是不是很长时间都没加载完数据

**Comment by bizshow** [comment]
![image](https://github.com/istoreos/istoreos/assets/42473885/ebe6384e-5a4b-4f0b-a2d3-8115b5873093)

![image](https://github.com/istoreos/istoreos/assets/42473885/46585e10-5a28-4344-8136-95dc9b06c265)

确实，问题出在如上图的请求中。

**Comment by bizshow** [comment]
我自己通过构造同样的post请求以后，在执行到30s左右会返回这个响应：
`[{"jsonrpc":"2.0","id":2,"result":[0,{"data":"# Put your custom commands here that should be executed once\n# the system init finished. By default this file does nothing.\n\nln -s /proc/self/fd /dev/fd\n/etc/init.d/uhttpd start\nnginx\n\nexit 0\n"}]}`

**Comment by jjm2473** [comment]
估计是某个插件的init脚本有bug，导致一调用就卡死。在浏览器加载的过程中，终端执行`ps ww|grep init.d`，把结果发出来看看。

**Comment by huanhxkx** [comment]
我的x86小主机，也是开机就会卡死，后面刷了老版本就好了，现在北京敢更新，已更新就会无法进入系统，无论是ｕ盘启动还是刷入到硬盘里，都是一样

**Comment by jjm2473** [comment]
@huanhxkx 你的是RTL8125网卡？不要使用20240112版本就行了

**Comment by bizshow** [comment]
> 估计是某个插件的init脚本有bug，导致一调用就卡死。在浏览器加载的过程中，终端执行`ps ww|grep init.d`，把结果发出来看看。

<img width="854" alt="image" src="https://github.com/istoreos/istoreos/assets/42473885/5b71bf58-dd24-4a7d-8fd3-d523c0670934">
附上进入时，终端里的输出

**Comment by bizshow** [comment]
<img width="653" alt="image" src="https://github.com/istoreos/istoreos/assets/42473885/808177a3-8a6e-4e99-baea-c94620b34a1c">

问题可能出在 {dockerd} /bin/sh /etc/rc.common /etc/init.d/dockerd enabled 上
多次进入时，会有多个进程在跑

**Comment by jjm2473** [comment]
把你的 `/etc/init.d/dockerd` 提取出来看看，还有卡住的时候执行`ps ww|grep ubus; ubus call service list '{"name":"dockerd"}'`看看

**Comment by bizshow** [comment]
> 把你的 `/etc/init.d/dockerd` 提取出来看看，还有卡住的时候执行`ps ww|grep ubus; ubus call service list '{"name":"dockerd"}'`看看

<img width="824" alt="image" src="https://github.com/istoreos/istoreos/assets/42473885/566b16b6-020d-4c2b-a3a5-e1c44f7461b0">

卡住的时候，执行命令显示上面的内容

**Comment by bizshow** [comment]
[dockerd.zip](https://github.com/istoreos/istoreos/files/14061184/dockerd.zip)
上面是 /etc/init.d/dockerd 文件

**Comment by jjm2473** [comment]
你自己执行`time /etc/init.d/dockerd enabled`会卡住吗？还有执行`time ubus call service list '{"name":"dockerd"}'`看看命令执行了多长时间

**Comment by star8020** [comment]
同样的问题，硬盘休眠也进不去。

**Comment by jjm2473** [comment]
@star8020 你的估计是因为硬盘坏了

**Comment by Somnr123** [comment]
> 看看浏览器请求，是不是很长时间都没加载完数据

同样的问题，电脑出现XHR request  
但是同网络下手机访问却没有问题![image](https://github.com/istoreos/istoreos/assets/107115628/d660723d-74b7-4109-b4c1-ee2c71ad339d)

**Comment by jjm2473** [comment]
@Somnr123  可能电脑翻墙了？换个浏览器，或者浏览器清理缓存试试？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2499/1
