### ISSUE TITLE
能否在系统内配置风扇IO实现自动控温

### ISSUE THREAD

**Issue by WJ-JAY** [istoreos/istoreos#1269]
我用的是树莓派4，用的是“同伴科技”的套件，带了风扇模块，烧录istoreos后风扇长转，没法正常控温，看能否自定义风扇控制的IO，或者你们后续会有更好的方案解决这个问题吗？

**Comment by jjm2473** [comment]
如果是gpio或者pwm控制的，可以修改dts（设备树）实现温控。但是，如果板子本身没有风扇接口，gpio或pwm是自定义的，那固件不可能在dts里面定义好温控策略，就自己找找温控脚本吧。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2498/1
