### ISSUE TITLE
N100无法调用核显

### ISSUE THREAD

**Issue by gh61514** [istoreos/istoreos#1271]
天钡R1，最新版固件，plex，emby，jell都无法调用核显，ls /dev/dri/ 可以看到核显。

**Comment by gh61514** [comment]
plex跟emby都有会员，软件内配置也没什么问题，同样的配置unraid正常

**Comment by szkeum** [comment]
你用的哪个版本，我连ls dev/dri都看不到设备，用的是1月份正式版固件

**Comment by jjm2473** [comment]
跟会员没什么关系，jellyfin肯定不需要会员的。既然你能看到 /dev/dri/ ，那应该驱动没问题了，使用istore的jellyfin插件来部署试试。

**Comment by gh61514** [comment]
我都是用商店的插件，软件版本也是前几天发布的1月份最新版

**Comment by bcseputetto** [comment]
@gh61514 请注意，emby需要beta版本，也就是4.8版本才能支持较新的Intel 核心GPU，这是emby的问题，你需要切到beta镜像来安装容器
https://emby.media/community/index.php?/topic/121160-when-can-we-expect-the-release-of-the-official-48/

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1996/4

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1996/5

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2496/1
