### ISSUE TITLE
[功能请求]Docker容器的自定义排序/按照ABC顺序排列

### ISSUE THREAD

**Issue by OcrSu** [istoreos/istoreos#1273]
真的搞不明白容器排列原理，每次都是乱糟糟的，想找特定容器名字要挨个看。
不知是否变成按照像windows文件管理器的排列方式那样，abcdefg这样顺序排列。
或者自定义拖拽排列。

**Comment by jjm2473** [comment]
默认应该是按id顺序排的

**Comment by OcrSu** [comment]
> 默认应该是按id顺序排的

不太明白怎么修改id，用iStoreos商店装的docker应用的话，是自动安装配置的。

这个排序是小问题，优先级不高，只是提出来看看先。

**Comment by jjm2473** [comment]
id是docker自己生成的，没得改。我看看能不能支持点击表头排序，不过dockerman是用lua实现的，不是现代的js，支持的可能性不大

**Comment by jjm2473** [comment]
一般浏览器都支持 Ctrl+F 搜索的，所以要搜索的话肯定没问题。手机上麻烦些

**Comment by OcrSu** [comment]
> 一般浏览器都支持 Ctrl+F 搜索的，所以要搜索的话肯定没问题。手机上麻烦些

强迫症需求罢了是我的，不好开发就不搞了吧，QWQ，大佬太勤奋了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2494/1
