### ISSUE TITLE
3322域名解释404错误

### ISSUE THREAD

**Issue by rockanarki** [istoreos/istoreos#1274]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：3322域名解释404错误

### (2) 路由器型号和固件版本

A：x86 iStoreOS 22.03.6 2024011517 

解决办法：修改/usr/share/ddns/default/3322.org.json，把[members.3322.org] 更改为 [members.3322.net]

**Comment by jjm2473** [comment]
不是已经加上3322.net了吗？

**Comment by jjm2473** [comment]
<img width="559" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/e8031b75-39dc-42cf-ad58-a240ffc7f954">

如果你的设备没显示3322.net，那估计是你自己安装了其他版本的ddns-scripts

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2493/1
