### ISSUE TITLE
关于挂载网络存储的问题和建议

### ISSUE THREAD

**Issue by szkeum** [istoreos/istoreos#1280]
管理员你好，我用了网络存储-挂载网络共享，添加了smb局域网内群晖和威联通的共享盘，保存并应用后，在系统挂载里面并没有发现已挂载的盘，就是并未成功，不知道是什么问题。在windows电脑里是可以分别访问群晖和威联通的共享盘的。另外，建议在挂载网络共享里添加NFS协议，并能开机自启动。感谢！

**Comment by szkeum** [comment]
另外补充一下，在网络存储—NFS管理里面启用文件夹共享后，还需要手动ssh添加chmod 777给文件夹权限才能访问到，能都解决下简化流程，感谢！

**Comment by jjm2473** [comment]
NFS本来就是权限严格的，你要用合适的用户登录才行，不可能什么文件夹都搞成777。用samba就没问题，可以勾选强制root和集成所有者。

**Comment by jjm2473** [comment]
建议不要再搞NFS，以后会遇到更多问题，例如服务端或者客户端掉线，即使重连了却再也挂载不了，NFS基本不是一个可用的东西。

**Comment by szkeum** [comment]
我觉得NFS挺好用的，现在还没遇到啥问题，主要就是建议既然istoreos已经做了web设置页面，就顺便一起把这个功能加上，或者有这个功能但是个BUG修复一下就好了。

**Comment by jjm2473** [comment]
既然你要使用NFS，那就要了解用户组和权限的关系，只要你的登录用户组跟文件权限匹配，就不会访问不了。

**Comment by jjm2473** [comment]
NFS管理就支持挂载NFS。

samba挂载失败的话，执行`/etc/init.d/cifs start`看看有没有报错。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2486/1
