### ISSUE TITLE
强烈需求，cgroupV2 为内核默认。

### ISSUE THREAD

**Issue by gowy222** [istoreos/istoreos#1284]
很多docker容器已经默认需要cgroupV2为系统内核默认版本了..
另外nftables有计划上线？iptable官宣退役..性能瓶颈上限!
科学上网遇上iptable何苦呢...

**Comment by jjm2473** [comment]
怎么判断是不是 cgroupV2

**Comment by Vbaethon** [comment]
确实 ，需要nftables了

**Comment by jjm2473** [comment]
nftables的兼容性不好，有些插件还是要用iptables（我能想到的是oaf插件，可能还有其他的插件），两个混用容易出问题
