### ISSUE TITLE
istoreos 有没有密码错误次数保护

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1288]
比如某个ip登陆错误次数够了5次便拒绝5分钟这种

**Comment by jjm2473** [comment]
可以给openwrt提建议

**Comment by jjm2473** [comment]
不要一个问题发多个issue，嫌issue太少？

**Comment by pili-book** [comment]
用luck大吉转发的，我这是公网并不是穿透的，访问到路由页面后，这个有什么安全防护？



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年1月23日(周二) 下午2:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] istoreos 有没有密码错误次数保护 (Issue #1288)




 
不要一个问题发多个issue，嫌issue太少？

**Comment by jjm2473** [comment]
那就没有了，而且估计https加密都没。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2483/1
