### ISSUE TITLE
OneNav主题docker 更换

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1295]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：OneNav主题位于templates目录下，如果您不喜欢默认主题，可自行开发或者使用第三方主题。

注意：如果使用的Docker部署，主题位于挂载文件夹的templates目录下
适用于Docker方式安装
在您的挂载目录下创建一个templates目录，然后将主题解压至此目录
打开OneNav后台 - 系统设置 - 主题设置 - 选择要使用的主题
 官方说明是这样子的

但是我找不到这个所谓的挂载目录，当时镜像就是默认安装的，不知道挂载目录在哪
![image](https://github.com/istoreos/istoreos/assets/96804858/e117224a-2df1-4ade-9b98-f151b5b730b3)
![image](https://github.com/istoreos/istoreos/assets/96804858/f24eff3e-d4e7-4f67-b782-ebebead07d98)

### (2) 路由器型号和固件版本

A：R6s

### (3) 详细日志和/或截图

A：

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2477/1
