### ISSUE TITLE
应用商店里的应用不能更新？

### ISSUE THREAD

**Issue by hui-f** [istoreos/istoreos#1296]
![Snipaste_2024-01-23_08-48-08](https://github.com/istoreos/istoreos/assets/125562384/79da7e6f-5a53-409d-afb2-eb0d7e83f654)
![Snipaste_2024-01-23_08-48-57](https://github.com/istoreos/istoreos/assets/125562384/e7875753-0ba4-4b87-94d3-71111d338ce5)
应用商店里面的软件更新，总是更新不了

**Comment by hui-f** [comment]
处理器：n100，系统：22.03.6 2024011910

**Comment by jjm2473** [comment]
<img width="395" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/e029a5bb-7f73-4f0a-8c33-1e9d2b3ca18c">

我倒是想问问你用的什么软件源呢，`op.dllkids.xyz`既不是openwrt官方仓库，也不是国内有名的镜像地址，也不是istore提供的软件源，安装出问题关istore屁事？

**Comment by hui-f** [comment]
> <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/3896703/298823841-e029a5bb-7f73-4f0a-8c33-1e9d2b3ca18c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDAyOTcsIm5iZiI6MTcwNTk5OTk5NywicGF0aCI6Ii8zODk2NzAzLzI5ODgyMzg0MS1lMDI5YTViYi03ZjczLTRmMGEtOGMzMy0xZTlkMmIzY2ExOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDg1MzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ0MGIxYzY5MmYwNDBlNmJlYjQ0NzE2MjBkMGEzNDI0ZDdiYmM0MTUyYzAxODhmZWFiZWU1YzcxYjIwZDVjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hEmb5SblnCtWOIofpY3esAwHUp52FhgfsSdBnTddD2I">
> 我倒是想问问你用的什么软件源呢，`op.dllkids.xyz`既不是openwrt官方仓库，也不是国内有名的镜像地址，也不是istore提供的软件源，安装出问题关istore屁事？

换源了还是失败，怎么解决，重新安装吗？
![Uploading Snipaste_2024-01-23_16-52-43.jpg…]()

**Comment by hui-f** [comment]
> <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/3896703/298823841-e029a5bb-7f73-4f0a-8c33-1e9d2b3ca18c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDAyOTcsIm5iZiI6MTcwNTk5OTk5NywicGF0aCI6Ii8zODk2NzAzLzI5ODgyMzg0MS1lMDI5YTViYi03ZjczLTRmMGEtOGMzMy0xZTlkMmIzY2ExOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMDg1MzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ0MGIxYzY5MmYwNDBlNmJlYjQ0NzE2MjBkMGEzNDI0ZDdiYmM0MTUyYzAxODhmZWFiZWU1YzcxYjIwZDVjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hEmb5SblnCtWOIofpY3esAwHUp52FhgfsSdBnTddD2I">
> 我倒是想问问你用的什么软件源呢，`op.dllkids.xyz`既不是openwrt官方仓库，也不是国内有名的镜像地址，也不是istore提供的软件源，安装出问题关istore屁事？

换源了，还是不行，怎么解决，重新安装吗？
![Snipaste_2024-01-23_16-52-43](https://github.com/istoreos/istoreos/assets/125562384/65df4f78-e026-448d-8a9a-b498cca341c4)

**Comment by jjm2473** [comment]
看看能不能卸载掉之前的，如果不行，那就恢复出厂设置最简单

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2476/1
