### ISSUE TITLE
iStoreOS固件作为旁路由，现在我的Emby只能内网访问

### ISSUE THREAD

**Issue by kevinbaby1986** [istoreos/istoreos#1297]
我用过IstoreOS，作为旁路由，其他大没问题，就是我内网一台电脑做的emby服务器只能内网看了，外网访问不了，我把它直通我的爱快主路由就解决了，但是这样的话暴雪战网,易宝之类的又不能用了。用回旁路由就战网易宝正常了，但是emby又不能外网了，是不是要设置IstoreOS防火墙？我已经在爱快上把台式机端口映射到外面了，但是IstoreOS给拦下来了应该。我也尝试写规则，估计水平有限，添加的防火墙通信规则都没生效。有没有大佬可以指导指导？我的爱快局域网IP（192.168.0.28），IstoreOS IP (192.168.88.1），装emby的台式机固定IP(192.168.88.100) emby的端口8096。有大佬能提供一下解决教程吗？爱快我已经端口映射了我的192.168.88.100的8096出去了，估计就是IstoreOS给拦下来了，期待后续版本能自动放行。

**Comment by bcseputetto** [comment]
你这哪里是旁路由，你这是二级路由。还是说你的爱快是`192.168.0.0/16`，而不是`/24`
如果是二级路由，爱快的LAN是 `192.168.0.0/24` 段，那么iStoreOS的WAN是从这个段自动获取IP，你没有提及，那我假设它是`192.168.0.100/24`，接着iStoreOS的LAN是`192.168.88.0/24`段，它自己的LAN IP是 `192.168.88.1/24`
你电脑的IP是 `192.168.88.100/24`
接下来你要把电脑监听的端口转发出去，你首先需要在iStoreOS上做端口转发。
将iStoreOS局域网的IP转发到iStoreOS WAN IP上。
`192.168.88.100:8096`(电脑)→`192.168.0.100:8096`(iStoreOS WAN)
然后爱快再把它局域网的IP转发到公网上
`192.168.0.100:8096`(iStoreOS)→`爱快公网IP:8096`

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2475/1
