### ISSUE TITLE
安装配置Jellyfin一直不成功

### ISSUE THREAD

**Issue by Berg-E5** [istoreos/istoreos#1299]
用的最新固件   X86平台
安装配置Jellyfin一直不成功
![image](https://github.com/istoreos/istoreos/assets/125849101/a410d20b-f272-4fad-8026-bb8c7d044ed1)

**Comment by jjm2473** [comment]
网络问题，镜像下载不了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2473/1
