### ISSUE TITLE
wan_6 这个错误提示还是觉得应该修正下。

### ISSUE THREAD

**Issue by haobinnan** [istoreos/istoreos#1300]
别的固件点击编辑没有错误提示。
![image](https://github.com/istoreos/istoreos/assets/31329170/91b9ea71-7d30-4b43-84b4-0a6806dde346)

![image](https://github.com/istoreos/istoreos/assets/31329170/05d1f257-8d5e-4766-b22a-70084d99f60a)

设备型号
FastRhino R66s
固件版本
iStoreOS 22.03.6 2024011910

**Comment by zctmdc** [comment]
手动创建一个就好了 :)

1. 创建接口 wan_6

2. 指定协议和设备 建议选定 `pppoe-wan` 而不是 `@wan` *会导致总是获取不到地址，需要修改一下配置才行（比如 修改IPv6 分配长度）*

3. 其他按照图

<img width="1556" alt="image" src="https://github.com/istoreos/istoreos/assets/24244480/b2c8621d-a878-4d5d-bba1-5a7c8d8a0f7e">

<img width="1335" alt="image" src="https://github.com/istoreos/istoreos/assets/24244480/16ee01cd-4396-4edb-af44-467c20c7e334">

<img width="961" alt="image" src="https://github.com/istoreos/istoreos/assets/24244480/25f51000-01ca-4209-94e2-0e50b5319334">

4. 建议这里按图配置，不然上不了


<img width="625" alt="image" src="https://github.com/istoreos/istoreos/assets/24244480/45194668-8dee-456b-bd09-daca6e3471cb">


<img width="953" alt="image" src="https://github.com/istoreos/istoreos/assets/24244480/3bf77d14-8437-49d4-97a4-97ce93d7c490">

**Comment by jjm2473** [comment]
你看仔细了，wan6和wan_6不是同一个东西，wan_6是pppoe创建的虚拟接口，没得配置，相关配置都在pppoe里面

**Comment by jjm2473** [comment]
之所以其他固件没有wan_6，那只是因为其他固件的版本太老了，openwrt 21版本以上，pppoe拨号的情况下都有wan_6。当然，界面上应该要让wan_6的编辑和删除按钮变灰的，openwrt目前好像还没做。

**Comment by haobinnan** [comment]
> 之所以其他固件没有wan_6，那只是因为其他固件的版本太老了，openwrt 21版本以上，pppoe拨号的情况下都有wan_6。当然，界面上应该要让wan_6的编辑和删除按钮变灰的，openwrt目前好像还没做。

是的 我上面的截图 的确是21如果能将编辑与删除 禁用掉最好。免得发生奇异。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2472/1
