### ISSUE TITLE
建议  流量统计中的“上传“与”下载“流量显示中添加每秒”位“的统计，这样与实际运营商宣传的带宽可以吻合

### ISSUE THREAD

**Issue by haobinnan** [istoreos/istoreos#1303]
<img width="761" alt="image" src="https://github.com/istoreos/istoreos/assets/31329170/11ca0331-f200-4952-b24e-d96e3f0f0b8c">

**Comment by jjm2473** [comment]
要是有人要对比下载软件的速度呢，又对不上了。

**Comment by haobinnan** [comment]
> 要是有人要对比下载软件的速度呢，又对不上了。

可以考虑提供两种显示方式。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2469/1
