### ISSUE TITLE
请问怎样在istoreOS中使用Express VPN

### ISSUE THREAD

**Issue by JingZheX** [istoreos/istoreos#1305]
请问怎样在istoreOS中使用Express VPN

**Comment by jjm2473** [comment]
问express vpn的客服，怎么在openwrt里面使用，如果openwrt能用，那istoreos也可以

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2467/1
