### ISSUE TITLE
安装了PPTPD后菜单里没有该选项

### ISSUE THREAD

**Issue by goodlove1984** [istoreos/istoreos#1306]
### (1) 具体问题

A：在系统-软件包-搜索-PPTP，安装了pptpd、kmod-pptp、kmod-pppox、ppp-mod-pptp后。web界面没有任何显示。记得以前用OP其他版本的时候，安装了PPTP都会有一个VPN的子类目，下面有pptp的配置界面。现在装后什么都没有

### (2) 路由器型号和固件版本

X86工控主板J1900CPU，iStoreOS 22.03.6 2024011910

### (3) 详细日志和/或截图
![image](https://github.com/istoreos/istoreos/assets/96854407/d9cf4a58-9659-4c22-a288-c9f3c7c5f375)
![image](https://github.com/istoreos/istoreos/assets/96854407/7ff90ef0-0956-4331-92e9-089c122d7576)

**Comment by jjm2473** [comment]
你说的是pptp服务端还是客户端？

**Comment by jjm2473** [comment]
如果是客户端，那么在网络-接口里面添加新接口，就可以选择pptp了

**Comment by goodlove1984** [comment]
我安装的是服务端

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2466/1
