### ISSUE TITLE
esxi内安装无法显示CPU温度

### ISSUE THREAD

**Issue by leeinto** [istoreos/istoreos#1307]
esxi内安装无法显示CPU温度，还有网络唤醒是否可以自己保存呀？每次都手动输入有点麻烦。

**Comment by haobinnan** [comment]
1、为什么要在虚拟机中查看cpu温度？这个应该在宿主机中获取。
2、关于网络唤醒可以考虑写任务计划。

**Comment by jjm2473** [comment]
你说的网络唤醒是哪个界面，应该可以直接选择机器啊，不需要输入

**Comment by leeinto** [comment]
如图位置，没有我群晖的地址每次都手动输入，而且好多都没用的，也无法修改备注，希望优化下细节功能。



Lee&nbsp;into
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "istoreos/istoreos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月26日(星期五) 中午11:46
***@***.***&gt;;
抄送:&nbsp;"Lee ***@***.******@***.***&gt;;
主题:&nbsp;Re: [istoreos/istoreos] esxi内安装无法显示CPU温度 (Issue #1307)





 
你说的网络唤醒是哪个界面，应该可以直接选择机器啊，不需要输入

**Comment by leeinto** [comment]
1.我是在esxi内安装，esxi页面好像没温度显示的地方。我看istoreos内有，但不显示温度，应该是没适配esxi这种情况。
2.如图就没有群晖的地址，每次都得手动写，而且无法保存修改备注名称，希望细节能有所优化。



Lee into
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "istoreos/istoreos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月26日(星期五) 中午11:38
***@***.***&gt;;
抄送:&nbsp;"Lee ***@***.******@***.***&gt;;
主题:&nbsp;Re: [istoreos/istoreos] esxi内安装无法显示CPU温度 (Issue #1307)





 
1、为什么要在虚拟机中查看cpu温度？这个应该在宿主机中获取。
 2、关于网络唤醒可以考虑写任务计划。

**Comment by snnh** [comment]
虚拟机查看不了物理机的温度传感器，如果想看温度的话，可以试试lxc

**Comment by jjm2473** [comment]
图呢？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2465/1
