### ISSUE TITLE
没有rtl8822cs 的无线网卡驱动

### ISSUE THREAD

**Issue by zhangdachen** [istoreos/istoreos#1308]
没有rtl8822cs 的无线网卡驱动

**Comment by zhangdachen** [comment]
R2S PLUS 设备

**Comment by haobinnan** [comment]
设备是不是改了pid vid，如果改了也会造成无法识别。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2464/1
