### ISSUE TITLE
请问有无适配iqp60xx的计划

### ISSUE THREAD

**Issue by AkimioJR** [istoreos/istoreos#1312]
如题，不知道应该怎么提交希望适配的机型，手上刚好有一个兆能m2，虽然无线性能比较一般但是ipq60000的性能很强，想刷istoreOS做主路由，但好像当前源码只有ipq40xx和ipq80xx

**Comment by breeze303** [comment]
> 如题，不知道应该怎么提交希望适配的机型，手上刚好有一个兆能m2，虽然无线性能比较一般但是ipq60000的性能很强，想刷istoreOS做主路由，但好像当前源码只有ipq40xx和ipq80xx

你可以参考lede最新的commit，添加soc支持并非易事，特别是高通机型，还需要搭配nss等一系列东西

**Comment by jjm2473** [comment]
istoreos官方只适配了rk35xx，rk33xx，x86，rpi4，其他机型只是openwrt代码自带的，并没有适配（固件升级可能有问题）。

lean给部分高通的机型适配了istoreos，可以看看这里有没有你的机型 https://fw.koolcenter.com/Lean/

**Comment by AkimioJR** [comment]
> istoreos官方只适配了rk35xx，rk33xx，x86，rpi4，其他机型只是openwrt代码自带的，并没有适配（固件升级可能有问题）。
> 
> 
> 
> lean给部分高通的机型适配了istoreos，可以看看这里有没有你的机型 https://fw.koolcenter.com/Lean/

只有一个同CPU的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2461/1
