### ISSUE TITLE
磁盘阵列无法创建

### ISSUE THREAD

**Issue by webcf1983** [istoreos/istoreos#1315]
### (1) 具体问题

A：我已经挂载了2块硬盘，但创建阵列那里显示检测不到可用磁盘阵列成员

### (2) 路由器型号和固件版本

A：自组pc，iStoreOS 22.03.6 2024012613

### (3) 详细日志和/或截图

A：
![QQ截图20240128004415](https://github.com/istoreos/istoreos/assets/117358200/12d7b092-0161-4c7b-bb45-d95db621df56)
![QQ截图20240128004425](https://github.com/istoreos/istoreos/assets/117358200/f9d915f9-83f4-45f1-9215-f3b8b4a3e107)

**Comment by jjm2473** [comment]
可能是因为你的硬盘已经挂载了，在挂载点那边卸载掉以后试试，如果还不行，就用磁盘管理删掉硬盘的所有分区

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2458/1
