### ISSUE TITLE
57810s 驱动无法正常加载

### ISSUE THREAD

**Issue by coLATin** [istoreos/istoreos#1317]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
57810s 驱动无法正常加载。
### (1) 具体问题
万兆网卡，57810s，2.5g 模式，pve 直通到 istoreos 虚拟机，无法正常识别网口，没加载网口设备，说明 2 个万兆口没有正确驱动，请补充驱动
A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
bnx2x驱动是有集成的，看看内核日志有没有报错

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2457/1
