### ISSUE TITLE
在华硕ChromeBox3 CN65上无法通过ip进入luci

### ISSUE THREAD

**Issue by Gaped511** [istoreos/istoreos#1318]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：在 华硕 Chrome box 3 CN65 上安装最新版本的iStoreOS，不能通过192.168.100.1进入管理界面。接上显示器后，选择 show interface 的那个选项，在 ipv4 处没有任何显示。使用2023092815版本就可以，因为精力有限，不知道没有问题的最近版本是什么。

### (2) 路由器型号和固件版本

A：华硕 Chrome box 3 CN65 （i7-8550U/16G/傲腾m10/realtek 8什么网卡，忘了），2024012613版本出现了这个问题。

### (3) 详细日志和/或截图

A：
![微信图片_20240129220758](https://github.com/istoreos/istoreos/assets/39939598/f70ad16f-dacf-4d32-a3b6-9bfd8a8d0828)

**Comment by lizhi10** [comment]
在老版本升级至新版后，网卡正常，但是在新版本执行重置以后，又出现了此问题。老版本重置无此问题。

**Comment by Gaped511** [comment]
我知道了，新版的istoreos改了单网口设备的设置

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2456/1
