### ISSUE TITLE
nat环回不生效

### ISSUE THREAD

**Issue by 18515381698** [istoreos/istoreos#1319]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：nat环回已开启，不生效，内网通过域名无法请求内网服务器

### (2) 路由器型号和固件版本

A：[Powered by LuCI openwrt-22.03 branch (git-23.292.78392-9f66674)](https://github.com/openwrt/luci) / [ArgonTheme v2.2.10.9](https://github.com/jerrykuku/luci-theme-argon) / iStoreOS 22.03.6 2024012613

### (3) 详细日志和/或截图

A：
<img width="877" alt="image" src="https://github.com/istoreos/istoreos/assets/15626569/7484c320-668c-4f06-ac8a-131a843a500b">

**Comment by uibehw** [comment]
我也遇到这个问题了，刷的23.06-240126最新版X86_64-EFI固件，端口转发一直不成功，折腾了一晚上，搜遍了网络上的各种办法，映射端口就是打不开。

**Comment by jjm2473** [comment]
环回源IP改成外部试试？

**Comment by 18515381698** [comment]
> Contributor

试了，依旧无法内网通过域名访问

**Comment by jjm2473** [comment]
你这个内网服务器直接用ip和端口可以访问吗

**Comment by 18515381698** [comment]
> 你这个内网服务器直接用ip和端口可以访问吗

是可以的。我有一个域名abc.xxx.com。内网192.168.100.235服务端口5000，在路由（LAN:192.168.100.1，WAN:123.123.123.123）端口映射是6000。内网请求192.168.100.235:5000是正常的，外网请求abc.xxx.com:6000也是正常的。但内网请求abc.xxx.com:6000就失败。
nat环回已开启，功能似乎未生效。网上查了很多openwrt的系统的nat环回不生效的例子。有说修改/etc/sysctl.conf的，但也不生效

**Comment by 18515381698** [comment]
似乎因为我端口转发里没添加一条源区域是lan的记录？我添加上后lan通过域名访问正常了

**Comment by jjm2473** [comment]
理论上NAT环回就是用来做这件事的

**Comment by PunkFleet** [comment]
> 似乎因为我端口转发里没添加一条源区域是lan的记录？我添加上后lan通过域名访问正常了

请问是如何设置端口转发的，我这样对吗：

<img width="1266" alt="Image" src="https://github.com/user-attachments/assets/11b5f915-5a45-4fce-8e71-1d877fea5465" />

**Comment by King-hsw** [comment]
> 似乎因为我端口转发里没添加一条源区域是lan的记录？我添加上后lan通过域名访问正常了

请问可以参考一下怎么设置么？我也是这种问题但是不知道怎么配置你说的这个。不过我域名绑定的是ipv6的不知道行不行

**Comment by jjm2473** [comment]
ipv6的NAT环回暂不支持，openwrt就是如此。可以使用socat转发，这样就不需要NAT和环回了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2455/1
