### ISSUE TITLE
R6s无法安装jellyfin

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1321]
![111](https://github.com/istoreos/istoreos/assets/96804858/765c1156-be2c-4dae-9d47-f232879decb4)
![222](https://github.com/istoreos/istoreos/assets/96804858/d17a4e2e-9699-46bb-b293-e3759f3c7454)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2454/1
