### ISSUE TITLE
jellyfin 安装后无法使用

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1323]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：
![image](https://github.com/istoreos/istoreos/assets/96804858/65514c13-d4e1-4972-8665-812d0eacaa0a)
![image](https://github.com/istoreos/istoreos/assets/96804858/6c3c0842-9bba-4166-8b1d-b0b92e0bd6f1)

![image](https://github.com/istoreos/istoreos/assets/96804858/e2001054-5d51-41a4-8741-8c7147f4c5fa)
显示挂载成功，但是网页打开是空白
### (2) 路由器型号和固件版本
FriendlyElec NanoPi R6S
A：
iStoreOS 22.03.5 2023121510 / LuCI istoreos-22.03 branch git-23.342.39264-37c783a
### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
你确定30秒已经启动完了？

**Comment by pili-book** [comment]
> 你确定30秒已经启动完了？

docker run --name jellyfin \
    --privileged \
    --restart=unless-stopped -td \
    --device /dev/rga\
    --device /dev/dri\
    --device /dev/dma_heap\
    --device /dev/mpp_service\
    --dns=172.17.0.1 \
    -e TZ=Asia/Shanghai \
    --mount type=tmpfs,destination=/config/transcodes\
    -v "/mnt:/media" \
   -v /mnt:/mnt:rslave \
    jjm2473/jellyfin-mpp:latest
最后手动创建的。。。。。
但是发现个问题扫库特别慢，cpu都占不了多少，我的媒体库是挂载的nas的都是2.5g网口哦，r6s八核的cpule

**Comment by jjm2473** [comment]
我靠，你把jellyfin的配置文件夹设置成samba挂载的文件夹了？而且根据你的另一个issue，你这个文件夹可能还是只读的，能启动才怪了。

**Comment by jjm2473** [comment]
而且你自己部署的jellyfin甚至没有映射config目录，你是不打算保存jellyfin的数据是吧。

**Comment by pili-book** [comment]
> 我靠，你把jellyfin的配置文件夹设置成samba挂载的文件夹了？而且根据你的另一个issue，你这个文件夹可能还是只读的，能启动才怪了。

这个只读已经改了
https://github.com/istoreos/istoreos/issues/1325 帮忙看看这个问题
实话说，原来不知道怎么的还能用。。删了照你说的改了改不能用了 
![2E48E283](https://github.com/istoreos/istoreos/assets/96804858/0c543cd0-3ba1-4411-be95-2affcefc2f85)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2452/1
