### ISSUE TITLE
R6s Jellyfin  cpu占用疑惑，不知道是不是bug

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1328]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：昨晚安装好jellyfin以后,建立媒体库，扫描速度很快，cpu占用达到百分之30左右，今天晚上更改美体裤名字后好像得重新搜库，但是速度很慢，cpu也只占到百分之5左右，偶尔奔到百分之12也会很快下来。。。不知道这怎么理解，是固件bug还是什么设置不对了，我cpu模式设置的是性能模式频率固定最大了吧

### (2) 路由器型号和固件版本

A：FriendlyElec NanoPi R6S
iStoreOS 22.03.5 2023121510 / LuCI istoreos-22.03 branch git-23.342.39264-37c783a

### (3) 详细日志和/或截图

A：

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2447/1
