### ISSUE TITLE
关于 “系统”->“实时信息”->“连接” 的疑惑

### ISSUE THREAD

**Issue by haobinnan** [istoreos/istoreos#1329]
请教个问题，这个连接页面 用istoreos时候 这里挺准的，因为我经常长时间查看摄像头 这里就会产生一个几百兆的连接  换成其它固件后 就不准了 不知道为什么 感觉非istoreos固件某种老化时间比较短导致的，只是猜测，如果谁懂 能否指点迷津 感谢

**Comment by haobinnan** [comment]
<img width="1102" alt="image" src="https://github.com/istoreos/istoreos/assets/31329170/1d36fecc-c9c9-442c-b8cc-7a29856ca5ad">

**Comment by haobinnan** [comment]
glinet的 固件也有这个问题 还有lean的 qwt 也有这个问题 目前就是 istoreos 准。

**Comment by jjm2473** [comment]
感觉比较可能是因为有什么网络相关的加速导致的，尤其防火墙有关的加速

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2446/1
