### ISSUE TITLE
关于商店的'iStore X'皮肤的问题

### ISSUE THREAD

**Issue by rocxj** [istoreos/istoreos#1330]
主页展示应用中心模块是否可以提供展示图标大小调整，列表模式切换的选项或者可以提供个性化配置的选项，安装应用多了，图标会挤在一起，操作很不方便，也非常不好看。
![image](https://github.com/istoreos/istoreos/assets/8263442/73944500-be21-4184-a039-6de124dde638)

**Comment by jjm2473** [comment]
修复了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2445/1
