### ISSUE TITLE
docker重启后ip变化了

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1332]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：重启后发现几个docker容器的地址变化了。。。。没有隐射路由端口，不知道这个docker自己的ip能固定吗，我是直接界面生成的没有用命令

### (2) 路由器型号和固件版本

A：R6s

### (3) 详细日志和/或截图

A：

**Comment by byteinfo** [comment]
把容器的网络换成 主机模式 (Host)，不需要再做端口映射

**Comment by pili-book** [comment]
主机模式界面上生成的时候好像没看到哪里选吗？必须用代码吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月7日(周三) 上午10:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] docker重启后ip变化了 (Issue #1332)




 
把容器的网络换成 主机模式 (Host)，不需要再做端口映射

**Comment by jjm2473** [comment]
使用端口转发啊，`-p`参数你以为干嘛的？

如果你要固定ip，那么需要创建一个网络，不能使用默认的bridge网络。详情看docker官方文档

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2443/1
