### ISSUE TITLE
挂载 CIFS/SMB  重启后就消失一个bug

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1333]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：挂载 CIFS/SMB 
![image](https://github.com/istoreos/istoreos/assets/96804858/2286dfd1-6ec2-4a58-bafe-997ebc95f306)
![image](https://github.com/istoreos/istoreos/assets/96804858/df017be2-21f2-485c-8443-fc09038ba0ba)
发现个问题，重启后本来挂载的两个只剩下了一个自动挂载上了。。。。我觉得绝对算bug
重启两次都是这样子。。。。手动再确认下就挂上了
后来经过多次重启实验，我加上第三个挂载项。。。。后两个能挂上估计第一个不能自动挂载上。。。。。啥情况哦

### (2) 路由器型号和固件版本

A：FriendlyElec NanoPi R6S
iStoreOS 22.03.6 2024012613 / LuCI istoreos-22.03 branch git-24.016.46072-3e9fab7

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
可能是因为启动过程中网络还没连接好就执行到挂载了

**Comment by pili-book** [comment]
那这。。。。。怎解决，固件本身这样子应该是还是bug吧，我自己解决的话应该去哪改改东西



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年2月9日(周五) 中午12:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 挂载 CIFS/SMB  重启后就消失一个bug (Issue #1333)




 
可能是因为启动过程中网络还没连接好就执行到挂载了

**Comment by pili-book** [comment]
这个怎么能调节一下，延迟一下了



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年2月9日(周五) 中午12:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 挂载 CIFS/SMB  重启后就消失一个bug (Issue #1333)




 
可能是因为启动过程中网络还没连接好就执行到挂载了

**Comment by pili-book** [comment]
那我想把他延时一下得去哪改东西了



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年2月9日(周五) 中午12:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 挂载 CIFS/SMB  重启后就消失一个bug (Issue #1333)




 
可能是因为启动过程中网络还没连接好就执行到挂载了

**Comment by jjm2473** [comment]
之后会增加一个延迟的参数配置

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2442/1
