### ISSUE TITLE
动态DDNS  cloudflare.com-v4   dnsexit都解析不了

### ISSUE THREAD

**Issue by zhb7670** [istoreos/istoreos#1336]
### (1) 具体问题

动态DDNS  cloudflare.com-v4   dnsexit. 都解析不了

### (2) 路由器型号和固件版本

 ESXI N5105

### (3) 详细日志和/或截图

cloudflare.com-v4报错：
 020652  WARN : NO valid IP found
 020652  WARN : Error in 'expand_ipv6()' - invalid IPv6 found: '' expanded: ''
 020652  info : Starting main loop at 2024-02-12 02:06
 020652       : Detect local IP on 'web'
 020652       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/hongbo.dat -o /var/run/ddns/hongbo.err --no-proxy 'http://checkipv6.dyndns.com'
 020652 ERROR : GNU Wget Error: '4'
 020652       : wget: unable to resolve host address 'checkipv6.dyndns.com'
 020652  WARN : Transfer failed - retry 1/0 in 60 seconds
 020752       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/hongbo.dat -o /var/run/ddns/hongbo.err --no-proxy 'http://checkipv6.dyndns.com'
 020752 ERROR : GNU Wget Error: '4'
 020752       : wget: unable to resolve host address 'checkipv6.dyndns.com'
 020752  WARN : Transfer failed - retry 2/0 in 60 seconds

dnsexit报错：
020652  WARN : NO valid IP found
 020652  WARN : Error in 'expand_ipv6()' - invalid IPv6 found: '' expanded: ''
 020652  info : Starting main loop at 2024-02-12 02:06
 020652       : Detect local IP on 'web'
 020652       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/hongbo.dat -o /var/run/ddns/hongbo.err --no-proxy 'http://checkipv6.dyndns.com'
 020652 ERROR : GNU Wget Error: '4'
 020652       : wget: unable to resolve host address 'checkipv6.dyndns.com'
 020652  WARN : Transfer failed - retry 1/0 in 60 seconds

**Comment by jjm2473** [comment]
你确定用这个 `http://checkipv6.dyndns.com/` 能获取到公网地址？

**Comment by zhb7670** [comment]
> 你确定用这个 `http://checkipv6.dyndns.com/` 能获取到公网地址？

确定

**Comment by zhb7670** [comment]
![image](https://github.com/istoreos/istoreos/assets/52443818/584d887a-aa3e-45d0-80ec-f3215057e72b)

**Comment by jjm2473** [comment]
那你在软路由上执行`curl http://checkipv6.dyndns.com/`以及`wget -O- http://checkipv6.dyndns.com/`看看

**Comment by jjm2473** [comment]
> `wget: unable to resolve host address 'checkipv6.dyndns.com'`

看你的日志中有这个，你确定软路由的DNS正常且有ipv6吗？执行 `nslookup checkipv6.dyndns.com` 看看

**Comment by zhb7670** [comment]
> curl http://checkipv6.dyndns.com/

![image](https://github.com/istoreos/istoreos/assets/52443818/9b3a724e-7152-42ee-84d5-ee01ba086168)

**Comment by zhb7670** [comment]
> > `wget: unable to resolve host address 'checkipv6.dyndns.com'`
> 
> 看你的日志中有这个，你确定软路由的DNS正常且有ipv6吗？执行 `nslookup checkipv6.dyndns.com` 看看

![image](https://github.com/istoreos/istoreos/assets/52443818/e3851329-7528-4698-adb9-edb3078f5c0e)

**Comment by zhb7670** [comment]
我装了好多op系统，用DDNS都没有问题，只有iStoreOS的DDNS，解析不了

**Comment by zhb7670** [comment]
ipv4  ipv6都不能解析出来

**Comment by zhb7670** [comment]
root@iStoreOS:~# curl http://checkipv6.dyndns.com/
curl: (6) Could not resolve host: checkipv6.dyndns.com
上面的是正常的，错了，iStoreOS并不能获取

**Comment by zhb7670** [comment]
![image](https://github.com/istoreos/istoreos/assets/52443818/413def91-8194-4a98-8e02-9cff2ce5bb52)

**Comment by zhb7670** [comment]
![image](https://github.com/istoreos/istoreos/assets/52443818/9f895627-342b-45f1-be53-ae30b7059afe)

**Comment by zhb7670** [comment]
![image](https://github.com/istoreos/istoreos/assets/52443818/49167bac-45d0-42b8-a675-51a5c357e10e)

**Comment by zhb7670** [comment]
![image](https://github.com/istoreos/istoreos/assets/52443818/f3d19093-9639-4157-a14e-d5340dfb397f)
把这个钩去掉就好了，默认是钩选的

**Comment by jjm2473** [comment]
确实，默认禁止ipv6解析，因为可能影响翻墙插件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2440/1
