### ISSUE TITLE
请问可以集体更新一下商店和系统的插件吗

### ISSUE THREAD

**Issue by daoyelihuowang** [istoreos/istoreos#1337]
如标题，好多插件都是老版本，希望可以集体更新一波

**Comment by jjm2473** [comment]
有些插件是从openwrt仓库安装的，卸载重装就能更新了。istore托管的只有这些 https://github.com/linkease/istore-repo/tree/main/bin/packages

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2439/1
