### ISSUE TITLE
istoreos x86_64 直通pci

### ISSUE THREAD

**Issue by zhuozi1212** [istoreos/istoreos#1338]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：查询一下是否能开启iommu通过vfio达到pci直通设备
主板是w680+12500，支持并开启iommu，sr-iov，vt-d，vt-x
图内的通过修改grub的方式开始是不是为方式不对，或者有其他办法也能pci直通到webvirtcloud

### (2) 路由器型号和固件版本

A：istoreos x86_64_efi

### (3) 详细日志和/或截图

A：
![YNSFHF)ZO3$(5 P92P0I2X](https://github.com/istoreos/istoreos/assets/47881667/44405be6-16a6-416d-ac61-f57092585fc4)

**Comment by jjm2473** [comment]
可以修改/boot/grub里面的配置文件，但是这个文件每次升级固件都会被重置。

**Comment by jjm2473** [comment]
看你的cmdline不是已经生效了吗

**Comment by zhuozi1212** [comment]
> 看你的cmdline不是已经生效了吗

libvirt 错误- unsupported configuration: host doesn't support VFIO PCI passthrough
![image](https://github.com/istoreos/istoreos/assets/47881667/b4f7dc51-d003-4809-aa73-b8b775247dbe)

**Comment by jjm2473** [comment]
那你就按其他教程，修改/boot/grub

**Comment by zhuozi1212** [comment]
> 那你就按其他教程，修改/boot/grub

因为没有关于openwrt的方法，因此我只是参考centos的贴文

**Comment by ks-bao** [comment]
因为时间不够，所以我没空把显卡直通开发完成。你有兴趣，我提供大概的思路：

### 一、grub 要修改，比如

INTEL 后面要添加：intel_iommu=on iommu=pt video=efifb:off,vesafb:off

或者 AMD后面要添加：amd_iommu=on iommu=pt video=vesafb:off,efifb:off,simplefb:off

### 二、删除原本的显卡驱动，比如

rm /lib/modules/5.10.176/i915.ko

要恢复也简单，从 /rom/lib/modules 文件夹恢复。

### 三、vfio-pci 要改成一下内容

```
cat /etc/modules.d/vfio-pci 
vfio-pci ids=8086:4e61 disable_vga=1
```

对了，ids=8086:4e61 应该要自己搜索看看，自己的显卡 ID 是啥~

并给与权限：
```
chmod 666 /dev/vfio/vfio
```

### 四、修改虚拟机 libvirt xml 文件，如下

```
<domain type='kvm' id='18' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>

( 注意开头跟结尾，中间内容省略...)

  <qemu:commandline>
    <qemu:arg value="-set"/>
    <qemu:arg value="device.hostdev0.romfile=/usr/share/OVMF/vbios_gvt_uefi.rom"/>
    <qemu:arg value="-set"/>
    <qemu:arg value="device.hostdev0.driver=vfio-pci-nohotplug"/>
    <qemu:arg value="-set"/>
    <qemu:arg value="device.hostdev0.x-igd-opregion=on"/>
  </qemu:commandline>
```

vbios_gvt_uefi.rom 要从这个参考文章下载：

[参考文章](https://wiki.archlinux.org/title/Intel_GVT-g#Using_DMA-BUF_with_UEFI/OVMF)

后记：貌似 vbios_gvt_uefi.rom 我放倒了 docker 的 /etc/libvirt 文件夹下面了。

### 五、打好 windows 驱动之后，还需要把物理驱动加到  XML 里面

写完检测发现遗漏了步骤五：（可以参考 PVE，大体流量是一模一样的，只是 vfio 以及 xml 修复方式有点不一样）

```
<hostdev mode="subsystem" type="pci" managed="yes">
  <source>
    <address domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
  </source>
  <address type="pci" domain="0x0000" bus="0x06" slot="0x00" function="0x0"/>
</hostdev>

<hostdev mode="subsystem" type="pci" managed="yes">
  <source>
    <address domain="0x0000" bus="0x01" slot="0x00" function="0x1"/>
  </source>
  <address type="pci" domain="0x0000" bus="0x07" slot="0x00" function="0x0"/>
</hostdev>

<video>
  <model type="none"/>
</video>

```

上面的内容本人亲自用 N5105 验证成功了哈。但是精力有限，没空从头到尾分享出来。

**Comment by jjm2473** [comment]
我看了下，目前22.03固件的内核没开启iommu的支持，好像只有测试固件才开了

**Comment by jjm2473** [comment]
下载这里的23.05测试固件，grub一样修改，应该就行了 https://fw.koolcenter.com/iStoreOS/alpha/x86_64_efi/

**Comment by zhuozi1212** [comment]
> 我看了下，目前22.03固件的内核没开启iommu的支持，好像只有测试固件才开了

之后的正式版会留一个在杂项设置里面开启的选项吗？

**Comment by jjm2473** [comment]
我看看22.03打开iommu以后兼容性怎么样

**Comment by jjm2473** [comment]
@zhuozi1212 试试这个固件，开启了iommu，注意还是要手动修改grub配置文件 https://we.tl/t-WZr9OpXPbi

**Comment by jjm2473** [comment]
显卡驱动应该可以不删除的，unbind就行了。 https://www.ibm.com/docs/en/linux-on-z?topic=hs-pci

对于intel，差不多是：
```bash
lspci -n | grep 00:02.0
echo 0000:00:02.0 > /sys/bus/pci/drivers/i915/unbind
echo 8086 4e55 > /sys/bus/pci/drivers/vfio-pci/new_id
```
注意最后一个id需要改成第一条命令里面显示的

**Comment by jjm2473** [comment]
最新固件已经支持图形界面配置iommu开关了

**Comment by journeyaway** [comment]
想在istoreos里装的homeassistant直通usb用zigbee网关，怎么都能不成功，lsusb后得到
root@iStoreOS:~# lsusb
Bus 003 Device 003: ID 1a86:7523  USB Serial
然后虚拟机的xml增加并删除前面冲突的bus和port
###
      <source>
        <vendor id='0x1a86'/>
        <product id='0x7523'/>
        <address bus='3' device='3'/>
      </source>
      <address type='usb' bus='0' port='1'/>
    </hostdev>
启动后提示找不到
Unable to stat /dev/bus/usb/003/003: No such file or directory

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2438/1
