### ISSUE TITLE
能否在istoreOS首页显示所有网口的状态呢？

### ISSUE THREAD

**Issue by king1393** [istoreos/istoreos#1339]
目前首页好像只能显示eth0，eth1两个网口的状态，能否改变一下UI布局显示所有网口的状态呢？
![屏幕截图 2024-02-13 203201](https://github.com/istoreos/istoreos/assets/32534889/28689824-01e2-465e-a9ec-dee78eec0b1f)

**Comment by LemonPAKA** [comment]
![image](https://github.com/istoreos/istoreos/assets/17202894/2e2e84af-1545-4fa5-a83c-3f5cf8b0f73e)
wo'j我觉得并不是界面的问题

**Comment by jjm2473** [comment]
鼠标移到两侧有滚动按钮

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2437/1
