### ISSUE TITLE
aria2 绝对路径错误

### ISSUE THREAD

**Issue by fengjiuge1** [istoreos/istoreos#1340]
![QQ截图20240213222309](https://github.com/istoreos/istoreos/assets/71777013/17ada5d8-e983-4d6a-b4fa-ad9cc260d676)
![QQ截图20240213222421](https://github.com/istoreos/istoreos/assets/71777013/bb3b6462-91e7-41ed-9bf6-7eef041947e4)
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：
![QQ截图20240213222432](https://github.com/istoreos/istoreos/assets/71777013/d5ee6ce0-2716-4e58-8eae-4a87239327a5)

**Comment by jjm2473** [comment]
没复现，你还是看看自己填的路径是不是有不可见字符，或者使用了全角符号。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2436/1
