### ISSUE TITLE
迅游加速器无法启动

### ISSUE THREAD

**Issue by LionYu66** [istoreos/istoreos#1341]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
迅游加速器下载后点选启用无法启动

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：迅游加速器下载后点选启用无法启动

### (2) 路由器型号和固件版本

A：
x86 Generic
iStoreOS 22.03.6 2024012613

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/51237029/a4dc512a-13dc-43fd-b813-8c51f6eeff03)

**Comment by jjm2473** [comment]
没复现，卸载重装试试。

**Comment by jjm2473** [comment]
你点了“保存应用”了吗

**Comment by LionYu66** [comment]
都试了，最后系统重置出厂设置好了，可能更新系统的时候系统部件出问题了吧

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2435/1
