### ISSUE TITLE
有支持光影猫的固件吗？

### ISSUE THREAD

**Issue by syjjx** [istoreos/istoreos#1344]
Photonicat光影猫 配置
瑞芯微 RK3568（4核 Cortex®-A55 @ 2.0GHz), ARM Mali-G52, NPU 0.8Tops
高通QCA1023 B/G/N/AC (2.4G/5G)

希望可以驱动VPU，实现硬解码

**Comment by jjm2473** [comment]
没有测试机

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2432/1
