### ISSUE TITLE
管理界面的远程端口哪里能设置吗？

### ISSUE THREAD

**Issue by wjcghdzh** [istoreos/istoreos#1345]
作为旁路由使用，但是有在外远程进管理界面的需求，默认的端口是什么？
主路由有公网ip和ddns，我只需要端口转发下，不想用其他的内网穿透插件。

**Comment by jjm2473** [comment]
那不就是端口转发的那个端口吗？？问的什么问题。
你是不知道哪里设置端口转发吗？在网络-防火墙里面

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2431/1
