### ISSUE TITLE
图标文字显示不全

### ISSUE THREAD

**Issue by master-yun-yun** [istoreos/istoreos#1346]
更新了路由狗
图标文字显示不全了
![路由狗](https://github.com/istoreos/istoreos/assets/79097488/279c8967-0b92-4340-b7ee-11f040280c4d)

**Comment by Carseason** [comment]
下个版本会弄好

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2430/1
