### ISSUE TITLE
R5S LTS只能识别两个接口

### ISSUE THREAD

**Issue by lxdai7610** [istoreos/istoreos#1351]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? 
 没有类似的issue

2. 详细叙述

(1) 具体问题

R5S从r5s-20231231-openwrt-rockchip-armv8-friendlyarm刷到 iStoreOS 22.03.6 系统识别城R5C 而且只识别到两个接口，换了好几个版本都是这样

 (2) 路由器型号和固件版本

机器型号：R5S 4G版
固件版本：iStoreOS 22.03.6 2024011910

 (3) 详细日志和/或截图

A：
型号识别错误，应该是R5S
![image](https://github.com/istoreos/istoreos/assets/59252682/10cde855-ac83-482b-82c6-da0808101802)

网口只识别到两个
![image](https://github.com/istoreos/istoreos/assets/59252682/497ef899-6c5c-4d1f-95bc-9dbddbad35c9)

**Comment by lxdai7610** [comment]
update：
使用 2023052616之前的版本，比如2023052311就会识别正确，网口也可以全部识别
![image](https://github.com/istoreos/istoreos/assets/59252682/b87cd851-c8df-4957-a1cc-dfbb3d9016e5)
![image](https://github.com/istoreos/istoreos/assets/59252682/f4832e41-1266-403d-a982-7ada13b341e5)

**Comment by jjm2473** [comment]
直接刷最新固件，不要从老版本升级

**Comment by lxdai7610** [comment]
试过了，直接线刷高版本还是一样，反应到设备厂商那，说说春节后的R5S升级了一下，多了一个红外接收器，不知道是否是这个原因导致

**Comment by jjm2473** [comment]
你的R5S是新买的？

**Comment by jjm2473** [comment]
你能拍个R5S的正面照吗，看看是不是 [R5S-LTS](https://www.friendlyelec.com/index.php?route=product/product&product_id=287) 。

**Comment by jjm2473** [comment]
试试这个固件，加上了 R5S LTS 和 R5S C1 的支持 https://we.tl/t-OZpxEc8gZC

**Comment by lxdai7610** [comment]
> 尝试一下这个固件，加上 R5S LTS 和 R5S C1 的支持https://we.tl/t-OZpxEc8gZC

这个固件没问题，刷上后识别型号为：R5S LTS，网口也可以识别三个
![image](https://github.com/istoreos/istoreos/assets/59252682/f2f52349-6101-4aec-9eec-c35d54a33b7d)
![image](https://github.com/istoreos/istoreos/assets/59252682/a7d66172-3bad-4e89-a909-2b17d53854c0)

**Comment by jjm2473** [comment]
OK，那之后的固件都会支持

**Comment by lxdai7610** [comment]
厂商反馈：春节后的R5S 升级了红外接收接口，LTS 就是加了红外的，所以加了新的型号实际就是R5S LTS，感谢大佬@jjm2473，等待官方更新了...

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2426/1
