### ISSUE TITLE
Safari浏览器访问iStoreOS网页部分内容不显示

### ISSUE THREAD

**Issue by will-huang9531** [istoreos/istoreos#1352]
(1) 具体问题

使用macOS14的Safari浏览器访问iStoreOS-22.03端网页，其中部分插件如：实时流量（v1.0.3）、主机流量统计（v1.0.0）不显示任何内容，换用Chrome能够正常显示，请尝试修复这个问题。

(2) 路由器型号和固件版本
路由器型号：X86平台
固件版本：iStoreOS-22.03

 (3) 详细日志和/或截图
<img width="1856" alt="iShot_2024-02-20_16 45 26" src="https://github.com/istoreos/istoreos/assets/103096674/ef27c734-8689-445e-bd88-ad3ce6093139">
<img width="1848" alt="iShot_2024-02-20_16 45 39" src="https://github.com/istoreos/istoreos/assets/103096674/f3d0a6f1-190d-4327-a7d0-f17e2e40f737">

**Comment by jjm2473** [comment]
应该是Safari浏览器的bug，动态修改table内容都会出现table只显示一行的问题

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2425/1
