### ISSUE TITLE
iStoreOS 静态地址分配 中文名

### ISSUE THREAD

**Issue by luz83o** [istoreos/istoreos#1354]
请大佬麻烦支持 [静态地址分配]或者[主机名映射] 可以修改中文名。或者有类似的插件推荐也可以。十分感谢。

**Comment by jjm2473** [comment]
我测试了下，强行使用中文的话，dnsmasq虽然能跑起来，但是nslookup之类的都没法解析中文

**Comment by jjm2473** [comment]
如果你还想让系统支持中文主机名，那就反馈给openwrt吧，看看他们能不能支持。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2423/1
