### ISSUE TITLE
路由器后台主页显示网络未连接，电脑却有网。

### ISSUE THREAD

**Issue by a751309788** [istoreos/istoreos#1355]
![屏幕截图 2024-02-22 141056](https://github.com/istoreos/istoreos/assets/64885891/e3e32ce5-d54d-451b-a17d-6b46450e7aac)

路由器显示网络未连接，无法下载插件。但是底下的每个设备都有网

**Comment by jjm2473** [comment]
什么路由器，固件版本是什么？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2422/1
