### ISSUE TITLE
ax9000没有docker

### ISSUE THREAD

**Issue by curui** [istoreos/istoreos#1356]
ax9000没有docker
![ddd1](https://github.com/istoreos/istoreos/assets/83493228/a1fb5c2e-3384-4c31-aba2-ce4a87422854)

**Comment by jjm2473** [comment]
ax9000不是istoreos官方维护的，反馈给作者

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2421/1
