### ISSUE TITLE
突然发现不能更新软件了！

### ISSUE THREAD

**Issue by illusionist1127** [istoreos/istoreos#1357]
原有开始更新Unifi固件，发现无法更新，期初以为是墙的问题，最后发现所有软件都无法更新。
![iShot_2024-02-23_01 26 48](https://github.com/istoreos/istoreos/assets/123858298/a27eaebb-2304-4b97-b980-f1767f9af568)

**Comment by jjm2473** [comment]
删掉国内的docker镜像仓库，使用官方仓库

**Comment by illusionist1127** [comment]
新人小白，具体咋操作呀，劳烦了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2420/1
