### ISSUE TITLE
提交一个bug（可能是）。多网口的机器，安装后启动，无法通过主路由网段访问管理网页。

### ISSUE THREAD

**Issue by happymy** [istoreos/istoreos#1358]
提交一个bug（可能是）。多网口的机器，安装后启动，无法通过主路由网段访问管理网页。SSH可连接、可ping通baidu，只能通过子网访问管理页面，用子网段访问管理页面继续配置后可解决。或安装前bios禁用其他网口。建议：quickstart命令增加一个配置选项，让主路由网段可访问管理网页。

**Comment by jjm2473** [comment]
防火墙默认禁止wan口入站，你在lan口进后台把防火墙的wan区域设置为允许入站就行了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2419/1
