### ISSUE TITLE
docker 打开防火墙

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1361]
1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时包括已关闭的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)

 没有类似的issue
2. 详细叙述
(1) 具体问题
我发现主路由docker建立容器后会自动打开防火墙，这样我用lucky大吉或者scoat想要端口转发的时候，这个端口就会被占用无法打开，还需要额外打开另外的端口，这样会不会增加外网端口暴露的风险呢,如果我不想在docker容器映射的同时打开这个端口的防火墙，应该如何设置了，或者能否在docker的配置上添加相关的选项呢
![image](https://github.com/istoreos/istoreos/assets/96804858/95a402c5-d010-4669-831b-255ef4087240)
zhetya这样能解决吗
(2) 路由器型号和固件版本
A：FriendlyElec NanoPi R6S
iStoreOS 22.03.5 2023121510 / LuCI istoreos-22.03 branch git-23.342.39264-37c783a

**Comment by jjm2473** [comment]
docker的防火墙已经禁用，不会自动开放，你要开放的话，用系统防火墙配置就行了。

**Comment by pili-book** [comment]
但是我某个容器映射了端口5700，使用lucky大吉反向代理，那个端口就已经占用了。。。。。



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年2月25日(周日) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] docker 打开防火墙 (Issue #1361)




 
docker的防火墙已经禁用，不会自动开放，你要开放的话，用系统防火墙配置就行了。

**Comment by pili-book** [comment]
> docker的防火墙已经禁用，不会自动开放，你要开放的话，用系统防火墙配置就行了。

![image](https://github.com/istoreos/istoreos/assets/96804858/abcd348d-c1f3-4f5b-9fe7-bf988b789878)

**Comment by jjm2473** [comment]
那不是废话吗，端口映射不就已经占用掉端口了吗？你是不是不了解端口的概念啊

**Comment by jjm2473** [comment]
端口已经被docker自动映射了，也就是已经有端口转发，你要外网访问就在防火墙允许这个端口输入就行了，不需要再配置端口转发。这种问题不要再来istoreos反馈，这是普通的网络知识，跟固件没任何关系。

**Comment by pili-book** [comment]
那这种情况luck大吉的反向代理就只能是映射别的端口吗？各种尝试好像没办法，都是显示端口占用了



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年2月25日(周日) 晚上7:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] docker 打开防火墙 (Issue #1361)




 
端口已经被docker自动映射了，也就是已经有端口转发，你要外网访问就在防火墙允许这个端口输入就行了，不需要再配置端口转发。这种问题不要再来istoreos反馈，这是普通的网络知识，跟固件没任何关系。
