### ISSUE TITLE
初始化安装istoreos，希望通过wan口也能设置

### ISSUE THREAD

**Issue by 858622025** [istoreos/istoreos#1364]
我经常远程在外，设备出现问题后，远程还原设备后，默认连接wan口，无法远程初始化设置。能否让多网口的设备，既能lan口指定默认ip连接设备，也可以wan口动态ip设置

**Comment by jjm2473** [comment]
不行，有安全风险。

**Comment by 858622025** [comment]
不懂风险在哪里？初始化设置后，可以关闭，而且本身对于单网口设备来说，没有区别啊



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年2月25日(周日) 下午5:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 初始化安装istoreos，希望通过wan口也能设置 (Issue #1364)




 
不行，有安全风险。

**Comment by jjm2473** [comment]
单网口可以访问啊，单网口的话，默认就是lan口，只是默认dhcp客户端而已

**Comment by jjm2473** [comment]
我说的是wan口默认不能访问后台，因为有些人的wan口是dhcp能获取到公网ip的，详情看这个issue  https://github.com/istoreos/istoreos/issues/1132

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2416/1
