### ISSUE TITLE
R4S使用RTL8156B的2.5G usb 网卡断流

### ISSUE THREAD

**Issue by zjqwhy** [istoreos/istoreos#1366]
希望能添加最新的kmod-usb-net-rtl8152-vendor。

**Comment by jjm2473** [comment]
现在就是这个驱动，早就不用内核自带的r8152了，只是因为替换了内核驱动，所以驱动名称是r8152

**Comment by zjqwhy** [comment]
> 现在就是这个驱动，早就不用内核自带的r8152了，只是因为替换了内核驱动，所以驱动名称是r8152

谢谢，如果不是驱动的问题的话，能帮我看这个到底是什么造成的,跑下测试马上就这样。
iStoreOS 22.03.6 2024022310 / LuCI istoreos-22.03 branch git-24.016.46072-3e9fab7
<img width="624" alt="SCR-20240226-qsxb" src="https://github.com/istoreos/istoreos/assets/105403482/955c9857-50d8-409b-bc97-6b04517d48ee">
<img width="668" alt="捕获" src="https://github.com/istoreos/istoreos/assets/105403482/7e07b6e4-c815-4951-95fa-e61957358460">

**Comment by zjqwhy** [comment]
> 现在就是这个驱动，早就不用内核自带的r8152了，只是因为替换了内核驱动，所以驱动名称是r8152

使用 ethtool -K eth2 tx off rx off后有所改善，但是下载文件时间一长就卡死了。
<img width="334" alt="捕获" src="https://github.com/istoreos/istoreos/assets/105403482/27812313-e598-4e9f-9047-efeb6bd6cdd1">
<img width="716" alt="SCR-20240226-rjnd" src="https://github.com/istoreos/istoreos/assets/105403482/95c33975-9e36-420d-9f2d-0415c12d2e02">

**Comment by jjm2473** [comment]
可能是usb有问题，反正rk的usb有问题也不奇怪，之前r2s的usb网卡甚至都没法识别，打了rk的补丁才稳定。

**Comment by jjm2473** [comment]
你测试下openwrt 22.03.6有没有这个问题，如果有，就反馈给openwrt，r4s是openwrt官方维护的机型

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2414/1
