### ISSUE TITLE
R4SE是否可以增加VPU的驱动

### ISSUE THREAD

**Issue by snowinner** [istoreos/istoreos#1368]
如题，在R4se上使用Jellyfin没有硬件加速，希望官方可以加入VPU支持

**Comment by jjm2473** [comment]
r4s是openwrt官方维护的机型，istoreos不会做太多修改，有建议可以反馈给openwrt

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2412/1
