### ISSUE TITLE
系统自带DHCP服务无法按照顺序分配lan口设备IP地址

### ISSUE THREAD

**Issue by yakult-xia** [istoreos/istoreos#1377]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：系统自带DHCP服务无法按照顺序分配lan口设备IP地址，已在DHCP 服务—高级设置里面开启顺序分配 IP。但仍然没有分配效果。具体截图情况见详细日志/截图部分

### (2) 路由器型号和固件版本

A：EQ12 ，固件版本istoreos-22.03.6-2024030112-x86-64-squashfs-combined-efi.img.gz

### (3) 详细日志和/或截图

A：1.已在luci界面中DHCP 高级设置中开启按顺序分配
![1](https://github.com/istoreos/istoreos/assets/73748728/a104a907-c3cd-4275-a161-b857d0611f44)
2.LAN口ip设置及地址池设置情况
![2](https://github.com/istoreos/istoreos/assets/73748728/1d8fc627-5d96-4269-8917-d41634af9bab)
![3](https://github.com/istoreos/istoreos/assets/73748728/681f2e03-6823-49e9-bd95-5784d3b84f49)
3.DHCP config 文件情况
{config dnsmasq
        option domainneeded '1'
        option localise_queries '1'
        option rebind_protection '1'
        option rebind_localhost '1'
        option local '/lan/'
        option domain 'lan'
        option expandhosts '1'
        option authoritative '1'
        option readethers '1'
        option leasefile '/tmp/dhcp.leases'
        option localservice '1'
        option ednspacket_max '1232'
        option port '53'
        option sequential_ip '1'
        option localuse '1'
        option noresolv '0'
        option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
        option cachesize '1000'

config dhcp 'lan'
        option interface 'lan'
        option start '100'
        option leasetime '12h'
        option dhcpv4 'server'
        option ra 'server'
        option dhcpv6 'server'
        option limit '100'

config dhcp 'wan'
        option interface 'wan'
        option ignore '1'

config odhcpd 'odhcpd'
        option maindhcp '0'
        option leasefile '/tmp/hosts/odhcpd'
        option leasetrigger '/usr/sbin/odhcpd-update'
        option loglevel '4'
}
4.未能按顺序分配情况截图
![4](https://github.com/istoreos/istoreos/assets/73748728/d9f6256e-4eb8-4df9-908e-477c73aa487c)

**Comment by jjm2473** [comment]
大部分设备都会先申请之前用过的ip，如果没冲突就会使用，跟dhcp服务配置无关。只有新设备才有可能按顺序。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2406/1
