### ISSUE TITLE
安装失败：

### ISSUE THREAD

**Issue by woaijorden** [istoreos/istoreos#1380]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：安装失败，一直卡在  eth0：Nonative access to PCI extendedconfig space,falling back to CSI

### (2) 路由器型号和固件版本

A：AMD 3550H迷你小主机，
固件版本：istoreos-22.03.6-2024022310-x86-64-squashfs-combined-efi.img

### (3) 详细日志和/或截图

A：
![photo_2024-03-02_16-48-25](https://github.com/istoreos/istoreos/assets/14155266/4f4a4895-0bd7-494f-9d55-c128e2e31e80)

**Comment by jjm2473** [comment]
参考这个 https://github.com/istoreos/istoreos/issues/1289
