### ISSUE TITLE
R4S启动不了

### ISSUE THREAD

**Issue by wolvth** [istoreos/istoreos#1383]
因为之前是一直从低版本升级过来的，没有发现这问题。
最近全新刷了一次固件，发现无法启动。
只亮一个红灯。发现有其他人有同样的问题
#1210 
我的R4S是1G内存版本，无内置存储空间。TF卡启动。

**Comment by jjm2473** [comment]
既然知道有issue，还再发一遍干嘛，都说了是openwrt原版就有的bug，而且也提供了解决方案。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2402/1
