### ISSUE TITLE
升级了最新版后网络连接一直是检测中，固件更新那里一直转圈

### ISSUE THREAD

**Issue by zypj1123** [istoreos/istoreos#1385]
网络连接一直是检测中，固件更新那里一直转圈貌似还是在检测，cpu和内存占用好像也变大了。
![1](https://github.com/istoreos/istoreos/assets/122420980/a3767b9a-3caa-4452-b458-c4ad809f5d27)
![2](https://github.com/istoreos/istoreos/assets/122420980/6313c595-a020-4a81-b6ae-706bcddba5fc)
![3](https://github.com/istoreos/istoreos/assets/122420980/f117ca44-1a58-4318-a769-a30ac413c654)

**Comment by jjm2473** [comment]
估计是dns错误

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2400/1
