### ISSUE TITLE
有更新到最新内核的计划吗

### ISSUE THREAD

**Issue by oienwav** [istoreos/istoreos#1386]
x86 大小核出了几代了，期待支持

**Comment by bcseputetto** [comment]
大概没有，因为需要通过与OpenWrt内核版本一致来兼容OpenWrt官方opkg软件源，不存在随便升级最新内核
OpenWrt官方的22.03.6是 [5.10.201-1-7865481e154fa056bd3b6ca1ae9b5f74](http://downloads.openwrt.org/releases/22.03.6/targets/x86/64/kmods/5.10.201-1-7865481e154fa056bd3b6ca1ae9b5f74/) iStoreOS 22.03.6也是这个内核版本
就算升级到最新稳定版23.05.2，内核也是 [5.15.137-1-47964456485559d992fe6f536131fc64](http://downloads.openwrt.org/releases/23.05.2/targets/x86/64/kmods/5.15.137-1-47964456485559d992fe6f536131fc64/)

**Comment by jjm2473** [comment]
对，istoreos的内核是跟随openwrt的，这样才能使用openwrt的完整软件仓库

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2399/1
