### ISSUE TITLE
希望iStore OS增加可以通过iSCSI或者SMB或者NFS外挂第三方存储的方式

### ISSUE THREAD

**Issue by newsharpstar** [istoreos/istoreos#1387]
希望iStore OS增加可以通过iSCSI或者SMB或者NFS外挂第三方存储的方式。这样可以有更好的扩展性使用软路由进行下载以及文件管理。

**Comment by jjm2473** [comment]
固件不是有吗

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2398/1
