### ISSUE TITLE
希望可以加入上网管理功能

### ISSUE THREAD

**Issue by cnfjice** [istoreos/istoreos#139]
应该是wifi密码泄露了，经常有人连接到wifi上来，希望可以增加个上网管理或者家长控制之类的功能，禁止某个mac上网或者某些应用。因为设备比较多，100多个设备，如果修改wifi密码的话，全部设备都要重新连接，工程量有点大，而且不能保证下次wifi密码不泄露。市场里提供的ip限速不好用，只能限速到1，测试了下依然可以上网。。。

**Comment by houzi-** [comment]
这个功能我们已经在开发了，需要点时间

**Comment by cnfjice** [comment]
> 这个功能我们已经在开发了，需要点时间

感谢感谢。。。辛苦了。。。

**Comment by cnfjice** [comment]
找到一个可用的插件，测试有效。
[上网时间控制luci-app-accesscontrol_1-11_all.zip](https://github.com/linkease/istoreos/files/8932961/luci-app-accesscontrol_1-11_all.zip)

**Comment by jjm2473** [comment]
istore有了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3597/1
