### ISSUE TITLE
R2S软重启，启动失败

### ISSUE THREAD

**Issue by HalcyonDaysssss** [istoreos/istoreos#1390]
### (1) 具体问题

A：在“系统”-“重启”后，软路由无法启动，红灯常亮，WAN不亮，电脑手动修改ip无法访问软路由。拔掉电源在接回去可以正常启动。

### (2) 路由器型号和固件版本

A：固件版本
iStoreOS 22.03.6 2024030112

**Comment by HalcyonDaysssss** [comment]
@jjm2473 大佬有解决的办法吗？

**Comment by jjm2473** [comment]
换tf卡，这个应该早就有人讨论过了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2395/1
