### ISSUE TITLE
ddns绑定v6后用域名访问间接性出现Uncaught TypeError: Cannot read properties of null (reading 'classList')导致页面无法服务,自己输入公网v6就无问题

### ISSUE THREAD

**Issue by fengxuanzheng** [istoreos/istoreos#1391]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：ddns绑定v6后通过域名访问时不时打不开网页需要自己输入v6地址直接访问,浏览器控制台出现ncaught TypeError: Cannot read properties of null (reading 'classList'),之前配置过https,现在关闭了https依旧出现问题,浏览器控制台出现Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.之后就会恢复正常显示,注意虽然webui无法显示但是域名此时连接ssh后台是正常的

### (2) 路由器型号和固件版本

A：
软路由:cpu 12100;主板:精粤B760M(
QEMU Standard PC (Q35 + ICH9, 2009))
固件:
iStoreOS 22.03.6 2024022310

### (3) 详细日志和/或截图

A：
<img width="742" alt="1709607391206" src="https://github.com/istoreos/istoreos/assets/77388367/7a86e078-582a-4be3-a194-65f3c0a836f6">
<img width="736" alt="1709607994549" src="https://github.com/istoreos/istoreos/assets/77388367/b4ef04e2-7a80-4063-9329-a2ab7c5adb09">

B:
系统日志:
Tue Mar  5 08:42:33 2024 user.info : luci: accepted login on / for root from 240e:452:dd88:xxxxxx
Tue Mar  5 08:44:39 2024 daemon.err uhttpd[7397]: Not sandbox environment
Tue Mar  5 08:49:40 2024 user.info : luci: accepted login on / for root from 240e:452:dd88:xxxxxx
Tue Mar  5 09:07:40 2024 authpriv.info dropbear[2067]: Child connection from 240e:452:dd88:xxxxxx
Tue Mar  5 09:07:48 2024 authpriv.notice dropbear[2067]: Password auth succeeded for 'root' from 240e:452:dd88:xxxxxx
Tue Mar  5 09:24:54 2024 daemon.err uhttpd[28494]: Warning: Not all of the space available to /dev/vda appears to be used, you can fix the GPT to use all of the space (an extra 31 blocks) or continue with the current setting?
Tue Mar  5 09:29:56 2024 user.info : luci: accepted login on / for root from 240e:452:dd88:xxxxxx
Tue Mar  5 10:04:19 2024 user.info : luci: accepted login on / for root from 240e:452:dd88:xxxxxx
Tue Mar  5 10:04:51 2024 user.info : luci: accepted login on / for root from 240e:452:dd88:xxxxxx
Tue Mar  5 10:07:12 2024 user.info : luci: accepted login on / for root from 240e:452:dd88:xxxxxx
Tue Mar  5 10:21:25 2024 authpriv.info dropbear[1340]: Child connection from 240e:452:dd88:xxxxxx
Tue Mar  5 10:21:32 2024 authpriv.notice dropbear[1340]: Password auth succeeded for 'root' from 240e:452:dd88:xxxxxx
Tue Mar  5 10:21:32 2024 authpriv.info dropbear[1340]: Exit (root) from <240e:452:dd88:xxxxxx:3996>: Disconnect received
Tue Mar  5 10:21:40 2024 authpriv.info dropbear[1355]: Child connection from 240e:452:dd88:xxxxxx
Tue Mar  5 10:21:46 2024 authpriv.notice dropbear[1355]: Password auth succeeded for 'root' from 240e:452:dd88:xxxxxx
Tue Mar  5 10:21:47 2024 authpriv.info dropbear[1355]: Exit (root) from <240e:452:dd88:xxxxxx>: Disconnect received
Tue Mar  5 10:24:21 2024 user.info : luci: accepted login on / for root from 240e:452:dd88:xxxxxx
Tue Mar  5 10:25:05 2024 authpriv.info dropbear[2136]: Child connection from 240e:452:dd88:xxxxxx
Tue Mar  5 10:25:10 2024 authpriv.notice dropbear[2136]: Password auth succeeded for 'root' from 240e:452:dd88:xxxxxx
Tue Mar  5 10:25:12 2024 authpriv.info dropbear[2136]: Exit (root) from <240e:452:dd88:xxxxxx:3996>: Disconnect received
内核日志:
[内核日志.txt](https://github.com/istoreos/istoreos/files/14489799/default.txt)

**Comment by jjm2473** [comment]
可能是你的浏览器插件导致的。使用chrome浏览器，还有在隐身模式里面打开，看看还有没有错误。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2394/1
