### ISSUE TITLE
能否增加对RTL8822CE网卡的驱动支持（NanoPi R5C）

### ISSUE THREAD

**Issue by acmookey** [istoreos/istoreos#1394]
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：使用的软路由设备是R5C（4G内存），自己购买了和官方同型号的RTL8822CE  M.2 WiFi模块，但是安装启动后，发现在 “网络”中没有 “无线”相关的菜单，想问下目前是否不支持该网卡以及后续能否增加该网卡相关的驱动支持。

PS：从[友善官网的wiki](https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R5C/zh#.E5.A6.82.E4.BD.95.E4.BD.BF.E7.94.A8M.2_WiFi)来看，FriendlyWrt系统应该是支持WiFi模块的。

### (2) 路由器型号和固件版本

A：路由器型号 - **友善R5C(4G内存)**
A：固件版本 - **iStoreOS 22.03.6 2024030112**

### (3) 详细日志和/或截图

A：
```bash
root@r5c:~# dmesg|grep -i wifi
[   10.048446] Intel(R) Wireless WiFi driver for Linux
[   14.931105] auto rmmod mwifiex_pcie
```

**Comment by jjm2473** [comment]
`lsmod|grep rtw_8822ce`

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2391/1
