### ISSUE TITLE
安装firewall4导致防火墙显示系统上存在旧版 iptables 规则，如何恢复iptables

### ISSUE THREAD

**Issue by HalcyonDaysssss** [istoreos/istoreos#1395]
r2s，软件版本iStoreOS 22.03.6 2024030112。求大佬如何安装回去iptables，并卸载firewall4冲突的包

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2390/1
