### ISSUE TITLE
istore中能否增加以前koolsharelede软件中心中的策略路由插件

### ISSUE THREAD

**Issue by cyrinkwork** [istoreos/istoreos#1398]
找到了这个https://github.com/koolshare/ledesoft/tree/master/policy

**Comment by jjm2473** [comment]
openwrt本来就自带策略路由的配置页面，在“网络”-“路由”里面

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2387/1
