### ISSUE TITLE
ramips 构架不做任何修改编译成功后，无法启动

### ISSUE THREAD

**Issue by hq999999** [istoreos/istoreos#1399]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
编译环境：utuntu22.04   
编译istores分支22.03 23.05  master 编译成功无法启动路由 
编译istores分支openwrt-23.05 可以正常启动成功
### (1) 具体问题

A：编译istores分支22.03 23.05 编译成功无法启动路由 
编译istores分支openwrt-23.05 可以正常启动成功

### (2) 路由器型号和固件版本

A：ramips/mt7621
hc5962

### (3) 详细日志和/或截图
![QQ截图20240308092953](https://github.com/istoreos/istoreos/assets/155155038/9482e394-41f8-4da9-a8e3-4d06d2462e3f)

A：

**Comment by jjm2473** [comment]
官方只支持arm64和x86_64，其他的没任何修改。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2386/1
