### ISSUE TITLE
ntfs3-mount缺少kmod-fs-ntfs3依赖

### ISSUE THREAD

**Issue by innmonkey** [istoreos/istoreos#1400]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
编译时提示缺少依赖
WARNING: Makefile 'package/feeds/packages/glib2/Makefile' has a build dependency on 'pcre2/host', which does not exist
WARNING: Makefile 'package/feeds/third_party/luci-app-LingTiGameAcc/Makefile' has a dependency on 'LingTiGameAcc', which does not exist
WARNING: Makefile 'package/diy/ntfs3-mount/Makefile' has a dependency on 'kmod-fs-ntfs3', which does not exist

### (2) 路由器型号和固件版本
型号：x86
分支：istoreos-22.03
### (3) 详细日志和/或截图
![image](https://github.com/istoreos/istoreos/assets/152150297/69c6b15e-1924-4a2f-9b30-86835e5812ba)

**Comment by jjm2473** [comment]
不用管这个，5.15以下的内核使用的是ntfs3-oot
