### ISSUE TITLE
MT7916(AW7916-NPD) 开除36以外的信道，下载速度有问题

### ISSUE THREAD

**Issue by Siriling** [istoreos/istoreos#1404]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：MT7916(AW7916-NPD) 开除36以外的信道，内网测速或者下载文件会断流，速度不过10mbps，速度有问题。
复现条件：
1. 7916开AX模式，信道44-48（只测试了这几个），通道宽度160
2. 手机需要支持160，并且连接速率有2400
3. 连接WiFi进行测速或者下载，出现断流，速度直降10mbps以下

### (2) 路由器型号和固件版本

A：x86，istoreos-22.03.6-2024030112-x86-64-squashfs-combined-efi.img

### (3) 详细日志和/或截图

A：
WiFi设置图
![a7af7eda301c3b2039ee36ea8a6dffa8](https://github.com/istoreos/istoreos/assets/97015395/7fb77a05-047e-46d6-8f90-815d89ccc936)

手机连接图
![e6422ccef6bd61c20e9f06b206aa7ec6](https://github.com/istoreos/istoreos/assets/97015395/b24d09fb-60f0-496b-8b4b-4a46e312f268)

测速图
![f2cfaaf7fcf3ae3ed7b9064fff255c9d](https://github.com/istoreos/istoreos/assets/97015395/ed235188-b61e-43b8-833b-513fe449a9b5)

![4dc9f0864dff2b2707fbc6eb576218dd](https://github.com/istoreos/istoreos/assets/97015395/9413246f-747b-4127-9023-339ec9571623)

**Comment by jjm2473** [comment]
使用157信道试试

**Comment by HC153Yuanyuan** [comment]
请问找到解决方法了吗？我的只要设为160M带宽吞吐就掉到10Mbps以内，换成80M就能跑到1000Mbps。 做AP和做STA现象一致。

**Comment by HC153Yuanyuan** [comment]
> 使用157信道试试

157信道带宽最大只有80M

**Comment by Siriling** [comment]
> 请问找到解决方法了吗？我的只要设为160M带宽吞吐就掉到10Mbps以内，换成80M就能跑到1000Mbps。 做AP和做STA现象一致。

没解决，is的这个驱动一直存在这个问题

**Comment by jjm2473** [comment]
如果是驱动问题，那可能要等24版才会更新驱动了
