### ISSUE TITLE
【功能询问/建议】关于iStoreOS的远程被唤醒功能支持

### ISSUE THREAD

**Issue by OcrSu** [istoreos/istoreos#1406]
请问一下，iStoreOS目前不支持远程被唤醒吗？

远程被唤醒：我在外面使用手机，访问路由器（Openwrt）后台Web页面；使用Web页面中的网络唤醒功能，对br-lan的iStoreOS的电脑进行唤醒；然后iStoreOS电脑就会开机。

我在主板中打开了Wol的开关，也就是PCI设备启动支持。
但我实际中发现，仍然无法远程唤醒iStoreOS的设备。（华硕H310M-R R2.0）
我使用Windows10的另一台设备则可以被唤醒。（B450M Mortor Max)

我注意到某些网卡在远程被唤醒教程中，有在系统中关闭网卡快速启动功能才能实现的。

希望大佬们指导一下QWQ，如果确实不支持目前，希望iStoreOS能够在后续更新中提供支持。

**Comment by jjm2473** [comment]
应该是bios里面设置的吧

**Comment by jjm2473** [comment]
系统里面使用 ethtool 设置网卡： https://wiki.archlinux.org/title/Wake-on-LAN

**Comment by OcrSu** [comment]
> 系统里面使用 ethtool 设置网卡： https://wiki.archlinux.org/title/Wake-on-LAN

收到

不过要等我出院再试试了，我目前肺结核在医院里住院治疗。 :)

**Comment by a5412398** [comment]
下个lucky，里面都带

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2382/1
