### ISSUE TITLE
SMB3 多通道

### ISSUE THREAD

**Issue by jc-huang-90** [istoreos/istoreos#1412]
目前是否支持SMB的多通道叠加网速，没有的话，后续能否考虑支持？

**Comment by jjm2473** [comment]
应该支持吧，这又不需要依赖固件，samba4支持就支持

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2376/1
