### ISSUE TITLE
iStoreOS是否可以做到DHCP手动指定IP与MAC之间绑定？

### ISSUE THREAD

**Issue by newsharpstar** [istoreos/istoreos#1413]
iStoreOS是否可以做到DHCP手动指定IP与MAC之间绑定？
没找到地方在哪配置。

**Comment by lingyunzhiss** [comment]
网络-DHCP-静态地址分配

**Comment by newsharpstar** [comment]
> 网络-DHCP-静态地址分配

是的，我昨天DHCP一个一个页面找的，找到了。为了安全，我又做了IP和MAC的绑定。

**Comment by newsharpstar** [comment]
如果像长期静态保留地址，那么就需要创建静态绑定的时候，在租约期那个地方配置为infinite。

**Comment by filwu8** [comment]
绑定后，重启计算机，重启路由器都不生效， 计算机还是获取的老的ip地址，怎么刷新？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2375/1
