### ISSUE TITLE
docker 出现问题如何解决。。。甚至导致开不了机

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1419]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
今天上午忽然不能访问onenva，回家发现内网也无法登录路由地址，所以重启，但是重启好多次才勉强点亮，进入路由页面发现，docker容器全部停摆了，其中两个的172开头的网络还是重合的，不知道如何产生这样的问题，很多天了一直很稳定忽然搞个这样的事情。。。。而且这几天也没有动过docker，应该说没动过路由设置，使用docke的容器本身不应该有这样的问题吧。。想不明白，不知道是不是bug了，请教遇到这样的问题如何解决

停止docker 然后再打开解决了。。。。但是闹不清这是如何发生的，好好的就这样了，而且重启都不行，差点没能重启成功，有心想重启下再试试，就怕起不来娄，这是不是得给docker加上启动延时让它慢点了，到现在不确定为啥好多次启动不了

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：
![image](https://github.com/istoreos/istoreos/assets/96804858/b4b08cde-31dc-463b-a6ca-70b5f4286c93)
![image](https://github.com/istoreos/istoreos/assets/96804858/06c9eee0-c86e-41d8-94d5-9ce09b331caf)

### (2) 路由器型号和固件版本

A：

FriendlyElec NanoPi R6S

iStoreOS 22.03.6 2024012613
### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
你咋这么多莫名其妙的问题。
可能中毒了，可能文件损坏了，可能硬盘坏了。

**Comment by pili-book** [comment]
我也纳闷啊。。。。。啥也没折腾。。。好好的自己就这样了，搞不清楚这是arm机器就是不稳定还是怎么滴



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年3月15日(周五) 晚上8:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] docker 出现问题如何解决。。。甚至导致开不了机 (Issue #1419)




 
你咋这么多莫名其妙的问题。
 可能中毒了，可能文件损坏了，可能硬盘坏了。

**Comment by pili-book** [comment]
请问下你在这行这么久，你说arm
的软路由和86的软路由稳定性哪个更好了



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年3月15日(周五) 晚上8:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] docker 出现问题如何解决。。。甚至导致开不了机 (Issue #1419)




 
Closed #1419 as completed.

**Comment by jjm2473** [comment]
建议别用USB移动硬盘

**Comment by pili-book** [comment]
没有啊，就是本身的emmc



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年3月15日(周五) 晚上10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] docker 出现问题如何解决。。。甚至导致开不了机 (Issue #1419)




 
建议别用USB移动硬盘

**Comment by jjm2473** [comment]
那可能中毒了吧

**Comment by pili-book** [comment]
最近没动过。。。如何中毒呢。。。。，大哥你别开玩笑



---原始邮件---
发件人: "Liangbin ***@***.***&gt;
发送时间: 2024年3月16日(周六) 中午11:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] docker 出现问题如何解决。。。甚至导致开不了机 (Issue #1419)




 
那可能中毒了吧

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2370/1
