### ISSUE TITLE
挂载的磁盘损坏

### ISSUE THREAD

**Issue by xmyaoshu** [istoreos/istoreos#1424]
挂载的2t磁盘，突然掉了，无法挂载，在PE中DiskGenius显示已损坏，但是可以查看里面文件，磁盘不是物理损坏，像这种情况如何通过命令修复呢，求命令方式修复磁盘的方法，不甚感激。

**Comment by jjm2473** [comment]
如果是文件系统损坏，根据文件系统的类型修复，自己谷歌搜一下就知道了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2366/1
