### ISSUE TITLE
Tehuti TN4010万兆网卡驱动

### ISSUE THREAD

**Issue by fish200000** [istoreos/istoreos#1430]
求大佬支持下万兆网卡

网卡地址
http://mmui.com.cn/index.php?id=439
驱动包地址
http://mmui.com.cn/data/upload/image/9710.zip

网上买了2块做软路由系统，，安装了不识别

**Comment by jjm2473** [comment]
看资料方案是Tehuti TN4010，不知道linux或者openwrt支持了没，你还是反馈给openwrt吧，我们没有人力去移植一个小众的设备驱动。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2360/1
