### ISSUE TITLE
使用群晖虚拟机安装固件时报以下错误并且不能正常开机

### ISSUE THREAD

**Issue by jsczlcmdk** [istoreos/istoreos#144]
![image](https://user-images.githubusercontent.com/105581974/168463048-637edae1-e637-42d5-a10d-772488734299.png)

**Comment by jsczlcmdk** [comment]
能帮忙看看是怎么回事吗

**Comment by jsczlcmdk** [comment]
我是在黑群晖DS918+上安装的
![image](https://user-images.githubusercontent.com/105581974/168463162-a23fa984-ab62-4359-88de-74d1e1c75ace.png)

**Comment by jsczlcmdk** [comment]
![image](https://user-images.githubusercontent.com/105581974/168463235-6c33d343-6d64-4cdd-bb2f-29579ac1c681.png)

**Comment by jannson** [comment]
应该是 OK 了，你按 Enter 试试。或者可以试试今天的版本。

**Comment by jsczlcmdk** [comment]
修改i了IP，可以登录了，就是里面的插件太少了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3583/1
