### ISSUE TITLE
tcp会被重置问题

### ISSUE THREAD

**Issue by jasonnmy** [istoreos/istoreos#1443]
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：用部分国外ip访问内网设备会出现tcp重置问题，主路由都能访问，istore管理页被端口转发后也能访问，但其他内网设备都不能访问，用主路由端口转发到电脑也不能访问

### (2) 路由器型号和固件版本

A：软路由 iStoreOS 22.03.5 2023092815

### (3) 详细日志和/或截图

A：这张是能访问的ip
![Snipaste_2024-03-23_00-05-38](https://github.com/istoreos/istoreos/assets/10269349/8a548952-7ec4-493a-a7ff-98134260417c)

这个ip就是会被重置
![Snipaste_2024-03-23_00-08-01](https://github.com/istoreos/istoreos/assets/10269349/536daf7e-d38b-4809-86b2-cf7563236266)

这是防火墙
![Snipaste_2024-03-22_23-46-17](https://github.com/istoreos/istoreos/assets/10269349/f338e818-26dc-409e-8c2e-61fe6ec9419e)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2348/1
