### ISSUE TITLE
unraid安装istoreos，同一网段下，电脑可以访问istoreos后台无法访问unraid请问需要哪里设置嘛

### ISSUE THREAD

**Issue by xmyaoshu** [istoreos/istoreos#1451]
如题：unraid安装istoreos，同一网段下，电脑可以访问istoreos后台无法访问unraid请问需要哪里设置吗？感谢！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2344/1
