### ISSUE TITLE
git push到github仓库Connection closed by remote host，我应该修改什么才可以解决这个问题

### ISSUE THREAD

**Issue by HETAOSAMA** [istoreos/istoreos#1456]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
git push到github仓库时
kex_exchange_identification: Connection closed by remote host
Connection closed by 20.205.243.166 port 22
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
openclash也正常运行也可以访问油管github等网站
我不使用旁路由时可以正常push，

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：树莓派4b [istoreos-22.03.6-2024031514-raspberrypi-rpi4-squashfs.img.gz]

### (3) 详细日志和/或截图

A：
kex_exchange_identification: Connection closed by remote host
Connection closed by 20.205.243.166 port 22
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by jjm2473** [comment]
找政府投诉电信部门
