### ISSUE TITLE
两点使用体验建议

### ISSUE THREAD

**Issue by carsonrz** [istoreos/istoreos#1460]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：
1.建议“quickstart”增加修改 网关（gateway）的功能，不然修改IP后，还要登录istoreos再修改。
2.【状态】【路由】界面，请增加标记 mac主机名称的功能。

### (2) 路由器型号和固件版本

A：iStoreOS 22.03.6 2024031514

### (3) 详细日志和/或截图

A：
![1711596219272](https://github.com/istoreos/istoreos/assets/5436351/637a7ab1-6d55-4140-9660-d5102cfc2f05)
![1711596902227](https://github.com/istoreos/istoreos/assets/5436351/d5ce94ff-337a-4128-aa87-572105300fc3)

**Comment by jjm2473** [comment]
修改lan ip跟网关有半毛线关系？如果你是要做旁路由，那么有旁路由向导。不是旁路由根本不需要在lan设置网关，这是错误的用法。

**Comment by jjm2473** [comment]
设备名称在dhcp状态里面可以看到（后台的“状态”-“概览”），不是dhcp分配的ip哪来的名称？谁提供这个名称？这个ipv4邻居本质上就是ARP表，又不是只有lan口才有arp表，在这显示名称不是莫名其妙？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2338/1
