### ISSUE TITLE
需要一个MT7922无线网卡的驱动

### ISSUE THREAD

**Issue by zhaikm** [istoreos/istoreos#1464]
一直没有MT7922的无线网卡驱动，能提供一下驱动程序或者集成到下个版本的系统中么

**Comment by slamdunk1987** [comment]
小白同求…

**Comment by zhaikm** [comment]
哪位大神能帮忙提供一下

**Comment by jjm2473** [comment]
老早就集成了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2334/1
