### ISSUE TITLE
无法安装更新iStore里面的任何插件，以及拉取任何Docker运行程序。

### ISSUE THREAD

**Issue by wusuoweiju1** [istoreos/istoreos#1467]
在iStore里更新或者下载和以及拉取任何Docker新插件均提示，无法认证SSL，在系统更新界面更新固件也有这个提示。固件是可以正常上网状态也是能够正常使用。安装失败如图所示。
固件版本：
iStoreOS 22.03.5 2023082509
![Snipaste_2024-04-01_11-34-21](https://github.com/istoreos/istoreos/assets/55151709/5a462033-e79a-4c17-863a-f98d35e9d4d0)
![Snipaste_2024-04-01_11-35-31](https://github.com/istoreos/istoreos/assets/55151709/596bfd92-813a-45fd-b337-22ce9b10f8e0)
![Snipaste_2024-04-01_11-36-04](https://github.com/istoreos/istoreos/assets/55151709/dae82c8e-8a66-45df-9e64-6aa770bdc77b)

**Comment by wusuoweiju1** [comment]
已经解决，从另一台设备中复制ca-certificates过来就可以了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2331/1
