### ISSUE TITLE
upnp报错无法使用及防火墙规则混用

### ISSUE THREAD

**Issue by breeze303** [istoreos/istoreos#1469]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：upnp没有任何连接且在系统日志报错，防火墙提示iptables 和 nftables 规则混用

### (2) 路由器型号和固件版本

A：
型号：n5000es-x86_64
固件版本：iStoreOS 22.03.6 2024031514 

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/122870904/7b5cd8d9-d953-4d21-9c7d-97b4ce75e4a9)
![image](https://github.com/istoreos/istoreos/assets/122870904/7f5114de-327f-4509-a066-537c5334fcc7)

**Comment by breeze303** [comment]
![image](https://github.com/istoreos/istoreos/assets/122870904/b8d18457-7449-481a-8a10-ee70b225aeec)
![image](https://github.com/istoreos/istoreos/assets/122870904/1bed4467-b7cf-40f2-8b07-a1907747cbbb)
重启upnp问题依旧，之前固件版本是正常的，怀疑是fw规则问题导致

**Comment by breeze303** [comment]
![image](https://github.com/istoreos/istoreos/assets/122870904/a34c382e-399c-4af1-ba64-3eb4a31f01c8)

**Comment by breeze303** [comment]
目前问题解决了，引起问题的原因的安装插件的时候自动安装了nft相关的依赖导致防火墙规则混用，upnp出错

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2329/1
