### ISSUE TITLE
PD虚拟机跑 isoreos 提示 interface not found

### ISSUE THREAD

**Issue by zhEdward** [istoreos/istoreos#1475]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：用来做测试，虚拟机跑码完通过 quickstart ，修改ip，虚拟机上网络设置 桥接Thunderbolt Ethernet，然后重启，192.168.6.99 无法进入web。结合标题来看感觉是 网口 没设置还是没识别到

PS：之前操作安装 LEDE固件 以及官方原版固件也是一样步骤都没问题

### (2) 路由器型号和固件版本

A：PD虚拟机，istoreos-22.03.6-2024030112-x86-64-squashfs-combined

### (3) 详细日志和/或截图

A：
<img width="640" alt="image" src="https://github.com/istoreos/istoreos/assets/12438329/a89f8f12-2249-45c4-b452-7f447ed83f42">

<img width="640" alt="image" src="https://github.com/istoreos/istoreos/assets/12438329/8ce409fd-f9ad-406d-a33f-816d4a7ae5d5">

**Comment by jjm2473** [comment]
执行`ip link`看看，以及`lspci -nnk`

**Comment by zhEdward** [comment]
由于没有ip，无法用scp导出编辑，只能截屏 
```ip link```如下：
<img width="927" alt="image" src="https://github.com/istoreos/istoreos/assets/12438329/9d5bde3c-b61c-4993-ae91-059c036a7a7c">
<img width="928" alt="image" src="https://github.com/istoreos/istoreos/assets/12438329/a86f0553-1c83-49b8-b4af-b0d2e1688073">

```lscpci -nnk``` 想输出txt，但报错 **lspci unable to load libkmod resources error 12**无法查看完整，然后没有滚动条，只能截图后半部分，如下：
<img width="930" alt="image" src="https://github.com/istoreos/istoreos/assets/12438329/04bc5e70-8fe6-46f5-ab4a-a0195b456a9f">

**Comment by jjm2473** [comment]
你的网卡是不是在系统第一次启动完成以后才插上去的？也就是说，哪个磁盘初次启动时是没有网卡的，不管你是虚拟网卡还是什么。

算了，直接执行`firstboot -y -r`，恢复出厂设置，让系统重新配置一遍。

**Comment by zhEdward** [comment]
> 你的网卡是不是在系统第一次启动完成以后才插上去的？也就是说，哪个磁盘初次启动时是没有网卡的，不管你是虚拟网卡还是什么。
> 
> 算了，直接执行`firstboot -y -r`，恢复出厂设置，让系统重新配置一遍。

确实。用vmc文件创建的虚拟机，导入就自动跑码，跑完我关闭才在PD给它桥接网络。恢复出厂，现已正常。感谢

**Comment by persiliao** [comment]
@zhEdward 朋友，你用PD跑的iStore旁路由设备连上主路由WIFI能上网吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2325/1
