### ISSUE TITLE
系统内的软件包看到有更新了，不知道敢不敢升级了

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1478]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
![image](https://github.com/istoreos/istoreos/assets/96804858/fc84790e-df7f-4e5e-903b-31155e996cb8)

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
不嫌麻烦就升级，以后出问题别反馈就行了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2323/1
