### ISSUE TITLE
防火墙不能通过鼠标点击定位

### ISSUE THREAD

**Issue by huojicache** [istoreos/istoreos#148]
在2.37版本防火墙-目标可以通过点击定位到目标位置，新版的不能。
希望加回来

**Comment by jannson** [comment]
方便给个截图么？我感觉你说的是老酷软 LEDE 的那个版本。。。

不是我们 iStoreOS 系列。

**Comment by jjm2473** [comment]
这是新版luci的问题，可以去openwrt的项目组那边提issue

**Comment by jjm2473** [comment]
修复了，下个版本固件发布。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3574/1
