### ISSUE TITLE
Plex无法使用硬件解码，已经把移植 Intel GPU 驱动 (i915-oot)选项打开了

### ISSUE THREAD

**Issue by S-wisdom** [istoreos/istoreos#1482]
使用istore里面的plex，安装后无法正常开启硬件解码，要怎么才能加载到核显驱动呢，我用的是N100的机器

**Comment by jjm2473** [comment]
不需要选择驱动，现在都是自动的。至于plex怎么设置，自己网上找教程。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2320/1
