### ISSUE TITLE
[提问]关于独显的兼容性

### ISSUE THREAD

**Issue by OcrSu** [istoreos/istoreos#1484]
我想请问一下，iStoreOS对于独显的适配性如何？

我观察到有些媒体管理软件用核显解码效率太低了。

我想将我的AMD RX6800显卡装我的NAS上面，但我不清楚 iStoreOS有无默认安装驱动。

如果没有，请问该如何安装。

**Comment by jjm2473** [comment]
amd不清楚，驱动是安装了的，但没任何测试机，intel的话基本支持。

**Comment by OcrSu** [comment]
> amd不清楚，驱动是安装了的，但没任何测试机，intel的话基本支持。

明白了，那我到时候换上新显卡后测试一下

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2318/1
