### ISSUE TITLE
docker 容器如何升级

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1485]
![image](https://github.com/istoreos/istoreos/assets/96804858/466e1994-6518-4573-8cff-1adb1810ee0e)
如何能够无损升级docker的容器了
图中的升级和更新如何正确使用

**Comment by ksi1110** [comment]
如果你在部署容器的时，使用镜像的tag是latest，那么将容器停止后重新再启动就会直接更新到最新

**Comment by pili-book** [comment]
怎么停止更新了？是先停止，然后再启动镜像会自动更新了？不用手动重新拉取镜像吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月10日(周三) 上午10:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] docker 容器如何升级 (Issue #1485)




 
如果你在部署容器的时，使用镜像的tag是latest，那么将容器停止后重新再启动就会直接更新到最新

**Comment by jjm2473** [comment]
如果是istore安装的docker插件，一般都有“更新/应用”按钮，如果是自己部署的，那重新部署就是更新了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2317/1
