### ISSUE TITLE
更改LAN口为WAN口后，其余LAN口消失了

### ISSUE THREAD

**Issue by webcf1983** [istoreos/istoreos#1488]
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：默认主板自带网口eth0为WAN口，pcie网卡四个口eth1-4均为LAN口，通过后台更改eth4为WAN口后，eth1-3消失，只剩下eth0和eth4是WAN口了，如何让eth1-3重新出现？

### (2) 路由器型号和固件版本

A：自组pc

### (3) 详细日志和/或截图

A：
![716DB3915DD1E71FC770A1C1B403A1D5](https://github.com/istoreos/istoreos/assets/117358200/4d562b37-dccb-4ae1-9e20-fa084c521b20)

**Comment by webcf1983** [comment]
已解决…
感谢TG群老哥，不知道为啥LAN的配置文件被删掉了
重新添加配置文件内容就好了

**Comment by Huggy2020** [comment]
怎么解决的，在哪里看解决方法

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2314/1
