### ISSUE TITLE
owntone插件，播放时输出选择computer本机播放输出时报错

### ISSUE THREAD

**Issue by wangdongfreesky** [istoreos/istoreos#1490]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
owntone插件，播放时输出选择computer本机播放输出时报错

## 2. 详细叙述
请求失败 (状态：500 Internal Server Error http://192.168.50.3:3689/api/outputs/0/toggle)
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：零刻EQ12 n100主机
iStoreOS 22.03.6 2024031514 / LuCI istoreos-22.03 branch git-24.057.30647-6659faa

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
owntone是官方docker版，有问题反馈给官方项目。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2312/1
