### ISSUE TITLE
异常断电登陆界面打不开，显示下面代码，请问怎么恢复

### ISSUE THREAD

**Issue by slamdunk1987** [istoreos/istoreos#1492]
/usr/lib/lua/luci/dispatcher.lua:1136: Invalid controller file found
The file '/usr/lib/lua/luci/controller/shadowsocksr.lua' contains an invalid module line.
Please verify whether the module name is set to 'luci.controller.shadowsocksr' - It must correspond to the file path!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:1136: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:1236: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:638: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:887: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:482: in function </usr/lib/lua/luci/dispatcher.lua:481>

**Comment by jjm2473** [comment]
估计文件损坏了，用ssh或者ttyd打开终端（ http://istoreos.lan:7681 ），登录以后执行`rm -f /usr/lib/lua/luci/controller/shadowsocksr.lua`，应该就正常了，如果还有其他损坏的文件也这样处理。之后重新安装损坏的插件。

**Comment by slamdunk1987** [comment]
非常感谢🙏发自我的 iPhone在 2024年4月12日，13:35，Liangbin Lian ***@***.***> 写道：﻿
估计文件损坏了，用ssh或者ttyd打开终端（ http://istoreos.lan:7681 ），登录以后执行rm -f /usr/lib/lua/luci/controller/shadowsocksr.lua，应该就正常了，如果还有其他损坏的文件也这样处理。之后重新安装损坏的插件。
