### ISSUE TITLE
pve 8 mt7922 直通 2024031514 驱动存在 网络中 没有无线设置入口

### ISSUE THREAD

**Issue by mr00ff** [istoreos/istoreos#1496]
尊敬的开发者 早/中/晚都好
如题 还需要提供啥
虚拟化: pve 8.1
网卡型号: mt7922
固件版本 iStoreOS 22.03.6 2024031514

```shell
dmesg|grep -i wifi

lspci
```

![3660cc3221e029e81122e3c780446e0](https://github.com/istoreos/istoreos/assets/48547769/98e8b73f-7ed1-4460-b2b1-379376c16819)

![33849205814f9722812f73f8fab2877](https://github.com/istoreos/istoreos/assets/48547769/c64fccf0-3737-46a3-aea0-d4eac4536400)

![image](https://github.com/istoreos/istoreos/assets/48547769/b89a82a6-3c1d-45fb-837d-fdc7a7f4aa62)

补充日志信息 :
Sun Apr 14 18:19:46 2024 kern.err kernel: [   13.159618] mt7921e 0000:00:10.0: Message 0004008a (seq 1) timeout

**Comment by SkiffBoy** [comment]
大佬，最后怎么解决的？

**Comment by 1137129606** [comment]
**相同问题mt7921k x86实体机无法识别**

![f74956998a5f32f0d5880812a7dc4aa](https://github.com/user-attachments/assets/8f2f5a49-2001-4294-bcef-c7c7ee08dac6)
![366414aca8b1ae1ca00fa946db66fe3](https://github.com/user-attachments/assets/55325c34-d855-45a6-8974-3cb35a1338ad)
![15fd18c3a4d12b6a7a4991b55665545](https://github.com/user-attachments/assets/5c6f1322-52a9-44ed-978d-cea7c8e15b09)

**Comment by tonbit** [comment]
![Image](https://github.com/user-attachments/assets/bab4e9ba-2a92-45a2-9189-2a0dd75d36c8)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2308/1
