### ISSUE TITLE
iStoreOS的docker中只剩配置

### ISSUE THREAD

**Issue by bboyjim** [istoreos/istoreos#1498]
## 1.关于你要提交的问题
昨天更新了固件22.03.6 2024031514，iStoreOS的docker中只剩配置了，而且首页的DOCKER配置也出现这个提示。尝试重启docker，重新安装都不行

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图
![1713150310068](https://github.com/istoreos/istoreos/assets/103984701/447722ec-949c-4066-a689-f90521034672)

![1713149073197](https://github.com/istoreos/istoreos/assets/103984701/05f760f6-6848-4a91-9d5a-005de5580367)

**Comment by bboyjim** [comment]
![1713152235162](https://github.com/istoreos/istoreos/assets/103984701/984df9ce-ae2b-4bdc-8de5-54c0ea7fb8ba)
我解决了，因为docker配置被还原了。所以docker目录要自己手动改一下

**Comment by jjm2473** [comment]
怎么会无缘无故还原？你升级时没保留配置？

**Comment by smhjw** [comment]
> ![1713152235162](https://github.com/istoreos/istoreos/assets/103984701/984df9ce-ae2b-4bdc-8de5-54c0ea7fb8ba)
> 我解决了，因为docker配置被还原了。所以docker目录要自己手动改一下

改了以后我怎么保存不了呢

**Comment by jjm2473** [comment]
检查下是不是根目录满了导致无法写入

**Comment by ljiner** [comment]
我这个改完还是不显示

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2307/1
