### ISSUE TITLE
实时监控，即netData安装后打开为空白页

### ISSUE THREAD

**Issue by zeno980** [istoreos/istoreos#1499]
![PixPin_2024-04-15_14-35-22](https://github.com/istoreos/istoreos/assets/44129442/16b1c90b-4f1c-4f94-b0ec-d5f0bf0ad47d)
通过curl localshost:19999发现返回正常

**Comment by jjm2473** [comment]
你是在局域网打开的吗？如果不是，那就自己要注意端口

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2306/1
