### ISSUE TITLE
5月18号更新版本万兆网卡无法识别，退回老版本正常

### ISSUE THREAD

**Issue by zhengyi1314** [istoreos/istoreos#150]
如题

**Comment by genesis-lua** [comment]
你报一下你的网卡型号呀倒是。。。

**Comment by zhengyi1314** [comment]
网卡型号。 CX341         机器就是现在出的那个r86s。  附上

**Comment by genesis-lua** [comment]
完蛋，我也是这个mallenox的网卡，那看来我也不能升级了

**Comment by jjlizz** [comment]
同上，r86s的mellanox 10g sfp光口升级后不能识别，打了mlx4_core也不行，开机启动的时候驱动报错

**Comment by jannson** [comment]
请尝试这个内测版本：https://fw.koolcenter.com/iStoreOS/alpha/

**Comment by jannson** [comment]
请测试最新的版本。

**Comment by fancierr** [comment]
测试过了，没有用，还是0429的版本可以驱动，之后的测试版或者0707万兆光口的网卡依然无法识别

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3570/1
