### ISSUE TITLE
no disk to install

### ISSUE THREAD

**Issue by charlieJ93** [istoreos/istoreos#1500]
x86物理机，install x86的时候提示 no disk to install
扩容成功后还是同样的提示，无法安装
![image](https://github.com/istoreos/istoreos/assets/152156558/e4861caf-37ac-4989-a5f8-7390ef8d6cc9)

**Comment by jjm2473** [comment]
你知道这个功能是干嘛的吗？

**Comment by charlieJ93** [comment]
> 你知道这个功能是干嘛的吗？
不太明白

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2305/1
