### ISSUE TITLE
alist网盘升级到 3.33.0后就不能启动了

### ISSUE THREAD

**Issue by zjqwhy** [istoreos/istoreos#1501]
系统日志显示Tue Apr 16 18:03:45 2024 daemon.info procd: Instance alist::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
<img width="1067" alt="SCR-20240416-pxiv" src="https://github.com/istoreos/istoreos/assets/105403482/45b1d9b1-d3c1-48a9-88da-daa72a18b6b8">

**Comment by jonilchan** [comment]
重启一下Alist看看，我刚升级完也是不能进去，重启完就可以了

**Comment by jjm2473** [comment]
重启系统试试，可能之前的进程没结束或者没清理干净，这是alist自己的问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2304/1
