### ISSUE TITLE
未知原因导致SessionError，提示会话已过期以及权限不足，无法读取UCI配置

### ISSUE THREAD

**Issue by cokar** [istoreos/istoreos#1503]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：内网登陆，输入密码后提交，无法进入登录后页面，提示会话已过期，需要重新登录，提示框下方页面信息显示权限不足，无法读取UCI配置

### (2) 路由器型号和固件版本

A：页脚信息：Powered by LuCI istoreos-22.03 branch (git-24.057.30647-6659faa)/ArgonTheme v2.2.10.10/iStoreOS 22.03.6 2024031514
路由器是N5005

### (3) 详细日志和/或截图

A：![微信截图_20240417151000](https://github.com/istoreos/istoreos/assets/16682946/8578f58a-7b99-4ed1-851a-c3bedbadc40e)

**Comment by jjm2473** [comment]
反正不是固件问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2302/1
