### ISSUE TITLE
是否支持查看某个设备访问的外网http/https地址？

### ISSUE THREAD

**Issue by f1ynng8** [istoreos/istoreos#1504]
打算抓取电视开机广告的来源http(s) url，在路由器上屏蔽掉。

**Comment by jjm2473** [comment]
如果只是http，直接抓包就行了，https的话还需要做mitm代理。

**Comment by f1ynng8** [comment]
> 如果只是http，直接抓包就行了，https的话还需要做mitm代理。

感谢您的回复。我看istoreos有个插件叫“简单网络管控”，可能是luci-app-control-webrestriction？

这个插件的配置里可以配置禁止访问的url，这里也是通过https解密获得的吗？未来是否可以参考这里对url的识别来增加统计设备访问的url统计？

另外，是否可以通过统计某个设备dns解析的方式获得设备访问外网域名的统计？

**Comment by jjm2473** [comment]
那个插件不可能检测https的url，明文最多能检测到访问的域名（SNI，DNS），而且这个插件还不一定支持。http本来就是明文，要检测什么都行，只看性能。而且拦截域名不一定需要检测http/https，在DNS上把域名劫持到无效ip就行了。

**Comment by jjm2473** [comment]
总之不要想着随便就能解析https，如果谁都能看到https内容，那还要https干嘛？

**Comment by f1ynng8** [comment]
非常感谢，明白了！那看来我得换个思路了，用clash之类的代理所有的流量，然后通过clash来看看某个设备访问了哪些url。

**Comment by jjm2473** [comment]
clash也看不到访问https的url。都说了需要mitm代理才有可能抓到url，而且要在客户端安装假的CA证书。具体教程就自己搜索mitm代理

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2301/1
