### ISSUE TITLE
路由会间隔23s左右出现网络波动

### ISSUE THREAD

**Issue by deeezi** [istoreos/istoreos#1508]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：近期使用存在时延波动问题，通过PING发现基本都是在间隔23s左右波动一次，ping外网还是网关IP都存在问题，ping同一台机器安装的其他虚拟机IP是正常，从HTOP上看负荷并不高，系统日志上也没看到异常，网线从软路由接到普通路由器上是可以正常使用的，并没出现波动问题，所以可以排除网络问题的，刷其他固件版本、重装啥的都试了还是无法解决，想请教下是什么问题导致？

### (2) 路由器型号和固件版本

A：是一台N100 X86小主机用ESXI安装的istoreos，版本2024031514。

### (3) 详细日志和/或截图

A：
![屏幕截图 2024-04-18 013205](https://github.com/istoreos/istoreos/assets/72186173/0da06c1d-b142-4a14-9055-aceb2cdf5598)
![屏幕截图 2024-04-18 014749](https://github.com/istoreos/istoreos/assets/72186173/e177f5d3-25c1-43ee-8d2f-eb05c87a6e63)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2298/1
