### ISSUE TITLE
penpot无法安装

### ISSUE THREAD

**Issue by junyi5d** [istoreos/istoreos#1509]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ X] 没有类似的issue

### (1) 具体问题

A：在istore安装penpot，都是默认设置，无法安装成功运行，容器的penpot-penpot-backend-1，penpot-penpot-frontend-1经常卡住

### (2) 路由器型号和固件版本

A：零刻GTR7，已分配docker50G，istore分配4核

### (3) 详细日志和/或截图

A：页面提示 网关错误
请过会儿再来试试，我们正在对服务器进行一些简单维护。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2297/1
