### ISSUE TITLE
ECM拨号如何获取IPV6

### ISSUE THREAD

**Issue by fx607jv** [istoreos/istoreos#1510]
2，编辑/etc/config/network文件，在wwan_6里添加option extendprefix '1',内容后保存
3，编辑/etc/config/dhcp文件，在lan口设置中，添加如下内容：
        option dhcpv6 'server'
        option ra 'server'
        option ra_slaac '1'
        list ra_flags 'managed-config'
        list ra_flags 'other-config'
        option ra_management '1'
设置后还是不行 但是mbim模式是有V6的 就是用ECM模式弄不出来！

**Comment by jjm2473** [comment]
ecm拨号跟你lan口的dhcpv6服务有个屁关系，你改lan口干嘛？

5G模块的问题自己咨询模块厂商，可能需要使用AT命令修改配置。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2296/1
