### ISSUE TITLE
海外用户无法安装iStore软件，和更新软件源，均提示SSL错误

### ISSUE THREAD

**Issue by botong-zhou** [istoreos/istoreos#1513]
*[x] 没有类似的issue

### (1) 具体问题

A：无法在商店安装软件，提示SSL错误，经过相关操作后，更新系统中的openssl组件，我本地网络可以打开，也可以下载到 Packages.gz 这个文件，这个错误也导致软件源配置好后无法更新软件列表

### (2) 路由器型号和固件版本

A：X86_64，固件版本 22.03

### (3) 详细日志和/或截图

A：日志：
istore (失败于： 2024/4/22 20:01:07) > is-opkg install 'app-meta-webvirtcloud'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to istore.linkease.com:443 

截图：
<img width="886" alt="image" src="https://github.com/istoreos/istoreos/assets/4154316/0ab7401d-2176-4acd-8f35-489a4b4e3bb8">

<img width="581" alt="image" src="https://github.com/istoreos/istoreos/assets/4154316/7df81924-26b2-4fa1-a1e4-2359414ba883">

**Comment by jjm2473** [comment]
你用的什么固件？是官方istoreos吗？系统时间对不对？

**Comment by jjm2473** [comment]
你自己的浏览器能否打开 https://istore.linkease.com/repo/

**Comment by botong-zhou** [comment]
浏览器可以打开，但是，路由器本身打开就会错误，但是其他ssl会正常
<img width="826" alt="image" src="https://github.com/istoreos/istoreos/assets/4154316/e7f814fa-e581-49b0-9f33-482b374d88a5">

**Comment by jjm2473** [comment]
你为什么不升级固件呢？怎么还在使用23年的固件，也许升级到新固件就好了，可能只是以为ssl版本太老或者CA证书没更新。

**Comment by botong-zhou** [comment]
哦哦，好的，那升级一下就可以了对吧

Liangbin Lian ***@***.***> 于2024年4月23日周二 14:35写道：

**Comment by jjm2473** [comment]
嗯，如果你只是想测试这个问题有没有解决，可以使用ventoy来测试新版本，比较灵活，随时可以换版本。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2294/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2294/6
