### ISSUE TITLE
修改open files数值，因lucky大吉遇到too many open files原因

### ISSUE THREAD

**Issue by pili-book** [istoreos/istoreos#1516]
1.关于你要提交的问题
最近使用lucky大吉发生too many open files 提示 ，反向代理全部失效，沟通作者有可能是系统限制，查看file-max设置足够大，但是查看ulimit -a 发现open file 只有1024大，想将这个数值设置大一点，如何设置，网上查找修改 /etc/security/limits.conf （系统无这个文件，手动添加也不成功）文件的方法不成功，请问官方如何修改这个数值
![image](https://github.com/istoreos/istoreos/assets/96804858/7f6d5112-d2a6-44eb-bf63-1d8ba7cc2bf2)

Q：是否用关键词搜索了issue? (使用 "x" 选择)

 没有类似的issue
2. 详细叙述
(1) 具体问题
A：

(2) 路由器型号和固件版本
A：nanopi r6s

(3) 详细日志和/或截图
A：

**Comment by simper** [comment]
这个问题怎么解决的后来？我在init.d里修改相关服务的启动脚本也不生效…

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2291/1
