### ISSUE TITLE
建议删掉nas迅雷插件

### ISSUE THREAD

**Issue by gogogogood** [istoreos/istoreos#1518]
我发现NAS迅雷会偷偷跑PCDN，疯狂占用上传
应该是中了挖矿病毒，我容易删了重弄就正常了

**Comment by 138161** [comment]
qBittorrent-qBittorrentEE
4.6.4-4.6.4.10  (amd64;arm64v8;arm32v7) 集成Trackers自动更新
https://hub.docker.com/r/johngong/qbittorrent
http://192.168.100.1:8989

docker pull johngong/qbittorrent
docker create \
    --name=qbittorrent \
    -e QB_WEBUI_PORT=8989 \
    -e QB_EE_BIN=true \
    -e UID=1000 \
    -e GID=1000 \
    -e UMASK=022 \
    -e TZ=Asia/Shanghai
    -e QB_TRACKERS_UPDATE_AUTO=true
    -p 6884:6884 \
    -p 6884:6884/udp \
    -p 8989:8989 \
    -v /mnt/sata2-4/Configs:/config \
    -v /mnt/sata2-4:/Downloads \
    --restart unless-stopped \
    johngong/qbittorrent:latest

**Comment by jjm2473** [comment]
不用的时候关掉容器呗，为什么要下架，总有人要用的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2290/1
