### ISSUE TITLE
r86s的mellanox 10g sfp光口升级后不能识别，打了mlx4_core之后也不行，开机启动的时候驱动报错

### ISSUE THREAD

**Issue by jjlizz** [istoreos/istoreos#152]
如题

**Comment by jannson** [comment]
请尝试这个内测版本：https://fw.koolcenter.com/iStoreOS/alpha/

**Comment by mz-intel** [comment]
@jjlizz 想请教一下怎么烧到emmc的，U盘起来的时候网口能识别，但是install x86后网卡就掉了。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3565/1
