### ISSUE TITLE
Argon 主题设置webm文件为壁纸时，壁纸不会自适应大小

### ISSUE THREAD

**Issue by motto1** [istoreos/istoreos#1521]
![Screenshot_20240425_223656](https://github.com/istoreos/istoreos/assets/116414193/39e610e9-5174-42f6-a5c8-b5624abf97ce)
如图

**Comment by jjm2473** [comment]
反馈给argon官方

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2287/1
