### ISSUE TITLE
iStoreOS与京东云兼容性有问题，只能识别1G网口

### ISSUE THREAD

**Issue by cgfyl** [istoreos/istoreos#1522]
iStoreOS与京东云兼容性有问题，iStoreOS插京东云路由器wan口，iStoreOS后台看只有1G，电脑显示没有问题为2.5G，光猫显示也没有问题2.5G，怀疑iStoreOS网卡驱动兼容性有问题。

**Comment by cgfyl** [comment]
不好意思忘了说，设备是畅网先锋版V2 N100。
请问怎么更改固定端口速率，例如10/100/1000/2500，确保路由每次启动不失效。
不知道iStoreOS改端口速率可以正常2.5G不？
感谢！

**Comment by jjm2473** [comment]
截图看看

**Comment by cgfyl** [comment]
![0011111](https://github.com/istoreos/istoreos/assets/51185050/d47a13e8-7c27-49d1-aa33-4d5d11c03070)
第一个是光猫、第二个是电脑，第三个框选的是插京东云BE6500WAN口

**Comment by jjm2473** [comment]
检查网线质量。既然你的几个网卡都是同一个型号，其他网卡都能协商到2.5G，那应该跟驱动无关。

**Comment by cgfyl** [comment]
请问怎么把这个接口速率锁定到2500，保证路由每次重启都能自动锁定这个端口速率，感谢！

**Comment by jjm2473** [comment]
自己找资料，一般用ethtool命令修改。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2286/1
