### ISSUE TITLE
istoreos的tg群怎么没了

### ISSUE THREAD

**Issue by aa1049372051** [istoreos/istoreos#1523]
# istoreos的tg群怎么没了
https://t.me/+QwxW7aimSMeRdQJX

**Comment by TThwaite** [comment]
你被拉黑了，多半言论不当被封禁了

**Comment by jjm2473** [comment]
不知道，没关注这个群

**Comment by kctony** [comment]
邀請連結過期了, 沒加過這個群, 剛點了是顯示過期

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2285/1
