### ISSUE TITLE
统一文共享 创建用户时 提示用户名必须满足正则表达式

### ISSUE THREAD

**Issue by efffftn5** [istoreos/istoreos#1527]
统一文共享 创建用户时 提示用户名必须满足正则表达式，为什么会提示这种？ 不能简单输入自己想要的用户名吗？
![20240429103907](https://github.com/istoreos/istoreos/assets/168391010/430f3006-7502-45eb-a9ad-478af3bc0d3a)

**Comment by 138161** [comment]
是不是小写和数字？

**Comment by 138161** [comment]
大概没说人话，哈哈

**Comment by Vash90** [comment]
大概意思是，首字母不能大写。

**Comment by jjm2473** [comment]
这个用户名需要符合linux用户的格式，简单来说，就是小写字母开头，后面可以出现小写字母，数字，下划线和减号

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2281/1
