### ISSUE TITLE
升级系统版本 istoreos-22.03.6-2024041213 时，刷写界面跳回主界面，重启后无法进入系统

### ISSUE THREAD

**Issue by javen-yan** [istoreos/istoreos#1528]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：最新版本的istoreOS更新的时候，已经进入刷写界面，但是会自动跳回主页面，再次提示有更新， 多次操作无效。 重启后无法进入系统

### (2) 路由器型号和固件版本

A：升级 istoreos-22.03.6-2024041213， 路由器 j4125 

### (3) 详细日志和/或截图

A：无截图

**Comment by jjm2473** [comment]
提取 `/overlay/upgrade.log` 看看

**Comment by youngslim** [comment]
R66S出现同样问题, 升级系统时跳回主界面, 等待无果后拔电源重启无法进入系统, 网线插口灯不亮.

**Comment by jjm2473** [comment]
@youngslim 你的已经刷坏了，你刷机等了多久拔电的？如果还在刷你就拔了，肯定就损坏系统了。

**Comment by youngslim** [comment]
> @youngslim 你的已经刷坏了，你刷机等了多久拔电的？如果还在刷你就拔了，肯定就损坏系统了。

10分钟左右, 之前正常刷机1-2分钟就自动重启连上网了. 这个都不要紧, 我尝试rufus重新刷最新的0510的版本也还是不行, 上个版本才可以正常开机.

**Comment by jjm2473** [comment]
@youngslim OK，我拿个r66s测试下

**Comment by jjm2473** [comment]
@youngslim 你说的正常版本是哪个版本？还有，你从哪下载的固件，下载的新固件检查下文件大小，有条件计算下md5值。

**Comment by youngslim** [comment]
> @youngslim 你说的正常版本是哪个版本？还有，你从哪下载的固件，下载的新固件检查下文件大小，有条件计算下md5值。

<img width="1129" alt="image" src="https://github.com/istoreos/istoreos/assets/37982578/26ea7170-998a-4d69-b958-7c18b13e4177">
这是官方文档里的下载地址, 我昨天是刷了0510还是网口灯不亮, 0430是可以了, md5确实没有看, 可能也不严谨. 主要之前OTA从未出过问题.

**Comment by jjm2473** [comment]
@youngslim 我测试过了，完全没问题。我用的是balenaEtcher制作sd卡启动。

<img width="472" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/e7aed675-be1c-4c2f-b268-c9bda8f04d9c">

就算ota失败好了，你不是自己用rufus重做系统了吗？我不知道rufus是不是需要自己解压的。

还有，我看你的截图，你为什么下载r6s的固件？r66s跟r6s是同一个硬件吗？现在r66s和r68s都应该下载r6xs路径下的固件。

**Comment by javen-yan** [comment]
我得这个是因为我的磁盘坏掉了发自我的手机-------- 原始邮件 --------发件人： youngslim ***@***.***>日期： 2024年5月13日周一 15:24收件人： istoreos/istoreos ***@***.***>抄送： Javen Yan ***@***.***>, Author ***@***.***>主    题： Re: [istoreos/istoreos] 升级系统版本 istoreos-22.03.6-2024041213 时，刷写界面跳回主界面，重启后无法进入系统 (Issue #1528)

@youngslim 你说的正常版本是哪个版本？还有，你从哪下载的固件，下载的新固件检查下文件大小，有条件计算下md5值。

image.png (view on web)
这是官方文档里的下载地址, 我昨天是刷了0510还是网口灯不亮, 0430是可以了, md5确实没有看, 可能也不严谨. 主要之前OTA从未出过问题.

**Comment by jjm2473** [comment]
r6s跟r66s甚至不是同一家公司出的，

**Comment by youngslim** [comment]
抱歉, 刚刚截图的时候没仔细看. 实际用的是R6XS那个文件夹里的. 
明白你说的, 我回去再试一下balenaEtcher吧, 只是OTA遇到问题了就反馈一下.

**Comment by jjm2473** [comment]
ota会自动校验hash值的，下载的文件肯定不会有错。升级过程出问题可能是有程序无法关闭（但这只会卡住升级程序，不会损坏系统），或者tf卡出了故障，断电。

**Comment by youngslim** [comment]
> ota会自动校验hash值的，下载的文件肯定不会有错。升级过程出问题可能是有程序无法关闭（但这只会卡住升级程序，不会损坏系统），或者tf卡出了故障，断电。

那如果遇到类似情况OTA还是有概率会挂么? 我在这里反馈也是看到有人和我一样, 就是OTA没有跳到之前的那个正在升级, 而是回到首页. 
那只能每次OTA之前做好备份了吧. R66S没有屏幕也看不到是啥问题.

**Comment by jjm2473** [comment]
@youngslim 都说了如果是软件故障，一般不会损坏系统。如果还能自动回到首页，那可能升级程序都没执行到刷机过程呢，这时候在终端里面看看/overlay/upgrade.log有没有错误。

**Comment by youngslim** [comment]
> @youngslim 都说了如果是软件故障，一般不会损坏系统。如果还能自动回到首页，那可能升级程序都没执行到刷机过程呢，这时候在终端里面看看/overlay/upgrade.log有没有错误。

好的, 感谢解答

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2280/1
