### ISSUE TITLE
各种失败啊 安什么软件都失败 是什么问题呢?

### ISSUE THREAD

**Issue by skyheaton** [istoreos/istoreos#1530]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：
![Snipaste_2024-04-30_12-01-00](https://github.com/istoreos/istoreos/assets/63988573/a081c0dd-71a5-49b6-883a-e848198b2c33)
![Snipaste_2024-04-30_12-01-14](https://github.com/istoreos/istoreos/assets/63988573/44f07239-9f84-4733-862c-034980ce00b1)
![Snipaste_2024-04-30_12-01-25](https://github.com/istoreos/istoreos/assets/63988573/72756201-5089-4eb3-8ad8-61ee0d190bd6)

**Comment by jjm2473** [comment]
https://github.com/linkease/istore/issues/122

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2278/1
