### ISSUE TITLE
mtk7922无线网卡问题，ac模式无法设置打开，ax模式很多信道设置了没有wifi

### ISSUE THREAD

**Issue by xx-vv** [istoreos/istoreos#1535]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：mtk7922无线网卡，ac模式无法使用，ax模式48信道后面的好像很少能使用，设置了没有wifi；我用过lean和immortalwrt的固件，均能打开设置ac模式，以及ax模式后面的一些信道选择使用能正常收到wifi

istoreos的有一些地方很好，我挺爱用的，希望作者大大能看看问题，打一下补丁修复一下

### (2) 路由器型号和固件版本

A：x86，n4505，mtk7922无线网卡，istoreos-22.03.6-2024043010-x86-64-squashfs-combined-efi.img

### (3) 详细日志和/或截图

A：这是ac模式设置的样子和日志，就少了一个东西
![47153fd0311b965cfc470ac20503b0f9](https://github.com/istoreos/istoreos/assets/135017778/d7d6665f-163e-4266-b350-c385e0ff8506)

![a24d44e2390d6329ccbe1618bb11d367](https://github.com/istoreos/istoreos/assets/135017778/b4c33d65-c0df-48be-b9c8-31870f69faaa)

这是ax模式设置的样子和日志，没有wifi出现
![393c23fe25cdc3086904b2d68c90aabb](https://github.com/istoreos/istoreos/assets/135017778/2933e63f-e742-48e3-b367-f2352515e258)
![d888dabf3a7462c210d322137b9f8a59](https://github.com/istoreos/istoreos/assets/135017778/591e27b5-6765-4200-9c36-606d0d42471c)

以下是openwrt.ai固件测试，源码是lean的，immortalwrt的固件之前编译试过，wifi和lean是差不多的
![18e79cea0f2f255e37932a2f62fead34](https://github.com/istoreos/istoreos/assets/135017778/cf567aef-5f4a-4d74-9dd9-f49a68d91ca3)
![916d879910effbd88f8f9089ee811412](https://github.com/istoreos/istoreos/assets/135017778/436f1ee8-cdb7-466f-a438-c3fbddf05c87)
![77280213688e6f99f2cb696061366d35_720](https://github.com/istoreos/istoreos/assets/135017778/4f8aa159-2440-4b74-a952-8614102bd341)

**Comment by jjm2473** [comment]
5G频段试试157频道，这个频道不需要雷达回避。

**Comment by lldqvip** [comment]
我也是mt7922的，直通istore后，无线里完全启动不了，设置不了ap。是没有驱动的原因吗，驱动里也加了bin文件一样不行，直通给win一切正常，能修复下这款驱动吗。我是极摩客m6主机rz616网卡![IMG_20240515_221220.jpg](https://github.com/istoreos/istoreos/assets/90892602/5e932eea-9cf7-46ea-b4b8-9292cea4d79a)

![Image_1716184816710.png](https://github.com/istoreos/istoreos/assets/90892602/7f468b68-bf41-42c1-a0d3-39ec73f80618)

**Comment by Goodsunny312** [comment]
我也是mt7922，j1900的x86平台，网上的办法都尝试过了，在添加bin文件到根目录后仅能在客户端模式运行，无法当作ap，ax，ac模式，157频段80mhz都试过了都显示发射功率3dbm无法运行，恳求作者修复该款驱动

**Comment by jjm2473** [comment]
好像wifi直通都有问题

**Comment by xx-vv** [comment]
> 好像wifi直通都有问题

抱歉，之前比较忙，很少看github，关于7922无线网卡问题，我已经卖了，减去烦恼，买了60块的贝尔刷的op做ap，嘎嘎香。而且和上面那哥们差不多的问题，之前我在pve环境下，无论是istoreos，lede，imm的，直通无线网卡都无法驱动wifi，出问题之前都是正常使用的，是突然无线掉了就再也没正常过了。通过pve官方手册的步骤，屏蔽pve本身的无线驱动后就能用，但不稳定，重启物理机那个命令就会失效。但esxi直通无线网卡就能正常使用，当时op的内核版本最高就是6.1的，都试过，之前也换过机子尝试n4120，n4505，物理机直装均没问题。严重怀疑是pve的驱动或者是内核太新了导致的，只在恩山看到这个贴子内容，和我当时的情况一模一样。但我不是很能理解他表达的意思。

[已解决]pve直通pcie无线网卡
https://www.right.com.cn/forum/thread-8286014-1-1.html
(出处: 恩山无线论坛)


![image](https://github.com/istoreos/istoreos/assets/135017778/80ee3638-0ca5-4eb8-8bce-30496c3af476)

**Comment by Kisoul** [comment]
> > 好像wifi直通都有问题
> 
> 抱歉，之前比较忙，很少看github，关于7922无线网卡问题，我已经卖了，减去烦恼，买了60块的贝尔刷的op做ap，嘎嘎香。而且和上面那哥们差不多的问题，之前我在pve环境下，无论是istoreos，lede，imm的，直通无线网卡都无法驱动wifi，出问题之前都是正常使用的，是突然无线掉了就再也没正常过了。通过pve官方手册的步骤，屏蔽pve本身的无线驱动后就能用，但不稳定，重启物理机那个命令就会失效。但esxi直通无线网卡就能正常使用，当时op的内核版本最高就是6.1的，都试过，之前也换过机子尝试n4120，n4505，物理机直装均没问题。严重怀疑是pve的驱动或者是内核太新了导致的，只在恩山看到这个贴子内容，和我当时的情况一模一样。但我不是很能理解他表达的意思。
> 
> [已解决]pve直通pcie无线网卡 https://www.right.com.cn/forum/thread-8286014-1-1.html (出处: 恩山无线论坛)
> 
> ![image](https://private-user-images.githubusercontent.com/135017778/333682141-80ee3638-0ca5-4eb8-8bce-30496c3af476.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTYwMzQsIm5iZiI6MTcyNDU5NTczNCwicGF0aCI6Ii8xMzUwMTc3NzgvMzMzNjgyMTQxLTgwZWUzNjM4LTBjYTUtNGViOC04YmNlLTMwNDk2YzNhZjQ3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxNDIyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDQ0YjJiMTJjYzdhM2YwNzc5ODNjMDA4NmM4YzlhNmM1ZGZkMmVmYWZkODYyZDViYWJhZDFmOThkYTc2NDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9taClCqgfoTtYj-ECpaJVTf50dYcX4o2X5hmKgMoaJA)

怎么屏蔽pve自身的Wi-Fi驱动？网上只有屏蔽显卡驱动的教程

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2275/1
