### ISSUE TITLE
alist修改了端口之后还是得用源端口登录

### ISSUE THREAD

**Issue by 1219ls** [istoreos/istoreos#1539]
<img width="620" alt="联想截图_20240503002741" src="https://github.com/istoreos/istoreos/assets/125373290/2b922893-7cb4-42e3-8a31-8f37b2bb10e9">
<img width="284" alt="联想截图_20240503002747" src="https://github.com/istoreos/istoreos/assets/125373290/035042fe-8f4e-4410-8887-c42974a0def1">

**Comment by jjm2473** [comment]
重启看看还有没有问题，如果有问题，就反馈给alist插件的维护者 https://github.com/sbwml/luci-app-alist

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2272/1
