### ISSUE TITLE
iStored软件商城无法安装软件

### ISSUE THREAD

**Issue by duohetangshui1** [istoreos/istoreos#1540]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：iStored软件商城无法安装软件

### (2) 路由器型号和固件版本

A：玩客云-23.05.3

### (3) 详细日志和/或截图

A：
![screenshot-20240503-004256](https://github.com/istoreos/istoreos/assets/168762145/8e9caa6a-4785-4be6-ba05-3b16e9029505)

**Comment by jjm2473** [comment]
不知道你这个istore是怎么安装的，缺少了`script-utils`这个软件包

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2271/1
