### ISSUE TITLE
系统时间问题

### ISSUE THREAD

**Issue by G00dChina** [istoreos/istoreos#1542]
系统默认的cst时间好像搞错了，NTP同步后，导致bios里时间差8个小时，CST,UTC，+8，-8，option timezone 中，有地方搞错了，我在测试定时开机时发现的问题，硬件为X86工控机。

**Comment by jjm2473** [comment]
这是因为x86的bios没有规范时区导致的，系统里面并不知道bios是用什么时区。你看看bios里面能不能选择时区吧。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2268/1
