### ISSUE TITLE
图标文字依然显示不全

### ISSUE THREAD

**Issue by master-yun-yun** [istoreos/istoreos#1543]
之前反馈过
还是没解决
如图
![QQ图片20240503200657](https://github.com/istoreos/istoreos/assets/79097488/7d8277e8-3230-4fa3-a954-b74d4eaead34)

**Comment by jjm2473** [comment]
之前在哪反馈的，继续在那讨论，没必要重复发。

**Comment by master-yun-yun** [comment]
>

> 之前在哪反馈的，继续在那讨论，没必要重复发。

之前发的回复说下一个版本解决，然后关闭话题了

**Comment by jjm2473** [comment]
关闭了也可以继续回复啊，没锁定就行

**Comment by jjm2473** [comment]
不然现在又要找负责人反馈？

**Comment by master-yun-yun** [comment]
> 关闭了也可以继续回复啊，没锁定就行

可能我理解有误，以为关闭了就不能回复了，也以为关闭了后管理员不会再去看了。
如果觉得影响了你们，删除即可。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2267/1
