### ISSUE TITLE
能否把tailscale版本升级一下？

### ISSUE THREAD

**Issue by master-yun-yun** [istoreos/istoreos#1544]
内置版本太古老了，自己下载的ipk无法升级。
现在都1.64.2了。内置的还是1.3x。
谢谢

**Comment by master-yun-yun** [comment]
后来发现，有2种，一种叫tailscale，另一种叫tailscaled，换一种升级成功。
不知道tailscale和tailscaled有什么区别？

**Comment by jjm2473** [comment]
试试从istore卸载重装

**Comment by YARRN** [comment]
新装的tailscale版本也很旧……

**Comment by lawiker** [comment]
是的，求大佬升级一下，辛苦了

**Comment by iloveyou1919** [comment]
求更新呀，大佬。

**Comment by YARRN** [comment]
看了下op的软件库版本就很旧，试着直接下最新包手动解压安装了之后发现版本是新的，但意料之中的luci和路由狗都不识别

**Comment by jjm2473** [comment]
tailscale是openwrt官方仓库提供的，我们一般不会去专门升级，除非有bug影响使用。

**Comment by YARRN** [comment]
目前的tailscale版本下，分配的smb协议没法被安卓设备远程访问，用webdev就行。不知道这算不算影响使用。tailscale官方是提示这个版本太旧，有安全漏洞的。

**Comment by jjm2473** [comment]
@YARRN 那你试过tailscale新版本就能让安卓访问smb协议吗？

openwrt今天release了22.03.7，tailscale都还是1.32，如果有严重问题可以反馈给openwrt。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2266/1
