### ISSUE TITLE
更新到 iStoreOS 22.03.6 2024043010 后，alist 无法启动

### ISSUE THREAD

**Issue by wao1201** [istoreos/istoreos#1550]
### (1) 具体问题

A：alist 无法启动

### (2) 路由器型号和固件版本

A：iStoreOS 22.03.6 2024043010, R5S

### (3) 详细日志和/或截图

A：页面显示“Alist 未运行”，直接访问相应 IP:Port 无法访问

**Comment by wao1201** [comment]
补充：alist 是通过 store 安装的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2261/1
