### ISSUE TITLE
v2ray-a

### ISSUE THREAD

**Issue by jhyeguang** [istoreos/istoreos#1552]
![微信图片_20240506220136](https://github.com/istoreos/istoreos/assets/163638000/cff5bf3a-edda-42b3-b8c9-8323a10ce46b)
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
v2ray-a安装了，运行里不能启动
A：

### (2) 路由器型号和固件版本
X86 ,iStoreOS 22.03.6 2024043010
A：

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
GFW的问题，反馈给政府。

**Comment by jjm2473** [comment]
你看看自己的浏览器能不能打开 hubmirror.v2raya.org ，如果不行，要么这个网站本身已经下线，要么就是需要翻墙

**Comment by jhyeguang** [comment]
谢谢
