### ISSUE TITLE
IPv6端口问题

### ISSUE THREAD

**Issue by jhyeguang** [istoreos/istoreos#1556]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：IPv6下，域名解析后，istoreos下开放的端口都可以直接访问，能不能设置可以自己更改IPv6可开放的端口，用IPv6反代IPv4地址端口来访问

### (2) 路由器型号和固件版本

A：x86_64

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
istore里面安装socat就行了，支持ipv6转ipv4或者反过来

**Comment by jhyeguang** [comment]
ipv6下，所有端口都暴露在公网下，不安全，希望关闭IPv6大部分端口，留几个反代用或管理用端口，

**Comment by jjm2473** [comment]
放心，默认都是不开放的，要开放端口的话，不管ipv6还是ipv4都要在防火墙设置。

**Comment by tudoubocai** [comment]
同问，域名解析到ipv6后，所有端口都能访问，相当于ipv6没有防火墙。
请问应该怎么处理？

**Comment by jjm2473** [comment]
@tudoubocai 你在内网测试的吧，内网肯定都能访问，要测应该换其他网络，例如手机的数据网络。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2257/1
