### ISSUE TITLE
samba4 共享目录 wan口无法访问

### ISSUE THREAD

**Issue by Vash90** [istoreos/istoreos#1560]
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述

通过 lan口 能访问，wan口 不行。
wan口接上级路由，分配ip: 192.168.2.100
lan口 ip:192.168.100.1

防火墙开启端口:137,138,139,445
samba4 监听:br-lan,wan

### (1) 具体问题
A：lan口可以正常访问  \\192.168.100.1
      wan口无法访问到  \\192.168.2.100

### (2) 路由器型号和固件版本
A：istoreos-22.03.6-2024031514-x86-64

### (3) 详细日志和/或截图
A：
![image](https://github.com/istoreos/istoreos/assets/6929525/c01fe08c-4672-4f08-9826-e033c59b2d91)
![image](https://github.com/istoreos/istoreos/assets/6929525/943c945b-660d-4a45-aa5d-f431e5c4a74f)

**Comment by Vash90** [comment]
继续弄了下，现在看 因该不是 istoreos 的问题。
电脑，和手机能通过 wan口 ip访问到samba了。只是其中另一条 win10 死活访问不了，各种设置。

**Comment by Vash90** [comment]
1 开始->运行（快捷键“win+R”）,输入“regedit”后回车，打开注册表编辑器。

2 依次打开“HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters”。

3 找到“AllowInsecureGuestAuth”，如果没有，就新建一个DWORD（32）项重命名为“AllowInsecureGuestAuth”，设为“1”，确定。

4 重试，已能成功访问共享文件夹。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2254/1
