### ISSUE TITLE
iStoreOS 在 Dell 7090mff 上安装失败

### ISSUE THREAD

**Issue by Gaped511** [istoreos/istoreos#1563]
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：在 Dell 7090mff 上安装 istoreos, 每次都是跑了一段代码以后直接黑屏, 然后将机器连接到路由器上也不能通过网页访问.

### (2) 路由器型号和固件版本

A：Dell 7090mff (i7-10700T, 32G, 256G nvme, 1T data, 用 DP 连接显示器), 用了0430 的那个固件.

### (3) 详细日志和/或截图

A：

**Comment by Vash90** [comment]
最好有 跑到最后的代码，截图。
另外，单网口设备，唯一的网口可能是lan口。不要接路由，直接接电脑访问，192.168.100.1试试。

**Comment by lizhi10** [comment]
> 最好有 跑到最后的代码，截图。 另外，单网口设备，唯一的网口可能是lan口。不要接路由，直接接电脑访问，192.168.100.1试试

**Comment by jjm2473** [comment]
录屏看看，我们可没这个机器来测试。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2252/1

**Comment by billdegithub** [comment]
vi /etc/default/grub
修改GRUB_CMDLINE_LINUX：在文件中找到 GRUB_CMDLINE_LINUX="" 这一行，在双引号中间加上 nomodeset。如果该行已有其他参数，记得用空格隔开。
修改前：GRUB_CMDLINE_LINUX="quiet"
修改后：GRUB_CMDLINE_LINUX="quiet nomodeset"
你遇到的“进入系统后黑屏”问题，大概率是Linux内核的KMS（Kernel Mode Setting，内核模式设置）与你的集显或DP接口之间出现了兼容问题

不过不能升级，升级系统又的手工改。。如果能从固件方面修复就OK

**Comment by jjm2473** [comment]
iStoreOS的x86版本支持配置内核启动参数，且升级时可以保留：

<img width="2680" height="1750" alt="Image" src="https://github.com/user-attachments/assets/764703cd-9dae-4292-8822-be1669e7d4a8" />

**Comment by jjm2473** [comment]
> vi /etc/default/grub
> 修改GRUB_CMDLINE_LINUX：在文件中找到 GRUB_CMDLINE_LINUX="" 这一行，在双引号中间加上 nomodeset。如果该行已有其他参数，记得用空格隔开。
> 修改前：GRUB_CMDLINE_LINUX="quiet"
> 修改后：GRUB_CMDLINE_LINUX="quiet nomodeset"

这个方式不适用于openwrt/istoreos，对于openwrt/istoreos，需要在启动到grub时按e编辑，加上参数启动，启动以后再按我上面提到的方式持久化内核参数。

**Comment by jjm2473** [comment]
目前尚不知道这个问题是不是可以靠禁用modeset解决。因为我还怀疑可能是供电不足。
