### ISSUE TITLE
HP 331FLR 网卡无法识别和加载

### ISSUE THREAD

**Issue by flyingmyname** [istoreos/istoreos#1564]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "" 选择)
* [x] 没有类似的issue

### (1) 具体问题
D2550 主板上使用HP 331FLR（BCM95719）+PCIE X1转接板，安装iSotreOS，能在lspci里面看到Broadcom的Ethernet Contorller，但是没有加载。在web页面的接口里面找不到相应的eth接口。
A：

### (2) 路由器型号和固件版本
路由器型号：D2550 itx主板（主板型号：TIGD2-CI V1.0）
istoreos-22.03.6-2024043010-x86-64-squashfs-combined-efi
A：

### (3) 详细日志和/或截图
![5D33EEA03669F4A3552B14F17E04BEB8](https://github.com/istoreos/istoreos/assets/69414913/ce624dc3-79a1-465e-a314-d33b0533583c)

A：

**Comment by jjm2473** [comment]
自己搜一下这个网卡在openwrt上应该安装什么驱动，istoreos也是一样的。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2251/1
