### ISSUE TITLE
H28K使用了最新的固件后，在局域网连不上了

### ISSUE THREAD

**Issue by wxk0721** [istoreos/istoreos#1569]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：刷机后，使用网线连接软路由和电脑，是可以登录上去的。但是如果电脑不插在软路由上，而是插在上层硬路由上，使用软路由局域网ip就登录不上去了。
比如我的软路由ip是：192.168.0.100，当电脑插在软路由上的时候，使用这个地址可以连接并登录，如果电脑插在了上层路由器上就打不开这个地址了。

### (2) 路由器型号和固件版本

A：H28K，固件：istoreos-22.03.6-2024051012-h28k-squashfs.img

### (3) 详细日志和/或截图

A：

**Comment by Gaped511** [comment]
这是因为去年最后几个版本中有一项修改，禁止从wan访问软路由导致的。
在防火墙里面允许 wan 访问和转发就行了

**Comment by jjm2473** [comment]
默认禁止wan口访问路由器，防止被攻击。在lan口登录后台以后，打开“网络”-“防火墙”，在wan区域的“输入”那边选择“允许”就行了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2247/1
