### ISSUE TITLE
istoreos安装迅雷下载无法运行，求解[抱拳]

### ISSUE THREAD

**Issue by jhp1015** [istoreos/istoreos#1575]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by yeqingyeqing** [comment]
我也是，x86全新安装istoreos，从商店下载，安装镜像后web打不开，显示404 not found，改成宿主网络也不行，docker根目录已经迁移过了。

**Comment by jhp1015** [comment]
是不是官方固件的问题？



---原始邮件---
发件人: "Ye ***@***.***&gt;
发送时间: 2024年5月14日(周二) 上午9:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] istoreos安装迅雷下载无法运行，求解[抱拳] (Issue #1575)




 
我也是，x86全新安装istoreos，从商店下载，安装镜像后web打不开，显示404 not found，改成宿主网络也不行，docker根目录已经迁移过了。

**Comment by fx607jv** [comment]
我也一样！不知道什么时候可以解决

**Comment by jhp1015** [comment]
只能等官方更新了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月14日(周二) 中午12:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] istoreos安装迅雷下载无法运行，求解[抱拳] (Issue #1575)




 
我也一样！不知道什么时候可以解决

**Comment by soulripper13** [comment]
use cnk3x/xunlei:3.7.1 not cnk3x/xunlei:latest

**Comment by soulripper13** [comment]
> 我也是，x86全新安装istoreos，从商店下载，安装镜像后web打不开，显示404 not found，改成宿主网络也不行，docker根目录已经迁移过了。

use cnk3x/xunlei:3.7.1 not cnk3x/xunlei:latest

**Comment by Vash90** [comment]
看看，docker 里面 迅雷的 容器 启动了吗？有时候，服务里的迅雷点了启动，但是docker没启动

**Comment by fx607jv** [comment]
都试过了 明显安装的时候 镜像下载不全！

**Comment by jhp1015** [comment]
有解决办法吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月15日(周三) 中午12:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] istoreos安装迅雷下载无法运行，求解[抱拳] (Issue #1575)




 
都试过了 明显安装的时候 镜像下载不全！

**Comment by jhp1015** [comment]
这是新的镜像地址吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月15日(周三) 中午11:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] istoreos安装迅雷下载无法运行，求解[抱拳] (Issue #1575)




 
use cnk3x/xunlei:3.7.1 not cnk3x/xunlei:latest

**Comment by yeqingyeqing** [comment]
> > 我也是，x86全新安装istoreos，从商店下载，安装镜像后web打不开，显示404 not found，改成宿主网络也不行，docker根目录已经迁移过了。
> 
> use cnk3x/xunlei:3.7.1 not cnk3x/xunlei:latest

谢谢，这个镜像是能用的，目前已运行。 cnk3x/xunlei:3.7.1 ，在自定义处拉取这个镜像。

**Comment by fx607jv** [comment]
OK 搞定 谢谢

**Comment by jhp1015** [comment]
你这是具体怎么操作的？

**Comment by miaoxiaohu** [comment]
![image](https://github.com/istoreos/istoreos/assets/37968528/c84523d7-d7f4-4e8d-8305-93fafc2568d0)

**Comment by miaoxiaohu** [comment]
> 你这是具体怎么操作的？

![image](https://github.com/istoreos/istoreos/assets/37968528/22f09501-bda1-423e-9c65-244cd776cece)

**Comment by yczxhcq1** [comment]
换了3.7.1，提示“当前无法使用此页面”  各位怎么解决的？

**Comment by jjm2473** [comment]
这个404只是因为新版本没有自动重定向/web到迅雷首页，实际上自己删掉地址栏的/web就行了

**Comment by jjm2473** [comment]
不过插件也会改成不加/web

**Comment by alex086cn** [comment]
> > 你这是具体怎么操作的？
> 
> ![image](https://private-user-images.githubusercontent.com/37968528/331802717-22f09501-bda1-423e-9c65-244cd776cece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTk3OTcsIm5iZiI6MTcxNjQ1OTQ5NywicGF0aCI6Ii8zNzk2ODUyOC8zMzE4MDI3MTctMjJmMDk1MDEtYmRhMS00MjNlLTljNjUtMjQ0Y2Q3NzZjZWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEwMTgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NGVjNTc1Y2Q1MGQ5MDYxMGRiYTY3M2ZjM2RmMGQ1Y2RmMGRmY2EzMDcyOWZkNGJiMGIzNWZiZGZkOTJmYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fLfgeXdDOsIoEWfxycul59oPYUqAd3EVPEy2tAqOBxQ)

我也是困扰了两天，刚才发现用新的镜像地址，不勾选host network可以成功，勾选了就提示DNS

**Comment by jjm2473** [comment]
@alex086cn 都说了跟dns没什么关系

**Comment by jjm2473** [comment]
插件升级到 1.0.3 即可解决此问题，使用哪个版本的镜像都行。大概十分钟以后就可以在istore看到插件升级按钮了。

**Comment by jhp1015** [comment]
我的x86 istoreos最新版，安装 4.77-5passwall经常断流，重启一下dnsmasq就恢复了，求解

**Comment by c36128898** [comment]
> 插件升级到 1.0.3 即可解决此问题，使用哪个版本的镜像都行。大概十分钟以后就可以在istore看到插件升级按钮了。

我更新到了1.0.3，但是还是打不开管理页面，按上面的换自定义源也不行，请问还有其他解决方式么

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2242/1
