### ISSUE TITLE
每次重启dockerd都随机新的接口

### ISSUE THREAD

**Issue by chrisuhg** [istoreos/istoreos#1577]
* [ x] 没有类似的issue

## 2. 详细叙述
网络接口中的docker0网桥，附加的docker网口每次重启dockerd都会导致接口全部丢失并生成新的接口
之前刚安装好istore的时候好像没有发现这样的问题，后来更新过重置过网络才出现的这个问题。

### (1) 具体问题

A：如何固定docker的网络接口

### (2) 路由器型号和固件版本

A：Mini主机；
[Powered by LuCI istoreos-22.03 branch (git-24.057.30647-6659faa)](https://github.com/openwrt/luci) / [ArgonTheme v2.2.10.10](https://github.com/jerrykuku/luci-theme-argon) / iStoreOS 22.03.6 2024043010

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/34882677/d69a00d3-1ac8-4c94-bc88-8e64923f03f9)

**Comment by jjm2473** [comment]
可能你安装了第三方软件源的docker，导致不兼容了，恢复出厂设置看看还有没有问题吧

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2241/1
