### ISSUE TITLE
R6S网络接口提个建议

### ISSUE THREAD

**Issue by adminlte** [istoreos/istoreos#1579]
现在R6S的wan是eth1、lan1是eth2、lan2是eth0，能不能把固件的wan改成eth0、lan1改成eth1、lan2改成eth2

**Comment by jjm2473** [comment]
不能，这是R6S外壳标记好的，改了反而混乱。如果有特殊需要可以自己在网络-接口配置里面修改。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2239/1
