### ISSUE TITLE
登录页面能否增加个二次验证(2FA)提升安全性

### ISSUE THREAD

**Issue by clangcn** [istoreos/istoreos#1581]
登录页面能否增加个二次验证(2FA)提升安全性？

**Comment by Carseason** [comment]
除非不用现在的luci体系，不然只能靠上游

**Comment by jjm2473** [comment]
用ddnsto啊

**Comment by clangcn** [comment]
> 用ddnsto啊

用着ddnsto呢，不过我的直接展示页面，不需要ddnsto再次验证

**Comment by Carseason** [comment]
感觉可以做一个前向代理，来代理路由的 80 端口，ddns 公网访问的话 使用前向代理的服务来访问，而不是直接访问路由器的默认端口，这样就可以实现验证码了

**Comment by jjm2473** [comment]
> 用着ddnsto呢，不过我的直接展示页面，不需要ddnsto再次验证

估计只是因为你在同一个网络里面已经登录过了。ddnsto是需要扫描登录才能访问的。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2237/1
