### ISSUE TITLE
希望出一下HT3（EasePi ARS4）带WIFI的固件，谢谢！！！

### ISSUE THREAD

**Issue by shuaidaoya** [istoreos/istoreos#1583]
## EasePi ARS4
内核版本 | 5.10.201
固件版本 iStoreOS 22.03.6 2024011219 / LuCI istoreos-22.03 branch git-24.009.14990-dc7527f 
目标平台 rockchip/rk35xx 

![03f3926fb84464391b523b187372810](https://github.com/istoreos/istoreos/assets/130221900/9b6a9bca-4f11-4634-a92f-efe38b361d43)

![微信图片_20240517232543](https://github.com/istoreos/istoreos/assets/130221900/b280fb93-ce37-4885-a3d5-fadf6e4aa1f2)
e335a7fde0)

**Comment by jjm2473** [comment]
关键看wifi模块是什么型号的，如果有驱动的话就能识别，没驱动也没办法

**Comment by dragonflylee** [comment]
@shuaidaoya WIFI芯片 aic8800, 对应分支 https://github.com/dragonflylee/istoreos
暂不支持AP模式

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2236/1
