### ISSUE TITLE
新版定期出现高速上传下载是为啥？

### ISSUE THREAD

**Issue by lingchvip** [istoreos/istoreos#1584]
我是用一旧笔记本做的系统，现在只要装202401月以后的新版os，就是网线接口要换的以后的，差不多间隔一两天，半夜就会自行出现占满带宽的高速上传下载，导致cpu和内存100%，cpu温度飙到七八十度，卡机，重启依旧，我是没开放外部端口，外网没办法访问的。装回202312月以前的版本就不会有这现象，不知道是哪里设置出问题？

**Comment by jjm2473** [comment]
你确定没用pt/bt下载？或者网心云之类的pcdn？

**Comment by phxufeng** [comment]
我是做旁路由的，最近也出现了这种情况，主路由是爱快的，发现上行很大。一直要 2M 的上行。而且系统进程中内存占比高的结束后就正常了。
旁路由上没有安装 pcdn 的应用。

**Comment by jjm2473** [comment]
那可能中毒了呗，之前就有用户中毒以后出现这种现象

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2235/1
