### ISSUE TITLE
首页IP地址这里不能自己选择接口

### ISSUE THREAD

**Issue by kangSenjon** [istoreos/istoreos#1587]
![360截图20240520104650320](https://github.com/istoreos/istoreos/assets/170283610/e351d8de-d9f3-4aeb-8f68-7ae5109db226)
默认显示wan口也可以，现在我这里显示的是其他接口

**Comment by jjm2473** [comment]
谁让你在iptv上加默认网关的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2232/1
