### ISSUE TITLE
编译E8450的固件  不能分配IP地址 没有IPV4的网关地址

### ISSUE THREAD

**Issue by zow2023** [istoreos/istoreos#1595]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
E8450是什么东西，什么架构的？

**Comment by zow2023** [comment]
linksys的路由器  ,aarch64_cortex-a53,有劳你看下什么原因，。

**Comment by jjm2473** [comment]
这个没有支持，编译了也没用的。目前官方支持的只有rk35xx系列，rk33xx系列，x86系列，rpi4这些。非官方支持的机型就算编译能成功，很多功能可能都没适配，例如沙箱，以及MTD分区也不一定支持，至少没测试过。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2225/1
