### ISSUE TITLE
软件包插件类的小部分建议

### ISSUE THREAD

**Issue by huanshentianling** [istoreos/istoreos#1600]
建议istoreos整体固件安装的软件弄个分区或分类，
第一个
istoreos系统内置安装的必须的缺了就不稳定的软件包分类。

第二个istoreos系统自带内置安装的可卸载或升级后不影响istoreos稳定的软件包分类(但是能不能用就不一定了)

第三就是istoreos内置商店下载的软件分类(不包括路由狗的)。

最后就是用户其他渠道下载的各种软件包插件的分类(包括路由狗内的)
还有一个就是优化下已安装软件包的列表显示方式，现在的感觉很是不方便

又多个其他建议，希望能设置不自动挂载指定的部分磁盘/硬盘

**Comment by jjm2473** [comment]
前面的用沙箱。istoreos本身就有rom分区，系统自带软件都在里面。overlay分区是你自己安装的软件。如果你还要再加一层，那就是沙箱。

最后设置磁盘不挂载可以在“系统”-“挂载点”配置，只要配置好，并且不启用，那就不会挂载。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2221/1
