### ISSUE TITLE
无法挂载ntfs硬盘了

### ISSUE THREAD

**Issue by cc1213** [istoreos/istoreos#1601]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：升级后不能挂载ntfs硬盘了的

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
一般都是文件系统损坏，试试用ntfsfix命令修复。

**Comment by zhiqiang-gao** [comment]
same issue with istore R23.9.9

**Comment by jjm2473** [comment]
R23.9.9是什么鬼，这根本就不是istoreos的版本号

**Comment by londbell** [comment]
> R23.9.9是什么鬼，这根本就不是istoreos的版本号

其实lean的istoreos确实有这个版本

<img width="1025" height="237" alt="Image" src="https://github.com/user-attachments/assets/c1100725-32a7-4e8d-b477-c5605b46ebe6" />

**Comment by jjm2473** [comment]
如果是lean的版本，那可以去他的群或者github上反馈，lean的版本跟官方istoreos差别很大。这个jdcloud固件好像还是4.x的内核，不一定有好的ntfs驱动。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2220/1
