### ISSUE TITLE
文件管理报错：AxiosError: Request failed with status code 500

### ISSUE THREAD

**Issue by Zephyr0131** [istoreos/istoreos#1604]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：首页点击文件管理，报500错误，官网未找到其他查看日志的办法。

### (2) 路由器型号和固件版本

A：
iStoreOS 22.03.6 2024052410

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/10428249/47be2b6e-9fd6-4b90-8889-8d5ee6f500f8)

**Comment by jjm2473** [comment]
什么浏览器

**Comment by Zephyr0131** [comment]
chrome

**Comment by kylin0329** [comment]
我PVE安装的虚拟机进去之后也是报这个错

**Comment by yuhua2025** [comment]
我的问题是：打开文件管理后要等大慨40秒才出现内容
![屏幕截图 2024-06-02 151104](https://github.com/istoreos/istoreos/assets/117059330/688d08fc-2a80-4f2b-a637-5e678fccd70a)

**Comment by seafeee** [comment]
我也是同样的问题。 软路由：r66s 使用的chrome浏览器

**Comment by seafeee** [comment]
![image](https://github.com/istoreos/istoreos/assets/49563049/6ce86362-9209-4904-81cc-301d96b4ea2a)
@zorro0109 这个功能是易有云提供的，所以得把这个服务打开

**Comment by jjm2473** [comment]
这个后台API确实是易有云提供的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2217/1
