### ISSUE TITLE
能否实现IP与mac绑定、标记名称、限速的功能

### ISSUE THREAD

**Issue by zmj987** [istoreos/istoreos#1611]
istoreos

能否实现IP与mac绑定、标记名称、限速的功能

像tp-link的AC的ipmac绑定和限速功能。

**Comment by jjm2473** [comment]
名称和ip可以在dhcp里面配置，限速要用qos插件

**Comment by PlutoNameless** [comment]
> 名称和ip可以在dhcp里面配置，限速要用qos插件

当前iStoreos软件商店中，只有一个基础的eqos插件，它仅支持ipv4的限速；
期望能有一个支持ipv6和mac地址的限速，尤其是mac地址，因为如果本地网络有ipv6后，对该设备v4和v6分别限速后，如果该设备同时走了v4和v6的流量，是没办法合计到一起进行限速控制。

**Comment by jjm2473** [comment]
那还有其他更好用的qos插件吗，推荐下

**Comment by PlutoNameless** [comment]
> 那还有其他更好用的qos插件吗，推荐下

我当前在使用这个库https://github.com/sirpdboy/luci-app-eqosplus

**Comment by GeorgeGalway** [comment]
> > 那还有其他更好用的qos插件吗，推荐下
> 
> 我当前在使用这个库https://github.com/sirpdboy/luci-app-eqosplus

这个库实测安装不少问题

**Comment by luoye-fe** [comment]
sirpdboy/luci-app-eqosplus 这个库 v6 似乎无用

**Comment by jjm2473** [comment]
24.10 可以试试从软件包安装 luci-i18n-nft-qos-zh-cn ，会出现在服务-QoS Nftables 版。然后先去“根据 Mac 地址限制速率”勾选启用，保存应用。然后最下面就可以配置按mac地址限速了。我测试了下，只对上传限速有效，下载无法限速。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2211/1
