### ISSUE TITLE
卸载nginx后无法进入后台

### ISSUE THREAD

**Issue by Nuo-Mituan** [istoreos/istoreos#1615]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
卸载nginx后无法进入后台访问显示404 Not Found
nginx/1.21.3

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
卸载nginx后无法进入后台
### (1) 具体问题

A：卸载nginx后无法进入后台

### (2) 路由器型号和固件版本

A：x86 istoreos-22.03.6-2024052410

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/39124372/f20dd506-89c2-4acd-9b70-ccdb0e11c3eb)

能否通过命令行对系统进行在线更新，这是否能解决问题？

**Comment by Nuo-Mituan** [comment]
通过istore安装的Nginx，也是通过istore卸载的Nginx

**Comment by Carseason** [comment]
/etc/init.d/uhttpd start

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2208/1
