### ISSUE TITLE
创建新磁盘分区出错！

### ISSUE THREAD

**Issue by magi-Z** [istoreos/istoreos#1616]
### (1) 具体问题
mmcblk1p4创建时出错Error: Can't create any more partitions. 无法创建新分区扩容overlay和迁移docker！！！
### (2) 路由器型号和固件版本
R4se

**Comment by jjm2473** [comment]
MBR分区表最多只有4个分区。如果要更多分区，需要自己用命令创建扩展分区，目前网页上没有地方可以创建扩展分区。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2207/1
