### ISSUE TITLE
应用过滤特征库更新后无数据！

### ISSUE THREAD

**Issue by magi-Z** [istoreos/istoreos#1617]
### (2) 路由器型号和固件版本
R4se

### (3) 详细日志和/或截图
![屏幕截图 2024-05-31 104446](https://github.com/istoreos/istoreos/assets/63131352/e4b1a7ca-d7aa-40c0-86c9-ba0e9a6e3962)

**Comment by jjm2473** [comment]
要”基本设置“启用以后才有数据的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2206/1
