### ISSUE TITLE
uHTTPd证书上传提示没权限

### ISSUE THREAD

**Issue by kokpk** [istoreos/istoreos#1623]
uHTTPd里添加证书怎么上传一直提示Access to path denied by ACL 没权限呢。
路径是[(root)etc » ssl吧

**Comment by jjm2473** [comment]
重新安装uhttpd插件试试

**Comment by jjm2473** [comment]
确实没有权限，应该设计好的，只能通过其他方式上传，这个界面只是选择文件而已

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2203/1

**Comment by WalkingDead-Chen** [comment]
没有大能解决下这个问题吗

**Comment by jjm2473** [comment]
在软件包里安装 luci-app-filebrowser ，luci就有权限访问任意文件了。
