### ISSUE TITLE
/OPT 文件夹所在分区太小，导致分区满后，无法进入系统

### ISSUE THREAD

**Issue by xsnadboy** [istoreos/istoreos#1626]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
/OPT 文件夹所在分区太小，导致分区满后，无法进入系统

Q：是否用关键词搜索了issue? (使用 "x" 选择)
1：OPT
2：分区满

### (1) 具体问题

A：/OPT 文件夹所在分区太小，导致分区满后，无法进入系统

### (2) 路由器型号和固件版本

A：N100 16G+256G 四网口 X86
B:iStoreOS 22.03.6 2024052410 / LuCI istoreos-22.03 branch git-24.057.30647-6659faa

### (3) 详细日志和/或截图

A：由于已经无法进入系统，只能接电视进入，第一次进fail 模式后发现有跳一个空间已满的提示为：/user/share/……
而后折腾许久，还是无法进入，只能通过 fristboot命令做出厂设置。
所有软件和Docker都需要重新安装调试，非常麻烦。
能否做一个分区大一点的系统镜像（原来的只有2G，听说如果自己扩容的话又不能升级系统）
或是做一个系统分区清理工具，以免屡次重装。
感谢大佬，星星送上。

**Comment by jjm2473** [comment]
首页不是一开始就提醒你迁移docker吗？你可以在系统盘后面再分一个区，把docker迁到这个分区，就没问题了，也不影响升级。如果有外部硬盘就更好。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2202/1
