### ISSUE TITLE
虚拟内存

### ISSUE THREAD

**Issue by db-root** [istoreos/istoreos#1630]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x ] 没有类似的issue

## 2. 详细叙述
我是用的京东云亚瑟路由器刷了istoreos，内存只有0.5g，但是闪存挺多的，是否能设置swap来优化内存的使用呢
还有就是按照B站中 酷友社 的视频《百元路由器京东ax1800沉浸式刷机体验》刷完之后在路由器上查询的存储不太对，从首页上看是没有格式化，这个是否能格式化，以及如何设置swap
![image](https://github.com/istoreos/istoreos/assets/90075706/49a2af83-5614-403f-8e93-e510524aa679)

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：
NAME="OpenWrt"
VERSION="19.07-SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt 19.07-SNAPSHOT"
VERSION_ID="19.07-snapshot"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r673-88ca66eb5"
LEDE_BOARD="ipq60xx/generic"
LEDE_ARCH="aarch64_cortex-a53"
LEDE_TAINTS="no-all busybox"
LEDE_DEVICE_MANUFACTURER="OpenWrt"
LEDE_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
LEDE_DEVICE_PRODUCT="Generic"
LEDE_DEVICE_REVISION="v0"
LEDE_RELEASE="OpenWrt 19.07-SNAPSHOT r673-88ca66eb5"

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/90075706/66607059-78d2-40d8-8550-55f222e31a0c)

**Comment by jjm2473** [comment]
这款机型不是官方支持的，而是lean移植的，需要找lean咨询。
