### ISSUE TITLE
rtw_8821cu无线网卡模块运行异常，大佬帮忙看看

### ISSUE THREAD

**Issue by xiaomeng9597** [istoreos/istoreos#1632]
错误日志

Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]: ttyd 1.6.3 (libwebsockets 4.2.1-unknown)
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]: tty configuration:
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]:   start command: /bin/login
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]:   close signal: SIGHUP (1)
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]:   terminal type: xterm-256color
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]: LWS: 4.2.1-unknown, loglevel 7
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]: NET CLI SRV H1 H2 WS ConMon IPV6-off
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]:    /usr/lib/libwebsockets-evlib_uv.so
Tue Jun 11 17:36:27 2024 daemon.err ttyd[11686]: [2024/06/11 17:36:27:8746] N:  Using foreign event loop...
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]:  ++ [wsi|0|pipe] (1)
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]:  ++ [vh|0|netlink] (1)
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]:  ++ [vh|1|default||7681] (2)
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]: lws_socket_bind: nowsi: source ads 0.0.0.0
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]:  ++ [wsi|1|listen|default||7681] (2)
Tue Jun 11 17:36:27 2024 daemon.notice ttyd[11686]:  Listening on port: 7681
Tue Jun 11 17:36:28 2024 daemon.err nmbd[9415]: [2024/06/11 17:36:28.535099,  0] ../../source3/nmbd/nmbd.c:901(main)
Tue Jun 11 17:36:28 2024 daemon.err nmbd[9415]:   nmbd version 4.18.8 started.
Tue Jun 11 17:36:28 2024 daemon.err nmbd[9415]:   Copyright Andrew Tridgell and the Samba Team 1992-2023
Tue Jun 11 17:36:28 2024 daemon.info [7384]: <info>  [base-manager] couldn't check support for device '/sys/devices/platform/fe300000.ethernet': not supported by any plugin
Tue Jun 11 17:36:29 2024 daemon.info [7384]: <info>  [base-manager] couldn't check support for device '/sys/devices/platform/fe380000.usb/usb1/1-1/1-1.1': not supported by any plugin
Tue Jun 11 17:36:30 2024 daemon.err smbd[9414]: [2024/06/11 17:36:30.439950,  0] ../../source3/smbd/server.c:1746(main)
Tue Jun 11 17:36:30 2024 daemon.err smbd[9414]:   smbd version 4.18.8 started.
Tue Jun 11 17:36:30 2024 daemon.err smbd[9414]:   Copyright Andrew Tridgell and the Samba Team 1992-2023
Tue Jun 11 17:36:32 2024 daemon.info procd: - init complete -
Tue Jun 11 17:36:41 2024 daemon.err dockerd[10345]: time="2024-06-11T09:36:41.836465007Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: error while dialing: dial unix:///var/run/docker/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Tue Jun 11 17:36:42 2024 daemon.err dockerd[10345]: time="2024-06-11T09:36:42Z" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
Tue Jun 11 17:36:42 2024 daemon.err modprobe: failed to find a module named aufs
Tue Jun 11 17:36:42 2024 daemon.err dockerd[10345]: time="2024-06-11T09:36:42.563004824Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
Tue Jun 11 17:36:42 2024 daemon.err dockerd[10345]: time="2024-06-11T09:36:42.564410944Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
Tue Jun 11 17:36:42 2024 daemon.err dockerd[10345]: time="2024-06-11T09:36:42.572033587Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
Tue Jun 11 17:36:42 2024 kern.warn kernel: [   48.915391] overlayfs: upperdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
Tue Jun 11 17:36:42 2024 kern.warn kernel: [   48.915405] overlayfs: workdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
Tue Jun 11 17:36:42 2024 kern.warn kernel: [   48.915414] overlayfs: lowerdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
Tue Jun 11 17:36:42 2024 kern.warn kernel: [   48.915421] overlayfs: lowerdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
Tue Jun 11 17:36:42 2024 daemon.info modprobe: nf_conntrack is already loaded
Tue Jun 11 17:36:42 2024 daemon.info modprobe: nf_conntrack_netlink is already loaded
Tue Jun 11 17:36:42 2024 daemon.info avahi-daemon[7319]: Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
Tue Jun 11 17:36:42 2024 daemon.info avahi-daemon[7319]: New relevant interface docker0.IPv4 for mDNS.
Tue Jun 11 17:36:42 2024 daemon.info avahi-daemon[7319]: Registering new address record for 172.17.0.1 on docker0.IPv4.
Tue Jun 11 17:36:43 2024 daemon.debug ModemManager[12380]: hotplug: event reported: action=add, name=docker0, subsystem=net
Tue Jun 11 17:36:43 2024 daemon.err ModemManager[12380]: hotplug: parent device sysfspath not found
Tue Jun 11 17:36:43 2024 kern.warn kernel: [   49.612953] overlayfs: upperdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
Tue Jun 11 17:36:43 2024 kern.warn kernel: [   49.612965] overlayfs: workdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
Tue Jun 11 17:36:43 2024 kern.warn kernel: [   49.612972] overlayfs: lowerdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
Tue Jun 11 17:36:43 2024 kern.warn kernel: [   49.612977] overlayfs: lowerdir is in-use as upperdir/workdir of another mount, accessing files from both mounts will result in undefined behavior.
Tue Jun 11 17:36:46 2024 daemon.err uwsgi[7424]: *** has_emperor mode detected (fd: 7) ***
Tue Jun 11 17:36:46 2024 daemon.err uwsgi[7424]: [uWSGI] getting INI configuration from /etc/uwsgi/vassals/luci-webui.ini
Tue Jun 11 17:36:46 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:36:46 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-webui.ini has been spawned
Tue Jun 11 17:36:46 2024 daemon.info uwsgi-luci: spawned uWSGI master process (pid: 12450)
Tue Jun 11 17:36:46 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:36:46 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-webui.ini is ready to accept requests
Tue Jun 11 17:36:46 2024 daemon.err nginx[7490]: 2024/06/11 17:36:46 [error] 7517#0: *3 open() "/www/favicon.ico" failed (2: No such file or directory), client: 192.168.23.238, server: _lan80, request: "GET /favicon.ico HTTP/1.1", host: "192.168.23.112", referrer: "http://192.168.23.112/"
Tue Jun 11 17:36:47 2024 daemon.err nginx[7490]: 2024/06/11 17:36:47 [error] 7517#0: *3 open() "/www/favicon.ico" failed (2: No such file or directory), client: 192.168.23.238, server: _lan80, request: "GET /favicon.ico HTTP/1.1", host: "192.168.23.112", referrer: "http://192.168.23.112/"
Tue Jun 11 17:36:47 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:36:47 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-webui.ini is now loyal
Tue Jun 11 17:36:54 2024 user.info : luci: accepted login on / for root from 192.168.23.238
Tue Jun 11 17:36:58 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:36:58 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-webui.ini is now loyal
Tue Jun 11 17:37:12 2024 daemon.info uwsgi-luci: Tue Jun 11 17:37:12 2024 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /cgi-bin/luci/istore/u/guide/ddns/ (ip 192.168.23.238) !!!
Tue Jun 11 17:37:12 2024 daemon.info uwsgi-luci: Tue Jun 11 17:37:12 2024 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /cgi-bin/luci/istore/u/guide/ddns/ (192.168.23.238)
Tue Jun 11 17:37:16 2024 daemon.info uwsgi-luci: uWSGI worker 1 cheaped.
Tue Jun 11 17:37:56 2024 daemon.info hostapd: wlan0: STA 46:7c:6b:cc:de:b0 IEEE 802.11: authenticated
Tue Jun 11 17:37:56 2024 daemon.notice hostapd: wlan0: STA-OPMODE-N_SS-CHANGED 46:7c:6b:cc:de:b0 1
Tue Jun 11 17:37:56 2024 daemon.info hostapd: wlan0: STA 46:7c:6b:cc:de:b0 IEEE 802.11: associated (aid 1)
Tue Jun 11 17:37:56 2024 daemon.notice hostapd: wlan0: AP-STA-CONNECTED 46:7c:6b:cc:de:b0
Tue Jun 11 17:37:56 2024 daemon.info hostapd: wlan0: STA 46:7c:6b:cc:de:b0 RADIUS: starting accounting session CABA5477AFB5C39D
Tue Jun 11 17:39:17 2024 kern.err kernel: [  203.837555] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:17 2024 kern.err kernel: [  203.838759] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:39:18 2024 kern.err kernel: [  204.428682] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:18 2024 kern.err kernel: [  204.429527] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:39:18 2024 kern.err kernel: [  204.631884] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:18 2024 kern.err kernel: [  204.633823] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:39:21 2024 kern.err kernel: [  207.282307] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:21 2024 kern.err kernel: [  207.283279] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:39:21 2024 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 46:7c:6b:cc:de:b0
Tue Jun 11 17:39:22 2024 kern.warn kernel: [  208.278573] rtw_8821cu 1-1.1:1.2: timed out to flush queue 3
Tue Jun 11 17:39:22 2024 kern.err kernel: [  208.515763] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:22 2024 kern.err kernel: [  208.516986] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:39:24 2024 kern.err kernel: [  210.676516] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:24 2024 kern.err kernel: [  210.677732] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:39:30 2024 kern.err kernel: [  216.921635] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:30 2024 kern.err kernel: [  216.922655] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:39:37 2024 kern.err kernel: [  223.054806] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:37 2024 kern.err kernel: [  223.055780] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:39:43 2024 kern.err kernel: [  229.296308] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:43 2024 kern.err kernel: [  229.297285] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:39:49 2024 kern.err kernel: [  235.574011] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:49 2024 kern.err kernel: [  235.575156] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:39:54 2024 daemon.err uwsgi[7424]: *** has_emperor mode detected (fd: 8) ***
Tue Jun 11 17:39:54 2024 daemon.err uwsgi[7424]: [uWSGI] getting INI configuration from /etc/uwsgi/vassals/luci-cgi_io.ini
Tue Jun 11 17:39:54 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:39:54 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini has been spawned
Tue Jun 11 17:39:54 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:39:54 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini is ready to accept requests
Tue Jun 11 17:39:54 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:39:54 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini is now loyal
Tue Jun 11 17:39:55 2024 kern.err kernel: [  241.807934] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:39:55 2024 kern.err kernel: [  241.809483] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:40:02 2024 kern.err kernel: [  248.061383] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:40:02 2024 kern.err kernel: [  248.062410] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:40:08 2024 kern.err kernel: [  254.197181] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:40:08 2024 kern.err kernel: [  254.198026] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:40:14 2024 kern.err kernel: [  260.457386] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:40:14 2024 kern.err kernel: [  260.458612] rtw_8821cu 1-1.1:1.2: failed to download drv rsvd page
Tue Jun 11 17:40:14 2024 authpriv.info dropbear[14920]: Child connection from 192.168.23.238:45192
Tue Jun 11 17:40:14 2024 authpriv.notice dropbear[14920]: Password auth succeeded for 'root' from 192.168.23.238:45192
Tue Jun 11 17:40:19 2024 daemon.notice hostapd: Remove interface 'wlan0'
Tue Jun 11 17:40:19 2024 daemon.notice hostapd: wlan0: interface state ENABLED->DISABLED
Tue Jun 11 17:40:19 2024 daemon.notice hostapd: wlan0: AP-DISABLED
Tue Jun 11 17:40:19 2024 daemon.notice hostapd: wlan0: CTRL-EVENT-TERMINATING
Tue Jun 11 17:40:19 2024 daemon.err hostapd: rmdir[ctrl_interface=/var/run/hostapd]: Permission denied
Tue Jun 11 17:40:19 2024 daemon.notice hostapd: nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Tue Jun 11 17:40:19 2024 kern.info kernel: [  265.515008] device wlan0 left promiscuous mode
Tue Jun 11 17:40:19 2024 kern.info kernel: [  265.515196] br-lan: port 2(wlan0) entered disabled state
Tue Jun 11 17:40:19 2024 daemon.notice netifd: Network device 'wlan0' link is down
Tue Jun 11 17:40:19 2024 kern.warn kernel: [  265.818709] rtw_8821cu 1-1.1:1.2: timed out to flush queue 3
Tue Jun 11 17:40:19 2024 daemon.info avahi-daemon[7319]: Interface wlan0.IPv6 no longer relevant for mDNS.
Tue Jun 11 17:40:19 2024 daemon.info avahi-daemon[7319]: Leaving mDNS multicast group on interface wlan0.IPv6 with address fe80::7e25:daff:fe8e:4e97.
Tue Jun 11 17:40:19 2024 daemon.notice ttyd[11686]: rops_handle_POLLIN_netlink: DELADDR
Tue Jun 11 17:40:19 2024 daemon.info avahi-daemon[7319]: Withdrawing address record for fe80::7e25:daff:fe8e:4e97 on wlan0.
Tue Jun 11 17:40:19 2024 daemon.notice netifd: lan (5084): udhcpc: sending renew to server 192.168.23.1
Tue Jun 11 17:40:19 2024 daemon.notice netifd: lan (5084): udhcpc: lease of 192.168.23.112 obtained from 192.168.23.1, lease time 43200
Tue Jun 11 17:40:19 2024 daemon.debug ModemManager[14950]: hotplug: event reported: action=remove, name=wlan0, subsystem=net
Tue Jun 11 17:40:20 2024 daemon.notice netifd: Wireless device 'radio0' is now down
Tue Jun 11 17:40:20 2024 daemon.notice hostapd: Configuration file: /var/run/hostapd-phy0.conf (phy wlan0) --> new PHY
Tue Jun 11 17:40:20 2024 daemon.debug ModemManager[15050]: hotplug: event reported: action=add, name=wlan0, subsystem=net
Tue Jun 11 17:40:20 2024 kern.err kernel: [  266.623308] rtw_8821cu 1-1.1:1.2: error beacon valid
Tue Jun 11 17:40:20 2024 kern.err kernel: [  266.624281] rtw_8821cu 1-1.1:1.2: failed to download rsvd page
Tue Jun 11 17:40:20 2024 kern.err kernel: [  266.625404] rtw_8821cu 1-1.1:1.2: failed to download firmware
Tue Jun 11 17:40:20 2024 daemon.err hostapd: Could not set interface wlan0 flags (UP): Resource busy
Tue Jun 11 17:40:20 2024 daemon.err hostapd: nl80211: Could not set interface 'wlan0' UP
Tue Jun 11 17:40:20 2024 daemon.notice hostapd: nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Tue Jun 11 17:40:20 2024 daemon.err hostapd: nl80211 driver initialization failed.
Tue Jun 11 17:40:20 2024 daemon.notice hostapd: wlan0: CTRL-EVENT-TERMINATING
Tue Jun 11 17:40:20 2024 daemon.err hostapd: hostapd_free_hapd_data: Interface wlan0 wasn't started
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994): Command failed: ubus call hostapd config_add {"iface":"wlan0", "config":"/var/run/hostapd-phy0.conf"} (Invalid argument)
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994): Usage: ubus [<options>] <command> [arguments...]
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994): Options:
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  -s <socket>:		Set the unix domain socket to connect to
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  -t <timeout>:		Set the timeout (in seconds) for a command to complete
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  -S:			Use simplified output (for scripts)
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  -v:			More verbose output
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  -m <type>:		(for monitor): include a specific message type
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994): 			(can be used more than once)
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  -M <r|t>		(for monitor): only capture received or transmitted traffic
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994): Commands:
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  - list [<path>]			List objects
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  - call <path> <method> [<message>]	Call an object method
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  - subscribe <path> [<path>...]	Subscribe to object(s) notifications
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  - listen [<path>...]			Listen for events
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  - send <type> [<message>]		Send an event
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  - wait_for <object> [<object>...]	Wait for multiple objects to appear on ubus
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):  - monitor				Monitor ubus traffic
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994):
Tue Jun 11 17:40:20 2024 daemon.notice netifd: radio0 (14994): Device setup failed: HOSTAPD_START_FAILED
Tue Jun 11 17:40:20 2024 daemon.notice netifd: Wireless device 'radio0' set retry=0
Tue Jun 11 17:40:20 2024 daemon.crit netifd: Wireless device 'radio0' setup failed, retry=0
Tue Jun 11 17:40:20 2024 daemon.notice netifd: Wireless device 'radio0' is now down
Tue Jun 11 17:40:23 2024 daemon.info [7384]: <info>  [base-manager] couldn't check support for device '/sys/devices/platform/fe380000.usb/usb1/1-1/1-1.1': not supported by any plugin
Tue Jun 11 17:46:55 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:46:55 2024 - [emperor] bringing back instance /etc/uwsgi/vassals/luci-webui.ini to on-demand mode
Tue Jun 11 17:46:55 2024 daemon.info uwsgi-luci: Tue Jun 11 17:46:55 2024 - received message 0 from emperor
Tue Jun 11 17:46:55 2024 daemon.info uwsgi-luci: SIGINT/SIGTERM received...killing workers...
Tue Jun 11 17:46:55 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:46:55 2024 - [emperor] curse the uwsgi instance /etc/uwsgi/vassals/luci-webui.ini (pid: 12450)
Tue Jun 11 17:46:57 2024 daemon.err uwsgi[7424]: [uwsgi-emperor] /etc/uwsgi/vassals/luci-webui.ini -> back to "on demand" mode, waiting for connections on socket "/var/run//luci-webui.socket" ...
Tue Jun 11 17:47:40 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:47:40 2024 - [emperor] bringing back instance /etc/uwsgi/vassals/luci-cgi_io.ini to on-demand mode
Tue Jun 11 17:47:40 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:47:40 2024 - [emperor] curse the uwsgi instance /etc/uwsgi/vassals/luci-cgi_io.ini (pid: 14767)
Tue Jun 11 17:47:42 2024 daemon.err uwsgi[7424]: [uwsgi-emperor] /etc/uwsgi/vassals/luci-cgi_io.ini -> back to "on demand" mode, waiting for connections on socket "/var/run//luci-cgi_io.socket" ...
Tue Jun 11 17:55:48 2024 daemon.err uwsgi[7424]: *** has_emperor mode detected (fd: 7) ***
Tue Jun 11 17:55:48 2024 daemon.err uwsgi[7424]: [uWSGI] getting INI configuration from /etc/uwsgi/vassals/luci-webui.ini
Tue Jun 11 17:55:48 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:55:48 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-webui.ini has been spawned
Tue Jun 11 17:55:48 2024 daemon.info uwsgi-luci: spawned uWSGI master process (pid: 15728)
Tue Jun 11 17:55:48 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:55:48 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-webui.ini is ready to accept requests
Tue Jun 11 17:55:49 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:55:49 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-webui.ini is now loyal
Tue Jun 11 17:55:54 2024 daemon.err uwsgi[7424]: *** has_emperor mode detected (fd: 8) ***
Tue Jun 11 17:55:54 2024 daemon.err uwsgi[7424]: [uWSGI] getting INI configuration from /etc/uwsgi/vassals/luci-cgi_io.ini
Tue Jun 11 17:55:54 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:55:54 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini has been spawned
Tue Jun 11 17:55:54 2024 daemon.err uwsgi[7424]: Tue Jun 11 17:55:54 2024 - [emperor] vassal /etc/uwsgi/vassals/luci-cgi_io.ini is ready to accept requests

**Comment by xiaomeng9597** [comment]
系统刚重启后wlan0正常，有WiFi信号出来，用设备链接WiFi一会后就掉线了，然后报上面的错误，不知道咋解决了

**Comment by peanutlya** [comment]
同样的问题，后面解决了吗

**Comment by peanutlya** [comment]
> 系统刚重启后wlan0正常，有WiFi信号出来，用设备链接WiFi一会后就掉线了，然后报上面的错误，不知道咋解决了

同样的问题，后面解决了吗

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2197/1
