### ISSUE TITLE
求助，设置旁路由后并指向旁路由网关和DNS，无法上网

### ISSUE THREAD

**Issue by wwushi** [istoreos/istoreos#1636]
单网口物理机安装istoreos并设置成旁路由模式，网关和DNS均指向主路由并关闭旁路由DHCP，设备手动设置网关和DNS为旁路由ip时无法连通网络。

主路由网段：
![20240613-121218](https://github.com/istoreos/istoreos/assets/24545350/7b20f37e-311b-4009-ad01-e26673c2533a)
![20240613-121224](https://github.com/istoreos/istoreos/assets/24545350/28d41710-fa50-4568-be40-4ac72a8de0ce)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2193/1
