### ISSUE TITLE
修改Openclash配置管理中的配置文件导致WEB挂死无法访问

### ISSUE THREAD

**Issue by JayL946** [istoreos/istoreos#1637]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题
修改Openclash配置管理中的配置文件，增加规则后，点击保存配置，会导致web界面挂死转圈无法访问，必须重启软路由才能访问web管理
A

### (2) 路由器型号和固件版本
R68S内核版本5.10.201
iStoreOS 22.03.6 2024052410
Openclash客户端版本v0.46.014-beta
Openclash Meta内核alpha-g0d4e57c
Openclash Tun内核2023.08.17-13-gdcc8d87

A：

### (3) 详细日志和/或截图
Fri Aug  4 17:00:38 2017 kern.err kernel: [   36.460566] overlayfs: upperdir is in-use as upperdir/workdir of another mount, mount with '-o index=off' to override exclusive upperdir protection.
Fri Aug  4 17:00:38 2017 daemon.info modprobe: nf_conntrack is already loaded
Fri Aug  4 17:00:38 2017 daemon.info modprobe: nf_conntrack_netlink is already loaded
Fri Aug  4 17:00:38 2017 daemon.info avahi-daemon[6721]: Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
Fri Aug  4 17:00:38 2017 daemon.info avahi-daemon[6721]: New relevant interface docker0.IPv4 for mDNS.
Fri Aug  4 17:00:38 2017 daemon.info avahi-daemon[6721]: Registering new address record for 172.17.0.1 on docker0.IPv4.
Fri Aug  4 17:00:38 2017 daemon.debug ModemManager[14174]: hotplug: event reported: action=add, name=docker0, subsystem=net
Fri Aug  4 17:00:38 2017 daemon.err ModemManager[14174]: hotplug: parent device sysfspath not found
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: started, version 2.89 cachesize 150
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: DNS service limited to local subnets
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset no-nftset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: UBus support enabled: connected to system bus
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.5.100 -- 192.168.5.249, lease time 12h
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for test
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for local
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for bss.pandora.xiaomi.com
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for o2o.api.xiaomi.com
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using 13 more local addresses
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: reading /tmp/resolv.conf.d/resolv.conf.auto
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using nameserver 223.5.5.5#53
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using nameserver 223.5.5.5#53
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for test
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for local
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for bss.pandora.xiaomi.com
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for o2o.api.xiaomi.com
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using 13 more local addresses
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: read /etc/hosts - 12 names
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 4 names
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
Fri Aug  4 17:00:39 2017 daemon.warn dnsmasq[1]: no servers found in /tmp/resolv.conf.d/resolv.conf.auto, will retry
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: reading /tmp/resolv.conf.d/resolv.conf.auto
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using nameserver 119.29.29.29#53
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using nameserver 8.8.8.8#53
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for test
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for local
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for bss.pandora.xiaomi.com
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using only locally-known addresses for o2o.api.xiaomi.com
Fri Aug  4 17:00:39 2017 daemon.info dnsmasq[1]: using 13 more local addresses
Fri Aug  4 17:00:40 2017 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: started, version 2.89 cachesize 150
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: DNS service limited to local subnets
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset no-nftset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: UBus support enabled: connected to system bus
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.5.100 -- 192.168.5.249, lease time 12h
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for test
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for local
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for bss.pandora.xiaomi.com
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for o2o.api.xiaomi.com
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using 13 more local addresses
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: reading /tmp/resolv.conf.d/resolv.conf.auto
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using nameserver 119.29.29.29#53
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using nameserver 8.8.8.8#53
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for test
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for local
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for bss.pandora.xiaomi.com
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using only locally-known addresses for o2o.api.xiaomi.com
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: using 13 more local addresses
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: read /etc/hosts - 12 names
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 4 names
Fri Aug  4 17:00:42 2017 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
Fri Aug  4 17:00:42 2017 cron.err crond[14555]: crond (busybox 1.35.0) started, log level 5
Fri Aug  4 17:00:42 2017 daemon.notice procd: /etc/rc.d/S99openclash: OpenClash Already Stop!
Thu Jun 13 12:30:22 2024 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) b0:59:47:42:a0:f6
Thu Jun 13 12:30:22 2024 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 192.168.5.226 b0:59:47:42:a0:f6
Thu Jun 13 12:30:22 2024 daemon.info dnsmasq-dhcp[1]: DHCPDISCOVER(br-lan) b0:59:47:42:a0:f6
Thu Jun 13 12:30:22 2024 daemon.info dnsmasq-dhcp[1]: DHCPOFFER(br-lan) 192.168.5.226 b0:59:47:42:a0:f6
Thu Jun 13 12:30:22 2024 daemon.info dnsmasq-dhcp[1]: DHCPREQUEST(br-lan) 192.168.5.226 b0:59:47:42:a0:f6
Thu Jun 13 12:30:22 2024 daemon.info dnsmasq-dhcp[1]: DHCPACK(br-lan) 192.168.5.226 b0:59:47:42:a0:f6 360_CAMERA_D708
Thu Jun 13 12:30:22 2024 daemon.err nmbd[13080]: [2024/06/13 12:30:22.840965,  0] ../../source3/nmbd/nmbd_become_lmb.c:398(become_local_master_stage2)
Thu Jun 13 12:30:22 2024 daemon.err nmbd[13080]:   *****
Thu Jun 13 12:30:22 2024 daemon.err nmbd[13080]:
Thu Jun 13 12:30:22 2024 daemon.err nmbd[13080]:   Samba name server ISTOREOS is now a local master browser for workgroup WORKGROUP on subnet 192.168.5.1
Thu Jun 13 12:30:22 2024 daemon.err nmbd[13080]:
Thu Jun 13 12:30:22 2024 daemon.err nmbd[13080]:   *****
Thu Jun 13 12:30:29 2024 cron.err crond[14555]: time disparity of 3606929 minutes detected
Thu Jun 13 12:30:37 2024 daemon.info dnsmasq[1]: exiting on receipt of SIGTERM
Thu Jun 13 12:30:40 2024 daemon.notice procd: /etc/rc.d/S99openclash: OpenClash Already Start!
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: started, version 2.89 cachesize 150
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: DNS service limited to local subnets
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset no-nftset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: UBus support enabled: connected to system bus
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq-dhcp[1]: DHCP, IP range 192.168.5.100 -- 192.168.5.249, lease time 12h
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#7874
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 0-6.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 0.zone
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 00.net
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 000.link
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 00042.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 00058.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 0006266.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 000714.xyz
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 000dn.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 000e.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 000pc.net
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 000vw.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 00117163.xyz
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001daima.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001jm.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001job.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001jp.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001kd.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001pp.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001tech.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001town.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001tudou.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 001u.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 00257.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 002lzj.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 0033.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 0037wan.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using nameserver 114.114.114.114#53 for domain 00394.net
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: more servers are defined but not logged
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using only locally-known addresses for test
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using only locally-known addresses for local
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using only locally-known addresses for bss.pandora.xiaomi.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using only locally-known addresses for o2o.api.xiaomi.com
Thu Jun 13 12:30:40 2024 daemon.info dnsmasq[1]: using 13 more local addresses
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]: ttyd 1.6.3 (libwebsockets 4.2.1-09e6c20)
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]: tty configuration:
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]:   start command: /bin/login
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]:   close signal: SIGHUP (1)
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]:   terminal type: xterm-256color
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]: LWS: 4.2.1-09e6c20, loglevel 7
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]: NET CLI SRV H1 H2 WS ConMon IPV6-off
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]:    /usr/lib/libwebsockets-evlib_uv.so
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]:  ++ [wsi|0|pipe] (1)
Thu Jun 13 12:30:40 2024 daemon.err ttyd[15548]: [2024/06/13 12:30:40:9988] N:  Using foreign event loop...
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]:  ++ [vh|0|netlink] (1)
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]:  ++ [vh|1|default||7681] (2)
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]: lws_socket_bind: nowsi: source ads 0.0.0.0
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]:  ++ [wsi|1|listen|default||7681] (2)
Thu Jun 13 12:30:40 2024 daemon.notice ttyd[15548]:  Listening on port: 7681
Thu Jun 13 12:30:41 2024 daemon.info dnsmasq[1]: read /etc/hosts - 12 names
Thu Jun 13 12:30:41 2024 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 4 names
Thu Jun 13 12:30:41 2024 daemon.info dnsmasq-dhcp[1]: read /etc/ethers - 0 addresses
Thu Jun 13 12:30:47 2024 user.notice cifs: server/name or mountpoint is empty
Thu Jun 13 12:30:48 2024 daemon.info procd: - init complete -
Thu Jun 13 12:31:15 2024 user.info : luci: accepted login on /admin/services/openclash/config for root from 192.168.5.191
A：

**Comment by jjm2473** [comment]
反馈给openclash，这垃圾插件出问题也不是一次两次了。
