### ISSUE TITLE
旁路由设置科学上网，设备一多就无法连接外网

### ISSUE THREAD

**Issue by wwushi** [istoreos/istoreos#1638]
单网口物理机安装istoreos设置旁路由并安装科学上网插件，连接设备一多部分设备就无法连接外网，旁路由和主路由负载都没超过一半，这是节点服务器问题还是旁路由问题？

**Comment by jjm2473** [comment]
试试防火墙那边把FullconeNAT改成高性能模式。

还有旁路由的话，需要注意下是不是无线路由器的问题，如果通过wifi可以访问翻墙网站，反而不能访问国内网站，那大概率就是这个问题了。 https://github.com/istoreos/istoreos/issues/598

**Comment by wwushi** [comment]
防火墙已开启高性能模式，插件用的是openclash，十几台设备还好，一百多台设备同时访问就会出现部分无法访问外网，但是旁路由负载都不到一半，是不是UDP连接数过多？

**Comment by QiaQia8** [comment]
openclash改用Meta内核试一下
