### ISSUE TITLE
每次重启后无法自动获取ipv6地址，需要到接口手动重启wan口

### ISSUE THREAD

**Issue by s-theo** [istoreos/istoreos#1643]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：每次重启后无法自动获取ipv6地址，需要到接口手动重启wan口

### (2) 路由器型号和固件版本

A：iStoreOS 22.03.6, 2024052410

### (3) 详细日志和/或截图

这是路由器重启后的

<img width="823" alt="image" src="https://github.com/istoreos/istoreos/assets/89436345/e72e0d2b-2158-42c3-b766-721c445a079f">

手动重启wan口后就显示正常

<img width="785" alt="image" src="https://github.com/istoreos/istoreos/assets/89436345/b0db978d-b5d2-4384-b2ea-9121de391aef">

**Comment by jjm2473** [comment]
可能运营商限制了重拨ipv6的间隔

**Comment by s-theo** [comment]
> 可能运营商限制了重拨ipv6的间隔

应该是我之前的设置有问题，我重置了系统又重新设置了下，现在恢复正常了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2190/1
