### ISSUE TITLE
京东云亚瑟 AX1800刷iStoreOS后能联网但没有网速

### ISSUE THREAD

**Issue by BUBU315** [istoreos/istoreos#1648]
京东云亚瑟 AX1800刷iStoreOS后能联网但没有网速
亚瑟 AX1800用wan口连接交换机
iStoreOS采用  “连接线有路由器”方式  采用“自动获取DHCP”模式

iStoreOS   防火墙WAN口限制全部改为“接受”
目前的情况是通过亚瑟 AX1800的lan口链接电脑，能连接互联网但是没有网速，网站打不开。

**Comment by jjm2473** [comment]
这个固件是lean移植的，在这反馈没用。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2187/1
