### ISSUE TITLE
插件商城里的transmission怎么创建账号，密码？

### ISSUE THREAD

**Issue by Skinsly** [istoreos/istoreos#1650]
插件商城里的transmission怎么创建账号，密码？

**Comment by jjm2473** [comment]
服务菜单里面

**Comment by Skinsly** [comment]
> 服务菜单里面

没找到，大佬可以截个图吗，麻烦了

**Comment by jjm2473** [comment]
服务-Transmission-RPC授权验证

**Comment by jjm2473** [comment]
哦，我发现transmission插件可能有bug，如果要修改rpc验证，要先在最上边禁用，保存应用，然后修改rpc设置并且启用。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2185/1
