### ISSUE TITLE
启动过程中overlayfs警告

### ISSUE THREAD

**Issue by keififteen01** [istoreos/istoreos#1652]
![istoreosissues1](https://github.com/istoreos/istoreos/assets/173222824/407964fb-f0a8-45f0-b1f3-38136852af12)
![istoreosissues2](https://github.com/istoreos/istoreos/assets/173222824/46e35988-6e6b-4774-92a8-7d9522fd53a4)
我可以怎做呢

**Comment by jjm2473** [comment]
忽略这个警告，或者把docker迁移到硬盘上。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2183/1
