### ISSUE TITLE
我的UI界面关于管理挂载别的设备的webdev界面丢失

### ISSUE THREAD

**Issue by aikeqin** [istoreos/istoreos#1653]
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：管理设备挂载NAS的webdev界面不在了，求助，怎么找回来。是整个界面不在UI里面了

### (2) 路由器型号和固件版本

A：x86_x64

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/172475963/23798499-8cfe-4e91-8287-b5906e4c5248)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2182/1
