### ISSUE TITLE
通过易有云文件管理无法上传文件

### ISSUE THREAD

**Issue by liuwleo** [istoreos/istoreos#1654]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue
有类似issue，但是显示已更新。
## 2. 详细叙述
通过易有云文件管理器在tmp文件下新建文件夹，并上传ipk文件。系统报错，无法上传。
### (1) 具体问题
通过易有云文件管理无法上传文件
A：

### (2) 路由器型号和固件版本

A：Intel(R) Celeron(R) J4125 CPU @ 2.00GHz

iStoreOS 22.03.6 2024061415 / LuCI openwrt-22.03 branch git-23.119.80898-65ef406

### (3) 详细日志和/或截图

A：
<img width="450" alt="image" src="https://github.com/istoreos/istoreos/assets/49121177/99c89b2f-e3ff-4e2a-87a0-aff5803a9de4">

**Comment by jjm2473** [comment]
重复 https://github.com/istoreos/istoreos/issues/1446

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2181/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2347/3
