### ISSUE TITLE
请问 iStoreOS 支持带有 emmc 存储的 x86 设备吗?

### ISSUE THREAD

**Issue by Gaped511** [istoreos/istoreos#1658]
在网上看到戴尔的 wyse 3040, 价格低, 体积小, 配置也还行, 用的阿童木处理器, 功耗也小, 颜值在线, 感觉是下载机和旁路由, NAS 的不错选择. 但是这个机型是 emmc 存储, 好像是不支持普通的硬盘的, 看到网上有刷 openwrt 的, 需要打开 emmc 支持才能刷. 请问 iStoreOS 可以支持这个机型吗?
谢谢!

**Comment by jjm2473** [comment]
emmc是支持的，只要你的bios支持从emmc引导

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2179/1
