### ISSUE TITLE
增加ComFast-952AX的pid vid至MT7921U驱动

### ISSUE THREAD

**Issue by NatsuZoraKanata** [istoreos/istoreos#1662]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：USB 无线网卡CF-952AX V1，芯片MT7921AU，iStoreOS内置的kmod-mt7921u内核驱动模块缺少对此WiFi网卡的pid vid识别
每次重启后需要手动echo 3574 6211 > /sys/bus/usb/drivers/mt7921u/new_id
linux主线驱动已对此网卡适配

### (2) 路由器型号和固件版本

A：树莓派4B V1.2 USB WiFi模块 CF-952AX V1，固件版本 iStoreOS 22.03.6 2024061415

### (3) 详细日志和/或截图

A：
#usb信息
lsusb
Bus 002 Device 002: ID 3574:6211 MediaTek Inc. Wireless_Device
#linux主线驱动支持
![image](https://github.com/istoreos/istoreos/assets/88589371/750cea26-9770-40ec-9059-ca83cb39d48a)
https://github.com/torvalds/linux/blob/master/drivers/net/wireless/mediatek/mt76/mt7921/usb.c

**Comment by jjm2473** [comment]
id加上了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2176/1
