### ISSUE TITLE
Fixed WebVirtCloud won't autostart instance with script (Fixed)

### ISSUE THREAD

**Issue by soulripper13** [istoreos/istoreos#1663]
In /etc/init.d/ Create a file start_vm.sh

```bash
#!/bin/sh /etc/rc.common

START=99
STOP=1

start() {
    
    docker exec <container name> virsh start <Instance name>
}

stop() {
    
    docker exec <container name> virsh shutdown <Instance name>
}
```

`chmod +x /etc/init.d/start_vm.sh`

`/etc/init.d/start_vm.sh enable`

Reboot and verify

**Comment by waynewie** [comment]
我已经按照这个操作了，可是显示错误。。
![Xnip2024-10-02_02-03-25](https://github.com/user-attachments/assets/15a3ab9f-d4e0-454a-9750-8d0b3cc70fe1)
![Xnip2024-10-02_02-02-47](https://github.com/user-attachments/assets/16dc1968-13ad-499b-a2a3-7918f3c4b4e2)
![Uploading Xnip2024-10-02_02-03-57.jpg…]()

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2175/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2250/12

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2250/13

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2363/5
