### ISSUE TITLE
istoreos 还是不支持I226吗？

### ISSUE THREAD

**Issue by xinzhongyouhai** [istoreos/istoreos#1665]
反馈bug/问题模板，提建议请删除
 iStoreOS 22.03.6, 2024061415
 -------------------------------------------------------
root@iStoreOS:~# lspci|grep -i 'eth'
01:00.0 Ethernet controller: Intel Corporation Device 125c (rev 04)
02:00.0 Ethernet controller: Intel Corporation Device 125c (rev 04)
03:00.0 Ethernet controller: Intel Corporation Device 125c (rev 04)
04:00.0 Ethernet controller: Intel Corporation Device 125c (rev 04)
root@iStoreOS:~# 

网络连接老是会从1000M变成100M~

**Comment by dunkeng** [comment]
我的机器就是I226，你要不考虑一下先换个网线试试？

**Comment by xinzhongyouhai** [comment]
> 我的机器就是I226，你要不考虑一下先换个网线试试？

网线没问题~实际上插拔下网线有概率恢复到1000M连接~网线问题只是错觉罢了~

**Comment by jjm2473** [comment]
换好点的网线，例如6类扁网线

**Comment by jjm2473** [comment]
变成百兆的时候执行`ethtool eth0`看看输出什么

**Comment by xinzhongyouhai** [comment]
> 变成百兆的时候执行`ethtool eth0`看看输出什么

 好的~等我再遇到变百兆的时候试验一下再来回帖

**Comment by xinzhongyouhai** [comment]
```
root@iStoreOS:~# ethtool eth0
Settings for eth0:
        Supported ports: [ TP ]
        Supported link modes:   10baseT/Half 10baseT/Full 
                                100baseT/Half 100baseT/Full 
                                1000baseT/Full 
                                2500baseT/Full 
        Supported pause frame use: Symmetric
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  10baseT/Half 10baseT/Full 
                                100baseT/Half 100baseT/Full 
                                1000baseT/Full 
                                2500baseT/Full 
        Advertised pause frame use: Symmetric
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Speed: 100Mb/s
        Duplex: Full
        Port: Twisted Pair
        PHYAD: 0
        Transceiver: internal
        Auto-negotiation: on
        MDI-X: off (auto)
        Supports Wake-on: pumbg
        Wake-on: g
        Current message level: 0x00000007 (7)
                               drv probe link
        Link detected: yes
root@iStoreOS:~# 
```

**Comment by xinzhongyouhai** [comment]
![Uploading 微信截图_20240702195401.png…]()

**Comment by xinzhongyouhai** [comment]
ethtool -s eth0 speed 1000 duplex full autoneg on 这个命令是可以解决问题的~不知道是不是每次重启软路由都要执行一次

**Comment by xinzhongyouhai** [comment]
![Uploading 微信截图_20240702195401.jpg…]()

**Comment by xinzhongyouhai** [comment]
![Uploading 222.jpg…]()

**Comment by jjm2473** [comment]
如果强制设置到1000M，那你要测试下稳定性，会不会丢包啥的。

你可以写到开机命令里面。

**Comment by jjm2473** [comment]
重复 #1640

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2173/1
