### ISSUE TITLE
dnsmasq设置上游DNS服务器 无法转发所有请求到上游DNS服务器

### ISSUE THREAD

**Issue by Houiin** [istoreos/istoreos#1667]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A： Dnsmasq中，设置将DNS请求转发到`127.0.0.1:5553` 的adguard，adg中重写DNS设置了一个不存在的域名`nt.qc.loca`l，`A记录`指向`192.168.5.120`. 

正常情况下客户端发出DNS请求到达istoreOS后，请求被转发到adg。但是adg中无法看到相应的查询记录，客户端也无法返回域名解析.

`PC  ---> iStoreOS dnsmasq :53  ---x这里有问题x--->  adgurad home :5553 ---> Public DNS`

### (2) 路由器型号和固件版本

A： x86_64 iStoreOS 22.03.6 2024061415

### (3) 详细日志和/或截图

**dnsmasq端口设置为 `:53`**
![dnsmasq端口设置](https://github.com/istoreos/istoreos/assets/30932544/3817e22b-048f-4bf5-a206-cbbb43597124)

**dnsmasq上游设置为本机的adguard home `:5553`**
![dnsmasq转发dns请求到本机5553](https://github.com/istoreos/istoreos/assets/30932544/01ab78ba-bec9-4895-9e80-b0432a706ec8)

**向iStoreOS `:53`端口的dnsmasq发起请求, 查询不到**
```
<<>> DiG 9.18.12-1-Debian <<>> @192.168.5.2 -p 53 nt.qc.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 56230
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;nt.qc.local.                   IN      A

;; Query time: 0 msec
;; SERVER: 192.168.5.2#53(192.168.5.2) (UDP)
;; WHEN: Sun Jun 23 15:01:16 UTC 2024
;; MSG SIZE  rcvd: 40
```
可以在adg查询记录里面看到，
有很多Dns请求都被成功转发到了Adguard Home，
但是并不是所有请求都被成功转发，例如自定义域名`nt.qc.local` 没有查询记录，客户端也无法得到结果
![图片](https://github.com/istoreos/istoreos/assets/30932544/acc372c9-d42c-4120-b3d5-4e1dabd730f3)

**如果直接向adg发起请求，是可以得到返回结果的**
```
; <<>> DiG 9.18.12-1-Debian <<>> @192.168.5.2 -p 5553 nt.qc.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56302
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nt.qc.local.                   IN      A

;; ANSWER SECTION:
nt.qc.local.            10      IN      A       192.168.5.120

;; Query time: 3 msec
;; SERVER: 192.168.5.2#5553(192.168.5.2) (UDP)
;; WHEN: Sun Jun 23 14:56:46 UTC 2024
;; MSG SIZE  rcvd: 45

```

**Comment by Houiin** [comment]
一个一个选项尝试过去解决了：

dnsmasq 常规设置中 `重定向保护` 取消勾选, 否则无法返回本地的IP地址
dnsmasq 高级设置中 `过滤本地包` 取消勾选，否则无法转发`.local`域名到上游服务器

**Comment by Houiin** [comment]
一个一个选项尝试过去解决了：

dnsmasq 常规设置中 `重定向保护` 取消勾选, 否则无法返回本地的IP地址
dnsmasq 高级设置中 `过滤本地包` 取消勾选，否则无法转发`.local`域名到上游服务器

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2171/1
