### ISSUE TITLE
升级0519版本后，RTL8125网卡只能协商1Gbps

### ISSUE THREAD

**Issue by Pg0dxY** [istoreos/istoreos#167]
升级0519版本后，RTL8125B网卡只能协商1Gbps
尝试使用“ethtool -s eth2 speed 2500”命令后，提示"Cannot advertise speed 2500"
ethtool结果如下↓
![912KDU1XQ7QSTJYJ_MHZ)T9](https://user-images.githubusercontent.com/34093080/169682734-bac25ceb-ef7e-4a99-a355-503de6192d09.png)

尝试重新安装0519版本不解决问题，降级安装到老版本一切正常

**Comment by Pg0dxY** [comment]
补充配置
E3-1265L v3
技嘉B85N Phoenix
WAN口板载I-217V
LAN为一块四口2.5G网卡，四个独立的RTL8125B网卡

此前正常时使用的是0429版本

**Comment by jannson** [comment]
收到。

**Comment by jannson** [comment]
请尝试昨天发布的 0526 版本，增加了很多关于 USB 的驱动。我估计可以了。

**Comment by Pg0dxY** [comment]
> 请尝试昨天发布的 0526 版本，增加了很多关于 USB 的驱动。我估计可以了。

在另外一台设备上尝试了0526版本，还是只能协商到1Gbps（图中的eth0）
![image](https://user-images.githubusercontent.com/34093080/170825169-6778ffd2-1236-420f-87fc-ab2ac84eb64b.png)

尝试ethtool -s 命令强制协商2.5Gbps，提示cannot advertise
![image](https://user-images.githubusercontent.com/34093080/170825252-4cbb0189-6502-4e71-ba4e-473daddc034e.png)

我这个卡是RTL8125B（和一些主板板载的是同款），和USB的8156/8152驱动似乎还不太一样，大佬有空的话可以再Check下

**Comment by Acocoplay** [comment]
同RTL8125B网卡，我是安装了0610最新版，同样也只能协商在1Gbps

**Comment by jjm2473** [comment]
没升级r8152驱动导致的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3533/1
