### ISSUE TITLE
商店jellyfin能更新最新版本嘛

### ISSUE THREAD

**Issue by agneitnyreh** [istoreos/istoreos#1671]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
A：商店的jellyfin能更新版本嘛，新的jellyfin的客户端好像不让用低版本服务端了

### (2) 路由器型号和固件版本
A：

### (3) 详细日志和/或截图
![image](https://github.com/istoreos/istoreos/assets/131347347/b1b63668-95ae-471c-bad0-a7cd52459fcc)
A：

**Comment by agneitnyreh** [comment]
https://www.bilibili.com/read/cv26838403/

**Comment by jjm2473** [comment]
如果不是ars2或者rk35xx机型，在插件页面点部署就行了，重新部署的时候就会拉取新镜像

**Comment by agneitnyreh** [comment]
嗯嗯，换源后也可以

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2167/1
