### ISSUE TITLE
H69k MINI使用istoreos-22.03.6-2024061415-h6xk版本无法拨号上网

### ISSUE THREAD

**Issue by EmperorLoong** [istoreos/istoreos#1678]
使用modemmanager这个协议提示“正在拆卸调制解调器载体”

H69K_MINI
5G模块:广和通FM650_CN
固件版本:istoreos-22.03.6-2024061415

不止我一个人遇到这个问题：https://github.com/istoreos/istoreos/issues/1217#issuecomment-1953600083
以下为截图
![screenshot-1718849726499](https://github.com/istoreos/istoreos/assets/55019893/70cecf3f-fd87-49cb-a74f-00803c50452d)
![screenshot-1718850701656](https://github.com/istoreos/istoreos/assets/55019893/584635ac-b8c8-4b5c-b1f3-aa93e9a33ca5)
![screenshot-1718849638303](https://github.com/istoreos/istoreos/assets/55019893/ef2e0ca1-c64c-4d30-ad99-99c3c038cc61)
![screenshot-1718849674187](https://github.com/istoreos/istoreos/assets/55019893/ee1f9c1c-4b47-4c7e-9610-28299c98994a)

**Comment by jjm2473** [comment]
自己调试，5G模块本来容易出问题，反正我们以前测试过可以连接，现在不可能再研究为什么你的环境不行。还有，你的天线接了吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2163/1
