### ISSUE TITLE
树莓派4b在系统更新了固件后，就再也连不上了

### ISSUE THREAD

**Issue by a-zhui** [istoreos/istoreos#1682]
之前设置的是静态ip，查看路由器发现，路由器给它分配了新ip，但是用新的ip也连接不上

**Comment by a-zhui** [comment]
6月29更新的

**Comment by tanhaogg** [comment]
遇上类似问题了, IP 倒是没有变化, 只是 iStoreOS 的管理页面打不开了, 上面跑的其它服务都还运行正常.

**Comment by tanhaogg** [comment]
> 遇上类似问题了, IP 倒是没有变化, 只是 iStoreOS 的管理页面打不开了, 上面跑的其它服务都还运行正常.

我的问题已经解决, 是因为之前安装了 nginx, 然后再卸载导致的问题, 按这儿的指引解决了问题
https://github.com/istoreos/istoreos/issues/1657#issuecomment-2182918211

**Comment by a-zhui** [comment]
@tanhaogg 我的上面没装nginx，还没注意上面的服务，不管怎么样，谢了兄弟

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2162/1
