### ISSUE TITLE
固件更新时误取消勾选了“保留配置”导致配置丢失，能否增加二次确认？

### ISSUE THREAD

**Issue by xkx6149** [istoreos/istoreos#1687]
确实是自己不小心，手贱点掉了，然后点击刷写固件就立即开始刷机，配置全清了。

记得有些固件会有二次弹窗告知，本次保留配置/本次清除配置。

能否增加一个二次确认的措施，感谢！

**Comment by jjm2473** [comment]
你清除复选框，再点刷机，本来就已经两步了，再加一步不是还有人一样会直接点？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2157/1
