### ISSUE TITLE
docker如何解决拉取镜像问题

### ISSUE THREAD

**Issue by 138161** [istoreos/istoreos#1688]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：当前docker的内容出现安装困难

### (2) 路由器型号和固件版本

A：22.03

### (3) 详细日志和/或截图

A：有临时替代方法吗？还是要手动下载，然后导入？谢谢

**Comment by jjm2473** [comment]
istore安装“istore增强”这个插件，会自动配置一个代理

**Comment by 138161** [comment]
ok,有效解决，谢谢

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2156/1
