### ISSUE TITLE
在docker中无法运行nodered

### ISSUE THREAD

**Issue by kern111** [istoreos/istoreos#1696]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
在docker中拉库策成功，创建容器运行就会报错
### (1) 具体问题

A：Containers: start nodered...code:500 failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: chdir to cwd ("/usr/src/node-red") set in config.json failed: operation not supported: unknown

### (2) 路由器型号和固件版本

A：软路由 n4100   iStoreOS 22.03.6 2024012613

### (3) 详细日志和/或截图

A：错误信息：Containers: start nodered...code:500 failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: chdir to cwd ("/usr/src/node-red") set in config.json failed: operation not supported: unknown

**Comment by jjm2473** [comment]
我怀疑你是不是乱填参数，或者搞错了镜像的架构

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2149/1
