### ISSUE TITLE
同为3399CPU的NanoPi M4能否使用R4S的固件呢

### ISSUE THREAD

**Issue by remph99** [istoreos/istoreos#1697]
请问友善电子推出的NanoPi M4，CPU为rk3399，能否使用R4S固件使用istore？

**Comment by jjm2473** [comment]
这个要问友善，看看是不是相同的软件配置

**Comment by fenghuan1994** [comment]
测试了一下R4s固件，无法启动

**Comment by remph99** [comment]
谢谢！

**Comment by fenghuan1994** [comment]
更新一下，可以刷，需要先刷这个历史包，然后在线更新到最新就行。不能直接刷最新版本，无法启动，原因未知。但是下载
istoreos-21.02.3-2022112305-nanopi-r4s-squashfs.img.gz这个版本，可以开机，就是绿灯会一直亮。在线更新可以正常到最新版本，也能正常开机

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2148/1
