### ISSUE TITLE
树莓派3B docker安装ubuntu， kasm无法上网

### ISSUE THREAD

**Issue by petezhou2022** [istoreos/istoreos#1699]
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ X] 没有类似的issue

### (1) 具体问题

A：树莓派3B dockers安装了ubuntu后，kasm内部无法上网

![image](https://github.com/istoreos/istoreos/assets/99304803/0139dfde-3b8f-4d54-885a-b5b958665a65)
![image](https://github.com/istoreos/istoreos/assets/99304803/0e9cb718-a7f2-4ecf-b2df-94bc15093dd6)
![image](https://github.com/istoreos/istoreos/assets/99304803/748ba408-29c6-49d3-9268-d6d48e2a232f)

### (2) 路由器型号和固件版本

A：树莓派3B

### (3) 详细日志和/或截图

A：

**Comment by petezhou2022** [comment]
![image](https://github.com/istoreos/istoreos/assets/99304803/3cc4682d-26aa-4281-add6-9d694166057f)

**Comment by jjm2473** [comment]
我们没出树莓派3B的固件，也许你要问问固件作者是不是改了docker的网络配置。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2146/1
