### ISSUE TITLE
请问支持RTL8126 5G电口么

### ISSUE THREAD

**Issue by Cranberrylemom** [istoreos/istoreos#1700]
请问支持RTL8126 5G电口么如题

**Comment by jjm2473** [comment]
安装这个驱动试试：
[kmod-r8126_5.10.201+10.013.00-1_x86_64.zip](https://github.com/user-attachments/files/16245727/kmod-r8126_5.10.201%2B10.013.00-1_x86_64.zip)

下载后解压出里面的ipk，在istore安装这个ipk。然后执行`lsmod | grep r8126`看看是不是驱动加载了，然后再看看网卡是不是识别到了。

**Comment by Cranberrylemom** [comment]
> 安装这个驱动试试： [kmod-r8126_5.10.201+10.013.00-1_x86_64.zip](https://github.com/user-attachments/files/16245727/kmod-r8126_5.10.201%2B10.013.00-1_x86_64.zip)
> 
> 下载后解压出里面的ipk，在istore安装这个ipk。然后执行看看是不是驱动加载了，然后再看看网卡是不是识别到了。`lsmod | grep r8126`

佬，OK的，能识别到了，好用！！！！

**Comment by Cranberrylemom** [comment]
内网测试速度跑满了，包用的！

**Comment by jjm2473** [comment]
好，那下次发布固件会集成

**Comment by jjm2473** [comment]
@Cranberrylemom 你测试了最新固件不安装r8126驱动就不支持rtl8126吗？我看固件自带的r8125驱动应该也支持的，是不是你没在后台的杂项设置里面启用r8125驱动？

**Comment by Cranberrylemom** [comment]
> @Cranberrylemom 你测试了最新固件不安装r8126驱动就不支持rtl8126吗？我看固件自带的r8125驱动应该也支持的，是不是你没在后台的杂项设置里面启用r8125驱动？

应该是我没有启动r8125驱动，因为我的是i226网卡，没想到r8125也能驱动

**Comment by Cranberrylemom** [comment]
我的r8126是另外用m2转的网口

**Comment by Cranberrylemom** [comment]
![屏幕截图 2024-07-17 215540](https://github.com/user-attachments/assets/5e317425-52dc-450e-b2db-eca831f3d1ff)

**Comment by Cranberrylemom** [comment]
![屏幕截图 2024-07-17 215226](https://github.com/user-attachments/assets/ae4c423c-3d00-4997-b9e4-bec06c5164ac)

**Comment by gelinesee** [comment]
请问能装在Mac OS 吗？ 谢谢！

**Comment by jjm2473** [comment]
@gelinesee 你说固件还是驱动？固件一般用虚拟机安装，例如VirtualBox。驱动肯定是没法通用的了。

**Comment by gelinesee** [comment]
驱动，因为我放在NAS下载固件能用，MacOS不行。谢谢你！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2145/1
