### ISSUE TITLE
istoreos-23.05的源编译有问题

### ISSUE THREAD

**Issue by dd-bpir3** [istoreos/istoreos#1703]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
编译提示有问题
### (1) 具体问题

A：编译后打不开web界面

### (2) 路由器型号和固件版本

A：bpi-r3

### (3) 详细日志和/或截图

A：
WARNING: Makefile 'package/feeds/telephony/asterisk/Makefile' has a dependency on 'libjwt', which does not exist
WARNING: Makefile 'package/feeds/third/luci-app-baidupcs-web/Makefile' has a dependency on 'baidupcs-web', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx6', which does not exist
WARNING: Makefile 'package/feeds/packages/prometheus-node-exporter-lua/Makefile' has a dependency on 'bmx6-json', which does not exist

  make[3] -C feeds/kenzo/luci-app-quickstart compile
luci-app-quickstart does not support JavaScript source minification
luci-app-quickstart does not support CSS source minification
luci-app-quickstart does not support JavaScript source minification
luci-app-quickstart does not support CSS source minification
 make[3] -C feeds/kenzo/luci-app-istorex compile
luci-app-istorex does not support JavaScript source minification
luci-app-istorex does not support CSS source minification
luci-app-istorex does not support JavaScript source minification
luci-app-istorex does not support CSS source minification
 make[3] -C feeds/luci/protocols/luci-proto-openconnect compile
 make[2] package/install
 make[2] target/install
 make[3] -C target/linux install
 make[2] package/index
WARNING: Applying padding in /home/yph/istoreos/bin/targets/mediatek/filogic/packages/Packages to workaround usign SHA-512 bug!

**Comment by jjm2473** [comment]
没适配bpi-r3。

如果你要自己适配或编译，别忘了openwrt默认的软件包可能不包含web界面，你可以参考其他机型的istoreos固件的配置文件，例如 https://fw0.koolcenter.com/iStoreOS/rpi4/config.seed https://fw0.koolcenter.com/iStoreOS/rpi4/feeds.conf

**Comment by jjm2473** [comment]
顺便提一句，23.05我们并没有维护，就发过几个x86的测试固件而已。打算以后直接上24版。建议你还是用22.03的代码。

**Comment by dd-bpir3** [comment]
>顺便提一句，23.05我们并没有维护，就发过几个x86的测试固件而已。打算以后直接上24版。建议你还是用22.03的代码。
![1](https://github.com/user-attachments/assets/ddeec586-cdab-4464-a8b6-fa385d797c34)
![2](https://github.com/user-attachments/assets/71a9056e-27d5-4625-a22a-2504a9cc2408)
22.03没适配bpi-r3，本人小白想用22.03源码编译，需要把23.05下target/linux/mediatek/filogic复制到22.03下吗？还是怎么操作？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2142/1
