### ISSUE TITLE
aria2安装后没有配置界面，卸载重装没有用，怎么解决？

### ISSUE THREAD

**Issue by yb9210** [istoreos/istoreos#1706]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue
X
## 2. 详细叙述
aria2安装后没有配置界面，卸载重装没有用

### (1) 具体问题

A：aria2安装后没有配置界面，卸载重装没有用

### (2) 路由器型号和固件版本

A：
设备型号
FriendlyElec NanoPi R5S LTS
固件版本
iStoreOS 22.03.6 2024062810

### (3) 详细日志和/或截图

A：
![微信图片_20240712163256](https://github.com/user-attachments/assets/ca702629-6ad5-40bd-86fb-589a49eff24c)

**Comment by jjm2473** [comment]
你的配置文件被写坏了，卸载掉aria2，然后删除/etc/config/aria2，然后再安装aria2就行了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2139/1
