### ISSUE TITLE
防火墙通信规则问题，希望解决一下，谢谢

### ISSUE THREAD

**Issue by Axzzzygr** [istoreos/istoreos#1708]
istoreos防火墙的通信规则点保存应用不生效，目前解决办法是设置完通信规则就在旁边的自定义规则里点击一下保存才生效，或者重启istoreos和重启防火墙
还有就是通信规则里设置映射也不生效，只能用端口转发，重启防火墙也不行，希望都解决一下，谢谢！

**Comment by jjm2473** [comment]
恢复出厂设置后看能否复现

**Comment by Axzzzygr** [comment]
> 恢复出厂设置后看能否复现

是的，回复出厂设置也还是一样的，目前用的最新固件版本

**Comment by jjm2473** [comment]
我测试了，没复现你说的问题。

**Comment by Axzzzygr** [comment]
> 我测试了，没复现你说的问题。

我的平台是esxi8.0 x86架构，主要是在通信规则里映射端口不生效重启防火墙也没用，还有改里面禁ping就是得重启防火墙才行，不信的话可加联系方式远程的方式测试

**Comment by Axzzzygr** [comment]
> 我测试了，没复现你说的问题。

我的平台是esxi8.0 x86架构的istoreos，主要是在通信规则里映射端口不生效重启防火墙也没用，还有改里面禁ping就是得重启防火墙才行，不信的话可加联系方式远程的方式测试

**Comment by jjm2473** [comment]
后台的“状态”-“防火墙”可以看到防火墙规则，你自己配置完通信规则到这边搜一下端口号，如果能搜到说明防火墙已经生效了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2137/1
