### ISSUE TITLE
iStoreOS更新后wan口协商速率只有100Mbos

### ISSUE THREAD

**Issue by linyuancode** [istoreos/istoreos#1715]
x86硬件直接安装iStoreOS更新22.03.6 2024071911固件后，启动或重启wan口协商速率仅有100Mbps，手动拔掉wan口网线再插上会变为正常1000Mbps。根据以往issue，可能本次更新变动驱动启动顺序导致。

**Comment by jjm2473** [comment]
跟驱动顺序无关，这次没变更驱动顺序，r8125和r8126是同一个优先级而且负责不同的设备没有重合。
如果真是驱动顺序问题，那就不会拔插网线就好了。
可以使用`ethtool -i eth0`命令检查使用的驱动。

还是换网线试试吧。

**Comment by 15906617886** [comment]
> x86硬件直接安装iStoreOS更新22.03.6 2024071911固件后，启动或重启wan口协商速率仅有100Mbps，手动拔掉wan口网线再插上会变为正常1000Mbps。根据以往issue，可能本次更新变动驱动启动顺序导致。

换更好的网线可以解决

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2131/1
