### ISSUE TITLE
iStoreOS导航栏中docker只剩配置了

### ISSUE THREAD

**Issue by linyuancode** [istoreos/istoreos#1719]
1.关于你要提交的问题
昨天更新了固件22.03.6 2024071911，iStoreOS的docker中只剩配置了。与issue1498表现一致，但是首页迁移docker目录正常，手动修改配置内的目录也没用。

A：

(2) 路由器型号和固件版本
A：

(3) 详细日志和/或截图
![IMG_20240723_020322.jpg](https://github.com/user-attachments/assets/a21a5e3c-8179-44fb-8b01-32e1863b90d6)

![IMG_20240723_020305.jpg](https://github.com/user-attachments/assets/a3b29675-a891-4fe7-b5ea-247f110fb667)

**Comment by ljiner** [comment]
请问你的解决了吗？我这个也出现这个问题了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2129/1

**Comment by JOZECN** [comment]
误打误撞，尝试istore应用商店下载会在后面使用到docker的应用比如DPanel，选择仅安装，等下载安装好已刷新，docker菜单的东西又回来了
