### ISSUE TITLE
这个可以启动，但缺少8156B网卡驱动

### ISSUE THREAD

**Issue by jannson** [istoreos/istoreos#172]
这个可以启动，但缺少8156B网卡驱动

> 请尝试这个内测版本：https://fw.koolcenter.com/iStoreOS/alpha/

_Originally posted by @bg4dew in https://github.com/linkease/istoreos/issues/161#issuecomment-1132657821_

**Comment by jannson** [comment]
@bg4dew 之前 0506 的版本能行不？

**Comment by bg4dew** [comment]
> @bg4dew 之前 0506 的版本能行不？

原来版本正常

**Comment by jannson** [comment]
请尝试昨天发布的 0526 版本，增加了很多关于 USB 的驱动。我估计可以了。

**Comment by jannson** [comment]
修复了！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3520/1
