### ISSUE TITLE
【iStore】关于最新版的iStore取消HomeAssistant应用的问题

### ISSUE THREAD

**Issue by linvex** [istoreos/istoreos#1732]
## 1.关于你要提交的问题
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
A：之前老版本的 iStoreOS 的 iStore 是提供一键 HomeAssistant 安装应用的，但是最新版没有了。我知道可以通过安装 KVM 虚拟机的方式安装，但是过程繁琐且对硬件要求较高。尝试在命令行做了一次安装源更新，发现源里还是有 HomeAssistant 相关的app的，但是我自己安装后无法正常使用，应该是需要一些其他依赖，但是我不知道需要哪些内容。
是否有可能恢复一键安装 docker 版本的 HomeAssistant，或者使用命令的方式可以通过 `is-opkg install` 进行安装/卸载？谢谢！

### (2) 路由器型号和固件版本
A：x86机器，4C8G

### (3) 详细日志和/或截图
A：
拉取的源内容：
<img width="590" alt="image" src="https://github.com/user-attachments/assets/bfb7972e-f1b2-41cd-bae8-2775013da86e">

查看包信息：
<img width="762" alt="image" src="https://github.com/user-attachments/assets/e14980e6-f995-4691-a9cc-373b1f58cadb">

**Comment by jjm2473** [comment]
这个插件根本就没改过

<img width="535" alt="image" src="https://github.com/user-attachments/assets/a2daf65b-be97-4cb8-b48d-4c43f6c44bab">

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2116/1
