### ISSUE TITLE
istoreos安装在ikuai虚拟机内，打开后台界面，显示的是英文界面，要怎么调成中文界面？

### ISSUE THREAD

**Issue by wangluofanzi** [istoreos/istoreos#1735]
(1) 具体问题
istoreos-22.03.6-2024071911-x86-64-squashfs-combined.img.gz经过解压，转成VMDK，安装在ikuai的虚拟机内，打开后台界面，显示的是英文界面，要怎么调成中文界面？

 (2) 路由器型号和固件版本
istoreos-22.03.6-2024071911-x86-64-squashfs-combined.img.gz经过解压，转成VMDK安装在ikuai的虚拟机内。

**Comment by jjm2473** [comment]
默认跟随你的浏览器的语言。如果要强制中文，那么在系统-语言和界面里面设置（默认 http://192.168.100.1/cgi-bin/luci/admin/system/system ）

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2113/1
