### ISSUE TITLE
h28k编译23.05固件错误

### ISSUE THREAD

**Issue by Spaiol** [istoreos/istoreos#1739]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

在github上使用action编译失败，奇怪的是查阅代码并没有找到错误的文件。

### (2) 路由器型号和固件版本

h28k，22.03

### (3) 详细日志和/或截图

Applying /workdir/openwrt/target/linux/generic/backport-5.15/791-v6.2-01-net-phy-Add-driver-for-Motorcomm-yt8521-gigabit-ethernet.patch using plaintext: 
patching file MAINTAINERS
patching file drivers/net/phy/Kconfig
patching file drivers/net/phy/motorcomm.c
Hunk #1 FAILED at 1.
Hunk #2 FAILED at 38.
Hunk #3 FAILED at 111.
Hunk #4 FAILED at 121.
4 out of 4 hunks FAILED -- saving rejects to file drivers/net/phy/motorcomm.c.rej
Patch failed!  Please fix /workdir/openwrt/target/linux/generic/backport-5.15/791-v6.2-01-net-phy-Add-driver-for-Motorcomm-yt8521-gigabit-ethernet.patch!
make[4]: *** [Makefile:29: /workdir/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.15.125/.prepared_0b891fa5784ba8ffc6d911ec6d720107] Error 1
make[4]: Leaving directory '/workdir/openwrt/target/linux/rockchip'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/workdir/openwrt/target/linux'
time: target/linux/compile#8.96#8.21#12.87
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:30: target/linux/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [target/Makefile:23: /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:236: world] Error 2
Error: Process completed with exit code 2.

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2110/1
