### ISSUE TITLE
Unraid6.9.2开心版虚拟机安装固件网卡不显示

### ISSUE THREAD

**Issue by main1994** [istoreos/istoreos#174]
![QQ截图20220523113208](https://user-images.githubusercontent.com/37812452/169738353-7f6a228c-aa11-4b17-bc3c-fee57397209a.png)

**Comment by main1994** [comment]
回车之后quickstart无法成功修改ip

**Comment by jannson** [comment]
你截图的这个问题不影响。但是无法修改 IP 可能是其它原因，可以 Show Interface 上来看看。

**Comment by main1994** [comment]
![QQ截图20220523153011](https://user-images.githubusercontent.com/37812452/169766764-f991b579-ebe4-41c6-b277-d694a612b6d1.png)
找不到interface

**Comment by jannson** [comment]
全虚拟网卡用的是啥？还有你得真实网卡又是啥？

**Comment by KLRot** [comment]
有同样的问题

**Comment by jannson** [comment]
请尝试昨天发布的 0526 版本，增加了很多关于 USB 的驱动。我估计可以了。

**Comment by gxlwrc** [comment]
用EFI版本就行了~

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3515/1
