### ISSUE TITLE
PD 虚拟机安装的iStoreOS最新版，旁路由模式，手机连主路由WIFI无法联网

### ISSUE THREAD

**Issue by persiliao** [istoreos/istoreos#1746]
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：PD 虚拟机安装的iStoreOS最新版，桥接网络模式，其它功能都正常，但是旁路由模式，手机连主路由WIFI无法联网

### (2) 路由器型号和固件版本

A：固件版本: iStoreOS 22.03.7 2024080210

### (3) 详细日志和/或截图

A：
![image](https://github.com/user-attachments/assets/c596026d-3153-43fd-bc53-461cb3b59b71)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2104/1
