### ISSUE TITLE
商店可以MoviePilot吗？

### ISSUE THREAD

**Issue by drama8888** [istoreos/istoreos#1759]
https://github.com/graysui/MoviePilot
这个项目很好用啊，可以代替原先的nas tool

**Comment by jjm2473** [comment]
项目开发者都说了：
> 仅用于学习交流使用，请勿在任何国内平台宣传该项目！

我们还上架istore，那不是让开发者难堪吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2094/1
