### ISSUE TITLE
安装uci-app-ipsec-vpnserver-manyusers_all.ipk会造成无限重启

### ISSUE THREAD

**Issue by Pinehao** [istoreos/istoreos#176]
1、安装uci-app-ipsec-vpnserver-manyusers_all.ipk会造成无限重启，0518 0519 0523均如此，0506没问题，不知是否是个案
2、建议：网络向导不要放一级菜单，或者做一个隐藏选项

**Comment by jannson** [comment]
uci-app-ipsec-vpnserver-manyusers_all.ipk 这个 ipk 在哪里？我下载测试下。
我刚刚更新了 0525 的版本，这个版本的品质还不错。

**Comment by jjm2473** [comment]
最新固件提高了内核模块的兼容性，测试x86已经不会重启了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3510/1
