### ISSUE TITLE
iStoreOS docker pull 和 push 私有仓库不成功，daemon.json配置不生效

### ISSUE THREAD

**Issue by dengwentong** [istoreos/istoreos#1762]
## 1.iStoreOS docker pull 和 push 私有仓库不成功
**istoreOS版本：** 22.03

## 2. 详细叙述
已经配置了 /etc/docker/daemon.json 并且也已经重新启动docker和路由器了，依然不生效。
我在公司服务器 CentOS下，Ubuntu下均能成功。

### (1) 具体问题
```bash
✘ ⚡ root@iStoreOS  /usr/lib  docker pull www.123.org:8050/dwt-harbor/redis-photon:v2.10.3
Error response from daemon: Get "https://www.123.org:8050/v2/": http: server gave HTTP response to HTTPS client
```
![1](https://github.com/user-attachments/assets/88df650b-3aca-4b58-9d45-fed7f41de28a)
![2](https://github.com/user-attachments/assets/ccb0d693-7db0-44bc-a81c-dc2de5570913)

**Comment by dengwentong** [comment]
已经找到方法了。

**Comment by jjm2473** [comment]
istoreos的docker默认不是使用这个daemon.json，而是使用生成的。

**Comment by albicocccca** [comment]
> istoreos的docker默认不是使用这个daemon.json，而是使用生成的。

我也遇到这个情况了，大哥能说的具体些openwrt上怎么操作吗，换源不生效

**Comment by albicocccca** [comment]
> 已经找到方法了。

能教教我吗

**Comment by jjm2473** [comment]
@albicocccca 删掉/etc/config/dockerd，然后自己写好 /etc/docker/daemon.json ，然后执行`/etc/init.d/dockerd restart`就行了。不过不推荐自己写daemon.json，毕竟istoreos本来就提供了后台页面管理docker配置。还有如果自己写daemon.json，注意禁用掉docker的iptables功能，以免出现安全问题。

**Comment by londbell** [comment]
> [@albicocccca](https://github.com/albicocccca) 删掉/etc/config/dockerd，然后自己写好 /etc/docker/daemon.json ，然后执行`/etc/init.d/dockerd restart`就行了。不过不推荐自己写daemon.json，毕竟istoreos本来就提供了后台页面管理docker配置。还有如果自己写daemon.json，注意禁用掉docker的iptables功能，以免出现安全问题。

主路由istoreos安装了kspeeder，打开http://192.168.2.1:5003可以看到有效

在旁路由的istoreos上设定了镜像服务器
Registry Mirrors:
  https://192.168.2.1:5443/

结果pull依然报错：
docker pull adolfintel/speedtest:latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by londbell** [comment]
> > [@albicocccca](https://github.com/albicocccca) 删掉/etc/config/dockerd，然后自己写好 /etc/docker/daemon.json ，然后执行`/etc/init.d/dockerd restart`就行了。不过不推荐自己写daemon.json，毕竟istoreos本来就提供了后台页面管理docker配置。还有如果自己写daemon.json，注意禁用掉docker的iptables功能，以免出现安全问题。
> 
> 主路由istoreos安装了kspeeder，打开[http://192.168.2.1:5003可以看到有效](http://192.168.2.1:5003%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%88%B0%E6%9C%89%E6%95%88)
> 
> 在旁路由的istoreos上设定了镜像服务器 Registry Mirrors: https://192.168.2.1:5443/
> 
> 结果pull依然报错： docker pull adolfintel/speedtest:latest Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

在主路由将registry.linkease.net解析到192.168.2.1；然后将镜像地址改成https://registry.linkease.net:5443/，问题解决，为啥不可以使用ip形式？

**Comment by jjm2473** [comment]
@londbell 因为docker会验证https证书，如果用ip，怎么申请证书呢？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2092/1
