### ISSUE TITLE
升级系统版本后无法进入后台，但是正常开机可以ssh链接

### ISSUE THREAD

**Issue by NebulaMao** [istoreos/istoreos#1763]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：更新系统版本后无法通过http://IP地址 进入后台，系统正常开机，扫描后端口80并未开放

### (2) 路由器型号和固件版本

A：J1800 x86的 22 03 7

### (3) 详细日志和/或截图

A：/overlay/upgrade.log 没有显示错误

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2091/1
