### ISSUE TITLE
无法解析xx.xx.com->192.168.31.2这种类型的域名

### ISSUE THREAD

**Issue by xuanxiaoyu69** [istoreos/istoreos#1764]
### (1) 具体问题

我有一个域名 xx.xx.com 解析到了 192.168.31.2 这样的内网ip，但是在istoreOS下，整个局域网无法解析该域名

### (2) 路由器型号和固件版本

x86机器 + iStoreOS 22.03.6 2024071911

### (3) 详细日志和/或截图

root@iStoreOS:~# ping mgr.shoppaas.c708.xyz
ping: bad address 'mgr.shoppaas.c708.xyz'

![image](https://github.com/user-attachments/assets/a441cbed-5657-4f5b-bd09-fd8b187754ee)

**Comment by xuanxiaoyu69** [comment]
找到解决办法了，在**dhcp/dns**->**常规设置**，把**重绑定保护**的勾去掉就可以了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2090/1
