### ISSUE TITLE
报告一个bug，多wan口的时候，首页显示流量不准

### ISSUE THREAD

**Issue by shenwrt** [istoreos/istoreos#177]
同上，我第一个wan口是宽带拨号，第二个是iptv接入，首页只显示iptv的流量，希望能增加一个设置，让用户可以自主选择显示哪个wan口或者直接显示所有wan口流量总合

**Comment by jannson** [comment]
OK

**Comment by jjm2473** [comment]
https://github.com/istoreos/istoreos/discussions/693

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3508/1
