### ISSUE TITLE
开机运行报错，提示网卡堵塞

### ISSUE THREAD

**Issue by zzyyyds88** [istoreos/istoreos#1780]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：开机时提示网卡堵塞，不知道是什么原因到导致的，目前是使用的vmware虚拟机安装的istore镜像，网卡采用桥接模式，在之前时间没有发现类似问题，直到最近时间才发现这个问题的存在，无论是22.03.5还是22.03.7，都存在这个问题，之前出现网卡堵塞可能会出现在局域网环境下后台无法访问的情况，使用ddnsto穿透的可以访问，虚拟机的宿主机可以访问，在局域网下的其他设备无法访问，但是在设备重新连接局域网后又可以重新访问。我还有证明问题的视频，不知道如何发出

### (2) 路由器型号和固件版本

A：22.03.5和22.03.7

### (3) 详细日志和/或截图

A：
![3a2fadff-36e0-4668-8ccc-0746fe8e3733](https://github.com/user-attachments/assets/5f115ea8-3996-4a77-a2fb-e5376d4da63b)
![96f2d4e0-7db4-46b6-a4ea-ea62efcad12a](https://github.com/user-attachments/assets/c0f3883c-9398-4895-9a07-060de6ab609b)

**Comment by jjm2473** [comment]
哪有提示网卡堵塞？难道你是说是docker0？docker0是docker的网络桥，当你启停docker容器的时候，会有虚拟网口接入或者拔出docker0，就会有这个日志，是正常的。
这跟你局域网能不能访问后台完全无关。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2077/1
