### ISSUE TITLE
/overlay扩容后，安装软件仍然提示空间不足

### ISSUE THREAD

**Issue by RobinLeon** [istoreos/istoreos#1781]
# （1）具体问题
参照https://www.vumstar.com/3134/ 网页的两种方法，对/overlay进行扩容。扩容后仍然无法安装软件，提示overlay空间不足

# (2) 路由器型号和固件版本

硬件型号：x86-64，PVE虚拟机
固件版本：istorenas  iStoreOS 22.03.7 2024080210 oversea

# (3) 详细日志和/或截图
![overlay配置情况](https://github.com/user-attachments/assets/6fb8fa67-0f44-4aca-a007-d17e6140268e)
![sdc1分区情况](https://github.com/user-attachments/assets/55d43b86-d557-4005-879a-379a82045368)
![软件安装失败](https://github.com/user-attachments/assets/be76a5ca-b7e1-4010-b159-66ed57e8a4ac)
![挂载点信息](https://github.com/user-attachments/assets/5571cf54-a7b3-4312-aa8b-06a70fc45a9d)

**Comment by RobinLeon** [comment]
解决了，还需要如图修改opkg配置后才能指定安装路径
![opkg配置](https://github.com/user-attachments/assets/d918f6fe-ba3f-4dad-8a74-7d16ff14d778)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2076/1
