### ISSUE TITLE
软件中心安装的nlbwmon只能持续统计流量10多分钟，然后就不统计流量了

### ISSUE THREAD

**Issue by m0eak** [istoreos/istoreos#1783]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：软件中心安装的nlbwmon只能持续统计流量10多分钟，然后就不统计流量了，系统日志里也没有发现报错

### (2) 路由器型号和固件版本

A：软路由x86 pve部署 iStoreOS 22.03.7 2024080210

### (3) 详细日志和/或截图

A：日志中没有nlbwmon相关的报错。

**Comment by mygit20230606** [comment]
你解决了吗 我这里也有同样的问题

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2074/1
