### ISSUE TITLE
SAMBA开机自启出问题

### ISSUE THREAD

**Issue by linyuancode** [istoreos/istoreos#1784]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

SAMBA服务在系统重启后未正常工作。

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：
使用统一文件共享功能同时开启了SAMBA和WebDAV文件共享，但是系统重启后445端口ping不通，也无法smb访问共享文件夹，webdav没问题。

后续测试，系统重启后ipv4可以ping通445端口，IPv6不可以（均为wan侧），ping返回信息msg=IOException，samba设置中已监听wan6接口。需要重启samba服务IPv6才能ping通。

目前手动解决：
进入启动项中，重启unishare或者samba4均可以解决，但是系统重启后每次都需要手动到系统启动项中重启SAMBA才正常。
问题：
是否是某种bug，怎么能够设置在开机后自动重启一下unishare或者samba4先解决一下当下问题。

### (2) 路由器型号和固件版本

A：
X86
iStoreOS 22.03.7 2024080210

### (3) 详细日志和/或截图

A：
![image](https://github.com/user-attachments/assets/bd9dfeb2-0d64-4535-b7b7-7984d56de51e)
![IMG_20240826_235106.jpg](https://github.com/user-attachments/assets/975d0077-9d1b-41dd-a13a-211df574b892)

**Comment by oyksoft** [comment]
同样有此问题，不知道如何修复。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2073/1
