### ISSUE TITLE
istoreos docker容器报错：dial tcp xx.xx.xx.xx: connect: connection refused

### ISSUE THREAD

**Issue by lemonc7** [istoreos/istoreos#1790]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
使用docker安装bark和思源笔记等容器，会报错 dial tcp xx.xx.xx.xx: connect: connection refused

### (1) 具体问题

A：用路由器istoreos和hyper-v虚拟的istoreos装都会报错，系统重置后也没用；istoreos虚拟群晖和hyper-v虚拟ubuntu系统装这两个容器都是正常使用的，不太清楚我哪里设置有问题

### (2) 路由器型号和固件版本

A：CPU-J4124，固件istoreos-22.03.6-2024071911-x86-64-squashfs-combined.img.gz

### (3) 详细日志和/或截图

A：
stdout:       ___                                   ___           ___           ___
stdout:      /  /\        ___           ___        /__/\         /  /\         /__/\
stdout:     /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
stdout:    /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
stdout:   /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
stdout:  /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
stdout:  \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
stdout:   \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
stdout:    \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
stdout:      /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
stdout:      \__\/                                 \__\/         \__\/         \__\/
stdout: I 2024/08/28 22:37:48 runtime.go:74: kernel is booting:
stdout:     * ver [3.1.4]
stdout:     * arch [amd64]
stdout:     * os [alpine]
stdout:     * pid [1]
stdout:     * runtime mode [prod]
stdout:     * working directory [/opt/siyuan]
stdout:     * read only [false]
stdout:     * container [docker]
stdout:     * database [ver=20220501]
stdout:     * workspace directory [/siyuan/workspace/]
stdout: I 2024/08/28 22:37:48 conf.go:125: loaded conf [/siyuan/workspace/conf/conf.json]
stdout: I 2024/08/28 22:37:48 runtime.go:123: use network proxy [system]
stdout: I 2024/08/28 22:37:48 serve.go:127: kernel [pid=1] http server [0.0.0.0:6806] is booting
stdout: I 2024/08/28 22:37:48 conf.go:838: database size [7.57 MB], tree/block count [0/0]
stdout: I 2024/08/28 22:37:48 working.go:193: kernel booted
stdout: I 2024/08/28 22:37:48 box.go:77: auto stat [trees=0, blocks=0, dataSize=56.84 kB, assetsSize=0 B]
stdout: E 2024/08/28 22:37:51 rhy.go:50: get version info failed: Get "https://siyuan-sync.b3logfile.com/apis/siyuan/version?ver=3.1.4": dial tcp 8.136.157.37:443: connect: connection refused
stdout: I 2024/08/28 22:38:18 session.go:116: auth success [ip=172.18.0.1:45698]
stdout: I 2024/08/28 22:38:18 serve.go:232: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0]
stdout: W 2024/08/28 22:38:19 tree.go:220: block tree not found [id=20200923234011-ieuun1p], stack: [    github.com/siyuan-note/siyuan/kernel/model.LoadTreeByBlockID({0xc0019f37e8, 0x16})
stdout:     	/go/src/github.com/siyuan-note/siyuan/kernel/model/tree.go:218 +0x5b
stdout:     github.com/siyuan-note/siyuan/kernel/model.GetDoc({0x0, 0x0}, {0x0, 0x0}, {0xc0019f37e8, 0x16}, 0x0, {0x0, 0x0}, 0x0, ...)
stdout:     	/go/src/github.com/siyuan-note/siyuan/kernel/model/file.go:604 +0x94
stdout:     github.com/siyuan-note/siyuan/kernel/api.getDoc(0xc00165a100)
stdout:     	/go/src/github.com/siyuan-note/siyuan/kernel/api/filetree.go:957 +0x599
stdout: ]
stdout: W 2024/08/28 22:38:23 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:23 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:23 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:23 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:23 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:23 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:24 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:24 net.go:90: network is offline [checkURL=https://oss.b3logfile.com]
stdout: W 2024/08/28 22:38:24 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:24 net.go:90: network is offline [checkURL=https://oss.b3logfile.com]
stdout: W 2024/08/28 22:38:24 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:24 net.go:90: network is offline [checkURL=https://oss.b3logfile.com]
stdout: W 2024/08/28 22:38:24 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:24 net.go:90: network is offline [checkURL=https://oss.b3logfile.com]
stdout: W 2024/08/28 22:38:24 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:24 net.go:90: network is offline [checkURL=https://oss.b3logfile.com]
stdout: W 2024/08/28 22:38:24 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:24 net.go:90: network is offline [checkURL=https://oss.b3logfile.com]
stdout: W 2024/08/28 22:38:25 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:26 net.go:136: check url [https://oss.b3logfile.com] is online failed: Get "https://oss.b3logfile.com": dial tcp 218.94.231.41:443: connect: connection refused
stdout: W 2024/08/28 22:38:26 net.go:90: network is offline [checkURL=https://oss.b3logfile.com]
stdout: E 2024/08/28 22:38:51 rhy.go:50: get version info failed: Get "https://siyuan-sync.b3logfile.com/apis/siyuan/version?ver=3.1.4": dial tcp 8.136.157.37:443: connect: connection refused
stdout: E 2024/08/28 22:38:51 updater.go:233: get announcement failed: Get "https://siyuan-sync.b3logfile.com/apis/siyuan/version?ver=3.1.4": dial tcp 8.136.157.37:443: connect: connection refused
stdout: I 2024/08/28 22:39:11 serve.go:232: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0]

**Comment by betsylotus** [comment]
请问这个问题怎么解决得呢？我在iStoreOS里面装思源笔记也遇到了同样的问题
