### ISSUE TITLE
默认配置编译R2s报错

### ISSUE THREAD

**Issue by ldscdil66** [istoreos/istoreos#1797]
### (1) 具体问题

A：拉取项目后执行
./scripts/feed update -a
./scripts/feed install -a
make menuconfig -> 只修改了设备型号->R2s，其他配置都默认
make download -j1
make -j1 V=s
最后报错

### (2) 路由器型号和固件版本

A：R2s  istoreos-22.03

### (3) 详细日志和/或截图

A：arch/arm/dts/rk3308-evb.dts:372.19-381.5: Warning (graph_child_address): /rgb/ports/port@1: graph node has single child node 'endpoint@0', #address-cells/#size-cells are not necessary
  SHIPPED dts/dt.dtb
  FDTGREP dts/dt-spl.dtb
  FDTGREP dts/dt-tpl.dtb
  COPY    u-boot.dtb
./"arch/arm/mach-rockchip/make_fit_atf.sh" \
arch/arm/dts/rk3308-easepi.dtb > u-boot.its
/usr/bin/env: 'python2': No such file or directory
ls: cannot access 'bl31_0x*.bin': No such file or directory
  MKIMAGE u-boot.itb
Error: u-boot.its:46.29-30 syntax error
FATAL ERROR: Unable to parse input tree
./tools/mkimage: Can't read u-boot.itb.tmp: Invalid argument
make[4]: *** [Makefile:1056: u-boot.itb] Error 255
make[4]: Leaving directory '/home/haha/tmp/istoreos/build_dir/target-aarch64_generic_musl/u-boot-easepi-rk3308/u-boot-2017.09-20230725'
make[3]: *** [Makefile:112: /home/haha/tmp/istoreos/build_dir/target-aarch64_generic_musl/u-boot-easepi-rk3308/u-boot-2017.09-20230725/.built] Error 2
make[3]: Leaving directory '/home/haha/tmp/istoreos/package/boot/uboot-rk35xx'
time: package/boot/uboot-rk35xx/easepi-rk3308/compile#31.55#8.98#39.21
    ERROR: package/boot/uboot-rk35xx failed to build (build variant: easepi-rk3308).
make[2]: *** [package/Makefile:120: package/boot/uboot-rk35xx/compile] Error 1
make[2]: Leaving directory '/home/haha/tmp/istoreos'
make[1]: *** [package/Makefile:114: /home/haha/tmp/istoreos/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/haha/tmp/istoreos'
make: *** [/home/haha/tmp/istoreos/include/toplevel.mk:234：world] 错误 2

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2063/1
