### ISSUE TITLE
luci-app-turboacc是否可以更新一下插件

### ISSUE THREAD

**Issue by msxdsw** [istoreos/istoreos#1798]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
luci-app-turboacc  没有这个插件，不知道系统底层是否已经有了，如果没有，个人如何可以安装，能给提供一下教程 吗？
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by ghost** [comment]
luci-app-turboacc无法通过安装的方式来安装，你可以在编译中加入https://github.com/chenmozhijin/turboacc

**Comment by w9315273** [comment]
我能问一下这玩意儿有什么用么

**Comment by ghost** [comment]
其实感觉没啥用对于x86设备，但是对与性能不足的arm设备可以提高小包的转发

**Comment by jjm2473** [comment]
现在这插件还有啥用？直接在防火墙开启“软件流量分载”就行了。

**Comment by jjm2473** [comment]
fullcone-nat相关设置也在防火墙。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2062/1
