### ISSUE TITLE
请问支持搭载MT7621的HATLAB GateBoard-One设备吗？应该下载哪个固件？

### ISSUE THREAD

**Issue by mick0960** [istoreos/istoreos#1806]
## 1.关于你要提交的问题
请问支持搭载MT7621的HATLAB GateBoard-One设备吗？应该下载哪个固件？

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：请问支持搭载MT7621的HATLAB GateBoard-One设备吗？应该下载哪个固件？

### (2) 路由器型号和固件版本

A：型号：HATLab GateBoard-One
目前固件版本：OpenWrt 21.02.5, r16554-1d4dea6d4f

### (3) CPU信息

![image](https://github.com/user-attachments/assets/466dffe1-5215-4e54-9761-4d3e0a83fafe)

**Comment by jjm2473** [comment]
官方没有维护低性能CPU的机型，目前支持的都是x86_64和arm64机型。官方固件在这里可以找到 https://fw.koolcenter.com/iStoreOS/

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2053/1
