### ISSUE TITLE
给个nastools的备份

### ISSUE THREAD

**Issue by czz875** [istoreos/istoreos#1807]
nastools在iStore无了，有好心人能给个nastools的ipk备份吗
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：nastools在iStore无了，有好心人能给个nastools的ipk备份吗

### (2) 路由器型号和固件版本

A：x64/x86

### (3) 详细日志和/或截图

A：

**Comment by lsttczh10** [comment]
同求一个，

**Comment by jjm2473** [comment]
https://istore.linkease.com/repo/all/nas_luci/luci-app-nastools_1.1.3-20231208_all.ipk
https://istore.linkease.com/repo/all/nas_luci/luci-i18n-nastools-zh-cn_git-23.072.37344-dadcf42_all.ipk

注意默认的镜像可能没用了，需要自己替换成有效的镜像。
还有，安装以后不会出现在istore里，需要自己在菜单找。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2052/1
