### ISSUE TITLE
固件下载不了

### ISSUE THREAD

**Issue by woeoio** [istoreos/istoreos#1808]
反馈bug/问题模板，提建议请删除

https://[istore.linkease.com](https://istore.linkease.com/)/

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by girlmn** [comment]
1. 下载最新固件时 下载网页发生错误
2. r5s 
3. 
![image](https://github.com/user-attachments/assets/1b380162-87d3-4e20-ada3-9ffe8025d75f)
![image](https://github.com/user-attachments/assets/4ea442d7-8802-4ca3-abb1-903a31d463c7)

**Comment by girlmn** [comment]
请尽快恢复

**Comment by jjm2473** [comment]
不是还有其他备用地址吗？或者到这里下载 https://sourceforge.net/projects/istoreos/files/iStoreOS/

**Comment by jjm2473** [comment]
而且这不是插件，是固件。而且不是404，是连接错误。

**Comment by woeoio** [comment]
后来好了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2051/1
