### ISSUE TITLE
请问525版本IPV6是不是还是有问题？

### ISSUE THREAD

**Issue by terryzung** [istoreos/istoreos#181]
525版本可以获取IPV6地址但是不能访问IPV6网站。

**Comment by jannson** [comment]
你用其他固件可以访问 IPv6 网站么？有的即使得到 IPv6 也无法访问网站。

**Comment by terryzung** [comment]
> 你用其他固件可以访问 IPv6 网站么？有的即使得到 IPv6 也无法访问网站。

506版本时IPV6可以用，后来升级后就不行了，可以获取IPV6地址，但是不能IPV6访问网站

**Comment by ablezzzz** [comment]
526的ipv6获取到了ipv6地址，也无法上网

**Comment by jannson** [comment]
如果以前能用，现在不能用，那我们确认下。。。

**Comment by menchian** [comment]
現在的版本依然有同樣問題（r4s）

**Comment by jannson** [comment]
嗯，这个问题还存在，最近还没空去修复。刚开发完成了 RAID，下一步来修复。

**Comment by jjm2473** [comment]
这个也许是因为固件默认禁止ipv6 dns解析。
在 “DHCP/DNS” 的 “高级设置” 里面，取消勾选 “禁止解析 IPv6 DNS 记录” 就行了。

很多人的ipv6有问题，所以默认禁止ipv6解析。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3499/1
