### ISSUE TITLE
istore OS首页IP地址显示无法调整

### ISSUE THREAD

**Issue by lonely5202** [istoreos/istoreos#1811]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
上海电信因为要看IPTV加了一些配置, 然后首页就自动显示85的专网IP信息了. 其实我还是想显示PPPOE获得的地址信息, 但没法在首页这里自己选择显示哪个网络的IP地址了. 希望后续更新能加上
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：22.03.7 2024080210

### (3) 详细日志和/或截图

A：![Snipaste_2024-09-14_11-11-47](https://github.com/user-attachments/assets/b9c43dce-f496-4cd4-b7c4-057c5f9f882c)

**Comment by jjm2473** [comment]
既然不是默认网关，那就别够勾选默认网关。

**Comment by jjm2473** [comment]
iptv接口配置的时候，不要勾选“使用默认网关”，因为根本不会从这个接口上网。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2048/1
