### ISSUE TITLE
115网盘昨天不能用,今天发现Alist 无法连115网盘，麻烦商店及时更新新的Alist版本

### ISSUE THREAD

**Issue by KoreAkira** [istoreos/istoreos#1814]
![image](https://github.com/user-attachments/assets/6a32b0f6-1290-4cbd-954a-d6b967eac565)

**Comment by hnzhaihui** [comment]
iStoreOS 22.03.6 2024032917 商店里的alist还是3.33.0，最新alist是3.37.3，已经解决了115网盘不能登录的问题，希望能尽快更新，谢谢！

**Comment by byteinfo** [comment]
https://github.com/sbwml/luci-app-alist/releases 到这里自己下载软件包更新一下吧

**Comment by WangDefa88** [comment]
> https://github.com/sbwml/luci-app-alist/releases 到这里自己下载软件包更新一下吧

请问怎么手动添加到istore里面去啊？那里只支持ipk和run格式的，这个gz格式的下载下来怎么弄呢？

**Comment by byteinfo** [comment]
> > https://github.com/sbwml/luci-app-alist/releases 到这里自己下载软件包更新一下吧
> 
> 请问怎么手动添加到istore里面去啊？那里只支持ipk和run格式的，这个gz格式的下载下来怎么弄呢？
下载相应版本，解压出来是ipk的

**Comment by jjm2473** [comment]
istore更新了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2046/1
