### ISSUE TITLE
建议适配友善r3s

### ISSUE THREAD

**Issue by levkanm** [istoreos/istoreos#1820]
![image](https://github.com/user-attachments/assets/68aad290-5ace-4aec-b8ef-8cb29dba4fef)

**Comment by jjm2473** [comment]
请提供测试机

**Comment by jjm2473** [comment]
已经适配

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2041/1
