### ISSUE TITLE
Docker容器创建不出来

### ISSUE THREAD

**Issue by gh4zw** [istoreos/istoreos#1823]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：Docker容器创建不出来，执行 Docker run 命令，提示“没有指定命令选项”，添加了命令选项后，又无法识别。同样的 Docker run 语句之前在群辉上是可以正常执行的。

### (2) 路由器型号和固件版本

A：星际蜗牛：Intel(R) Celeron(R) CPU J1900 @ 1.99GHz
      固件版本：iStoreOS 22.03.7 2024080210 / LuCI istoreos-22.03 branch git-24.207.28853-3b34de8

### (3) 详细日志和/或截图

A：![屏幕截图 2024-09-22 160927](https://github.com/user-attachments/assets/d1271d21-ff3c-46d7-a5ab-c0f0a47c1a8a)

**Comment by rayangl** [comment]
有没有可能 不需要 run 你使用的命令是其他操作系统的

**Comment by jjm2473** [comment]
eoch是啥命令啊？你确定不是echo？

**Comment by gh4zw** [comment]
谢谢两位的回复，使我理顺了思路，找到自己忽略的地方了。
确实是界面表单填写有问题

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2039/1
