### ISSUE TITLE
请问如何设置登录页禁止公网访问？

### ISSUE THREAD

**Issue by 534701851** [istoreos/istoreos#1824]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：请问如何设置禁止公网访问？部署ddnsgo后暴露在公网 怕被打

### (2) 路由器型号和固件版本

A：esxi

### (3) 详细日志和/或截图

A：

**Comment by 138161** [comment]
你试一下
防火墙--通讯规则--添加
协议         TCP    UDP
源区域     wanwan: [以太网适配器: "eth0"] wan6: [以太网适配器: "eth0"] 
目标区域    设备 (输入)
目标端口    80
操作          抛弃

**Comment by jjm2473** [comment]
默认都是禁止wan口访问的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2038/1
