### ISSUE TITLE
为什么istoreOS中rcloned 开机自动启动脚本无法执行？其他openwrt可以

### ISSUE THREAD

**Issue by Yumega** [istoreos/istoreos#1828]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
同样配置在其他openwrt没有错误，可以正常启动
wget https://wp.gxnas.com/wp-content/uploads/2021/08/rcloned && vi rcloned
（脚本修改自己成目录）
mv rcloned /etc/init.d/rcloned
chmod +x /etc/init.d/rcloned
bash /etc/init.d/rcloned start

启动项添加 bash /etc/init.d/rcloned start
### (1) 具体问题

A：istoreOS系统启动项，rcloned 启动执行失败

### (2) 路由器型号和固件版本

A：J4125 x86, 最新版固件

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
https://wp.gxnas.com/wp-content/uploads/2021/08/rcloned 这个脚本是给debian使用的。例如里面使用的ps命令也是完整版，不是openwrt自带的busybox版本。你说openwrt能用这个方式自动启动rclone？那我问你哪里注册了自动启动？openwrt自动启动的文件夹知道是哪个吗？用你提供的命令能单次启动就已经万幸了。

**Comment by jjm2473** [comment]
如果你要用rclone挂载webdav，istoreos的“挂载网络共享”里面就能选择rclone。

**Comment by Yumega** [comment]
> https://wp.gxnas.com/wp-content/uploads/2021/08/rcloned 这个脚本是给debian使用的。
骷髅头的固件 可以正常使用 
https://www.right.com.cn/forum/thread-7371875-1-1.html

**Comment by Yumega** [comment]
> 如果你要用rclone挂载webdav，istoreos的“挂载网络共享”里面就能选择rclone。

用上了

**Comment by jjm2473** [comment]
> 骷髅头的固件 可以正常使用

这根本不是官方openwrt啊，也许他集成了其他版本的ps，让这个脚本能正常运行。但是也绝对不可能开机启动，因为根本没注册到自启动文件夹里面。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2035/1
