### ISSUE TITLE
istore无法安装插件 手动安装时依赖也安装不上

### ISSUE THREAD

**Issue by girlmn** [istoreos/istoreos#1830]
### (1) 具体问题

重新刷了固件后无法安装依赖和插件

### (2) 路由器型号和固件版本

r5s 
![image](https://github.com/user-attachments/assets/a96f2414-1dc6-4928-ad3b-b3172d4c9ff4)

### (3) 详细日志和/或截图
![image](https://github.com/user-attachments/assets/28eea2bc-2031-4a44-8cfe-9ddcf1c8836a)

**Comment by jjm2473** [comment]
软路由的系统时间不对

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2033/1
