### ISSUE TITLE
在8168网卡上使用了8169驱动

### ISSUE THREAD

**Issue by sheen197** [istoreos/istoreos#1834]
### (1) 具体问题

可能类似 https://github.com/istoreos/istoreos/issues/899

在wyse 5070上安装istoreos。二手资料讯息显示wyse5070的网卡是8168
在istoreos中使用ethtool 发现 driver是r8169   firmware-version是 rtl8168h
发生的情况是，网速上下行有巨大的速度差。
台式机使用iperf或者homebox测速，下行（从软路由到台式机）1000M，上行（从台式机到软路由）60M

文件管理器查看lib/firmware，能看到rtl8168h相关的fw文件。在istoreos界面内的软件包界面的已安装列表，也能看到rtl8168相关组件。但如果按照ethtool里的信息，那它就是反而优先加载了r8169的驱动？

下行满速表明至少网线这些应该是没问题的。那上下行速度差是否是因为错误的启用了r8169驱动导致呢？
这种情况应当怎么解决？直接删除8169相关组件吗？ 

### (2) 路由器型号和固件版本

硬件是 wyse 5070 瘦客户机
软件是 iStoreOS 22.03.7 2024080210

**Comment by sheen197** [comment]
使用 https://github.com/istoreos/istoreos/issues/904 中的方法已解决，一开始搜错了

**Comment by sheen197** [comment]
在杂项设置中启用8168网卡驱动后上下行速率恢复正常，都能达到一致的1000M速率

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2029/1
