### ISSUE TITLE
没有包，什么时候会添加？

### ISSUE THREAD

**Issue by IIIef** [istoreos/istoreos#1836]
我无法安装软件包, 
nftables
kmod-nft-nat
kmod-nft-offload
kmod-nft-queue
luci-app-homeproxy
它们何时会被添加，以及它们是否会在不久的将来被添加。
![img-2024-09-28-09-25-01](https://github.com/user-attachments/assets/868f9706-fd5d-4aa2-99a5-8fcabfabf253)

**Comment by jjm2473** [comment]
为什么一定要这个，其他翻墙插件不够用吗？luci-app-homeproxy只支持nftables，不支持iptables。用passwall不就行了。

**Comment by jjm2473** [comment]
暂时还不会切换到nftables

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2028/1
