### ISSUE TITLE
网络共享权限自动回滚

### ISSUE THREAD

**Issue by zhanghaoliang996** [istoreos/istoreos#1838]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：每次去掉共享目录的只读权限后，等一段时间不知道是系统重启还是什么就自动又勾选上了

### (2) 路由器型号和固件版本

A：openwrt 固件版本
iStoreOS 22.03.7 2024080210

### (3) 详细日志和/或截图

A：
![微信截图_20241001132509](https://github.com/user-attachments/assets/46ace6c4-d455-4565-9712-81c59eb681ad)

**Comment by jjm2473** [comment]
说明你这个共享是在“统一文件共享”里配置的啊，如果你不打算用“统一文件共享”来管理，那就在那边删掉。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2026/1
