### ISSUE TITLE
求助 其他openwrt系统中正常工作的shellcrash功能在istoreos中无法正常工作

### ISSUE THREAD

**Issue by fejelaqbhbv** [istoreos/istoreos#1839]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

shellcrash中有个防火墙重启后XXX的自定义自动任务，在istoreos无法正常工作，尝试原版openwrt 23.05 22.03 21.02，immortalwrt 23.05 21.02，lean lede这六份固件都是正常工作的，只有istoreos无法正常工作，求助。

操作过程
01. 下载并刷入[istore固件](https://fw0.koolcenter.com/iStoreOS/x86_64_efi/istoreos-22.03.7-2024080210-x86-64-squashfs-combined-efi.img.gz)
02. 开机后通过网络向导设置并成功通过宽带拨号连接
03. 通过 服务-终端 或其它ssh软件登录
04. [安装shellcrash](https://github.com/juewuy/ShellCrash/blob/dev/README_CN.md#%E5%9C%A8%E7%BA%BF%E5%AE%89%E8%A3%85)
05. 进入shellcrash并通过 5 配置自动任务-1 添加自动任务-随意-8 防火墙服务重启后执行 添加自动任务 （我多数是用的11 重设透明路由防火墙，因为速度快且明显）
06. 随意加载一份可用配置文件启动shellcrash并正常运行
07. 确认 5 配置自动任务-2 管理任务列表-刚才自己添加的任务- 3 立即执行一次 可正常工作
08. 通过 网络-接口-重启pppoe(wan)
09. 查看shellcrash 5 配置自动任务-3 查看任务日志 ，是否存在两次及以上的执行记录

多次尝试，istoreos只能手动触发，无法自动触发防火墙重启后XXX的命令，而其他openwrt固件通过同样的流程添加任务可正常工作

### (2) 路由器型号和固件版本

iStoreOS 22.03.7 2024080210 / LuCI istoreos-22.03 branch git-24.207.28853-3b34de8 X64

**Comment by fejeIaqbhbv** [comment]
这两天又自己抽空找了下原因，应该是istoreos修改了防火墙的问题
```sh
git clone -b istoreos-22.03 --single-branch --filter=blob:none https://github.com/istoreos/istoreos
cd istoreos
./scripts/feeds update -a
./scripts/feeds install -a
touch .config
cat >> .config << EOF
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y
CONFIG_TARGET_KERNEL_PARTSIZE=100
CONFIG_TARGET_ROOTFS_PARTSIZE=1000
# CONFIG_PACKAGE_firewall is not set
CONFIG_PACKAGE_firewall4=y
CONFIG_PACKAGE_kmod-nft-tproxy=y
CONFIG_PACKAGE_luci-app-ttyd=y
EOF
make defconfig
make -j$(nproc)
```
用istore提供的源代码，修改防火墙为fw4后编译出来的固件是正常的

所以是22版本强用ipt的问题

很奇怪，照理应该不会有这种问题

检测的是依赖包又不是固件版本

istore提供的22版ipt也没有装nft相关

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2025/1
