### ISSUE TITLE
配置始终保存失败

### ISSUE THREAD

**Issue by jihongboo** [istoreos/istoreos#1842]
### (1) 具体问题

A：配置始终保存失败

### (2) 路由器型号和固件版本

A：N1 iStoreOS 22.03.6 2024043010

### (3) 详细日志和/或截图

A：uci set dockerd.globals.data_root='/overlay/upper/opt/docker'

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2022/1
