### ISSUE TITLE
r3s 什么时候适配呀

### ISSUE THREAD

**Issue by doudou-dream** [istoreos/istoreos#1858]

**Comment by coolsnowwolf** [comment]
已经适配  PR

**Comment by Suaig** [comment]
我拉了最新的PR，编译成功了，但是不能进后台，不知道为啥子。能获取到IP 192.168.100.1

**Comment by jjm2473** [comment]
重复 #1820

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2011/1
