### ISSUE TITLE
无法识别万兆网卡

### ISSUE THREAD

**Issue by cuteyboys** [istoreos/istoreos#1860]
具体问题

A：我是用硬酷R2 Max的万兆机器 万兆网卡为AQC113C-B1-C 安装了固件后 可能由于驱动问题 无法识别万兆网卡 该怎么解决

路由器型号和固件版本

A：固件版本为 2023052616

**Comment by jjm2473** [comment]
用最新固件来测试，然后执行`lspci -nnk`把输出贴出来

**Comment by cuteyboys** [comment]
<img width="949" alt="微信图片_20241022192338" src="https://github.com/user-attachments/assets/8fd2119e-15d9-487d-b182-c1a3a926002e">
固件版本：22.03.7-2024080210

**Comment by cuteyboys** [comment]
> 用最新固件来测试，然后执行`lspci -nnk`把输出贴出来

![image](https://github.com/user-attachments/assets/caa74fe4-2fe3-49af-9582-bdb1731e570b)
固件版本：22.03.7-2024080210

**Comment by jjm2473** [comment]
今天会发固件，集成了驱动，需要自己测试下有没有问题。

**Comment by cuteyboys** [comment]
> 今天会发固件，集成了驱动，需要自己测试下有没有问题。

老哥 更新固件现在还没有发出吗

**Comment by jjm2473** [comment]
@cuteyboys 你先到这里下载吧，不过安装以后先别用在线更新，不然会降级 https://sourceforge.net/projects/istoreos/files/iStoreOS/

**Comment by cuteyboys** [comment]
> @cuteyboys 你先到这里下载吧，不过安装以后先别用在线更新，不然会降级 https://sourceforge.net/projects/istoreos/files/iStoreOS/

感谢开发老哥，我安装后已经可以正常使用，什么时候可以正常自动更新呢

**Comment by jjm2473** [comment]
检查更新时如果显示202408xx版本，就别更新，至少要202410以后的才行。这周应该会发上线的

**Comment by jjm2473** [comment]
固件已经发布了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2010/1
