### ISSUE TITLE
0526版，温度显示依然有问题，永远显示128度

### ISSUE THREAD

**Issue by hwd1118** [istoreos/istoreos#188]
![image](https://user-images.githubusercontent.com/30280994/170808506-0721ea1d-9290-4881-97e7-accea04e528f.png)

机器是英特尔老款nuc，n3700cpu

**Comment by jannson** [comment]
好吧，我同事非得不用 sensors。我一会还是让开发者用回 sensors 吧。。。

**Comment by jannson** [comment]
请加入 iStoreOS QQ 群，我远程下你的机器吧。你给的方案也不得行。。。
且还是不想用 sensors，这个东西也没个固定自动，你给的 sensors | grep -E 'temp1' 也是不行的，你看看里面的 temp1 这么多，都不知道哪个。。。

<img width="358" alt="1516568dc473dbc5c6d952d7722821d" src="https://user-images.githubusercontent.com/4100344/171096884-d68b81b8-773a-4f2e-a7bc-1e200c97be12.png">

**Comment by alex300414** [comment]
0601版本，AMD机型还有不显示温度

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3482/1
