### ISSUE TITLE
x86机器安装后wan口无法使用静态(固定)IP

### ISSUE THREAD

**Issue by 0ct** [istoreos/istoreos#1882]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：WAN口使用静态IP/固定IP,出现异常
问题1：使用上级路由IP与mac地址绑定功能，路由器无法获取到IP
问题2：使用路由器的静态IP，概览页面无法显示wan口IP，可正常登录管理页面

### (2) 路由器型号和固件版本
路由器型号：
- EQ12（AX101可能，显示i225 * 2）
![image](https://github.com/user-attachments/assets/52d3bdd4-4ed8-4575-be65-ae97f4c6bd3c)
- 自组小主机（3 x Intel i226-V (via PCIe), 1 x Realtek 8156B[G] (via USB 3.0)）

固件版本：[iStoreOS/x86_64_efi/istoreos-22.03.7-2024102509-x86-64-squashfs-combined-efi.img.gz](https://fw0.koolcenter.com/iStoreOS/x86_64_efi/istoreos-22.03.7-2024102509-x86-64-squashfs-combined-efi.img.gz)

### (3) 详细日志和/或截图
截图以EQ12为例
问题1：
1. 上级路由器配置IP与mac地址绑定
![image](https://github.com/user-attachments/assets/292daf89-7de3-45fa-b850-0d9349cf33c3)
2. quickstart中wan口IPv4无IP
![382171257-8e386efc-14a6-4e86-94b3-01893d87aa3d](https://github.com/user-attachments/assets/b4767161-84c5-4f46-b343-33f5aba484c2)

问题2：
1. iStoreOS wan口配置静态IPv4，可以通过浏览器登录管理页面，概览中的wan口为空
![image](https://github.com/user-attachments/assets/306c90cf-944b-4c00-9448-b48c126d6279)
![image](https://github.com/user-attachments/assets/c7f9fe64-cdb5-498a-b843-46fad263c4ce)

正常DHCP：
![image](https://github.com/user-attachments/assets/6bc438c4-f78e-4bd4-b76b-6766263419a0)

版本信息：
![image](https://github.com/user-attachments/assets/201a7ece-8a10-40d9-9492-d10bd69f0986)

**Comment by 0ct** [comment]
更多：
- DHCP时，上级路由器显示iStoreOS 为主机名
DHCP：
![image](https://github.com/user-attachments/assets/854dcfb4-c5ed-4558-b07d-150af02187f3)
接口-wan-静态IP：
![image](https://github.com/user-attachments/assets/69888b30-a66c-48ed-b0f3-e8e06b12a14f)
- 自定义IP，无法上网。DNS 配置和联网检查一直转圈。已修改尝试过：1. /etc/resolv.conf，2. dhcp/dns中转发，接口中wan口高级的自定义dns
接口-wan-静态IP：
![image](https://github.com/user-attachments/assets/33deda55-dcfc-4b86-981a-4f7c5a6deb88)
![image](https://github.com/user-attachments/assets/7b0bbb3c-a942-4887-a70b-4dc24df932f1)
网络诊断可以获取到IP，但无法ping 通
![image](https://github.com/user-attachments/assets/f0e1b8f2-afdf-4da2-88f6-39cb4375e6d5)

**Comment by 0ct** [comment]
必须填写完整静态地址:
IP address 
mask
gateway

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1997/1
