### ISSUE TITLE
请问什么时候升级到23.05，22的内核太老了，不支持新cpu的gpu解码

### ISSUE THREAD

**Issue by goIntoAction** [istoreos/istoreos#1883]
看到23.05的分支很久没提交新代码了，不知道istoreos团队的计划是怎么样的

**Comment by fejeIaqbhbv** [comment]
> 请问什么时候升级到23.05，22的内核太老了，不支持新cpu的gpu解码

不知道你是不是intel的

是的话先试下 系统-杂项设置-驱动

> 看到23.05的分支很久没提交新代码了，不知道istoreos团队的计划是怎么样的

官方之前说不上23.05了，因为23和22内核差别不大，直接上24.10 6.6的内核，现在op官方刚分branch才刚十个小时，都还没release呢，再等等

**Comment by goIntoAction** [comment]
> > 请问什么时候升级到23.05，22的内核太老了，不支持新cpu的gpu解码
> 
> 不知道你是不是intel的
> 
> 是的话先试下 系统-杂项设置-驱动
> 
> > 看到23.05的分支很久没提交新代码了，不知道istoreos团队的计划是怎么样的
> 
> 官方之前说不上23.05了，因为23和22内核差别不大，直接上24.10 6.6的内核，现在op官方刚分branch才刚十个小时，都还没release呢，再等等

谢谢解答，我是用n100 cpu，之前试过使用i915驱动，jellyfin还是不能调用gpu，这样看来还是得等24了

**Comment by fejeIaqbhbv** [comment]
我记得n100之前说可以用，你别关这个issue

---

你参考下这个https://github.com/istoreos/istoreos/issues/1271#issuecomment-1899817188

**Comment by goIntoAction** [comment]
> 我记得n100之前说可以用，你别关这个issue
> 
> 你参考下这个[#1271 (comment)](https://github.com/istoreos/istoreos/issues/1271#issuecomment-1899817188)

我和他现象一样，dri下能看到renderD128，我后面试下自己安装jellyfin，不用istore商店的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1996/1
