### ISSUE TITLE
第三方云编译，缺少某些系统必要的依赖和插件，需要你们修复

### ISSUE THREAD

**Issue by xiaomeng9597** [istoreos/istoreos#1887]
缺少quickstart和store应用商店插件，quickstart只有一个quickstart依赖其他包都没有了，首页和网络向导，网口配置都没了，10月份28号的时候编译还有这些依赖和插件的。很奇怪到11月份的时候编译就没了。左边是这个月编译的，右边是10月份编译的，你们上游仓库改了某些东西吗？
![Screenshot_2024-11-05-14-54-06-885_bin mt plus](https://github.com/user-attachments/assets/a9417daa-5e5e-4943-aa7f-a84b3e5d4274)
云编译仓库地址 https://github.com/xiaomeng9597/Actions-iStoreOS-RK35XX

**Comment by xiaomeng9597** [comment]
瑞芯微rk35xx架构的，我寻思着这个月我也没有改什么东西啊

**Comment by xiaomeng9597** [comment]
上面那些依赖和插件，应该都是默认预装进去的啊

**Comment by xiaomeng9597** [comment]
貌似第三方个人编译的istoreos固件都存在这个问题了，.config文件里面都有这些包名的，编译出来的固件依然缺少这些依赖和插件，所以系统已不完整，没法使用了，本地编译应该也受影响。

**Comment by fejeIaqbhbv** [comment]
```
src-git-full packages https://github.com/jjm2473/packages.git;istoreos-22.03
src-git-full luci https://github.com/jjm2473/luci.git;istoreos-22.03
src-git-full routing https://git.openwrt.org/feed/routing.git;openwrt-22.03
src-git-full telephony https://git.openwrt.org/feed/telephony.git;openwrt-22.03
src-git store https://github.com/linkease/istore.git;main
src-git third https://github.com/jjm2473/openwrt-third.git;main
src-git third_party https://github.com/linkease/istore-packages.git;main
src-git diskman https://github.com/jjm2473/luci-app-diskman.git;dev
src-git oaf https://github.com/jjm2473/OpenAppFilter.git;dev4
src-git linkease_nas https://github.com/linkease/nas-packages.git;master
src-git linkease_nas_luci https://github.com/linkease/nas-packages-luci.git;main
src-git jjm2473_apps https://github.com/jjm2473/openwrt-apps.git;main
```

**Comment by xiaomeng9597** [comment]
> ```
> src-git-full packages https://github.com/jjm2473/packages.git;istoreos-22.03
> src-git-full luci https://github.com/jjm2473/luci.git;istoreos-22.03
> src-git-full routing https://git.openwrt.org/feed/routing.git;openwrt-22.03
> src-git-full telephony https://git.openwrt.org/feed/telephony.git;openwrt-22.03
> src-git store https://github.com/linkease/istore.git;main
> src-git third https://github.com/jjm2473/openwrt-third.git;main
> src-git third_party https://github.com/linkease/istore-packages.git;main
> src-git diskman https://github.com/jjm2473/luci-app-diskman.git;dev
> src-git oaf https://github.com/jjm2473/OpenAppFilter.git;dev4
> src-git linkease_nas https://github.com/linkease/nas-packages.git;master
> src-git linkease_nas_luci https://github.com/linkease/nas-packages-luci.git;main
> src-git jjm2473_apps https://github.com/jjm2473/openwrt-apps.git;main
> ```

并不是这个问题造成的，istore应用商店仓库，小宝他们删除了两个必要的依赖造成的，官方固件网站上的config.buildinfo文件里面也没有被删除的两个依赖包名。

**Comment by xiaomeng9597** [comment]
> ```
> src-git-full packages https://github.com/jjm2473/packages.git;istoreos-22.03
> src-git-full luci https://github.com/jjm2473/luci.git;istoreos-22.03
> src-git-full routing https://git.openwrt.org/feed/routing.git;openwrt-22.03
> src-git-full telephony https://git.openwrt.org/feed/telephony.git;openwrt-22.03
> src-git store https://github.com/linkease/istore.git;main
> src-git third https://github.com/jjm2473/openwrt-third.git;main
> src-git third_party https://github.com/linkease/istore-packages.git;main
> src-git diskman https://github.com/jjm2473/luci-app-diskman.git;dev
> src-git oaf https://github.com/jjm2473/OpenAppFilter.git;dev4
> src-git linkease_nas https://github.com/linkease/nas-packages.git;master
> src-git linkease_nas_luci https://github.com/linkease/nas-packages-luci.git;main
> src-git jjm2473_apps https://github.com/jjm2473/openwrt-apps.git;main
> ```

我用的feeds.conf和.config文件都是来自istoreos固件站的，所以并不是这个软件源仓库的原因，反正我已经解决了
https://fw0.koolcenter.com/iStoreOS/station-p2/feeds.conf
https://fw0.koolcenter.com/iStoreOS/station-p2/config.buildinfo

**Comment by fejeIaqbhbv** [comment]
额，那估计是近一个月删的吧，我之前编译没发现问题
不清楚你怎么解决的
如果麻烦的话可以考虑指定hash
https://fw0.koolcenter.com/iStoreOS/station-p2/feeds.buildinfo

**Comment by xiaomeng9597** [comment]
> 额，那估计是近一个月删的吧，我之前编译没发现问题 不清楚你怎么解决的 如果麻烦的话可以考虑指定hash https://fw0.koolcenter.com/iStoreOS/station-p2/feeds.buildinfo

另外追加添加这几个包名就可以解决了

CONFIG_PACKAGE_coreutils=y
CONFIG_PACKAGE_coreutils-base64=y
CONFIG_PACKAGE_coreutils-stat=y
CONFIG_PACKAGE_coreutils-stty=y

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1992/1
