### ISSUE TITLE
0526版本启动大概率网卡不工作，网卡为CX341，必顺要断电重启，0506无此问题

### ISSUE THREAD

**Issue by ilyyce-luojun** [istoreos/istoreos#189]
主板为H310 CPU  I5 6600T 网卡CX341

**Comment by jannson** [comment]
收到。我们确认 ing

**Comment by ilyyce-luojun** [comment]
老大，是否确认，我刷了0610版本还是一样

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3481/1
