### ISSUE TITLE
局域网内有IP为192.168.3.2的设备，但是istore的路由界面没有显示该设备

### ISSUE THREAD

**Issue by King-hsw** [istoreos/istoreos#1891]
## 1.关于你要提交的问题
局域网内有IP为192.168.3.2的设备，但是istore的路由界面没有显示该设备

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
全屋组网，光猫桥接，r5s作为主路由拨号，下面接了一个TL-R479GPE-AC，接在机器的LAN口，只做统一控制，不提供IP分配，目前r5s的路由面板看到AC的设备的ip地址，但是能显示AC下AP提供连接的设备

### (2) 路由器型号和固件版本

<img width="1197" alt="image" src="https://github.com/user-attachments/assets/d9b5347a-edff-4bef-9455-dede9b604c73">

### (3) 详细日志和/或截图

<img width="1286" alt="image" src="https://github.com/user-attachments/assets/a23b18cb-bc82-4f00-bc58-413093aeb50e">
<img width="652" alt="image" src="https://github.com/user-attachments/assets/d342e2d7-9773-42c1-9a77-b0549c2cfe4d">

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1988/1
