### ISSUE TITLE
编译istoreos系统，发现缺少插件

### ISSUE THREAD

**Issue by 1967937965** [istoreos/istoreos#1894]
没有类似的issue

## 2. 详细叙述
编译istoreos系统时，缺少istore插件，尝试手动下载到package文件夹和添加到feeds.conf.default中依旧缺少，尝试更换编译机依旧缺少

路由器型号和固件版本

A：所有

**Comment by fejeIaqbhbv** [comment]
去 https://fw.koolcenter.com/iStoreOS/ 找你对应固件的`feeds.buildinfo`
比如x64就用 https://fw0.koolcenter.com/iStoreOS/x86_64_efi/feeds.buildinfo 里的内容代替 feeds.conf.default

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1986/1
