### ISSUE TITLE
opkg update 报错失败 opkg_download: Failed to download https://istore.linkease.com/repo/all/compat/Packages.gz, curl returned 35.

### ISSUE THREAD

**Issue by WvvvWv** [istoreos/istoreos#1898]
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x ] 没有类似的issue
有类似curl的issus，但是没有解决我这边的问题

### (1) 具体问题
商店手动安装passwall2提示失败，然后又试了opkg 更新发现也失败。

### (2) 路由器型号和固件版本
J4125工控机，Pve All In Boom

设备型号
QEMU Standard PC (Q35 + ICH9, 2009)
固件版本
iStoreOS 22.03.7 2024102509
内核版本
5.10.221

### (3) 详细日志和/或截图

应用商店手动安装passwall2失败报错：
![商店手动安装报错](https://github.com/user-attachments/assets/7b6fbce5-6c99-4e47-aaeb-6f5ce5f33bd6)

SSH手动执行opkg update报错：
![SSH执行opkg update报错](https://github.com/user-attachments/assets/79bf070b-8d7d-441d-96d9-129993d8ae2d)

软件包功能里点击更新列表报错：
![软件包页面点击更新列表报错](https://github.com/user-attachments/assets/1b996f51-031b-4f08-bc3e-4a6c3f17286e)

**Comment by 1JI0O** [comment]
我也遇到这个问题，环境相同，报错相同

**Comment by myweihp** [comment]
遇到同样问题+1

**Comment by mcbianxiao** [comment]
遇到同样问题+1

**Comment by lilu0826** [comment]
+1

**Comment by t2wei** [comment]
遇到同样问题+1, 工控机J1900, PVE, iStoreOS 版本相同

**Comment by solar020** [comment]
同样的问题，任何软件都安装不进

**Comment by HotMaker** [comment]
一模一样问题

**Comment by bcseputetto** [comment]
https://github.com/bcseputetto/Are-u-ok/issues/23

**Comment by Derek-Aaron** [comment]
也是同样的问题，手动上传包也不行的
![image](https://github.com/user-attachments/assets/93689bb8-a57d-420f-8b40-c15ecda0a213)

**Comment by WvvvWv** [comment]
> [bcseputetto/Are-u-ok#23](https://github.com/bcseputetto/Are-u-ok/issues/23)

@bcseputetto 多谢，问题已解决

**Comment by weisonglin8** [comment]
我也是同样的问题
