### ISSUE TITLE
Docker迁移，提示错误 “网络异常:504GatewayTimeout”

### ISSUE THREAD

**Issue by abao-chen** [istoreos/istoreos#1901]
### (1) 具体问题

A：Docker迁移，提示错误 “网络异常:504GatewayTimeout”

### (2) 路由器型号和固件版本

A：x86平台，固件版本：iStoreOS 22.03.6

### (3) 详细日志和/或截图

A：
![8355704d3b4daefccdb68f3c69a817f](https://github.com/user-attachments/assets/5079a2e4-5d1a-4026-8498-fe607fa21d3c)

**Comment by abao-chen** [comment]
已解决，原因是docker数据过大迁移时间超过了nginx默认的时长，重新设置nginx超时时长即可

**Comment by neochou** [comment]
怎么设置nginx的超时时长呀

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1983/1
