### ISSUE TITLE
x86主机无显示器接口怎么刷固件

### ISSUE THREAD

**Issue by XYZ-bear** [istoreos/istoreos#1910]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
我的x86主机没有外接显示器接口，官方文档只提供了插u盘接显示器的方法，我这种情况可以怎么刷机呢？

**Comment by gzsdbb** [comment]
方法有很多 比里拆硬盘

**Comment by XYZ-bear** [comment]
你好 还有其它办法吗 目前手上没有硬盘转usb的工具

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1974/1
