### ISSUE TITLE
软件源换 apk 了

### ISSUE THREAD

**Issue by HBat11233** [istoreos/istoreos#1914]
https://github.com/coolsnowwolf/lede/issues/13000

**Comment by fejeIaqbhbv** [comment]
目前和istoreos无关，lean大用的snapshot软件源，istore用的stable软件源

**Comment by jjm2473** [comment]
lean的软件仓库本来就混用版本，现在openwrt那边的snapshot版本切换到apk了，自然出问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1972/1
