### ISSUE TITLE
开机一段时间后硬盘进不去

### ISSUE THREAD

**Issue by github180556** [istoreos/istoreos#1957]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
docker运行了adguard和HA，usb易驱线接硬盘开启samba共享，开机一段时间是正常的，再过一会就看不到磁盘信息和docker信息了，samba也进不去了，但是HA使用正常。系统里面的重启后，管理界面登录不进去。只能拔电重启。是不是性能不够？还是硬盘问题？
### (1) 具体问题

A：

### (2) 路由器型号和固件版本
J1800 2G 物理机，iStoreOS 22.03.7 2024102509
A：

### (3) 详细日志和/或截图

A：

**Comment by github180556** [comment]
关闭了主板usb2 link power management，换了带电源供电的易驱线和3.5寸硬盘，现在不掉了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1955/1
