### ISSUE TITLE
docker容器dns问题求解惑

### ISSUE THREAD

**Issue by wcbspp** [istoreos/istoreos#1959]
同样的桥接模式的容器有的就显示172.0.0.1，有的显示- 
也抓不到该容器访问53端口。求解这是怎么回事儿。
![image](https://github.com/user-attachments/assets/c801dd2c-a65c-499b-b031-cf90da2128b8)
![image](https://github.com/user-attachments/assets/40c63197-14a9-4863-88d6-47aa0f41223b)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1953/1
