### ISSUE TITLE
【再次发生】从国外无法访问istore商店

### ISSUE THREAD

**Issue by Vash90** [istoreos/istoreos#1961]
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue
有，但是问题没有解决
## 2. 详细叙述
地点日本，istore商店 完全加载不出来
### (1) 具体问题

ping不通
istore.linkease.com
istore.istoreos.com
![image](https://github.com/user-attachments/assets/993209ef-82e8-4d89-85ef-61c726490390)

**Comment by ReijiAkaba** [comment]
同样，日本ip无法访问istore

**Comment by gohkh0825** [comment]
马来西亚IP也没有办法访问

**Comment by Vash90** [comment]
B站的官方账户，在评论里回复了下。
还是服务器的问题，他们服务器的运营商把所有海外ip都给禁止了。

**Comment by badboyman** [comment]
同样ping不通，无法访问istore商店

**Comment by ZPC00** [comment]
截止目前仍然不通

**Comment by ReijiAkaba** [comment]
好像能ping通了现在

**Comment by jjm2473** [comment]
已经换ip了，国外会解析到新ip

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1952/1
