### ISSUE TITLE
一个大容量硬盘分区怎么只能挂载一部分容量

### ISSUE THREAD

**Issue by Nuo-Mituan** [istoreos/istoreos#1962]
系统版本    iStoreOS 22.03.7 2024120615
设备型号    BROUNION R86S
如题我的2tb的nvme硬盘挂载只能挂载1.31tb，剩下的空间完全无法挂载使用
另一个usb硬盘也是如此，无法挂载全部硬盘空间，但是首页显示的却是全部硬盘空间，硬盘无任何问题
具体如下图
![3](https://github.com/user-attachments/assets/ab6a4b4f-26e4-4fbe-944f-15da15da5e99)
![4](https://github.com/user-attachments/assets/206ca8da-6a69-44f4-810c-b1d311533f1f)
![1](https://github.com/user-attachments/assets/600ef088-3bb2-4d12-aa8c-1364a9032546)
![2](https://github.com/user-attachments/assets/64ba80dd-7b09-4097-8f48-e7739afcd27b)

**Comment by Nuo-Mituan** [comment]
最近存不进东西了我进去看挂载项才发现有这个问题

**Comment by Nuo-Mituan** [comment]
root@iStoreOS:~# fdisk -l
Disk /dev/nvme0n1: 1.86 TiB, 2048408248320 bytes, 4000797360 sectors
Disk model: UncertainTruth Basic Pro
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: D1DFCA8E-847A-4E1C-B569-8B1158C31FE9

Device         Start        End    Sectors  Size Type
/dev/nvme0n1p1  2048 4000797326 4000795279  1.9T Microsoft basic data


Disk /dev/mmcblk0: 116.48 GiB, 125074145280 bytes, 244285440 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 9156DE9D-0090-48B3-0AB2-A033FC70C900

Device            Start       End   Sectors   Size Type
/dev/mmcblk0p1      512    262655    262144   128M EFI System
/dev/mmcblk0p2   263168    787455    524288   256M Microsoft basic data
/dev/mmcblk0p3   787968  11273757  10485790     5G Microsoft basic data
/dev/mmcblk0p4 11274240 244283392 233009153 111.1G Linux filesystem


Disk /dev/sda: 1.46 TiB, 1600321314304 bytes, 3125627567 sectors
Disk model: Expansion
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: D1DFCA8E-847A-4E1C-B569-8B1158C31FE9

Device     Start        End    Sectors  Size Type
/dev/sda1   2048 3125627533 3125625486  1.5T Microsoft basic data

**Comment by Nuo-Mituan** [comment]
通过resize2fs扩容了，此贴终结

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1951/1
