### ISSUE TITLE
机器J4125+I226V，最近换了个2.5G猫发现两个网口协商是2500M但是测速有问题（光猫桥接）

### ISSUE THREAD

**Issue by One-Piece-Y** [istoreos/istoreos#1971]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
机器J4125+I226V，最近换了个2.5G猫发现两个网口协商是2500M但是测速有问题（光猫桥接）：
1、猫2.5G口连接软路由2.5G口（eth0），1000M下行测速只有五六百兆
2、猫千兆口连接软路由2.5G口（eth0），1000M下行测速900+兆跑满
3、猫2.5G口连接PC（Win11）2.5G口，1000M下行测速1200+兆跑满
想请教大家该如何解决！现在这里感谢大家！
A：

### (2) 路由器型号和固件版本
型号：CncTion J4125-4L
架构 ：Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
目标平台：x86/64
固件版本：iStoreOS 22.03.7 2024120615 / LuCI istoreos-22.03 branch git-24.339.46321-5f9267c
内核版本：5.10.221
A：

### (3) 详细日志和/或截图

A：

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1946/1
