### ISSUE TITLE
[求助]误删除了R5S的所有网络接口，目前无法连接进系统内

### ISSUE THREAD

**Issue by ComicAuthor** [istoreos/istoreos#1973]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：误删除了R5S的所有网络接口，在恩山上看到使用hdmi接显示屏后终端清除网口设置。但实际上只有一个光标在闪动，无法使用键盘输入内容。 请问现在这个情况下有什么好办法可以救砖。不太想重刷系统。感谢好心人。

### (3) 详细日志和/或截图

A：

**Comment by ComicAuthor** [comment]
已刷机

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1945/1
