### ISSUE TITLE
无法使用hy2协议梯子

### ISSUE THREAD

**Issue by wuruoshui** [istoreos/istoreos#1979]
我使用vps搭建了一个梯子，但在使用过程中发现我的hysteria2协议的节点在连接istoreOS路由时出现无法连接的情况，切换到流量数据可以正常连接，但vmess和vless协议的节点梯子在连接istoreOS时不受影响可以正常使用，我只要重启istore路由器就可以连接hy2协议的节点，但是过段时间又不可以连接了
设备为倍控n100工控机
[Powered by LuCI istoreos-22.03 branch (git-24.339.46321-5f9267c)](https://github.com/openwrt/luci) / [ArgonTheme v2.2.10.10](https://github.com/jerrykuku/luci-theme-argon) / iStoreOS 22.03.7 2024120615
![屏幕截图 2024-12-13 210825](https://github.com/user-attachments/assets/af740834-93c5-4de9-998b-f2f4bcd6d908)

**Comment by jjm2473** [comment]
如果不是ipv6节点，一般都是运营商或者GFW屏蔽了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1942/1
