### ISSUE TITLE
Asia/Shanghai 时间并不是东八区时间。

### ISSUE THREAD

**Issue by wcbspp** [istoreos/istoreos#1990]
目前系统里设置的时间Asia/Shanghai并没有正确显示东八区时间，好像opwenwrt老问题了吧？
![image](https://github.com/user-attachments/assets/275badac-9f94-4a82-9a73-88e0bff3c41f)
![image](https://github.com/user-attachments/assets/4952f990-779f-4fe3-912d-2e34553e79e4)

**Comment by wcbspp** [comment]
opkg install zoneinfo-asia 重启之后也没有效果 好像之前版本没有这问题

**Comment by wcbspp** [comment]
![image](https://github.com/user-attachments/assets/895167c5-31e7-4f6c-8211-f41f3218714b)

**Comment by jjm2473** [comment]
点一下“与NTP服务器同步”试试

**Comment by wcbspp** [comment]
> 点一下“与NTP服务器同步”试试

![image](https://github.com/user-attachments/assets/c52cc68b-efec-4872-8552-073fb1f0c4d5)
没什么效果

**Comment by wcbspp** [comment]
> 点一下“与NTP服务器同步”试试

![image](https://github.com/user-attachments/assets/d04ed63f-1c0b-4200-854c-1dad26ae26f3)
没效果~

**Comment by bcseputetto** [comment]
@wcbspp 修改系统，时间同步，里面的候选ntp服务器
`ntp.aliyun.com`
`ntp1.aliyun.com`
`ntp2.aliyun.com`
`ntp3.aliyun.com`
`ntp4.aliyun.com`
`ntp5.aliyun.com`
然后再试试

**Comment by wcbspp** [comment]
> ntp1.aliyun.com
![image](https://github.com/user-attachments/assets/723f35a7-8652-469f-991d-8699907f25a2)
![image](https://github.com/user-attachments/assets/64257d75-e665-4e23-a731-7bb89d498305)
换了阿里的也不行呢.....

**Comment by bcseputetto** [comment]
@wcbspp 终端里面执行
```console
date
```
截图看下

**Comment by wcbspp** [comment]
> @wcbspp 终端里面执行
> 
> ```
> date
> ```
> 
> 截图看下

![image](https://github.com/user-attachments/assets/7b9ed96b-c921-4acf-b86b-e91053d4011b)
看起来走的是utc时间，设置里换成etc/GMT-8可以正常显示时间，但是各种插件的日志时间会有问题。

**Comment by bcseputetto** [comment]
@wcbspp 执行下面命令，截图执行结果
```
cat /etc/config/system
ls -l /etc
ls /usr/share/zoneinfo/Asia/
cat /etc/localtime
```

**Comment by wcbspp** [comment]
> @wcbspp 执行下面命令，截图执行结果
> 
> ```
> cat /etc/config/system
> ls -l /etc
> ls /usr/share/zoneinfo/Asia/
> cat /etc/localtime
> ```

![image](https://github.com/user-attachments/assets/235d275a-9685-4cf1-8282-3e102ce0d15e)
![image](https://github.com/user-attachments/assets/c4af2700-08e0-4739-a5a2-aee13359fa56)
![image](https://github.com/user-attachments/assets/fd8745e6-0c46-431d-b663-a4fbbe21bb1d)
/etc/localtime这个不存在

**Comment by bcseputetto** [comment]
@wcbspp 执行
```
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
```
然后重启一下系统，再看下某些插件的时间

**Comment by wcbspp** [comment]
> ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
还是不得行
![image](https://github.com/user-attachments/assets/388a70a9-f77f-48a5-826d-364e2d2f3e44)
![image](https://github.com/user-attachments/assets/b68e83e4-af84-43dd-ae8a-8ae21236b8e5)
![image](https://github.com/user-attachments/assets/f2d46911-4311-4d01-92b7-44bba9a06571)
![image](https://github.com/user-attachments/assets/4b20a47a-5fd1-4392-8441-7b3fcd9e4fb9)

**Comment by bcseputetto** [comment]
你这是重启后时间又变回去了？

**Comment by bcseputetto** [comment]
@wcbspp 执行
```
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci commit system
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
/etc/init.d/system reload
```
执行完这些不重启，看一下系统时间和插件时间

**Comment by wcbspp** [comment]
> @wcbspp 执行
> 
> ```
> uci set system.@system[0].zonename='Asia/Shanghai'
> uci set system.@system[0].timezone='CST-8'
> uci commit system
> ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
> /etc/init.d/system reload
> ```
> 
> 执行完这些不重启，看一下系统时间和插件时间
额
![image](https://github.com/user-attachments/assets/82826f67-fd63-462c-87df-b10cbe8c676f)

**Comment by bcseputetto** [comment]
@wcbspp 你有升级过软件包吗？去用系统便利工具先修复一下系统软件看看

**Comment by wcbspp** [comment]
> @wcbspp 你有升级过软件包吗？去用系统便利工具先修复一下系统软件看看

系统是上周重新装的最新版本，刚修复了一下，重启后还是没有变化

**Comment by 138161** [comment]
我装了chrony
#增加的源
pool 2.centos.pool.ntp.org iburst
pool ntp.aliyun.com iburst
pool 0.cn.pool.ntp.org iburst
pool 1.cn.pool.ntp.org iburst
pool 2.cn.pool.ntp.org iburst
pool 3.cn.pool.ntp.org iburst
pool 0.europe.pool.ntp.org iburst
再也没有烦恼过

**Comment by wcbspp** [comment]
> ntp.aliyun.com
应该不是一个问题
我这里时间服务器本身没问题 时区不正常

**Comment by wcbspp** [comment]
> @wcbspp 执行下面命令，截图执行结果
> 
> ```
> cat /etc/config/system
> ls -l /etc
> ls /usr/share/zoneinfo/Asia/
> cat /etc/localtime
> ```

问题已经解决。
/etc/localtime文件问题  rm后重新关联 ln -sf /usr/share/zoneinfo/Asia/Shanghai即可。
也非常感谢您了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1935/1
