### ISSUE TITLE
浮动网关在旁路由时，主路由的端口转发失效

### ISSUE THREAD

**Issue by KevinZjYang** [istoreos/istoreos#1998]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：我控制变量测试过：
前提：主路由设置端口转发。比如30022 - 30022 ，lucky监听30022端口进行反代。为了控制变量lucky安装在其他设备上。主路由、旁路由均可正常上网。
1、当浮动网关在主路由时，可以正常通过域名访问。
2、当浮动网关在旁路由时，无法正常访问。

### (2) 路由器型号和固件版本

A：R1 + R68S 均为最新版本

### (3) 详细日志和/或截图

A：

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1931/1
