### ISSUE TITLE
NUC6CAYH的Intel® Dual Band Wireless-AC 3168驱动

### ISSUE THREAD

**Issue by hwd2024** [istoreos/istoreos#2017]
NUC6CAYH安装了istoreos，但是它的Intel® Dual Band Wireless-AC 3168没有用，请问要怎么安装驱动让它起作用呢？

**Comment by hwd2024** [comment]
驱动我自己已经搞定了！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/1921/1
