### ISSUE TITLE
系统日志一直报 daemon.warn dnsmasq[11819]: failed to create listening socket 

### ISSUE THREAD

**Issue by longaga** [istoreos/istoreos#204]
![W`_U30M UX0MXYRM%1G6{U7](https://user-images.githubusercontent.com/25930270/172341138-9a654177-c58c-4697-ad88-dd86ebd9039a.png)

单线双拨，好像是最近几个版本一直出现，每隔一段时间报错，字面意思就ipv6网关地址不可用？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3448/1
