### ISSUE TITLE
能否支持R2C呢？

### ISSUE THREAD

**Issue by mmdh123** [istoreos/istoreos#210]
目前R2C的用户也增长了很多，期待尽快支持R2C，谢谢

**Comment by mynameisalice** [comment]
帮顶，R2C存量用户还是蛮多的。

**Comment by krkrchan** [comment]
同问，希望开发者能支持一下卑微的R2C用户啦。貌似R2C与R2S就是网卡不同，应该改一下网卡驱动就好了。

R2C 参数信息在这里： http://www.friendlyelec.com.cn/nanopi-R2C.asp

感谢开发者！

**Comment by jannson** [comment]
收到。

**Comment by jjm2473** [comment]
已集成驱动

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3439/1
