### ISSUE TITLE
8156B usb 网卡，奇怪问题，可以获取IP，但不能上网

### ISSUE THREAD

**Issue by yahochina** [istoreos/istoreos#211]
![微信图片_20220612134110](https://user-images.githubusercontent.com/39253130/173217425-e2be1cc1-100e-44c9-bcdf-cde76eb9fdcb.png)

获取IP信息都正确，但就是PING不通网关，上不了网。重置路由，刷了几个版本，都是一样的问题，换ISTOREOS之前的OPENWRT是正常可以用的。

**Comment by ChaosHeadNo** [comment]
相同的问题，设备是x86的j4125。

lsusb能够发现相应网卡，ethtool无法进行设置速率、重置等操作。

可以在网口管理中找到相应网口，连接网线后没有协商速率。

更换千兆网卡正常

**Comment by jjm2473** [comment]
目前固件里面的驱动太老了，不支持 rtl8156，下个版本会更新驱动

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3438/1
