### ISSUE TITLE
使用群晖虚拟机安装固件时报以下错误并且不能正常开机

### ISSUE THREAD

**Issue by 502880166** [istoreos/istoreos#22]
![9973C090-8BBD-4DD7-99A1-125D8A157A33](https://user-images.githubusercontent.com/53418367/163744211-5740e705-660d-4f9d-8bc8-5d163d66c957.jpeg)

麻烦大佬您看看是哪里出了问题，谢谢了

**Comment by jannson** [comment]
目前还看不出来啥问题。。。

**Comment by 502880166** [comment]
> 目前还看不出来啥问题。。。

这就尬住了哈哈哈哈哈哈😂

**Comment by jannson** [comment]
上面 最后一行 docker 错误，感觉跟你的根目录磁盘有关系。
等后面再来跟你定位吧，现在还有一些其它更紧急的事情。。。

**Comment by 502880166** [comment]
> 上面 最后一行 docker 错误，感觉跟你的根目录磁盘有关系。
> 等后面再来跟你定位吧，现在还有一些其它更紧急的事情。。。

好的，大佬先忙紧急的

**Comment by pingshu** [comment]
同样的问题，虚拟机安装固件，第一次能进入但重启后报错误并且不能正常开机

**Comment by Roy2088** [comment]
同样的问题。环境：Intel E1000网卡，软件 Exsi6.7+Linux 64

**Comment by jsczlcmdk** [comment]
我的也是这样的问题

**Comment by jannson** [comment]
这个问题还无法重现。等我们进一步的消息

**Comment by jannson** [comment]
应该是跟文件系统找不到。用我们最新的版本试试。解决了！

**Comment by jjm2473** [comment]
这个日志是成功启动了啊，有啥问题？
