### ISSUE TITLE
你好。不支持虚拟机网卡么。。以后也没有支持的计划么

### ISSUE THREAD

**Issue by hanlin0323** [istoreos/istoreos#220]
esxi装了一个，vmxnet3不支持

**Comment by jannson** [comment]
好的，我来记录，会有支持的计划。。。

**Comment by CallMeR** [comment]
CONFIG_PACKAGE_kmod-vmxnet3=y

不是在编译时候加个这个就行了吗？

**Comment by yaoshuangshl** [comment]
我的没问题，ESXI6.7u3下的vmxnet3
![image](https://user-images.githubusercontent.com/42952682/174207799-cb05111d-b8a0-49f0-bdc9-8e7dc64eeec2.png)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3431/1
