### ISSUE TITLE
请问能否做个图形化界面 http禁用或重定向到https，然后有替换/上传证书的界面呢？现在网络安全还是需要跟上一些的哈

### ISSUE THREAD

**Issue by yaoshuangshl** [istoreos/istoreos#228]
如题~可以参考群晖的做法
![64bfb3d4e7516bac21ac3403827013e](https://user-images.githubusercontent.com/42952682/174213339-987c0977-ae54-493b-b569-8241eb5ed225.png)

**Comment by jannson** [comment]
感谢，跟你聊天，你就帮我把信息提交上来了。非常感谢，这个功能看起来跟 DDNS 是一起的，应该搞的。。。

**Comment by jannson** [comment]
要跟 let'encrypt 结合来做才是最佳实践。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3420/1
