### ISSUE TITLE
新增 R4S 1G 版本固件（4G 版本已经 OK）

### ISSUE THREAD

**Issue by jannson** [istoreos/istoreos#230]
https://doc.linkease.com/zh/guide/istoreos/install_r2s.html

**Comment by byteinfo** [comment]
R4S 4G 版本 无法重启的问题修复一下吧 @jannson

**Comment by jannson** [comment]
1G 内存问题已经修复！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3418/1
