### ISSUE TITLE
后台管理界面字体映射错误

### ISSUE THREAD

**Issue by akira304moto** [istoreos/istoreos#239]
Argon 主题下，默认西文字体是 Google Sans，在其他路由器固件上显示正确，但在 iStoreOS 中映射错误，似乎字体文件没有加载。在苹果设备上所有西文一律显示为苹方，看起来比较奇怪。Logo 所使用的 TypoGraphica 字体也是如此情况，被映射成宋体（Safari）或苹方（Edge）。希望可以排查一下，怀疑是字体文件没有被包含在固件内。

作为临时解决方案，我自己是在 /www/luci-static/argon/css/cascades.css 中修改了一些内容，在 --font-family-sans-serif 项最前面加上 `-apple-system,system-ui,BlinkMacSystemFont,`，调用苹果系统原生字体 San Francisco 显示，效果不错。另外出现 TypoGraphica 的地方，在其后面也作如此添加。

注意到首页网速监测图表右上角速度显示样式在 /www/luci-static/quickstart/style.css 中，需要单独修改。而图表内部光标悬置时出现的时间、速度信息不知道如何修改。

以下为更改前后效果对比：

# 首页

修改前

<img width="1014" alt="home-1" src="https://user-images.githubusercontent.com/22417867/174417028-949157db-0802-4127-a237-e930a50087d9.png">

修改后

<img width="1024" alt="home-2" src="https://user-images.githubusercontent.com/22417867/174417472-ae26001f-f9a1-42b0-874e-ac9b8164003c.png">

# 接口页

修改前

<img width="1013" alt="port-1" src="https://user-images.githubusercontent.com/22417867/174417057-5170b746-030e-4cd7-a8bf-095bac035829.png">

修改后

<i<img width="1025" alt="port-2" src="https://user-images.githubusercontent.com/22417867/174417473-0279669d-60de-4b98-9221-7d19cce666a8.png">

# 状态页

修改前

<img width="1013" alt="status-1" src="https://user-images.githubusercontent.com/22417867/174417032-391d26b0-7e92-4803-aac0-d4ed350b894c.png">

修改后

<img width="1024" alt="status-2" src="https://user-images.githubusercontent.com/22417867/174417474-925afdc3-1adc-49cd-9e55-750b4cbd17c3.png">

**Comment by jannson** [comment]
专业啊兄弟，我看不懂，我让我们工程师看看。

**Comment by jjm2473** [comment]
如果是argon主题的问题，可以去argon项目反馈

**Comment by akira304moto** [comment]
正文第一段已经说了“Argon 主题的Google Sans 在其他路由器固件上显示正确”，不是 Argon 主题的问题。所以才比较奇怪。

**Comment by jjm2473** [comment]
哦，我想起来了，是openwrt的css压缩工具的bug，会导致多个 `@font-face` 被删除到只剩一个，在Chrome上显示又没问题所以没关注。

相关bug的链接 https://github.com/openwrt/luci/issues/5067 https://github.com/openwrt/luci/issues/5755

我看看加上 `LUCI_MINIFY_CSS:=0` 能不能解决。

**Comment by jjm2473** [comment]
加上`LUCI_MINIFY_CSS:=0`就修复了。没发现网速监测图的样式有问题，估计之前已经修复了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3406/1
