### ISSUE TITLE
安装时会提示报错以及缺少i915/kbl_dmc_ver1_04.bin

### ISSUE THREAD

**Issue by sepli921** [istoreos/istoreos#241]
安装时会提示报错以及缺少i915/kbl_dmc_ver1_04.bin

**Comment by sepli921** [comment]
x86版本

**Comment by jjm2473** [comment]
安装应该修复了，报错可能是因为overlay挂载失败？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3403/1
