### ISSUE TITLE
能连上OpenVPN 服务器，并访问内网设备，但不能上外网

### ISSUE THREAD

**Issue by tommytianhm** [istoreos/istoreos#243]
如题

**Comment by jjm2473** [comment]
一般都是路由配置问题，检查：
1. openvpn客户端的网关是不是对端的ip？
2. openvpn服务端是否开启了ip forwarding？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3400/1
