### ISSUE TITLE
能支持无线网卡吗？

### ISSUE THREAD

**Issue by donedonefly** [istoreos/istoreos#251]

**Comment by jannson** [comment]
应该有一些无线网卡驱动，但是我们的 UI 没直接支持。估计得你来手动安装无线的 luci 就行吧。。。
我们到没试过。。。

**Comment by szseer** [comment]
我也是无线网卡问题，插了两个无线网卡都没识别，不懂怎么解决啊。

**Comment by qmqsu** [comment]
> 应该有一些无线网卡驱动，但是我们的 UI 没直接支持。估计得你来手动安装无线的 luci 就行吧。。。
> 
> 我们到没试过。。。

支持AX201无线网卡驱动吗

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3392/1
