### ISSUE TITLE
夏天来了，希望增加R4S的风扇脚本

### ISSUE THREAD

**Issue by fk3166** [istoreos/istoreos#271]
首先感谢小宝带来的固件，非常好用，希望新版固件更新里面增加风扇的脚本，比较夏天到了，在弱电箱里跑，运行docker后温度更加吓人了，再次感谢

**Comment by w9315273** [comment]
密封环境 风扇再快也是内循环 我觉得还是要先改善环境

**Comment by luogujun** [comment]
我的也有风扇也不转，希望添加该脚本。

**Comment by jjm2473** [comment]
新固件增加了风扇配置

**Comment by fk3166** [comment]
请问是最新的3.10的版本已经集成了吗，在哪里打开，没有看到相应的选项发自我的 iPhone在 2023年3月17日，14:42，练亮斌 ***@***.***> 写道：﻿
Closed #271 as completed.

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3366/1
