### ISSUE TITLE
计划任务crontab没有执行，反馈err

### ISSUE THREAD

**Issue by Leong003** [istoreos/istoreos#285]
设备r2s，只运行openclash和docker cups，设置重启任务和openclash订阅更新，均无法执行，甚至是ssh登陆reboot指令也无法运行，必须通过reboot -f来强制重启。

Tue Jul  5 00:26:26 2022 cron.err crond[27727]: crond (busybox 1.33.2) started, log level 5

**Comment by jannson** [comment]
收到。
