### ISSUE TITLE
【新功能】支持快速的进行网口设置，修改 LAN/WAN 口

### ISSUE THREAD

**Issue by jannson** [istoreos/istoreos#288]

**Comment by duojie-sys** [comment]
R5S设置旁路由后更改了IP地址，和主路由同一网段，然后重启就再也进不去路由管理页面，不知什么原因。

**Comment by jannson** [comment]
断电重启下试试？是不是路由器死掉了，没重启成功？

**Comment by jannson** [comment]
新插件已经上线

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3342/1
