### ISSUE TITLE
增加上网时间控制、app上网控制、PPTP功能

### ISSUE THREAD

**Issue by zzxysun** [istoreos/istoreos#289]
固件里没有上网时间控制、app上网控制等网络控制功能的应用和插件，建议增加上去。另外，在安装PPTPD的时候，提示找不到kmod-gre和kmod-mppe依赖，能不能提前把这些功能提前打包进固件里。

**Comment by jannson** [comment]
PPTPD 感觉有点过时了，网时间控制、app上网控制后期加上！

**Comment by cnfjice** [comment]
[上网时间控制luci-app-accesscontrol_1-11_all.zip](https://github.com/linkease/istoreos/files/9075874/luci-app-accesscontrol_1-11_all.zip)
用这个吧，我已经用好久了。。。软件包那里安装即可。

**Comment by zzxysun** [comment]
我知道pptp过时了，只是我的国产操作系统只支持pptp，没有办法呀！！！

**Comment by jjm2473** [comment]
已集成

**Comment by jjm2473** [comment]
上网时间控制 可在 istore 安装

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3341/1
