### ISSUE TITLE
r5s固件能增加wireguard内核模块么？

### ISSUE THREAD

**Issue by chainone** [istoreos/istoreos#290]
当前没有kmod-wireguard, 无法使用wireguard, 能否帮忙加进去？

**Comment by jannson** [comment]
等我们合并一波代码，调整下来搞起。

**Comment by chainone** [comment]
感谢感谢！我试了一波所有的R5S的固件，没有一个能把wireguard跑起来的，就靠你了 @jannson

**Comment by jannson** [comment]
好吧。。。等我们继续移植 R5S

**Comment by jjm2473** [comment]
已集成

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3340/1
