### ISSUE TITLE
AMD CPU没有温度和IPV6获取但是不能上网下个版本能更新吗？

### ISSUE THREAD

**Issue by terryzung** [istoreos/istoreos#295]
AMD CPU没有温度显示和IPV6可以获取但是不能上网下个版本能更新吗？

**Comment by jannson** [comment]
部分 AMD CPU 确实没温度，原因也是因为我们没有机器无法测试。
IPv6 这个问题我们暂时不知道。估计都往后放吧。。。
CPU 温度可以来群里找我或者相关人，可以远程我们用 SSH 看看，修复起来很容易

**Comment by terryzung** [comment]
我的cpu是AMD GX-420CA，之前有个版本显示过，后来升级就没有了！群在线时间一般什么时候？

**Comment by schnuffell** [comment]
> 部分AMD CPU确实没温度，原因也是因为我们没有机器 测试 。看看，修复起来很容易

查看了一下JS  头有点大  如果用调用 sensors里面结果的话  应该会好一些吧 这样就不太容易因为CPU型号不显示

**Comment by jjm2473** [comment]
ipv6的问题可能只是因为默认禁止ipv6 dns解析，在“DHCP/DNS”的高级设置里可以关闭此功能，第一个选项就是。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3337/1
