### ISSUE TITLE
网络接口状态不显示接口

### ISSUE THREAD

**Issue by yingjun** [istoreos/istoreos#299]
![image](https://user-images.githubusercontent.com/1521269/178643809-bde1de33-0795-4a15-96c5-f1e42a24f6bd.png)

**Comment by jannson** [comment]
请问 7月15号的版本这个 OK 了么？

**Comment by yingjun** [comment]
> 请问 7月15号的版本这个 OK 了么？

没有，刚刚更新，还是一样，空白。而且已经清空了浏览器缓存。敢试了其它浏览器的隐私模式。还是空白

**Comment by lolikyo** [comment]
我也出现了这个问题

**Comment by jjm2473** [comment]
1. 换个浏览器试试
2. 恢复出厂设置试试

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3333/1
