### ISSUE TITLE
i225-v网卡只有第一个LAN口可用

### ISSUE THREAD

**Issue by expliyh** [istoreos/istoreos#307]
在其它地方看到openwrt固件版本5.10以上没有这个问题，希望能尽快升级

**Comment by jannson** [comment]
之前我们修复锅这个问题的。。。并且我们的机器貌似都 OK 的。估计需要远程定位下你的硬件才行。

**Comment by expliyh** [comment]
破案了，是Windows的锅，不用虚拟交换机改成直通就好了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3328/1
