### ISSUE TITLE
不小心删除了那个能控制一段时间会话过期插件里的账号密码，现在登录后台显示无效的用户名/密码，有什么解决办法吗？

### ISSUE THREAD

**Issue by wangzy123456** [istoreos/istoreos#308]
用初始账号密码和修改过的账号密码都试过了，都不行，重启过再试还是不行。

**Comment by jannson** [comment]
截图吧，我感觉没听懂你说得。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3327/1
