### ISSUE TITLE
J4125的用Esxi虚拟机安装iStoreOS后用在线更新功能后进不去系统

### ISSUE THREAD

**Issue by a79419042** [istoreos/istoreos#311]
J4125的用Esxi虚拟机安装iStoreOS后用在线更新功能后进不去系统
提示出现这些代码
![image](https://user-images.githubusercontent.com/106438358/179431278-deac9193-2465-44a5-8544-d7a3b2d55f00.png)

**Comment by w9315273** [comment]
为什么不用硬盘镜像的方式安装啊 省好多麻烦的

**Comment by jjm2473** [comment]
现在应该已经没问题了，没修之前其实按回车也能进。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3324/1
