### ISSUE TITLE
i225 V3网卡无法识别

### ISSUE THREAD

**Issue by ryanxu36** [istoreos/istoreos#314]
5.15内核的固件支持i225 V3网卡了，iStoreOS最新版固件安装完后无法识别网卡，给不出IP，请问下一版固件会支持吗？

**Comment by zzmalone** [comment]
同问，我的也是在等待更新升级

**Comment by molin830** [comment]
现在是不支持i226网卡

**Comment by kulajj77** [comment]
现在支持i226网卡了吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3321/1
