### ISSUE TITLE
x86主界面启动内网测试失败

### ISSUE THREAD

**Issue by songgang2008** [istoreos/istoreos#316]
This repository is a mirror of our main repo at https://git.openwrt.org/openwrt/openwrt.git
It is for reference only and is not active for checkins or for reporting issues.

All issues should be reported at: https://bugs.openwrt.org

Please do not open any NEW issue here - we will be closing the Github issues
capability in the near future.

We will continue to accept Pull Requests here as described in the repo description.

Close this now and click here: https://bugs.openwrt.org

Thankyou for your co-operation.

> x86主界面启动内网测试失败。如图。在istore插件里启动正常。

**Comment by jannson** [comment]
收到。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3319/1
