### ISSUE TITLE
Compile ARS2 Issue

### ISSUE THREAD

**Issue by leenchan** [istoreos/istoreos#319]
ARS2 没法编译，卡在 toolchain 的编译，好像没有下载到内核

**Comment by jjm2473** [comment]
ARS2的内核不是openwrt官方支持的版本，需要使用外部的linux代码库，目前ARS2的内核未开源，可以使用香蕉派释出的同方案的内核源码 https://github.com/BPI-SINOVOIP/BPI-W2-bsp/tree/rtk1296_ow/linux-rtk

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3316/1
