### ISSUE TITLE
软路由作为旁路由，怎么设置让智能家居不走旁路由。

### ISSUE THREAD

**Issue by My-By** [istoreos/istoreos#321]
主路由拨号，旁路由ISOS，主路由网关不指向旁路由，为什么家里的智能家居的网段会显示到旁路由的路由表里，以前别的系统并不会这样，导致当路由温度都飙到老高了，如何让未指向旁路由的设备不走旁路由的流量。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3314/1
