### ISSUE TITLE
0423版本修改lan口ip重启后就失效了

### ISSUE THREAD

**Issue by Trumpgodie** [istoreos/istoreos#325]
试过修改/etc/config/network文件
quickstart命令修改
进入后台通过引导修改lanIP三种方式
重启以后都失效了。ip还是默认的192.168.100.1

后面的版本有没有修改？

**Comment by jannson** [comment]
你估计下载太老的版本了，下载的地方越后面是越新的。0423 得多老了。请用最新版本测试。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3310/1
