### ISSUE TITLE
可以增加上网行为管理吗？放假了，神兽管不住

### ISSUE THREAD

**Issue by zzmalone** [istoreos/istoreos#326]
This repository is a mirror of our main repo at https://git.openwrt.org/openwrt/openwrt.git
It is for reference only and is not active for checkins or for reporting issues.

All issues should be reported at: https://bugs.openwrt.org

Please do not open any NEW issue here - we will be closing the Github issues
capability in the near future.

We will continue to accept Pull Requests here as described in the repo description.

Close this now and click here: https://bugs.openwrt.org

Thankyou for your co-operation.

**Comment by jannson** [comment]
在考虑集成一些开源的方案，我们还在内部测试。

**Comment by zzmalone** [comment]
谢谢啊，希望尽早上线。

**Comment by jjm2473** [comment]
oaf+网络管控就够用了吧，ars2上都用了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3309/1
