### ISSUE TITLE
X86固件 kernel版本不兼容 无法安装Wireguard

### ISSUE THREAD

**Issue by vodkafu** [istoreos/istoreos#327]
需要 = 5.4.179-1-57dcfbca1f3225678d24912f782b4e67 版本，已安装 5.4.179-1-c934a9b28630d2f8c92f9b84d17305e7
希望能在软件中心上一些相关组件
![Snipaste_2022-07-25_11-38-17](https://user-images.githubusercontent.com/44867336/180694329-19362431-d529-402f-8e5b-f62b1c0364b8.png)

**Comment by bcseputetto** [comment]
0715版本内核和官方的21.02.2的opkg源内核版本Hash不一致，导致无法安装各种kmod组件
0707版本还没有这个问题的
@jjm2473 @jannson

**Comment by vodkafu** [comment]
> 

好的 感谢厚米 我先刷回0707

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3308/1
