### ISSUE TITLE
0715版本内核问题

### ISSUE THREAD

**Issue by bcseputetto** [istoreos/istoreos#328]
0715版本内核和官方的21.02.2的opkg源内核版本vermagic不一致，导致无法安装各种kmod组件
0707版本还没有这个问题的
![2022070722_kernel](https://user-images.githubusercontent.com/29139573/181147523-1443287b-5e76-4a36-98d7-b67267b3db4a.png)
![2022071510_kernel](https://user-images.githubusercontent.com/29139573/181147530-85a03a74-2ad0-4dcd-81d7-d15802c5a135.png)
![21 02 2_kernel](https://user-images.githubusercontent.com/29139573/181147834-e7922374-8710-44ad-8d1f-631740af5a13.png)
![21 02 2_kernel2](https://user-images.githubusercontent.com/29139573/181147846-1008f0ab-ec91-4a03-9e91-4bbe787572ef.png)

**Comment by bcseputetto** [comment]
顺便 kmod-l2tp 安装有问题，尽管在0707版本下。
会一直卡在 Configuring kmod-l2tp
![opkg_kmod-l2tp](https://user-images.githubusercontent.com/29139573/181148120-929b6d9a-1bb1-4b08-a1a3-ece12abf7bf8.png)

**Comment by jannson** [comment]
这个问题下个版本修复！

**Comment by jannson** [comment]
修复了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3307/1
