### ISSUE TITLE
wireguard与设置成同一个防火墙区域后dhcp崩溃

### ISSUE THREAD

**Issue by le3pak** [istoreos/istoreos#331]
opkg update之后安装wireguard，
设置服务端口与对端端口完毕后，设置wireguard端口与lan端口为一个防火墙区域后，dhcp不能分配ip，lan直接崩溃不能ping通，通过重置才能解决。
如果可以的话，请开发者修复此问题。

**Comment by 666dechaoge** [comment]
> opkg update之后安装wireguard， 设置服务端口与对端端口完毕后，设置wireguard端口与lan端口为一个防火墙区域后，dhcp不能分配ip，lan直接崩溃不能ping通，通过重置才能解决。 如果可以的话，请开发者修复此问题。

大佬你解决了吗，用不了wireguard难受

**Comment by 666dechaoge** [comment]
> opkg update之后安装wireguard， 设置服务端口与对端端口完毕后，设置wireguard端口与lan端口为一个防火墙区域后，dhcp不能分配ip，lan直接崩溃不能ping通，通过重置才能解决。 如果可以的话，请开发者修复此问题。

不在同一个防火墙能用吗（我R2S只添加wireguard接口，什么都还没配就崩了。。。

**Comment by le3pak** [comment]
> > opkg update之后安装wireguard， 设置服务端口与对端端口完毕后，设置wireguard端口与lan端口为一个防火墙区域后，dhcp不能分配ip，lan直接崩溃不能ping通，通过重置才能解决。 如果可以的话，请开发者修复此问题。
> 
> 不在同一个防火墙能用吗（我R2S只添加wireguard接口，什么都还没配就崩了。。。

过去很久了，记得当时不在同一个防火墙，给wg端口新建的端口，也是崩溃不分配ip，多番试验无果。后面就把istoreOS弃了，用supes.top定制固件，目前使用稳定。

**Comment by jjm2473** [comment]
下个版本会集成wireguard驱动，看看能不能解决

**Comment by jjm2473** [comment]
升级最新固件，看看问题还存不存在，如果之前安装过wireguard驱动，先卸载掉再升级固件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3304/1
