### ISSUE TITLE
能否支持R4SE（R4S的EMMC版本）？

### ISSUE THREAD

**Issue by cuicuifeng** [istoreos/istoreos#334]
已经有R4S的EMMC版本了，不知道istoreos什么时候可以支持？

**Comment by jannson** [comment]
搞搞。但是得等等，最近要更新一个方便修改网口的功能

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3301/1
