### ISSUE TITLE
解决内核驱动签名问题。内核打算用官方的内核？还是IStoreOS维护一个带kmod的软件源

### ISSUE THREAD

**Issue by ziyaofeng** [istoreos/istoreos#335]
解决内核驱动签名问题。内核打算用官方的内核？还是IStoreOS维护一个带kmod的软件源

**Comment by jannson** [comment]
我们用官方的内核，不过这个 kmod 的错误，我们得看看。我们就是用官方 release 分支的内核，一模一样的。

**Comment by ziyaofeng** [comment]
内核version magic不一致，导致加载不了kmod。编译的时候生成的version magic跟官方不一样，没搞什么特殊的东西的话，可以拿官方的内核直接替换掉，kmod包都用官方的。或者把所有kmod包都编译一次，然后做一个软件源呗

**Comment by jjm2473** [comment]
内核version magic有patch方案，不过如果是自己编译固件，可以把大部分需要的模块都打包进固件，不会占用多少空间

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3300/1
