### ISSUE TITLE
多WAN情况下网心云使用哪条宽带的问题

### ISSUE THREAD

**Issue by flugel** [istoreos/istoreos#337]
多WAN负载均衡的情况下，网心云使用的WAN口不固定，IP直接显示为外网或上级路由IP，能否增加功能，选择使用特定的一个或者多个WAN口？

**Comment by jannson** [comment]
对的，这个是我们下一步来支持网心云的一个关键功能！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3299/1
