### ISSUE TITLE
最新版本，缺少kmod-nft-compat依赖，还请排查下！

### ISSUE THREAD

**Issue by LONG2252** [istoreos/istoreos#342]
包名：openwrt-21.02.1-2022042317-x86-64-generic-squashfs-combined.vmdk

缺少kmod-nft-compat，且无法安装，请排查下。

**Comment by jannson** [comment]
嗯。下个版本会修复。是内核的编译的问题。

**Comment by jannson** [comment]
修复了，内核可以自己安装相关的内核插件。

**Comment by MvCraK** [comment]
还是有问题kmod-nft-compat

**Comment by jcoseql** [comment]
25号还在的，昨天晚上kmod-nft-compat又跑了。

**Comment by LiangGuangzhou** [comment]
怎么自己解决啊？急用passwall

**Comment by jjm2473** [comment]
x86不是可以使用线上的源安装内核模块吗

**Comment by jjm2473** [comment]
你们用的软件源可能太新了，用这里的离线包吧 https://github.com/AUK9527/Are-u-ok/tree/main

**Comment by jjm2473** [comment]
kmod-nft-compat 至少在22.03以上版本才有的，所以以前不可能在固件里集成过，除非测试固件。要么使用测试固件，基于22.03，要么使用离线包

**Comment by jjm2473** [comment]
这个依赖根本就不需要，因为前面的依赖已经满足。

<img width="380" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/15de2caf-6066-4436-8ae2-008359528041">

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3293/1
