### ISSUE TITLE
麻烦更新一下unup功能，该功能处于基本不可用状态。

### ISSUE THREAD

**Issue by Martintep** [istoreos/istoreos#346]
就开了一个passwall，配置了一个iptv的桥接，什么软件都没装，unup处在薛定谔的猫状态，pc上的moonglight自动转发服务一堆端口几个能转发的，nas直接配置不了。

**Comment by jannson** [comment]
我们的 UPNPD 的版本很新，我们技术人员测试都说好的。我们自己开发的易有云产品也是能自动端口转啊的。如果要最稳定的版本，得退回到 2020 年的一个 UPNPD 的版本。目前还在纠结这个决定。。。
