### ISSUE TITLE
首页和网络向导 空白 无显示

### ISSUE THREAD

**Issue by 1064298219** [istoreos/istoreos#347]
![image](https://user-images.githubusercontent.com/75106198/185058168-521e59c2-2c13-4641-8b69-70210c66c207.png)
![image](https://user-images.githubusercontent.com/75106198/185058211-45bd8685-af69-4a7c-a7cb-584a6f7fb9fd.png)

**Comment by Carseason** [comment]
换个浏览器

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3289/1
