### ISSUE TITLE
能否启用 r4s GPU 来实现硬件解码

### ISSUE THREAD

**Issue by hakrei** [istoreos/istoreos#349]
希望能启用 R4S GPU 实现硬解，非常感谢

**Comment by jannson** [comment]
R4S 我们没精力支持。我们考虑支持 R5S ，目前 ARS2 已经支持！

**Comment by GreenTeodoro839** [comment]
> R4S 我们没精力支持。我们考虑支持 R5S ，目前 ARS2 已经支持！

看恩山上有帖子说gpu驱动的，lean版可以直接添加 
https://www.right.com.cn/forum/thread-4099256-1-1.html ，官方版打补丁后也可以 https://www.right.com.cn/forum/thread-5357320-1-1.html ，下个版本能不能加上gpu驱动试试，jellyfin就先让有需要的人自己折腾吧😀

**Comment by enjoyO** [comment]
@jannson  请问现在r5c和R5s的固件已经支持GPU硬件解码了吗

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3287/1
