### ISSUE TITLE
BCM578XX 2.5G支持

### ISSUE THREAD

**Issue by TalusL** [istoreos/istoreos#351]
希望iStoreOS增加 BCM578XX 2.5G支持 patchs可以参考 https://github.com/JAMESMTL/snippets/tree/master/bnx2x/patches

这个光纤网卡原本只支持1000M/10000M协商，但是可以通过配置支持2500M，需要patch驱动支持。很多路由固件如爱快、已经支持。现在很多人通过它配合2.5G猫棒 MA5671A G-010S-P  G-010S-A 等取代家庭光猫，节省位置的同时还能超越运营商光猫的性能限制，压榨运营商预留部分宽带。

**Comment by jannson** [comment]
感谢提供信息。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3284/1
