### ISSUE TITLE
按照到傲腾16G加速盘的话 无法正常启动

### ISSUE THREAD

**Issue by jwwsjlm** [istoreos/istoreos#353]
U盘的话正常启动 但是按照正常流程
输入quickstart 然后选择安装x86  只有一个nvme的傲腾盘..然后选择这个硬盘之后 正常安装 到最后有个321的倒计时 重启 这个时候拔掉U盘 然后正常启动的话 系统卡在USB界面

**Comment by yahochina** [comment]
我的软路由也用的16G傲腾NVME模式，启动完全无问题。

**Comment by jwwsjlm** [comment]
> 我的软路由也用的16G傲腾NVME模式，启动完全无问题。

设置了一下..好像DD的话 无法创建引导..必须进PE 用img写盘重刷..否则开机软路由无法引导到傲腾

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3282/1
