### ISSUE TITLE
samba 共享网盘读写速度只有2MB/S，请是哪里设置不对吗？

### ISSUE THREAD

**Issue by zhangjie135** [istoreos/istoreos#356]
This repository is a mirror of our main repo at https://git.openwrt.org/openwrt/openwrt.git
It is for reference only and is not active for checkins or for reporting issues.

All issues should be reported at: https://bugs.openwrt.org

Please do not open any NEW issue here - we will be closing the Github issues
capability in the near future.

We will continue to accept Pull Requests here as described in the repo description.

Close this now and click here: https://bugs.openwrt.org

Thankyou for your co-operation.

**Comment by jannson** [comment]
请说明下硬件配置，硬盘信息，以及是不是 NTFS，还是 EXT4 文件系统格式等。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3279/1
