### ISSUE TITLE
Intel-i226-V网卡驱动添加

### ISSUE THREAD

**Issue by dnpl** [istoreos/istoreos#357]
最新出的畅网第四版Intel-i226-V无法识别

**Comment by blankvip** [comment]
我也使用了，无法识别，不知道什么时候能添加

**Comment by Ethan1209** [comment]
mark一下，同样的问题

**Comment by dnpl** [comment]
看了一下源码，有226的驱动更新，只是没有编译进去，我自己编译了一下，还没有测试能否识别，先关闭issue了

**Comment by blankvip** [comment]
> 看了一下源码，有226的驱动更新，只是没有编译进去，我自己编译了一下，还没有测试能否识别，先关闭issue了

大佬，编译完可以用吗？

**Comment by dnpl** [comment]
> > 看了一下源码，有226的驱动更新，只是没有编译进去，我自己编译了一下，还没有测试能否识别，先关闭issue了
> 
> 大佬，编译完可以用吗？

已经编译完成，自己测试使用目前没有发现问题，可以使用源码编译一下

**Comment by blankvip** [comment]
> > > 看了一下源码，有226的驱动更新，只是没有编译进去，我自己编译了一下，还没有测试能否识别，先关闭issue了
> > 
> > 
> > 大佬，编译完可以用吗？
> 
> 已经编译完成，自己测试使用目前没有发现问题，可以使用源码编译一下

大佬，求共享固件，我不会编译，感谢。。。

**Comment by dnpl** [comment]
> > > > 看了一下源码，有226的驱动更新，只是没有编译进去，我自己编译了一下，还没有测试能否识别，先关闭issue了
> > > 
> > > 
> > > 大佬，编译完可以用吗？
> > 
> > 
> > 已经编译完成，自己测试使用目前没有发现问题，可以使用源码编译一下
> 
> 大佬，求共享固件，我不会编译，感谢。。。

留下q，有空发给你一下

**Comment by blankvip** [comment]
> > > > > 看了一下源码，有226的驱动更新，只是没有编译进去，我自己编译了一下，还没有测试能否识别，先关闭issue了
> > > > 
> > > > 
> > > > 大佬，编译完可以用吗？
> > > 
> > > 
> > > 已经编译完成，自己测试使用目前没有发现问题，可以使用源码编译一下
> > 
> > 
> > 大佬，求共享固件，我不会编译，感谢。。。
> 
> 留下q，有空发给你一下

q：626631052

**Comment by shen-lan** [comment]
现在最新版的还有这个问题吗 ？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3278/1
