### ISSUE TITLE
r5s这个固件能不能线刷emmc？

### ISSUE THREAD

**Issue by anycallmoo** [istoreos/istoreos#360]
r5s这个固件能不能线刷emmc？

**Comment by jannson** [comment]
当然是可以的，就是官方的 SDK 支持的，用官方提供的任何方式都是支持的。

**Comment by cjyy46** [comment]
> r5s这个固件能不能线刷emmc？

我也遇到同样问题 请问你解决了吗

**Comment by SyntaxSlinger** [comment]
现在还是不能线刷，希望解决下

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3275/1
