### ISSUE TITLE
商店的diskman插件安装失败

### ISSUE THREAD

**Issue by hwangjunjie** [istoreos/istoreos#362]
设备：R2S
iStore： v0.1.12-4
固件版本：OpenWrt 21.02.2 2022071511
软件源配置：清华大学
<img width="700" alt="image" src="https://user-images.githubusercontent.com/2819873/187100103-16fdf6b9-a709-44d5-a318-fa3064e89f05.png">

**Comment by jannson** [comment]
最新的应该 OK 了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3274/1
