### ISSUE TITLE
hyper-v 虚拟机安装，无法自动识别新的网口

### ISSUE THREAD

**Issue by qjj2857** [istoreos/istoreos#364]
安装虚拟机时，第一次启动，分配了几张网卡，则后续增减网卡都不会在ifconfig里显示

原版openwrt可以随便增减虚拟交换机

**Comment by jannson** [comment]
那可能你的虚拟网卡驱动，我们内核没得。等我们有空测试吧。缺少了驱动，我估计。

**Comment by jjm2473** [comment]
不是吧，哪有交换机，只是新的物理网口没有关联到逻辑网口而已。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3272/1
