### ISSUE TITLE
无法安装无线网卡驱动

### ISSUE THREAD

**Issue by ken0212** [istoreos/istoreos#365]
固件版本x86/64
OpenWrt 21.02.2 2022071510 / LuCI openwrt-21.02-cn branch git-22.186.32466-892d5d9
内核版本 | 5.4.179

无法安装rt2800这个无线网卡驱动，明明源和内核都是对得上了，无语了，大神看看啥情况呀？？？

**root@iStoreOS:~# opkg list |grep kmod-rt2**
kmod-rt2400-pci - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (RT2400 PCI)
kmod-rt2500-pci - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (RT2500 PCI)
kmod-rt2500-usb - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (RT2500 USB)
kmod-rt2800-lib - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (rt2800 LIB)
kmod-rt2800-mmio - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (RT28xx/RT3xxx MMIO)
kmod-rt2800-pci - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (RT2860 PCI)
kmod-rt2800-usb - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (RT2870 USB)
kmod-rt2x00-lib - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (LIB)
kmod-rt2x00-mmio - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (MMIO)
kmod-rt2x00-pci - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (PCI)
kmod-rt2x00-usb - 5.4.179+5.10.85-1-1 - Ralink Drivers for RT2x00 cards (USB)

**root@iStoreOS:~# opkg install kmod-rt2800-usb --force-depends**
Unknown package 'kmod-rt2800-usb'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.179-1-57dcfbca1f3225678d24912f782b4e67) for kmod-rt2x00-lib
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-rt2x00-lib found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.179-1-57dcfbca1f3225678d24912f782b4e67) for kmod-rt2x00-usb
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-rt2x00-usb found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.179-1-57dcfbca1f3225678d24912f782b4e67) for kmod-rt2800-lib
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-rt2800-lib found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.179-1-57dcfbca1f3225678d24912f782b4e67) for kmod-rt2800-usb
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-rt2800-usb found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-rt2800-usb.
root@iStoreOS:~# **opkg install kmod-rt2x00-usb --force-depends**
Unknown package 'kmod-rt2x00-usb'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.179-1-57dcfbca1f3225678d24912f782b4e67) for kmod-rt2x00-lib
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-rt2x00-lib found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.179-1-57dcfbca1f3225678d24912f782b4e67) for kmod-rt2x00-usb
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-rt2x00-usb found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-rt2x00-usb.
root@iStoreOS:~#

**Comment by jannson** [comment]
新版本修复了，请测试最新版本。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3271/1
