### ISSUE TITLE
R68S主页无法正确显示网口信息

### ISSUE THREAD

**Issue by Idealisten** [istoreos/istoreos#367]
问题描述：
istoreOS主页网络接口状态一栏，只有ETH0,1,3这三个接口，无法显示ETH2接口，即使我连接了ETH2也无法显示此接口（但是可以正常使用，仅是不显示）。检查LAN口配置信息，LAN口也已勾选ETH1,2,3三个接口。

固件版本
OpenWrt 21.02.1 2022061022
内核版本
4.19.219

**Comment by jjm2473** [comment]
实测可能已经修复，注意eth2可能在eth3后面

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3269/1
