### ISSUE TITLE
能否在下个版本加入kmod-nft-core关联的包

### ISSUE THREAD

**Issue by eddywei** [istoreos/istoreos#369]
部分功能需要 kmod-nft-core 支持，是否可以下个版本加入，。

**Comment by jannson** [comment]
现在新的版本，可以安装内核插件了，你可以自己从官方插件里面安装试试。

**Comment by eddywei** [comment]
好的，我再试试看，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "istoreos/istoreos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月22日(星期四) 下午5:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [istoreos/istoreos] 能否在下个版本加入kmod-nft-core关联的包 (Issue #369)





 
现在新的版本，可以安装内核插件了，你可以自己从官方插件里面安装试试。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3266/1

**Comment by eddywei** [comment]
这只是自动回复，请稍等，我会尽快正式回复您的邮件。谢谢！

**Comment by eddywei** [comment]
感谢帮助



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年10月9日(周四) 凌晨0:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 能否在下个版本加入kmod-nft-core关联的包 (Issue #369)


kc-bao left a comment (istoreos/istoreos#369)
 
此问题已在 酷友社 上被提及。那里可能有相关详细信息：
 
https://www.koolcenter.com/t/topic/3266/1
