### ISSUE TITLE
r5s分区不能格式化，希望能支持在线升级

### ISSUE THREAD

**Issue by mengxunlingxue** [istoreos/istoreos#370]
r5s考虑升级内核和增加在线升级吗
另外目前版本的，磁盘管理，不能格式化自带的8G空间的剩余部分，不能使用，如果操作，重启后会不能开机和使用

**Comment by mengxunlingxue** [comment]
测试/mnt/data_mmcblk0p6分区可以格式化，不影响使用
mmcblk0p3 mmcblk0p4不能格式化，否则会开不了机，建议完善

**Comment by CrawlerMonster** [comment]
同样的问题，希望大神帮忙完善

**Comment by jannson** [comment]
这个是基础功能，肯定会支持。我们还在慢慢移植。这个我就先关闭了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3265/1
