### ISSUE TITLE
更新软件中心后无法使用

### ISSUE THREAD

**Issue by onlyleolei** [istoreos/istoreos#371]
更新软件中心0.1.12-5后出现一个边框闪红的黑色窗体，里面字符是istore>#。
系统日志显示daemon.err procd: instance istore not found
点X无法关闭，也不能使用软件中心
可以退回到其他设置页面
已安装的插件目测运行正常。
貌似商店更新丢了.........
路由器是R4S

**Comment by jannson** [comment]
哦，目前貌似遇到几个这样的问题，等我们确认哈。

**Comment by onlyleolei** [comment]
新固件直接升级后问题依然存在，重刷固件后解决。推测不是单纯的商店丢了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3264/1
