### ISSUE TITLE
NAT端口回流的问题

### ISSUE THREAD

**Issue by ahmengkai** [istoreos/istoreos#374]
我是ESXI 7.0虚拟机安装的istoreos
每次公网IP变动后，局域网都没办法使用域名访问到内网架设的服务，比如机器上的虚拟群晖NAS  ，其他设备上的博客 导航页这些，但是用手机流量 以及 外部网络是可以打开这些的。
我需要手动打开istoreos后台，随便点一点，再过个几分钟就可以访问了。。。
每次都是这样，特别麻烦

**Comment by jannson** [comment]
还没确认此问题。我映像中我们都是修复了的，并且后台有个 配置选择，启用 NAT 回流。具体老忘记。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3261/1
