### ISSUE TITLE
R68s的固件里能不能把沙箱模式加进去？

### ISSUE THREAD

**Issue by rockyzhz** [istoreos/istoreos#375]
那个小机器经常被我玩到崩溃，可惜不能像PVE或者ESXi里一样，做个快照，崩溃了就直接一键回滚恢复了。。。

**Comment by jannson** [comment]
这个是肯定加进去的，基础功能，目前 R68S 还在慢慢移植中。挺多东西没完成的。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3260/1
