### ISSUE TITLE
istoreos更新9.16版本之后软件源一直报错 

### ISSUE THREAD

**Issue by lvyremix** [istoreos/istoreos#377]
![Uploading image.png…]()
软件源报错 配置里选择不了

**Comment by lvyremix** [comment]
![image](https://user-images.githubusercontent.com/25837327/190612756-feb13f57-bc28-4953-81a2-c113881b631a.png)

**Comment by longaga** [comment]
![9KDX7FY2 J}( $2 P{`@6`U](https://user-images.githubusercontent.com/25930270/190836130-484fa13c-dcaa-44ce-b640-9442f0f8219e.png)
无论设置什么源都提示错误。。9.16版本，之前是正常的

**Comment by NyaNyaXin** [comment]
遇到了相同的问题

**Comment by zeusfly** [comment]
一样的问题，但软件源是能正常切换

**Comment by paulyinghu** [comment]
一样的问题，但软件源是能正常切换

**Comment by molin830** [comment]
遇到了相同的问题

**Comment by 744129844** [comment]
遇到了相同的问题

**Comment by zdj8032** [comment]
一样的问题，但软件源是能正常切换

**Comment by lvyremix** [comment]
好像说明天更新修复 大家等等看吧

**Comment by jannson** [comment]
已经修复，你们继续更新版本就好了。

**Comment by zhouweisong** [comment]
> 

我已经安装了最新版 还是没有解决 istoreos-21.02.3-2022092414-x86-64-squashfs-combined-efi

**Comment by zhouweisong** [comment]
> 已经修复，你们继续更新版本就好了。

我已经安装了最新版 还是没有解决 istoreos-21.02.3-2022092414-x86-64-squashfs-combined-efi

**Comment by w2816771** [comment]
我也遇到了同样的问题

**Comment by Relax-87** [comment]
@jannson 22.03.5 2023090810 版本 仍然报错 软件源错误 无论切换那个都一样提示

**Comment by grock304** [comment]
为啥去年 9 月的问题，我今年 9 月遇到……是一到 9 月就好扯拐吗？

**Comment by Zhiyuan2024** [comment]
> 为啥去年 9 月的问题，我今年 9 月遇到……是一到 9 月就好扯拐吗？

一样 今天遇到了

**Comment by jzsmqss** [comment]
我用于pppoe拨号，一样的报错，现在是2023年12月12日了，还是修复不了吧？
（源是清华，固件版本iStoreOS 22.03.5 2023112413，内核版本5.10.176

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3259/1
