### ISSUE TITLE
在StoreOS 21.02.3 2022091615 版本中首页 网络连接状态一直显示检测中 

### ISSUE THREAD

**Issue by zzmalone** [istoreos/istoreos#379]

**Comment by zzmalone** [comment]
![image](https://user-images.githubusercontent.com/51351422/191180170-3e8171fd-0444-4f17-b233-026211cde4fe.png)

**Comment by jannson** [comment]
又发布了新版本，已经修复。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3257/1
