### ISSUE TITLE
在StoreOS 21.02.3 2022091615 版本中，首页点击内网测速，跳转到raid管理界面

### ISSUE THREAD

**Issue by zzmalone** [istoreos/istoreos#380]

**Comment by jannson** [comment]
确实这个问题还存在。。。唉，我才发布新版本。。。估计下个版本修复了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3256/1
