### ISSUE TITLE
第三方插件包的网址无法访问

### ISSUE THREAD

**Issue by szseer** [istoreos/istoreos#381]
This repository is a mirror of our main repo at https://git.openwrt.org/openwrt/openwrt.git
It is for reference only and is not active for checkins or for reporting issues.

All issues should be reported at: https://bugs.openwrt.org

Please do not open any NEW issue here - we will be closing the Github issues
capability in the near future.

We will continue to accept Pull Requests here as described in the repo description.

Close this now and click here: https://bugs.openwrt.org

Thankyou for your co-operation.

**Comment by jannson** [comment]
不确定是啥问题。跟 OpenWRT 标准的一样的，应该不会有问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3255/1
