### ISSUE TITLE
請教大大,,,Nastool 在pc 外置硬盤找不到外置硬盤文件夾

### ISSUE THREAD

**Issue by evajoe2** [istoreos/istoreos#383]
Nastool 在pc ,媒体库>設置>新增目錄,
找不到外置硬盤 文件夾 
(/mnt/data_sdb1/video)<<<找不到

Jellyfin影院 只能找到docker 外置硬盤 文件夾
(mnt/data_sdb1/docker/Video) <<< ok
(/mnt/data_sdb1/video)<<<找不到

不知是否我弄錯setting

小白新手請見諒

**Comment by jannson** [comment]
这个应该到 NasTool 那边交流，目前我们核心上架了他们的插件，没提供更多的帮助。等我们的 NAS版本，我们也许会提供更简化的配置向导。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3253/1
