### ISSUE TITLE
能否做一个aliddns和网络唤醒的插件

### ISSUE THREAD

**Issue by sooway** [istoreos/istoreos#384]
能否做一个aliddns和网络唤醒的插件，我感觉我这个要求很简单实现
另外socat插件用不了，是否有问题，麻烦查一查
还有手动安装的插件，希望也能放到istore的应用里，可以方便卸载，谢谢

**Comment by jannson** [comment]
socat 很早修复了啊，你卸载重新安装试试。
aliyun ddns 也有，首页我们都还给了 向导设置

远程唤醒貌似有官方的，我们确认下，可以增加。问题你最好确认下，或者到交流群讨论。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3252/1
