### ISSUE TITLE
啥时候可以支持Nanopi R2C，期待这个固件好久了（必须叫一声大宝哥吗，不然不理人，【表情】【表情】）

### ISSUE THREAD

**Issue by hongmaju** [istoreos/istoreos#393]
This repository is a mirror of our main repo at https://git.openwrt.org/openwrt/openwrt.git
It is for reference only and is not active for checkins or for reporting issues.

All issues should be reported at: https://bugs.openwrt.org

Please do not open any NEW issue here - we will be closing the Github issues
capability in the near future.

We will continue to accept Pull Requests here as described in the repo description.

Close this now and click here: https://bugs.openwrt.org

Thankyou for your co-operation.

**Comment by hongmaju** [comment]
![image](https://user-images.githubusercontent.com/11548009/192675796-9a36f73e-471e-4b2a-83cd-6d29758718a5.png)

**Comment by hongmaju** [comment]
wan口，YT8521S的网卡驱动

**Comment by GolemZ2K** [comment]
卖了，换R2S，马上就能用上！

**Comment by jjm2473** [comment]
不兼容r2s的话就算了

**Comment by jjm2473** [comment]
最新r2s固件已经集成yt8521驱动，r2c直接刷r2s固件就行了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3244/1
