### ISSUE TITLE
大宝哥 在挂载网络共享里 把nas文件夹挂载到op 能成功 并被jellyfin读取 可以过一阵子路径会自动消失不见 再次开启共享又出现 就是待不久 机器正常运行 无任何操作 消失了 jellyfin也读不到媒体文件夹了

### ISSUE THREAD

**Issue by molin830** [istoreos/istoreos#394]
[This](url) repository is a mirror of our main repo at https://git.openwrt.org/openwrt/openwrt.git
It is for reference only and is not active for checkins [or](![)2GEIU_K~S}WMZL3LE`HTEF](https://user-images.githubusercontent.com/46592253/192465224-707defd2-a944-4689-8bf3-5420c966de6b.png)) for reporting issues.

All issues should be reported at: https://bugs.openwrt.org

Please do not open any NEW issue here - we will be closing the Github issues
capability in the near future.

We will continue to accept Pull Requests here as described in the repo description.

Close this now and click here: https://bugs.openwrt.org

Thankyou for your co-operation.

**Comment by molin830** [comment]
![)2GEIU_K~S}WMZL3LE`HTEF](https://user-images.githubusercontent.com/46592253/192466297-5487a442-42b2-40c7-bb2d-d3cbe55bb41b.png)
![B@XTN90Q}YW6DNM6X8{0J}Y](https://user-images.githubusercontent.com/46592253/192466304-ec0f4124-2c9a-4f4f-88e5-7917fc85ac6f.png)
![ORAS$R3OY~{$8Y9O$ D0%CR](https://user-images.githubusercontent.com/46592253/192466305-ab71c44d-3cfc-4ae5-8e0b-c66f2a1bcc57.png)

**Comment by molin830** [comment]
![)2GEIU_K~S}WMZL3LE`HTEF](https://user-images.githubusercontent.com/46592253/192466929-95aeb9ab-35af-4db6-81ca-3ad0d691a789.png)
![B@XTN90Q}YW6DNM6X8{0J}Y](https://user-images.githubusercontent.com/46592253/192466937-5ca69d0d-644c-423f-8767-d59fe2630d3f.png)
![ORAS$R3OY~{$8Y9O$ D0%CR](https://user-images.githubusercontent.com/46592253/192466944-66322a4b-8403-4266-8a0e-26ae14e82965.png)

**Comment by My-By** [comment]
不知道你解决了没有，我今天刚解决，把挂载点设置成全英文，不带中文的，就算掉了也会自动挂载进去，相对来说可能会好一点。

**Comment by My-By** [comment]
![1669868241139](https://user-images.githubusercontent.com/109018851/204964778-e1fa46d3-b493-431f-9c49-abc4af2f6783.png)
![1669868258365](https://user-images.githubusercontent.com/109018851/204964779-7841a5b5-8b82-48d9-9563-794f1c3943a5.png)
亲测只要是中文挂载点很容易多设备接入或者短暂延迟断网就会掉挂载，一旦全英文配置，重启，掉挂载也会自动挂载上去，很稳定。

**Comment by jjm2473** [comment]
是不是网络不稳定，还有不要把路径设置到nvme什么里面，直接/mnt/nas不行吗？

**Comment by My-By** [comment]
在网络共享里填5次你要挂载的网络地址 五条填一模一样的，我的E3845填一次稳如老狗，J4125填一次重启或者断网就掉，无法自动挂载，填5次就很稳，具体原因不明。

**Comment by HFfay** [comment]
有挂载  WebDAV 成功的么？应用之后，挂载目录生成了，但是里面是空的。
![企业微信截图_20230207160339](https://user-images.githubusercontent.com/7297472/217186737-9558c170-8a60-4467-a1bf-8376c0ab77d4.png)
![image](https://user-images.githubusercontent.com/7297472/217186883-46d6382b-14de-43a8-a351-e95ca16c57b9.png)

**Comment by jjm2473** [comment]
@HFfay 试试完整的url，http开头的

**Comment by HFfay** [comment]
> 

谢谢，还是没有用。

主要是没教程，网上也找不到相关配置的例子。

**Comment by HFfay** [comment]
我这边解决了，需要在url后面再加一层/dav/才行

**Comment by jjm2473** [comment]
> 我这边解决了，需要在alist的url后面再加一层/dav/才行 完整url是这样的：[http://ip:端口/dav/](http://ip:%E7%AB%AF%E5%8F%A3/dav/)

我靠，alist后台页面不是告诉你webdav的路径了吗，居然会不知道要家dav？？

**Comment by Joker-lm** [comment]
![image](https://user-images.githubusercontent.com/122144667/234975438-f429e4ea-ddfd-4a07-9bd8-cf9853eb2e75.png)
用户那里只能选guest,自定义没用啊，挂不成功

**Comment by auroracamus** [comment]
> 在网络共享里填5次你要挂载的网络地址 五条填一模一样的，我的E3845填一次稳如老狗，J4125填一次重启或者断网就掉，无法自动挂载，填5次就很稳，具体原因不明。

亲测这个方法好用，大力出奇迹~

**Comment by Joker-lm** [comment]
> 

用户那里不能选，怎么解决的，兄弟

**Comment by Joker-lm** [comment]
> > 在网络共享里填5次你要挂载的网络地址 五条填一模一样的，我的E3845填一次稳如老狗，J4125填一次重启或者断网就掉，无法自动挂载，填5次就很稳，具体原因不明。
> 
> 亲测这个方法好用，大力出奇迹~

用户那里不能选，不能用admin账户，怎么解决的，兄弟

**Comment by Joker-lm** [comment]
> @Joker-lm 用户那下拉不是可以自己填吗，填完回车

囧😳，我没回车

**Comment by 411EN** [comment]
> 我这边解决了，需要在alist的url后面再加一层/dav/才行 完整url是这样的：[http://ip:端口/dav/](http://ip:%E7%AB%AF%E5%8F%A3/dav/)

我也是填写完整路径，挂载的文件夹里还是空的 请问怎么解决

**Comment by houuu23** [comment]
必须要用户名跟密码

**Comment by wuchjun** [comment]
![Image](https://github.com/user-attachments/assets/3c25ac28-6fe2-4a1e-88fe-ae2e104925bb)
填写了账号密码，访问目录提示“登录状态丢失”



> 必须要用户名跟密码

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3243/1
