### ISSUE TITLE
ssr 配置应用后一直提示【正在等待配置被应用… 0s】

### ISSUE THREAD

**Issue by GrayPenn** [istoreos/istoreos#40]
正在等待配置被应用… 0s

倒计时为0之后遮罩没有消失，页面无法其它操作，只能刷新重新进入 Istore

**Comment by jannson** [comment]
嗯，同样发现这个问题。请等后续。。。

**Comment by zb737472783** [comment]
我发现 不要直接应用,而是先保存 在右上角未配置那里再点应用就可以了.

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3845/1
