### ISSUE TITLE
R4S固件发现一个问题不能软重启

### ISSUE THREAD

**Issue by Ginua8292** [istoreos/istoreos#407]
不论在SSH输入reboot还是直接点重启！都不会重启！只能断了电开机

**Comment by byteinfo** [comment]
用什么软件写的固件？我之前Balenaetcher写固件无法重启，直接点重启和reboot 不能正常启动，一直亮红灯，必须重插电源才能开机，几个版本都是这样。。。后来用rufus写固件竟然可以重启了。。。

**Comment by Ginua8292** [comment]
> rufus

我就是用rufus写！几个版本都不能重启！

**Comment by supen8012** [comment]
用的最新的openwrt-2022071511-nanopi-r4s-squashfs.img.gz，无论用Balenaetcher还是rufus写固件，系统菜单的重启都失败，一直亮红灯，刷了几遍了，特来请教，怎么才能让重启功能正常？期待用上ISTOREOS的固件！

**Comment by byteinfo** [comment]
> > rufus
> 
> 我就是用rufus写！几个版本都不能重启！

换个卡试试

**Comment by xinyue603** [comment]
x86的也是同样的问题。最新的092414固件，打算退回老版本固件了，盲目追新没必要，稳定就不要动了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3231/1
