### ISSUE TITLE
无法格式化+挂载硬盘

### ISSUE THREAD

**Issue by hongzhi725** [istoreos/istoreos#408]
N5105 刷 iStore OS EFI ，无法挂载硬盘。
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/17839970/196204766-ae262707-f7e8-4230-8326-018dc11b07ce.png">

**Comment by 865102930** [comment]
这个efi的无法格式化和挂载，非efi那个能格式化和挂载

**Comment by Hujiayi626** [comment]
我也是yimu一样情况，请问解决了吗？或者怎么手动格式化？请教！

**Comment by 865102930** [comment]
自带的无法格式化和挂载,在软件中心下载磁盘工具能进行格式化.

**Comment by jjm2473** [comment]
已修复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3230/1
