### ISSUE TITLE
R4S固件的网卡驱动麻烦手动调整下

### ISSUE THREAD

**Issue by cerellean** [istoreos/istoreos#410]
目前应该还是默认的8169驱动，网口还是老问题，有一盏灯不亮
![image](https://user-images.githubusercontent.com/76246967/197346135-9d2b8cdd-18d0-47d2-910c-d8aa741030e2.png)

LEDE源码已经调整为默认8168了
![image](https://user-images.githubusercontent.com/76246967/197346162-8ea4bfa0-d108-4d0f-852d-7e4ac562713a.png)

**Comment by jjm2473** [comment]
https://github.com/coolsnowwolf/lede/blob/master/package/lean/r8168/patches/001-r8168-add-LED-configuration-from-OF.patch
https://github.com/coolsnowwolf/lede/blob/master/target/linux/rockchip/patches-5.4/106-arm64-rockchip-add-OF-node-for-pcie-eth-on-NanoPi-R4S.patch

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3228/1
