### ISSUE TITLE
刷的最新版本，带宽被限速在100M了，有没有遇到同样问题的兄弟

### ISSUE THREAD

**Issue by wyx13758197247** [istoreos/istoreos#411]
不知道为什么被限速在100M了，找不到原因，esxi虚拟机下面跑的软路由，换另一个OP固件没有问题，但是那个固件NAT有问题导致我无法内网的情况下用域名访问内网设备。。有没有同样情况的兄弟，或者大佬告诉我哪里可以改，谢谢

**Comment by jjm2473** [comment]
升级最新固件看看海也有没有问题，还有看看是否网卡协商到100M了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3227/1
