### ISSUE TITLE
RAID 重启之后，不会自动恢复

### ISSUE THREAD

**Issue by jannson** [istoreos/istoreos#416]
断电之后，开机是这个状态：
![image](https://user-images.githubusercontent.com/4100344/198432567-b8e6f55e-1755-4c29-9b8d-53f55efd87a3.png)

需要扫码恢复之后才正常：
![image](https://user-images.githubusercontent.com/4100344/198432633-ae0ca11a-a2ad-4421-a137-c623b8494986.png)

需要思考的问题：
1. 如果 docker 安装到 raid 上面，那么启动要等待 raid 自动恢复 OK 之后，才能启动 Docker
2. 其他下载插件也同样的道理

**Comment by jjm2473** [comment]
这个是因为mdadm启动时硬盘还没初始化吗？

**Comment by jjm2473** [comment]
这个是因为断电吗，不是因为系统重置导致mdadm配置丢失吗？虚拟机测试，只要恢复了mdadm的配置，重启不会丢失raid。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3222/1
