### ISSUE TITLE
webdav文件上传问题

### ISSUE THREAD

**Issue by zhcn7** [istoreos/istoreos#417]
![屏幕截图 2022-10-28 094048](https://user-images.githubusercontent.com/51230084/198445310-eb8c5022-83bb-4fa3-b49a-88cfe2f8f35c.jpg)
通过raidrive把openwrt的webdav挂载到本地，通过复制粘贴的方式上传或下载文件，上传时出现如图所示错误

**Comment by jjm2473** [comment]
重复 #412

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3221/1
