### ISSUE TITLE
虚拟机下好像不能用

### ISSUE THREAD

**Issue by goldensquall** [istoreos/istoreos#42]
我在爱快的虚拟机里安装了以后，SSR始终无法开启，请问什么原因呢？

**Comment by jannson** [comment]
我们确认下。这个是第三方插件，我们也仅仅测试了其中一部分。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3839/1
