### ISSUE TITLE
x86的ubuntu插件，内网正常，局域网外网点不出来

### ISSUE THREAD

**Issue by sooway** [istoreos/istoreos#420]
我的版本是x86的j1900，安装了ubuntu插件，内网点击“Ubuntu 桌面链接”正常。
我有公网IP，然后阿里云的动态域名，用域名在局域网外访问路由器，点击“Ubuntu 桌面链接”，出来一个空白的“about:blank#blocked”的网页，出不来ubuntu登录页面，请求大神怎么处理。

**Comment by sooway** [comment]
意思是不能用动态域名解析，要用ddnsto，那我试试

**Comment by sooway** [comment]
能不能改成不用穿透，动态域名解析也可以用的

**Comment by sooway** [comment]
我端口做了转发到docker,然后不是点击“Ubuntu 桌面链接”，而是直接域名加端口，可以访问到ubuntu。这个issues关闭了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3218/1
