### ISSUE TITLE
istoreOS install error root not found 

### ISSUE THREAD

**Issue by cgy0214** [istoreos/istoreos#427]
u盘放在机器上执行安装系统时，出现错误求助。
启动正常跑码
执行到30.617376 NFSD: starting  10-second grace period (net f0000097) 最后一直停留再此。
1.回车出现root目录
2.执行 quickstart 出现安装菜单
3.执行 install X86
报错异常：error:root not found 
查看网卡信息选项为空。

反复试过的版本：
istoreos-21.02.3-2022102715-x86-64-squashfs-combined.img.gz
istoreos-21.02.3-2022092414-x86-64-squashfs-combined.img.gz
istoreos-21.02.3-2022091615-x86-64-generic-squashfs-combined-efi.img.gz
istoreos-21.02.3-2022102715-x86-64-squashfs-combined-efi.img.gz

**Comment by cgy0214** [comment]
是识别不到安装的U盘，还是机器里的固态硬盘呀？。机器里有两块我已经卸掉一块了，把u盘也设置第一启动项了，还是不行。有什么解决办法吗

**Comment by cgy0214** [comment]
直接盘刷就好了,不用这个包的。

**Comment by cu97ming** [comment]
> 直接盘刷就好了,不用这个包的。

请问下 直接盘刷是指直接把img镜像写入到磁盘中吗？

**Comment by likooo12580** [comment]
有人解决这个问题了么？ 求点步骤（来个英文教程网址也行）

**Comment by cgy0214** [comment]
使用physdiskwrite用PE进把磁盘重新删分区然后用cmd执行 phydiskwrite.exe -u xxxx-efi.img 进入窗口后一定要执行 mount -o remount rw /不然没有权限保存不了配置， 新盘不会有这个问题也可以直接换个硬盘

**Comment by cgy0214** [comment]
> > 直接盘刷就好了,不用这个包的。
> 
> 请问下 直接盘刷是指直接把img镜像写入到磁盘中吗？
使用physdiskwrite用PE进把磁盘重新删分区然后用cmd执行 phydiskwrite.exe -u xxxx-efi.img 进入窗口后一定要执行 mount -o remount rw /不然没有权限保存不了配置， 新盘不会有这个问题也可以直接换个硬盘

**Comment by cgy0214** [comment]
> > 直接盘刷就好了,不用这个包的。
> 
> 请问下 直接盘刷是指直接把img镜像写入到磁盘中吗？

使用physdiskwrite用PE进把磁盘重新删分区然后用cmd执行 phydiskwrite.exe -u xxxx-efi.img 进入窗口后一定要执行 mount -o remount rw /不然没有权限保存不了配置， 新盘不会有这个问题也可以直接换个硬盘

**Comment by cgy0214** [comment]
> 有人解决这个问题了么？ 求点步骤（来个英文教程网址也行）

见上

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3212/1

**Comment by neuronvirus** [comment]
> > 有人解决这个问题了么？ 求点步骤（来个英文教程网址也行）
> 
> 见上

谢谢你 老哥, 确认可行
