### ISSUE TITLE
x86机器ipv6问题

### ISSUE THREAD

**Issue by unpack8866** [istoreos/istoreos#428]
x86机器，终端设备正常获取到ipv6，但是无法使用，ipv6测试不成功；请问这个固件ipv6目前是不是不正常？我用其它的op ipv6都是正常的

**Comment by qcnwolf** [comment]
去 网络-dhcp/dns-高级设置，把禁止解析IPv6DNS记录勾选去了就能正常使用IPv6了

**Comment by jjm2473** [comment]
允许ipv6解析以后是否正常了？

**Comment by jjm2473** [comment]
https://github.com/istoreos/istoreos/discussions/646

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3211/1
