### ISSUE TITLE
10g网卡驱动——x710-t4 已经OK

### ISSUE THREAD

**Issue by yutian12345** [istoreos/istoreos#43]
请问常用10g网卡有驱动吗？intel或者m的

**Comment by jannson** [comment]
请提供一个驱动型号列表，我们来参考下。今晚上的版本已经增加了很多 2.5G 网卡驱动

**Comment by dellffff** [comment]
这个x710-t4这个10g卡能驱动吗？

**Comment by jannson** [comment]
> 这个x710-t4这个10g卡能驱动吗？

最新固件增加了最新版本的 i40e 的驱动，请试试能否使用。

**Comment by yutian12345** [comment]
> 请提供一个驱动型号列表，我们来参考下。今晚上的版本已经增加了很多 2.5G 网卡驱动

X550t2 
cx341
？

**Comment by longaga** [comment]
> > 这个x710-t4这个10g卡能驱动吗？
> 
> 最新固件增加了最新版本的 i40e 的驱动，请试试能否使用。

谢谢大神，我测试了v20220422 可以顺利驱动X710-T4L

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3836/1
