### ISSUE TITLE
ax210 无线网卡无法识别

### ISSUE THREAD

**Issue by Wang1998** [istoreos/istoreos#430]
求大佬适配ax210无线网卡,我看LEDE里面有人成功适配 AP 5G https://github.com/coolsnowwolf/lede/issues/9976

**Comment by jjm2473** [comment]
intel的wifi驱动不支持5G AP https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi#features

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3210/1
