### ISSUE TITLE
使用ventoy打开istoreos的ISO和img都会卡在new full-speed USB device number 4 using ci_hdrc

### ISSUE THREAD

**Issue by keng3333** [istoreos/istoreos#431]

**Comment by jjm2473** [comment]
看看是不是跟这个有关 https://www.ventoy.net/cn/doc_openwrt.html

**Comment by jjm2473** [comment]
已经修复了

**Comment by jjm2473** [comment]
之后的固件支持ventoy启动，而且不需要按官方文档的特殊处理，解压后就能启动，还支持升级和安装到其他设备上

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3209/1
