### ISSUE TITLE
网口配置无法正常显示VLAN对应的物理接口

### ISSUE THREAD

**Issue by erqing-lvxv** [istoreos/istoreos#433]
使用VLAN拨号的话网口配置这vlan口对应的物理网口无法正常显示勾选

![3cc8d0c8d89f5b3ec1701bd28ea8ed2](https://user-images.githubusercontent.com/63153016/199676977-02f02e4c-679e-4a06-8f96-07a7ce834f64.jpg)
![d9f56d3fab69d8659f1b0cc23cd9275](https://user-images.githubusercontent.com/63153016/199676976-7d43d8db-981c-47ce-bc44-c775ece007b2.jpg)

**Comment by jjm2473** [comment]
“网口配置”不支持vlan，不要用它配置

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3207/1
