### ISSUE TITLE
iStoreOS区域转发问题wan口入站数据问题

### ISSUE THREAD

**Issue by jac88288** [istoreos/istoreos#435]
iStoreOS区域转发问题wan口入站数据问题，在选择”接受“保存应用后过了一段时间会自动跳回“丢弃”，在重启后还是一样，无论删除后还是重新建立wan入站数据还是一样
![微信图片_20221105170943](https://user-images.githubusercontent.com/109743406/200112422-d3e40030-104f-48c2-944b-13851175c387.png)

**Comment by luyi1680** [comment]
我也碰上了这个问题

**Comment by jac88288** [comment]
删掉wan接口，重新创建internet命名的接口就不会，以wan作为接口就会出现，防火墙开启入站后，重启就会恢复到入站  丢弃

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3205/1
