### ISSUE TITLE
alist被搞坏了

### ISSUE THREAD

**Issue by tolshao** [istoreos/istoreos#441]
在终端输入 alist admin --help类似的命令，
然后就把配置文件改了，删除插件，重装之后，发现无法启动了；
根目录，find -name alist，删掉，重启机子，也不行；

![image](https://user-images.githubusercontent.com/22099608/200467614-31de26b5-384a-4e49-9a2f-975cb742eeab.png)

**Comment by tolshao** [comment]
> 在终端输入 alist admin --help类似的命令， 然后就把配置文件改了，删除插件，重装之后，发现无法启动了； 根目录，find -name alist，删掉，重启机子，也不行；
> 
> ![image](https://user-images.githubusercontent.com/22099608/200467614-31de26b5-384a-4e49-9a2f-975cb742eeab.png)

在配置文件里手动添加user，password也不行，uci show命令如下：
![image](https://user-images.githubusercontent.com/22099608/200468256-b8807311-0d57-41ea-aaab-bc5e578c0da1.png)

**Comment by tolshao** [comment]
解决了，上午还更新过一次插件，估计把命令写错了；
添加，CONFIG_DIR=/etc/alist/
修改，procd_append_param command server --data $CONFIG_DIR
解决，alist server 无--conf用法

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3199/1
