### ISSUE TITLE
R2S无法安装jellyfin

### ISSUE THREAD

**Issue by smaxad47** [istoreos/istoreos#450]
从IStore中安装,会提示
Unknown package 'app-meta-jellyfin'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-app-jellyfin for app-meta-jellyfin
 * pkg_hash_check_unresolved: cannot find dependency luci-i18n-jellyfin-zh-cn for app-meta-jellyfin
 * pkg_hash_fetch_best_installation_candidate: Packages for app-meta-jellyfin found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package app-meta-jellyfin.
 
luci-app-jellyfin
luci-i18n-jellyfin-zh-cn
这两个包没有了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3191/1
