### ISSUE TITLE
树莓派计划今年是不是没有希望了？

### ISSUE THREAD

**Issue by fanmingming** [istoreos/istoreos#455]
树莓派今年还能上包吗？

**Comment by lvshuiwuxian** [comment]
大哥，请问树莓派2B 是否也可以适配哈？

**Comment by rex5652** [comment]
有4B的了
https://fw.koolcenter.com/iStoreOS/rpi4/

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3186/1
