### ISSUE TITLE
挂载硬盘存在坏块的NTFS文件系统，samba或者docker去打开或者读取存在坏块的文件夹会导致系统重启，

### ISSUE THREAD

**Issue by zhouyunjian** [istoreos/istoreos#456]
[   53.877581] ntfs3: sdb2: MFT: r=2f10d, expect seq=3 instead of 2!
[   53.878700] ntfs3: sdb2: MFT: r=2f10f, expect seq=3 instead of 4!
[   60.101514] ntfs3: sdb2: MFT: r=2f10d, expect seq=3 instead of 2!
[   60.101918] ntfs3: sdb2: MFT: r=2f10f, expect seq=3 instead of 4!
[   60.496984] i915 0000:00:02.0: Failed to load DMC firmware i915/skl_dmc_ver1_27.bin. Disabling runtime power management.
[   60.496985] i915 0000:00:02.0: DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
[   66.253946] ntfs3: sdb2: MFT: r=2f10d, expect seq=3 instead of 2!
[   66.256846] ntfs3: sdb2: MFT: r=2f10f, expect seq=3 instead of 4!
[   72.433748] ntfs3: sdb2: MFT: r=2f10d, expect seq=3 instead of 2!
[   72.434187] ntfs3: sdb2: MFT: r=2f10f, expect seq=3 instead of 4!
[   78.575214] ntfs3: sdb2: MFT: r=2f10d, expect seq=3 instead of 2!
[   78.575571] ntfs3: sdb2: MFT: r=2f10f, expect seq=3 instead of 4!
[   84.729012] ntfs3: sdb2: MFT: r=2f10d, expect seq=3 instead of 2!
[   84.729345] ntfs3: sdb2: MFT: r=2f10f, expect seq=3 instead of 4!

就报告一下这个问题，一天起来突然发现istoreos不断重启，发现查不到原因，然后把docker的emby停了就好了，一开始以为是docker或者emby的问题，查到后边排除了，重新启动的emby容器如果不挂上电影目录不会导致系统重启，然后查系统日志发现有
 ntfs3: sdb2: MFT: r=2f10f, expect seq=3 instead of 4!  （sdb2是NTFS的移动硬盘）
类似的内核日志，然后通过samba浏览usb挂载的移动硬盘NTFS文件系统只要一打开电影文件夹系统就重启，然后定位到了是移动硬盘的问题，最后拿硬盘来单独扫发现存在坏块。

如果istoreos莫名其妙不断重启，建议查一下挂载的NTFS文件系统硬盘有没有损坏。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3185/1
