### ISSUE TITLE
希望可以增加对rtl8111系列网卡的支持

### ISSUE THREAD

**Issue by ggg-g** [istoreos/istoreos#459]
目前默认使用的是r8169这个驱动，瑞昱官方有r8168的驱动，希望可以增加对rtl8111系列网卡的支持

**Comment by ggg-g** [comment]
发了好久了，希望被看到

**Comment by ggg-g** [comment]
@jjm2473 @jannson

**Comment by jjm2473** [comment]
OK，我试试能不能编译

**Comment by jjm2473** [comment]
@ggg-g 哪些机型可以测试这个驱动？

**Comment by ggg-g** [comment]
> @ggg-g 哪些机型可以测试这个驱动？

我的是nuc改的双网卡。
我在恩山那边也看到不少X86用这款卡的。
lean大已经将openwrt自带的r8169取消默认，而是换成了r8168

**Comment by jjm2473** [comment]
我没有机器测试，等下我把ipk发上来给你测试

**Comment by jjm2473** [comment]
[kmod-r8168_5.4.188+8.051.02-1_x86_64.ipk.zip](https://github.com/istoreos/istoreos/files/10235512/kmod-r8168_5.4.188%2B8.051.02-1_x86_64.ipk.zip)

解压以后安装里面的ipk

**Comment by ggg-g** [comment]
> [kmod-r8168_5.4.188+8.051.02-1_x86_64.ipk.zip](https://github.com/istoreos/istoreos/files/10235512/kmod-r8168_5.4.188%2B8.051.02-1_x86_64.ipk.zip)
> 
> 解压以后安装里面的ipk

安装成功了

**Comment by ggg-g** [comment]
> [kmod-r8168_5.4.188+8.051.02-1_x86_64.ipk.zip](https://github.com/istoreos/istoreos/files/10235512/kmod-r8168_5.4.188%2B8.051.02-1_x86_64.ipk.zip)
> 
> 解压以后安装里面的ipk

感谢大佬，我自己编译了好多天，一直不行。

**Comment by jjm2473** [comment]
运行没问题吗

**Comment by ggg-g** [comment]
> 运行没问题吗

大佬，安装完之后，路由器倒是正常运行。但我看不到运行的是哪个驱动程序

**Comment by jjm2473** [comment]
执行 `ethtool -i eth0`

**Comment by ggg-g** [comment]
> 执行 `ethtool -i eth0`

![image](https://user-images.githubusercontent.com/57361301/208034788-30f95f51-b734-4518-a3ee-e5441d32e004.png)
运行的还是原来的驱动

**Comment by jjm2473** [comment]
更新固件吧，新固件已经删掉8169驱动了，换成了8168

**Comment by ggg-g** [comment]
> 更新固件吧，新固件已经删掉8169驱动了，换成了8168

昨日已更新，目前运行良好

**Comment by JonXman** [comment]
> 更新固件吧，新固件已经删掉8169驱动了，换成了8168

大佬，我是istore OS的openwrt，他们固件没有支持r8168驱动，我安装你给的ipk后重启也还是r8169的驱动，怎么操作更换掉这个驱动呢？麻烦大佬你了

**Comment by jjm2473** [comment]
@JonXman istoreos最新的固件已经可以在后台配置需要的驱动了。看看更新日志

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3182/1
