### ISSUE TITLE
web服务器

### ISSUE THREAD

**Issue by bestruirui** [istoreos/istoreos#461]
有计划使用nginx作为默认web服务器吗

**Comment by gonboy** [comment]
> opkg update opkg install luci-nginx
> 
> 这样可以自己用 nginx

安装提示ssl版本太旧，无法安装(r68s)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3180/1
