### ISSUE TITLE
编译下载ninja-1.10.2.tar.gz失败

### ISSUE THREAD

**Issue by Dew-OF-Aurora** [istoreos/istoreos#465]
+ curl -f --connect-timeout 20 --retry 5 --location https://codeload.github.com/ninja-build/ninja/tar.gz/v1.10.2?/ninja-1.10.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.cdn.openwrt.org/ninja-1.10.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.openwrt.org/ninja-1.10.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/ninja-1.10.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
No more mirrors to try - giving up.
make[3]: *** [Makefile:78: /home/kali/router_os/istoreos/dl/ninja-1.10.2.tar.gz] Error 2
make[3]: Leaving directory '/home/kali/router_os/istoreos/feeds/packages/devel/ninja'
time: package/feeds/packages/ninja/host-compile#0.22#0.03#17.45
    ERROR: package/feeds/packages/ninja [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/ninja/host/compile] Error 1
make[2]: Leaving directory '/home/kali/router_os/istoreos'
make[1]: *** [package/Makefile:110: /home/kali/router_os/istoreos/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/kali/router_os/istoreos'
make: *** [/home/kali/router_os/istoreos/include/toplevel.mk:234：world] 错误 2

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3176/1
