### ISSUE TITLE
关于qBittorrent卡死卸载   以后再次安装报错

### ISSUE THREAD

**Issue by wanglongfei8899** [istoreos/istoreos#470]
![e6c008edd874d78b3e81bcdddae3551](https://user-images.githubusercontent.com/75508757/202913096-c5d2d8e2-2097-4e04-a5bd-6279cb671f20.jpg)
  

istore (失败于： 2022/11/21 00:14:08) > is-opkg install 'app-meta-qbittorrent'
Root disk full!

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3171/1
