### ISSUE TITLE
能不能加入wrtbwmon这个实时流量监控插件

### ISSUE THREAD

**Issue by qcnwolf** [istoreos/istoreos#480]
能不能加入wrtbwmon这个实时流量监控插件，自带插件没有查看某个ip的实时流量，无法针对性的使用eqos进行IP限速

**Comment by sooway** [comment]
我也希望加入这个实时流量监控的，之前LEDE上面有。

**Comment by sooway** [comment]
x86下首页是没有的，流量统计是点不了的，软件中心也没有

**Comment by qcnwolf** [comment]
> 这个插件是有的，首页有个实时流量，，

**Comment by qcnwolf** [comment]
> 这个插件是有的，首页有个实时流量，或者软件中心实时流量就是它　。

x86 2022112313首页是流量统计，状态里的实时流量就是它，是总的网络流量，无法查看单个ip的流量。而软件中心的实时流量实际是nlbwmon，怎么说呢，很不好用。

**Comment by lwgm** [comment]
https://github.com/bcseputetto/Are-u-ok/blob/master/packages/README.md

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3161/1
