### ISSUE TITLE
无法安装系统惠普HP500,提示“Booting 'iStoreOS'"

### ISSUE THREAD

**Issue by foudx** [istoreos/istoreos#481]
This repository is a mirror of our main repo at https://git.openwrt.org/openwrt/openwrt.git
It is for reference only and is not active for checkins or for reporting issues.

All issues should be reported at: https://bugs.openwrt.org

Please do not open any NEW issue here - we will be closing the Github issues
capability in the near future.

We will continue to accept Pull Requests here as described in the repo description.

Close this now and click here: https://bugs.openwrt.org

Thankyou for your co-operation.

**Comment by jjm2473** [comment]
没有机器测试，你看看openwrt能不能启动

**Comment by jjm2473** [comment]
还有试试efi和非efi固件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3160/1
