### ISSUE TITLE
次新版在线升级到最新版，商店卡死。

### ISSUE THREAD

**Issue by lingyunzhiss** [istoreos/istoreos#483]
This repository is a mirror of our main repo at https://git.openwrt.org/openwrt/openwrt.git
It is for reference only and is not active for checkins or for reporting issues.

All issues should be reported at: https://bugs.openwrt.org

Please do not open any NEW issue here - we will be closing the Github issues
capability in the near future.

We will continue to accept Pull Requests here as described in the repo description.

Close this now and click here: https://bugs.openwrt.org

Thankyou for your co-operation.
![image](https://user-images.githubusercontent.com/19514184/204034583-e51f77dd-dc2e-41b5-bae6-7cbf1e8d7fc5.png)
这窗口独占前台，关不掉。只能重开网页躲过它。

**Comment by jjm2473** [comment]
估计是istore没有完整升级导致的，例如依赖的包没有升级

**Comment by jjm2473** [comment]
打开终端，执行 `is-opkg install taskd luci-lib-taskd luci-app-store`，如果还有问题，就重启试试

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3158/1
