### ISSUE TITLE
r68s-21.02.3固件版本网口识别问题

### ISSUE THREAD

**Issue by shuzr** [istoreos/istoreos#491]
https://fw.koolcenter.com/iStoreOS/r68s/istoreos-21.02.3-2022112412-r68s-squashfs.img.gz  #版本固件网口带宽识别错误

![image_2022-11-28](https://user-images.githubusercontent.com/25197414/204153710-b4fe5357-4e98-40bc-872c-2383d26ad3cf.png)

**Comment by shuzr** [comment]
> eth0跟着eth2上网了怎么回事？不上网可能会导致错误。 或者你说硬件错误是啥？

r68s有四个网口,eth1是wan口，都连了网线，其中0,1为千兆口,2,3为2.5G口，但是固件刷入以后除了wan口其它几个口速度都限制到了百兆，请大佬帮助定位下问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3151/1
