### ISSUE TITLE
校园网的ipv6地址获取问题

### ISSUE THREAD

**Issue by luyi1680** [istoreos/istoreos#493]
校园网有ipv6，如果网线直连电脑，电脑pppoe拨号是可以获得ipv4和ipv6地址的。但是用装有istoreOS的软路由拨号就无法获取ipv6地址，请问如何解决。

**Comment by My-By** [comment]
能给我看看你的设置吗，有图的话我好帮你看看能不能解决。

**Comment by luyi1680** [comment]
> 能给我看看你的设置吗，有图的话我好帮你看看能不能解决。

感谢回复，我开始想按照https://post.smzdm.com/p/ad9qkz9k/和https://sustech.online/service/network/ipv6/两篇文章里的设置方法进行设置，发现其有些界面的选项与istoreos里的不一致，下面我的设置。

WAN-高级设置：
![image](https://user-images.githubusercontent.com/33284268/204987680-88691af8-0d4d-4bd0-a6fe-3115cafa9452.png)
![image](https://user-images.githubusercontent.com/33284268/204987747-5354bae0-2e65-4b18-8ab6-07bf8f1f9c0b.png)
![image](https://user-images.githubusercontent.com/33284268/204988316-2a15047a-cbc9-4527-90d9-e1ec58fbad74.png)
![image](https://user-images.githubusercontent.com/33284268/204988355-a85f9873-f4ca-48da-a674-b5847fbf8847.png)
![image](https://user-images.githubusercontent.com/33284268/204988404-ef632cf1-2f63-4490-88a9-d4effcc92595.png)


WAN6：
![image](https://user-images.githubusercontent.com/33284268/204987995-46893c65-b117-46cd-8ca0-b0defb45b382.png)
![image](https://user-images.githubusercontent.com/33284268/204988080-5209c11e-afc0-446f-adfc-ca2f7b1993b6.png)
![image](https://user-images.githubusercontent.com/33284268/204988155-c9fcc32e-9219-4f7f-b780-dc4ae9ff2a3d.png)
![image](https://user-images.githubusercontent.com/33284268/204988210-463f0e24-8e0c-4ad9-aa79-13c388abeb9f.png)
![image](https://user-images.githubusercontent.com/33284268/204988239-e636166c-5751-4fa0-ab1c-261da4658175.png)

LAN：
![image](https://user-images.githubusercontent.com/33284268/204988515-04628d4e-a8ff-42d5-a4c0-26e150ec2ca0.png)
![image](https://user-images.githubusercontent.com/33284268/204988549-4657d0f6-1c01-4207-a11b-65e3f4659c61.png)
![image](https://user-images.githubusercontent.com/33284268/204988587-9d88e2b1-f11b-40c0-98f8-efe439aee007.png)
![image](https://user-images.githubusercontent.com/33284268/204988609-6da6f413-8707-4013-bb44-53f78b7bd3f4.png)
![image](https://user-images.githubusercontent.com/33284268/204988657-a3113322-7eca-440d-886d-6b1a91a7d177.png)
![image](https://user-images.githubusercontent.com/33284268/204988696-71b9c7e7-fe55-4e30-9c6c-e8beba92af65.png)
![image](https://user-images.githubusercontent.com/33284268/204988726-7e8384f4-0540-4039-93bb-5db1e866311f.png)

DHCP/DNS：
![image](https://user-images.githubusercontent.com/33284268/204988815-271ee202-bd0d-46bd-b86a-baa314326458.png)

防火墙：
![image](https://user-images.githubusercontent.com/33284268/204988893-fa74c57c-f46b-4804-a53e-bd65a2d8e8d3.png)

**Comment by My-By** [comment]
奇怪，讲道理你这个设置应该是可以分配到ipv6的啊，

**Comment by My-By** [comment]
你把网络接口的页面截图我看看，

**Comment by luyi1680** [comment]
![image](https://user-images.githubusercontent.com/33284268/204991030-58d5d080-a958-4e89-b09a-605e79697260.png)

**Comment by My-By** [comment]
你这个已经分配到ipv6了，你看lan口的ipv6有显示了。

**Comment by luyi1680** [comment]
这个不是应该得有2403开头的IP才行嘛

**Comment by luyi1680** [comment]
![image](https://user-images.githubusercontent.com/33284268/204991725-bda3f7af-93c3-433c-a237-bb4cc5453f9b.png)
首页这里也不显示ipv6

**Comment by My-By** [comment]
右键电脑右下角的网络打开网络和in的设置-更改配适器选项-右键你的网卡-状态，看看有没有ipv6，界面里是不会同时显示v6和v4的，有v4会优先跑v4，没有v4才跑v6，那个显示的是你现在再跑的网络。

**Comment by luyi1680** [comment]
也是没有
![image](https://user-images.githubusercontent.com/33284268/204992843-063bdcd9-a1ea-4f1e-8b6a-9aa46eee038a.png)

**Comment by My-By** [comment]
所以你是有v6了，只是软路由界面没显示而已，那个没办法，强迫症会觉得不舒服，我以前也是这样，

**Comment by luyi1680** [comment]
我再研究研究，谢谢你

**Comment by jjm2473** [comment]
只有2开头的ipv6地址才是有效的公网地址，如果没有分配到，可能要找其他人问问是不是有ipv6地址，以及如何获取（PPPOE还是DHCPv6），也可以试试电脑拨号以后能不能获取到ipv6地址

**Comment by My-By** [comment]
你的问题解决了吗 我大概知道你的问题了，如果没解决，回复我一下，我跟你说怎么解决。

**Comment by passwii** [comment]
> 
Hi，我遇到和他同样的问题，PPPOE的V6有显示，但是无法通过IPV6联网测试； 已经关闭DHCP/DNS里面的禁止IPV6解析。 请问你如何解决这个问题？

**Comment by luyi1680** [comment]
> > 
> 
> Hi，我遇到和他同样的问题，PPPOE的V6有显示，但是无法通过IPV6联网测试； 已经关闭DHCP/DNS里面的禁止IPV6解析。 请问你如何解决这个问题？

我参考这个网站里的内容进行设置，就可以了
https://sustech.online/service/network/ipv6/

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3149/1
