### ISSUE TITLE
X86版本21.02.3 2022112519，市场中AlistV3.3.0安装后不能运行。。。一直显示未运行

### ISSUE THREAD

**Issue by Phoenixiao191** [istoreos/istoreos#495]
X86版本21.02.3 2022112519，市场中AlistV3.3.0安装后不能运行。。。一直显示未运行。点击启动可能绿几秒，然后又是显示未运行

**Comment by Phoenixiao191** [comment]
使用 A U ok的2.0版本没有问题

**Comment by Phoenixiao191** [comment]
勾选上**### “允许从外网访问”**就运行成功了，我也醉了，折腾了2天。。。。。哭了！！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3148/1
