### ISSUE TITLE
samba挂载NAS不成功。（成功，但不能以名称访问）

### ISSUE THREAD

**Issue by lingyunzhiss** [istoreos/istoreos#50]
![image](https://user-images.githubusercontent.com/19514184/164802133-d8ac34d0-dc18-4ded-bcea-cc13c9b48f4d.png)
![image](https://user-images.githubusercontent.com/19514184/164802252-a6fd23b5-bdd1-4243-9297-dc3687c9807b.png)

**Comment by jannson** [comment]
可能 netbios 没开启。上班后我们试试

**Comment by jannson** [comment]
我们测试没得问题

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3818/1
