### ISSUE TITLE
增加树莓派的固件

### ISSUE THREAD

**Issue by jannson** [istoreos/istoreos#500]
已经完成：

* 安装[教程](https://doc.linkease.com/zh/guide/istoreos/install_rpi4.html)
* 下载[固件](https://fw.koolcenter.com/iStoreOS/rpi4/)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3144/1
