### ISSUE TITLE
iStoreOS 树莓派 Jellyfin 无法硬件加速

### ISSUE THREAD

**Issue by zydisney** [istoreos/istoreos#501]
iStoreOS 树莓派 Jellyfin 无法硬件加速...
貌似没有v4l2的支持？

**Comment by jjm2473** [comment]
openwrt的官方固件可以吗？如果可以，我们只需要打开内核开关就行。或者试试最新固件，开启了多媒体支持，而且可以安装openwrt官方的内核模块

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3143/1
