### ISSUE TITLE
root disk full

### ISSUE THREAD

**Issue by 865102930** [istoreos/istoreos#502]
![image](https://user-images.githubusercontent.com/18364926/205491154-7f7c9462-599e-4f58-b815-b4bb2d8ce015.png)

**Comment by 865102930** [comment]
![image](https://user-images.githubusercontent.com/18364926/205491229-ffe91a0e-3c1d-4bc2-98c8-63c85139320c.png)

**Comment by 865102930** [comment]
解决了,删除掉root目录下的jackett, qb, 把这两个插件的配置路径换到别的磁盘目录下.
from
![image](https://user-images.githubusercontent.com/18364926/205530939-23083dc2-bd88-4a15-b878-d33cac043ef5.png)
to
![image](https://user-images.githubusercontent.com/18364926/205531099-deeacee6-ae0d-438c-af7b-e717b716e7f8.png)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3142/1
