### ISSUE TITLE
您好，R5S要如何升级到istoreos-21.02.3-2022112412这个版本

### ISSUE THREAD

**Issue by marsdeng1986** [istoreos/istoreos#503]
您好，R5S要如何升级到istoreos-21.02.3-2022112412这个版本，我通过刷机软件或者从系统升级都升级失败了

**Comment by mengxunlingxue** [comment]
> 类似这样安装不行么？https://doc.linkease.com/zh/guide/istoreos/install_r2s.html

无法安装到内置的emmc存储上,只能使用tf卡安装了,同样r68s发布的固件,好像也不能升级上去,奈何r68s没有tf卡接口,只能使用内置emmc

**Comment by marsdeng1986** [comment]
我是刷进emmc的，没办法通过tf卡升级

**Comment by mengxunlingxue** [comment]
> 
遇到同样的问题,我现在已经用tf卡做系统了,只是r68s没法用了

**Comment by marsdeng1986** [comment]
> 类似这样安装不行么？https://doc.linkease.com/zh/guide/istoreos/install_r2s.html

能否同步更新emmc的固件呢

**Comment by jjm2473** [comment]
rk3568要刷emmc参考这个教程 https://supes.top/%E7%94%B5%E7%8A%80%E7%89%9Br68s%E7%BA%BF%E5%88%B7openwrt%E6%95%99%E7%A8%8B/

不再提供单独的emmc固件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3141/1
