### ISSUE TITLE
树莓派版希望可以升级一下内核，目前不支持kmod-wireguard

### ISSUE THREAD

**Issue by rex5652** [istoreos/istoreos#504]
RT
![1be9af0a-a808-4c74-b5d0-99589973af63](https://user-images.githubusercontent.com/1674158/205494655-c6eaf254-a061-4c6b-bb1a-15271cd545a9.jpg)

**Comment by GreenTeodoro839** [comment]
不是需要升级内核，kmod需要编译时一起编译

**Comment by jjm2473** [comment]
可以使用官方仓库的内核模块，这个版本的固件忘了给内核版本打代码导致不支持，下个版本个固件会修复

**Comment by jjm2473** [comment]
最新固件已集成wireguard驱动，更新试试

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3140/1
