### ISSUE TITLE
istoreos的网心云不能打开启动 UPnP

### ISSUE THREAD

**Issue by Soul8310** [istoreos/istoreos#506]
但是路由里我开了，网心云就是不显示。

**Comment by jian263994241** [comment]
公网&全锥型  和 UPnP 不会同时存在

**Comment by jjm2473** [comment]
不需要管这个，istore的插件会自动开放40000以上的端口

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3138/1
