### ISSUE TITLE
小主机是WG82583V千兆网卡  安装这个固件安装后找不到网卡驱动

### ISSUE THREAD

**Issue by jichun29** [istoreos/istoreos#507]
INTEL WG82583V千兆通信芯片   这个打不上驱动   能适配下吗

**Comment by jjm2473** [comment]
查了下[资料](https://linux-hardware.org/?id=pci:8086-150c-8086-0000)，82583 使用的是e1000e驱动，这个驱动老早就集成到istoreos固件里了，如果你的固件太老就升级到最新版看看。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3137/1
