### ISSUE TITLE
首页中docker迁移目录不成功

### ISSUE THREAD

**Issue by hero-intelligent** [istoreos/istoreos#509]
设备r2s，不清楚是否所有设备都有此问题
镜像istoreos-21.02.3-2022112309-nanopi-r2s-squashfs.img.gz

![image](https://user-images.githubusercontent.com/112150507/206131058-8ecfd4cc-10ff-4fc1-95b1-ef9182e1edd1.png)

![image](https://user-images.githubusercontent.com/112150507/206131143-e319e7c0-5944-40aa-ba81-cf7fc1706e62.png)

![image](https://user-images.githubusercontent.com/112150507/206131254-289d763f-d1ed-4253-b1fc-6b8a3dfbbed0.png)

**Comment by HOILUNG** [comment]
那你有没有考虑过.先把docker服务关闭了在迁移目录试试呢,目录被占用的呢,可能迁移不成功

**Comment by jjm2473** [comment]
不是因为你输入的路径开头多了个空格吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3135/1
