### ISSUE TITLE
CM4 能支持下M.2 NVME接口的 SSD吗？TF卡不够用，速度也不行

### ISSUE THREAD

**Issue by dxylove** [istoreos/istoreos#512]
This repository is a mirror of our main repo at https://git.openwrt.org/openwrt/openwrt.git
It is for reference only and is not active for checkins or for reporting issues.

All issues should be reported at: https://bugs.openwrt.org

Please do not open any NEW issue here - we will be closing the Github issues
capability in the near future.

We will continue to accept Pull Requests here as described in the repo description.

Close this now and click here: https://bugs.openwrt.org

Thankyou for your co-operation.

**Comment by jjm2473** [comment]
nvme支持加上了，等下个版本的固件

**Comment by jjm2473** [comment]
最新固件已经增加nvme支持，测试看看 https://fw.koolcenter.com/iStoreOS/rpi4/

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3132/1
