### ISSUE TITLE
另外可以出一个插件类似airconnect嘛，让dlna设备支持AirPlay~~

### ISSUE THREAD

**Issue by nevertoday** [istoreos/istoreos#516]
这个docker 组件真的很刺激， 能不能更直观一点的方案，集中进来？
thks!

**Comment by nevertoday** [comment]
项目参考： https://www.jianshu.com/p/bc1680ffd4fb
中间他们的底层方案都是docker 上的 
https://github.com/philippe44/AirConnect
开启之后，家中那种老旧音箱， 比如sonos play1 能全部被手机或者其他终端音源投放，不再吃灰！！

**Comment by jjm2473** [comment]
airconnect的延时很大

**Comment by nevertoday** [comment]
是很大延迟，但真的可用！很多情景下，我只需要开着，不看画面，当播客听~

**Comment by jjm2473** [comment]
如果是安卓系统的建议用这个app，测试mac电脑推送音频到安卓，延时可以忽略不计 https://play.google.com/store/apps/details?id=com.waxrain.airplayer2

**Comment by jjm2473** [comment]
airconnect已经添加了

**Comment by nevertoday** [comment]
> airconnect

在电视上安装了你推荐的软件，很好的是，速度很给力；一点点遗憾是不能扫描到局域网的sonos 系统

**Comment by nevertoday** [comment]
更新的路由器版本用上了， 感动！牛！
强！赞。
谢谢！

**Comment by sauween** [comment]
> airconnect 已经发布

airconnect 失效了。已经无法支持 dlan 华为音响测试失败

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3128/1
