### ISSUE TITLE
网心云 - 容器魔方upnp 一直不能用请问怎么设置？？？

### ISSUE THREAD

**Issue by soulm00m00** [istoreos/istoreos#528]
网心云 - 容器魔方upnp 一直不能用请问怎么设置？？？

**Comment by soulm00m00** [comment]
不打开收益上不去



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月18日(周日) 晚上8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 网心云 - 容器魔方upnp 一直不能用请问怎么设置？？？ (Issue #528)




 
如果在路由器里面泡网新云，是不需要也不能用 UPNP 的

**Comment by soulm00m00** [comment]
收益很差



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月18日(周日) 晚上8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [istoreos/istoreos] 网心云 - 容器魔方upnp 一直不能用请问怎么设置？？？ (Issue #528)




 
如果在路由器里面泡网新云，是不需要也不能用 UPNP 的

**Comment by jjm2473** [comment]
如果是istore里面的网心云插件，已经自动打开40000以上的端口了，不需要再去管upnp。如果还有问题，就去找网心云的客服

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3117/1
