### ISSUE TITLE
vm虚拟机安装的istore里，vm的共享文件夹在系统里找不到路径

### ISSUE THREAD

**Issue by makergit365** [istoreos/istoreos#530]
如题，vm的共享文件夹功能，在istore里找不到路径，我百度查找其他linux系统都是在/mnt/hgfs下，但我找不到

**Comment by jjm2473** [comment]
你确定vm的共享文件驱动可以安装到openwrt里？那你看其他系统怎么安装的，试试能不能用同样的方式安装

**Comment by makergit365** [comment]
可以关闭了，我按照其他系统的尝试了几种方法最终成功了，感谢回答

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3116/1
