### ISSUE TITLE
很多官方软无法安装(R68s)

### ISSUE THREAD

**Issue by gonboy** [istoreos/istoreos#531]
系统自带核心和软件太旧了。
常用软件很多都无法安装。
装一个缺少库，装一个缺少库，无语了😓

**Comment by jjm2473** [comment]
不是master分支，是21.02.3

**Comment by jjm2473** [comment]
如果需要安装某些插件，可以到这里找 https://github.com/AUK9527/Are-u-ok/tree/main/apps/all

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3115/1
