### ISSUE TITLE
istoreos-21.02.3

### ISSUE THREAD

**Issue by KeplerSSSSS** [istoreos/istoreos#532]
更新istoreos-21.02.3后,硬盘不能使用    多次更新回滚无效  莫名其妙多了个26G的分区   不知道干什么用的

多次尝试后依然无效,不能安装任何插件

**Comment by love5461** [comment]
> 更新istoreos-21.02.3后,硬盘不能使用 多次更新回滚无效 莫名其妙多了个26G的分区 不知道干什么用的
> 
> 多次尝试后依然无效,不能安装任何插件

硬盘管理，删除掉以后重新挂载

**Comment by jjm2473** [comment]
确定26G不是空闲空间吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3114/1
