### ISSUE TITLE
error:root not found

### ISSUE THREAD

**Issue by zrhtop** [istoreos/istoreos#535]
u盘放在机器上执行安装系统时，出现错误求助。
启动正常跑码

1.执行 quickstart 出现安装菜单
2.执行 install X86
报错异常：error:root not found
查看网卡信息选项为空。

目前的最新版x86

机器是R86S万兆网卡版，硬盘是emmc的，通过cd到mnt下可以看到硬盘并且可以访问里面的数据，但是安装脚本检测不到我的硬盘。如果能自定义安装硬盘的路径而不是自动检测就完美了。或者说，目前有没有什么办法可以刷入系统？我没有找到刷入emmc的工具。

**Comment by jjm2473** [comment]
这个问题是由于uuid冲突导致的，下个版本固件会采用新的方法判定启动盘，就算uuid冲突也能挂载，只是uuid冲突的情况下不一定挂载哪个

**Comment by jjm2473** [comment]
已修复

**Comment by paulhybryant** [comment]
我还是遇到了同样的问题，用的最新的固件2024022310

**Comment by lao-zei** [comment]
遇到了同样的问题，用的最新固件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3111/1
