### ISSUE TITLE
istoreos工作超过18小时以后DHCP，IPV4自动挂掉

### ISSUE THREAD

**Issue by love5461** [istoreos/istoreos#538]
机器配置：
inter nuc 11 双网口版本
系统iStoreOS 21.02.3 2022121613  
故障问题：
工作17,18个小时后，IPV4的DHCP自动挂掉了，下面局域网内所有IPV4都死掉了。只有IPV6能够自动获取到IP地址。重启以后故障自动消失。或者用手机通过外网登录路由器以后把内网设置中的保持DHCP重新打开以后，网络才能够自动恢复。不知道什么原因。

**Comment by jjm2473** [comment]
内存不足？

**Comment by LionYu66** [comment]
我好像也是随机dhcp挂掉，而且内存占用才13%

**Comment by jjm2473** [comment]
看看dhcp的分配记录，有没有一直增长

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3108/1
