### ISSUE TITLE
istore 里的自定义挟持域名或者自定义dns解析在哪里

### ISSUE THREAD

**Issue by shiyuanGame** [istoreos/istoreos#541]
istore 里的自定义挟持域名或者自定义dns解析在哪里

**Comment by GreenTeodoro839** [comment]
终端进去vi /etc/hosts，和改Windows的hosts一样

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3106/1
