### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by 0xDion** [istoreos/istoreos#543]
反馈bug

#提交的问题
1. 无法成功软重启 
2. Alist插件安装后无法运行

## 详细叙述
重启后电源指示灯常亮，无法启动系统，必须插拔一次电源

###路由器型号和固件版本

路由器型号：R2S
固件版本: istoreos-21.02.3-2022121614-r2s-squashfs.img

**Comment by jjm2473** [comment]
软重启的问题估计跟rk3568机型一样，这里跟进 https://github.com/istoreos/istoreos/issues/561 。
alist的问题，看看系统日志有没有报错

**Comment by jjm2473** [comment]
看看这里的测试固件能不能软重启 https://fw.koolcenter.com/iStoreOS/alpha/r2s

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3085/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3104/1
