### ISSUE TITLE
R86S-G3刷入iStoreOS无线网卡无法识别

### ISSUE THREAD

**Issue by qmqsu** [istoreos/istoreos#544]
如果是驱动问题 请问有什么办法自己添加吗

**Comment by jjm2473** [comment]
自己编译就行了，而且支持openwrt官方的软件仓库

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3103/1
