### ISSUE TITLE
r5c安装r5s的固件可以吗？

### ISSUE THREAD

**Issue by Ejoyyee** [istoreos/istoreos#545]
我试了一下，把写好r5s系统的sd卡放到r5c里面没有启动刷机，不知道为什么。

**Comment by GreenTeodoro839** [comment]
不可以，差一个字母都是完全不同的机器

**Comment by Ejoyyee** [comment]
谢谢回答

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3102/1
