### ISSUE TITLE
磁盘格式化有时候失败

### ISSUE THREAD

**Issue by jannson** [istoreos/istoreos#546]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

<img width="695" alt="5189da822a858709be87fa9db5d2cc3" src="https://user-images.githubusercontent.com/4100344/210291709-b89b3da3-0b95-48f0-93af-e46341535a20.png">

**Comment by shen-lan** [comment]
遇到了一模一样的问题 怎么解决

**Comment by jjm2473** [comment]
遇到问题先用磁盘管理操作

**Comment by Devil523343732SKY** [comment]
我是手动分区可以一次，然后迁移了docker，后面剩余的56G空间都无法分区格式化，磁盘管理和首页的自动分区并挂载都报错没有可用扇区

**Comment by jjm2473** [comment]
EFI固件用磁盘管理可以增加任意多个分区，非EFI固件只能增加一个分区。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3101/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3105/5
