### ISSUE TITLE
r2s的frpc客户端无法打开

### ISSUE THREAD

**Issue by MissMyDove** [istoreos/istoreos#549]
### (1) 具体问题

A：r2s的frpc客户端无法打开

### (2) 路由器型号和固件版本

A：R2S，21.02.3 2022121614

### (3) 详细日志和/或截图

A：
![image](https://user-images.githubusercontent.com/22162943/211139816-dc74c08c-cdfc-424c-8783-adb54c49aaf3.png)

**Comment by iabbaa** [comment]
我也是这样

**Comment by jjm2473** [comment]
使用r68s测试没发现这个问题，看看系统日志，还有看看浏览器的网络请求

**Comment by jjm2473** [comment]
https://github.com/istoreos/istoreos/issues/419

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3099/1
