### ISSUE TITLE
有人知道 quickstart里的  install x86是干嘛的吗 ？

### ISSUE THREAD

**Issue by shen-lan** [istoreos/istoreos#551]
![Snipaste_2023-01-09_09-45-44](https://user-images.githubusercontent.com/21122615/211257847-9470563e-0981-4855-9557-5dcf1f010e7a.png)

我的理解是进入到控制台不就已经安装完毕了吗  为啥这里又要重新安装一次 ？

**Comment by jjm2473** [comment]
如果是u盘或者tf卡启动的，可以用这个功能安装istoreos到其他地方，例如硬盘或者emmc。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3097/1
