### ISSUE TITLE
突然进不去路由器主页了

### ISSUE THREAD

**Issue by huaxiac4** [istoreos/istoreos#555]
今天突然就打不开了，打开主页就报错。但是本身路由功能都没有问题。可以正常上网。帮忙看下如何解决。很急

错误代码如下:
Status: 500 Internal Server Error /usr/lib/lua/luci/template.lua:97: Failed to execute template 'istorex/index'. A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'istorex/main'. A runtime error occurred: /usr/lib/lua/luci/template.lua:74: Failed to load template 'tasks/embed'. Error while parsing template '/usr/lib/lua/luci/view/tasks/embed.htm': No such file or directory stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:74: in function '__init__' /usr/lib/lua/luci/util.lua:65: in function 'Template' /usr/lib/lua/luci/dispatcher.lua:766: in function 'include' [string "/usr/lib/lua/luci/view/istorex/main.htm"]:1: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function (tail call): ? /usr/lib/lua/luci/controller/istorex.lua:74: in function 'istorex_template' [string "/usr/lib/lua/luci/view/istorex/index.htm"]:3: in main chunk stack traceback: [C]: in function 'error' /usr/lib/lua/luci/template.lua:97: in function (tail call): ? /usr/lib/lua/luci/dispatcher.lua:1027: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:478: in function
![Uploading E752FF14-E5FE-43A9-9E17-AAC50FC23B27.png…]()

**Comment by kevingraham03** [comment]
我也是同样的问题，功能正常，但是打不开管理界面
![Uploading BBCEC300-2441-472F-9805-065B95ABD864.png…]()

**Comment by jjm2473** [comment]
可能安装过程中出现异常了，例如磁盘满了。使用终端或者ssh执行 `is-opkg install luci-lib-taskd` 看看

**Comment by huaxiac4** [comment]
> 

没有等到您恢复了。我直接格盘重装了

**Comment by dunquzhiyi** [comment]
我也是这个问题
![chrome_XttqM9GHu6](https://user-images.githubusercontent.com/124344543/216546214-aef9a202-2e43-4bc5-b01e-96394009f2e1.png)

**Comment by jjm2473** [comment]
@dunquzhiyi 明显不是同一个问题啊，看看自己有没有翻墙吧，或者访问的ip对不对

**Comment by dunquzhiyi** [comment]
> @dunquzhiyi明显不是同一个问题啊，看自己有没有翻墙吧，或者访问者访问的ip对不对

ip是对的，我在设置端口转发的时候报错，刷新之后进不去了。设置端口转发的目的是想在公网访问管理页面，已经做了ddns。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3093/1
