### ISSUE TITLE
X86 版 1216，在U盘安装完毕后，重启后拔掉U盘，卡在启动界面

### ISSUE THREAD

**Issue by Touch4Benny** [istoreos/istoreos#556]
拔掉U盘后，进入系统会卡在Waiting for root device ，请问有什么办法解决？

**Comment by My-By** [comment]
首选启动盘看看需不需要改？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3092/1
