### ISSUE TITLE
安装后拔去U盘重启报错i915 0000:00:02.0: Failed to load DMC firmware i915/kbl_dmc_ver1_04.bin. Disabling runtime power management.

### ISSUE THREAD

**Issue by MrNewOne** [istoreos/istoreos#557]
### (1) 具体问题

A：安装后拔去U盘重启报错i915 0000:00:02.0: Failed to load DMC firmware i915/kbl_dmc_ver1_04.bin. Disabling runtime power management.

### (2) 路由器型号和固件版本

A：固件版本：istoreos-21.02.3-2022121613-x86-64-squashfs-combined-efi.img.gz
路由器：J4125 4口RTL8125B网卡
### (3) 详细日志和/或截图

![webfilehelper](https://user-images.githubusercontent.com/122798306/212688346-e6b1419d-d456-44cd-bbc5-677f9b67292a.jpg)

>

**Comment by L0tus0** [comment]
我在也遇到了同样的问题，据恩山一个帖子说是因为root device PARTUUID没有指向正确的引导分区所致。
我最后是安装1207的legacy版本解决的。

**Comment by MrNewOne** [comment]
> 我也遇到了同样的问题，据恩山一个帖子说是因为root device PARTUUID没有指向正确的引导分区所致。 我最后是安装1207的legacy版本解决的。

多谢，那我试一下1207的efi版本

**Comment by jjm2473** [comment]
如果是使用quickstart安装导致的问题，那之后会修复

**Comment by jjm2473** [comment]
已修复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3090/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3091/1
