### ISSUE TITLE
x86_1216版本引导时卡在GNU GRUB界面，无法自动引导iStoreOS

### ISSUE THREAD

**Issue by L0tus0** [istoreos/istoreos#558]
## 1. 问题摘要
x86_1216版本`both efi and legacy`引导时卡在GNU GRUB界面，无法自动引导iStoreOS

Q：是否用关键词搜索了issue?
* [x] 没有类似的issue

### (1) 具体问题

A：x86_1216版本引导时卡在GNU GRUB界面，无法自动引导iStoreOS，必须人工按回车，并且每次启动都要。而1207版本（legacy，我使用的软路由无法正常引导efi固件，与[此贴](https://github.com/istoreos/istoreos/issues/557)情况一致）一切正常。测试了**U盘启动通过`quickstart`安装**与**先安装早期版本再通过iStoreOS更新固件**两种方式，都是一样的情况。

### (2) 路由器型号和固件版本

A：
* 路由器型号：x86架构6网口小主机`3865U & 4G DDR4 & 32G mSATA SSD`
* 固件版本：[istoreos-21.02.3-2022121613-x86-64-squashfs-combined.img.gz](https://fw.koolcenter.com/iStoreOS/x86_64/istoreos-21.02.3-2022121613-x86-64-squashfs-combined.img.gz)及其[efi版本](https://fw.koolcenter.com/iStoreOS/x86_64_efi/istoreos-21.02.3-2022121613-x86-64-squashfs-combined-efi.img.gz)

### (3) 详细日志和/或截图

A：
![ef0a1c75d8d9fe6f88efdb563cb53df](https://user-images.githubusercontent.com/99093540/212710262-79b54ccc-7ae2-43a9-b49a-7b97c34b1b41.jpg)

**Comment by jjm2473** [comment]
是不是自己修改过grub的配置，默认是倒计时2秒钟后自动启动

**Comment by L0tus0** [comment]
> 是不是自己修改过grub的配置，默认是倒计时2秒钟后自动启动

没有修改过grub配置，下载镜像后用rufus默认配置写到U盘里。从1216这个版本从U盘引导时就这样。

**Comment by jjm2473** [comment]
启动以后执行 `cat /boot/grub/grub.cfg` 看看

**Comment by jjm2473** [comment]
看代码1207到1216之间没有修改过grub相关的配置，确定不是因为键盘被按住？或者grub读取到了其他盘的配置文件？（grub只会查找有grub配置文件的分区，而不是直接查找启动盘）

**Comment by L0tus0** [comment]
> 看代码1207到1216之间没有修改过grub相关的配置，确定不是因为键盘被按住？或者grub读取到了其他盘的配置文件？（grub只会查找有grub配置文件的分区，而不是直接查找启动盘）

现在再装1216对我来说代价比较大，毕竟都配置好了，有合适的机会再尝试提供更多信息。
- 我很确定不是因为键盘被按住，比如说在1207固件升级到1216这种情况下，软路由都没有接键盘，但十几分钟都毫无响应
- grub读取到其他盘也可以排除，因为只有一个32G的SSD（现在看来似乎是这台机子自己的问题）
另外一个可以提供的信息是，1207固件刻到U盘和1216固件刻到U盘，在同样U盘引导时1207可以直接跑码后进系统，而1216会卡grub。

**Comment by L0tus0** [comment]
我刚刚在两台PC上都测试了一下U盘引导1216固件，grub会闪现一下，但不会卡。
我也查看了1207和1216的grub配置文件，不同点在于timeout的设置。1207固件timeout为0，1216固件timeout为1。
猜测与此有关，当然那台软路由肯定是有大问题（比如在我不知情的情况下开机产生了一个莫名其妙的按键值导致它卡住？）

**Comment by jjm2473** [comment]
试试最新的固件吧0129

**Comment by jjm2473** [comment]
timeout=1是方便万一要看串口调试信息或者要进failsafe模式。
你说有问题的软路由也重新刷最新的固件试试

**Comment by jjm2473** [comment]
根据[这个帖子](https://forum.openwrt.org/t/solved-boot-hangs-on-lede-item-in-grub-menu-on-x86-no-grub-timeout/24741/9)，应该是串口初始化时的杂讯让grub停止了倒计时，所以没自动启动istoreos。

这个问题通过禁止串口输入到grub修复了，下个版本发布。

**Comment by jjm2473** [comment]
已修复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3090/1
