### ISSUE TITLE
防火墙BUG 提交

### ISSUE THREAD

**Issue by coolzhi** [istoreos/istoreos#559]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：网络-防火墙- wan口 入站数据重启服务器后就变成丢弃了 之前设置过了接受

### (2) 路由器型号和固件版本

A：[2022121613-x86-64-squashfs-combined-efi.img.gz](https://fw.koolcenter.com/iStoreOS/x86_64_efi/istoreos-21.02.3-2022121613-x86-64-squashfs-combined-efi.img.gz)

### (3) 详细日志和/或截图

A：
![QQ截图20230120103552](https://user-images.githubusercontent.com/34399798/213607433-678cf54e-a9d7-4491-85ee-6ff505154c3c.png)

因为设置了定时重启路由器，这个不解决等下次想远程路由器的时候就不行了

**Comment by jjm2473** [comment]
这个不是bug，是istoreos为了防止外网攻击，自动禁止pppoe入站。如果你确实要允许外网访问所有端口，那增加一条防火墙规则即可

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3089/1
