### ISSUE TITLE
无法科学上网

### ISSUE THREAD

**Issue by maxin-cn** [istoreos/istoreos#560]
在威联通nas里面使用虚拟机安装了istoreos，作为旁路由使用，旁路由可以正常上网。但是安装科学上网插件之后无法科学上网（科学上网插件测试通过）。
![image](https://user-images.githubusercontent.com/38418898/213696097-e2a971d4-b9e6-4cc7-8789-adbb9b7ee081.png)

**Comment by jjm2473** [comment]
你确定虚拟机和宿主机的路由配置是正确的？“无法科学上网”是指电脑还是虚拟机？

**Comment by maxin-cn** [comment]
> 你确定虚拟机和宿主机的路由配置是正确的？“无法科学上网”是指电脑还是虚拟机？

后来换成了passwall，可以通过软路由翻墙了。
