### ISSUE TITLE
Cannot convert image format from img to iso

### ISSUE THREAD

**Issue by fred214** [istoreos/istoreos#563]
Hi,
On mac, I use Vmware fusion to create virtual machine to install istoreos, but I found after I convert image from `img` to `iso` by using
```
 hdiutil convert input.img -format UDTO -o output.iso
```
The vmware fusion found no media in CDROM, do you have any experience about this issue?
Many thanks.

**Comment by fred214** [comment]
I got it, the img is not a install image

**Comment by jjm2473** [comment]
Use `qemu-img` to convert image format, include vmdk.
For example:
`qemu-img convert istoreos.img -f raw -O vmdk istoreos.vmdk`

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3086/1
