### ISSUE TITLE
支持R6S

### ISSUE THREAD

**Issue by ArtechZhu** [istoreos/istoreos#564]
请问是否有支持R6S的计划？

**Comment by yinbug** [comment]
同问什么时候支持r6s，或者教我怎么开发固件，我自己写pr支持r6s

**Comment by luogujun** [comment]
有计划支持R6S么？我想有个盼头。

**Comment by ArtechZhu** [comment]
不用等了，官方没人回复的，邮件、B站我都问过好几次了，没有任何回复，已经不关注了，随缘。

R6S你可以先用 supes.top 编译的固件，至于想用 NAS 相关的功能，建议还是买个 NAS 吧，不贵，关键是稳定和安全，用起来舒服

**Comment by jjm2473** [comment]
测试固件22.03.4已经支持R6S/R6C https://github.com/istoreos/istoreos/issues/716

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3064/4
