### ISSUE TITLE
./scripts/feeds install -a 安装时报错

### ISSUE THREAD

**Issue by softfuttery** [istoreos/istoreos#567]
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：./scripts/feeds install -a 安装时报错，显示依赖包不存在，且-f参数无法覆盖，百度未找到方法

### (2) 路由器型号和固件版本

A：cm360 rtd1296 

### (3) 详细日志和/或截图

A：debian 11.6
cm360:~/istoreos$ ./scripts/feeds install -a
Collecting package info: done
WARNING: Makefile 'package/feeds/third/luci-app-baidupcs-web/Makefile' has a dependency on 'baidupcs-web', which does not exist
WARNING: Makefile 'package/diy/ntfs3-mount/Makefile' has a dependency on 'kmod-fs-ntfs3', which does not exist
Installing all packages from feed packages.
WARNING: Not overriding core package 'xtables-addons'; use -f to force
Installing all packages from feed luci.
WARNING: Not overriding core package 'luci-app-aria2'; use -f to force
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed store.
Installing all packages from feed third.

**Comment by jjm2473** [comment]
只是警告而已，忽略即可

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3083/1
