### ISSUE TITLE
应用商店获取不到数据

### ISSUE THREAD

**Issue by Chonglian233** [istoreos/istoreos#568]
(1) 具体问题

A：应用商店的全部软件里获取不到数据，已安装的软件不显示

(2) 路由器型号和固件版本

A：R66S，istoreos 21.02.3 2022111208

(3) 详细日志和/或截图

A：
![mmexport1675131062178](https://user-images.githubusercontent.com/44470472/215642146-90fcec73-e8da-476e-adf8-3b5a06f934f4.png)

![mmexport1675131060849](https://user-images.githubusercontent.com/44470472/215642157-c32e97a6-fae4-4750-be0d-104a6cb13c87.png)

**Comment by jjm2473** [comment]
看清楚，这是“已安装”界面

**Comment by jjm2473** [comment]
一般都是因为你自己电脑的网络有问题

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3082/1
