### ISSUE TITLE
再提一下，X86版的固件，请求增加主机的实时流量

### ISSUE THREAD

**Issue by sooway** [istoreos/istoreos#569]
有类似的issue

### (1) 具体问题

A：再提一下，X86版的固件，首页真没有实时流量，软件中心也没有，翻遍菜单也没有，这个问题有人提了几次了，麻烦核实下，谢谢开发者，要显示局域网内，各个主机的实时流量。

### (2) 路由器型号和固件版本

A：X86版，从始至终的版本都没有

### (3) 详细日志和/或截图

要下面这种样子的
<img src="https://www.8dlive.com/wp-content/uploads/2022/11/210957swq4lfezw7p64qet.jpg" width="1144" height="703" />

**Comment by jjm2473** [comment]
这个插件叫什么

**Comment by jjm2473** [comment]
istore里面不是有个“主机流量监控”插件吗？

**Comment by sooway** [comment]
“主机流量监控”不好用，上面那个插件名字好像是wrtbwmon

**Comment by Bender1337** [comment]
如果能加上这个功能就太好了。
“主机流量监控”这个插件根本不好用

**Comment by My-By** [comment]
主机流量监控确实是累赘，真想看看哪个设备跑流量，都看不好。

**Comment by jjm2473** [comment]
istore上架了 `实时流量` ，这个插件的更新频率是5秒一次，足够实时监控了。

`主机流量监控` 只是数据更新频率慢一点，最快30秒一次，并不是不能用，而且统计数据更丰富。

**Comment by sooway** [comment]
> istore上架了 `实时流量` ，这个插件的更新频率是5秒一次，足够实时监控了。
> 
> `主机流量监控` 只是数据更新频率慢一点，最快30秒一次，并不是不能用，而且统计数据更丰富。

谢谢！！！！！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3081/1
