### ISSUE TITLE
怎么配置vlan？

### ISSUE THREAD

**Issue by tx5866** [istoreos/istoreos#577]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
家里的光猫到路由只有一条网线，需要单线复用上网和iptv
在光猫侧已经区分了vlan，但是在istoreos没找到相关的配置

istoreos 好像删掉了 openwrt 里面的接口的的物理设置。

我在openwrt是参考这个视频做的单线复用的配置的
https://www.bilibili.com/video/BV1AB4y1C7WB/?vd_source=cd728c2d7b8067f7ebeae6fb35e38dcd

### (2) 路由器型号和固件版本

A：n5105

**Comment by jjm2473** [comment]
不是删除了，而是你看的教程是老版本luci的（2018年以前），新版本都在“网络”-“接口”-“设备”页里面配置vlan，或者在填接口的时候使用类似`eth0.100`这样的名称

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3075/1
