### ISSUE TITLE
请求添加对NanoPi R5C的支持

### ISSUE THREAD

**Issue by tcbt999** [istoreos/istoreos#578]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：NanoPi R5C 刷入R5S版本无法启动。

### (2) 路由器型号和固件版本

A：NanoPi R5C   openwrt  R5S所有版本

### (3) 详细日志和/或截图

A：可以刷入，但无法启动。

**Comment by jjm2473** [comment]
官方的R5C和R5S使用同一个固件吗

**Comment by tcbt999** [comment]
有的可以编译成一个固件，比如官方的friendlywrt，骷髅头是分下来的。

**Comment by GreenTeodoro839** [comment]
> 官方的R5C和R5S使用同一个固件吗

跟r2s r2c差不多，网口配置不一样

**Comment by tcbt999** [comment]
是的

**Comment by tcbt999** [comment]
官方的R5C和R5S确实使用同一个固件

**Comment by jjm2473** [comment]
如果只是PHY芯片不一样，那就简单了

**Comment by jjm2473** [comment]
如果只是PHY芯片不一样，应该不至于不能启动

**Comment by GreenTeodoro839** [comment]
> 如果只是PHY芯片不一样，应该不至于不能启动

我也不太明白，可以参考一下骷颅头的r5c固件

**Comment by antbuster** [comment]
R5S固件可以用，但是一个USB口无法识别，LED灯无用，LAN口错乱。还有相比官方固件，发热严重

**Comment by jjm2473** [comment]
> R5S固件可以用，但是一个USB口无法识别，LED灯无用，LAN口错乱。还有相比官方固件，发热严重

发热是因为没驱动风扇？

**Comment by bearcolin** [comment]
5C比5S还多了个m.2的无线网卡 rtl8822ce

**Comment by v1006945671** [comment]
我刷了，可以启动，但是灯错乱的，多了一个不存在的网口

**Comment by jjm2473** [comment]
最新固件已经支持了，跟R5S同一个固件，如果之前刷了R5S的固件，要全新刷机才有效。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3074/1
