### ISSUE TITLE
2.5g网卡

### ISSUE THREAD

**Issue by zb737472783** [istoreos/istoreos#58]
![image](https://user-images.githubusercontent.com/2137950/164953540-6ac7cd82-fdc0-4990-b560-25ef4aa043c5.png)
网卡是225型号 现在是不是没有跑在2500m上

**Comment by zb737472783** [comment]
这是wan口

**Comment by zb737472783** [comment]
这是wan口,上游是RedmiAX5400电竞版 接在2.5g口上

**Comment by jannson** [comment]
从你的截图上看，没协商在 2500Mb/s 上。

方便的化，换 https://fw.koolcenter.com/LEDE_X64_fw867/ 这个我们老固件，看看能否跑到 2.5G。
新老固件目前是独立维护的，可以对比看看。

**Comment by zb737472783** [comment]
目前不是很方便测试LEDE,我的路由是2个2.5g网口 笔记本接一个lan口 可以识别2.5g 另一个是wan口 接mesh路由,只显示1g,我把笔记本直接接mesh路由可以识别2.5g,就是说mesh路由的2.5g是正常的.
换成软路由就变成1g了.感觉是lan口驱动的2.5g没问题, wan口就驱动不起来的样子.

**Comment by jannson** [comment]
之前遇到有个驱动有这样的问题，后来更新了 5.10 的驱动过来貌似好了。也许是类似的问题。

**Comment by zb737472783** [comment]
那我就等着更新就可以吧

**Comment by zb737472783** [comment]
大佬,后面更新的时候别忘记我这个2.5g的驱动啊...

**Comment by jannson** [comment]
MARK

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3796/1
