### ISSUE TITLE
我的是树莓派4b, 安装passwall时提示各缺少依赖iptables-mod-socket, 安装openclash提示缺少kmod-inet-diag，hello world创建节点时无法通过剪切板导入节点。目前只有SSR好用。

### ISSUE THREAD

**Issue by tinkchan** [istoreos/istoreos#581]
我的是树莓派4b, 安装passwall时提示没有库能提供依赖iptables-mod-socket, 安装openclash提示缺少kmod-inet-diag，hello world创建节点时无法通过剪切板导入节点。目前只有SSR好用。

**Comment by jjm2473** [comment]
passwall2才需要依赖iptables-mod-socket，passwall不需要。iptables-mod-socket 和 kmod-ipt-socket 实际上已经包含在tproxy模块，只需要空包即可，可以从这里下载 https://istore.linkease.com/repo/all/meta/ 。

**Comment by jjm2473** [comment]
参考这个issue，都是一样的 https://github.com/istoreos/istoreos/issues/570

**Comment by tinkchan** [comment]
安装上了，谢谢。

**Comment by jjm2473** [comment]
升级istore以后应该就可以安装了
