### ISSUE TITLE
iptv 单线复用 vlan出错

### ISSUE THREAD

**Issue by tx5866** [istoreos/istoreos#582]
### (1) 具体问题

A：iptv 单线复用 vlan出错

### (2) 路由器型号和固件版本

A：路由型号 N5105

### (3) 详细日志和/或截图

A：路由配置：
![image](https://user-images.githubusercontent.com/84910032/217837934-cee13fbc-b2d7-4389-b8a4-59dcc3be6365.png)
配置2:
![image](https://user-images.githubusercontent.com/84910032/217838023-5d7688f3-53c1-4afe-89c3-cc9bbbdae046.png)
配置3：
![image](https://user-images.githubusercontent.com/84910032/217838119-21eed892-9e3f-46e0-bc29-09a6423545eb.png)

光猫配置
<img width="326" alt="1675952443611" src="https://user-images.githubusercontent.com/84910032/217838390-f5ecc0f5-a4a5-4f26-ae75-809647871ba7.png">
<img width="328" alt="1675952450029" src="https://user-images.githubusercontent.com/84910032/217838436-7bfd7924-d1b7-4fba-94c3-b025982b1278.png">
<img width="328" alt="1675952450029" src="https://user-images.githubusercontent.com/84910032/217838459-7c93c6ee-5f81-437c-a0db-64704cc133d2.png">

network的配置：

config interface 'loopback'
        option device 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fd8c:3cf9:9a05::/48'

config interface 'wan'
        option proto 'pppoe'
        option username '0755040@163.gd'
        option password 'paas'
        option device 'eth0'

config interface 'wan6'
        option device 'eth0'
        option proto 'dhcpv6'

config device
        option name 'br-lan'
        option type 'bridge'
        list ports 'eth1'
        list ports 'eth2'

config interface 'lan'
        option device 'br-lan'
        option proto 'static'
        option netmask '255.255.255.0'
        option ip6assign '60'
        option defaultroute '0'
        list ipaddr '192.168.2.1/24'

config interface 'docker'
        option device 'docker0'
        option proto 'none'
        option auto '0'

config device
        option type '8021q'
        option ifname 'eth0'
        option vid '2'
        option name 'eth0.2'

config device
        option type '8021q'
        option ifname 'eth0'
        option vid '3'
        option name 'eth0.3'

config interface 'lan1'
        option proto 'static'
        option device 'eth3'

config device
        option type 'bridge'
        option name 'iptv'
        list ports 'eth0.3'
        list ports 'eth3'

config interface 'iptv'
        option proto 'none'
        option device **'iptv'**

**Comment by jjm2473** [comment]
eth3已经作为一个逻辑接口了？那就不能作为桥接了。

**Comment by jjm2473** [comment]
也就是删掉
```
config interface 'lan1'
    option proto 'static'
    option device 'eth3'
```

**Comment by locis08** [comment]
请问问题解决了吗？我也遇到这个问题，不知道怎么解决。感谢

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3071/1
