### ISSUE TITLE
希望添加对H68K和H66K的支持，谢谢大佬

### ISSUE THREAD

**Issue by littleLice** [istoreos/istoreos#585]
### 希望添加对同样是RK3568的H68K和H66K的支持，谢谢大佬！

**Comment by jjm2473** [comment]
他们连原理图都没公开，不知道怎么改dts

**Comment by littleLice** [comment]
> 他们连原理图都没公开，不知道怎么改dts
@jjm2473 
大佬帮忙看一下这是不是dts相关的资料。
[百度网盘链接](https://pan.baidu.com/s/1vQWkFWKSpl4UOCf-Izii1g?pwd=1234)  
提取码：1234

**Comment by jjm2473** [comment]
谢谢，我看看

**Comment by jjm2473** [comment]
dts文件不知道是什么哪个内核版本的。原理图有啥好藏着掖着的，3568方案原理图早就烂大街了，都是大同小异，真不知道hinlink在想什么。

**Comment by jjm2473** [comment]
好像他们的固件或者内核代码也没公开

**Comment by littleLice** [comment]
> dts文件不知道是什么哪个内核版本的。原理图有啥好藏着掖着的，3568方案原理图早就烂大街了，都是大同小异，真不知道hinlink在想什么。

真没必要藏着掖着，开源让大家参与不成才能良性发展吗

**Comment by littleLice** [comment]
> 好像他们的固件或者内核代码也没公开

这是产品经理的QQ，大佬有兴趣适配的话可以联系一下502995956

**Comment by jjm2473** [comment]
最近厂商有找过我们，他们可能会自己PR代码支持

**Comment by ks-bao** [comment]
给力，可能很快就有了。

**Comment by jjm2473** [comment]
今天会上架

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3068/1
