### ISSUE TITLE
状态——实时监控无法打开

### ISSUE THREAD

**Issue by kimdir-sh** [istoreos/istoreos#586]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ X] 没有类似的issue

### (1) 具体问题

A：状态菜单---实时监控打开是空白页。在其他电脑访问是提示（loalhost ip）拒绝访问。

### (2) 路由器型号和固件版本

A：j4125 PVE istoreos 20230203

### (3) 详细日志和/或截图

A：
![IMAGE 2023-02-12 22:13:58](https://user-images.githubusercontent.com/122258382/218316208-7a78a74b-610b-490a-8384-988aca1a42f2.jpg)

![IMAGE 2023-02-12 22:13:55](https://user-images.githubusercontent.com/122258382/218316202-7fb6fdab-57bc-4e8e-944b-bbfb8f906b6e.jpg)

**Comment by jjm2473** [comment]
localhost？如果你的luci事通过转发访问的，netdata使用的端口不是80，看看是不是没转发端口出来

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3067/1
