### ISSUE TITLE
什么时候支持R6S啊?

### ISSUE THREAD

**Issue by jian263994241** [istoreos/istoreos#589]
手上的r6s吃灰了

**Comment by littleLice** [comment]
手里有个H68K有个H66K也在吃灰，感觉istoreOS维护的比其他的好，轻nas也很吸引人，但是不适配┭┮﹏┭┮

**Comment by jjm2473** [comment]
> 手里有个H68K有个H66K也在吃灰，感觉istoreOS维护的比其他的好，轻nas也很吸引人，但是不适配┭┮﹏┭┮

主要没人PR啊，不可能一个人维护这么多设备

**Comment by jjm2473** [comment]
重复 https://github.com/istoreos/istoreos/issues/564

**Comment by jjm2473** [comment]
测试固件22.03.4已经支持R6S/R6C https://github.com/istoreos/istoreos/issues/716

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3064/1
