### ISSUE TITLE
excalidraw能安装，但无法运行

### ISSUE THREAD

**Issue by waxjoy** [istoreos/istoreos#591]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：excalidraw能安装，但无法运行

### (2) 路由器型号和固件版本

A：Raspberry Pi 4 Model B Rev 1.4 & iStoreOS 21.02.3 2023020317

### (3) 详细日志和/或截图

A：
![image](https://user-images.githubusercontent.com/30931572/218807608-25830831-dbef-4425-8747-a791616c5611.png)

**Comment by jjm2473** [comment]
这个插件好像值支持x86平台

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3062/1
