### ISSUE TITLE
关于树莓派4B启用SMABA,挂在硬盘，进不去目录的问题

### ISSUE THREAD

**Issue by GD2021** [istoreos/istoreos#592]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
![image](https://user-images.githubusercontent.com/81171294/219036566-e8d588f0-64a5-40bc-8d37-bea5543ff362.png)

A：

### (3) 详细日志和/或截图

A：
![image](https://user-images.githubusercontent.com/81171294/219036317-1055a895-3a60-47af-a272-10f88df80d50.png)
![image](https://user-images.githubusercontent.com/81171294/219036388-052fe79b-9b61-4896-80d8-11af27a8f194.png)
![image](https://user-images.githubusercontent.com/81171294/219036476-d8b6faec-06b0-4d53-90b5-38b826687c00.png)

**Comment by GD2021** [comment]
![image](https://user-images.githubusercontent.com/81171294/219036737-7cbc62ca-ca48-43eb-a31b-2be8c261e6a1.png)

**Comment by GD2021** [comment]
苹果手机访问也失败
![image](https://user-images.githubusercontent.com/81171294/219037113-2ed8947a-e94d-40a9-81e3-f05c46c0f51f.png)
![image](https://user-images.githubusercontent.com/81171294/219037146-1ecfb84c-aa60-4854-8c68-bf4be8e4dd07.png)

**Comment by jjm2473** [comment]
1. samba默认是没有用户名密码的，如果要设置账号密码，可以在“网络存储”-“统一文件共享”里面配置，而且注意默认不能使用root用户名
2. windows里面应该是使用`\\192.168.100.1`，而不是`//*`

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3061/1
