### ISSUE TITLE
硬盘挂载失败

### ISSUE THREAD

**Issue by memorycan** [istoreos/istoreos#593]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
拔下硬盘再插上后无法挂载，多次重启，恢复出厂还是不行
### (1) 具体问题

A：硬盘无法挂载

### (2) 路由器型号和固件版本

A：X86 iStoreOS 21.02.3 2023020316

### (3) 详细日志和/或截图
mount: /mnt/data_sda1: mount(2) system call failed: No error informtion.
[A：
![QQ截图20230216010301](https://user-images.githubusercontent.com/125489749/219100361-438a42c5-c221-410f-9926-6f0b4ed93cb0.png)
![image](https://user-images.githubusercontent.com/125489749/219100493-c32c380c-cdf4-4b36-a100-94b9262496e2.png)
![image](https://user-images.githubusercontent.com/125489749/219100864-59c17a99-9352-4577-b63b-53b120e5bf24.png)

**Comment by jjm2473** [comment]
应该是文件系统损坏，重新格式化或者使用 e2fsck 命令修复，详情自己Google。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3060/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3725/2
