### ISSUE TITLE
Root diskfull 

### ISSUE THREAD

**Issue by edoxcf** [istoreos/istoreos#594]
路由器型号和固件版本
X86 iStoreOS 21.02.3 2023020316

问题：
安装可道云一段时间后，想重新删除安装。于是停用可道云后，我用文件管理器删除移动硬盘根目录下的\kodexplore，但删除失败，查看目录，发现大部分文件已经删除，但...\data目录下有临时文件无法删除。 
然后我尝试重新安装可道云，出现 root disk full!的提示。我再安装其他软件业同样出现该情况，均无法安装。
![image](https://user-images.githubusercontent.com/67780854/219261938-b2875c2e-b5fb-4ef0-8aba-ed98b7604102.png)

**Comment by jjm2473** [comment]
根目录满了吧，想办法清理掉

**Comment by jjm2473** [comment]
这个报错是根目录满了，也就是系统区，跟你的移动硬盘无关。大概是因为你把docker设置到根目录了，或者把文件下载到根目录了，不然不太可能满

**Comment by adyh888** [comment]
增加一个未格式化的磁盘，扩容[/overlay]，详情不懂的可以加wechat:liuweiweiadyh88

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3059/1
