### ISSUE TITLE
RPC: fragment too large:

### ISSUE THREAD

**Issue by hubumulity** [istoreos/istoreos#599]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
docker安装了甜糖，好像流量一大就会出现
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：iStoreOS 21.02.3 2022121613 / LuCI istoreos-21.02 branch git-22.332.46448-a322196

### (3) 详细日志和/或截图

A：Fri Feb 17 18:16:28 2023 kern.notice kernel: [670206.037685] RPC: fragment too large: 369295616
Fri Feb 17 18:16:37 2023 kern.notice kernel: [670214.820866] RPC: fragment too large: 369295616
Fri Feb 17 18:17:45 2023 kern.notice kernel: [670283.031767] RPC: fragment too large: 369295616
Fri Feb 17 18:17:46 2023 kern.notice kernel: [670283.797890] RPC: fragment too large: 1195725856
Fri Feb 17 18:18:20 2023 kern.notice kernel: [670317.976660] RPC: fragment too large: 369295616
Fri Feb 17 18:18:31 2023 kern.notice kernel: [670329.043341] RPC: fragment too large: 1195725856
Fri Feb 17 18:18:37 2023 kern.notice kernel: [670334.653820] RPC: fragment too large: 1195725856
Fri Feb 17 18:19:16 2023 kern.notice kernel: [670373.701883] RPC: fragment too large: 1195725856

**Comment by jjm2473** [comment]
要不跟这个帖子讨论下？可能人家已经解决了 https://github.com/coolsnowwolf/lede/issues/6876

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3057/1
