### ISSUE TITLE
[√ ] 在路由器里安装docker又安装了宝塔都正常工作外网也能访问，重启路由器后，docker也能自动启动镜像，但是宝塔网管理页面无法访问，需要反复重启几次才有概率成功

### ISSUE THREAD

**Issue by sd3970566** [istoreos/istoreos#601]
在路由器里安装docker又安装了宝塔都正常工作外网也能访问，重启路由器后，docker也能自动启动镜像，但是宝塔网管理页面无法访问，需要反复重启几次才有概率成功
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [√ ] 没有类似的issue

### (1) 具体问题

A：在路由器里安装docker又安装了宝塔都正常工作外网也能访问，重启路由器后，docker也能自动启动镜像，但是宝塔网管理页面无法访问，需要反复重启几次才有概率成功！有时候意外断电的情况下，导致重启路由器。网站服务是否正常开启纯靠运气··就不太给力啊，希望能够修复。  

### (2) 路由器型号和固件版本

A：固件版本
iStoreOS 21.02.3 2023020316
内核版本
5.4.188

### (3) 详细日志和/或截图

A：我路由器重启了好几遍。 日志很多。具体也不知道从哪里发起。我就docker的事件随便就近的时间发一段  和  路由器的日志 就近的发一段吧
 【docker日志】>这个是最后一次重启成功 启动宝塔服务后的日志。我就没再重启了
：[2023-02-19 00:04:03] container exec_die Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:08] container exec_create: /bin/sh -c curl -sf http://127.0.0.1:8888/btpanel || exit 1 Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:08] container exec_start: /bin/sh -c curl -sf http://127.0.0.1:8888/btpanel || exit 1 Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:08] container exec_die Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:13] container exec_create: /bin/sh -c curl -sf http://127.0.0.1:8888/btpanel || exit 1 Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:13] container exec_start: /bin/sh -c curl -sf http://127.0.0.1:8888/btpanel || exit 1 Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:13] container exec_die Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:18] container exec_create: /bin/sh -c curl -sf http://127.0.0.1:8888/btpanel || exit 1 Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:18] container exec_start: /bin/sh -c curl -sf http://127.0.0.1:8888/btpanel || exit 1 Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:18] container exec_die Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:23] container exec_create: /bin/sh -c curl -sf http://127.0.0.1:8888/btpanel || exit 1 Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:23] container exec_start: /bin/sh -c curl -sf http://127.0.0.1:8888/btpanel || exit 1 Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:24] container exec_die Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:29] container exec_create: /bin/sh -c curl -sf http://127.0.0.1:8888/btpanel || exit 1 Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:29] container exec_start: /bin/sh -c curl -sf http://127.0.0.1:8888/btpanel || exit 1 Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 Container Name: centos
[2023-02-19 00:04:29] container exec_die Container ID: 1530e8d2cfff75c14d90cb8bd3e292ec99d713410fced0419d161d52cd974606 

========================我是分隔符=========================
【路由器日志】>这个是最后一次重启成功 启动宝塔服务后的日志。我就没再重启了
Sat Feb 18 23:49:57 2023 daemon.info dnsmasq[4221]: using only locally-known addresses for domain invalid
Sat Feb 18 23:49:57 2023 daemon.info dnsmasq[4221]: using only locally-known addresses for domain bind
Sat Feb 18 23:49:57 2023 daemon.info dnsmasq[4221]: using only locally-known addresses for domain lan
Sat Feb 18 23:49:57 2023 daemon.warn dnsmasq[4221]: no servers found in /tmp/resolv.conf.d/resolv.conf.auto, will retry
Sat Feb 18 23:49:57 2023 daemon.info dnsmasq[4221]: read /etc/hosts - 4 addresses
Sat Feb 18 23:49:57 2023 daemon.info dnsmasq[4221]: read /tmp/hosts/dhcp.cfg01411c - 6 addresses
Sat Feb 18 23:49:57 2023 authpriv.info dropbear[4311]: Not backgrounding
Sat Feb 18 23:49:57 2023 kern.warn kernel: [   12.126495] xt_FULLCONENAT: warning: failed to register a conntrack notifier. Disable active GC for mappings.
Sat Feb 18 23:49:57 2023 user.notice : Added device handler type: bonding
Sat Feb 18 23:49:57 2023 user.notice : Added device handler type: 8021ad
Sat Feb 18 23:49:57 2023 user.notice : Added device handler type: 8021q
Sat Feb 18 23:49:57 2023 user.notice : Added device handler type: macvlan
Sat Feb 18 23:49:57 2023 user.notice : Added device handler type: veth
Sat Feb 18 23:49:57 2023 user.notice : Added device handler type: bridge
Sat Feb 18 23:49:57 2023 user.notice : Added device handler type: Network device
Sat Feb 18 23:49:57 2023 user.notice : Added device handler type: tunnel
Sat Feb 18 23:49:57 2023 user.notice wan_drop: current proto pppoe
Sat Feb 18 23:49:57 2023 daemon.notice procd: /etc/rc.d/S39blockmount: /dev/sda1 UUID=292A-A6AD TYPE=vfat LABEL=kernel MOUNT=/boot
Sat Feb 18 23:49:57 2023 daemon.notice procd: /etc/rc.d/S39blockmount: /dev/sda2 UUID=0531f9ed-9895142a-7e7cd6b6-ad2d7ed5 TYPE=squashfs LABEL= MOUNT=/rom
Sat Feb 18 23:49:57 2023 daemon.notice procd: /etc/rc.d/S39blockmount: /dev/sda3 UUID=5b0c6698-8a6a-4f09-a365-41fd8ec55e54 TYPE=ext4 LABEL=etc MOUNT=/overlay
Sat Feb 18 23:49:57 2023 daemon.notice procd: /etc/rc.d/S39blockmount: /dev/sdb1 UUID=e4a21fee-be00-47dd-85e5-9815ecddc8a9 TYPE=ext4 LABEL= MOUNT=/mnt/sata2-1
Sat Feb 18 23:49:57 2023 daemon.notice procd: /etc/rc.d/S45nfs: exportfs: could not open /var/lib/nfs/.etab.lock for locking: errno 2 (No such file or directory)
Sat Feb 18 23:49:57 2023 daemon.notice procd: /etc/rc.d/S45nfs: point 1
Sat Feb 18 23:49:57 2023 daemon.notice procd: /etc/rc.d/S45nfs: exportfs: could not open /var/lib/nfs/.etab.lock for locking: errno 2 (No such file or directory)
Sat Feb 18 23:49:57 2023 daemon.notice procd: /etc/rc.d/S45nfs: exportfs: can't lock /var/lib/nfs/etab for writing
Sat Feb 18 23:49:57 2023 daemon.notice procd: /etc/rc.d/S45nfs: point 2
Sat Feb 18 23:49:57 2023 daemon.notice procd: /etc/rc.d/S45nfs: point 3
Sat Feb 18 23:49:57 2023 cron.err crond[5112]: crond (busybox 1.33.2) started, log level 5
Sat Feb 18 23:49:58 2023 kern.info kernel: [   12.940308] 8021q: adding VLAN 0 to HW filter on device eth1
Sat Feb 18 23:49:58 2023 kern.info kernel: [   12.942565] br-lan: port 1(eth1) entered blocking state
Sat Feb 18 23:49:58 2023 kern.info kernel: [   12.944568] br-lan: port 1(eth1) entered disabled state
Sat Feb 18 23:49:58 2023 kern.info kernel: [   12.946624] device eth1 entered promiscuous mode
Sat Feb 18 23:49:58 2023 daemon.notice netifd: Interface 'lan' is enabled
Sat Feb 18 23:49:58 2023 daemon.notice netifd: Interface 'lan' is setting up now
Sat Feb 18 23:49:58 2023 daemon.notice netifd: Interface 'lan' is now up
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: reading /tmp/resolv.conf.d/resolv.conf.auto
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: using only locally-known addresses for domain test
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: using only locally-known addresses for domain onion
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: using only locally-known addresses for domain localhost
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: using only locally-known addresses for domain local
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: using only locally-known addresses for domain invalid
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: using only locally-known addresses for domain bind
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: using only locally-known addresses for domain lan
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: using nameserver 114.114.114.114#53
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: using nameserver 223.5.5.5#53
Sat Feb 18 23:49:58 2023 daemon.info dnsmasq[4221]: using nameserver 119.29.29.29#53
Sat Feb 18 23:49:58 2023 kern.info kernel: [   12.976062] 8021q: adding VLAN 0 to HW filter on device eth2
Sat Feb 18 23:49:58 2023 kern.info kernel: [   12.977931] br-lan: port 2(eth2) entered blocking state
Sat Feb 18 23:49:58 2023 kern.info kernel: [   12.979620] br-lan: port 2(eth2) entered disabled state
Sat Feb 18 23:49:58 2023 kern.info kernel: [   12.981428] device eth2 entered promiscuous mode
Sat Feb 18 23:49:58 2023 kern.info kernel: [   13.008213] 8021q: adding VLAN 0 to HW filter on device eth3
Sat Feb 18 23:49:58 2023 kern.info kernel: [   13.010356] br-lan: port 3(eth3) entered blocking state
Sat Feb 18 23:49:58 2023 kern.info kernel: [   13.012289] br-lan: port 3(eth3) entered disabled state
Sat Feb 18 23:49:58 2023 kern.info kernel: [   13.014656] device eth3 entered promiscuous mode
Sat Feb 18 23:49:58 2023 daemon.notice netifd: Interface 'loopback' is enabled
Sat Feb 18 23:49:58 2023 daemon.notice netifd: Interface 'loopback' is setting up now
Sat Feb 18 23:49:58 2023 daemon.notice netifd: Interface 'loopback' is now up
Sat Feb 18 23:49:58 2023 daemon.notice netifd: Interface 'wan' is enabled
Sat Feb 18 23:49:58 2023 daemon.notice netifd: Interface 'wan6' is enabled
Sat Feb 18 23:49:58 2023 kern.info kernel: [   13.044087] 8021q: adding VLAN 0 to HW filter on device eth0
Sat Feb 18 23:49:58 2023 daemon.notice netifd: Network device 'lo' link is up
Sat Feb 18 23:49:58 2023 daemon.notice netifd: Interface 'loopback' has link connectivity
Sat Feb 18 23:49:58 2023 user.notice firewall: Reloading firewall due to ifup of lan (br-lan)
Sat Feb 18 23:49:58 2023 kern.warn kernel: [   13.522569] xt_FULLCONENAT: warning: failed to register a conntrack notifier. Disable active GC for mappings.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Found user 'nobody' (UID 65534) and group 'nogroup' (GID 65534).
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Successfully dropped root privileges.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: avahi-daemon 0.8 starting up.
Sat Feb 18 23:49:58 2023 daemon.warn avahi-daemon[6118]: WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: No service file found in /etc/avahi/services.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Joining mDNS multicast group on interface br-lan.IPv6 with address fd32:ce2b:ffe0::1.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: New relevant interface br-lan.IPv6 for mDNS.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Joining mDNS multicast group on interface br-lan.IPv4 with address 192.168.9.1.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: New relevant interface br-lan.IPv4 for mDNS.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Joining mDNS multicast group on interface lo.IPv6 with address ::1.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: New relevant interface lo.IPv6 for mDNS.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: New relevant interface lo.IPv4 for mDNS.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Network interface enumeration completed.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Registering new address record for fd32:ce2b:ffe0::1 on br-lan.*.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Registering new address record for 192.168.9.1 on br-lan.IPv4.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Registering new address record for ::1 on lo.*.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Registering new address record for 127.0.0.1 on lo.IPv4.
Sat Feb 18 23:49:58 2023 daemon.info avahi-daemon[6118]: Registering HINFO record with values 'X86_64'/'LINUX'.
Sat Feb 18 23:49:58 2023 user.notice ucitrack: Setting up /etc/config/dhcp reload dependency on /etc/config/network
Sat Feb 18 23:49:58 2023 user.notice ucitrack: Setting up /etc/config/network reload dependency on /etc/config/wireless
Sat Feb 18 23:49:58 2023 user.notice ucitrack: Setting up /etc/config/luci-splash reload dependency on /etc/config/firewall
Sat Feb 18 23:49:59 2023 user.notice ucitrack: Setting up /etc/config/qos reload dependency on /etc/config/firewall
Sat Feb 18 23:49:59 2023 user.notice ucitrack: Setting up /etc/config/miniupnpd reload dependency on /etc/config/firewall
Sat Feb 18 23:49:59 2023 user.notice ucitrack: Setting up /etc/config/odhcpd reload dependency on /etc/config/dhcp
Sat Feb 18 23:49:59 2023 user.notice ucitrack: Setting up non-init /etc/config/fstab reload handler: /sbin/block mount
Sat Feb 18 23:49:59 2023 user.notice ucitrack: Setting up /etc/config/system reload trigger for non-procd /etc/init.d/led
Sat Feb 18 23:49:59 2023 daemon.err odhcpd[4821]: Failed to send to ff02::1%lan@br-lan (Address not available)
Sat Feb 18 23:49:59 2023 user.notice ucitrack: Setting up /etc/config/luci_statistics reload dependency on /etc/config/system
Sat Feb 18 23:49:59 2023 user.notice ucitrack: Setting up /etc/config/dhcp reload dependency on /etc/config/system
Sat Feb 18 23:49:59 2023 user.notice ucitrack: Setting up /etc/config/cifs reload trigger for non-procd /etc/init.d/cifs
Sat Feb 18 23:49:59 2023 user.notice ucitrack: Setting up /etc/config/nfs reload trigger for non-procd /etc/init.d/nfs
Sat Feb 18 23:49:59 2023 daemon.info smartd[7238]: smartd 7.2 2020-12-30 r5155 [x86_64-linux-5.4.188] (localbuild)
Sat Feb 18 23:49:59 2023 daemon.info smartd[7238]: Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org
Sat Feb 18 23:49:59 2023 daemon.info smartd[7238]: Opened configuration file /etc/smartd.conf
Sat Feb 18 23:49:59 2023 daemon.crit smartd[7238]: File /etc/smartd.conf line 3 (drive DEFAULT): Missing argument to -n Directive
Sat Feb 18 23:49:59 2023 daemon.crit smartd[7238]: Valid arguments to -n Directive are:
Sat Feb 18 23:49:59 2023 daemon.crit smartd[7238]: never[,N][,q], sleep[,N][,q], standby[,N][,q], idle[,N][,q]
Sat Feb 18 23:49:59 2023 daemon.crit smartd[7238]: Configuration file /etc/smartd.conf has fatal syntax errors.
Sat Feb 18 23:49:59 2023 daemon.info smartd[7238]: Monitoring 0 ATA/SATA, 0 SCSI/SAS and 0 NVMe devices
Sat Feb 18 23:49:59 2023 daemon.notice procd: /etc/rc.d/S96appfilter: uci: Entry not found
Sat Feb 18 23:49:59 2023 daemon.notice procd: /etc/rc.d/S96appfilter: uci: Entry not found
Sat Feb 18 23:49:59 2023 daemon.err rmmod: module is not loaded
Sat Feb 18 23:49:59 2023 daemon.info avahi-daemon[6118]: Server startup complete. Host name is iStoreOS.local. Local service cookie is 2337885208.
Sat Feb 18 23:49:59 2023 daemon.info smartd[7238]: smartd received signal 15: Terminated
Sat Feb 18 23:49:59 2023 daemon.info smartd[7238]: smartd is exiting (exit status 0)
Sat Feb 18 23:50:01 2023 daemon.info samba4-server: io_uring module found, enabling VFS io_uring. (also needs Kernel 5.4+ Support)
Sat Feb 18 23:50:01 2023 daemon.info samba4-server: io_uring module found, enabling VFS io_uring. (also needs Kernel 5.4+ Support)
Sat Feb 18 23:50:01 2023 daemon.info samba4-server: io_uring module found, enabling VFS io_uring. (also needs Kernel 5.4+ Support)
Sat Feb 18 23:50:01 2023 daemon.err nmbd[8223]: [2023/02/18 23:50:01.280593,  0] ../../lib/util/become_daemon.c:136(daemon_ready)
Sat Feb 18 23:50:01 2023 daemon.err nmbd[8223]:   daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
Sat Feb 18 23:50:01 2023 daemon.notice procd: /etc/rc.d/S99dockerd: iptables: No chain/target/match by that name.
Sat Feb 18 23:50:01 2023 daemon.err smbd[8222]: [2023/02/18 23:50:01.599960,  0] ../../lib/util/become_daemon.c:136(daemon_ready)
Sat Feb 18 23:50:01 2023 daemon.err smbd[8222]:   daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
Sat Feb 18 23:50:01 2023 daemon.err smbd[8222]: [2023/02/18 23:50:01.600298,  0] ../../source3/smbd/server.c:1083(smbd_open_one_socket)
Sat Feb 18 23:50:01 2023 daemon.err smbd[8222]:   smbd_open_one_socket: open_socket_in: Address not available
Sat Feb 18 23:50:01 2023 daemon.err smbd[8222]: [2023/02/18 23:50:01.600447,  0] ../../source3/smbd/server.c:1083(smbd_open_one_socket)
Sat Feb 18 23:50:01 2023 daemon.err smbd[8222]:   smbd_open_one_socket: open_socket_in: Address not available
Sat Feb 18 23:50:01 2023 daemon.notice procd: /etc/rc.d/S99nfsd: point 1
Sat Feb 18 23:50:01 2023 daemon.notice procd: /etc/rc.d/S99nfsd: point 2
Sat Feb 18 23:50:01 2023 daemon.notice procd: /etc/rc.d/S99nfsd: point 3
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[4221]: exiting on receipt of SIGTERM
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: Connected to system UBus
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: started, version 2.85 cachesize 150
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: DNS service limited to local subnets
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: UBus support enabled: connected to system bus
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq-dhcp[8991]: DHCP, IP range 192.168.9.100 -- 192.168.9.249, lease time 12h
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain test
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain onion
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain localhost
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain local
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain invalid
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain bind
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain lan
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: reading /tmp/resolv.conf.d/resolv.conf.auto
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain test
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain onion
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain localhost
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain local
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain invalid
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain bind
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using only locally-known addresses for domain lan
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using nameserver 114.114.114.114#53
Sat Feb 18 23:50:02 2023 daemon.info dnsmasq[8991]: using nameserver 223.5.5.5#53

**Comment by jjm2473** [comment]
先确认一下，容器之间与依赖关系吗？如果有，那可能失败，这是docker自己的问题

**Comment by jjm2473** [comment]
你发日志应该发启动失败的情况下的日志

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3055/1
