### ISSUE TITLE
倍控j4125esxi虚拟istoreos，wan口和esxi管理口重合，虽然修改过WAN口，依然无效。

### ISSUE THREAD

**Issue by dreamtang113** [istoreos/istoreos#602]
倍控j4125esxi（版本7.03）虚拟istoreos，wan口和esxi管理口重合（esxi的管理口默认eth0，不是没有考虑过修改过，一修改就无法连接，不知道是固件还是软件的问题），把eth3改成WAN口，把br-lan设置成eth0，eth1，eth2，WAN口就没有数据。

**Comment by jjm2473** [comment]
看起来是你的esxi虚拟机网卡配置的问题，试试虚拟机的网卡不要添加esxi管理口

**Comment by Masterwillty** [comment]
ESXI管理口要在ESXI的程序中固定，直接插显示器的那个。Istoreos的口在虚拟机中先直通网口，然后再在网页上自己调

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3054/1
