### ISSUE TITLE
istoreOS启动grub问题

### ISSUE THREAD

**Issue by 1nicky** [istoreos/istoreos#604]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by 1nicky** [comment]
（1）具体问题：iStoreOS启动grub直接进入iStoreOS（failsafe）模式，不能直接进入iStore模式。仅仅在每日断电很长一段时间，大概是一晚上左右，第二日通电后，就不能直接进入iStoreOS模式j。
（2）路由器型号和固件版本：J4125双网口I226——V2.5G；iStoreOS/x86_64_efi/istoreos-21.02.3-2023021714-x86-64-squashfs-combined-efi.img.gz
（3）截图
![image](https://user-images.githubusercontent.com/100368402/220168696-9051f664-7267-45ed-9cd5-399a3f1e42a3.png)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3052/1
