### ISSUE TITLE
transmission是否可以更新到4.0

### ISSUE THREAD

**Issue by PandaEgg** [istoreos/istoreos#605]
transmission已经更新到4.0 istoreos上是否可以更新到4.0

**Comment by jjm2473** [comment]
目前transmission实际使用的是官方openwrt 21.02.3对应的版本，如果没问题就不更新。
如果遇到了bug，或者有重大功能更新，istore才会自己编译新版本

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3051/1
