### ISSUE TITLE
frpc没有开启的选项

### ISSUE THREAD

**Issue by shen-lan** [istoreos/istoreos#606]
1. x86
2. istore商店安装 frp
3. 
![image](https://user-images.githubusercontent.com/21122615/220681403-36b2e428-6546-46f7-b1ee-8fecd11492fe.png)

**Comment by jjm2473** [comment]
这个插件本来就没有开关，安装以后就会开启。如果运行失败，看看系统日志就知道为啥了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3050/1
