### ISSUE TITLE
macOS 的 Chrome 无法登录 qBittorrent 的 WebUI

### ISSUE THREAD

**Issue by ramondsq** [istoreos/istoreos#607]
## 1.关于你要提交的问题
macOS 的 Chrome 无法登录 qBittorrent 的 WebUI ，换用 Windows 的 Chrome 就可以

### (1) 具体问题

A：macOS Ventura 13.2.1，Chrome 版本 110.0.5481.177（正式版本） (arm64)

### (2) 路由器型号和固件版本

A：x86，固件版本：iStoreOS 21.02.3 2023021714

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
那不是浏览器问题吗，反馈过来又有什么用

**Comment by jjm2473** [comment]
qb的webui是qb自带的，不是独立的插件。你遇到的问题要么出在浏览器上，要么出在qb上，要么就是你的配置有问题，怎么都不会联想到固件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3049/1
