### ISSUE TITLE
istoreos可否支持trubo acc？

### ISSUE THREAD

**Issue by Masterwillty** [istoreos/istoreos#608]
问题：能否支持istoreos上使用troubacc功能？
版本：最新固件，X86架构。
找了一些X86的troubacc插件装不上去，也没有找到自带这个功能

**Comment by jjm2473** [comment]
turboacc需要修改内核，可能导致内核兼容性变差，不能安装官方编译的内核模块，所以不打算支持

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3048/1
