### ISSUE TITLE
r2s  fq 怎么都用不了

### ISSUE THREAD

**Issue by Tony-N2** [istoreos/istoreos#615]
不管是passwall 还是 bypass或者其他，
只要一打开，r2s就无法ping 通外网。。（其他固件没这个问题）

要怎么看是哪里出问题。。。

**Comment by jjm2473** [comment]
估计节点问题或者配置问题。
如果没有其他人反馈，就关掉了

**Comment by jjm2473** [comment]
之后如果有人遇到翻墙问题，可以试试这里的离线安装包 https://github.com/AUK9527/Are-u-ok/tree/main/apps
