### ISSUE TITLE
docker的混杂模式MACVLAN无法分配IP

### ISSUE THREAD

**Issue by poloniumn** [istoreos/istoreos#617]
按照教程

https://doc.linkease.com/zh/guide/easepi/advanced.html#%E6%B7%B7%E6%9D%82%E6%A8%A1%E5%BC%8Fmacvlan
配置完成后，创建容器，在容器内使用命令

ip addr flush dev eth0 && udhcpc
提示

ip: can't send flush request: Operation not permitted，
无法分配到内网IP，只有自动分配的172 IP段。尝试用cat手动更改 /etc/hosts似乎也没用。

我看说明上是写了ARS2，我是X86板子直接安装，是不是不支持这个特性？还是哪里配置有问题。

于是按照我之前使用的linux系统的命令尝试手动创建macvlan网口，命令如下：
docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=br-lan   \ opwrtdocker

创建容器时直接指定网卡和IP，可以分配到IP，也可以访问容器，但是容器只能连接内网，无法访问外网，请问是否是哪里配置需要根据情况进行修改，我查了一下午也没找到什么好办法...

我不太清楚应该上传哪部分的日志，如果有需要哪里的日志请说明一下，谢了。

**Comment by jjm2473** [comment]
macvlan是不支持跟本机通讯的，如果连这个都不知道，就别用macvlan。如果要桥接本机的br-lan，而且要本机分配ip，那就直接用桥接就行，而不是macvlan。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3043/1
