### ISSUE TITLE
R5S重启时如果两个LAN口都接有正在工作的设备会不停重启

### ISSUE THREAD

**Issue by beiming42** [istoreos/istoreos#618]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

【R5S+iStoreOS 21.02.3 2023022415】
如果R5S重启的时候两个LAN口都接有正在工作的设备（比如一台路由器和一台PC），R5S重启后会每隔37s左右再次重启一次，不会停止。

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：FriendlyElec NanoPi R5S + iStoreOS 21.02.3 2023022415 / LuCI istoreos-21.02 branch git-23.037.57600-91128de

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
你有串口工具吗，能不能在重启时看到内核日志？

还有看看重启以后有没有`/sys/kernel/debug/crashlog`这个文件，如果有，提取出来发到这里

**Comment by jjm2473** [comment]
还可以测试下 20230203 版本的固件有没有这个问题

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3042/1
