### ISSUE TITLE
手贱更新软件包  求大佬帮忙

### ISSUE THREAD

**Issue by wanglongfei8899** [istoreos/istoreos#619]
手贱更新软件包 
![图片1](https://user-images.githubusercontent.com/75508757/221411487-4d5bea15-1f45-44f0-a2fd-40abdcd6ee50.png)
 有啥办法恢复不  不想重装

**Comment by jjm2473** [comment]
变成英文了？重启下下就会恢复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3041/1
