### ISSUE TITLE
请求对BCM43142/BCM943142HM驱动支持

### ISSUE THREAD

**Issue by S0DX** [istoreos/istoreos#621]
请求支持老旧无线网卡，x86平台，pcie插槽连接。N2800平台

**Comment by jjm2473** [comment]
先去查openwrt有没有支持，有的话，直接按照人家的教程就可以安装。使用最新的固件

**Comment by jjm2473** [comment]
`opkg update; opkg install kmod-b43 ` 应该就支持了

**Comment by S0DX** [comment]
> lspci能够看到网卡信息，但是使用dmesg可以看到返回消息Driver 'b43' was unable to register with bus_type 'bcma' because the bus was not initialized.

**Comment by jjm2473** [comment]
确实kmod-bcma不一致导致

**Comment by jjm2473** [comment]
已经修复，等固件发布

**Comment by S0DX** [comment]
此次更新后依然无法使用，dmsg显示dmesg | grep b43
[   14.501480] b43: module has no kallsyms
[   14.512942] b43legacy: module has no kallsyms

**Comment by jjm2473** [comment]
> 此次更新后依然无法使用，dmsg显示dmesg | grep b43 [ 14.501480] b43: module has no kallsyms [ 14.512942] b43legacy: module has no kallsyms

这两个只是警告，我加上的，意思是使用了openwrt官方的内核模块。

**Comment by jjm2473** [comment]
> 同时网络接口状态也无法查看，如有需要我可以提供主机网络映射地址提供调试。

不是说wifi吗，跟这个有什么关系？

**Comment by jjm2473** [comment]
你可以安装openwrt官方固件看看能否支持，如果可以，istoreos一般也可以。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3039/1
