### ISSUE TITLE
如何在LAN接口->物理设置中，启用IGMP 嗅探

### ISSUE THREAD

**Issue by wudingjian** [istoreos/istoreos#622]
igmpproxy | 0.2.1-4 已安装

我看防火墙中，也有IGMP协议，是针对wan的规则

L大的固件，是在LAN接口->物理设置->启用桥接，下面就有一个IGMP 嗅探。

这个主要是用于iptv的组播用的。

我想咨询一下，istoreos 目前支持LAN接口启用IGMP 嗅探吗？如果不支持，如何才能实现？请教了！麻烦知道的回复一下我，谢谢！

另外建议
1、msd_lite IPTV 组播也能增加到软件库或商店中。

2、软件商店中的，CUPS打印服务，安装好后，并没有带有各家厂商的常见打印机驱动（例如：foo2zjs），我想把路由器的usb接口，接在打印机上。启用打印机的无线打印功能。

**Comment by jjm2473** [comment]
应该在“设备”标签页里面，Lean的固件还是很老的luci，没有“设备”页签

**Comment by wudingjian** [comment]
> 

感谢回复，找到了。

**Comment by ttcdldxsby** [comment]
同istoreos,用22ssh,装了imgp,但是嗅探一直找不到在哪.请教楼主分享下在哪块?谢谢

**Comment by ttcdldxsby** [comment]
> > 
> 
> 感谢回复，找到了。

这个话题是关闭了是吗,请问如何找到iStoreOS igmp设置的,或者安装的什么版本?

**Comment by jjm2473** [comment]
网络-接口-设备

**Comment by ttcdldxsby** [comment]
谢谢好朋友,我一直以为,那个设备是在主菜单里来着.找遍了也没找到,原来是在网络接口的子菜单.多谢多谢.回家研究研究.

Liangbin Lian ***@***.***> 于2024年3月19日周二 02:43写道：

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2611/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3038/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3038/7
