### ISSUE TITLE
X86固件  运行一段时间后科学上网插件会丢失配置，只能卸掉重新安装才能用

### ISSUE THREAD

**Issue by YsWGYY** [istoreos/istoreos#623]
## 1.关于你要提交的问题
X86固件 安装科学上网插件使用一段时间后，插件点进去显示没有任何配置，目前使用了SSR+   PASSWALL   HELLO WORLD均出现这个问题，只能通过卸载后重新安装才可以正常使用

### (2) 路由器型号和固件版本
X86 64

**Comment by jjm2473** [comment]
什么版本的固件？
看看overlay空间还有多少

**Comment by jjm2473** [comment]
怀疑是不是你的硬盘掉了，或者空间满了导致配置文件损坏
