### ISSUE TITLE
r5s 使用中的几个问题

### ISSUE THREAD

**Issue by underlaw** [istoreos/istoreos#624]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：samba创建不了。使用高级配置出错。
![image](https://user-images.githubusercontent.com/33020405/222107799-4cbd4877-494e-4ac1-a24a-016175aa7590.png)
![image](https://user-images.githubusercontent.com/33020405/222108171-f5831fb8-4e9b-46eb-9b59-369d205f5adc.png)

B:webdav,启动不了。
![image](https://user-images.githubusercontent.com/33020405/222107999-ee45adb2-90ab-431b-924b-90e245d519de.png)

C:ZeroTier关闭不了。
![image](https://user-images.githubusercontent.com/33020405/222108346-df7713f4-5905-46a6-8ded-e200296eb9c9.png)

D:软件包源有问题
![image](https://user-images.githubusercontent.com/33020405/222903871-e2461f58-5be4-4c63-979d-2793f7cd0e89.png)

E:首页显示lan1为100M,电信端是1000M网卡

![image](https://user-images.githubusercontent.com/33020405/222904222-f8805677-2abd-48c1-b600-204a072af91a.png)

### (2) 路由器型号和固件版本

A：r5s.  [Powered by LuCI Master (git-23.040.60681-9fc2e34)](https://github.com/openwrt/luci) / [ArgonneTheme v1.7.3](https://github.com/kenzok78/luci-theme-argonne) / OpenWrt R23.2.14

### (3) 详细日志和/或截图

A：

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3037/1
