### ISSUE TITLE
21.02.3 2023022415固件无法下载UU加速器，报错无法找到软件包

### ISSUE THREAD

**Issue by justbin95** [istoreos/istoreos#626]
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：最新版本iStoreOS无法在软件中心安装UU加速器，显示如下

```
Collected errors:
* opkg_download_pkg: Package luci-app-uugamebooster is not available from any configured src.
* opkg_install_pkg: Failed to download luci-app-uugamebooster. Perhaps you need to run 'opkg update' ?
* opkg_install_cmd: Cannot install package app-meta-uugamebooster.
```

已经试过 “opkg update” 命令以及换源，仍旧无法找到相应软件包。

### (2) 路由器型号和固件版本

A：路由器型号：Unraid虚拟机 QEMU Standard PC (Q35 + ICH9, 2009)
固件版本：iStoreOS 21.02.3 2023022415 / LuCI openwrt-21.02 branch git-22.347.45520-d30ab74

### (3) 详细日志和/或截图

A：
<img width="664" alt="20230302094834" src="https://user-images.githubusercontent.com/39414738/222309867-ad67d4ce-7ebe-4cdc-8ef0-8b89282d74e7.png">

**Comment by justbin95** [comment]
已解决，添加自定义软件源即可
```
src/gz nas https://istore.linkease.com/repo/x86_64/nas
```

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3035/1
