### ISSUE TITLE
建议增加msd_lite包

### ISSUE THREAD

**Issue by jinxiao** [istoreos/istoreos#627]
路由器型号：x86-64
istoreOS版本：21.02.3 2023022415
建议内容：目前自带udpxy，但是没有msd_lite性能好，相对来说，msd_lite更好用，建议考虑收录，前期可以只增加一个ipk
软件源码地址：https://github.com/rozhuk-im/msd_lite

docker版本运行命令 compose版本
```
version: '3.9'
services:
  msd:
    image: tinyserve/msd_lite
    network_mode: host
    volumes:
      - /mnt/nvme0n1-5/msd_lite/msd_lite.conf:/etc/msd_lite.conf
    restart: always

**Comment by jjm2473** [comment]
有性能的比较吗，会不会只是缓存设置的差别？udpxy有luci界面，配置应该比msd_lite的容器简单吧

**Comment by jinxiao** [comment]
暂时关闭了，rejoin的问题

**Comment by lancsir** [comment]
已添加

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3034/1
