### ISSUE TITLE
希望增加 R4S 核显驱动

### ISSUE THREAD

**Issue by byteinfo** [istoreos/istoreos#628]
希望增加 R4S 核显驱动

**Comment by jjm2473** [comment]
R4S使用的是openwrt官方的内核版本，如果官方支持，那按官方的方式安装内核模块就行了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3033/1
