### ISSUE TITLE
21.02.3 2023022415版本IPv4和ipv6显示错误

### ISSUE THREAD

**Issue by lmabbe-lm** [istoreos/istoreos#631]
21.02.3 2023022415版本IPv4和ipv6显示错误
这个是系统显示的
![image](https://user-images.githubusercontent.com/18411932/222969793-8a2df110-b1b5-4221-8ae2-80d59ae3778d.png)
这个是baidu显示的ipv4地址
![image](https://user-images.githubusercontent.com/18411932/222969822-5a64c758-ea7c-4b6e-b858-512c9600b04a.png)

ipv6不应该显示fe80开头的，
应该显示外网的240开头的吧
![image](https://user-images.githubusercontent.com/18411932/222969900-f9e95c1f-a4cb-4a08-96bb-7f616e8558f1.png)

**Comment by LemonPAKA** [comment]
IPV4是因为你这个是运营商给的内网地址，IPV6是因为你是通过自动分配的WAN_6而不是WAN6所以检测错误了

**Comment by lmabbe-lm** [comment]
> IPV4是因为你这个是运营商给的内网地址，IPV6是因为你是通过自动分配的WAN_6而不是WAN6所以检测错误了

那这个ipv4，怎么改才能变成外网的地址啊

**Comment by LemonPAKA** [comment]
> > IPV4是因为你这个是运营商给的内网地址，IPV6是因为你是通过自动分配的WAN_6而不是WAN6所以检测错误了
> 
> 那这个ipv4，怎么改才能变成外网的地址啊

找运营商加钱（

**Comment by jjm2473** [comment]
ipv4是因为你拨号得到的ip不是公网地址，而是运营商的大内网，对于互联网来说只能看到你的公网地址。

ipv6的可能有bug

**Comment by jinxiao** [comment]
ipv6的我也有这个问题，读取的是wan口的IP而不是WAN6的
![Screenshot_2023-03-11-10-03-54-68_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/2718196/224459240-2e723693-47df-4087-b709-03096ff21f6b.jpg)
![Uploading Screenshot_2023-03-11-10-03-28-62_df198e732186825c8df26e3c5a10d7cd.jpg…]()

**Comment by jjm2473** [comment]
新固件已修复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3030/1
