### ISSUE TITLE
防火墙，区域-转发，总是自动变为"丢弃"

### ISSUE THREAD

**Issue by QQ274910669** [istoreos/istoreos#632]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：小主机X86和虚拟机系统 ,都遇到一样的问题【 单臂路由，有定时执行换IP命令，防火墙-wan->accept-“区域-转发”总是自动变为丢弃。】麻烦大佬，看一下怎么回事。

### (2) 路由器型号和固件版本

A：X86-64/iStoreOS 21.02.3 2023022415

### (3) [详细日志和/或截图]

A：
![image](https://user-images.githubusercontent.com/81500585/223014255-db713541-3db7-4f9c-9514-bf174ba8965f.png)

**Comment by ks-bao** [comment]
是不是拨号了？重启之后就会变成丢弃。你可以用系统便利工具删除这个特性。

**Comment by jjm2473** [comment]
这是特性，如果要允许wan口入站，可以去流量规则里面添加

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2765/2

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3029/1
