### ISSUE TITLE
Docker停止失败

### ISSUE THREAD

**Issue by qzydustin** [istoreos/istoreos#633]
Q：是否用关键词搜索了issue? 
[docker 停止 失败] 没有类似的issue

### (1) 具体问题

A：主页Docker的快捷按钮失效，无法停止/启动Docker；
但是在启动项中可以关闭Docker自动启动和停止Docker

### (2) 路由器型号和固件版本

A：X86使用virtualbox虚拟化

### (3) 详细日志和/或截图

A：![停止失败截图](https://i.imgur.com/p4MywY3.png)

系统日志中没有相关的

**Comment by jjm2473** [comment]
固件版本

**Comment by qzydustin** [comment]
> 固件版本

istoreos-21.02.3-2023022415-x86-64-squashfs-combined.img.gz

**Comment by jjm2473** [comment]
已确认

**Comment by rootphantomer** [comment]
r66s也一样  固件版本iStoreOS 21.02.3 2023022415

**Comment by jjm2473** [comment]
等新固件发布

**Comment by wdmywm3** [comment]
原来真的不是我配置错误，而是这个开关有问题吗😂

**Comment by jjm2473** [comment]
> 原来真的不是我配置错误，而是这个开关有问题吗😂

开和关都会失败，所以如果一开始就没启动，那可能是配置问题。

**Comment by jjm2473** [comment]
20230310固件已经修复了

**Comment by wdmywm3** [comment]
> > 原来真的不是我配置错误，而是这个开关有问题吗😂
> 
> 开和关都会失败，所以如果一开始就没启动，那可能是配置问题。

一开始启动过，但是后来发现怎么关都关不掉，以为自己有啥没搞对，不过更新之后就已经关掉了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3028/1
