### ISSUE TITLE
您好，很抱歉打扰您了，在安装插件时候提示“curl: (22) The requested URL returned error: 404”导致无法下载，是什么原因？路由器是小米CR660X，我是小白，会认真操作，不好意思打扰您了。

### ISSUE THREAD

**Issue by 561410590** [istoreos/istoreos#635]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by 561410590** [comment]
![OpenWrt - LuCI 和另外 1 个页面 - 个人 - Microsoft​ Edge Dev 2023_3_9 16_04_27](https://user-images.githubusercontent.com/67544413/223959093-e2909456-5907-4c30-bf6c-3eadc0b0a2a2.png)

**Comment by jjm2473** [comment]
CR660X应该是mips架构的，不支持

**Comment by 561410590** [comment]
> CR660X应该是mips架构的，不支持

原来是这样，谢谢，麻烦你了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3026/1
