### ISSUE TITLE
openwrt设备中无法创建“虚拟以太网”(veth)

### ISSUE THREAD

**Issue by Iongtimenosee** [istoreos/istoreos#636]
添加设备配置中有一种设备叫“虚拟以太网”，实际上就是添加veth设备，添加后界面有显示，但ip link show中无显示，说明没有在后台执行添加动作。

路由器型号和固件版本：目前最新

**Comment by jjm2473** [comment]
暂时可以通过重启设备解决

**Comment by jjm2473** [comment]
创建设备以后，在接口页面增加一个接口引用它就行了，如果不知道要用什么协议，就配置个静态ip协议。如果是不需要openwrt管理的虚拟网口，就自己用ip命令创建吧

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3025/1
