### ISSUE TITLE
固件在线更新完成后无法进入后台

### ISSUE THREAD

**Issue by shenlonghui** [istoreos/istoreos#640]
### (1) 具体问题

A：“istoreos-21.02.3-2023022415-x86-64-squashfs-combined-efi.img.gz”这个固件在线更新完成后无法进入后台

### (2) 路由器型号和固件版本

A：r86s-G3,cpu n6005,

### (3) 详细日志和/或截图

A：
<img width="850" alt="image" src="https://user-images.githubusercontent.com/44264544/224553334-853b60f6-48de-4d67-b89d-aa309c584296.png">
<img width="850" alt="224553334-853b60f6-48de-4d67-b89d-aa309c584296" src="https://user-images.githubusercontent.com/44264544/224553621-dc493f76-adbf-4055-a99e-35628a03357c.png">

**Comment by jjm2473** [comment]
应该是passwall插件损坏或者安装不完整，跟固件无关。

**Comment by jjm2473** [comment]
卸载passwall，再重新安装应该就能修复了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3020/1
