### ISSUE TITLE
升级软件包后无法登陆后台

### ISSUE THREAD

**Issue by hyy34** [istoreos/istoreos#641]
手欠升级了软件包，后台界面变了，帐号密码都对，无限循环登陆状态，而且变成了英文，SSH显示登陆成功但是没有命令行，不想拆机重装，请问有什么修复办法没？

![image](https://user-images.githubusercontent.com/26433019/224584671-de328d61-ac3c-497d-9621-a0732b793adc.png)

![image](https://user-images.githubusercontent.com/26433019/224584758-56397f47-3478-41be-b162-a49a808f8645.png)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3019/1
