### ISSUE TITLE
r66s接口状态丢失

### ISSUE THREAD

**Issue by rootphantomer** [istoreos/istoreos#642]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [X ] 没有类似的issue

### (1) 具体问题

A：r66s接口状态丢失，但不影响使用，点进到网口配置里也没有内容

### (2) 路由器型号和固件版本

A：R66S，21.02.3 2023031010

### (3) 详细日志和/或截图

A：
![image](https://user-images.githubusercontent.com/6481352/224693500-10ea474a-fd8a-4d94-b811-0f40af44b02b.png)

![image](https://user-images.githubusercontent.com/6481352/224693728-474b3df4-4486-49ac-bc3f-067ea222c6f9.png)

![image](https://user-images.githubusercontent.com/6481352/224693932-ab5d9a9c-98db-4a75-8e51-cf276c841ecf.png)

**Comment by jjm2473** [comment]
你看看 /etc/config/network 文件是不是损坏了

**Comment by rootphantomer** [comment]
@jjm2473 目测没有损坏。
![image](https://user-images.githubusercontent.com/6481352/224702494-c2538c34-1724-4a09-a1b2-0c6c805816a0.png)

**Comment by jjm2473** [comment]
登录后台以后，打开后台的这个地址看看 `/cgi-bin/luci/istore/network/interface/config/` ，例如 http://192.168.100.1/cgi-bin/luci/istore/network/interface/config/

如果有报错信息，就复制下来

**Comment by rootphantomer** [comment]
![image](https://user-images.githubusercontent.com/6481352/225183662-db486d93-a6ff-45dc-a159-eedc89519e15.png)
```
{"error":"exit status 1","success":-1000}
```

**Comment by jjm2473** [comment]
触发错误以后，终端执行 `logread | grep quickstart` 看看

**Comment by rootphantomer** [comment]
> 触发错误以后，终端执行 `logread | grep quickstart` 看看

![image](https://user-images.githubusercontent.com/6481352/225231592-260ebb21-fb6b-4f54-b07c-26bfb2750cd2.png)

**Comment by jjm2473** [comment]
可能你自己升级过系统的软件包？恢复出厂设置以后再看看有没有同样的问题

**Comment by rootphantomer** [comment]
> ip -pretty -detail -json link show >/dev/null

![image](https://user-images.githubusercontent.com/6481352/225679885-a22dbaa2-632b-4401-8a66-17d2c380fbfa.png)

>可能你自己升级过系统的软件包？恢复出厂设置以后再看看有没有同样的问题

恩，升级过一些。

**Comment by jjm2473** [comment]
@rootphantomer 哦，你把ip-full包卸载了，你的这个ip命令是精简版。执行 `opkg update; opkg install ip-full` 就可以恢复

**Comment by rootphantomer** [comment]
@jjm2473 ip-full 有，卸载重装ip-full的时候发现有个上层依赖组件没了，重装ip-full后就好了。谢谢。

**Comment by jjm2473** [comment]
看你截图的ip命令是从busybox来的，要么没装ip-full，要么你更新的时候失败了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3018/1
