### ISSUE TITLE
r66s 21.02.3 2023031010 版本使用一段时间后会网络会降速

### ISSUE THREAD

**Issue by rootphantomer** [istoreos/istoreos#647]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [X ] 没有类似的issue

### (1) 具体问题

A：r66s 21.02.3 2023031010 版本使用一段时间后会网络会降速。通过 系统便利工具 进行测试会从本来的500+Mbps，降速到了95Mbps，看了下千兆协商成百兆协议，重启后测试恢复正常，但大概30分钟左右后就变回百兆宽带速度。上一个版本是没遇到这个问题。上一层路由器是newifi3 D2。

### (2) 路由器型号和固件版本

A：r66s 21.02.3 2023031010

### (3) 详细日志和/或截图

A：
![image](https://user-images.githubusercontent.com/6481352/225278174-dbc31653-4d3a-4f39-86f4-85e60e8d3e70.png)

![image](https://user-images.githubusercontent.com/6481352/225279108-6dea614d-5d45-4aa7-b77f-cf8141532ea1.png)

![image](https://user-images.githubusercontent.com/6481352/225280774-9c492efd-08da-48c3-8afd-8f2bff0f1247.png)

**Comment by rootphantomer** [comment]
换了其他固件也一样，不是istore的问题，好像是D2开了Turbo ACC后，导致降速。关了以后目前正常。

**Comment by rootphantomer** [comment]
> 换了其他固件也一样，不是istore的问题，是我有个usb转网口的设备，插在usb接口上，但是没有使用导致的。拔了就没出问题了

也不是usb也不是acc的问题，固件换了两个千兆速率后，过段时间就变百兆。。。。感觉是上层路由的问题

**Comment by jjm2473** [comment]
那换网线试试

**Comment by rootphantomer** [comment]
> 那换网线试试

网口吹了口气，可能是网口进灰了，吹了气后没问题了。。。

**Comment by jjm2473** [comment]
居然是因为这个 🤣

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3017/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3053/4
