### ISSUE TITLE
大神可以麻烦发布一个[网络向导] ipk文件吗？ 小白实在不懂怎么提取，谢谢大神

### ISSUE THREAD

**Issue by iChenlife** [istoreos/istoreos#649]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
网络向导是属于quickstart的

这里有编译到固件的说明 https://github.com/linkease/nas-packages-luci ，openwrt 项目添加 feed 以后，选中 luci-app-quickstart 即可

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3015/1
