### ISSUE TITLE
请求新增两处优化

### ISSUE THREAD

**Issue by zhx47** [istoreos/istoreos#651]
1. 首页支持新硬盘固定挂载点
  现在新硬盘挂载点貌似是自动生成的？是否可以新增通过UUID方式记录，可以让用户自定义永久挂载点。
  不知道是不是我的操作有问题，那个首页的更改挂载点我输入后回车会变成自动生成的。

2. 扩容系统分区 /overlay
  2G太小啦，是否可以像云服务厂商那样，可以将系统盘除了swap或者boot等特殊分区以外的所有空间都同意挂载在/上

**Comment by jjm2473** [comment]
1. 首页配置挂载点就是用uuid的。
2. /overlay 2G还不够用吗，你安装了什么插件？docker和其他下载的数据建个新分区放不就行了？

**Comment by GreenTeodoro839** [comment]
> 1. 首页支持新硬盘固定挂载点
>    现在新硬盘挂载点貌似是自动生成的？是否可以新增通过UUID方式记录，可以让用户自定义永久挂载点。
>    不知道是不是我的操作有问题，那个首页的更改挂载点我输入后回车会变成自动生成的。
> 2. 扩容系统分区 /overlay
>    2G太小啦，是否可以像云服务厂商那样，可以将系统盘除了swap或者boot等特殊分区以外的所有空间都同意挂载在/上

overlay文件系统的特性，扩容不方便，云服务器一般是ext4，但是断电容易损坏

**Comment by jjm2473** [comment]
@GreenTeodoro839 使用ext4意味着所有修改都是在同一分区进行的，那固件升级的时候就没法保留用户安装的软件了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3014/1
