### ISSUE TITLE
iStoreOS使用问题

### ISSUE THREAD

**Issue by loveyanglove** [istoreos/istoreos#652]
主页面的几个按钮功能无法使用，
![image](https://user-images.githubusercontent.com/118234735/226086416-160eeb75-5785-441f-b6e7-d44543187058.png)

机器X86，版本最新版本21.02.3 2023031010

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3013/1
