### ISSUE TITLE
请求对NanoPi R5S的固件添加风扇温控插件

### ISSUE THREAD

**Issue by Lil-Gun** [istoreos/istoreos#653]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：[r5s-sdcard-0610.img.gz]该固件自己修改温控能正常使用
[istoreos-21.02.3-2023022415-r5s-squashfs.img.gz]新固件不行

### (2) 路由器型号和固件版本

A：NanoPi R5S [istoreos-21.02.3-2023022415-r5s-squashfs.img.gz] [r5s-sdcard-0610.img.gz]

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
不要提交重复issue。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3012/1
