### ISSUE TITLE
你好，可以在侧边栏添加带宽监控(显示、配置、备份、实时浏览监测)

### ISSUE THREAD

**Issue by iChenlife** [istoreos/istoreos#654]
我参考这个固件，没有找到怎么在istoreos安装的ipk，呜呜
https://github.com/DHDAXCW/OpenWRT_x86_x64
<img width="173" alt="0" src="https://user-images.githubusercontent.com/26037921/226099129-dfe6a3ba-af82-4078-80b0-d945bea90aac.png">

<img width="575" alt="屏幕截图 2023-03-18 175616" src="https://user-images.githubusercontent.com/26037921/226098754-44ca9c5b-5790-4537-b8ff-00ff1fa7bd1d.png">

<img width="611" alt="3" src="https://user-images.githubusercontent.com/26037921/226099009-84f4b123-b6de-48a1-bf40-e1a63812beb7.png">

我在istoreos安装的是 nlbwmon 和 rtbwmon

效果如下：差很多，呜呜
<img width="638" alt="5" src="https://user-images.githubusercontent.com/26037921/226099079-901a35a7-d20d-488c-8124-fbb77fe7d48e.png">

<img width="494" alt="6" src="https://user-images.githubusercontent.com/26037921/226099081-f435c16e-6c1a-4280-ae76-1124fbf159e2.png">

**Comment by jjm2473** [comment]
安装 `luci-app-statistics` ，还有很多 `collectd-mod-*` 开头的插件，需要监控什么就安装什么插件。

**Comment by jjm2473** [comment]
上面说的两个都是延时比较高，但是适合持久化，还有事后分析。

如果你要查看实时的网速，istore里也有“实时流量”

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3011/1
