### ISSUE TITLE
最新版本upnp失效

### ISSUE THREAD

**Issue by xiaolongv** [istoreos/istoreos#655]
现在最新版本突然upnp就失效了，上一个版本还可以并没有失效，现在版本iStoreOS 21.02.3 2023031010

**Comment by jjm2473** [comment]
没改过upnp。试试在高级设置关掉“使用 STUN”，打开“强制转发”，或者反过来。

**Comment by xiaolongv** [comment]
我这是旁路由模式

**Comment by xiaolongv** [comment]
旁路由关掉“使用 STUN”可以用了

**Comment by jjm2473** [comment]
旁路由开UPNP的意义是什么？UPNP要运行在出口网关啊。

**Comment by jjm2473** [comment]
除非在出口网关把旁路由作为DMZ主机，不然没意义。不过为什么不直接在出口网关上开UPNP访问呢？

**Comment by xiaolongv** [comment]
主路由upnp开了因为网关是指向旁路由的，我这要挂甜糖星愿和网心云要用到都是走apWiFi的，我试过了旁路由不开upnp就不会生效

**Comment by jjm2473** [comment]
> 主路由upnp开了因为网关是指向旁路由的，我这要挂甜糖星愿和网心云要用到都是走apWiFi的，我试过了旁路由不开upnp就不会生效

即使旁路由的upnp看起来有效，实际上完全没改变网络联通性，都说了除非你在网关主路由dmz到旁路由，不然外网入站的流量也不会转发到网心云或者甜糖。

实际上，你还不如在网关主路由dmz到网心云或者甜糖，即使没有upnp也开放到公网了。

真不知道这种错误的网络知识怎么来的，而且网心云或者甜糖也不知道旁路由情况下应该让出口网关做NAT，DMZ，或者upnp吗？真把upnp当成万能钥匙

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3010/1
