### ISSUE TITLE
R4SE 固件刷入emmc无法启动

### ISSUE THREAD

**Issue by lucas1024** [istoreos/istoreos#656]
R4SE 固件刷入emmc无法启动

**Comment by jjm2473** [comment]
无R4SE测试，R4SE是其他人贡献的代码，而且未收到其他人反馈无法启动。
你是怎么刷机的？

**Comment by lucas1024** [comment]
官方固件的EMMC刷机助手，还有官方给出的带EFlasher的刷机包都试过
iStoreOS用过0224和0317，都是刷进EMMC后重新通电，只有power的红灯是亮的
设备用的是R4SE带独立MAC的版本

**Comment by jjm2473** [comment]
.img.gz固件下载以后是不是没解压成img？ 仔细查看eMMC刷机教程 https://doc.linkease.com/zh/guide/istoreos/install_rockchip_sysupgrade.html

**Comment by jjm2473** [comment]
比较简单的方式是先刷到tf卡启动，启动之后登录后台，将固件命名成`1.img.gz`后，在“系统-文件传输”里面将固件上传上去，然后打开终端执行 `zcat /tmp/upload/1.img.gz | dd of=/dev/mmcblk0 bs=4096`（注意将mmcblk0改成emmc的实际设备名称，可能是mmcblk0也可能是mmcblk1）

**Comment by jjm2473** [comment]
usb刷机的话，参考这个教程 https://supes.top/nanopi-r4se%E7%BA%BF%E5%88%B7openwrt%E8%87%B3emmc%E6%95%99%E7%A8%8B/

注意也是要先解压固件

**Comment by jjm2473** [comment]
还有这个教程 https://github.com/DHDAXCW/DoorNet-1-2/blob/mere/emmc.md

**Comment by lucas1024** [comment]
USB刷机和DD命令都用过，刷进EMMC还是无法启动，用fdisk -l查看刷过的emmc只有三个分区
![image](https://user-images.githubusercontent.com/29851591/227723229-dc3b9f4b-6737-4c8a-a530-0aed90e33f52.png)

**Comment by jjm2473** [comment]
本来就三个分区，要那么多分区干嘛。写进emmc以后，要把sd卡弹出

**Comment by lucas1024** [comment]
sd卡弹出来等了半小时，系统也没启动，只有power灯饰亮的，sys灯不亮

**Comment by jjm2473** [comment]
你那个有9个分区的是什么？sd卡还是emmc？

istoreos只有三个分区。

**Comment by lucas1024** [comment]
九个分区的是SD卡，上面三个分区的是EMMC里的istoreos，EMMC里面系统没办法启动，插SD卡看看EMMC是不是空的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3009/1
