### ISSUE TITLE
iStoreos首页中间位置的七大模块，只有“网络向导” “终端” “固件更新”可以正常使用 ，其他的四个按钮从来没管用过

### ISSUE THREAD

**Issue by zzj6116** [istoreos/istoreos#657]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A： istoreos首页中间位置的七大模块，只有网络向导, 终端, 固件更新, 这三个按钮是可以正常点击访问的，其他的四个按钮从来就没管用过，尝试过重刷不同版本的固件，以及使用不同的刷机方式刷入固件，或者使用优盘启动，其他的四个按钮依然无法点击使用。按钮包括内网配置，DNS配置。软件源配置。开启沙箱，这四个按钮从来都没有管用过。已经使用了五个月，历经不同的固件版本。

### (2) 路由器型号和固件版本

A：路由器型号，J4125 X86双网口螃蟹网卡，型号被iStoreOS识别为Default string Default string，固件版本：iStoreOS 21.02.3 2023031010 / LuCI istoreos-21.02 branch git-23.037.57600-91128de

### (3) 详细日志和/或截图

![QQ截图20230320000821](https://user-images.githubusercontent.com/76789765/226189030-d7c1d8fc-8921-4972-8ca9-405b2e32ee95.png)
![2](https://user-images.githubusercontent.com/76789765/226189035-3aa9f1e3-1b4f-461e-80e6-b4d7d3d33e94.png)

**Comment by Carseason** [comment]
换个浏览器

**Comment by zzj6116** [comment]
> 换个浏览器

额，感谢，果然可以了，使用了多年的360极速浏览器不能点击这四个按钮，各种方法都试了，唯独没试过换浏览器，chrome和edge都是可以正常点击这四个按钮的。

**Comment by Carseason** [comment]
> > 换个浏览器
> 
> 额，感谢，果然可以了，使用了多年的360极速浏览器不能点击这四个按钮，各种方法都试了，唯独没试过换浏览器，chrome和edge都是可以正常点击这四个按钮的。

极速浏览器更新到最新版应该也可以的

**Comment by jjm2473** [comment]
很明显浏览器问题，没问题的都是跳转按钮，其他有对话框的都无效。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3008/1
