### ISSUE TITLE
X86能将显卡驱动编译入内核吗？

### ISSUE THREAD

**Issue by a0z1975** [istoreos/istoreos#658]
istoreos作为媒体服务器使用时，由于没有显卡驱动导致plex、emby等服务器缺失硬件解码功能，cpu软解码时使用率太高，建议将显卡驱动编译入内核解决缺失硬解码的问题。

**Comment by jjm2473** [comment]
如果openwrt支持的显卡，要么已经集成驱动，要么可以自己用opkg安装。据我所知n5105还没驱动。

**Comment by jjm2473** [comment]
https://github.com/istoreos/istoreos/issues/525

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3007/1
