### ISSUE TITLE
每次重启系统，防火墙会变成丢弃从wan到lan的转发数据。

### ISSUE THREAD

**Issue by ccettu** [istoreos/istoreos#659]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：网络-防火墙-区域，从WAN区域转发到LAN区域，或任意区域的入站数据改成接受后，在重启路由器或者做其它关于接口的设置后，该按钮会重新自动变成丢弃，这样会导致网心云docker容器魔方停止数据上传，需要手动再调会接受，但下次启动路由器后，仍然会变成丢弃。

### (2) 路由器型号和固件版本

A：J4125物理机安装和PVE下安装的iStoreOS 21.02.3 2023032001版本和上一个版本都有这样的问题。

### (3) 详细日志和/或截图

A：
![Snipaste_2023-03-21_01-08-22](https://user-images.githubusercontent.com/49177353/226419399-f55fd0e8-1dd1-414e-b6bc-928ff4851e47.jpg)

**Comment by jjm2473** [comment]
这不是早就有相同的issue了吗？ #632

为了防止外网攻击，pppoe拨号时自动禁止wan口入站。
可以自己在流量规则配置入站允许，或者在istore安装systool，里面有关掉自动脚本的功能。
