### ISSUE TITLE
能不能添加.tar.gz 我想用pve的lxc容器安装

### ISSUE THREAD

**Issue by gzygood** [istoreos/istoreos#661]
能不能添加.tar.gz 我想用pve的lxc容器安装
搜过了，去年有人问过

**Comment by jjm2473** [comment]
搜过了就别开新issue，在原来的issue里面回复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3004/1
