### ISSUE TITLE
希望内核能开启Kernel Debug Info功能？

### ISSUE THREAD

**Issue by Olympus-E** [istoreos/istoreos#665]
x86固件似乎是关闭的，kernel panic自动重启以后不会生成crashlog文件，尝试过人为制造内核崩溃也没有生成。有没有可能开启这个功能？最近总是kernel panic，debug需要日志文件

[](url)
Global settings settings --->
[*] Compile the kernel with symbol table information
(CONFIG_KERNEL_KALLSYMS=y)
[*] Compile the kernel with debug information
(CONFIG_KERNEL_DEBUG_INFO=y)

**Comment by Olympus-E** [comment]
自己编译了一个系统，但似乎只开这两个不行

感觉内核可以启用kdump和kexec支持？

[https://www.open-mesh.org/projects/devtools/wiki/Crashdumps_with_kexec](url)

在虚拟机环境下测试不成功，可能是因为Vmware的缘故，但手头上没有其他物理机可以测试了。

**Comment by jjm2473** [comment]
这个可以通过crashlog补丁把崩溃日志写到内存里，崩溃重启以后还能读出来，之后看看x86行不行。目前3568和ars2都有这个功能

**Comment by jjm2473** [comment]
openwrt已经把crashlog补丁删了，所以没法开启内核日志写入内存的功能，自己用串口调试吧。

**Comment by jjm2473** [comment]
不知道这个有没有用 https://www.kernel.org/doc/html/v5.10/admin-guide/ramoops.html

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3003/1
