### ISSUE TITLE
按照文档配置IPV6中继不生效

### ISSUE THREAD

**Issue by liukaho** [istoreos/istoreos#667]
按照[文档](https://doc.linkease.com/zh/guide/easepi/quick.html#_2-%E6%8B%A8%E5%8F%B7) 配置好了Lan和Wan6， 首页有显示IPV6了， 但还是无法访问IPV6的站点。路由器直连光猫的话是可以正常访问的， 是不是软路由这里哪里还配置少了？

固件版本 iStoreOS 21.02.3 2023032001
内核版本 5.4.188
软路由： R2S

**Comment by jjm2473** [comment]
https://github.com/istoreos/istoreos/discussions/646

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3001/1
