### ISSUE TITLE
R5S如果将一个2.5G网口切换为wan口，另外一个2.5G设置为LAN口，wan口会间歇性断开

### ISSUE THREAD

**Issue by luxzip** [istoreos/istoreos#668]
R5S 4G内存版本，使用21.02.3 2023032001最新版本

如果把WAN口切换到2.5G口上，则每30分钟就会间歇性断开（多次尝试可复现）并且该端口重启

查看系统日志，提醒pppoe ‘wan’ is down，然后重新拨号

一开始怀疑是IPv6的问题，完全关闭ipv6后，故障依旧

如果使用千兆口做wan口，则稳定无问题

怀疑是8125BG的驱动问题，不知道其他人有没有同样情况

**Comment by moonshine00** [comment]
我用的版本21.02.3 2022121613，目前连续开机66天，一个2.5G接光猫，另一个2.5G接lan,没有问题....
![截屏2023-03-30 上午8 57 50](https://user-images.githubusercontent.com/34091349/228700795-68bd8160-1406-4b7c-8bbd-46d9a9bda887.png)

**Comment by luxzip** [comment]
切换这个版本后，确实不会再自动重启端口了

但是我发现是PT下载的压力太大了，网络开始拥塞，应该是R5S性能不够

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3000/1
