### ISSUE TITLE
在线升级-保持设置并保留当前配置 勾不上

### ISSUE THREAD

**Issue by jjm2473** [istoreos/istoreos#674]
保持设置并保留当前配置 还不是勾不上

_Originally posted by @nettentacle in https://github.com/istoreos/istoreos/discussions/637#discussioncomment-5353194_

**Comment by jjm2473** [comment]
好像argon深色主题下会有问题

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2997/1
