### ISSUE TITLE
风扇控速

### ISSUE THREAD

**Issue by haygcao** [istoreos/istoreos#676]
反馈bug/问题模板，提建议请删除

## 1.x86 的小主机，风扇一直转个不停

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：x86 的小主机刷完istore os后风扇一直转个不停，能不能加个风扇调控的脚本或者插件

### (2) 路由器型号和固件版本

A：iStoreOS 21.02.3 2023032001

**Comment by jjm2473** [comment]
没研究过x86的风扇，不是在bios里面设置的吗？
