### ISSUE TITLE
更新固件后系统磁盘掉了，挂载后路径不匹配，无法使用

### ISSUE THREAD

**Issue by tinshou** [istoreos/istoreos#678]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
前两天更新了固件之后，发现装系统的硬盘掉了，只剩下1.94/2G(原来是用两百g的固态装系统，另外1T拿来存数据)，因为这两g系统盘也满了，无法安装插件。于是在高级设置中查看挂载信息，发现overlayfs:/overlay只挂载了这2g的磁盘，于是把两百多g的磁盘挂载成了overlayfs，但是成功之后1T的磁盘又掉了，于是又把数据磁盘挂载上，但是现在虽然系统盘挂载上了两百g，但是路径好像不一致，导致安装的插件都无法查看，易有云从首页进入也是找不到磁盘。

### (1) 具体问题

A：帮忙看下怎么恢复原来的系统设置，因为前几天刚注册了个pt站，新手任务还没完成，现在所有插件都用不了，pt也快过期了。

### (2) 路由器型号和固件版本

A：主机是自己组装的q1900，固件版本是21.02.3 2023032001

### (3) 详细日志和/或截图

A：
![mmexport1679921776857](https://user-images.githubusercontent.com/25699098/227945995-64523292-bda0-4203-8896-d15004c39978.jpg)
![涂鸦_mmexport1679908768547](https://user-images.githubusercontent.com/25699098/227946003-08fb7830-2d93-45c0-a81c-8caee37ee69c.jpg)

我在群里和客服都有留言，但是没有回复，请帮忙尽快看看，手机18680549175 微信同号，可以接受付费解决，谢谢

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2995/1
