### ISSUE TITLE
商店里的Jellyfin安装成功后在线下载完整包一直失败

### ISSUE THREAD

**Issue by wildtigerw** [istoreos/istoreos#68]
如题

**Comment by wildtigerw** [comment]
好希望这个问题能解决，升级到29日版本问题依旧。

**Comment by jannson** [comment]
经过了漫长的时间，改了好几个大版本，终于 狠稳定了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3770/1
