### ISSUE TITLE
好像istoreos对82680网卡兼容有问题

### ISSUE THREAD

**Issue by podipod** [istoreos/istoreos#680]
测试了好几个版本，好像82580这个网卡在istoreos上有问题，希望做一下兼容，谢谢🙏。

**Comment by jjm2473** [comment]
没有测试设备。igb驱动已经集成了，你看看内核日志有没有错误。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2994/1
