### ISSUE TITLE
请问istore后台系统日志出现大量 tracker.dcdn.baidu.com代表什么

### ISSUE THREAD

**Issue by Zxklinux** [istoreos/istoreos#681]
如下

Thu Mar 30 10:16:12 2023 daemon.warn dnsmasq[19209]: possible DNS-rebind attack detected: tracker.dcdn.baidu.com
Thu Mar 30 10:16:12 2023 daemon.warn dnsmasq[19209]: possible DNS-rebind attack detected: tracker.dcdn.baidu.com
Thu Mar 30 10:16:12 2023 daemon.warn dnsmasq[19209]: possible DNS-rebind attack detected: tracker.dcdn.baidu.com
Thu Mar 30 10:16:12 2023 daemon.warn dnsmasq[19209]: possible DNS-rebind attack detected: tracker.dcdn.baidu.com
Thu Mar 30 10:16:12 2023 daemon.warn dnsmasq[19209]: possible DNS-rebind attack detected: tracker.dcdn.baidu.com
Thu Mar 30 10:16:12 2023 daemon.warn dnsmasq[19209]: possible DNS-rebind attack detected: tracker.dcdn.baidu.com
Thu Mar 30 10:16:12 2023 daemon.warn dnsmasq[19209]: possible DNS-rebind attack detected: tracker.dcdn.baidu.com
Thu Mar 30 10:16:12 2023 daemon.warn dnsmasq[19209]: possible DNS-rebind attack detected: tracker.dcdn.baidu.com
Thu Mar 30 10:16:12 2023 daemon.warn dnsmasq[19209]: possible DNS-rebind attack detected: tracker.dcdn.baidu.com
。。。

这是作者在统计什么东西吗？还是有什么其他原因，谢谢

**Comment by jjm2473** [comment]
不是，目前没啥统计。这个一般是内网的设备发出的，你把内网设备都断开看看还有没有，可能是什么盒子？

**Comment by jjm2473** [comment]
https://zhuanlan.zhihu.com/p/114207971

https://blog.csdn.net/boliang319/article/details/38279195

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2993/1
