### ISSUE TITLE
修改文本框中的内容，点击“保存并应用”，提示“没有待应用的更改”

### ISSUE THREAD

**Issue by woann** [istoreos/istoreos#684]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：修改文本框中的内容，点击“保存并应用”，提示“没有待应用的更改”,必须要修改一个下拉框，或者开关类的配置，再点“保存并应用”，才能正常保存应用。说白了，就是没有监听文本框中内容的变更。

### (2) 路由器型号和固件版本

A：iStoreOS 21.02.3 2023032001 / LuCI istoreos-21.02 branch git-23.037.57600-91128de

### (3) 详细日志和/或截图

A：

**Comment by woann** [comment]
最新版本已经修复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2992/1
