### ISSUE TITLE
使用cloudflare ddns后，首页前端显示的不是域名

### ISSUE THREAD

**Issue by jinxiao** [istoreos/istoreos#689]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x ] 没有类似的issue

## 2. 详细叙述
前端首页显示的

### (1) 具体问题

A：DDNS目前使用的是cloudflare的，域名形如router.xxx.uk，其中在ddns配置中，
查询主机名为：router.xxx.uk
域名为：router@xxx.uk （该形式是cloudflare固定形式）

但是在首页看到的域名为： router@xxx.uk，是否改成查询主机名更好呢？

### (2) 路由器型号和固件版本

A：7505 iStoreOS 21.02.3 2023033111

### (3) 详细日志和/或截图

A：
![image](https://user-images.githubusercontent.com/2718196/229440906-8ba1525b-1080-4366-8777-2e1921268c36.png)

**Comment by jjm2473** [comment]
已修复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2987/1
