### ISSUE TITLE
r2s 跑不满千兆

### ISSUE THREAD

**Issue by HalcyonDaysssss** [istoreos/istoreos#690]
### (1) 具体问题

A：r2s跑不满千兆

### (2) 路由器型号和固件版本

A：软路由r2s，21.02.3 2023033111

### (3) 详细日志和/或截图
![image](https://user-images.githubusercontent.com/24239032/229572863-8f2d2def-11de-45a4-9351-9b1e474ccb9e.png)

A：在百度上搜索过，恩山论坛说将wan口跟landui对调，依旧不行

**Comment by HalcyonDaysssss** [comment]
好像说要开启usb3.0，但是不知道如何开启

**Comment by jjm2473** [comment]
本来就有usb3啊
<img width="524" alt="image" src="https://user-images.githubusercontent.com/3896703/230333787-a53f7c7b-7940-42d3-b3d4-2abf256d5422.png">

试试 20230310 固件性能怎么样吧，反正r2s的USB本身也不稳定

**Comment by HalcyonDaysssss** [comment]
> 本来就有usb3啊 <img alt="image" width="524" src="https://user-images.githubusercontent.com/3896703/230333787-a53f7c7b-7940-42d3-b3d4-2abf256d5422.png">
> 
> 试试 20230310 固件性能怎么样吧，反正r2s的USB本身也不稳定

但是我用QiuSimons/YAO这位大佬的固件，基本稳定跑千兆。。。。。不知道为啥

**Comment by jjm2473** [comment]
哦，可能 2月24号 升级了 r8152 驱动导致的

**Comment by jjm2473** [comment]
试试2月24号之前的固件

**Comment by jjm2473** [comment]
@HalcyonDaysssss 老固件恢复出厂设置再试试

**Comment by jjm2473** [comment]
已发布

**Comment by HoGarfield** [comment]
iStoreOS 22.03.6 2024011910
R2S，千兆宽带，旁路由模式。内网测速能跑千兆，但是电信测速就只能跑600M左右，假如不走软路由，电信测速就能跑满千兆。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2986/1
