### ISSUE TITLE
F3322 DDNS无法更新

### ISSUE THREAD

**Issue by tommytianhm** [istoreos/istoreos#691]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：f3322 DDNS 永不更新。

### (2) 路由器型号和固件版本

A：X86硬路由（非虚拟机），固件版本，iStoreOS 21.02.3 2023033111

### (3) 详细日志和/或截图

A： 064203       : force interval: 4320 seconds
 064203       : retry interval: 60 seconds
 064203       : retry counter : 0 times
 064203       : 'SIGTERM' was send to old process
 064203  note : PID '18023' terminated by 'SIGTERM' at 2023-04-04 06:42
 064203       : last update: never
 064203       : Detect registered/public IP
 064203       : #> /usr/bin/host -t A tommyxxx.f3322.net  >/var/run/ddns/myddns_ipv4.dat 2>/var/run/ddns/myddns_ipv4.err
 064203       : Registered IP '113.116.73.23' detected
 064203  info : Starting main loop at 2023-04-04 06:42
 064203       : Detect local IP on 'network'
 064203       : Local IP '113.92.95.134' detected on network 'wan'
 064203       : Update needed - L: '113.92.95.134' <> R: '113.116.73.23'
 064203       : Force communication via IP '113.92.95.134'
 064203       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 064203 ERROR : GNU Wget Error: '8'
 064203       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:42:03 ERROR 404: Not Found.
 064203  WARN : Transfer failed - retry 1/0 in 60 seconds
 064303       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 064303 ERROR : GNU Wget Error: '8'
 064303       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:43:03 ERROR 404: Not Found.
 064303  WARN : Transfer failed - retry 2/0 in 60 seconds
 064403       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 064403 ERROR : GNU Wget Error: '8'
 064403       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:44:03 ERROR 404: Not Found.
 064403  WARN : Transfer failed - retry 3/0 in 60 seconds
 064503       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 064503 ERROR : GNU Wget Error: '8'
 064503       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:45:03 ERROR 404: Not Found.
 064503  WARN : Transfer failed - retry 4/0 in 60 seconds
 064603       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 064603 ERROR : GNU Wget Error: '8'
 064603       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:46:03 ERROR 404: Not Found.
 064603  WARN : Transfer failed - retry 5/0 in 60 seconds
 064703       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 064703 ERROR : GNU Wget Error: '8'
 064703       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:47:03 ERROR 404: Not Found.
 064703  WARN : Transfer failed - retry 6/0 in 60 seconds
 064803       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 064803 ERROR : GNU Wget Error: '8'
 064803       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:48:03 ERROR 404: Not Found.
 064803  WARN : Transfer failed - retry 7/0 in 60 seconds
 064903       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 064903 ERROR : GNU Wget Error: '8'
 064903       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:49:03 ERROR 404: Not Found.
 064903  WARN : Transfer failed - retry 8/0 in 60 seconds
 065003       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 065003 ERROR : GNU Wget Error: '8'
 065003       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:50:03 ERROR 404: Not Found.
 065003  WARN : Transfer failed - retry 9/0 in 60 seconds
 065103       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 065103 ERROR : GNU Wget Error: '8'
 065103       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:51:03 ERROR 404: Not Found.
 065103  WARN : Transfer failed - retry 10/0 in 60 seconds
 065203       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 065203 ERROR : GNU Wget Error: '8'
 065203       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:52:03 ERROR 404: Not Found.
 065203  WARN : Transfer failed - retry 11/0 in 60 seconds
 065303       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 065303 ERROR : GNU Wget Error: '8'
 065303       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:53:03 ERROR 404: Not Found.
 065303  WARN : Transfer failed - retry 12/0 in 60 seconds
 065403       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 065403 ERROR : GNU Wget Error: '8'
 065403       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:54:03 ERROR 404: Not Found.
 065403  WARN : Transfer failed - retry 13/0 in 60 seconds
 065503       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 065503 ERROR : GNU Wget Error: '8'
 065503       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:55:03 ERROR 404: Not Found.
 065503  WARN : Transfer failed - retry 14/0 in 60 seconds
 065603       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 065603 ERROR : GNU Wget Error: '8'
 065603       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:56:03 ERROR 404: Not Found.
 065603  WARN : Transfer failed - retry 15/0 in 60 seconds
 065703       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 065703 ERROR : GNU Wget Error: '8'
 065703       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:57:03 ERROR 404: Not Found.
 065703  WARN : Transfer failed - retry 16/0 in 60 seconds
 065803       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 065804 ERROR : GNU Wget Error: '8'
 065804       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:58:04 ERROR 404: Not Found.
 065804  WARN : Transfer failed - retry 17/0 in 60 seconds
 065904       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 065904 ERROR : GNU Wget Error: '8'
 065904       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 06:59:04 ERROR 404: Not Found.
 065904  WARN : Transfer failed - retry 18/0 in 60 seconds
 070004       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 070004 ERROR : GNU Wget Error: '8'
 070004       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:00:04 ERROR 404: Not Found.
 070004  WARN : Transfer failed - retry 19/0 in 60 seconds
 070104       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 070104 ERROR : GNU Wget Error: '8'
 070104       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:01:04 ERROR 404: Not Found.
 070104  WARN : Transfer failed - retry 20/0 in 60 seconds
 070204       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 070204 ERROR : GNU Wget Error: '8'
 070204       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:02:04 ERROR 404: Not Found.
 070204  WARN : Transfer failed - retry 21/0 in 60 seconds
 070304       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 070304 ERROR : GNU Wget Error: '8'
 070304       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:03:04 ERROR 404: Not Found.
 070304  WARN : Transfer failed - retry 22/0 in 60 seconds
 070404       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 070404 ERROR : GNU Wget Error: '8'
 070404       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:04:04 ERROR 404: Not Found.
 070404  WARN : Transfer failed - retry 23/0 in 60 seconds
 070504       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 070504 ERROR : GNU Wget Error: '8'
 070504       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:05:04 ERROR 404: Not Found.
 070504  WARN : Transfer failed - retry 24/0 in 60 seconds
 070604       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 070604 ERROR : GNU Wget Error: '8'
 070604       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:06:04 ERROR 404: Not Found.
 070604  WARN : Transfer failed - retry 25/0 in 60 seconds
 070704       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 070704 ERROR : GNU Wget Error: '8'
 070704       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:07:04 ERROR 404: Not Found.
 070704  WARN : Transfer failed - retry 26/0 in 60 seconds
 070804       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 070804 ERROR : GNU Wget Error: '8'
 070804       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:08:04 ERROR 404: Not Found.
 070804  WARN : Transfer failed - retry 27/0 in 60 seconds
 070904       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 070904 ERROR : GNU Wget Error: '8'
 070904       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:09:04 ERROR 404: Not Found.
 070904  WARN : Transfer failed - retry 28/0 in 60 seconds
 071004       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071004 ERROR : GNU Wget Error: '8'
 071004       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:10:04 ERROR 404: Not Found.
 071004  WARN : Transfer failed - retry 29/0 in 60 seconds
 071104       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071104 ERROR : GNU Wget Error: '8'
 071104       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:11:04 ERROR 404: Not Found.
 071104  WARN : Transfer failed - retry 30/0 in 60 seconds
 071130       : ************ ************** ************** **************
 071130  note : PID '13064' started at 2023-04-04 07:11
 071130       : ddns version  : 2.8.2-14
 071130       : uci configuration:
ddns.myddns_ipv4.check_interval='5'
ddns.myddns_ipv4.check_unit='minutes'
ddns.myddns_ipv4.domain='tommyxxx.f3322.net'
ddns.myddns_ipv4.enabled='1'
ddns.myddns_ipv4.force_unit='minutes'
ddns.myddns_ipv4.interface='wan'
ddns.myddns_ipv4.ip_network='wan'
ddns.myddns_ipv4.ip_source='network'
ddns.myddns_ipv4.lookup_host='tommyxxx.f3322.net'
ddns.myddns_ipv4.password='***PW***'
ddns.myddns_ipv4.retry_unit='seconds'
ddns.myddns_ipv4.service_name='3322.org'
ddns.myddns_ipv4.use_ipv6='0'
ddns.myddns_ipv4.use_syslog='2'
ddns.myddns_ipv4.username='tommyxxx'
ddns.myddns_ipv4=service
 071130       : verbose mode  : 0 - run normal, NO console output
 071130       : check interval: 300 seconds
 071130       : force interval: 4320 seconds
 071130       : retry interval: 60 seconds
 071130       : retry counter : 0 times
 071130       : 'SIGTERM' was send to old process
 071130  note : PID '18493' terminated by 'SIGTERM' at 2023-04-04 07:11
 071130       : last update: never
 071130       : Detect registered/public IP
 071130       : #> /usr/bin/host -t A tommyxxx.f3322.net  >/var/run/ddns/myddns_ipv4.dat 2>/var/run/ddns/myddns_ipv4.err
 071130       : Registered IP '113.116.73.23' detected
 071130  info : Starting main loop at 2023-04-04 07:11
 071130       : Detect local IP on 'network'
 071130       : Local IP '113.92.95.134' detected on network 'wan'
 071130       : Update needed - L: '113.92.95.134' <> R: '113.116.73.23'
 071130       : Force communication via IP '113.92.95.134'
 071130       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071130 ERROR : GNU Wget Error: '8'
 071130       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:11:30 ERROR 404: Not Found.
 071130  WARN : Transfer failed - retry 1/0 in 60 seconds
 071230       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071230 ERROR : GNU Wget Error: '8'
 071230       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:12:30 ERROR 404: Not Found.
 071230  WARN : Transfer failed - retry 2/0 in 60 seconds
 071330       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071330 ERROR : GNU Wget Error: '8'
 071330       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:13:30 ERROR 404: Not Found.
 071330  WARN : Transfer failed - retry 3/0 in 60 seconds
 071430       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071430 ERROR : GNU Wget Error: '8'
 071430       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:14:30 ERROR 404: Not Found.
 071430  WARN : Transfer failed - retry 4/0 in 60 seconds
 071530       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071530 ERROR : GNU Wget Error: '8'
 071530       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:15:30 ERROR 404: Not Found.
 071530  WARN : Transfer failed - retry 5/0 in 60 seconds
 071630       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071630 ERROR : GNU Wget Error: '8'
 071630       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:16:30 ERROR 404: Not Found.
 071630  WARN : Transfer failed - retry 6/0 in 60 seconds
 071730       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071730 ERROR : GNU Wget Error: '8'
 071730       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:17:30 ERROR 404: Not Found.
 071730  WARN : Transfer failed - retry 7/0 in 60 seconds
 071830       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071830 ERROR : GNU Wget Error: '8'
 071830       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:18:30 ERROR 404: Not Found.
 071830  WARN : Transfer failed - retry 8/0 in 60 seconds
 071930       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 071930 ERROR : GNU Wget Error: '8'
 071930       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:19:30 ERROR 404: Not Found.
 071930  WARN : Transfer failed - retry 9/0 in 60 seconds
 072030       : #> /usr/bin/wget --hsts-file=/tmp/.wget-hsts -nv -t 1 -O /var/run/ddns/myddns_ipv4.dat -o /var/run/ddns/myddns_ipv4.err --bind-address=113.92.95.134 --no-proxy 'http://tommyxxx:***PW***@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134'
 072030 ERROR : GNU Wget Error: '8'
 072030       : http://tommyxxx:*password*@members.3322.org/dyndns/update?system=dyndns&hostname=tommyxxx.f3322.net&myip=113.92.95.134:
2023-04-04 07:20:30 ERROR 404: Not Found.
 072030  WARN : Transfer failed - retry 10/0 in 60 seconds

**Comment by jjm2473** [comment]
没看到404吗？

**Comment by tommytianhm** [comment]
> 没看到404吗？

自己摸索出来解决方案了。
固件默认配置的f3322的ddns服务器地址为f3322.org,实际连不上，所以404.
把配置文件里的f3322.org改为f3322.net就可以了。

**Comment by jjm2473** [comment]
可能根本就不是同一家

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2985/1
