### ISSUE TITLE
[bug]docker配置了远程终端，在关掉远程终端后，无法保存

### ISSUE THREAD

**Issue by HalcyonDaysssss** [istoreos/istoreos#692]
### (1) 具体问题

A：docker配置了远程终端，在关掉远程终端后，无法保存，显示：一个或多个必选项值为空！
B: 通过右上角未保存的配置，强行保存后，docker菜单依旧只有配置菜单。通过首页的docker进入docker高级配置，显示：无法调度: /cgi-bin/luci/admin/docker/overview

### (2) 路由器型号和固件版本

A：r2s，iStoreOS 21.02.3 2023033111

### (3) 详细日志和/或截图

A：
<img width="989" alt="image" src="https://user-images.githubusercontent.com/24239032/229673955-6a2d6f5b-9b54-4319-8500-6693ae98c5f6.png">

**Comment by HalcyonDaysssss** [comment]
@jannson

**Comment by HalcyonDaysssss** [comment]
@jjm2473

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2984/1
