### ISSUE TITLE
x86的系统WAN口每隔几小时就重连

### ISSUE THREAD

**Issue by github-szhang** [istoreos/istoreos#695]
宽带已改桥接，系统升级最新版后，看日志，每隔几小时就WAN口重新连接，这是啥毛病，下面是日志。
Thu Apr  6 02:35:32 2023 daemon.notice netifd: Interface 'wan' is now down
Thu Apr  6 02:35:32 2023 daemon.notice netifd: Interface 'wan' is setting up now
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - slhc
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - ppp_generic
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - pppox
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - pppoe
Thu Apr  6 02:35:32 2023 daemon.notice netifd: wan (2074): uci: Entry not found
Thu Apr  6 02:35:32 2023 local0.notice udpxy[2001]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is exiting with rc=[0]
Thu Apr  6 02:35:32 2023 daemon.info pppd[2116]: Plugin pppoe.so loaded.
Thu Apr  6 02:35:32 2023 daemon.info pppd[2116]: PPPoE plugin from pppd 2.4.9
Thu Apr  6 02:35:32 2023 local0.notice udpxy[2134]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is starting
Thu Apr  6 02:35:32 2023 daemon.notice pppd[2116]: pppd 2.4.9 started by root, uid 0
Thu Apr  6 02:35:32 2023 daemon.info pppd[2116]: PPP session is 37318
Thu Apr  6 02:35:32 2023 daemon.warn pppd[2116]: Connected to cc:1a:fa:eb:0d:c0 via interface eth0
Thu Apr  6 02:35:32 2023 kern.info kernel: [ 8695.878755] pppoe-wan: renamed from ppp0
Thu Apr  6 02:35:32 2023 daemon.info pppd[2116]: Renamed interface ppp0 to pppoe-wan
Thu Apr  6 02:35:32 2023 daemon.info pppd[2116]: Using interface pppoe-wan
Thu Apr  6 02:35:32 2023 daemon.notice pppd[2116]: Connect: pppoe-wan <--> eth0
Thu Apr  6 02:35:32 2023 daemon.info pppd[2116]: syncppp not active
Thu Apr  6 02:35:32 2023 daemon.info pppd[2116]: Remote message: Authentication failed!
Thu Apr  6 02:35:32 2023 daemon.err pppd[2116]: PAP authentication failed
Thu Apr  6 02:35:32 2023 daemon.notice pppd[2116]: Connection terminated.
Thu Apr  6 02:35:32 2023 daemon.info pppd[2116]: Exit.
Thu Apr  6 02:35:32 2023 daemon.notice netifd: Interface 'wan' is now down
Thu Apr  6 02:35:32 2023 daemon.notice netifd: Interface 'wan' is setting up now
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - slhc
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - ppp_generic
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - pppox
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - pppoe
Thu Apr  6 02:35:32 2023 daemon.notice netifd: wan (2207): uci: Entry not found
Thu Apr  6 02:35:32 2023 local0.notice udpxy[2134]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is exiting with rc=[0]
Thu Apr  6 02:35:32 2023 daemon.info pppd[2252]: Plugin pppoe.so loaded.
Thu Apr  6 02:35:32 2023 daemon.info pppd[2252]: PPPoE plugin from pppd 2.4.9
Thu Apr  6 02:35:32 2023 local0.notice udpxy[2270]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is starting
Thu Apr  6 02:35:32 2023 daemon.notice pppd[2252]: pppd 2.4.9 started by root, uid 0
Thu Apr  6 02:35:32 2023 daemon.info pppd[2252]: PPP session is 37319
Thu Apr  6 02:35:32 2023 daemon.warn pppd[2252]: Connected to cc:1a:fa:eb:0d:c0 via interface eth0
Thu Apr  6 02:35:32 2023 kern.info kernel: [ 8696.226751] pppoe-wan: renamed from ppp0
Thu Apr  6 02:35:32 2023 daemon.info pppd[2252]: Renamed interface ppp0 to pppoe-wan
Thu Apr  6 02:35:32 2023 daemon.info pppd[2252]: Using interface pppoe-wan
Thu Apr  6 02:35:32 2023 daemon.notice pppd[2252]: Connect: pppoe-wan <--> eth0
Thu Apr  6 02:35:32 2023 daemon.info pppd[2252]: syncppp not active
Thu Apr  6 02:35:32 2023 daemon.info pppd[2252]: Remote message: Authentication failed!
Thu Apr  6 02:35:32 2023 daemon.err pppd[2252]: PAP authentication failed
Thu Apr  6 02:35:32 2023 daemon.notice pppd[2252]: Connection terminated.
Thu Apr  6 02:35:32 2023 daemon.info pppd[2252]: Exit.
Thu Apr  6 02:35:32 2023 daemon.notice netifd: Interface 'wan' is now down
Thu Apr  6 02:35:32 2023 daemon.notice netifd: Interface 'wan' is setting up now
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - slhc
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - ppp_generic
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - pppox
Thu Apr  6 02:35:32 2023 daemon.err insmod: module is already loaded - pppoe
Thu Apr  6 02:35:32 2023 daemon.notice netifd: wan (2344): uci: Entry not found
Thu Apr  6 02:35:32 2023 local0.notice udpxy[2270]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is exiting with rc=[0]
Thu Apr  6 02:35:32 2023 daemon.info pppd[2386]: Plugin pppoe.so loaded.
Thu Apr  6 02:35:32 2023 daemon.info pppd[2386]: PPPoE plugin from pppd 2.4.9
Thu Apr  6 02:35:32 2023 local0.notice udpxy[2403]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is starting
Thu Apr  6 02:35:32 2023 daemon.notice pppd[2386]: pppd 2.4.9 started by root, uid 0
Thu Apr  6 02:35:33 2023 daemon.info pppd[2386]: PPP session is 37320
Thu Apr  6 02:35:33 2023 daemon.warn pppd[2386]: Connected to cc:1a:fa:eb:0d:c0 via interface eth0
Thu Apr  6 02:35:33 2023 kern.info kernel: [ 8696.630749] pppoe-wan: renamed from ppp0
Thu Apr  6 02:35:33 2023 daemon.info pppd[2386]: Renamed interface ppp0 to pppoe-wan
Thu Apr  6 02:35:33 2023 daemon.info pppd[2386]: Using interface pppoe-wan
Thu Apr  6 02:35:33 2023 daemon.notice pppd[2386]: Connect: pppoe-wan <--> eth0
Thu Apr  6 02:35:33 2023 daemon.info pppd[2386]: syncppp not active
Thu Apr  6 02:35:33 2023 daemon.info pppd[2386]: Remote message: Authentication failed!
Thu Apr  6 02:35:33 2023 daemon.err pppd[2386]: PAP authentication failed
Thu Apr  6 02:35:33 2023 daemon.notice pppd[2386]: Connection terminated.
Thu Apr  6 02:35:33 2023 daemon.info pppd[2386]: Exit.
Thu Apr  6 02:35:33 2023 daemon.notice netifd: Interface 'wan' is now down
Thu Apr  6 02:35:33 2023 daemon.notice netifd: Interface 'wan' is setting up now
Thu Apr  6 02:35:33 2023 daemon.err insmod: module is already loaded - slhc
Thu Apr  6 02:35:33 2023 daemon.err insmod: module is already loaded - ppp_generic
Thu Apr  6 02:35:33 2023 daemon.err insmod: module is already loaded - pppox
Thu Apr  6 02:35:33 2023 daemon.err insmod: module is already loaded - pppoe
Thu Apr  6 02:35:33 2023 daemon.notice netifd: wan (2483): uci: Entry not found
Thu Apr  6 02:35:33 2023 local0.notice udpxy[2403]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is exiting with rc=[0]
Thu Apr  6 02:35:33 2023 daemon.info pppd[2526]: Plugin pppoe.so loaded.
Thu Apr  6 02:35:33 2023 daemon.info pppd[2526]: PPPoE plugin from pppd 2.4.9
Thu Apr  6 02:35:33 2023 local0.notice udpxy[2542]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is starting
Thu Apr  6 02:35:33 2023 daemon.notice pppd[2526]: pppd 2.4.9 started by root, uid 0
Thu Apr  6 02:35:33 2023 daemon.info pppd[2526]: PPP session is 37322
Thu Apr  6 02:35:33 2023 daemon.warn pppd[2526]: Connected to cc:1a:fa:eb:0d:c0 via interface eth0
Thu Apr  6 02:35:33 2023 kern.info kernel: [ 8697.122751] pppoe-wan: renamed from ppp0
Thu Apr  6 02:35:33 2023 daemon.info pppd[2526]: Renamed interface ppp0 to pppoe-wan
Thu Apr  6 02:35:33 2023 daemon.info pppd[2526]: Using interface pppoe-wan
Thu Apr  6 02:35:33 2023 daemon.notice pppd[2526]: Connect: pppoe-wan <--> eth0
Thu Apr  6 02:35:33 2023 daemon.info pppd[2526]: syncppp not active
Thu Apr  6 02:35:33 2023 daemon.info pppd[2526]: Remote message: Authentication failed!
Thu Apr  6 02:35:33 2023 daemon.err pppd[2526]: PAP authentication failed
Thu Apr  6 02:35:33 2023 daemon.notice pppd[2526]: Connection terminated.
Thu Apr  6 02:35:33 2023 daemon.info pppd[2526]: Exit.
Thu Apr  6 02:35:33 2023 daemon.notice netifd: Interface 'wan' is now down
Thu Apr  6 02:35:33 2023 daemon.notice netifd: Interface 'wan' is setting up now
Thu Apr  6 02:35:33 2023 daemon.err insmod: module is already loaded - slhc
Thu Apr  6 02:35:33 2023 daemon.err insmod: module is already loaded - ppp_generic
Thu Apr  6 02:35:33 2023 daemon.err insmod: module is already loaded - pppox
Thu Apr  6 02:35:33 2023 daemon.err insmod: module is already loaded - pppoe
Thu Apr  6 02:35:33 2023 daemon.notice netifd: wan (2619): uci: Entry not found
Thu Apr  6 02:35:33 2023 local0.notice udpxy[2542]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is exiting with rc=[0]
Thu Apr  6 02:35:33 2023 daemon.info pppd[2662]: Plugin pppoe.so loaded.
Thu Apr  6 02:35:33 2023 daemon.info pppd[2662]: PPPoE plugin from pppd 2.4.9
Thu Apr  6 02:35:33 2023 local0.notice udpxy[2679]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is starting
Thu Apr  6 02:35:33 2023 daemon.notice pppd[2662]: pppd 2.4.9 started by root, uid 0
Thu Apr  6 02:35:33 2023 daemon.info pppd[2662]: PPP session is 37323
Thu Apr  6 02:35:33 2023 daemon.warn pppd[2662]: Connected to cc:1a:fa:eb:0d:c0 via interface eth0
Thu Apr  6 02:35:33 2023 kern.info kernel: [ 8697.526756] pppoe-wan: renamed from ppp0
Thu Apr  6 02:35:34 2023 daemon.info pppd[2662]: Renamed interface ppp0 to pppoe-wan
Thu Apr  6 02:35:34 2023 daemon.info pppd[2662]: Using interface pppoe-wan
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2662]: Connect: pppoe-wan <--> eth0
Thu Apr  6 02:35:34 2023 daemon.info pppd[2662]: syncppp not active
Thu Apr  6 02:35:34 2023 daemon.info pppd[2662]: Remote message: Authentication failed!
Thu Apr  6 02:35:34 2023 daemon.err pppd[2662]: PAP authentication failed
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2662]: Connection terminated.
Thu Apr  6 02:35:34 2023 daemon.info pppd[2662]: Exit.
Thu Apr  6 02:35:34 2023 daemon.notice netifd: Interface 'wan' is now down
Thu Apr  6 02:35:34 2023 daemon.notice netifd: Interface 'wan' is setting up now
Thu Apr  6 02:35:34 2023 daemon.err insmod: module is already loaded - slhc
Thu Apr  6 02:35:34 2023 daemon.err insmod: module is already loaded - ppp_generic
Thu Apr  6 02:35:34 2023 daemon.err insmod: module is already loaded - pppox
Thu Apr  6 02:35:34 2023 daemon.err insmod: module is already loaded - pppoe
Thu Apr  6 02:35:34 2023 daemon.notice netifd: wan (2754): uci: Entry not found
Thu Apr  6 02:35:34 2023 local0.notice udpxy[2679]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is exiting with rc=[0]
Thu Apr  6 02:35:34 2023 daemon.info pppd[2798]: Plugin pppoe.so loaded.
Thu Apr  6 02:35:34 2023 daemon.info pppd[2798]: PPPoE plugin from pppd 2.4.9
Thu Apr  6 02:35:34 2023 local0.notice udpxy[2815]: udpxy 1.0-25.0 (prod) standard [Linux 5.4.188 x86_64] is starting
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2798]: pppd 2.4.9 started by root, uid 0
Thu Apr  6 02:35:34 2023 daemon.info pppd[2798]: PPP session is 37324
Thu Apr  6 02:35:34 2023 daemon.warn pppd[2798]: Connected to cc:1a:fa:eb:0d:c0 via interface eth0
Thu Apr  6 02:35:34 2023 kern.info kernel: [ 8697.918739] pppoe-wan: renamed from ppp0
Thu Apr  6 02:35:34 2023 daemon.info pppd[2798]: Renamed interface ppp0 to pppoe-wan
Thu Apr  6 02:35:34 2023 daemon.info pppd[2798]: Using interface pppoe-wan
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2798]: Connect: pppoe-wan <--> eth0
Thu Apr  6 02:35:34 2023 daemon.info pppd[2798]: syncppp not active
Thu Apr  6 02:35:34 2023 daemon.info pppd[2798]: Remote message: Authentication Successful,Welcome!
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2798]: PAP authentication succeeded
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2798]: peer from calling number CC:1A:FA:EB:0D:C0 authorized
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: Joining mDNS multicast group on interface pppoe-wan.IPv6 with address fe80::468a:5b08:a4b6:1655.
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2798]: local  LL address fe80::468a:5b08:*:*
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: New relevant interface pppoe-wan.IPv6 for mDNS.
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2798]: remote LL address fe80::*:*
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: Registering new address record for fe80::468a:5b08:a4b6:1655 on pppoe-wan.*.
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2798]: local  IP address 1*
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2798]: remote IP address 180.171.*.*
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2798]: primary   DNS address 116.228.111.118
Thu Apr  6 02:35:34 2023 daemon.notice pppd[2798]: secondary DNS address 180.168.255.18
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: Joining mDNS multicast group on interface pppoe-wan.IPv4 with address 180.171.60.20.
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: New relevant interface pppoe-wan.IPv4 for mDNS.
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: Registering new address record for 180.*.*.* on pppoe-wan.IPv4.
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: Withdrawing address record for 180.*.*.* on pppoe-wan.
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: Leaving mDNS multicast group on interface pppoe-wan.IPv4 with address 180.171.60.20.
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: Interface pppoe-wan.IPv4 no longer relevant for mDNS.
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: Joining mDNS multicast group on interface pppoe-wan.IPv4 with address 180.171.60.20.
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: New relevant interface pppoe-wan.IPv4 for mDNS.
Thu Apr  6 02:35:34 2023 daemon.info avahi-daemon[14385]: Registering new address record for 180.*.*.*on pppoe-wan.IPv4.
Thu Apr  6 02:35:34 2023 daemon.warn dnsmasq[16757]: failed to create listening socket for fe80::*%pppoe-wan: Address not available
Thu Apr  6 02:35:34 2023 daemon.warn dnsmasq[16757]: failed to create listening socket for fe80::*c0%pppoe-wan: Address not available
Thu Apr  6 02:35:34 2023 daemon.warn dnsmasq[16757]: failed to create listening socket for fe80::*:dc0%pppoe-wan: Address not available
Thu Apr  6 02:35:34 2023 daemon.warn dnsmasq[16757]: failed to create listening socket for fe80::c*%pppoe-wan: Address not available
Thu Apr  6 02:35:34 2023 daemon.notice netifd: Network device 'pppoe-wan' link is up
Thu Apr  6 02:35:34 2023 daemon.notice netifd: Interface 'wan' is now up

**Comment by jjm2473** [comment]
没看到什么时候断开的，只能看到前面很多PPPoE登录失败，问问运营商

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2982/1
