### ISSUE TITLE
WAN口设置多个接口，首页联网状态无法选择

### ISSUE THREAD

**Issue by dsfdfsfds** [istoreos/istoreos#700]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：WAN口为eth0（光猫桥接，PPPoE），为了看iptv设置了vlan（eth0.85、DHCP客户端）。现在首页显示的联网状态、网速信息都是IPTV的信息，但我想看到WAN口拨号上网的情况。

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：
![image](https://user-images.githubusercontent.com/117132841/230699509-7594cd25-d244-4d1c-8f4e-05824d9e79c8.png)
![image](https://user-images.githubusercontent.com/117132841/230699539-68c15f5a-33f3-47ef-87d0-bd55b23984e0.png)
![image](https://user-images.githubusercontent.com/117132841/230699575-ee71f29c-ae15-4f66-ba5b-7d455c1f0a3e.png)

**Comment by jjm2473** [comment]
麻烦看看这个 https://github.com/istoreos/istoreos/discussions/693

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2979/1
