### ISSUE TITLE
ssr-plus 主界面无显示内容

### ISSUE THREAD

**Issue by ShaoyuWang1** [istoreos/istoreos#701]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：更新最新版本后，ssr-plus 主界面无显示内容，已经尝试过命令行remove后重装，问题并未解决

### (2) 路由器型号和固件版本

A：
j4125
iStoreOS 21.02.3 2023033111

### (3) 详细日志和/或截图

A：
现在的界面主界面无内容：
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/40138256/230699715-5cfb8a14-2968-4e65-ad43-91fd40153dfa.png">

**Comment by jjm2473** [comment]
查看插件的日志和系统日志

**Comment by q405812306** [comment]
我最近更新固件也出现过，还好我有dd整个系统，所以直接还原，不升级了

**Comment by jjm2473** [comment]
一般是配置文件损坏导致的，删掉有问题的配置文件，重新安装插件。或者恢复出厂设置再重新配置。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2978/1
