### ISSUE TITLE
R68S在使用tproxy模式时出错，提示 RTNETLINK answers: Address family not supported by protocol。

### ISSUE THREAD

**Issue by popalanluck** [istoreos/istoreos#703]
(1) 具体问题

A：r68s刷任意版本的istoreos固件，在安装shellclash后使用tproxy模式，都会出错。
  提示为：RTNETLINK answers: Address family not supported by protocol
                 RTNETLINK answers: File exists

执行命令  ip -4 rule，同样会出错。
RTNETLINK answers: Address family not supported by protocol
Dump terminated

执行命令 ip -6 rule则正常。

---------------------------------------------

希望istoreos能尽快解决这个小Bug。

--------------------------------------------------------------------------------------------------------------
                                                据说是固件编译的问题，需要在编译前添加
                                                                IP_MULTIPLE_TABLES=y  
--------------------------------------------------------------------------------------------------------------

 (2) 路由器型号和固件版本

A： 路由器型号为 FastRhino R68s   
       固件版本  iStoreOS 21.02.3 2023040712

### (3) 详细日志和/或截图

A：
![image](https://user-images.githubusercontent.com/81753503/230734145-84e2d555-ecae-4b58-b46b-58d9ab4d53e2.png)

**Comment by jjm2473** [comment]
试试这个固件有没有问题 https://we.tl/t-F6F84Jyz6O

**Comment by popalanluck** [comment]
@jjm2473 **非常感谢您。R68S刷入新固件后，ip  route和tproxy模式都能正常使用。此问题已经解决。**

![image](https://user-images.githubusercontent.com/81753503/231282102-f468cb35-af5e-4df9-891a-cb99ba5cceff.png)

**Comment by jjm2473** [comment]
好，感谢反馈

**Comment by jjm2473** [comment]
发布了
