### ISSUE TITLE
希望添加对R5C固件的支持，谢谢大佬们

### ISSUE THREAD

**Issue by PinkPinkFloyd** [istoreos/istoreos#705]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：希望添加对R5C固件的支持

### (2) 路由器型号和固件版本

A：友善R5C

### (3) 详细日志和/或截图

A：刷了R5S的，但无法启动

**Comment by WilliamHuangcc** [comment]
复议
R5C的配置和价位真的非常合适家用，希望能尽快支持，感谢

**Comment by phil-yeecen-cheng** [comment]
> 复议 另外有一个已经做了r5c固件的第三方： https://r5s.cooluc.com/

讲的不是一个事情，用友善自带的岂不是更好？

**Comment by phil-yeecen-cheng** [comment]
希望大佬能尽快帮忙适配R5C

**Comment by jjm2473** [comment]
最新固件已经支持了，跟R5S同一个固件，如果之前刷了R5S的固件，要全新刷机才有效。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2975/1
