### ISSUE TITLE
建议添加对树莓派3的支持

### ISSUE THREAD

**Issue by QueenLoli** [istoreos/istoreos#707]
建议添加对树莓派3的支持，让树莓派3作为旁路由、nas或者bridge来使用

**Comment by zealotCE** [comment]
怕是带不起来哦

**Comment by zealotCE** [comment]
我现在树莓派带个docker 跑点其他的都容易挂

**Comment by QueenLoli** [comment]
> 我现在树莓派带个docker 跑点其他的都容易挂

不打算跑docker，就跑个zerotier、vpn之类的，以及轻量点的东西，比如alist、广告或者snapraid之类，docker在这种1gb内存上连个qbittorrent都跑的不舒服

**Comment by jjm2473** [comment]
可以自己编译

**Comment by paulhybryant** [comment]
给否给一个编译的文档链接？谢谢！

**Comment by jjm2473** [comment]
@paulhybryant 参考openwrt官方的编译教程，都差不多

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2974/1
