### ISSUE TITLE
静态ip地址不在dhcp池中，设备无法上网

### ISSUE THREAD

**Issue by a499738316** [istoreos/istoreos#708]
## 1.关于你要提交的问题
静态分配地址上不了网
### (1) 具体问题

A：我在istore系统的dhcp/dns中静态分配了一个ip地址给设备，但是这个ip不在dhcp的地址池当中，设备通过自动连接的方式拿不到静态分配的ip，导致设备无法上网。
在设备网络里显示没有ipv4

pptp设置客户端分配ip范围，提示是选择不在dhcp分配的范围，但是如果不在这个范围pptp拨号的设备是没有网络的，但是填写dhcp范围的ip又回出现ip的冲突

### (2) 路由器型号和固件版本

A：x86

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
不在地址池中，起码也要同一个网段啊，怎么不行？

**Comment by jjm2473** [comment]
我怀疑你不知道网关和网段的作用，乱配置的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2973/1
