### ISSUE TITLE
EQ12 N100 CPU安装后只识别到百兆

### ISSUE THREAD

**Issue by socekin** [istoreos/istoreos#709]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/874961/231182291-436a717b-8a4d-4c69-8526-e9def819a00b.png">

EQ12 N100 CPU安装后只识别到百兆，网口为i225 2.5G

**Comment by jjm2473** [comment]
一般都是网线质量问题。没看到其他i225用户反馈

**Comment by socekin** [comment]
> 一般都是网线质量问题。没看到其他i225用户反馈

网线没问题，我用同一个路由器的网口、网线，接另外一台设备R5S就正常。我后来换了一个固件也正常了，istore os可能不兼容EQ12 N100

**Comment by jjm2473** [comment]
一般只有网卡对这个有影响，你看看系统日志和内核日志吧

**Comment by jjm2473** [comment]
如果还有问题，试试这个22.03.4的固件 https://github.com/istoreos/istoreos/issues/716

**Comment by jjm2473** [comment]
试试这里的 https://fw.koolcenter.com/iStoreOS/alpha/ 测试固件 istoreos-21.02.3-2023051620-test-netifd-x86-64

**Comment by zkxi** [comment]
![image](https://github.com/istoreos/istoreos/assets/37400193/e1a37faa-2981-4e73-9868-6c10ae46fbf5)
我这也是只有百兆，有时候重启就能解决，也不是个办法呀

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2972/1
