### ISSUE TITLE
统一文件共享问题超过4M无法写入

### ISSUE THREAD

**Issue by xiaoyi2020** [istoreos/istoreos#710]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：  统一文件共享问题超过4M无法写入
       挂载的硬盘可以读取但是超过4M的无法写入  没看到哪里可以修改
### (2) 路由器型号和固件版本

A： j1900
iStoreOS 21.02.3 2023040712

### (3) 详细日志和/或截图

A：
![1](https://user-images.githubusercontent.com/130570687/231733918-070b8c33-2ea9-475d-9d88-4fb5ac25cccc.png)

![2](https://user-images.githubusercontent.com/130570687/231733939-e52c45b8-12aa-4123-9c6a-b025c66c0123.png)

**Comment by jjm2473** [comment]
不要共享/mnt，而是共享/mnt里面的硬盘。

windows比较傻逼，只会计算根目录的大小，/mnt目录就是只有4MB，因为它自己不需要存数据，只要创建文件夹给硬盘挂载就行了。
/mnt只读是没问题的，写入的时候windows会判断错误。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2971/1
