### ISSUE TITLE
您好，请问旁路由模式下如何关闭主界面中的流量统计功能。

### ISSUE THREAD

**Issue by doudou6** [istoreos/istoreos#712]
您好，请问旁路由模式下如何关闭主界面中的流量统计功能。此功能开启会统计lan口流量，占用主机性能。

**Comment by jjm2473** [comment]
网卡本身就有统计啊，开不开都一样

**Comment by jjm2473** [comment]
内核本身就会记录网络接口的流量，可以用`ip -s link show br-lan`读出来。quickstart不过是5秒钟读一次数据然后计算差值，这能有什么性能损耗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2968/1
