### ISSUE TITLE
想修改从应用市场创建homeassistant docker容器时的脚本，可否提供路径及修改指引？

### ISSUE THREAD

**Issue by 319293013** [istoreos/istoreos#717]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：想修改从应用市场创建homeassistant docker容器时的脚本，添加一条挂载目录，用于保存私钥可否提供路径及修改指引

### (2) 路由器型号和固件版本

A：x86- iStoreOS 21.02.3 2023040712

### (3) 详细日志和/或截图

A：
![RIRX)WTC$2LRBU@(JA SM$9](https://user-images.githubusercontent.com/58453893/232234268-0a97ceb6-a093-44f5-b237-73c79a28fef8.png)

**Comment by jjm2473** [comment]
一般都在 /usr/libexec/istorec/ 里面

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2964/1
