### ISSUE TITLE
java JDK环境没办法配置

### ISSUE THREAD

**Issue by sxk349752531** [istoreos/istoreos#718]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
java JDK环境没办法配置
A：

### (2) 路由器型号和固件版本
R68S iStoreOS 21.02.3 2023033111
A：

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
你问的啥问题？你要在istore里面安装jdk？

**Comment by xiaomo-xxx** [comment]
可以参考这篇文章
https://blog.csdn.net/qq_39858654/article/details/135777769

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2963/1
