### ISSUE TITLE
最近更新的实时流量luci-app-rtbwmon在开启软件流量后无效。

### ISSUE THREAD

**Issue by wolvth** [istoreos/istoreos#722]
最近更新的实时流量luci-app-rtbwmon在开启软件流量分载后无效
另外不知道能不能做到同一IP，不通端口的网速显示

R4S，iStoreOS 21.02.3 2023041417

**Comment by jjm2473** [comment]
rtbwmon是依赖防火墙的统计功能，如果你的内核绕过了防火墙，那就没法统计了。

要看端口的流量可以在 “状态” - “实时信息” - “连接” 。

如前面所说，rtbwmon依赖防火墙的统计功能，如果要统计端口，那需要产生无数防火墙规则，不可能这样做。可以试试另一个流量统计插件。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2961/1
