### ISSUE TITLE
给R2S增加温控风扇脚本

### ISSUE THREAD

**Issue by heyaaron-Wu** [istoreos/istoreos#724]
希望新版固件更新里面增加风扇的脚本，因为夏天到了，在弱电箱里跑比较热

**Comment by jjm2473** [comment]
R2S里面还有空间风扇？

**Comment by heyaaron-Wu** [comment]
![Uploading IMG_6212.jpeg…]()
外置风扇

**Comment by jjm2473** [comment]
usb风扇？

**Comment by heyaaron-Wu** [comment]
![IMG_6213](https://github.com/istoreos/istoreos/assets/94272469/f0d2019f-68a3-488e-8c30-0656831d3c1e)
里面有5v

**Comment by heyaaron-Wu** [comment]
其他openwrt系统里面的启动项带有温度判断

**Comment by heyaaron-Wu** [comment]
谢谢啦

**Comment by heyaaron-Wu** [comment]
还有一个问题 关闭自动协商之后无法上网只能重启

**Comment by jjm2473** [comment]
@heyaaron-Wu 发新的issue

**Comment by heyaaron-Wu** [comment]
已发布

**Comment by jjm2473** [comment]
测试下这个固件 https://we.tl/t-B4Y3Np37ey ，应该50度开始就会启动风扇，根据温度会自动调整风扇转速。

**Comment by heyaaron-Wu** [comment]
得星期五测试

**Comment by heyaaron-Wu** [comment]
无法进入后台

**Comment by heyaaron-Wu** [comment]
测试完毕 机器已自动调整风扇转速

**Comment by jjm2473** [comment]
新固件会集成这个功能

**Comment by heyaaron-Wu** [comment]
未来更新还是现在已集成？

**Comment by Lil-Gun** [comment]
> 新固件会集成这个功能

希望R5S的固件也加上温控风扇脚本

**Comment by jjm2473** [comment]
@heyaaron-Wu 昨天的固件支持了

**Comment by lzy822052696** [comment]
未来会加入风扇配置页面吗？

**Comment by jjm2473** [comment]
> 未来会加入风扇配置页面吗？

技术上是没啥问题的，ARS2就有风扇配置页面，只是要其他机型的话，需要能够自动判断哪个温度配置是对应风扇的

**Comment by shaw830** [comment]
请问风扇脚本在哪里？我觉得50度温度有点高~想自行修改下。谢谢

**Comment by heyaaron-Wu** [comment]
目前还没有

**Comment by heyaaron-Wu** [comment]
> 请问风扇脚本在哪里？我觉得50度温度有点高~想自行修改下。谢谢

目前还没有

**Comment by jjm2473** [comment]
@shaw830 50度还高？那是cpu的温度，默认70度才开始降频呢。像r4s的官方配置55度才启动风扇。

**Comment by jjm2473** [comment]
@shaw830 哦，rk3328默认配置是85度才降频，50度还离得远呢

**Comment by AssassinOperation** [comment]
大佬可以给R68S也增加温控嘛😭

**Comment by heyaaron-Wu** [comment]
感觉每台机器都要温控🤔️

**Comment by jjm2473** [comment]
@AssassinOperation R68s有风扇接口？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2959/1
