### ISSUE TITLE
畅网N100 4个2.5G网口 只读出来一个wan口是2.5G，其他lan口都是1G

### ISSUE THREAD

**Issue by FROST1234** [istoreos/istoreos#725]
网卡型号intel i226, 装的2023040712这个版本
![1681925261533](https://user-images.githubusercontent.com/34257385/233153569-28a1d285-e8f1-435f-86f5-9067e7a126a1.jpg)

**Comment by jjm2473** [comment]
试试这里的测试固件 https://github.com/istoreos/istoreos/issues/716

**Comment by MAOGE2018** [comment]
https://github.com/istoreos/istoreos/discussions/732
试试这里方案行不行

**Comment by jjm2473** [comment]
试试这里的 https://fw.koolcenter.com/iStoreOS/alpha/  测试固件 istoreos-21.02.3-2023051620-test-netifd-x86-64

**Comment by RICwang** [comment]
这还要看网口对接设备的网口是否也是2.5G的，不是的话，只会以较小的那端显示，譬如你接的设备是百兆的网口，那这里只会显示100Mbit/s

**Comment by jjm2473** [comment]
升级最新固件看还有没有问题，上周应该修复了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2958/1
