### ISSUE TITLE
istoreos开启防火墙后设备无法访问外网ipv6

### ISSUE THREAD

**Issue by stjiji** [istoreos/istoreos#726]
N4100软路由安装istoreos拨号上网能正常获取公网ipv6地址。
默认开启ipv6防火墙后，内网设备(手机，PC等)无法通过外网的ipv6测试。

请问这是正常的吗，需要在通信规则里自行配置从lan到wan的ipv6流量吗
![Screenshot_2023-04-20-11-11-09-92_a252b927494330cdc2c8ba3b3f952e5e](https://user-images.githubusercontent.com/71817538/233249385-f607967f-e800-4828-854b-8b0898dce684.jpg)

![IMG_20230420_110653](https://user-images.githubusercontent.com/71817538/233249204-b4344905-f9bf-475a-8ba0-8dca29e7cbc6.jpg)
![Screenshot_2023-04-20-11-07-47-14_a252b927494330cdc2c8ba3b3f952e5e](https://user-images.githubusercontent.com/71817538/233249290-49aa4346-0e46-421d-8c16-5ecb30b5ee53.jpg)
![Screenshot_2023-04-20-11-08-11-40_a252b927494330cdc2c8ba3b3f952e5e](https://user-images.githubusercontent.com/71817538/233249360-3c241000-2f85-4771-a4cb-455f33a28d59.jpg)

**Comment by jjm2473** [comment]
你的内网设备有获取到ipv6地址吗

**Comment by stjiji** [comment]
> 你的内网设备有获取到IPv6地址吗

有的，内网设备都能获取到ipv6地址。

**Comment by jjm2473** [comment]
那你在内网设备执行 `ping6 240c::6666` ，还有 `nslookup taobao.com 192.168.100.1` (192.168.100.1改成软路由地址)

**Comment by jjm2473** [comment]
还有 `traceroute6 240c::6666`

**Comment by stjiji** [comment]
> 那你在内网设备操作`ping6 240c::6666`，还有`nslookup taobao.com 192.168.100.1`(192.168.100.1改成软件地址由地址)

![QQ图片20230422073021](https://user-images.githubusercontent.com/71817538/233749095-d0978b39-c170-4072-bc48-28786f35e289.png)
这是用内网群晖Ping后的结果，不知道能不能看出大概是哪里的问题。非常感谢您的回复。感激。

**Comment by stjiji** [comment]
> 那你在内网设备操作`ping6 240c::6666`，还有`nslookup taobao.com 192.168.100.1`(192.168.100.1改成软件地址由地址)

![QQ图片20230422073021](https://user-images.githubusercontent.com/71817538/233749095-d0978b39-c170-4072-bc48-28786f35e289.png)
这是用内网群晖Ping后的结果，不知道能不能看出大概是哪里的问题。非常感谢您的回复。感激。

**Comment by jjm2473** [comment]
看起来没问题啊，dns正常，路由也正常。除非你的内网设备的dns不是192.168.3.1？

**Comment by stjiji** [comment]
> 看起没有问题啊，dns正常，路由也正常。除了你的内网设备的dns不是192.168.3.1？

非常感谢您的解答

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2957/1
