### ISSUE TITLE
iStoreOS的iperf版本过低

### ISSUE THREAD

**Issue by xuzengli** [istoreos/istoreos#728]
安装了最新的iStoreOS 21.02.3 2023040712
iperf版本是2.0.13，最新的版本已经到了2.1.9。
目前的版本不支持--reverse参数，也就是反向测速。

可能有人会说为什么不用iperf3，iperf3也是有问题的：
1、windows版本太低（2016年的3.1.3，第三方）。iperf3并不是iperf2的升级版本，iperf2一直在更新，而且提供官方Windows版本。
2、在有线局域网环境，iperf3是没问题的。但在时延稍大的环境，比如Wi-Fi或广域网，iperf3的测速结果明显低于iperf。

**Comment by jjm2473** [comment]
这些插件都是跟随openwrt的release，你在软件包更新看看有没有新版本。也可以自己去 https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.3/packages/ 下载ipk安装，一般都能用

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2956/1
