### ISSUE TITLE
怎么使用终端配置端口转发呢

### ISSUE THREAD

**Issue by WuMing-dp** [istoreos/istoreos#729]
已经配置好了ddns，之前在设置里配置好了一下基础的端口转发规则，现在可以使用域名进入终端，如图，**已经在/etc/config/firewall添加了新的端口转发规则**，但是不知道怎么让它生效，常用的Linux firewall命令无效，请问op的防火墙restart命令是什么，或者怎么使用终端配置端口转发。
[![oeX53A.png](https://www.helloimg.com/images/2023/04/21/oeX53A.png)](https://www.helloimg.com/image/oeX53A)

然后我还修改了/etc/config/uhttpd 这个文件，想将op的web页面用8080端口打开，然后可以通过设置端口转发设置外网访问op的web页，但是修改重启后貌似还是80端口

[![oeXRZm.png](https://www.helloimg.com/images/2023/04/21/oeXRZm.png)](https://www.helloimg.com/image/oeXRZm)

**Comment by jjm2473** [comment]
防火墙修改以后，执行 `/etc/init.d/firewall reload` 重新加载，其他插件也都类似。配置文件和脚本的对应关系一般是名称对应，如果不清楚，可以看看 `/etc/config/ucitrack` 里面的记录

**Comment by jjm2473** [comment]
防火墙还支持加载外部脚本，可以自己写iptables命令，可能更方便你维护

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2955/1
