### ISSUE TITLE
AMD5900hx物理机安装温度监控不显示

### ISSUE THREAD

**Issue by 4538640** [istoreos/istoreos#731]
反馈bug/问题模板，提建议请删除

1.用物理机5900hx安装istoreOS，温度监控不能正常显示

2. 详细叙述

(1) 具体问题

A：温度监控不显示

 (2) 路由器型号和固件版本

A：AMD5900hx 固件版本
iStoreOS 21.02.3 2023042111

(3) 详细日志和/或截图

![IMG_1466](https://user-images.githubusercontent.com/60852679/233598301-bb15820b-5b88-4d22-b0da-b28616a9ec54.png)

**Comment by 4538640** [comment]
![IMG_1480](https://user-images.githubusercontent.com/60852679/233661868-c5c0fb97-4340-4463-8de8-0ecfb78d35bf.png)
sensors可以返回温度

**Comment by jjm2473** [comment]
你这个温度不是scsi的吗，也就是硬盘的吧？

**Comment by 4538640** [comment]
您发给我的信件已经收到。--------------------------------------------中文邮箱第一品牌——QQ免费邮 mail.qq.comThis is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by 4538640** [comment]
这个是什么温度我也不太清楚，就是首页的温度监控无法显示cpu核心温度

**Comment by terryzung** [comment]
AMD都不能显示温度，我也是这样

**Comment by jjm2473** [comment]
你们执行这行命令看看，把结果复制出来 `(cd /sys/class/thermal ; ls | grep thermal_zone | xargs -rn1 sh -c 'echo -n "$0 "; cat $0/type | tr -d "\\n"; echo -n " " ; cat $0/temp')`

**Comment by terryzung** [comment]
> 你们在终或ssh执行这行命令看看，把结果复制出来 `(cd /sys/class/thermal ; ls | grep thermal_zone | xargs -rn1 sh -c 'echo -n "$0 "; cat $0/type | tr -d "\\n"; echo -n " " ; cat $0/temp')`

执行了没有什么结果的

**Comment by 4538640** [comment]
> 

我也执行了没反应

**Comment by jjm2473** [comment]
那就是amd机型都没在内核注册温度传感器

**Comment by 4538640** [comment]
您发给我的信件已经收到。--------------------------------------------中文邮箱第一品牌——QQ免费邮 mail.qq.comThis is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by terryzung** [comment]
> 那就是amd机型都没在内核注册温度传感器

曾经有个一个版本显示过，很早前第二个版本。

**Comment by 4538640** [comment]
> 那就是amd机型都没在内核注册温度传感器

大神能在固件中添加amd处理器的温度显示插件吗

**Comment by jjm2473** [comment]
没法支持，内核都没注册传感器给用户端。

**Comment by 4538640** [comment]
您发给我的信件已经收到。--------------------------------------------中文邮箱第一品牌——QQ免费邮 mail.qq.comThis is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2954/1

**Comment by 4538640** [comment]
您发给我的信件已经收到。--------------------------------------------中文邮箱第一品牌——QQ免费邮 mail.qq.comThis is an automatic reply, confirming that your e-mail was received.Thank you
