### ISSUE TITLE
希望增加firefly itx-3588j的支持

### ISSUE THREAD

**Issue by tuntun2019** [istoreos/istoreos#734]
路由nas神板，双网口，4sata，官网有全套资料，烦请支持

**Comment by jjm2473** [comment]
非热门硬件，让厂家自己PR代码适配，或者找我们合作

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2952/1
