### ISSUE TITLE
PVE安装后, 只有PVE主机和istoreos互通, 内网其它主机无法访问

### ISSUE THREAD

**Issue by wxf26054** [istoreos/istoreos#735]
PVE安装后, 只有PVE主机和istoreos互通, 其它内网主机不能访问

**Comment by jjm2473** [comment]
你会配置虚拟机网桥吗？

**Comment by wxf26054** [comment]
> 你会配置虚拟机网桥吗？

网桥配置过了
![image](https://user-images.githubusercontent.com/22016320/233945956-5d2f9763-2e2b-45d1-a3df-fcbcaf44236f.png)

**Comment by jjm2473** [comment]
你这不是只桥接了一个网口吗？

**Comment by wxf26054** [comment]
> 你这不是只桥接了一个网口吗？
已经解决了, 是docker的问题

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2951/1
