### ISSUE TITLE
iStoreos网页端的易有云文件管理器新建文件时间是错误的

### ISSUE THREAD

**Issue by zzj6116** [istoreos/istoreos#736]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue
X
### (1) 具体问题

A：iStoreos网页端的易有云文件管理器新建文件时间是错误的，已查，软路由系统时间是正确的，在iStoreos网页端首页自带的文件管理器，列表模式，新建文件时间是错误的，慢了大约8小时。易有云APP上显示的文件时间也是错误的，但是Windows端通过SMB挂载的istoreos的硬盘，同一个文件，时间又是正确的
### (2) 路由器型号和固件版本

A：X86，j4125, 固件版本iStoreOS 21.02.3 2023042111

### (3) 详细日志和/或截图

A：
![dd85294abb459a970465d4b77f781d5](https://user-images.githubusercontent.com/76789765/233832857-604e0b8e-57e8-4cbd-a139-2f5f218ea6c3.png)

![bbf087c4f375f1af827f91c155eb213](https://user-images.githubusercontent.com/76789765/233832870-5b193160-237e-407c-8732-a3ab0240dca8.png)
![d6a5fc854dbe5a99a8676aec33bd860](https://user-images.githubusercontent.com/76789765/233832880-58f4490a-4827-4063-99a2-fb957db45f11.png)

**Comment by Bugaoxingxx** [comment]
8个小时，要么检查下OS内的时区是不是UTC啥的？

**Comment by jjm2473** [comment]
那应该是界面上显示的时区有问题

**Comment by jannson** [comment]
感谢反馈，我们来修复。

配置界面应该做个时区选择，默认是 +8 的时区。

**Comment by N1k1Zhang** [comment]
2023年12月24日，我也有这个同样的问题。

**Comment by jannson** [comment]
下个版本修复了。本周的版本。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2950/1
