### ISSUE TITLE
首页系统时间比本地时间快8小时

### ISSUE THREAD

**Issue by wcbspp** [istoreos/istoreos#737]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：首页系统时间比本地时间快8小时

### (2) 路由器型号和固件版本

A：R4SE -21.02.3 2023042111

### (3) 详细日志和/或截图

A：
![f8e847dfa142d996bb4a2730f209d01](https://user-images.githubusercontent.com/125283858/233833335-c7cf69c7-9eab-4431-889e-3ac1e8e6b558.png)

**Comment by rootphantomer** [comment]
这种一般系统时区里没选择utc+8北京时区，显示的是utc时区

**Comment by wcbspp** [comment]
> 这种一般系统时区里没选择utc+8北京时区，显示的是utc时区

好想没有utc➕8北京时区这个选项呢 现在选的是ASia/Shanghai

**Comment by jjm2473** [comment]
那就是你的电脑时间不对啊，可能电脑设置成了UTC时区，然后却按北京时间设置，然后还同步到 R4SE 了，那不就错误了吗

**Comment by wcbspp** [comment]
> 那就是你的电脑时间不对啊，可能电脑设置成了UTC时间区，然后却按北京时间设置，然后又同步到R4SE了，那不就错了吗

应该不是 电脑是UTC+8  istore os 在设置里是这样
**
![image](https://user-images.githubusercontent.com/125283858/233913576-610f7f5f-84e7-40c8-aea2-c76f53bbe97a.png)
**

**Comment by jjm2473** [comment]
软路由重启以后还有这个问题吗？

**Comment by wcbspp** [comment]
> 软路由重启以后还有这个问题吗？

是的 很早之前就有这个问题了 一些插件的日志时间都相差了八小时  opkg install zoneinfo-asia 之后其他插件的时间对了
后台看是这样
![image](https://user-images.githubusercontent.com/125283858/233919980-32684416-06ba-4653-a671-719781c8d301.png)

**Comment by jjm2473** [comment]
跟date -R无关，首页实际是读取 `ubus call system info` 里面的时间轴，然后转换成字符串，转换过程在设备上，不在浏览器。

**Comment by jjm2473** [comment]
不知道怎么解决，我也是用北京时间，没遇到过这个问题

**Comment by wcbspp** [comment]
> 不知道怎么解决，我也是用北京时间，没遇到过这个问题
获取的时间戳确实比本地时间快了8小时 头痛
![image](https://user-images.githubusercontent.com/125283858/234929882-0e685b4b-19c3-4ecd-a487-205311d065eb.png)
![image](https://user-images.githubusercontent.com/125283858/234930120-0cb81c2b-f0de-4178-848c-90c83e1a5a8e.png)

**Comment by jjm2473** [comment]
我看了下自己的设备，localtime确实不是UTC时间轴，而是本地的时间轴，我看看后端那边能不能指定时区。

**Comment by jjm2473** [comment]
修复了。

这个问题的复现方式就是 `opkg install zoneinfo-asia` ，然后重启。

后端改成UTC就不受影响了。

**Comment by wcbspp** [comment]
> 修复了。
> 
> 这个问题的复现方式就是 `opkg install zoneinfo-asia` ，然后重启。
> 
> 后端改成UTC就不受影响了。

牛~ 需要等待新版本更新不

**Comment by jjm2473** [comment]
如果你用了沙箱，我可以给你个ipk安装，以后升级固件退出沙箱就行。如果没用沙箱，那还是等固件更新吧，以免麻烦。

这是已经编译的quickstart，如果你有会用也可以自己尝试，但是如果你替换了系统里面的quickstart，之后固件更新就不会同步升级了（除非用沙箱）。  https://github.com/linkease/istore-packages/releases/download/prebuilt/quickstart-binary-0.7.6.tar.gz

**Comment by wcbspp** [comment]
> 如果你用了沙箱，我可以给你个ipk安装，以后升级固件退出沙箱就行。如果没用沙箱，那还是等固件更新吧，以免麻烦。
> 
> 这是已经编译的quickstart，如果你有会用也可以自己尝试，但是如果你替换了系统里面的quickstart，之后固件更新就不会同步升级了（除非用沙箱）。 https://github.com/linkease/istore-packages/releases/download/prebuilt/quickstart-binary-0.7.6.tar.gz

非常感谢~！

**Comment by yuankan1986** [comment]
> 修复了。
> 
> 这个问题的复现方式就是 `opkg install zoneinfo-asia` ，然后重启。
> 
> 后端改成UTC就不受影响了。

怎么解决的，我也遇到了同样的问题。感谢。

**Comment by jjm2473** [comment]
升级最新固件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2949/1
