### ISSUE TITLE
如果没有显示器，如何通过ssh等方式刷固件到硬盘里面

### ISSUE THREAD

**Issue by smallfawn** [istoreos/istoreos#738]
1) 具体问题

A：有u盘，和鼠标键盘，但是没有显示器，

### (2) 路由器型号和固件版本

A：j4125工控机

**Comment by jjm2473** [comment]
在u盘启动以后，连个网线在lan口，然后执行 `quickstart` ，有安装菜单

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2948/1
