### ISSUE TITLE
R66S/68S 会有异常高的CPU Load

### ISSUE THREAD

**Issue by xingruilin** [istoreos/istoreos#741]
### (1) 具体问题

A：R66S/68S 会有异常高的CPU Load

如图， 明明没有进程在大量占用CPU，平均负载却有4+；

我感觉这不太正常，因为我的另一台X86的istore设备并不会这样。希望有大佬解释或修复

### (2) 路由器型号和固件版本

固件版本 | iStoreOS 21.02.3 2023042111 / LuCI istoreos-21.02 branch git-23.088.34636-f8cc111

### (3) 详细日志和/或截图

A：
![007RgMFSgy1hddkvp9vmyj31y10pa4qp](https://user-images.githubusercontent.com/34702161/234647823-ad2b4227-41fc-4fd3-b0fb-fbb5f01e016b.jpg)

**Comment by jjm2473** [comment]
有使用机械硬盘吗

**Comment by xingruilin** [comment]
没有使用机械硬盘

**Comment by jjm2473** [comment]
那么这是刚开机的时候的负载吗，过几分钟还这样？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2946/1
