### ISSUE TITLE
安装OpneClash后客户端能科学访问，但是iStoreOS自身SSH后台不能科学访问，ping谷歌不通

### ISSUE THREAD

**Issue by Ceonta** [istoreos/istoreos#746]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：安装OpneClash后客户端能科学访问，但是iStoreOS自身SSH后台不能科学访问，ping谷歌不通

### (2) 路由器型号和固件版本

A：iStoreOS 21.02.3, 2023042111

### (3) 详细日志和/或截图

A：无

**Comment by jjm2473** [comment]
既然客户端都没问题了，那可能是配置错误啊，如果还有问题也应该反馈给openclash

**Comment by Aaronwang81** [comment]
想ping上openvpn。什么协议都没问题。
也可以用httping。
本机ssh不能访问应该是没有代理本机。没有配置成透明代理吧？

**Comment by anglebai** [comment]
有同样的问题，期待解决办法
