### ISSUE TITLE
R68s CPU平均负载高达10以上

### ISSUE THREAD

**Issue by binfoo** [istoreos/istoreos#747]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by binfoo** [comment]
2. 详细叙述
(1) 具体问题
A：R68S的状态，CPU平均负载达到10以上

(2) 路由器型号和固件版本
A：FastRhino R68s 型号；固件版本：iStoreOS 21.02.3 2023042111 / LuCI openwrt-21.02 branch git-23.093.57360-e98243e

(3) 详细日志和/或截图
A：截图如下
![image](https://user-images.githubusercontent.com/18188540/235047830-b52cb4fe-842b-4b20-8fbf-1b648efa7d2e.png)
![image](https://user-images.githubusercontent.com/18188540/235047863-e18c2ac6-b93e-4bab-8e81-532f1a7bbdb1.png)

**Comment by jjm2473** [comment]
看看是不是哪个进程死循环了。恢复出厂设置如果有问题再来反馈

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2941/1
