### ISSUE TITLE
计划任务似乎是坏的

### ISSUE THREAD

**Issue by 858622025** [istoreos/istoreos#751]
我设置了计划任务，但是启动项看不到，也不执行我的脚本
![A(T7QIIIW{D}G`1 4H _{$4](https://user-images.githubusercontent.com/16350440/235357576-0c812307-ee45-47dd-a9d1-688bc02ae1e4.jpg)

**Comment by 858622025** [comment]
> 启动项肯定看不到啊，这又不是启动项。
> 
> 首先检查你的脚本有没有可执行权限。
> 
> 其次，计划任务第一位代表的是分钟，不是秒钟，是不是你搞错了单位？还有“01”是什么意思，为什么不用“1”。 `1 * * * *`表示每个小时的01分执行，你等了一小时吗？ `*/6 * * * *`表示每个小时里面能被6整除的分钟执行一次，例如“12:00, 12:06, 12:12, 12:18...”。

这个问题没有了，后来从日志中查到了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2938/1
