### ISSUE TITLE
r5s使用FriendlyWrt emmc上传固件后提示“表单令牌不匹配”

### ISSUE THREAD

**Issue by fangbian233** [istoreos/istoreos#758]
r5s使用FriendlyWrt emmc上传固件后提示“表单令牌不匹配”
![image](https://user-images.githubusercontent.com/94010330/236510294-4fa75c2b-c464-4676-a037-ef461e3748a3.png)

**Comment by jjm2473** [comment]
应该太久没刷新页面了。而且这是friendlywrt的问题，你来这里发？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2932/1
