### ISSUE TITLE
首页温度检测的命令在那里修改

### ISSUE THREAD

**Issue by m0eak** [istoreos/istoreos#762]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：因为是pve里安装的所以检测不到温度，但是可以通过命令行和ssh密钥登录宿主机使用命令获取，想知道首页的温度信息是怎么实现的，能在哪修改一下吗?

### (2) 路由器型号和固件版本

A：J4125

### (3) 详细日志和/或截图

A：

**Comment by ysjy11** [comment]
也有同样疑问

**Comment by jjm2473** [comment]
没有命令，就是读取 /sys/class/thermal 里面的文件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2928/1
