### ISSUE TITLE
base-files更新无法进后台

### ISSUE THREAD

**Issue by dsjaklflk** [istoreos/istoreos#765]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by dsjaklflk** [comment]
r4se安装最新istores，在系统软件包里更新了base-files后，后台无法进入，出现登陆界面，名称默认root，密码为默认密码无更改依然无法进入
![IMG_1877](https://github.com/istoreos/istoreos/assets/97736369/55ada728-884a-4a42-96d4-bfc08976f236)

**Comment by jjm2473** [comment]
谁教你更新base-files的？大部分系统包都不应该更新，要是更新到不兼容的版本，可不是登录不了了，可能直接启动不了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2925/1
