### ISSUE TITLE
base-files更新后不能进后台

### ISSUE THREAD

**Issue by dsjaklflk** [istoreos/istoreos#766]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：在系统软件包里更新base-files后无法进入后台，密码和用户名都为更改过为默认

### (2) 路由器型号和固件版本

A：r4se最新固件

### (3) 详细日志和/或截图

A：
![IMG_1877](https://github.com/istoreos/istoreos/assets/97736369/f1926194-9993-4b64-afdb-622f180cb81a)

**Comment by jjm2473** [comment]
不能更新这个包。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2924/1
