### ISSUE TITLE
首页的的“DNS设置”是否支持DoH？

### ISSUE THREAD

**Issue by krkrchan** [istoreos/istoreos#772]
如题，我尝试添加DoH地址，但过一会儿就上不了网了。请问这里能添加DoH解析地址吗

**Comment by jjm2473** [comment]
不支持，这个实际就是修改网络接口里面的lan口dns

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2920/1
