### ISSUE TITLE
r2s关闭自动协商无法上网

### ISSUE THREAD

**Issue by heyaaron-Wu** [istoreos/istoreos#773]
详细叙述

### (1) 具体问题

A：使用ethtool -s eth0 speed 1000 duplex full autoneg off 命令关闭自动协商eth0变1000m 设备无法上网需重启 重启过后eth0变回原来100m

### (2) 路由器型号和固件版本

A：r2s 21.02.3-2023042111

**Comment by jjm2473** [comment]
既然都自动协商到百兆了，一般都是网线质量不行，或者对面不是千兆。你强行设置千兆要么不稳定，要么就直接上不了网

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2919/1
