### ISSUE TITLE
NASTOOLS问题，是不是噶了？

### ISSUE THREAD

**Issue by My-By** [istoreos/istoreos#774]
NASTOOLS是不是噶了？最新版本的3.2.2进不去，日志显示以下，我以为是我自己的问题，结果试了别人的软路由也一样，我的是E3845，我朋友是N5105，系统版本都是istoreos-21.02.3-2023051217-x86-64-squashfs-combined-efi.img.gz这个文件。

stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory
stderr: python3: can't open file '/nas-tools/run.py': [Errno 2] No such file or directory

**Comment by weiwei52o** [comment]
不看nastools官方群吗？nastools被国内派派助手给破解了。并且还反手给举报了，所以nastools紧急下架了，并且停止后续自动更新，，哎。国内这些恶心人的助手

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2918/1
