### ISSUE TITLE
登录后台无效的用户名和/或密码？

### ISSUE THREAD

**Issue by wwww05** [istoreos/istoreos#775]
默认网段 默认密码 没有公网

版本号 iStoreOS 21.02.3 2023051217
 
 X86 ESXI 8.0 u1

之前稳定使用很久了没遇到过这种问题 现在ESXI后台修改一次密码 过一段时间 就无法登录后台了

**Comment by jjm2473** [comment]
如果不是你改的密码，那可能是被黑客/病毒改了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2917/1
