### ISSUE TITLE
关于防火墙 重启

### ISSUE THREAD

**Issue by wanglongfei8899** [istoreos/istoreos#777]
每次重启 防火墙自动恢复设置
![0214f4cf924b261396f73a15e65ac1d](https://github.com/istoreos/istoreos/assets/75508757/21e5e03f-d216-4cf6-b187-978242231bf0)

**Comment by jjm2473** [comment]
不是让你先搜索issue了吗？ https://github.com/istoreos/istoreos/discussions/662

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2915/1
