### ISSUE TITLE
qbittorrent4.5.2(更新日期: 2023-05-15 13:43:08)遇到的问题

### ISSUE THREAD

**Issue by 18309871333** [istoreos/istoreos#779]
(1) 具体问题

A：昨晚更新了qbittorrent4.5.2(更新日期: 2023-05-15 13:43:08)这个版本，更新后qb总卡死，使用ddnsto链接卡住，等几分钟连接上发现qb重启了，这半天时间内出现了10几次这种情况，昨晚到今早一点上传下载都没动。

 (2) 路由器型号和固件版本

A：零客EQ12
iStoreOS 21.02.3 2023051217 / LuCI istoreos-21.02 branch git-23.088.34636-f8cc111

(3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
没看到其他人反馈，而且我测试过BT下载，起码几百兆的文件是没问题的

**Comment by 18309871333** [comment]
昨天晚上更新之前没这个问题，更新完就总卡主，挂 pt 种子，差不多都是 100g 左右，就这次更新出问题了，前两天更新两次都没这问题

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2914/1
