### ISSUE TITLE
DNS异常岀错率高

### ISSUE THREAD

**Issue by lmwyl** [istoreos/istoreos#782]
x86_64_efi的iStoreOS固件在“网络-->接口-->LAN-编辑-更改IPv4地址”确认重启后会岀现DNS异常岀错率十分高

**Comment by jjm2473** [comment]
过一会儿还是dns异常吗

**Comment by lmwyl** [comment]
解决方法是DNS配置改手动设置成第一级路由器的网关IP或网络营运商的网关IP可以解决的。

**Comment by jjm2473** [comment]
我倒是怀疑你的DNS地址跟内网IP冲突了，导致访问DNS时往内网发，而不是往外网发。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2911/1
