### ISSUE TITLE
istoreos这么好用既然支持DDNSTO，为什么没有Tailscale呢？

### ISSUE THREAD

**Issue by ZTOA10** [istoreos/istoreos#783]
如题：istoreos这么好用既然支持DDNSTO，为什么没有Tailscale呢？

**Comment by jjm2473** [comment]
直接opkg就能安装啊，关键是要会配置

**Comment by cero-ss** [comment]
我用的就是tailscale
手动下载安装tailscale和tailscaled
运行tailscale up --advertise-exit-node --accept-routes --advertise-routes=192.168.31.0/24   [这里填上软路由地址，如果是192.168.100.1就填192.168.100.0/24]，复制给的地址到浏览器上
然后在接口里新建一个选择tailscale设备，填上给的虚拟ip地址就行了
<img width="914" alt="360截图174604098212494" src="https://github.com/istoreos/istoreos/assets/32891402/7af06b8f-9037-42b6-8247-d4460a875ee7">
<img width="986" alt="360截图17001017355589" src="https://github.com/istoreos/istoreos/assets/32891402/f490bece-e5b3-4603-8643-67937df44751">

**Comment by qzydustin** [comment]
OpenWRT的教程可以在iStoreOS上正常使用，包括exit node和subnet router
https://openwrt.org/docs/guide-user/services/vpn/tailscale/start

**Comment by jjm2473** [comment]
tailscale还有个docker版，好像界面更好用吧

**Comment by nobodysclown** [comment]
手动安装成功了，分享下。下载对应的ipk，然后安装。

wget https://downloads.openwrt.org/snapshots/packages/aarch64_generic/packages/tailscale_1.48.2-1_aarch64_generic.ipk
wget https://downloads.openwrt.org/snapshots/packages/aarch64_generic/packages/tailscaled_1.48.2-1_aarch64_generic.ipk

opkg install tailscale_1.48.2-1_aarch64_generic.ipk tailscaled_1.48.2-1_aarch64_generic.ipk

**Comment by zhouxiaoxing91** [comment]
https://www.zyh8.com/archives/135/openwrt%E5%AE%89%E8%A3%85%E9%85%8D%E7%BD%AEtailscale/
OpenWrt安装配置Tailscale

这个教程说的很好

**Comment by jjm2473** [comment]
istore早已经上架了tailscale
