### ISSUE TITLE
问题返馈4：安装X86_64 EFI固件下的软路由改变默认的Ipv4地址造成OpenClash插件下的Dashboard控制面板显示变空白页

### ISSUE THREAD

**Issue by lmwyl** [istoreos/istoreos#786]
安装X86_64 EFI固件下的软路由改变默认的Ipv4地址造成OpenClash插件下的Dashboard控制面板显示变空白页，但返回默认的Ipv4地址则正常出错机率十分高。

**Comment by jjm2473** [comment]
那也是openclash的问题，谁的软路由还不能改ip了？要么你就改完重启设备
