### ISSUE TITLE
DNS配置错误

### ISSUE THREAD

**Issue by chunkingzou** [istoreos/istoreos#788]
1.关于你要提交的问题
DNS配置错误

 2. 详细叙述

(1) 具体问题

手动配置和自动配置都有问题，可以使用QQ，无法打开网页

### (2) 路由器型号和固件版本

A：电犀牛R68S 21.02.3-2023051217

### (3) 详细日志和/或截图

A：
![@ BG2TQ8 DS~SR8 @CL7%3D](https://github.com/istoreos/istoreos/assets/113987631/4eebbc68-1fa6-4d35-8658-871e4598bc83)

![$ICQ0(}E8GDOAYH}W3POFID](https://github.com/istoreos/istoreos/assets/113987631/edc688b9-bb50-4b57-92f6-7a4312a684d4)

**Comment by chunkingzou** [comment]
PPPoe拨号也会出现这种错误

**Comment by chunkingzou** [comment]
> 解决方法是DNS配置改手动设置成第一级路由器的网关IP或网络营运商的网关IP可以解决的。
依然不行
![屏幕截图 2023-05-25 232453](https://github.com/istoreos/istoreos/assets/113987631/0710496f-4275-4e0f-8b1d-877da752339f)

**Comment by chunkingzou** [comment]
这个是光猫桥接，上面一个软路由，istoreos接在软路由下面跑docker

**Comment by z104866** [comment]
我测试下来好像是adbyby_plus的问题...它一启动...就导致这个问题

**Comment by LAGOD777** [comment]
同样的问题，开启 hd，pw，就会 dns 错误，全部关闭就正常

**Comment by nobodysclown** [comment]
> 我测试下来好像是adbyby_plus的问题...它一启动...就导致这个问题

dnsfilter 也会导致这个问题

**Comment by Alex-Joe-Lee** [comment]
> 

这个问题如何解决的？我也遇到了相同的问题，掉电重启以后，dns就报错，目前的解决方案是手动修改/etc/resolv.conf，但是每次都修改会很烦

**Comment by ByZain** [comment]
同样的问题，开翻墙插件就会出现这种情况，境内网站无法访问但是境外网站访问正常。

**Comment by maoxiaomo** [comment]
同样的问题

**Comment by ByZain** [comment]
怀疑是lan口的dns和ss的dns都配置了，导致循环问答或者抢占之类的以至于国内无法上网。目前发现将lan口的DNS配置指向本身局域网地址(我的是192.168.31.x)，ss的dns正常配置(国外8.8.8.8国内阿里223.5.5.5，绕过大陆模式)，好像可以解决这个问题，已经一天过去了，感觉一切正常，等过两天再来追评。
----------------------------------------------------------------------------
妈的还是不行！

**Comment by msw0717** [comment]
这个有解决办法吗？我现在只能回退到060914那个版本

**Comment by grock304** [comment]
我也出现这个问题，最后在 iKuai 中的 DNS 设置里，关闭“强制客户端DNS代理”之后解决了。

不清楚原理，纯粹把 DNS 相关设置试了个遍试出来的。

**Comment by putianhui** [comment]
怎么解决啊？  我的j4125 安装istoreOS之后，wan拨号内网设备可以上网，但是istoreOS这个设备dns不能解析啊？  我手动改/etc/resolv.conf里面的dns服务器地址，可以上网了，但是过一段时间就又恢复原样了，web里面的接口dns我手动设置了114和253阿里云dns都不行

**Comment by samisme0818** [comment]
> 怎么解决啊？ 我的j4125 安装istoreOS之后，wan拨号内网设备可以上网，但是istoreOS这个设备dns不能解析啊？ 我手动改/etc/resolv.conf里面的dns服务器地址，可以上网了，但是过一段时间就又恢复原样了，web里面的接口dns我手动设置了114和253阿里云dns都不行

我的问题是安装了广告拦截插件，其中有dnsmasq组件，会干预系统的dns配置，禁用就好了。也是找了很久的问题。

**Comment by jjm2473** [comment]
@putianhui 可能你的运营商分配的dns有问题，那就手动填写dns。/etc/resolv.conf是自动生成的文件，你修改了也会被程序覆盖。

**Comment by jjm2473** [comment]
@chunkingzou 你确定上一级路由器有提供DNS服务？也就是192.168.10.1有DNS服务？有没有试过其他公共DNS，例如114.114.114.114，或者223.5.5.5？

**Comment by auflute** [comment]
在防火墙的自定义规则里加上：
iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53

**Comment by jjm2473** [comment]
@auflute 你的方案也行可以解决内网dns错误的问题，但是路由器本身的dns问题还是一样。而且后台DHCP/DNS页面本身就提供了dns劫持开关，不需要自己写防火墙规则。

**Comment by bingoup886** [comment]
昨晚遇到同样的问题，但试了试发现是科学工具的问题，bypass没问题，ssrp有问题

**Comment by ZephyrLeeX** [comment]
@bingoup886 passwall2 也有同样的问题

**Comment by QuantumLeap-us** [comment]
j4125 更新了 passwall  自动的dnsmasq 引起的冲突怎么解决啊

**Comment by wrb233** [comment]
> 我测试下来好像是adbyby_plus的问题...它一启动...就导致这个问题

谢谢

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2908/1

**Comment by dahuangshushu** [comment]
tailscale插件也可能导致此问题，cat /etc/resolv.conf 查看文件是否被插件覆写
