### ISSUE TITLE
请问istoreos的软件源什么可以提供IPsec插件，我看见网友从去年7月份提出需求了，你们也承诺会提供，但是截至今天也没有，而且系统又不提供第三方软件源的添加

### ISSUE THREAD

**Issue by swingpon** [istoreos/istoreos#793]
请问istoreos的软件源什么可以提供IPsec插件，我看见网友从去年7月份提出需求了，你们也承诺会提供，但是截至今天也没有，而且系统又不提供第三方软件源的添加

**Comment by jjm2473** [comment]
openwrt官方就有啊 https://openwrt.org/docs/guide-user/services/vpn/strongswan/basics

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2904/1
