### ISSUE TITLE
NFS/挂载网络共享 SMB 挂着爱快SAMBAF服务不成功、是不支持linux吗

### ISSUE THREAD

**Issue by mj520** [istoreos/istoreos#795]
爱快虚拟机 安装 istoreos
挂载 CIFS/SMB （Windows 网络共享）、挂载windows和爱快nas
![image](https://github.com/istoreos/istoreos/assets/6768732/f2a27407-fa89-4e2d-bca2-e6fcde3ebf42)
只挂载windows成功
![image](https://github.com/istoreos/istoreos/assets/6768732/ddfa6be2-b64e-4dc1-807b-643c2f76b587)
爱快samba
![image](https://github.com/istoreos/istoreos/assets/6768732/00e5fe53-bbf6-4204-afcd-64f7ee1e16e0)
windows 挂载爱快 成功
![image](https://github.com/istoreos/istoreos/assets/6768732/05819069-654a-4b05-b140-25425dbfc6c2)
 挂着目录下为空
![image](https://github.com/istoreos/istoreos/assets/6768732/13ddb660-5dcd-42fc-82b3-ab76621bf707)
 是不支持linux吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2903/1
