### ISSUE TITLE
PPPOE拨号提示错误,尝试连接失败

### ISSUE THREAD

**Issue by YuasKD** [istoreos/istoreos#797]
## 1.关于你要提交的问题
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue
## 2. 详细叙述
在 ESXI8虚拟机下拨号失败
### (1) 具体问题
A：在PPPOE时提示错误,尝试连接失败

### (2) 路由器型号和固件版本

A：畅网微控 N5105 i226网卡 固件版本 istoreos-21.02.3-2023051913-x86-64-squashfs-combined-efi

### (3) 详细日志和/或截图

A：
![Snipaste_2023-05-23_19-35-52](https://github.com/istoreos/istoreos/assets/39578430/649a67a9-12ac-410e-81ae-cd2400f7319a)

**Comment by jjm2473** [comment]
看系统日志，一般都会告诉你为什么失败

**Comment by YuasKD** [comment]
感谢解答,我在日志里发现支持的网络设备为e1000e,将虚拟化改为此类型可正常拨号上网

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2901/1
