### ISSUE TITLE
网络存储-挂载网络共享-挂载 CIFS/SMB问题

### ISSUE THREAD

**Issue by My-By** [istoreos/istoreos#798]
X86设备，挂载了网络存储一应用就好，设备重启就不自动挂载，linkease挂载网络存储做同步，每次软路由重启就断掉，很无奈。旁路由模式，挺早几个版本还好好的，有大佬知道怎么整吗，或者能不能整一个定时自动挂载之类的功能。

**Comment by My-By** [comment]
抱歉，原来是我网卡带不动，搞了链路聚合以后就可以了，尴尬。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2900/1
