### ISSUE TITLE
/storage/centaurs  此进程是什么？重启一段时间后占用大量内存？

### ISSUE THREAD

**Issue by daoshui** [istoreos/istoreos#799]
请问/storage/centaurs  此进程是什么？重启一段时间后占用大量内存？直到系统内存使用量达到100%  
![WeChat0ace1d43cf64a76bccf2e236d6c5c76d](https://github.com/istoreos/istoreos/assets/87849581/e6f72ad4-3eb0-4f52-a441-2a642db8afc6)

**Comment by My-By** [comment]
好像是QB下载文件导致的，不太确定，有点面熟。

**Comment by daoshui** [comment]
> 

我没有安装和使用qb

**Comment by sqpool** [comment]
有安装网心云吗

**Comment by jjm2473** [comment]
看路径估计是网心云，你看看系统里面有没有这个文件

**Comment by daoshui** [comment]
you安装网心云，以前都没这种情况，就是最近这一两周出现的

**Comment by jjm2473** [comment]
网心云的业务是有可能自动调整的，调整业务以后出现负载变化很正常

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2899/1
