### ISSUE TITLE
使用UU游戏加速器点击启动还是提示没有运行！

### ISSUE THREAD

**Issue by sjmyx** [istoreos/istoreos#80]
系统固件是最新版本，安装后无法运行UU游戏加速器
<img width="1119" alt="微信截图_20220428023953" src="https://user-images.githubusercontent.com/30992289/165596925-1550e801-179b-4977-bbb7-f611e4371592.png">
。

**Comment by jannson** [comment]
收到，感谢反馈。最近还忙着搞沙箱模式，跟升级插件不丢的事情。估计晚些修复。

**Comment by zhanqiweiwu** [comment]
我也是一样情况

**Comment by ha7rock** [comment]
请问这个插件的修复是否排上了日程呢？感谢！

**Comment by carryhcc** [comment]
请问下何时修复

**Comment by carryhcc** [comment]
附上 临时解决办法 https://router.uu.163.com/app/html/online/baike_share.html?baike_id=5f963c9304c215e129ca40e8

**Comment by jjm2473** [comment]
最近测试没发现这个问题，可能已经解决了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3736/1
