### ISSUE TITLE
 iStoreOS 21.02.3 22端口默认开启

### ISSUE THREAD

**Issue by YuasKD** [istoreos/istoreos#803]
一个建议,在ssh访问那里将端口选项默认为lan,当前默认为空,这会导致22端口被暴露到公网,对于新手来说,很危险.
![Snipaste_2023-05-26_21-39-40](https://github.com/istoreos/istoreos/assets/39578430/38c96c55-0e5d-4026-a934-12b83c7849fc)

**Comment by jjm2473** [comment]
如果你拨号的话，防火墙会自动禁止wan口访问，不只是22端口，是所有端口。

**Comment by jjm2473** [comment]
参考 https://github.com/istoreos/istoreos/discussions/662

**Comment by YuasKD** [comment]
我在机器上做了个测试当不指定端口时,我使用公网能ssh进来,而指定监听lan口使用公网无法ssh
![Snipaste_2023-05-27_20-59-08](https://github.com/istoreos/istoreos/assets/39578430/280c133a-5750-4bf2-9499-a4dc122c820b)
![Snipaste_2023-05-27_20-58-37](https://github.com/istoreos/istoreos/assets/39578430/f3188d08-fd6e-4954-aa98-62040cf2d6b4)

**Comment by jjm2473** [comment]
你的网络是拨号还是dhcp的？还有你在测试的时候是在内网还是外网，内网测试的时候就算使用外网ip也不算外网流量。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2896/1
