### ISSUE TITLE
局域网获取到ipv6后过段时间ipv6不可用

### ISSUE THREAD

**Issue by yh317** [istoreos/istoreos#806]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：局域网获取到ipv6地址后过一段时间（半小时左右），ipv6就不可用，无法访问纯ipv6域名。配置方式为无状态地址SLAAC，未开启DHCPv6（开DHCPv6一样有此bug）

### (2) 路由器型号和固件版本

A：FriendlyElec NanoPi R4S
       iStoreOS 21.02.3 2023051913

### (3) 详细日志和/或截图

A：暂无

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2893/1
