### ISSUE TITLE
应用过滤上传新的特征库，上传报错

### ISSUE THREAD

**Issue by Ardin963** [istoreos/istoreos#807]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
应用过滤上传新的特征库，上传报错，应用过滤不更新特征库，但是在系统-文件传输，有上传记录
### (1) 具体问题
/usr/lib/lua/luci/model/cbi/appfilter/appfilter.lua:205: attempt to concatenate local 'lang' (a boolean value)
stack traceback:
	/usr/lib/lua/luci/model/cbi/appfilter/appfilter.lua:205: in function 'callback'
	/usr/lib/lua/luci/http.lua:108: in function </usr/lib/lua/luci/http.lua:90>
	(tail call): ?
	/usr/lib/lua/luci/model/cbi/appfilter/appfilter.lua:182: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1362: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1030: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>
A：

### (2) 路由器型号和固件版本
H68K mini，
iStoreOS 21.02.3 2023052618
A：

### (3) 详细日志和/或截图
/usr/lib/lua/luci/model/cbi/appfilter/appfilter.lua:205: attempt to concatenate local 'lang' (a boolean value)
stack traceback:
	/usr/lib/lua/luci/model/cbi/appfilter/appfilter.lua:205: in function 'callback'
	/usr/lib/lua/luci/http.lua:108: in function </usr/lib/lua/luci/http.lua:90>
	(tail call): ?
	/usr/lib/lua/luci/model/cbi/appfilter/appfilter.lua:182: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1362: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1030: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>
A：

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2892/1
