### ISSUE TITLE
应用过滤手动上传特征库之后，选择用户中的终端设备不显示

### ISSUE THREAD

**Issue by Ardin963** [istoreos/istoreos#808]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
上传特征库无法上传之后，手动上传了特征库，但是上传之后设备一个都没有了
### (1) 具体问题

A：

### (2) 路由器型号和固件版本
H68K mini，
iStoreOS 21.02.3 2023052618
A：

### (3) 详细日志和/或截图
![image](https://github.com/istoreos/istoreos/assets/59965293/32d2e328-51cf-46fd-8524-29675f3b8bee)

A：

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2891/1
