### ISSUE TITLE
docker迁移问题

### ISSUE THREAD

**Issue by qzydustin** [istoreos/istoreos#813]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：ESXi下的iStoreOS，原来的2g硬盘不够了，我添加了一块虚拟硬盘5g，但是在docker迁移助手中一直显示“检测到您还没有挂载外置硬盘”。

我手动把原docker文件夹mv过去了，然后在高级设置中改了新的位置/mnt/sataxxx/docker，然后能正常使用。还需要做什么吗？

### (2) 路由器型号和固件版本

A：[Powered by LuCI istoreos-21.02 branch (git-23.088.34636-f8cc111)](https://github.com/openwrt/luci) / [ArgonTheme v2.2.10.8](https://github.com/jerrykuku/luci-theme-argon) / iStoreOS 21.02.3 2023052616

**Comment by jjm2473** [comment]
docker迁移会忽略小于8GB的硬盘分区

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2886/1
