### ISSUE TITLE
是否能出一个支持QEMU ARM virt 的版本

### ISSUE THREAD

**Issue by buleyy** [istoreos/istoreos#814]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：是否能出一个支持QEMU ARM virt 的版本

### (2) 路由器型号和固件版本

A：QEMU ARM virt

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
看了下armvirt的镜像格式（ https://downloads.openwrt.org/releases/22.03.5/targets/armvirt/64/ ），并不是磁盘镜像，而是分开了内核和rootfs，这样就没办法支持独立的overlay分区了，istoreos需要一个独立的overlay分区，所以没法支持

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2885/1
