### ISSUE TITLE
关于 Home Assistant 的一些分享和建议

### ISSUE THREAD

**Issue by tazyong** [istoreos/istoreos#815]
# 安装 supervisor 版本参考这个 https://github.com/istoreos/istoreos/issues/815#issuecomment-1953685442

-----

# ~~此方法已经无法安装 Supervised 2023.04.1 以后的版本了，已经安装旧版的也无法升级成功。因为在此之后的版本，官方改了挂载模式，而 openwrt 似乎并不支持。~~
我对这块不太熟悉，也没有时间精力去解决，已改用 esxi 虚拟机安装 hassos 了。

**致命问题：**

```bash
stderr: [31m23-06-14 04:10:03 ERROR (SyncWorker_5) [supervisor.docker.manager] Can't create container from homeassistant: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=homeassistant: Bad Request ("invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/opt/docker", bind mount source: "/opt/docker/hassio/share", propagation: "slave"")[0m
```

有了解的同学如果能解决，希望能分享一下。

---

**Home Assistant 是一个跨品牌的智能家居管理平台，以下所有描述简称为 HA。**

先说说HA的四种版本：

|| OS | Container | Core | Supervised |
| -- | -- | -- | -- | -- |
Automations（自动化） | ✅ | ✅ | ✅ | ✅ |
Dashboards（仪表盘） | ✅ | ✅ | ✅ | ✅ |
Integrations（集成） | ✅ | ✅ | ✅ | ✅ |
Blueprints（设计图） | ✅ | ✅ | ✅ | ✅ |
Uses container（使用容器） | ✅ | ✅ | ❌ | ✅ |
Supervisor（监管程序） | ✅ | ❌ | ❌ | ✅ |
Add-ons（加载项） | ✅ | ❌ | ❌ | ✅ |
Backups（备份） | ✅ | ✅1 | ✅1 | ✅ |
Managed Restore（管理还原） | ✅ | ❌2 | ❌2 | ✅ |
Managed OS（管理操作系统） | ✅ | ❌ | ❌ | ❌ |

更多请参考官网安装地址：https://www.home-assistant.io/installation/

## 版本说明

- HA OS 也被称为 `hassos`，它是操作系统，无法在 iStore OS 再安装一个操作系统
- HA Container 是基础的 Docker 部署方式，目前 iStore 商店里安装的就是这个，对极客玩家来说，属于阉割版本
- HA Core 就是一个 Python 程序，跟 HA Container 唯一的差别就是要自己配环境
- HA Supervised 也被称为 `hassio`，可以在现有操作系统上安装的完整版本，除了管理操作系统，它拥有 HA OS 的所有功能

## 关键部分

- 缺少 Supervisor 就无法在界面管理和更新 HA，升级全靠它
- 缺少 Add-ons 就无法在界面愉快地安装第三方软件，比如：Node-RED、Mosquitto broker、ESPHome
- 缺少 Managed Restore 就无法还原 HA，还原 HA 和还原备份数据不是一回事

## 安装 HA Supervised

**安装前应先移除在 iStore 中安装的 HA！**
进入 `iStore 首页 -> 终端`、`服务 -> 终端`、`ssh 客户端` 任意一处执行以下命令：

```
docker run -d \
  --name hassio_supervisor \
  --privileged \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/run/dbus:/var/run/dbus \
  -v /opt/docker/hassio:/data \
  -e SUPERVISOR_SHARE="/opt/docker/hassio" \
  -e SUPERVISOR_NAME="hassio_supervisor" \
  -e HOMEASSISTANT_REPOSITORY="homeassistant/qemux86-64-homeassistant" \
  --restart unless-stopped \
  homeassistant/amd64-hassio-supervisor:2023.04.1
```

理论上所有有 Docker 环境的机器都可以用以上方法安装。
_注意：命令行每行末尾都带了 `\`，这是 Linux 命令行的分行连接符，如果终端不支持，可以去掉改成单行命令。_

### 参数说明

- `--name hassio_supervisor`：将当前容器名称定义为 hassio_supervisor
- `--privileged`：允许访问主机上的所有设备和资源
- `-v /var/run/docker.sock:/var/run/docker.sock`：将 Docker 守护进程的 UNIX 套接字挂载到容器的 /var/run/docker.sock 目录中，以便 Supervisor 管理程序可以通过 Docker API 来管理其他容器
- `-v /var/run/dbus:/var/run/dbus`：将主机上的 D-Bus 系统消息总线挂载到容器中，以便 Supervisor 管理程序可以与系统服务通信
- `-v /opt/docker/hassio:/data`：将宿主机的 /opt/docker/hassio 目录挂载到容器内部目录 /data 中，方便在外部维护 HA 数据。如果修改了 docker 根目录，请修改为对应的路径，如：docker 根目录修改为 /mnt/sata1-4/docker 以后，对应的参数设置为 -v /mnt/sata1-4/docker/hassio:/data
- `-e SUPERVISOR_SHARE="/opt/docker/hassio"`：指定 Supervisor 的数据共享目录路径为 /opt/docker/hassio，这里的路径应和上面的参数的路径保持一致
- `-e SUPERVISOR_NAME="hassio_supervisor"`：指定 Supervisor 容器的名称为 hassio_supervisor
- `-e HOMEASSISTANT_REPOSITORY="homeassistant/qemux86-64-homeassistant"`：指定 Supervisor 要使用的 HA 镜像
- `--restart unless-stopped` 当容器异常退出或主机重启后自动重启
- `homeassistant/amd64-hassio-supervisor:2023.04.1`：Supervisor 镜像，版本为 2023.04.1，去掉版本号默认会安装最新版本的，但 Supervised 的版本管理没有将开发版和正式版本分开，最新的往往是开发版的，开发版对挂载目录和挂载模式有所调整，安装过程会遇到错误，需要自行解决，这里不推荐！

### 常用镜像

请自行替换命令行里的镜像安装，更多官方镜像请移步 [这里](https://hub.docker.com/u/homeassistant)。

HA 镜像
| 名称 | 描述 |
| -- | -- |
| [homeassistant/qemux86-64-homeassistant](https://hub.docker.com/r/homeassistant/qemux86-64-homeassistant) | 适用于 x86 64位架构并支持 QEMU 虚拟化的设备 |
| [homeassistant/generic-x86-64-homeassistant](https://hub.docker.com/r/homeassistant/generic-x86-64-homeassistant) | 适用于通用 x86 64位架构的设备 |
| [homeassistant/amd64-homeassistant](https://hub.docker.com/r/homeassistant/amd64-homeassistant) | 适用于 x86 64位架构的设备 |
| [homeassistant/qemux86-homeassistant](https://hub.docker.com/r/homeassistant/qemux86-homeassistant) | 适用于 x86 32位架构并支持 QEMU 虚拟化的设备 |
| [homeassistant/i386-homeassistant](https://hub.docker.com/r/homeassistant/i386-homeassistant) | 适用于 x86 32位架构的设备 |
| [homeassistant/qemuarm-64-homeassistant](https://hub.docker.com/r/homeassistant/qemuarm-64-homeassistant) | 适用于 ARM 64位架构并支持 QEMU 虚拟化的设备 |
| [homeassistant/aarch64-homeassistant](https://hub.docker.com/r/homeassistant/aarch64-homeassistant) | 适用于 ARMv8 64位架构的设备 |
| [homeassistant/armv7-homeassistant](https://hub.docker.com/r/homeassistant/armv7-homeassistant) | 适用于 ARMv7 架构的设备 |
| [homeassistant/armhf-homeassistant](https://hub.docker.com/r/homeassistant/armhf-homeassistant) | 适用于 ARMv6 或更高版本的硬浮点 (hard-float) ARM 架构的设备 |
| [homeassistant/raspberrypi4-64-homeassistant](https://hub.docker.com/r/homeassistant/raspberrypi4-64-homeassistant) | 适用于树莓派 4 64位 |
| [homeassistant/raspberrypi4-homeassistant](https://hub.docker.com/r/homeassistant/raspberrypi4-homeassistant) | 适用于树莓派 4 32位 |
| [homeassistant/raspberrypi3-64-homeassistant](https://hub.docker.com/r/homeassistant/raspberrypi3-64-homeassistant) | 适用于树莓派 3 64位 |
| [homeassistant/raspberrypi3-homeassistant](https://hub.docker.com/r/homeassistant/raspberrypi3-homeassistant) | 适用于树莓派 3 32位 |
| [homeassistant/raspberrypi2-homeassistant](https://hub.docker.com/r/homeassistant/raspberrypi2-homeassistant) | 适用于树莓派 2 |
| [homeassistant/raspberrypi-homeassistant](https://hub.docker.com/r/homeassistant/raspberrypi-homeassistant) | 适用于树莓派 |

Supervisor 镜像
| 名称 | 描述 |
| -- | -- |
| [homeassistant/amd64-hassio-supervisor](https://hub.docker.com/r/homeassistant/amd64-hassio-supervisor) | 适用于 x86 64位架构的计算机，如大多数台式电脑和服务器 |
| [homeassistant/i386-hassio-supervisor](https://hub.docker.com/r/homeassistant/i386-hassio-supervisor) | 适用于 x86 32位架构的计算机，如旧版台式电脑和服务器 |
| [homeassistant/aarch64-hassio-supervisor](https://hub.docker.com/r/homeassistant/aarch64-hassio-supervisor) | 适用于 ARMv8 64位架构（也称为AArch64）的计算机，如树莓派4的64位操作系统等 |
| [homeassistant/armv7-hassio-supervisor](https://hub.docker.com/r/homeassistant/armv7-hassio-supervisor) | 适用于 ARMv7 架构的计算机，如树莓派2、3和4等 |
| [homeassistant/armhf-hassio-supervisor](https://hub.docker.com/r/homeassistant/armhf-hassio-supervisor) | 适用于 ARMv6 或更高版本的硬浮点（hard-float）ARM架构的计算机 |

## 关于 HACS 商店

无论你现在在使用哪个版本，都可以安装 HACS 商店，目测只有开发版本（即含 `dev` 名称的镜像）才默认安装了。
进入 `配置 -> 设备与服务 -> 添加集成`，搜索 HACS，如果出现了 HACS 商店，就表示默认安装了，直接集成即可。如果找不到 HACS 商店，那就需要自己手动安装了，安装方法：

1. 进入 `Docker -> 容器 `，选择 HA 容器的编辑
2. 选择 `控制台`，选择 /bin/sh ，点击连接进入 /config 目录
3. 输入下面命令，安装 HACS 商店
    ```
    wget -O - https://hacs.vip/get | HUB_DOMAIN=ghproxy.com/github.com bash -
    ```
    上面安装的是 [HACS 极速版](https://github.com/hacs-china/integration)，因为国内网络环境原因，特别推荐！虽然比原版小了几个版本，但实测下来并不影响使用。商店虽旧，但安装的集成都是最新的，因为用的是国内的源，速度和稳定性都很好。
    觉得自己网络可以的（反正我的网络不行，即使出国也经常安装不成功），或者国外的玩家，可以安装 [原版 HACS 商店](https://hacs.xyz/docs/setup/download)
    ```
    wget -O - https://get.hacs.xyz | bash -
    ```
4. 安装成功后，进入 `配置 -> 设备与服务 -> 添加集成`，搜索 HACS 集成

## 建议

**最后希望官方能集成 HA Supervised 到 iStore 商店**

![image](https://github.com/istoreos/istoreos/assets/24738011/49dd6de9-ad6d-43c0-8876-77132169c419)
![image](https://github.com/istoreos/istoreos/assets/24738011/6cf6b35c-dd5e-49af-ad23-a1e5745a8c2a)
![image](https://github.com/istoreos/istoreos/assets/24738011/d613c5fe-82cc-4cd9-b255-07f618b33a94)

**Comment by caideone** [comment]
why？
stderr: [32m23-06-05 11:59:41 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
stderr: [32m23-06-05 11:59:41 INFO (MainThread) [supervisor.jobs] 'NetworkManager.load' blocked from execution, host Network Manager not available[0m
stderr: [32m23-06-05 11:59:41 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: set()[0m
stderr: [33m23-06-05 11:59:41 WARNING (MainThread) [supervisor.host.apparmor] AppArmor is not enabled on host[0m
stderr: [32m23-06-05 20:59:41 INFO (MainThread) [supervisor.docker.monitor] Started docker events monitor[0m
stderr: [32m23-06-05 20:59:41 INFO (SyncWorker_0) [supervisor.docker.interface] No version found for ghcr.io/home-assistant/aarch64-hassio-cli[0m
stderr: [32m23-06-05 20:59:41 INFO (MainThread) [supervisor.plugins.base] No cli plugin Docker image ghcr.io/home-assistant/aarch64-hassio-cli found.[0m
stderr: [32m23-06-05 20:59:41 INFO (MainThread) [supervisor.plugins.cli] Running setup for CLI plugin[0m
stderr: [32m23-06-05 20:59:41 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
stderr: [33m23-06-05 20:59:41 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'[0m
stderr: [33m23-06-05 20:59:41 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m
stderr: [32m23-06-05 21:00:11 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
stderr: [33m23-06-05 21:00:12 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'[0m
stderr: [33m23-06-05 21:00:12 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m
stderr: [32m23-06-05 21:00:42 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
stderr: [33m23-06-05 21:00:42 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'[0m
stderr: [33m23-06-05 21:00:42 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m
stderr: [32m23-06-05 21:01:12 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
stderr: [33m23-06-05 21:01:12 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'[0m
stderr: [33m23-06-05 21:01:12 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m
stderr: [32m23-06-05 21:01:42 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
stderr: [33m23-06-05 21:01:42 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'[0m
stderr: [33m23-06-05 21:01:42 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m

**Comment by tazyong** [comment]
@caideone 
从日志上看是网络问题，`aarch64-hassio-cli` 镜像没有下载成功，以后如果再遇到问题，自己先翻译看看能不能解决。
还有，不要安装带 `dev` 标识的开发版，`latest` 最新版绝大多数都是开发版本，遇到问题你解决不了！

supervisor 镜像版本列表：https://github.com/home-assistant/supervisor/pkgs/container/aarch64-hassio-supervisor
HA 所有套件稳定版本配置：https://version.home-assistant.io/stable.json

当前 supervisor 的稳定版本是 2023.04.1，没必要执着于最新版本！
HA 的 web 界面有稳定版本会提示更新的，在界面更新不会错。

```diff
stderr: [32m23-06-05 11:59:41 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
- stderr: [32m23-06-05 11:59:41 INFO (MainThread) [supervisor.jobs] 'NetworkManager.load' blocked from execution, host Network Manager not available[0m
+ stderr: [32m23-06-05 11:59:41 INFO (MainThread) [supervisor.jobs] “NetworkManager.load”被阻止执行，主机网络管理器不可用[0m
stderr: [32m23-06-05 11:59:41 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: set()[0m
stderr: [33m23-06-05 11:59:41 WARNING (MainThread) [supervisor.host.apparmor] AppArmor is not enabled on host[0m
stderr: [32m23-06-05 20:59:41 INFO (MainThread) [supervisor.docker.monitor] Started docker events monitor[0m
- stderr: [32m23-06-05 20:59:41 INFO (SyncWorker_0) [supervisor.docker.interface] No version found for ghcr.io/home-assistant/aarch64-hassio-cli[0m
+ stderr: [32m23-06-05 20:59:41 INFO (SyncWorker_0) [supervisor.docker.interface] 未找到 ghcr.io/home-assistant/aarch64-hassio-cli 的版本[0m
stderr: [32m23-06-05 20:59:41 INFO (MainThread) [supervisor.plugins.base] No cli plugin Docker image ghcr.io/home-assistant/aarch64-hassio-cli found.[0m
stderr: [32m23-06-05 20:59:41 INFO (MainThread) [supervisor.plugins.cli] Running setup for CLI plugin[0m
stderr: [32m23-06-05 20:59:41 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
stderr: [33m23-06-05 20:59:41 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'[0m
stderr: [33m23-06-05 20:59:41 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m
stderr: [32m23-06-05 21:00:11 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
stderr: [33m23-06-05 21:00:12 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'[0m
stderr: [33m23-06-05 21:00:12 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m
stderr: [32m23-06-05 21:00:42 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
stderr: [33m23-06-05 21:00:42 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'[0m
stderr: [33m23-06-05 21:00:42 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m
stderr: [32m23-06-05 21:01:12 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
stderr: [33m23-06-05 21:01:12 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'[0m
stderr: [33m23-06-05 21:01:12 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m
stderr: [32m23-06-05 21:01:42 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
stderr: [33m23-06-05 21:01:42 WARNING (MainThread) [supervisor.updater] Can't process version data: 'aarch64'[0m
stderr: [33m23-06-05 21:01:42 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m
```

**Comment by dannnney** [comment]
@tazyong 请问一下根据你的 docker 跑起来， ha 的网页端口是多少呢？我看你这里并没有设置端口映射

**Comment by tazyong** [comment]
> @tazyong 请问一下根据你的 docker 跑起来， ha 的网页端口是多少呢？我看你这里并没有设置端口映射

@dannnney ha端口是8123，不过这个装不了了，实在抱歉！

**Comment by ballack311** [comment]
请问现在2023.04.1这个版本业不能装了吗？我用docker装了以后日志里还是有这个报错....
23-10-11 13:17:48 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection
23-10-11 13:17:48 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec

**Comment by firegl99** [comment]
docker的homeassistant用bridge网络没问题吗？和智能设备都不在一个子网内

**Comment by ballack311** [comment]
您好  邮件已收到  谢谢

**Comment by docker-master** [comment]
我在闲鱼花了60块钱，装了个开发版，现在坏了，打不开网页，我去，先试试回退这个版本，反正有文件扒下来备份一下

**Comment by ballack311** [comment]
您好  邮件已收到  谢谢

**Comment by zanjie1999** [comment]
怎么不能装了？我现在2023.08.1在openwrt跑的好好的，他虽然明示不支持但是工作一切正常，并且还是一路升级上来的
要不来看看我的文章？
https://zyyme.com/docker-home-assistant-hassio-supervisor.html

**Comment by jjm2473** [comment]
Home Assistant Supervisor 部署命令：

## arm64
```bash
docker run -d \
  --name hassio_supervisor \
  --privileged \
  --restart unless-stopped \
  --dns=172.17.0.1 \
  -e TZ=Asia/Taipei \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/run/dbus:/var/run/dbus \
  -v /run/udev:/run/udev \
  -v /mnt/data/hassio:/data \
  -e SUPERVISOR_SHARE="/mnt/data/hassio" \
  -e SUPERVISOR_NAME="hassio_supervisor" \
  -e HOMEASSISTANT_REPOSITORY="homeassistant/qemuarm-64-homeassistant" \
  ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.01.1

```

## x86_64
```bash
docker run -d \
  --name hassio_supervisor \
  --privileged \
  --restart unless-stopped \
  --dns=172.17.0.1 \
  -e TZ=Asia/Taipei \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/run/dbus:/var/run/dbus \
  -v /run/udev:/run/udev \
  -v /mnt/data/hassio:/data \
  -e SUPERVISOR_SHARE="/mnt/data/hassio" \
  -e SUPERVISOR_NAME="hassio_supervisor" \
  -e HOMEASSISTANT_REPOSITORY="homeassistant/qemux86-64-homeassistant" \
  ghcr.io/home-assistant/amd64-hassio-supervisor:2024.01.1

```

把命令里面的**两个**`/mnt/data/hassio`改成自己希望在不同容器共享数据的路径就行了，注意，可能只有`/mnt/`的子目录才支持


已知问题：
1. observer的检查报告会误报异常，可以忽略
2. supervisor自我更新会失败，如果要更新，停止所有容器，删除hassio_supervisor容器，然后重新部署

**Comment by ballack311** [comment]
您好  邮件已收到  谢谢

**Comment by Vip4pt** [comment]
<img width="1218" alt="image" src="https://github.com/istoreos/istoreos/assets/21324892/7b6ff572-18c5-4055-95ec-85e8f7f15dd0">
装完了，打开了然后就这样的- -

**Comment by ballack311** [comment]
您好  邮件已收到  谢谢

**Comment by jjm2473** [comment]
不用看observer的检查报告，反正能正常运行，目前发现的问题也就supervisor自我更新会失败。

<img width="1329" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/531e18ce-2b67-4edb-aab6-fd0310924a5a">

<img width="1012" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/4747eab7-0955-464f-8d7d-3ce1496f77ad">

**Comment by jjm2473** [comment]
@Vip4pt 你有没有玩过HA啊，端口是8123

**Comment by cyczq11** [comment]
后续有解决这个问题吗？   想把hassos迁移过来 N1盒子上使用

**Comment by ballack311** [comment]
您好  邮件已收到  谢谢

**Comment by jjm2473** [comment]
@cyczq11 参考这里的命令 https://github.com/istoreos/istoreos/issues/815#issuecomment-1953685442

**Comment by chuc2rk** [comment]
> 不用看observer的检查报告，反正能正常运行，目前发现的问题也就supervisor自我更新会失败。

I have the same problem, have you fixed it? Thanks!

**Comment by ballack311** [comment]
您好  邮件已收到  谢谢

**Comment by chuc2rk** [comment]
here my error, please help me.

> s6-rc: info: service s6rc-oneshot-runner: starting
stderr: s6-rc: info: service s6rc-oneshot-runner successfully started
stderr: s6-rc: info: service fix-attrs: starting
stderr: s6-rc: info: service fix-attrs successfully started
stderr: s6-rc: info: service legacy-cont-init: starting
stderr: cont-init: info: running /etc/cont-init.d/udev.sh
stderr: [15:37:59] INFO: [32mSetup udev backend inside container[0m
stderr: [15:37:59] INFO: [32mUpdate udev information[0m
stderr: cont-init: info: /etc/cont-init.d/udev.sh exited 0
stderr: s6-rc: info: service legacy-cont-init successfully started
stderr: s6-rc: info: service legacy-services: starting
stderr: services-up: info: copying legacy longrun supervisor (no readiness notification)
stderr: services-up: info: copying legacy longrun watchdog (no readiness notification)
stderr: [15:37:59] INFO: [32mStarting local supervisor watchdog...[0m
stderr: s6-rc: info: service legacy-services successfully started
stderr: [32m24-05-28 15:38:01 INFO (MainThread) [supervisor.bootstrap] Use the old homeassistant repository for machine extraction[0m
stderr: [32m24-05-28 15:38:01 INFO (MainThread) [__main__] Initializing Supervisor setup[0m
stderr: [33m24-05-28 15:38:01 WARNING (MainThread) [supervisor.bootstrap] Missing SUPERVISOR_MACHINE environment variable. Fallback to deprecated extraction![0m
stderr: [32m24-05-28 15:38:01 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: qemux86-64[0m
stderr: [32m24-05-28 15:38:01 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/amd64-hassio-supervisor with version 2023.04.1[0m
stderr: [32m24-05-28 15:38:01 INFO (SyncWorker_0) [supervisor.docker.supervisor] Connecting Supervisor to hassio-network[0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE[0m
stderr: [33m24-05-28 15:38:02 WARNING (MainThread) [supervisor.resolution.evaluations.docker_configuration] Docker storage driver vfs is not supported![0m
stderr: [33m24-05-28 15:38:02 WARNING (MainThread) [supervisor.resolution.evaluations.docker_configuration] Docker logging driver json-file is not supported![0m
stderr: [33m24-05-28 15:38:02 WARNING (MainThread) [supervisor.resolution.evaluations.base] The configuration of Docker is not supported (more-info: https://www.home-assistant.io/more-info/unsupported/docker_configuration)[0m
stderr: [33m24-05-28 15:38:02 WARNING (MainThread) [supervisor.resolution.evaluations.base] AppArmor is required for Home Assistant. (more-info: https://www.home-assistant.io/more-info/unsupported/apparmor)[0m
stderr: [33m24-05-28 15:38:02 WARNING (MainThread) [supervisor.resolution.evaluations.base] D-Bus is required for Home Assistant. (more-info: https://www.home-assistant.io/more-info/unsupported/dbus)[0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [__main__] Setting up Supervisor[0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2[0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor[0m
stderr: [31m24-05-28 15:38:02 ERROR (MainThread) [supervisor.dbus.manager] No D-Bus support on Host. Disabled any kind of host control![0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [supervisor.jobs] 'NetworkManager.load' blocked from execution, host Network Manager not available[0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: set()[0m
stderr: [33m24-05-28 15:38:02 WARNING (MainThread) [supervisor.host.apparmor] AppArmor is not enabled on host[0m
stderr: [33m24-05-28 15:38:02 WARNING (MainThread) [supervisor.utils.whoami] Can't fetch Whoami data: Cannot connect to host services.home-assistant.io:443 ssl:default [Network unreachable][0m
stderr: [33m24-05-28 15:38:02 WARNING (MainThread) [supervisor.core] Can't adjust Time/Date settings: Can't fetch Whoami data: Cannot connect to host services.home-assistant.io:443 ssl:default [Network unreachable][0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [supervisor.docker.monitor] Started docker events monitor[0m
stderr: [32m24-05-28 15:38:02 INFO (SyncWorker_0) [supervisor.docker.interface] No version found for ghcr.io/home-assistant/amd64-hassio-cli[0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [supervisor.plugins.base] No cli plugin Docker image ghcr.io/home-assistant/amd64-hassio-cli found.[0m
stderr: [32m24-05-28 15:38:02 INFO (MainThread) [supervisor.plugins.cli] Running setup for CLI plugin[0m
stderr: [33m24-05-28 15:38:02 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection[0m
stderr: [33m24-05-28 15:38:02 WARNING (MainThread) [supervisor.plugins.cli] Error on install cli plugin. Retry in 30sec[0m

**Comment by jjm2473** [comment]
@chuc2rk Do not use the online update of supervisor. Instead, write a script to stop all supervisor and hassio related containers, and then redeploy supervisor.

Supervisor's online update may have bugs and fail to update containers.

**Comment by chuc2rk** [comment]
> @chuc2rk Do not use the online update of supervisor. Instead, write a script to stop all supervisor and hassio related containers, and then redeploy supervisor.
> 
> Supervisor's online update may have bugs and fail to update containers.

Could you give me detail script, thank you so much!

**Comment by jjm2473** [comment]
@chuc2rk No, I just mentioned that you can use script.

**Comment by jjjyyyllll** [comment]
在尝试最新版 在arm64的小路由器上

**Comment by ballack311** [comment]
您好  邮件已收到  谢谢

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2884/1

**Comment by ballack311** [comment]
您好  邮件已收到  谢谢

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2884/20
