### ISSUE TITLE
重启报错

### ISSUE THREAD

**Issue by hjiayu** [istoreos/istoreos#816]
### (1) 具体问题

A：重启报错
### 
![0c0975062c863ab729c9678913ab6d4](https://github.com/istoreos/istoreos/assets/63991010/ae03dbef-1ca1-4e64-aef9-525fb49eb0a4)

### (2) 路由器型号和固件版本

A：J1900 最新版

### (3) 详细日志和/或截图

A：rooteiStoreOS:/#[ 75.467423][drm:wait_panel_status]*ERROR*PPSstatemismatch
#
/

**Comment by jjm2473** [comment]
然后会卡死吗？
