### ISSUE TITLE
r5c跑不满千兆

### ISSUE THREAD

**Issue by jian263994241** [istoreos/istoreos#819]
两台r5c 一台刷的istoreos  一台刷的骷髅头固件,   同环境下 istoreos 只能跑到 850mbps 左右 ,   骷髅头的 940mbps 满千兆.  
手上还有另一台 r66s 同款CPU, 刷了istoreos 也只能跑 800mbps左右

**Comment by jjm2473** [comment]
没有调优经验，你可以试试测试版的固件有没有改善

**Comment by GreenTeodoro839** [comment]
istoreos主要是他们自己的产品用，骷颅头的rockchip固件用了patch加上调度很激进

**Comment by jjm2473** [comment]
@GreenTeodoro839 倒也不是，目前我们就出过一款硬件。其他固件可能会超频什么的，具体没研究。

**Comment by jjm2473** [comment]
更新到最新版本固件，看看能不能跑满了，我用自建的pppoe起码可以跑到1.3G了

**Comment by jian263994241** [comment]
最新版已解决

**Comment by diave971** [comment]
> 更新到最新版本固件，看看能不能跑满了，我用自建的pppoe起码可以跑到1.3G了

貌似最新版本又出现了相关问题，内网测速只有八百多兆22.03.7 2024080210版本
![image](https://github.com/user-attachments/assets/1579f2b4-291c-4ea5-a62e-36a77f7785a3)

**Comment by jjm2473** [comment]
@diave971 你确定这不是通过wifi测试的？内网有线要么～100M，要么～1000M，要么～2.5G，怎么可能500M到800M。楼主提的问题是pppoe外网速度异常，内网再怎么样也不会有cpu调度瓶颈。

**Comment by GreenTeodoro839** [comment]
> @diave971 你确定这不是通过wifi测试的？内网有线要么～100M，要么～1000M，要么～2.5G，怎么可能500M到800M。楼主提的问题是pppoe外网速度异常，内网再怎么样也不会有cpu调度瓶颈。

你那是协商速度，而不是实际速度。实际速度和机器性能有关

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2882/1
