### ISSUE TITLE
插件能否在行为管理系统，包含应用过滤、网址过滤、端口过滤、上网审计等功能做一些优化？

### ISSUE THREAD

**Issue by lvzhimou** [istoreos/istoreos#821]
插件能否在行为管理系统，包含应用过滤、网址过滤、端口过滤、上网审计等功能做一些优化？比如FROS系统，相对该方面做的相对较好，能否以插件形式融入或者对自身应用作一些优化。虽然现有部分功能，但相对还不是很完善。谢谢！

**Comment by jjm2473** [comment]
要有人开发啊，现在“应用过滤”插件就是用FROS作者的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2880/1
