### ISSUE TITLE
最新版本，缺少kmod-nft-compat依赖，还请排查下

### ISSUE THREAD

**Issue by bcvb2001** [istoreos/istoreos#822]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
有类似的问题，但是去年的，现在又出现了

### (1) 具体问题

A：最先0526版本，安装PASSWALL时会提示缺少依赖kmod-nft-compa

### (2) 路由器型号和固件版本

A：r68s

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/17878275/8feaf387-34bd-410d-a2a1-7064015ecf9e)

**Comment by NanjolnoRing** [comment]
我R2S刷的最新版也是这个问题，还请大佬排查下

**Comment by jjm2473** [comment]
如果能安装过去，就忽略掉。或者使用istore那边的离线安装方式，可能会自动解决这些问题

**Comment by jjm2473** [comment]
不要使用最新版本，最新版本适配的openwrt也是最新的。安装之前版本就行了。如果不会自己编译，可以用网友编译好的 https://github.com/AUK9527/Are-u-ok/tree/main

**Comment by jjm2473** [comment]
https://github.com/istoreos/istoreos/issues/342
