### ISSUE TITLE
Unifi控制器端口映射错误

### ISSUE THREAD

**Issue by alex-cse** [istoreos/istoreos#825]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：istore 商店 Unifi控制器端口映射错误，
docker以host network安装后
<img width="873" alt="image" src="https://github.com/istoreos/istoreos/assets/35652782/1b044370-b493-40b6-bef4-bb02a7730441">
点击 打开unif control 指向的端口为8083，但是实际端口为8443，没有找到可以修改的地方

### (2) 路由器型号和固件版本

A：x86 iStoreOS 21.02.3 2023052616

**Comment by jjm2473** [comment]
难道镜像改了默认端口？

**Comment by jjm2473** [comment]
哦，是插件的脚本的判断有bug

**Comment by jjm2473** [comment]
修复了，更新下

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2878/1
