### ISSUE TITLE
quickstart首页终端按钮问题

### ISSUE THREAD

**Issue by bcseputetto** [istoreos/istoreos#826]
## 1.关于你要提交的问题

由于目前openwrt的ttyd不支持https重定向，所以希望quickstart首页的终端按钮能支持判断ttyd启用SSL；在首页页面中点击“终端”打开的新页面能加上http(s)://

[ttyd issues](https://github.com/tsl0922/ttyd/issues/972)

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

N/A

### (2) 路由器型号和固件版本

x86 Generic

### (3) 详细日志和/或截图
![ttyd_ssl](https://github.com/istoreos/istoreos/assets/29139573/17cd594f-c7aa-44ea-af9e-a57830a46a23)
![ttyd_ssl_2](https://github.com/istoreos/istoreos/assets/29139573/3a9d0b15-fe96-40e9-8cb7-e11b3064b853)
![ttyd_ssl_3](https://github.com/istoreos/istoreos/assets/29139573/017579f5-5e59-4e43-bd61-85da912feb51)
![ttyd_ssl_4](https://github.com/istoreos/istoreos/assets/29139573/7d67de75-115c-4b90-8790-10d0b4043fba)

**Comment by jjm2473** [comment]
支持了端口和ssl构造url，下个版本发布

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2877/1
