### ISSUE TITLE
挂载移动硬盘，上传文件会掉盘的问题

### ISSUE THREAD

**Issue by duojiaqi123** [istoreos/istoreos#827]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：通过固态硬盘盒外接固态硬盘，在上传文件时会掉盘和下载文件时也会掉盘并且cpu会到100%

### (2) 路由器型号和固件版本

A：r2s
iStoreOS 21.02.3 2023052616

### (3) 详细日志和/或截图

A：Sun Jun 11 19:49:27 2023 kern.info kernel: [  291.437101] usb 1-1: new high-speed USB device number 2 using ehci-platform
Sun Jun 11 19:49:27 2023 kern.info kernel: [  291.640291] usb-storage 1-1:1.0: USB Mass Storage device detected
Sun Jun 11 19:49:27 2023 kern.info kernel: [  291.641325] scsi host0: usb-storage 1-1:1.0
Sun Jun 11 19:49:28 2023 kern.notice kernel: [  292.675122] scsi 0:0:0:0: Direct-Access     HIKSEMI  MD202            1.00 PQ: 0 ANSI: 6
Sun Jun 11 19:49:28 2023 kern.notice kernel: [  292.676018] sd 0:0:0:0: Attached scsi generic sg0 type 0
Sun Jun 11 19:49:28 2023 kern.notice kernel: [  292.677862] sd 0:0:0:0: [sda] 4000797360 512-byte logical blocks: (2.05 TB/1.86 TiB)
Sun Jun 11 19:49:28 2023 kern.notice kernel: [  292.678671] sd 0:0:0:0: [sda] Write Protect is off
Sun Jun 11 19:49:28 2023 kern.debug kernel: [  292.678683] sd 0:0:0:0: [sda] Mode Sense: 37 00 00 08
Sun Jun 11 19:49:28 2023 kern.notice kernel: [  292.679416] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
Sun Jun 11 19:49:28 2023 kern.info kernel: [  292.721509]  sda: sda1 sda2
Sun Jun 11 19:49:28 2023 kern.notice kernel: [  292.726112] sd 0:0:0:0: [sda] Attached SCSI disk
Sun Jun 11 19:49:29 2023 kern.info kernel: [  292.990741] EXT4-fs (sda2): recovery complete
Sun Jun 11 19:49:29 2023 kern.info kernel: [  292.991324] EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts: (null)
Sun Jun 11 19:49:29 2023 kern.warn kernel: [  292.991383] ext4 filesystem being mounted at /mnt/usb1-2 supports timestamps until 2038 (0x7fffffff)
Sun Jun 11 19:49:29 2023 daemon.info smartd[4606]: smartd received signal 15: Terminated
Sun Jun 11 19:49:29 2023 daemon.info smartd[4606]: smartd is exiting (exit status 0)
Sun Jun 11 19:49:29 2023 kern.warn kernel: [  293.709711] exFAT-fs (sda1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
Sun Jun 11 19:50:00 2023 kern.info kernel: [  324.346704] usb 1-1: USB disconnect, device number 2
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.361440] blk_update_request: I/O error, dev sda, sector 3869088 op 0x1:(WRITE) flags 0x4000 phys_seg 3 prio class 0
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.362486] blk_update_request: I/O error, dev sda, sector 3869328 op 0x1:(WRITE) flags 0x4000 phys_seg 3 prio class 0
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.363483] blk_update_request: I/O error, dev sda, sector 3869568 op 0x1:(WRITE) flags 0x4000 phys_seg 2 prio class 0
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.364481] blk_update_request: I/O error, dev sda, sector 3869808 op 0x1:(WRITE) flags 0x4000 phys_seg 2 prio class 0
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.365573] blk_update_request: I/O error, dev sda, sector 3870048 op 0x1:(WRITE) flags 0x4000 phys_seg 3 prio class 0
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.366581] blk_update_request: I/O error, dev sda, sector 3870288 op 0x1:(WRITE) flags 0x4000 phys_seg 3 prio class 0
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.367575] blk_update_request: I/O error, dev sda, sector 3870528 op 0x1:(WRITE) flags 0x4000 phys_seg 3 prio class 0
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.368569] blk_update_request: I/O error, dev sda, sector 3870768 op 0x1:(WRITE) flags 0x4000 phys_seg 3 prio class 0
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.369624] blk_update_request: I/O error, dev sda, sector 3871008 op 0x1:(WRITE) flags 0x4000 phys_seg 3 prio class 0
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.370629] blk_update_request: I/O error, dev sda, sector 3871248 op 0x1:(WRITE) flags 0x4000 phys_seg 3 prio class 0
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.385471] Buffer I/O error on dev sda2, logical block 1, lost async page write
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.386168] Buffer I/O error on dev sda2, logical block 2, lost async page write
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.386872] Buffer I/O error on dev sda2, logical block 71, lost async page write
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.388551] Buffer I/O error on dev sda2, logical block 73, lost async page write
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.389506] Buffer I/O error on dev sda2, logical block 74, lost async page write
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.390250] Buffer I/O error on dev sda2, logical block 341, lost async page write
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.391718] JBD2: Error while async write back metadata bh 1.
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.391724] JBD2: Error while async write back metadata bh 2.
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.392445] Aborting journal on device sda2-8.
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.393916] Buffer I/O error on dev sda2, logical block 355, lost sync page write
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.394807] JBD2: Error -5 detected when updating journal superblock for sda2-8.
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.395732] JBD2: Error while async write back metadata bh 71.
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.395747] JBD2: Error while async write back metadata bh 73.
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.396462] JBD2: Error while async write back metadata bh 74.
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.397178] JBD2: Error while async write back metadata bh 341.
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.460413] Buffer I/O error on dev sda1, logical block 122371, lost async page write
Sun Jun 11 19:50:00 2023 kern.err kernel: [  324.462167] Buffer I/O error on dev sda1, logical block 126466, lost async page write

**Comment by duojiaqi123** [comment]
后面还有这种

Sat Jun 10 21:56:17 2023 user.info : luci: accepted login on /admin/quickstart for root from 192.168.100.1
Sat Jun 10 21:57:32 2023 user.info : luci: accepted login on /admin/istorex/router/index for root from 192.168.100.242
Sat Jun 10 21:59:26 2023 kern.info kernel: [87678.090585] usb 1-1: USB disconnect, device number 12
Sat Jun 10 21:59:26 2023 kern.info kernel: [87678.091339] sd 0:0:0:0: Device offlined - not ready after error recovery
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.104330] blk_update_request: I/O error, dev sda, sector 4000781096 op 0x1:(WRITE) flags 0x800 phys_seg 7 prio class 0
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.105393] Aborting journal on device sda2-8.
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.105416] blk_update_request: I/O error, dev sda, sector 41800368 op 0x0:(READ) flags 0x80700 phys_seg 2 prio class 0
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.106810] blk_update_request: I/O error, dev sda, sector 4000780998 op 0x1:(WRITE) flags 0x800 phys_seg 1 prio class 0
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.107771] Buffer I/O error on dev sda2, logical block 355, lost sync page write
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.108483] JBD2: Error -5 detected when updating journal superblock for sda2-8.
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.108517] blk_update_request: I/O error, dev sda, sector 41799872 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.110129] blk_update_request: I/O error, dev sda, sector 1092756224 op 0x0:(READ) flags 0x80700 phys_seg 200 prio class 0
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.111426] blk_update_request: I/O error, dev sda, sector 128514 op 0x1:(WRITE) flags 0x100000 phys_seg 1 prio class 0
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.112419] Buffer I/O error on dev sda1, logical block 126466, lost async page write
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.113239] blk_update_request: I/O error, dev sda, sector 1092756424 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.114321] blk_update_request: I/O error, dev sda, sector 1092756425 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.115321] blk_update_request: I/O error, dev sda, sector 1092756426 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.116625] blk_update_request: I/O error, dev sda, sector 1092756427 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
Sat Jun 10 21:59:26 2023 kern.err kernel: [87678.134133] Buffer I/O error on dev sda1, logical block 126466, lost async page write

**Comment by jjm2473** [comment]
是不是电流不够

**Comment by jjm2473** [comment]
你的移动硬盘有外接电源的吗？电流是否达标？

**Comment by czz875** [comment]
r5c也存在该问题，主要是固态硬盘易复现，会产生系统盘和挂载盘同时掉盘的现象，机械偶尔也存在该问题，尝试其他固件无此问题。
![屏幕截图 2023-08-27 220512](https://github.com/istoreos/istoreos/assets/81894187/b341c3b2-36b8-458e-945b-711dbf6b9676)

**Comment by jjm2473** [comment]
看看磁盘管理那边有没有。还有看看内核日志有没有异常报错

**Comment by czz875** [comment]
磁盘管理编辑，进去后显示
/usr/lib/lua/luci/model/diskman.lua:316: attempt to concatenate field 'phy_sec' (a nil value)
stack traceback:
	/usr/lib/lua/luci/model/diskman.lua:316: in function 'get_disk_info'
	/usr/lib/lua/luci/model/cbi/diskman/partition.lua:25: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1533: in function '_form'
	/usr/lib/lua/luci/dispatcher.lua:1058: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:482: in function </usr/lib/lua/luci/dispatcher.lua:481>
内核日志
[  179.222852] print_req_error: 1704 callbacks suppressed
[  179.222861] blk_update_request: I/O error, dev sda, sector 614183232 op 0x1:(WRITE) flags 0x4000 phys_seg 128 prio class 0
[  179.222917] blk_update_request: I/O error, dev sda, sector 614184256 op 0x1:(WRITE) flags 0x4000 phys_seg 128 prio class 0
[  179.222938] blk_update_request: I/O error, dev sda, sector 614185280 op 0x1:(WRITE) flags 0x4000 phys_seg 128 prio class 0
[  179.222957] blk_update_request: I/O error, dev sda, sector 614186304 op 0x1:(WRITE) flags 0x4000 phys_seg 128 prio class 0
[  179.222974] blk_update_request: I/O error, dev sda, sector 614187328 op 0x1:(WRITE) flags 0x4000 phys_seg 128 prio class 0
[  179.222992] blk_update_request: I/O error, dev sda, sector 614188352 op 0x1:(WRITE) flags 0x4000 phys_seg 128 prio class 0
[  179.223009] blk_update_request: I/O error, dev sda, sector 614189376 op 0x1:(WRITE) flags 0x4000 phys_seg 128 prio class 0
[  179.223027] blk_update_request: I/O error, dev sda, sector 614190400 op 0x1:(WRITE) flags 0x4000 phys_seg 128 prio class 0
[  179.223043] blk_update_request: I/O error, dev sda, sector 614191424 op 0x1:(WRITE) flags 0x4000 phys_seg 128 prio class 0
[  179.223061] blk_update_request: I/O error, dev sda, sector 614192448 op 0x1:(WRITE) flags 0x4000 phys_seg 128 prio class 0
[  179.231239] ntfs3: 67 callbacks suppressed
[  179.231247] ntfs3: sda1: failed to read volume at offset 0x1290ea000
[  179.231424] buffer_io_error: 14 callbacks suppressed
[  179.231429] Buffer I/O error on dev sda1, logical block 786647, lost async page write
[  179.522751] ntfs3: sda1: failed to read volume at offset 0x1290ea000
[  179.548093] ntfs3: sda1: failed to read volume at offset 0x1290ea000
[  179.568953] ntfs3: sda1: failed to read volume at offset 0x1290ea000
[  179.588472] ntfs3: sda1: failed to read volume at offset 0x1290ea000
[  179.591574] ntfs3: sda1: failed to read volume at offset 0x1290ea000
[  180.569255] ntfs3: sda1: failed to read volume at offset 0x1290ea000
[  180.569365] ntfs3: sda1: failed to read volume at offset 0x1290ea000
[  193.883227] print_req_error: 402 callbacks suppressed
[  193.883234] blk_update_request: I/O error, dev sda, sector 6293496 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  193.883282] ntfs3: sda1: failed to read volume at offset 0xbffff000
[  193.883308] blk_update_request: I/O error, dev sda, sector 6295232 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  193.883318] ntfs3: sda1: failed to read volume at offset 0xc00d8000
[  193.883333] blk_update_request: I/O error, dev sda, sector 6295232 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  193.883342] ntfs3: sda1: failed to read volume at offset 0xc00d8000
[  193.883354] ntfs3: sda1: ntfs_evict_inode r=0 failed, -22.
[  193.883374] blk_update_request: I/O error, dev sda, sector 6293496 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  193.883383] ntfs3: sda1: failed to read volume at offset 0xbffff000
[  194.968295] blk_update_request: I/O error, dev sda, sector 6293496 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  194.968334] ntfs3: sda1: failed to read volume at offset 0xbffff000
[  194.968362] blk_update_request: I/O error, dev sda, sector 6295232 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  194.968372] ntfs3: sda1: failed to read volume at offset 0xc00d8000
[  194.968386] blk_update_request: I/O error, dev sda, sector 6295232 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  194.968394] ntfs3: sda1: failed to read volume at offset 0xc00d8000
[  194.968406] ntfs3: sda1: ntfs_evict_inode r=0 failed, -22.
[  194.968425] blk_update_request: I/O error, dev sda, sector 6293496 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[  194.968434] ntfs3: sda1: failed to read volume at offset 0xbffff000

**Comment by czz875** [comment]
实测中etx4格式更容易发生问题

**Comment by jjm2473** [comment]
格式化以后看看还有没有问题

**Comment by czz875** [comment]
做几次实验，大概率是卡 IO 导致 CPU 100% 问题，从而导致读不到盘

**Comment by czz875** [comment]
测试了几天，发现是卡i/o了
![屏幕截图 2023-08-31 220625](https://github.com/istoreos/istoreos/assets/81894187/830b7b54-10f7-4bcf-a83c-03d3da0d4457)
到最后会出现Load很高，CPU使用率很低的诡异情况，不知道如何解决
![屏幕截图 2023-08-31 184248](https://github.com/istoreos/istoreos/assets/81894187/e61af1e3-1076-4a9a-84b6-2d77ed73b7d3)

**Comment by jjm2473** [comment]
系统盘都能掉真是厉害。之后不要看首页显示的状态了，直接在终端执行 `lsblk` 就可以看到磁盘信息

**Comment by jjm2473** [comment]
万一首页那边只是因为io卡住没加载出来，那就没有任何参考价值了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2876/1
