### ISSUE TITLE
为什么我在istore里面下载的可道云打开后显示尚无任何配置

### ISSUE THREAD

**Issue by heipopw** [istoreos/istoreos#828]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：为什么我在istore里面下载的可道云打开后显示尚无任何配置

### (2) 路由器型号和固件版本

A：LuCI istoreos-21.02 branch (git-23.088.34636-f8cc111)

### (3) 详细日志和/或截图

A :  [https://upload.cc/i1/2023/06/10/fRv9CO.png](url)

**Comment by jjm2473** [comment]
把/etc/config里面的可道云配置文件删掉，然后重新安装插件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2875/1
