### ISSUE TITLE
请问是否支援联发科 MT9721/MT7922且三频跑满?

### ISSUE THREAD

**Issue by kenny61207** [istoreos/istoreos#830]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：目前使用OpenWRT原厂固件需要额外刷入驱动，请问IStoreOS是否内建这两张网卡的驱动，并且能2.4G/5G/6G 三频跑满，谢谢

### (2) 路由器型号和固件版本

A：
![image](https://github.com/istoreos/istoreos/assets/51124107/ebe017a1-5992-4896-80ca-149fb02a28ef)

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
自己测试啊，谁知道能不能跑满，我的设备最多也就1200M

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2873/1

**Comment by yangdong123** [comment]
为什么不能拆开设置2.4g 5g 6g ,一个配置改了其他频段也同步修改了，是不是bug?

**Comment by jjm2473** [comment]
> 为什么不能拆开设置2.4g 5g 6g ,一个配置改了其他频段也同步修改了，是不是bug?

你知道自己的模块支持多频共存吗？如果支持，那应该是有多个radio
