### ISSUE TITLE
qBittorrent Web UI 无法登录 忘记用户密码怎么办？

### ISSUE THREAD

**Issue by MAOGE2018** [istoreos/istoreos#832]
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

2. 详细叙述
 qBittorrent Web UI http://192.168.100.1:8080/  突然无法登录，显示 ：无效的用户名或密码。
记得没有修改默认密码，
设备型号:x86设备：倍控8505
固件版本:iStoreOS 21.02.3 2023052616
内核版本:5.4.188

请问如何修改默认密码？
安装路径是：
/mnt/sata2-1/Configs/qb/qBittorrent/config/qBittorrent.conf
网上查找过 但是在上面路径根本没有 qBittorrent.conf文件，删除“WebUI\Password_PBKDF2”这一行
参考的是这里：https://zhuanlan.zhihu.com/p/374538088
默认用户名是：admin  密码是：adminadmin
---------------
卸载从新安装就能默认密码进入了，不知道什么情况，嗨森请告诉我万一忘记如何修改吧！！！

**Comment by DaMccRee** [comment]
完全正确
