### ISSUE TITLE
	iStoreOS 21.02.3 2023060914 / LuCI istoreos-21.02 branch git-23.088.34636-f8cc111

### ISSUE THREAD

**Issue by ncy92** [istoreos/istoreos#833]
被控J4215 iStoreOS 21.02.3 2023060914 / LuCI istoreos-21.02 branch git-23.088.34636-f8cc111
DNS不定时失效无法访问网站，DNS只能添加一个不能添加备用DNS
![6754d6edc076e47c2e190d3a34a9e61](https://github.com/istoreos/istoreos/assets/76580423/b59fd5d8-71fd-4f8d-af02-449b93606af6)
![e264477b06ad14c908dadbd77e84879](https://github.com/istoreos/istoreos/assets/76580423/31e69bea-6758-443c-a32d-a204385fae8a)

**Comment by ncy92** [comment]
被控J4125

**Comment by jjm2473** [comment]
填个靠谱的dns不就行了，或者看看上游的路由器有没有dns服务

**Comment by ncy92** [comment]
> 填个靠谱的dns不就行了，或者看看上游的路由器有没有dns服务

软路由是二级路由，添加主路由拨号获取的IPv6 DNS就报错，现在只用IPv4的DNS没有断网问题

**Comment by ncy92** [comment]
![bc0cb4a69ad3b246d368edad0093e4a](https://github.com/istoreos/istoreos/assets/76580423/1304b6d4-4ed9-4067-96d7-93494585bb0f)
没有改任何配置就报错

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2871/1
