### ISSUE TITLE
急！手动升级出现找不到luci.iform模块，进不了luci页面。

### ISSUE THREAD

**Issue by 8389899** [istoreos/istoreos#836]
反馈bug/问题模板，提建议请删除

**1.关于你要提交的问题**
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时包括已关闭的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
没有找到类似的问题。

**2. 详细叙述**
**(1) 具体问题**
A：手动运行升级软件后
opkg list-upgradable | awk -F ' - ' '{print $1}' | xargs opkg upgrade
出现进不了luci
**(2) 路由器型号和固件版本**
A：X86
**(3) 详细日志和/或截图**
A：提示如下：
/usr/lib/lua/luci/controller/systools.lua:4: module 'luci.iform' not found:
	no field package.preload['luci.iform']
	no file './luci/iform.lua'
	no file '/usr/share/lua/luci/iform.lua'
	no file '/usr/share/lua/luci/iform/init.lua'
	no file '/usr/lib/lua/luci/iform.lua'
	no file '/usr/lib/lua/luci/iform/init.lua'
	no file './luci/iform.so'
	no file '/usr/lib/lua/luci/iform.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/controller/systools.lua:4: in main chunk
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1111: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:1211: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:705: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:806: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>

软路由机型是X86
进不了luci了，要怎么还原回去？

**Comment by jjm2473** [comment]
重刷，谁让你乱升级的。

**Comment by 8389899** [comment]
有没有办法退回升级前的状态？

**Comment by jjm2473** [comment]
除非你用了沙箱，那很简单，退出沙箱即可。

还有systool的系统软件修复也可以试试，但是现在你都已经打不开luci了，没法操作，除非自己手动执行。

**Comment by 8389899** [comment]
麻烦大佬能不能说下怎么手动执行？非常感谢。

**Comment by jjm2473** [comment]
很麻烦，而且你之前也不一定安装了systool，还是恢复出厂设置吧，别浪费时间了

**Comment by 8389899** [comment]
先谢谢大佬了！
systool已经安装了，我记得systool里有重装功能，现在luci进不去没法用了，手动方式要怎么做，能否麻烦大佬解惑？

**Comment by jjm2473** [comment]
直接执行 `/usr/share/systools/reset_rom_pkgs.run`，大概10秒后会自动重启

**Comment by jjm2473** [comment]
如果不知道哪里执行命令，那就打开后台页面，但是端口改成7681，例如 http://192.168.100.1:7681 ，输入用户名密码登录之后就可以执行命令了。

**Comment by 8389899** [comment]
可以用SSH连接，我马上试下，谢谢大佬！

**Comment by 8389899** [comment]
运行这个命令reset_rom_pkgs.run，系统配置会丢失吗？

**Comment by 8389899** [comment]
大佬，早上好！
昨天按您说的运行了reset_rom_pkgs.run，并重启系统，故障还是依旧进不了luci，提示出错还是跟原来一样，还有其它办法吗？

**Comment by jjm2473** [comment]
执行这个命令试试 `is-opkg install luci-lib-iform`

**Comment by 8389899** [comment]
好的，谢谢大佬，晚上回去试下。

**Comment by 8389899** [comment]
按大佬说的方法，终于搞定了，谢谢大佬！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2868/1
