### ISSUE TITLE
h68k不识别2.5g网口

### ISSUE THREAD

**Issue by kkyinAdmin** [istoreos/istoreos#837]
h6xk固件，版本21.02.3-2023060914，h68k四网口设备不识别2.5G的两个网口

**Comment by jjm2473** [comment]
没看到有人反馈，建议全新刷机看看。如果还有问题，可能是硬件版本的问题，那就要联系厂家了

**Comment by jjm2473** [comment]
我已经测试了，h68k没问题。如果你用了sd卡，而且还emmc和sd都刷过系统，那么拔掉sd卡，给emmc重新刷机看看还有没有问题，如果有，那只能是硬件问题了，因为h68k有多个版本。

**Comment by zhaozhedominic** [comment]
我也发现这个问题，就是写入不管什么时间版本的固件只有在lean的固件下2.5G口是正常识别，都是emmc写入未使用TF卡的情况下

**Comment by jjm2473** [comment]
@zhaozhedominic 硬件版本的问题，找厂家，你开机以后看看是不是被识别成H69K了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2867/1
