### ISSUE TITLE
无法在Docker中启用IPV6

### ISSUE THREAD

**Issue by 91651** [istoreos/istoreos#839]
无法在Docker Bridge网络中启用IPV6，使用官网配置后没有任何效果
配置如下
`/etc/docker/daemon.json`
`{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64",
  "experimental": true,
  "ip6tables": true
}`
使用 docker network inspect bridge 命令查看结果"EnableIPv6": false

**Comment by jjm2473** [comment]
/etc/docker/daemon.json 默认情况下是生成的，你改了也会被覆盖。如果你真的要手动配置 /etc/docker/daemon.json，那么先删掉 /etc/config/dockerd 。

不过配置的ipv6流量会被转发到容器吗？一般都是docker-proxy进行端口映射的，host网络模式下则直接使用宿主的网络。

**Comment by 91651** [comment]
> /etc/docker/daemon.json 默认情况下是生成的，你改了也会被覆盖。如果你真的要手动配置 /etc/docker/daemon.json，那么先删掉 /etc/config/dockerd 。
> 
> 不过配置的ipv6流量会被转发到容器吗？一般都是docker-proxy进行端口映射的，host网络模式下则直接使用宿主的网络。

感谢大神的回复，我后面试一下。

**Comment by 91651** [comment]
@jjm2473  如何在/etc/config/dockerd总配置IPV6呢？ 有没有关于/etc/config/dockerd的参数文档

**Comment by jjm2473** [comment]
`/etc/config/dockerd`没有那么高级（其他人也用不上ipv6，所以不知道有没有这个选项），如果你要自定义`/etc/docker/daemon.json`，那就按我前面说的，如果还有问题就去找Docker官方的文档。

**Comment by 91651** [comment]
@jjm2473  /etc/config/dockerd 删除后会自动创建，然后/etc/docker/daemon.json 仍然无效。
有意思的是 /etc/config/dockerd 中可以使用 /etc/docker/daemon.json 的相关配置，只需要稍微变更写法。

```
config globals 'globals'
	option log_level 'warn'
	option iptables '1'
	option data_root '/iData/docker'
	option experimental '1'
	option ipv6 '1'
	option ip6tables '1'
	option fixed_cidr_v6 'fd00::/80'
```

**Comment by jjm2473** [comment]
怎么会自动创建呢？难道你是在后台页面又配置了docker？既然你都要自己写daemon.json，就不能用后台页面配置。

/etc/config/dockerd只支持部分的配置，你可以自己看 /rom/etc/config/dockerd ，这个是原始的文件，被注释的就是提示你支持的参数。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2865/1
