### ISSUE TITLE
光猫路由模式，有ipv6且能正常通过ipv6网站的检测，istoreos后台已经有公网IPV6地址，但是没网络访问权。没有勾选禁止ipv6

### ISSUE THREAD

**Issue by OopsWD** [istoreos/istoreos#844]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：
光猫路由模式有ipv6且能正常通过ipv6网站的检测，istoreos后台已经有公网IPV6地址，但是没网络访问权。没有勾选禁止ipv6
### (2) 路由器型号和固件版本

A：x86
iStoreOS 21.02.3 2023060914

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/69693774/e2c2226a-108b-4281-839a-6bccfc964cec)
没有勾选
![image](https://github.com/istoreos/istoreos/assets/69693774/cfc03296-d28c-4c4b-b17b-0a15645e2872)
![image](https://github.com/istoreos/istoreos/assets/69693774/3f328e91-0ade-49f6-be69-a30d92268a9f)
![image](https://github.com/istoreos/istoreos/assets/69693774/c931c49b-2e01-45d4-9992-3068eca3e8ab)
![image](https://github.com/istoreos/istoreos/assets/69693774/a6e069d3-46dc-43c1-a1b5-e6ec09cd4890)
----电脑的ipv6测试结果----
![image](https://github.com/istoreos/istoreos/assets/69693774/529a1121-da15-4822-8568-dd96fab05eef)
----手机连接光猫WIFI的ipv6测试结果----
![image](https://github.com/istoreos/istoreos/assets/69693774/3526b90b-34df-4391-8752-d1d351b45ac9)

**Comment by alex-cse** [comment]
同样问题，重新拨号一次即可

**Comment by OopsWD** [comment]
> 同样问题，重新拨号一次即可

感谢解决了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2861/1
