### ISSUE TITLE
希望能添加airplay连接插件

### ISSUE THREAD

**Issue by jasonhuizhang** [istoreos/istoreos#848]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [X ] 没有类似的issue

### (1) 具体问题

A：安装Shairplay插件，并开启服务。在iPhone中看不到此airplay服务。另外，在安装包中搜索不到airplay2插件。希望能提供airplay服务。谢谢

### (2) 路由器型号和固件版本

A：iStore [v0.1.13-3]，R4S

### (3) 详细日志和/或截图

A：

**Comment by DaMccRee** [comment]
我也希望有

**Comment by jjm2473** [comment]
哪里有airplay2？

**Comment by jasonhuizhang** [comment]
之前用骷髅头固件自带有（https://github.com/DHDAXCW/NanoPi-R4S-R4SE）

**Comment by jasonhuizhang** [comment]
> 哪里有airplay2？

之前用骷髅头固件里面有（https://github.com/DHDAXCW/NanoPi-R4S-R4SE）

**Comment by jjm2473** [comment]
OK，应该是这个 https://github.com/coolsnowwolf/luci/blob/master/applications/luci-app-airplay2/Makefile

**Comment by jasonhuizhang** [comment]
> OK，应该是这个 https://github.com/coolsnowwolf/luci/blob/master/applications/luci-app-airplay2/Makefile

能加载到应用商店吗？不会编译🥹

**Comment by jjm2473** [comment]
istore已经上架了此插件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2857/1
