### ISSUE TITLE
发现终端无法使用pip yun等命令

### ISSUE THREAD

**Issue by q877604530** [istoreos/istoreos#850]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
发现终端无法使用pip yun等命令
### (1) 具体问题
发现终端无法使用pip yun等命令
A：

### (2) 路由器型号和固件版本
iStoreOS 21.02.3 2023060914
A：

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
又不是centos，哪来的yum？pip是python的包管理工具，需要自己安装，在后台的“系统”-“软件包”里。这是openwrt通用的技能，不要反馈到istoreos！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2855/1
