### ISSUE TITLE
自带DDNS 3322的URL已失效

### ISSUE THREAD

**Issue by yahochina** [istoreos/istoreos#852]
3322 的更新URL已从3322.org变更为3322.net

orayr 的好像也变更了

不修改DDNS用不了。

**Comment by jjm2473** [comment]
试试 Lucky，最近挺多人推荐的，iStore里面就能安装

**Comment by jibryant** [comment]
dnspod选项也没有了

**Comment by BG8HQE** [comment]
腾讯DNSPOD怎么莫有了哈，必须要用呢

**Comment by jjm2473** [comment]
@jibryant @BG8HQE 更新日志里面已经增加了解决方案 https://github.com/istoreos/istoreos/discussions/860

**Comment by jjm2473** [comment]
我看openwrt官方的仓库还是使用3322.org， 建议在openwrt那边反馈下，以免以后被上游覆盖 https://github.com/openwrt/packages

**Comment by jjm2473** [comment]
已经增加3322.net

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2853/1
