### ISSUE TITLE
R2S 版第二天会出现LAN口无数据，红灯。重启恢复，然后又出现

### ISSUE THREAD

**Issue by WWRichard** [istoreos/istoreos#853]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题
使用一天后，LAN 口无数据，重启恢复，然后又会出现。基本都会在第二天出现这个情况
LAN 口红灯，无网络，LAN口连接华为AX2 pro 路由器
A：

### (2) 路由器型号和固件版本
R2S

[istoreos-21.02.3-2023060914-r2s-squashfs.img.gz](https://fw0.koolcenter.com/iStoreOS/r2s/istoreos-21.02.3-2023060914-r2s-squashfs.img.gz)
A：

### (3) 详细日志和/或截图

A：

**Comment by WWRichard** [comment]
已经有人反馈了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2852/1
