### ISSUE TITLE
单击编辑wan_6弹错误弹窗,192.168.100.1,无法进入istorex 插件首页

### ISSUE THREAD

**Issue by fly127** [istoreos/istoreos#854]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [X] 没有类似的issue

## 2. 详细叙述

(1) 具体问题: wan_6 虚拟接口,点击"编辑", 会弹窗"TypeError
Cannot read properties of null (reading '.name')"
(2) istorex 插件, 输入192.168.100.1进入首页时,无法进入istorex的插件页.

A：

### (2) 路由器型号和固件版本

A：畅网N5000, 固件版本:iStoreOS 22.03.4 2023063015

### (3) 详细日志和/或截图

A：
![捕获](https://github.com/istoreos/istoreos/assets/73457045/f56e3622-cb02-42ad-ad15-9dede1760b24)

**Comment by jjm2473** [comment]
wan_6是动态接口，本来就没有实际的配置，编辑不了的

**Comment by linzelong18938901663** [comment]
我也是这个问题，请问如何解决，不用管他吗

**Comment by jjm2473** [comment]
wan_6是虚拟接口，本来就无法编辑，只是界面上没隐藏掉编辑按钮而已。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2851/1
