### ISSUE TITLE
无法 cd 出文件夹

### ISSUE THREAD

**Issue by benzo970210** [istoreos/istoreos#857]
在终端里面无法找到文件夹，我新建一个文件夹为ip，在软路由实体机（连接了显示器）能够cd 出来，在web页面终端找不到，在我电脑的finalshell 里面也cd 不出来，这是那点的问题

**Comment by rootphantomer** [comment]
...你目录不对，table补全不出来呗。ls看看有没有那个ip目录

**Comment by benzo970210** [comment]
ok
我确实没得弄对

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2848/1
