### ISSUE TITLE
硬盘挂载错误

### ISSUE THREAD

**Issue by GFDCGFC** [istoreos/istoreos#858]
每次挂载新硬盘挂载后首页显示正确，系统显示大小不对检测后容量也是不对，重新挂载后还是一样
![屏幕截图 2023-07-06 204615](https://github.com/istoreos/istoreos/assets/96916244/2f7bbd9e-2af0-4e33-b4d5-a1f650252661)
![屏幕截图 2023-07-06 204713](https://github.com/istoreos/istoreos/assets/96916244/d9b7457c-9650-417b-89e0-0f08a78680f7)

**Comment by jjm2473** [comment]
重新格式化，你这种情况是因为一开始分了个小分区，然后格式化的，后来扩大分区以后，又没有重新格式化，所以文件系统还是只有原来的大小。

对于ext4分区，可以使用resize2fs扩容，详情自己查资料。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2847/1
