### ISSUE TITLE
请问如何安装阿里云盘fuse？

### ISSUE THREAD

**Issue by benzo970210** [istoreos/istoreos#859]
请问如何安装阿里云盘fuse？

**Comment by rootphantomer** [comment]
https://github.com/messense/aliyundrive-fuse

![image](https://github.com/istoreos/istoreos/assets/6481352/4109cdef-b074-47d4-bcb1-d58e4ea1fabd)

**Comment by jjm2473** [comment]
fuse很久没更新了，安装了也没用

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2846/1
