### ISSUE TITLE
VNC下不需要 密码就能登录

### ISSUE THREAD

**Issue by fbt9910** [istoreos/istoreos#861]
导致vps被封垃圾玩意

**Comment by jjm2473** [comment]
你把vnc暴露出去，还说没密码？而且固件本身可没vnc，是你自己的虚拟机或vps服务商提供的vnc，不去找找vps的原因？

**Comment by jjm2473** [comment]
正常情况下，串口或者显示器，都是要物理连接键盘鼠标才能控制的。你自己用vnc把虚拟机暴露到公网，却说虚拟机里面的系统没密码？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2845/1
