### ISSUE TITLE
来个大佬istore 的frp怎么用啊

### ISSUE THREAD

**Issue by benzo970210** [istoreos/istoreos#862]
来个大佬istore 的frp怎么用啊

**Comment by jjm2473** [comment]
这不是论坛，issue是用来反馈问题或者提建议的。插件的使用自己百度下

**Comment by benzo970210** [comment]
没找到啊，他这个和openwrt 里面的完全不一样，就搞不懂了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2844/1
