### ISSUE TITLE
升级22.03.4后无法打开Web管理页面

### ISSUE THREAD

**Issue by wu0lei** [istoreos/istoreos#863]
esxi安装istoreos，在web在线更新后，无法登录web配置页面，升级的版本号：22.03.4-2023070715-x86-64-squashfs-combined-efi.img.gz

**Comment by jjm2473** [comment]
为什么不把日志发出来？既然是虚拟机，应该比物理机更容易抓日志或者截图吧

**Comment by WYH2004-MC** [comment]
> 为什么不把日志发出来？既然是虚拟机，应该比物理机更容易抓日志或者截图吧

物理机升级后出现一样的情况，浏览器提示拒绝了连接，ssh可以连接，已经尝试重启uhttpd还是一样，请问要提供哪个日志，luci还是uhttpd

**Comment by atomshadows** [comment]
我也遇到了，用SSH连接以后更新软件包和内核以后恢复，你可以试试：

# 更新软件列表
opkg update

# 更新所有 LUCI 插件
opkg list-upgradable | grep luci- | cut -f 1 -d ' ' | xargs opkg upgrade

# 如果要更新所有软件，包括 OpenWRT 内核、固件等
opkg list-upgradable | cut -f 1 -d ' ' | xargs opkg upgrade

**Comment by jjm2473** [comment]
别乱更新系统组件，反而容易出问题。

**Comment by jjm2473** [comment]
@WYH2004-MC 系统日志。后台进不去可以用 logread 命令读取日志。或者自己打开浏览器的调试工具，看看有没有打印错误

**Comment by jjm2473** [comment]
要么就恢复出厂设置

**Comment by WYH2004-MC** [comment]
> @WYH2004-MC 系统日志。后台进不去可以用 logread 命令读取日志。或者自己打开浏览器的调试工具，看看有没有打印错误

解决了，我又开了一个Issues #865 里面有个人给出了解决方法

**Comment by jjm2473** [comment]
如果之前使用nginx，现在打不开后台，那就升级nginx相关的包

**Comment by jjm2473** [comment]
ssh或者终端（访问7681端口）执行 `opkg remove --force-removal-of-dependent-packages --autoremove nginx-util; opkg update ; opkg install luci-nginx`

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2556/6

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2843/1
