### ISSUE TITLE
保留配置升级22.03.4-2023070715-x86-64-squashfs-combined-efi.img.gz后，aria2无法运行

### ISSUE THREAD

**Issue by ssupssup** [istoreos/istoreos#864]
保留配置升级22.03.4-2023070715-x86-64-squashfs-combined-efi.img.gz后，aria2无法运行，配置都没变，刷回旧版aira2就正常了

**Comment by jjm2473** [comment]
卸载，重新安装aria2试试

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2842/1
