### ISSUE TITLE
网络接口状态空

### ISSUE THREAD

**Issue by lolikyo** [istoreos/istoreos#872]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：网络接口状态空，网口配置页面空，但是接口以及网络一切正常

### (2) 路由器型号和固件版本

A：路由器R2S 固件iStoreOS 22.03.4 2023070715 / LuCI openwrt-22.03 branch git-23.119.80898-65ef406

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/49865203/1c14acb3-e7bd-4b79-b290-1622c1fd7982)
![image](https://github.com/istoreos/istoreos/assets/49865203/f2b9c333-3325-4b7a-8381-59b1dd741b9c)
![image](https://github.com/istoreos/istoreos/assets/49865203/4347dd73-2374-4644-94c8-2921d80cdb1e)

**Comment by jjm2473** [comment]
实测没有这个问题。

根据这里的第2条修复系统组件 https://github.com/istoreos/istoreos/wiki/FAQ

要么就恢复出厂设置

**Comment by lolikyo** [comment]
恢复sys解决了，感谢

**Comment by Vinke2** [comment]
+1 用系统修复工具解决了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2822/1
