### ISSUE TITLE
H68K更新到iStoreOS 22.03.4 2023070715，无法识别网口

### ISSUE THREAD

**Issue by CharlieVSAngel** [istoreos/istoreos#876]
H68K更新到iStoreOS 22.03.4 2023070715后，四网口无法正常识别，智能识别到三个网口，而且网口顺序不对
![Screenshot_20230713_124007](https://github.com/istoreos/istoreos/assets/85690780/b0847da4-45ee-45de-9066-794003a2b068)
![Screenshot_20230713_131414](https://github.com/istoreos/istoreos/assets/85690780/0d1436be-d5fb-40f5-848a-b52b249955a7)

**Comment by litongda007** [comment]
同样问题可以稳定复现在我的H68K上。另外设备型号识别也有误，会被识别为H69K。

**Comment by jjm2473** [comment]
因为h68k硬件有很多版本，有些硬件版本没法在软件上区分，我们也不会给一个型号分多个固件的，有问题就找厂商吧。

**Comment by jjm2473** [comment]
早期版本的h68k无法与现在的h69k区分开，于是识别成h69k了，h69k就是三个网口的

**Comment by CharlieVSAngel** [comment]
> 

为什么之前的版本就不会，升级到iStoreOS 22.03.4 2023070715后就出问题了，按照这个思路是不是可以解决？

**Comment by CharlieVSAngel** [comment]
> 早期版本的h68k无法与现在的h69k区分开，于是识别成h69k了，h69k就是三个网口的

可不可以自己手动添加端口？

为什么之前的版本就不会，升级到iStoreOS 22.03.4 2023070715后就出问题了，按照这个思路是不是可以解决？

**Comment by jjm2473** [comment]
因为之前的版本没有h69k啊

**Comment by lan-zz** [comment]
我的H68K，首页的网络接口状态与侧边菜单点出来的网口配置里都看不见网口，点击保存并应于就出现“网络异常：500 response parse failed”报错 
![IStoreOS截图-3](https://github.com/istoreos/istoreos/assets/39406063/53c0c0a4-9653-49c1-a6c2-def75f45d167)

**Comment by jjm2473** [comment]
@lan-zz 1. 换浏览器，2. 恢复出厂设置。总能修复的

**Comment by BlackteaCN** [comment]
<转载>
1.在终端执行
cp /boot/rockchip1.dtb  /boot/rockchip10.dtb
2.重启
3.接口中发现新接口
4.将新接口手动添加到lan。
5.第二步也可以改为直接恢复出厂设置
6.本教程仅限能正常识别三口的机型使用，原本只能识别一口的只能恢复双千兆，仍然无法使用2.5g。
这些最老的机型需要刷固定型号的固件，无法使用istoreos自动判别。

**Comment by jjm2473** [comment]
主要就是一些老的机器没有配置好ADC的电阻，导致无法跟其他版本区分开来，这样的机器应该很少。有能力的可以问厂商怎么改电阻，然后手动改。

手动替换dtb文件的话，升级固件以后又会变回来。

另外，如果熟悉uboot，可以进uboot的console，修改启动命令。uboot是不会被升级覆盖的。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2818/1
