### ISSUE TITLE
更新新版本后   N5105无法识别网口  无法上网

### ISSUE THREAD

**Issue by KeplerSSSSS** [istoreos/istoreos#877]
更新新版本后   N5105无法识别网口  无法上网

**Comment by jjm2473** [comment]
什么机型？什么网卡

**Comment by jjm2473** [comment]
我测试了R86s是没问题的，也是N5105，而且网络问题一般跟CPU无关

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2817/1
