### ISSUE TITLE
更新iStoreOS 22.03.4 2023070715后经常掉线

### ISSUE THREAD

**Issue by kinf520** [istoreos/istoreos#879]
不清楚是哪里的问题，自从更新这边版本后长期掉线自动重连。
![Snipaste_2023-07-15_10-37-48](https://github.com/istoreos/istoreos/assets/68365468/26a47ae1-9997-4746-b614-7fa743c41f87)
![Snipaste_2023-07-15_10-37-54](https://github.com/istoreos/istoreos/assets/68365468/8e64ba57-3587-4509-a0aa-65871bafdf66)
![{596F35E1-4751-447a-8503-7BF15B2DD313}](https://github.com/istoreos/istoreos/assets/68365468/4efd52b9-514e-4853-ac15-8594c4a572ad)

**Comment by kinf520** [comment]
![image](https://github.com/istoreos/istoreos/assets/68365468/7442eb27-b7d9-41eb-b093-c5d0204504ed)
捕捉到一个最新断网时间17.29分

**Comment by jjm2473** [comment]
发日志能不能直接复制文本呢，有什么必要截图

**Comment by jjm2473** [comment]
<img width="504" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/b89111e6-483d-4ae5-b28f-eeb063830b4c">
确定不是有人在拔插网线？先是eth3，然后eth0

**Comment by kinf520** [comment]
没人拔网线啊，而且每次断网都是随机的。有时候一天多，有时候几小时

**Comment by jjm2473** [comment]
那是不是过热了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2816/1
