### ISSUE TITLE
升级最新固件后x86-64 intel82546 pci双千兆网卡无法使用

### ISSUE THREAD

**Issue by mithrandiryee** [istoreos/istoreos#880]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：升级最新固件后x86-64 intel82546 pci双千兆网卡无法使用

### (2) 路由器型号和固件版本

A：WY546T2 PCI双口千兆网卡intel82546
i3-6100 Gigabyte B150M-D3V DDR3

### (3) 详细日志和/或截图

A：能认出ETH2,ETH3，流量0

**Comment by jjm2473** [comment]
你有看br-lan是不是包括eth2，eth3吗？执行`ip link`看看

**Comment by mithrandiryee** [comment]
> 

升级安装，lan桥包含这张网卡的2个ETH也就是ETH2,ETH3，可就是没流量，不知道是不是新内核删掉了32位PCI的驱动

**Comment by jjm2473** [comment]
执行`ip link`看看

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2815/1
