### ISSUE TITLE
20230716升级最新固件后突然掉线 无法进入webui 界面

### ISSUE THREAD

**Issue by gzxiexl** [istoreos/istoreos#881]
![image](https://github.com/istoreos/istoreos/assets/40417977/fca7f8f3-0352-4cd4-a5bd-0866b2bd43eb)

路由器接显示器显示如上
SSH中reboot都没有反应
我的是x86物理机安装的

**Comment by lbxxdg** [comment]
我好像也是，进管理页面报500 Internal Server Error错误，但是感觉网络功能还在

**Comment by Skyminers** [comment]
没有做任何更新操作，，我这里所有的 web 服务都报 HTTP ERROR 503。但是 ssh 可以进去，网络功能也是正常的

**Comment by jjm2473** [comment]
用free命令看看是不是内存不足

**Comment by jjm2473** [comment]
如果用了docker，把docker都停掉

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2814/1
