### ISSUE TITLE
请求添加 mosdns、AdGuard Home

### ISSUE THREAD

**Issue by draco-china** [istoreos/istoreos#883]
## 1.关于你要提交的问题
手动安装 mosdns 太过繁琐
[luci-app-mosdns](https://github.com/sbwml/luci-app-mosdns)
目前手动安装已正常运行

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
手动安装需要先安装mosdns v2dat 才能继续安装luci-app-mosdns及汉化包

希望可以提供完整pr istore软件列表相关流程，目前看了是分了好几个包 

- https://github.com/linkease/istore-packages
- https://github.com/linkease/istore-repo
- https://github.com/linkease/openwrt-app-meta

按仓库来看是否是以下步骤
1. 将上游代码同步到 istore-packages
2. 打包成 ipk 到 istore-repo
3. 在openwrt-app-meta添加前面所添加的app源数据

### (1) 具体问题
为什么不使用smart dns ?
A：相对而言 smart dns 手动配置麻烦，mosdns 自动分流 可以不需要复杂配置就可以使用

### (2) 路由器型号和固件版本

A：

### (3) 详细日志和/或截图

A：

**Comment by Jarv1s0** [comment]
你好，请问我在安装过程中出现以下以来错误，不知道你是在哪里下载的libubox20210516 和v2dat。我的是R4S，下载的aarch64_generic，提示不兼容。
Unknown package 'luci-app-mosdns'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency libubox20210516 for jsonfilter
 * pkg_hash_check_unresolved: cannot find dependency v2dat for luci-app-mosdns
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-mosdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-mosdns.

**Comment by jjm2473** [comment]
这里有离线安装包 https://github.com/AUK9527/Are-u-ok

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2812/1
