### ISSUE TITLE
R6C 20230716固件会断流

### ISSUE THREAD

**Issue by jian263994241** [istoreos/istoreos#884]
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：刚刷好固件，刷抖音头条经常看着看着就刷不出来， 一会有好了，  登陆后台观察，家里挂着京东云，  上传 8MB/s， 一会就变成0， 过一会上传速度又会上来， 过一会又变成 0上传。 估计这时候家里流量断了，  ppoe没有重新拨号说明宽带没断。   换成备用的R5C（同一版本固件） 没有问题， 已稳定一天多。

### (2) 路由器型号和固件版本

A：R6C 20230716

### (3) 详细日志和/或截图

A：日志看不出来，或者我不会看

**Comment by jjm2473** [comment]
日志看不出来就发出来啊，系统日志都是有时间的，把断网前后的日志复制出来

**Comment by kinf520** [comment]
我也是出现了断网，不过一会就自动好了。查看运行时间又是正常，就联网时间重新计算。不过我的是X86

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2811/1
