### ISSUE TITLE
👌【已解决】升级后出现  curl: (48) Error ！

### ISSUE THREAD

**Issue by cn-jiangfei** [istoreos/istoreos#886]
## 1.关于你要提交的问题
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
前几天看到有本版更新就随手更新了一下，更新以后没有注意，今天发现检测更新或者安装应用时提示 curl: (48) Error！
### (1) 具体问题

A：检查和更新固件时提示 curl: (48) Error！
B：iStore安装应用时提示 curl: (48) Error！
C：使用 curl 命令时提示 curl: (48) Error！

### (2) 路由器型号和固件版本

A：EXSI 虚拟机  x86/64
B：固件版本	iStoreOS 22.03.4 2023070715 / LuCI istoreos-22.03 branch git-23.103.23275-0193674
C ：内核版本	5.10.176

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/17905855/3bb88433-c8fb-458d-a92b-fcc8986884af)

![photo_2023-07-17_19-27-25](https://github.com/istoreos/istoreos/assets/17905855/eba81623-06d1-43a3-8039-bc25bccfd8dc)

![image](https://github.com/istoreos/istoreos/assets/17905855/552bc545-d47b-4e32-a75b-bb53c80ca657)

**Comment by cn-jiangfei** [comment]
已经解决，主要是因为   curl 和 libcurl 版本不匹配 导致的。
`root@Openwrt:~# curl -V
curl 7.88.1 (x86_64-openwrt-linux-gnu) libcurl/7.83.1 wolfSSL/5.5.3 nghttp2/1.44.0
Release-Date: 2023-02-20
Protocols: file ftp ftps http https mqtt
Features: alt-svc HSTS HTTP2 IPv6 Largefile SSL
WARNING: curl and libcurl versions do not match. Functionality may be affected.`

这时候更新一下  curl 和 libcurl ：
`opkg install curl libcurl`

更新以后提示缺少 libmbedtls.so.14、libmbedx509.so.1 和 libmbedcrypto.so.7 等共享库，并且找不到与 mbedtls 相关的符号。缺少什么在安装什么就可以了：
`opkg install libmbedtls libmbedx509 libmbedcrypto`

至此问题解决！

**Comment by jjm2473** [comment]
什么不匹配啊，就是因为你自己升级导致的啊

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2810/1
