### ISSUE TITLE
T68M安装固件22.03.4后网卡eth1不能识别，请修复。

### ISSUE THREAD

**Issue by dreamlandhl** [istoreos/istoreos#889]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：T68M安装固件22.03.4后网卡eth1不能识别，请修复。

### (2) 路由器型号和固件版本

A：T68M  固件22.03.4

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
t68m是厂家适配的，去找厂家反馈

**Comment by jjm2473** [comment]
最新固件应该修复了

**Comment by dreamlandhl** [comment]
安装新固件后T68M网卡已经正常了，谢谢！




胡磊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "istoreos/istoreos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月24日(星期一) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [istoreos/istoreos] T68M安装固件22.03.4后网卡eth1不能识别，请修复。 (Issue #889)





 
最新固件应该修复了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2808/1
