### ISSUE TITLE
TrueNas Scale虚拟机无法启动iStoreOS

### ISSUE THREAD

**Issue by wssfxtx** [istoreos/istoreos#891]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：TrueNas Scale虚拟机无法启动iStoreOS

### (2) 路由器型号和固件版本

A：TrueNas Scale虚拟机基于KVM，内存分配2G，磁盘2G，虚拟virtio网卡

### (3) 详细日志和/或截图

A：[![pC7qcTO.jpg](https://s1.ax1x.com/2023/07/20/pC7qcTO.jpg)](https://imgse.com/i/pC7qcTO)

**Comment by jjm2473** [comment]
参考这里的kvm配置试试 https://github.com/istoreos/istoreos-kvm

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2807/1

**Comment by wssfxtx** [comment]
您的邮件已经收到，我将尽快回复，谢谢！
