### ISSUE TITLE
7/14 的更新版里没有终端入口，网络里防火墙设置也消失了。

### ISSUE THREAD

**Issue by shgfzx** [istoreos/istoreos#892]
7/14 的更新版里没有终端入口，网络里防火墙设置也消失了。

**Comment by jjm2473** [comment]
机型是什么，终端的问题当天就修复了，确定是最新版本？

**Comment by shgfzx** [comment]
我用的是 r4s 重启了下又好了。多谢！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2806/1
