### ISSUE TITLE
ISTOREOS-X86架构的安装zerotier显示缺少luci-lua-runtime这个依赖。想问一下这个要怎么解决的？

### ISSUE THREAD

**Issue by Tincichow** [istoreos/istoreos#896]
ISTOREOS-X86架构的安装zerotier显示缺少luci-lua-runtime这个依赖。想问一下这个要怎么解决的？

**Comment by jjm2473** [comment]
不要使用不兼容的软件源

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2804/1
