### ISSUE TITLE
是否可以支持ax210网卡

### ISSUE THREAD

**Issue by yeyu12** [istoreos/istoreos#897]
ax210网卡，无法识别

**Comment by yeyu12** [comment]
我的路由是h68k，硬件里面用的是mt7921，但是7921的wifi特别不稳定，一会可以，一会不行。自己购买了个ax210网卡，但是装上后，无法识别，不能正常工作。希望可以支持一下，ax210网卡

**Comment by jjm2473** [comment]
intel的网卡没什么卵用的，只能作为客户端，不能作为AP

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2803/1
