### ISSUE TITLE
更新日志 - 22.03.4 - 20230714

### ISSUE THREAD

**Issue by ChristianSSH** [istoreos/istoreos#900]
### Discussed in https://github.com/istoreos/istoreos/discussions/878

<div type='discussions-op-text'>

<sup>Originally posted by **jjm2473** July 14, 2023</sup>
# 应用：
* QuickStart：“终端”按钮支持TTYD的用户自定义端口和SSL配置
* iStore：新上架nps，airplay2
* 动态DNS：集成dnspod，3322.net

# 设备：
* x86_64：加回风扇控制界面（由于BIOS差异，不保证可用）
* R5S/R5C：修复LED灯
* H69K：修复初次启动可能没打开WIFI的问题</div>

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2801/1
