### ISSUE TITLE
1G版R4S刷入R4S 1G版升2023071416固件，无法进入系统

### ISSUE THREAD

**Issue by ChristianSSH** [istoreos/istoreos#901]
R4S 1G版刷入2023071416固件无法加载系统，数据灯和网口灯都不亮。
在线升级和重刷都试过不行，希望大佬关注一下谢谢

**Comment by jjm2473** [comment]
你是按教程刷的吗？确定是r4s，而不是其他版本的硬件？

r4s跟r2s是同时编译的，内核和uboot也是同一套，我测试过r2s时没问题的。

**Comment by chenleibj** [comment]
是的 R4S 1G版 我也刷了，数据灯 网口灯不亮，看来 istoreos不支持R4S1G版~~

**Comment by jjm2473** [comment]
有试过旧版本保留配置升级或者重做系统吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2800/1
