### ISSUE TITLE
ARS2是停止支持了吗？

### ISSUE THREAD

**Issue by relaydream** [istoreos/istoreos#908]
ARS2是停止支持了吗？我看官方淘宝店已经下架硬件，且iStoreOS版本也很久没有更新了。
如果停止了官方支持，那么下一代硬件什么时候上架呢？我们会继续购买支持官方的硬件的。

**Comment by jjm2473** [comment]
没有停止支持啊，只是进入维护期了，如果有bug还是会修。

**Comment by picc745514** [comment]
哈哈，正式成为备胎

**Comment by relaydream** [comment]
还会出新一代硬件吗

**Comment by jjm2473** [comment]
不知道什么时候才有，还是多关注koolcenter的团购吧

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2794/1
