### ISSUE TITLE
应用过滤通过上传的特征库，重启软路由之后就失效重置了

### ISSUE THREAD

**Issue by Ardin963** [istoreos/istoreos#909]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：之前通过应用过滤无法上传新的特征库，现在已在新版本更新中修复了，但是现在的问题是，上传的特征库能工作了，但是在重启软路由之后有恢复到原始版本

### (2) 路由器型号和固件版本

A：

HINLINK OPC-H68K/H69K Board
iStoreOS 22.03.4 2023071416

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
找插件的原作者

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2793/1
