### ISSUE TITLE
用苹果的Safari浏览器不能打开istore商店，无法加载内容

### ISSUE THREAD

**Issue by Ardin963** [istoreos/istoreos#910]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：用苹果的Safari浏览器打开路由器后台，不能打开istore商店
其他的都能正常打开，istore无法加载内容

### (2) 路由器型号和固件版本

A：设备型号
HINLINK OPC-H68K/H69K Board
固件版本
iStoreOS 22.03.4 2023071416

### (3) 详细日志和/或截图

A：
<img width="1440" alt="Screen Shot 2023-07-28 at 10 12 53 AM" src="https://github.com/istoreos/istoreos/assets/59965293/209f897a-410d-4b4b-8461-2eb77f23cfee">

**Comment by jjm2473** [comment]
恢复出厂设置，或者[重新安装istore](https://github.com/linkease/istore#%E5%AE%89%E8%A3%85-istore-%E5%88%B0-openwrt-%E5%AE%98%E6%96%B9%E5%9B%BA%E4%BB%B6)。实测safari没问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2792/1
