### ISSUE TITLE
启动显示root@(none)

### ISSUE THREAD

**Issue by lhliu1982** [istoreos/istoreos#911]
x86平台，今天突然不能驱动网卡，怎么安装都不行，之前还能偶尔成功驱动网卡i226-v。换到原版openwrt又没问题。
![Uploading 16905106832551977225872952030563.jpg…]()

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2791/1
