### ISSUE TITLE
root@(none)启动无网络

### ISSUE THREAD

**Issue by lhliu1982** [istoreos/istoreos#912]
x86平台，今天突然不能驱动网卡，怎么安装都不行，之前还能偶尔成功驱动网卡i226-v。换到原版openwrt又没问题。

**Comment by jjm2473** [comment]
发两个issue干嘛

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2790/1
