### ISSUE TITLE
登陆密码忘记

### ISSUE THREAD

**Issue by ilovetaimei** [istoreos/istoreos#914]
请问登陆密码怎么重置

**Comment by jjm2473** [comment]
如果是x86，可以用键盘显示器终端手动编辑密码文件。其他就只能恢复出厂设置了

**Comment by jjm2473** [comment]
其他设备如果你有ttl调试也可以手动修改密码文件

**Comment by wiketor** [comment]
> 请问登陆密码怎么重置
passwd root

**Comment by cornradio** [comment]
如果忘记留密码可以在命令行界面passwd 命令重置
记得要重启再生效

**Comment by jjm2473** [comment]
忘记密码还能进命令行界面？那还要这密码干嘛

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2789/1
