### ISSUE TITLE
transmission远程无法访问WEB管理页面，已经做了端口转发，不知是不是设置问题，请教

### ISSUE THREAD

**Issue by ssupssup** [istoreos/istoreos#915]
X64最新固件22.03.4 2023071416，想用transmission，发现远程无法访问WEB管理页面，已经做了端口转发，不知是不是设置问题，请教

**Comment by Skinsly** [comment]
今天刚升到22.03.5，安装完tr外网可以访问，发送一个任务马上无法连接了

**Comment by scrymile** [comment]
> 今天刚升到22.03.5，安装完tr外网可以访问，发送一个任务马上无法连接了

是的，我也是，只要添加一个下载任务立马打不开。感觉开发者自己也不用transmission，估计也没更新版本的计划。还是尽量催一催吧

**Comment by scrymile** [comment]
不是设置问题

**Comment by Skinsly** [comment]
用docker安装Tr4.0.3在挂上中文ui就能正常用了，暂时我就这么解决的

**Comment by scrymile** [comment]
> 

怎么弄的

**Comment by jjm2473** [comment]
如果添加任务，还没下载tr就挂掉，那么在系统日志里面搜一下transmission，把日志贴出来。如果是下载过程中页面卡住，可能只是在创建文件过程中卡住了，等文件创建完就会恢复，如果是直接断线，那也是一样把日志贴出来。

**Comment by jjm2473** [comment]
我还在使用3.00呢，能有啥问题
<img width="1370" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/9b82f741-8cd5-4b2f-a929-6796bbc0c1f8">

**Comment by jjm2473** [comment]
transmission使用的是openwrt官方的版本，如果真有问题，openwrt的社区应该早就很多人反馈了。
如果你们是因为之前的固件就安装了tr，导致版本不是最新的，那么卸载重装一次tr试试。

**Comment by jjm2473** [comment]
你们是不是没注意权限问题，如果使用已存在的配置文件目录或下载目录，要注意权限问题，如果不想研究权限问题的话，可以在iStoreOS后台的transmission的配置页面的“全局配置”中，将“用户权限”和“组权限”都改成`root`，应该就没问题了。

权限问题在系统日志中都会提醒，早点看日志的话早就解决了。

**Comment by jjm2473** [comment]
还有，不要把下载路径或临时文件路径设置到/tmp或/run，这两个是内存，要是把大文件下载到这里，肯定会导致系统死机。

**Comment by jjm2473** [comment]
我将一台x86升级到最新固件，然后重新安装transmission，然后使用首页的配置，分别选择两个不存在的文件夹，配置以后就自动启动了tr，然后添加磁力链接下载，没问题。
<img width="1439" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/ecabf3b2-b293-4ba3-a777-24e9d917b95d">

如果要使用已存在的文件夹，又不确定文件夹权限是否正确，那就按前面说的将“用户权限”和“组权限”都改成`root`。

**Comment by scrymile** [comment]
> 我将一台x86升级到最新固件，然后重新安装transmission，然后使用首页的配置，分别选择两个不存在的文件夹，配置以后就自动启动了tr，然后添加磁力链接下载，没问题。 <img alt="image" width="1439" src="https://user-images.githubusercontent.com/3896703/258144309-ecabf3b2-b293-4ba3-a777-24e9d917b95d.png">
> 
> 如果要使用已存在的文件夹，又不确定文件夹权限是否正确，那就按前面说的将“用户权限”和“组权限”都改成`root`。

Mon Aug 14 02:14:58 2023 daemon.err transmission-daemon[5303]: [2023-08-13 18:14:58.862] Couldn't save file "/root/Configs/transmission/settings.json": Resource busy (variant.c:1226)

日志这么提示。

附上别人也碰到了这个问题https://github.com/openwrt/packages/issues/19376

**Comment by jjm2473** [comment]
你链接的issue不是说了不影响运行吗？总之就是改成root

**Comment by scrymile** [comment]
> 你链接的issue不是说了不影响运行吗？总之就是改成root

改成root，依然无法下载，下载的那个网页都打不开.....    pt站内也没显示我的Transmission有链接。。

**Comment by scrymile** [comment]
web界面都打不开，怎么可能没问题哦

**Comment by jjm2473** [comment]
那就看看系统日志，或者恢复出厂设置以后重新配置看能不能复现

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2788/1
