### ISSUE TITLE
更新20230728固件失败，无法正常启动

### ISSUE THREAD

**Issue by V1V1rus** [istoreos/istoreos#919]
## 1.关于你要提交的问题

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

有类似，但出现在去年，无参考意义

### (1) 具体问题

更新20230728版本失败，重启控制台显示

clocksurce:switched to clocksource tsc

### (2) 路由器型号和固件版本
畅网N5105，ESXI8.0，20230717
A：

### (3) 详细日志和/或截图
![image](https://github.com/istoreos/istoreos/assets/42931451/4667d8a4-1165-44a5-bebb-4cd9cc477349)

**Comment by jjm2473** [comment]
实际上是卡在`Waitting for root device...`，估计是升级过程断电或其他异常导致uuid没更新，重做系统就行了。如果想备份以前的用户数据，可以用另一个虚拟盘做系统启动，进系统以后把之前的磁盘的第三个分区备份出来。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2786/1
