### ISSUE TITLE
x86物理机能支持哪种型号pcie无线网卡？

### ISSUE THREAD

**Issue by 319293013** [istoreos/istoreos#921]
x86物理机能支持哪种型号pcie无线网卡？

**Comment by jjm2473** [comment]
mt7916/mt7921等，可以自己用`lsmod`查看已经安装的驱动。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2785/1
