### ISSUE TITLE
可以加上BCM57810S的2.5G补丁吗?

### ISSUE THREAD

**Issue by Jimzjy** [istoreos/istoreos#924]
https://github.com/coolsnowwolf/lede/blob/master/target/linux/x86/patches-5.10/993-bnx2x_warpcore_8727_2_5g_sgmii_txfault.patch

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2782/1
