### ISSUE TITLE
ARP路由表在线，但是实际上已经离线，ping不通

### ISSUE THREAD

**Issue by binfoo** [istoreos/istoreos#926]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ *] 没有类似的issue

## 2. 详细叙述

路由表中设备还在线，首页也显示4个设备，但是实际上192.168.100.128是离线的

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
![image](https://github.com/istoreos/istoreos/assets/18188540/10d364e7-12b3-4f1f-bc35-3a753a3c93e4)

A：

### (3) 详细日志和/或截图
![image](https://github.com/istoreos/istoreos/assets/18188540/13a7684f-8d85-4efc-af9f-61e99988ede1)

![image](https://github.com/istoreos/istoreos/assets/18188540/b41c22eb-89e7-4d67-b7ad-07998fe1deb2)

A：

**Comment by jjm2473** [comment]
ARP表有自己的刷新机制。设备下线难道还会主动通知路由器？肯定是有延迟的啊

**Comment by binfoo** [comment]
为啥延迟半天多？arp默认刷新不是30s吗？

**Comment by jjm2473** [comment]
那你就抓包看看为什么arp记录还能维持

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2781/1
