### ISSUE TITLE
建议添加 nginx 作为默认 web服务器 的版本

### ISSUE THREAD

**Issue by draco-china** [istoreos/istoreos#928]
目前已经自定义编译成功，不过还在尝试编译修改其他功能

以下是 移除 uhttpd 并使用 nginx 作为默认服务器代码 已经测试正常运行 仅供参考
https://github.com/draco-china/customize-istoreos-actions/blob/main/diy-part2.sh

**Comment by jjm2473** [comment]
为了避免出现兼容性问题，我们不会修改默认的web服务，如果有需要可以自己安装nginx，也没什么难度

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2780/1
