### ISSUE TITLE
加载大量节点列表时，左侧菜单栏显示不全及加载过慢

### ISSUE THREAD

**Issue by ccwctv** [istoreos/istoreos#931]
* [ ] 没有类似的issue

### (1) 具体问题

- 加载大量节点列表时，UI界面显示不全及加载过慢，加载完所有节点之前，左侧菜单栏显示不全；
- 比之前用其他固件慢几秒钟（总耗时>5s），之前其他固件加载过程中左侧菜单显示完全，且很快就加载完成；
- 用passwall时发现，换用其他版本passwall或ssr-plus后，情景复现

### (2) 路由器型号和固件版本

- 型号：J4105
- 固件版本：iStoreOS 22.03.5 2023072811 / LuCI istoreos-22.03 branch git-23.103.23275-0193674

### (3) 详细日志和/或截图
<img width="1920" alt="chrome_4KJumbanAo" src="https://github.com/istoreos/istoreos/assets/124767347/fc5fd82a-43a3-4ba0-9656-ec2d6f2f79cc">
<img width="1920" alt="chrome_imy31oREAn" src="https://github.com/istoreos/istoreos/assets/124767347/e0f4c778-abfb-46a7-ad14-2ffeae722c73">

**Comment by jjm2473** [comment]
因为passwall还在使用服务端渲染，也就是旧版的luci，肯定会出现这个问题，不管你用什么固件。

**Comment by ccwctv** [comment]
> 因为passwall还在使用服务端渲染，也就是旧版的luci，肯定会出现这个问题，不管你用什么固件。

了解了，感谢解惑

更新下，不只是passwall有这问题，ssrplus和bypass都有这问题
之前用其他固件，没有这样的问题

**Comment by jjm2473** [comment]
那你试试openwrt官方的固件，19以上的版本

**Comment by ccwctv** [comment]
> 那你试试openwrt官方的固件，19以上的版本

现在换esir的最新固件，没有这个问题，OpenWrt R23.7.7，内核5.15.122

**Comment by jjm2473** [comment]
跟内核和固件版本无关，只跟luci版本有关。国内很多固件作者还是使用luci17版呢
