### ISSUE TITLE
网络存储菜单整个消失

### ISSUE THREAD

**Issue by makerdegit** [istoreos/istoreos#933]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：istore很早之前就在线更新完之后网络存储这一个大选项就没了

### (2) 路由器型号和固件版本

A：x86物理机 
iStoreOS 22.03.5 2023080410

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/122148963/c6c1b01d-3aee-4a85-9cb4-480af13c691e)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2777/1
