### ISSUE TITLE
5.10内核缺失kmod-r8168，8111网卡wan口下行异常

### ISSUE THREAD

**Issue by tuntun2019** [istoreos/istoreos#935]
### (1) 具体问题

A：最新几个版本升级5.10内核后缺失kmod-r8168驱动，8111网卡速度很慢，wan下行速度异常上行正常。退回5.4内核最后版本正常。经过对比，5.10版本缺失kmod-r8168驱动

### (2) 路由器型号和固件版本

A：
问题版本为iStoreOS 22.03.5 2023080410  X86，正常版本为iStoreOS 21.02.3 2023060914   X86
两个版本均为efi版本

### (3) 详细日志和/或截图

A：老版本内核日志
1、[    8.831322] r8168 Gigabit Ethernet driver 8.051.02-NAPI loaded
有此 网络wan口下行正常
新版本缺失驱动无。
2、iStoreOS 21.02.3 2023060914   X86 可以在软件包搜索到已安装 
kmod-r8168 | 5.4.188+8.051.02-1
3、老版本 ethtool -i eth0 打印如下：
firmware-version:
expansion-rom-version:
bus-info: 0000:02:00.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
新版本为8169驱动，提示驱动为rk8169，实测能正常获取地址，但是wan口下行异常。此问题影响采用螃蟹8111网卡族的软路由

以上，请小宝大大将R8168驱动编译进最新版本

**Comment by jjm2473** [comment]
参考 https://github.com/istoreos/istoreos/issues/904

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2776/1
