### ISSUE TITLE
h68k的0804固件升级后被识别为h66k，导致两个网口不能用

### ISSUE THREAD

**Issue by mzl0408** [istoreos/istoreos#936]
用的固件的在线升级功能，升级0804固件后两个网口不能用了，一看被识别为h66k了，希望尽快修复。

**Comment by jjm2473** [comment]
估计又是硬件版本不一致导致的，自己联系硬件厂商解决。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2775/1
