### ISSUE TITLE
重启路由器后密码错误无法登陆

### ISSUE THREAD

**Issue by levis0792** [istoreos/istoreos#937]
## 2. 详细叙述
应该是安装baidu网盘插件 登陆下载后 重启路由器现实密码错误 无法登陆路由器
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：x86 3215

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
要么文件损坏了，要么被病毒攻击了。之前是默认密码吗？有没有开放ssh到外网？
