### ISSUE TITLE
DHCP/DNS 常规设置那个dns转发修改了端口没有用

### ISSUE THREAD

**Issue by 1764364648** [istoreos/istoreos#938]
## 1.关于你要提交的问题
DHCP/DNS 常规设置那个dns转发修改了没有用我修改了从7874端口修改成5553端口过一会就变成默认的7874端口了

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：我要使用AdGuard Home所以我去就修改端口修改成5553然后过了一会我打开AdGuard Home的网页管理页面就发就一条dns记录然后我就去查原因我去就DHCP/DNS看了一下发现端口被自动改成默认的7874端口了然后我又了5 6次都没有用都会自动的改会来默认的端口

### (2) 路由器型号和固件版本

A：x86 固件版本号是
iStoreOS 22.03.5 2023080410

### (3) 详细日志和/或截图

A：

**Comment by 1764364648** [comment]
![ea2619cbebf8cfd28ffa7f4550c4c0b4](https://github.com/istoreos/istoreos/assets/123971622/497b1f30-ee9c-4a4a-aff8-fb32a38dd9b5)

**Comment by jjm2473** [comment]
那估计是adguard改的，跟固件无关

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2774/1
