### ISSUE TITLE
DHCP IP地址池无法自定义

### ISSUE THREAD

**Issue by CMEPCBHG** [istoreos/istoreos#939]
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [X] 没有类似的issue

## 2. 详细叙述
使用 iStoreX-网络配置-内网配置 设置IP地址池起止地址时，会一直卡在“正在配置，请稍等...”的提示中，无法生效。

### (1) 具体问题

A：使用 iStoreX-网络配置-内网配置 设置IP地址池起止地址时，会一直卡在“正在配置，请稍等...”的提示中，无法生效。

### (2) 路由器型号和固件版本

A：x86 20230804版本固件

### (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/68275129/369c6475-7ad1-4de2-a697-3c25cfc3f25f)

**Comment by jjm2473** [comment]
可以先用网络-接口那边的lan配置

**Comment by CMEPCBHG** [comment]
> 可以先用网络-接口那边的lan配置

OK，不过这个问题也可以跟进解决一下，毕竟也算一个比较基础的功能BUG了。

**Comment by jjm2473** [comment]
我测试了没问题。 按这里的第2点修复试试 https://github.com/istoreos/istoreos/wiki/FAQ

**Comment by jjm2473** [comment]
等下，这是istorex？不是首页的配置？

**Comment by jjm2473** [comment]
istorex的问题自己找作者吧

**Comment by jannson** [comment]
帮看看首页的配置是否成功。如果是 iStoreX 应该只是个皮肤，出问题应该都出问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2773/1
