### ISSUE TITLE
请求istoreos团队的大佬们，x86架构的固件集成intel n100和intel n305核显驱动。

### ISSUE THREAD

**Issue by wuyufeng1989** [istoreos/istoreos#942]
请求istoreos团队的大佬们，x86架构的固件集成intel n100和intel n305核显驱动。

**Comment by jjm2473** [comment]
等openwrt上游发布23.05以后，我们才有可能升级内核，才能支持

**Comment by jjm2473** [comment]
这里有测试固件了 https://github.com/istoreos/istoreos/issues/965

**Comment by wuyufeng1989** [comment]
> 这里有测试固件了 #965

感谢各位辛苦付出

**Comment by jjm2473** [comment]
正式版固件也支持了，升级以后参考这个文章设置下 https://github.com/istoreos/istoreos/discussions/1022

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2771/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2772/2
