### ISSUE TITLE
x86  点击了一下挂载点 就不能进入路由器后台了

### ISSUE THREAD

**Issue by shiyuanGame** [istoreos/istoreos#943]
反馈bug/问题模板，提建议请删除
x86  点击了一下挂载点 就不能进入路由器后台了
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
j4125 最新版 x86固件
A：

### (3) 详细日志和/或截图
![8983d8d47939a6501b5167bd9495d07](https://github.com/istoreos/istoreos/assets/80084199/3bf3cae6-5b56-42d6-b2ea-95b3868951cb)

A：

**Comment by jjm2473** [comment]
后退就行了。这个错误估计是文件损坏或者安装了错误的软件，查看wiki的FAQ修复系统组件试试，还不行就只能恢复出厂设置了

**Comment by shiyuanGame** [comment]
原来是硬盘挂了 后来又买了一块硬盘 ok了> 后退就行了。这个错误估计是文件损坏或者安装了错误的软件，查看wiki的FAQ修复系统组件试试，还不行就只能恢复出厂设置了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2770/1
