### ISSUE TITLE
同一文件管理挂载的webdav无法重命名文件夹或者在其中另存文件

### ISSUE THREAD

**Issue by CG1995** [istoreos/istoreos#944]
Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x ] 没有类似的issue

2. 详细叙述

(1) 具体问题

A：同一文件管理挂载硬盘后，无法在这个挂载盘里重命名文件夹，比如在windows上显示：操作无法完成，因为其中的文件夹或文件已在另一程序中打开，我很确定我没有在别的地方打开这个文件夹，文件夹是新建的还热乎

 (2) 路由器型号和固件版本

A：r5s和r5c

 (3) 详细日志和/或截图

A：
![image](https://github.com/istoreos/istoreos/assets/21087049/f668ef8c-8422-4c11-a556-793396843a99)

**Comment by jjm2473** [comment]
建议使用samba，webdav不适合写

**Comment by CG1995** [comment]
> 建议使用samba，webdav不适合写

samba无法外网挂载，我看我的nas还有alist挂载的webdav都能正常读写，是不是我哪里设置的不对造成的

**Comment by jjm2473** [comment]
samba其实是可以外网挂载的，只是可能要端口转发，还有挂载的时候需要指定端口和共享文件夹名称，而不是只填服务器地址

**Comment by CG1995** [comment]
> samba其实是可以外网挂载的，只是可能要端口转发，还有挂载的时候需要指定端口和共享文件夹名称，而不是只填服务器地址

原来如此，十分感谢哈！

**Comment by 1klakla1** [comment]
> samba其实是可以外网挂载的，只是可能要端口转发，还有挂载的时候需要指定端口和共享文件夹名称，而不是只填服务器地址

大佬，0825版本的固件 samba 有BUG，播放视频几分钟就卡掉挂在，必须重启路由才能解决。然后无限循环。

**Comment by jjm2473** [comment]
@1klakla1 上一版本没问题吗？

**Comment by 1klakla1** [comment]
iStoreOS 21.02.3 2023042111
我上一个版本用的是这个版本号，没有问题。
更新了固件就出问题了，然后我就回滚快照了。测试了好几遍确定是新固件导致的。

**Comment by 1klakla1** [comment]
iStoreOS 21.02.3 2023042111
我上一个版本用的是这个版本号，没有问题。
更新了固件就出问题了，然后我就回滚快照了。测试了好几遍确定是新固件导致的。

**Comment by jjm2473** [comment]
@1klakla1 不保留配置升级试过吗

**Comment by 1klakla1** [comment]
iStoreOS 21.02.3 2023042111
我上一个版本用的是这个版本号，没有问题。
更新了固件就出问题了，然后我就回滚快照了。测试了好几遍确定是新固件导致的。

不保留配置升级还没试过，我明天测试反馈.

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2769/1
