### ISSUE TITLE
IT8655E等IT86传感器驱动缺失

### ISSUE THREAD

**Issue by KamisatoAyaka0v0** [istoreos/istoreos#946]
现版本无法读取IT86系列传感器 cpu温度均无法显示 软件源内只包含IT87系列驱动 望添加

**Comment by jjm2473** [comment]
IT86是什么机型用的？

**Comment by KamisatoAyaka0v0** [comment]
> IT86是什么配件用的？

x86平台主板 intel300系列 和amd am4低端主板 用的是这个传感器

**Comment by jjm2473** [comment]
原版的openwrt有这个驱动吗，或者原版openwrt从软件包那边能不能安装到

**Comment by jjm2473** [comment]
从软件包安装 `kmod-hwmon-it87` 看能不能用，没看到内核有 IT8655 相关的文本

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2767/1
