### ISSUE TITLE
迅雷下载无法配置多个下载路径

### ISSUE THREAD

**Issue by xmasrain** [istoreos/istoreos#948]
1.问题：istoreos中的docker应用迅雷下载，在配置“下载路径”的时候只能填写一个路径，这对于有多个盘符的用户则无法使用，若强行把路径设置为“/mnt”，则到应用中会仅识别为4M大小的空间，无法下载任何文件。

Q：是否用关键词搜索了issue? (使用 "x" 选择)
A：没有类似的issue

2. 详细叙述

istoreos中的docker应用迅雷，在配置“下载路径”的时候只能填写一个路径，这对于有多个盘符的用户则无法使用，若强行把路径设置为“/mnt”，则到应用中会仅识别为4M大小的空间，无法下载任何文件。

(2) 路由器型号和固件版本

A：设备型号
GEIT UT3000F
固件版本
iStoreOS 22.03.5 2023080410
内核版本
5.10.176

 (3) 详细日志和/或截图
![WeChat截图_20230811162740](https://github.com/istoreos/istoreos/assets/58833842/01253e53-87dc-43df-a51d-cba80239a752)
![WeChat截图_20230811163508](https://github.com/istoreos/istoreos/assets/58833842/6435da13-a80b-4ef5-9d40-e84b76f473f1)

**Comment by jjm2473** [comment]
说明你的/mnt/nas8t根本没挂载啊，要么就是迅雷启动时还没挂载，可以在系统-杂项设置里面配置等待硬盘

**Comment by llonline** [comment]
我也碰到同样问题。硬盘已经挂载了，但是就是无法使用。之前一直好的，但是怎么操作的已经忘记了，换了一块大硬盘，就不行了。

**Comment by jjm2473** [comment]
杂项设置里面配置等待硬盘

**Comment by lff110** [comment]
不行就重启一下设备也可以

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2766/1
