### ISSUE TITLE
UU加速器获取不到SN

### ISSUE THREAD

**Issue by a447948814** [istoreos/istoreos#952]
UU加速器无法使用，商店装的、官方脚本安装的都不行，获取不到SN=。，br-lan桥接也打开了。之前正常的。。现在手机端app可以绑定路由，也可以识别设备，但是点击加速就提示路由器网络组件初始化失败，应该就是获取不到SN导致的，麻烦大佬看一下啥问题

<img width="531" alt="9f47fb6a27b23cf3ea02da5608b7a83" src="https://github.com/istoreos/istoreos/assets/61766946/075ec1cf-d0f3-4b5d-a05c-608cde5e3630">

![image](https://github.com/istoreos/istoreos/assets/61766946/8b3847c7-91a7-423c-b301-3610042b0af3)

![32dd0fa8b59fb97c14836f50e57273a](https://github.com/istoreos/istoreos/assets/61766946/6bccc7ad-551f-4226-b24d-bbf52a4c16cc)

**Comment by a447948814** [comment]
关了吧 是我的问题，重置设置就好了。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2762/1
