### ISSUE TITLE
就是两台电脑都打开一台电脑打游戏就会卡

### ISSUE THREAD

**Issue by 1764364648** [istoreos/istoreos#954]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
就是两台电脑都打开一台电脑打游戏就会卡
### (1) 具体问题

A：就是两台电脑都打开一台电脑打游戏就会卡不管另外一台电脑在干嘛就算是另外一台电脑开机什么都不卡另外一台电脑打游戏也会卡要关机一台另外一台才不好卡我之前刷的的openwrt固件都没有这个问题刷到iStoreOS固件才有这个问题的麻烦iStoreOS团队解决一下这个问题

### (2) 路由器型号和固件版本

A：架构x86 固件版本22.03.5 2023081110

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
不知道什么问题，检查下电脑是不是ip冲突了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2760/1
