### ISSUE TITLE
新系统R2C报错

### ISSUE THREAD

**Issue by FSDXC111** [istoreos/istoreos#955]
貌似是多了一个符号，麻烦改一
<img width="846" alt="bug" src="https://github.com/istoreos/istoreos/assets/128386077/ce2eb4a6-e39d-4dd4-9ef9-6166ff2366fb">

下

**Comment by jjm2473** [comment]
确定不是浏览器问题？

**Comment by FSDXC111** [comment]
> 确定不是浏览器问题？

哪个浏览器都一样

**Comment by jjm2473** [comment]
你使用了nginx或者其他的web服务吗

**Comment by jjm2473** [comment]
你是在内网访问的吗，还是外网通过代理访问的？恢复出厂设置以后有没有这个问题？

**Comment by jjm2473** [comment]
我用r2s测试了，没有任何问题，还特意安装nginx测试了。r2s跟r2c是同一个固件。你遇到的问题肯定是因为使用了代理或者内网穿透之类的东西，又没透传404响应

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2759/1
