### ISSUE TITLE
D525 CPU温度为0

### ISSUE THREAD

**Issue by kbdancer** [istoreos/istoreos#956]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：首页CPU温度一直为0

### (2) 路由器型号和固件版本

A：路由器型号 To be filled by O.E.M. To be filled by O.E.M.
B：CPU 型号 Intel(R) Atom(TM) CPU D525 @ 1.80GHz （x86）
C：固件版本号 iStoreOS 22.03.5 2023081110 / LuCI istoreos-22.03 branch git-23.103.23275-0193674

### (3) 详细日志和/或截图

A：
![深度截图_选择区域_20230814120043](https://github.com/istoreos/istoreos/assets/3382693/1e625ccd-a040-437b-bf31-8b823d904344)
![深度截图_选择区域_20230814120100](https://github.com/istoreos/istoreos/assets/3382693/a650e9f0-0336-4286-b24a-a194b7bffc9e)

**Comment by jjm2473** [comment]
有些CPU没有温度传感器，很正常。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2758/1
