### ISSUE TITLE
R5S软件源修改后重启会还原默认清华源

### ISSUE THREAD

**Issue by ChengZhiDan** [istoreos/istoreos#957]
R5S软件源修改后重启会还原默认清华源

**Comment by jjm2473** [comment]
使用杂项设置那边的修改

**Comment by ChengZhiDan** [comment]
> 
杂项设置里面改过，首页软件源设置重启会还原默认清华源。

**Comment by jjm2473** [comment]
就不要用首页的配置了，而且应该也不是因为重启，而是因为升级固件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2757/1
