### ISSUE TITLE
求助Docker被弄成这个样子了有什么办法可以恢复原样吗

### ISSUE THREAD

**Issue by 1764364648** [istoreos/istoreos#958]
![b8ce79bb3a832497508efd09e3948060](https://github.com/istoreos/istoreos/assets/123971622/f66c7e2b-0929-4c84-b791-84f2bedd848f)
被弄成了这样有谁知道怎么恢复原来的样子吗

**Comment by rootphantomer** [comment]
![image](https://github.com/istoreos/istoreos/assets/6481352/f03d3ddd-ceaf-481a-bdaf-3d72af03cff6)
首页的这个开关打开，再去看看

**Comment by jjm2473** [comment]
看系统日志为什么dockerd无法启动

**Comment by 1764364648** [comment]
daemon.err dockerd[12532]: time="2023-08-18T17:12:23Z" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
Sat Aug 19 01:12:23 2023 daemon.err modprobe: failed to find a module named aufs
Sat Aug 19 01:12:23 2023 daemon.err dockerd[12532]: time="2023-08-18T17:12:23.500267425Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
Sat Aug 19 01:12:23 2023 daemon.err dockerd[12532]: time="2023-08-18T17:12:23.502166959Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
Sat Aug 19 01:12:23 2023 daemon.err dockerd[12532]: time="2023-08-18T17:12:23.516063336Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
Sat Aug 19 01:12:23 2023 daemon.err dockerd[12532]: time="2023-08-18T17:12:23.592612134Z" level=error msg="failed to mount overlay: invalid argument" storage-driver=overlay2
Sat Aug 19 01:12:23 2023 daemon.err dockerd[12532]: time="2023-08-18T17:12:23.593080794Z" level=error msg="[graphdriver] prior storage driver overlay2 failed: driver not supported"
Sat Aug 19 01:12:23 2023 kern.err kernel: [22125.779880] overlayfs: filesystem on '/opt/docker/overlay2/check-overlayfs-support3355764298/upper' not supported as upperdir
Sat Aug 19 01:12:24 2023 daemon.err dockerd[12532]: failed to start daemon: error initializing graphdriver: driver not supported
Sat Aug 19 01:12:40 2023 daemon.err dockerd[12894]: time="2023-08-18T17:12:40Z" level=warning msg="containerd config version `1` has been deprecated and will be removed in containerd v2.0, please switch to version `2`, see https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header"
Sat Aug 19 01:12:40 2023 daemon.err modprobe: failed to find a module named aufs
Sat Aug 19 01:12:40 2023 daemon.err dockerd[12894]: time="2023-08-18T17:12:40.355022021Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.devmapper" error="devmapper not configured"
Sat Aug 19 01:12:40 2023 daemon.err dockerd[12894]: time="2023-08-18T17:12:40.356981233Z" level=warning msg="could not use snapshotter devmapper in metadata plugin" error="devmapper not configured"
Sat Aug 19 01:12:40 2023 daemon.err dockerd[12894]: time="2023-08-18T17:12:40.366803763Z" level=error msg="failed to initialize a tracing processor \"otlp\"" error="no OpenTelemetry endpoint: skip plugin"
Sat Aug 19 01:12:40 2023 daemon.err dockerd[12894]: time="2023-08-18T17:12:40.418888693Z" level=error msg="failed to mount overlay: invalid argument" storage-driver=overlay2
Sat Aug 19 01:12:40 2023 daemon.err dockerd[12894]: time="2023-08-18T17:12:40.419048106Z" level=error msg="[graphdriver] prior storage driver overlay2 failed: driver not supported"
Sat Aug 19 01:12:40 2023 kern.err kernel: [22142.608492] overlayfs: filesystem on '/opt/docker/overlay2/check-overlayfs-support2265559195/upper' not supported as upperdir
Sat Aug 19 01:12:41 2023 daemon.err dockerd[12894]: failed to start daem  这是日志

**Comment by jjm2473** [comment]
你的docker数据目录是自己改的吗？默认肯定不是这个，恢复出厂设置

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2756/1
