### ISSUE TITLE
R4S 更新以后无法进入管理界面

### ISSUE THREAD

**Issue by Mickpennn** [istoreos/istoreos#959]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：R4S 升级以后无法进入管理界面

### (2) 路由器型号和固件版本

A：R4S [istoreos-22.03.5-2023080410-r4s-squashfs.img.gz](https://fw0.koolcenter.com/iStoreOS/r4s/istoreos-22.03.5-2023080410-r4s-squashfs.img.gz)

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
如果使用了nginx，那么需要用命令重装nginx，搜一下issue，有提到

如果不是nginx，那么恢复出厂设置或者重刷看看还有没有问题

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2755/1
