### ISSUE TITLE
手动安装design主题后报错

### ISSUE THREAD

**Issue by wangqingyuan233** [istoreos/istoreos#961]
如题，安装并使用design主题后报错，并无法访问luci页面。

以下为报错内容：
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'sysauth'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'header'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'themes/design/header'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/themes/design/header..."]:25: attempt to call field 'node_childs' (a nil value)
stack traceback:
	[string "/usr/lib/lua/luci/view/themes/design/header..."]:25: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:700: in function 'include'
	[string "/usr/lib/lua/luci/view/header.htm"]:3: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:700: in function 'include'
	[string "/usr/lib/lua/luci/view/sysauth.htm"]:1: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function </usr/lib/lua/luci/template.lua:85>
	(tail call): ?
	(tail call): ?
	/usr/lib/lua/luci/dispatcher.lua:483: in function </usr/lib/lua/luci/dispatcher.lua:482>

**Comment by jjm2473** [comment]
应该让主题来适配。你用的固件什么版本，相应版本的openwrt能用这个主题吗？

**Comment by xiehuc** [comment]
design 选择 js 分支安装

**Comment by xiehuc** [comment]
<img width="2331" alt="截屏2024-07-20 12 26 53" src="https://github.com/user-attachments/assets/8d778e0a-88d8-49ce-806a-0115607a529d">

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2754/1
