### ISSUE TITLE
esxi 8 系统中安装会发生连续报错信息，重启后能好一段时间，好像是网卡掉驱动，没有发现解决方法

### ISSUE THREAD

**Issue by PWMFI** [istoreos/istoreos#964]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
esxi 8 系统中安装会发生连续报错信息，重启后能好一段时间，好像是网卡掉驱动，没有发现解决方法
### (1) 具体问题

A：

### (2) 路由器型号和固件版本
虚拟机运行，设备型号
VMware, Inc. VMware20,1
固件版本
iStoreOS 22.03.5 2023081110
内核版本
5.10.176
A：

### (3) 详细日志和/或截图
![5eb194370cdd72eaa720c5c2db5ea75](https://github.com/istoreos/istoreos/assets/63692121/08e8f04f-e8ce-49bf-967a-4fd83435ed93)

A：

**Comment by PWMFI** [comment]
N5105 机器，直通了网卡（2.5g网卡），以前的版本没出现过这个问题

**Comment by jjm2473** [comment]
要不试试使用万兆的虚拟网卡？跟物理网卡桥接就行了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2751/1
