### ISSUE TITLE
自动掉速

### ISSUE THREAD

**Issue by Stark-Chen** [istoreos/istoreos#966]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：拨号模式下运行几天之后就会自动掉速，从千兆掉到400~600，死活上不上来。遇到多次，只有重启iStore系统才能恢复正常，已排除其他设备的影响。

### (2) 路由器型号和固件版本

A：X86 N4100   iStoreOS 22.03.4 2023071416

### (3) 详细日志和/或截图

A：
![Screenshot_20230819_204949_com knowyou perception_edit_167356689036](https://github.com/istoreos/istoreos/assets/67217528/f9bad6d9-87f1-4bf8-bbe3-c704c57cbf05)
已经重启没有日志保存

**Comment by jjm2473** [comment]
有没有使用网心云之类的边缘计算？
