### ISSUE TITLE
内网速度不达标

### ISSUE THREAD

**Issue by qq253044370** [istoreos/istoreos#967]
详细叙述

 (1) 具体问题:内网速度不达标。上游路由A也是X86 I5-7500 iStoreOS 22.03.4 2023071416。用iperf3测试。从下游路由到上游路由速度2.37G，达标。电脑到下游路由iperf3 2.34G 也达标。。但是电脑到上游主路由 2.17G。速度损失了不少。。这是为啥？
难道过了一道路由速度损失那么多？

 (2) 路由器型号和固件版本:上游路由A--X86 I5-7500 iStoreOS 22.03.4 202307141。下游路由B--X86 N100 iStoreOS 22.03.4 2023071416
左图是下游路由到主路由。右边图是电脑通过下游路由到主路由的测速。
![有度20230820153931](https://github.com/istoreos/istoreos/assets/36876485/d9cecade-b9fa-4071-8db3-755ad8a29bd4)

**Comment by jjm2473** [comment]
从2.3降到2.1，这能有多少？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2750/1
