### ISSUE TITLE
gogs重启后需要重新初始化

### ISSUE THREAD

**Issue by houhai2049** [istoreos/istoreos#973]
使用istore中的gogs插件

使用istore中的gogs插件，每次重启都会需要重新初始化，重启容器后正常;

使用的是天宝AMD 300U的4口软路由，系统安装在nvme中，还有2个盘做了raid1，数据放在了raid1的盘中

**Comment by jjm2473** [comment]
是不是配置的数据目录有问题？设备重启以后是不是只需要重启容器就能恢复正常，还是说必须要重新初始化以后才能恢复？

**Comment by houhai2049** [comment]
重启设备后gogs进入初始化页面，再重启容器后恢复正常，使用sqlite和MySQL都是这样；数据放在了2盘的raid盘中，如果放置在nvme中重启设备时正常的

**Comment by jjm2473** [comment]
OK，那可能是因为raid初始化比较慢，docker启动时还没挂载好。

打开后台页面，系统-杂项设置-启动，里面可以选择等待硬盘分区，分区可以选择raid分区或者raid格式化以后的分区，还可以配置最长等待时间。如果不知道选哪个分区，也可以留空，这样就纯粹倒计时而已。
至于怎么计算合适的最长等待时间，可以从系统日志估算出来，也就是开始出现docker日志到出现你的raid分区挂载的这段时间。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2744/1
