### ISSUE TITLE
更新固件后无法使用iStore opkg报错 Segmentation fault

### ISSUE THREAD

**Issue by break123aqwq** [istoreos/istoreos#975]
## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ X] 没有类似的issue

## 2. 详细叙述
更新固件后无法使用iStore opkg报错
更新失败: Segmentation fault
### (1) 具体问题
A：
<img width="1265" alt="image" src="https://github.com/istoreos/istoreos/assets/142923114/0ce328d6-02a6-46c8-85ed-c25d90e7a22b">
<img width="759" alt="image" src="https://github.com/istoreos/istoreos/assets/142923114/2ebe69cd-15df-4540-b103-dad392b0b6af">
任何操作都会提示 Segmentation fault
重启后以及升级最新固件都无法解决问题
### (2) 路由器型号和固件版本
A：
<img width="358" alt="image" src="https://github.com/istoreos/istoreos/assets/142923114/ee4ea208-3038-4d66-8903-a3c07a048710">

### (3) 详细日志和/或截图
A：

**Comment by break123aqwq** [comment]
<img width="387" alt="image" src="https://github.com/istoreos/istoreos/assets/142923114/1755b872-7f74-4f79-a084-616bceb8ef69">

**Comment by break123aqwq** [comment]
<img width="1500" alt="image" src="https://github.com/istoreos/istoreos/assets/142923114/dda41cc5-6007-40b6-b320-827d5abab271">

**Comment by jjm2473** [comment]
你是不是添加了非x86的软件源？
