### ISSUE TITLE
istore内安装的时间界面是英文

### ISSUE THREAD

**Issue by AKKIRR** [istoreos/istoreos#976]
安装的软件都是英文的，openclash一开始也是英文但是重置了一下openclash的设置就变成中文了
![image](https://github.com/istoreos/istoreos/assets/63959900/c12ad7fc-8071-4748-9566-641417163af6)

**Comment by AKKIRR** [comment]
后面重新刷了系统再安装又是中文的了 不知道是不是因为是开着openclash代理安装的原因所以是英文

**Comment by quentinztq** [comment]
我也有这样的问题，而且频繁出现
