### ISSUE TITLE
多 Wan 出现防火墙失效问题

### ISSUE THREAD

**Issue by Kaiyuan** [istoreos/istoreos#978]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
多 WAN 口联网出现路由器端口不能开放和转发

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [ √] 没有类似的issue

### (1) 具体问题

A：我两条宽带加上 TR069，3个 Wan 口，当电信联通同时联网时候会出现无法开放端口和端口转发。当断开联通网络之后才能正常访问我需要开放的端口

### (2) 路由器型号和固件版本

A：3865u   iStoreOS 21.02.3 2023042111

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
你是手动配置多拨的吗，有没有把配置的接口都加入防火墙的wan区域？

**Comment by jjm2473** [comment]
istore上架了一个多账户多拨的插件，你可以试试

**Comment by Kaiyuan** [comment]
> 你是手动配置多拨的吗，有没有把配置的接口都加入防火墙的wan区域？

我不是多拨，时多WAN，两条宽带。防火墙都设置 WAN的。

**Comment by jjm2473** [comment]
一样的，多拨也可以设置只拨一个，你用多账号功能就行了，不要这么死板

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2742/1
