### ISSUE TITLE
请问要如何启用巨型帧

### ISSUE THREAD

**Issue by ArtomYuan** [istoreos/istoreos#979]
请问要如何启用巨型帧，在网上没找到相关教程和文档

路由器型号和固件版本
Dell Inc. PowerEdge R620
iStoreOS 22.03.5 2023081110 / LuCI istoreos-22.03 branch git-23.103.23275-0193674

**Comment by jjm2473** [comment]
听说只要改MTU就行了，打开后台“网络”-“接口”页面，然后“设备”选项卡，在需要修改的网卡上点“配置”：
<img width="1112" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/b183fcd2-c159-4812-a9cf-0d0180b626e5">

然后就有MTU的选项了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2741/1
