### ISSUE TITLE
iStoreOS 是否支持 IPv6 Firewall 的 MSS Clamping?

### ISSUE THREAD

**Issue by peterkimliao** [istoreos/istoreos#980]
一般像是 RouterOS 会有这样的选项，确保连接上来的 Client MTU 和 MSS 能正确被修改，详情可参照:
https://www.nuomiphp.com/t/6138d57384d0401afa7dfcaf.html

请问 iStoreOS 也支持吗?

**Comment by jjm2473** [comment]
这个可以去openwrt那边问问，都是一样的。我估计是有的，这是ipv6防火墙的其中几条规则：
<img width="1204" alt="image" src="https://github.com/istoreos/istoreos/assets/3896703/483c896d-30de-43a8-90c9-e4b850902f15">

**Comment by jjm2473** [comment]
相应的开关在 网络-防火墙 页面里，默认WAN口开了MSS 钳制，自己点下区域的编辑按钮就能看到了。

**Comment by jjm2473** [comment]
如果你说的东西不是这个，那就不了解了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2740/1
