### ISSUE TITLE
为什么istoreos会拦截tcp

### ISSUE THREAD

**Issue by jasonnmy** [istoreos/istoreos#981]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
istoreso做旁路由出现了tcp被拦截情况，外网端口转发无法到内网，抓包看了下，tcp请求来，电脑返回了，但是到旁路由被中断了，发送端没收到回复，然后一直tcp retransmission。把旁路由换其他系统没问题，直连主路由也没问题

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本
iStoreOS 21.02.3, 2023022415 和22.03.5 2023082509
软路由
A：

### (3) 详细日志和/或截图

A：

**Comment by jasonnmy** [comment]
![image](https://github.com/istoreos/istoreos/assets/10269349/86379157-e7f8-4e66-bc26-ab748b01917c)

**Comment by jjm2473** [comment]
是否使用了小米路由器作为AP？

**Comment by jasonnmy** [comment]
查到原因了防火墙的问题，我之前没问题，突然升级某个版本后出现，好像是开了IP 动态伪装

**Comment by jjm2473** [comment]
按道理来说，做旁路由的话，根本就不会有流量经过了，因为主路由会直接往内网设备发。

**Comment by jjm2473** [comment]
你的主路由的端口转发是怎么做的，DMZ到旁路由吗，还是直接转发到目标内网设备

**Comment by jjm2473** [comment]
如果不开lan口的IP动态伪装的话，旁路由的docker容器没法上网

**Comment by jasonnmy** [comment]
爱快的直接端口转发，没开dmz

**Comment by jjm2473** [comment]
那理论上流量都不需要旁路由转发了啊，你抓包看到的tcp发送失败的目的ip是什么

**Comment by jjm2473** [comment]
爱快的端口转发是没改源ip吗？

**Comment by jasonnmy** [comment]
什么源ip

**Comment by jjm2473** [comment]
端口转发不就是NAT吗，至少目标ip要改吧，那源ip改了吗，如果源ip改成了爱快的ip，那内网设备回复的时候不就直接往爱快发了吗，怎么也不会经过旁路由

**Comment by jasonnmy** [comment]
ip为爱快和旁路由都能转发，其他设备就不行

**Comment by jjm2473** [comment]
所以说看看抓包的失败tcp的目的ip是什么啊

**Comment by jasonnmy** [comment]
等会

**Comment by jasonnmy** [comment]
![image](https://github.com/istoreos/istoreos/assets/10269349/103347f5-9bb2-47cd-8687-96ca261f9e8d)

**Comment by jjm2473** [comment]
为什么你的电脑收到的源ip不是局域网ip？正常的端口转发会把源ip也改掉，你还是看看爱快的端口转发是不是有什么特殊设置吧

**Comment by jasonnmy** [comment]
![image](https://github.com/istoreos/istoreos/assets/10269349/fab7c17b-e1e2-45c8-9c06-b41335b6d334)

**Comment by jjm2473** [comment]
参考下这个 https://bbs.ikuai8.com/thread-139586-1-1.html ，可能爱快的端口转发不是通常的使用CT维护连接

**Comment by jasonnmy** [comment]
可能爱快不一样吧

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2739/1
