### ISSUE TITLE
旁路由模式下，用IPV6外网访问不了web页面

### ISSUE THREAD

**Issue by royseaver** [istoreos/istoreos#983]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：设置旁路由模式，光猫拨号，主路由是TPLINK 设置IPV6桥模式，istoreos可以获取到IPV6，但外网就是访问不了。
自己windows电脑可以使用电脑获取的IPV6地址连接远程桌面和建的Jellyfin页面。
istoreos也用uhttpd设置管理页面端口为8080，也不行，不知道如何解决这个问题

### (2) 路由器型号和固件版本

A：x86工控机，单网口，iStoreOS 22.03.5 2023082509

### (3) 详细日志和/或截图

A：

**Comment by jjm2473** [comment]
需要主路由修改防火墙配置，跟旁路由无关

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2737/1
