### ISSUE TITLE
挂载点重启后失效

### ISSUE THREAD

**Issue by GFDCGFC** [istoreos/istoreos#988]
固件版本：iStoreOS 22.03.5 2023090112 / LuCI istoreos-22.03 branch git-23.103.23275-0193674
问题：挂载点设置好重启就会失效，要重新设置才行

**Comment by jjm2473** [comment]
是不是硬盘初始化太慢？系统-杂项设置，里面有个启动时等待硬盘的功能，打开试试

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2733/1
