### ISSUE TITLE
求助大佬VPN连接不上的问题

### ISSUE THREAD

**Issue by jackzhum** [istoreos/istoreos#989]
家里R2S刷了IStoreOS，采用PPPoE方式拨号上网，其它都正常，但是工作用的VPN连不上了，
提示：远程访问错误 619 不能建立到远程计算机的连接，因此用于此连接的端口已关闭

不知道是不是防火墙设置的不正确，也设置过端口转发，但是没有用，还请大佬指点下。

iStoreOS版本：iStoreOS 22.03.4

**Comment by jackzhum** [comment]
不知道是不是因为不支持PPTP协议的问题？

**Comment by jjm2473** [comment]
你开了pptp服务了吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2732/1
