### ISSUE TITLE
wan口无法拨号

### ISSUE THREAD

**Issue by vay1314** [istoreos/istoreos#992]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
为避免重复issue，请先搜索issue，确认没有类似issue再提交新issue；
注意搜索时**包括已关闭**的issue（删掉搜索框的的“is:open”条件）；

Q：是否用关键词搜索了issue? (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：直接保留配置升级最新版本wan口无法拨号，回退旧版本测试不保留配置升级也是无法拨号。回退旧版本正常
上传的日志为不保留配置升级，进入系统后wan接口重新切换pppoe协议，保存并应用的日志。

### (2) 路由器型号和固件版本

A：目前版本：iStoreOS 21.02.3 2023060914

### (3) 详细日志和/或截图
[log - 副本.txt](https://github.com/istoreos/istoreos/files/12546629/log.-.txt)

A：

**Comment by vay1314** [comment]
查明原因为新版删除了r8125驱动原因

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2729/1
