### ISSUE TITLE
强烈建议增加 常用usb 无线网卡驱动

### ISSUE THREAD

**Issue by DONGYUSEN** [istoreos/istoreos#993]
强烈建议增加 常用usb 无线网卡驱动

**Comment by hx801217** [comment]
USB网卡也没啊，微软surface 1663,8153b芯片，也没驱动

**Comment by jjm2473** [comment]
提供下驱动列表。

**Comment by jjm2473** [comment]
@hx801217 8153应该有吧，驱动名称是8152

**Comment by hx801217** [comment]
8152驱动不起来，不停报错，是微软surface的1663网卡，8153am芯片

**Comment by hx801217** [comment]
以前用fw867大大的lede是正常的

**Comment by hx801217** [comment]
@jjm2473 微软surface的1663网卡，8153am芯片，8152驱动没法用，不停报错，21.02和22.03均不能驱动

**Comment by RSHUEN-KW** [comment]
请问我应该去哪里查询目前Istoreos 系统支持的所有类型的网卡？

**Comment by jjm2473** [comment]
lsmod 可以列出所有驱动。如果是x86或者rk33xx，rpi4等机型，还能直接在软件包那边安装驱动。至于一个驱动支持那些网卡，那就不知道了

**Comment by jjm2473** [comment]
@hx801217  你说的“微软surface的1663网卡”确定是rtl8153方案的吗？是不是千兆网卡？执行`lspci -nnk`看看id是什么

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2728/1
