### ISSUE TITLE
lan 下面NAT 的问题

### ISSUE THREAD

**Issue by jamskl** [istoreos/istoreos#995]
最新版本的固件
配置防火墙NAT 规则时 不生效，我希望能转换多个LAN 下面的网段

**Comment by jjm2473** [comment]
什么意思，端口转发吗？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2727/1
