### ISSUE TITLE
istore系统，测速腰斩，无线更拉跨，换了esir瞬间清爽，好好弄弄吧

### ISSUE THREAD

**Issue by xuehuaxuyu** [istoreos/istoreos#998]
X86固件，挺好的一个系统，提升网速才是核心，网速都达不到，其他的花活等于白费。

**Comment by wangweiweiwei** [comment]
项目地址发一下呢

**Comment by jjm2473** [comment]
可能因为是0908版本的内存异常占用，升级最新固件就行了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2724/1
